[Pandas Data Validation](https://www.w3resource.com/python-exercises/pandas/pandas-data-validation.php)

In [1]:
import pandas as pd
import numpy as np

<div class="alert alert-warning">

**1. Checking Missing Values in a DataFrame**

**Write a Pandas program to check for missing values in a DataFrame.**

</div>

In [2]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1701,134,4,28.77,0.12,101.2704,7,East,Credit Card,...,1,56,Male,Clothing,4.1,Not Returned,Positive,9.28,nan,3.4
1,2023-01-02,1901,193,7,64.45,0.03,437.6155,3,East,Online,...,5,18,Male,Electronics,3.2,Returned,Negative,14.91,WELCOME5,1.8
2,2023-01-03,1324,136,8,77.78,0.23,479.1248,4,East,Credit Card,...,3,49,Female,Food,2.8,Returned,Neutral,5.40,WELCOME5,NaN
3,2023-01-04,1726,102,6,15.16,0.22,70.9488,6,South,Cash,...,3,61,Other,Books,4.5,Not Returned,Neutral,13.28,FREESHIP,NaN
4,2023-01-05,1572,168,8,60.76,0.20,388.8640,8,South,Credit Card,...,5,26,Male,Electronics,4.3,Returned,Neutral,NaN,nan,NaN
5,2023-01-06,1491,100,9,39.84,0.23,276.0912,2,South,Credit Card,...,3,64,Other,Clothing,3.2,Not Returned,Positive,9.95,SAVE10,NaN
6,2023-01-07,1981,102,2,86.59,0.11,154.1302,4,West,Cash,...,6,52,Male,Clothing,2.3,Not Returned,Negative,NaN,nan,4.6
7,2023-01-08,1720,152,5,42.63,0.08,196.0980,4,South,Credit Card,...,6,56,Other,Food,2.2,Returned,Positive,NaN,SAVE10,2.6
8,2023-01-09,1320,190,6,22.35,0.22,104.5980,7,North,Credit Card,...,3,47,Male,Food,3.1,Returned,Neutral,18.00,FREESHIP,1.1
9,2023-01-10,1144,189,5,98.38,0.21,388.6010,7,South,Credit Card,...,6,69,Female,Food,4.9,Returned,Positive,NaN,SAVE10,NaN
10,2023-01-11,1394,125,4,68.67,0.12,241.7184,1,West,Cash,...,1,55,Male,Clothing,4.1,Not Returned,Negative,13.21,FREESHIP,NaN
11,2023-01-12,1610,130,9,70.17,0.23,486.2781,9,West,Online,...,3,57,Male,Clothing,4.0,Returned,Positive,10.98,nan,3.4
12,2023-01-13,1795,127,6,31.81,0.03,185.1342,9,North,Credit Card,...,2,44,Other,Clothing,3.6,Not Returned,Positive,11.98,nan,4.3
13,2023-01-14,1905,138,6,76.83,0.10,414.8820,4,North,Online,...,6,25,Male,Books,2.0,Returned,Negative,14.54,SAVE10,2.5
14,2023-01-15,1909,173,6,28.44,0.24,129.6864,7,West,Cash,...,2,65,Male,Clothing,2.3,Not Returned,Negative,9.12,WELCOME5,1.9
15,2023-01-16,1133,135,7,27.82,0.28,140.2128,1,North,Online,...,6,49,Male,Food,3.5,Not Returned,Negative,10.11,nan,5.0
16,2023-01-17,1033,127,9,78.27,0.07,655.1199,5,East,Cash,...,2,55,Female,Food,4.3,Returned,Neutral,8.84,nan,NaN
17,2023-01-18,1113,172,2,31.14,0.16,52.3152,9,North,Cash,...,5,32,Other,Food,2.6,Not Returned,Positive,7.68,SAVE10,NaN
18,2023-01-19,1221,130,1,87.24,0.24,66.3024,6,West,Cash,...,5,55,Female,Clothing,2.5,Returned,Negative,NaN,nan,NaN
19,2023-01-20,1000,159,8,80.23,0.07,596.9112,2,North,Cash,...,5,45,Male,Food,1.9,Returned,Positive,8.40,nan,NaN
20,2023-01-21,1813,187,3,34.84,0.24,79.4352,1,South,Credit Card,...,4,33,Other,Electronics,2.4,Returned,Positive,13.07,nan,3.4
21,2023-01-22,1072,103,1,15.05,0.28,10.8360,3,East,Credit Card,...,1,25,Male,Books,4.9,Returned,Neutral,18.33,FREESHIP,NaN
22,2023-01-23,1694,111,4,30.03,0.09,109.3092,5,West,Credit Card,...,5,39,Other,Books,2.2,Not Returned,Negative,NaN,WELCOME5,4.1
23,2023-01-24,1468,104,7,77.23,0.09,491.9551,3,North,Credit Card,...,4,47,Male,Clothing,1.4,Returned,Positive,11.50,nan,4.9
24,2023-01-25,1162,100,5,34.11,0.24,129.6180,1,South,Credit Card,...,6,19,Male,Electronics,3.6,Returned,Positive,13.47,SAVE10,NaN
25,2023-01-26,1759,147,8,22.83,0.08,168.0288,1,West,Credit Card,...,5,19,Other,Food,2.0,Not Returned,Negative,19.87,FREESHIP,2.9
26,2023-01-27,1256,104,2,84.82,0.16,142.4976,8,West,Credit Card,...,1,28,Male,Food,3.8,Not Returned,Neutral,9.25,WELCOME5,3.9
27,2023-01-28,1479,144,4,66.71,0.27,194.7932,6,North,Online,...,2,35,Female,Books,1.6,Returned,Positive,11.02,FREESHIP,2.5
28,2023-01-29,1247,118,3,18.29,0.17,45.5421,1,South,Online,...,5,33,Male,Clothing,2.5,Returned,Negative,14.57,FREESHIP,4.8
29,2023-01-30,1962,147,4,67.82,0.03,263.1416,5,North,Credit Card,...,4,47,Male,Clothing,3.8,Not Returned,Negative,NaN,nan,NaN
30,2023-01-31,1851,183,3,83.84,0.09,228.8832,3,North,Credit Card,...,5,19,Female,Clothing,2.1,Returned,Neutral,18.24,SAVE10,3.9
31,2023-02-01,1794,175,8,60.12,0.00,480.9600,9,East,Cash,...,6,58,Male,Electronics,1.8,Returned,Neutral,10.70,WELCOME5,2.1
32,2023-02-02,1953,108,6,23.50,0.29,100.1100,9,West,Online,...,1,32,Female,Clothing,1.3,Not Returned,Positive,12.92,nan,1.6
33,2023-02-03,1971,140,2,25.40,0.18,41.6560,9,West,Credit Card,...,4,18,Other,Electronics,2.1,Not Returned,Negative,16.39,FREESHIP,4.4
34,2023-02-04,1506,192,3,61.03,0.13,159.2883,5,South,Credit Card,...,2,33,Other,Electronics,1.8,Not Returned,Negative,18.04,FREESHIP,4.4

<div class="alert alert-success">

**Solution 01:**
</div>

In [3]:
# 1. Checking Missing Values in a DataFrame
# Write a Pandas program to check for missing values in a DataFrame.

# Check for missing values
missing_values = df.isnull().sum()
missing_values[missing_values > 0]

shipping_cost       7
delivery_rating    13
dtype: int64

<div class="alert alert-warning">

**2. Ensuring Consistent Data Types of All Columns**

**Write a Pandas program to check and ensure that the data types of all columns are consistent.**

</div>

In [4]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1682,193,8,58.15,0.17,386.1160,1,South,Cash,...,6,25,Male,Books,1.2,Returned,Negative,17.48,nan,3.3
1,2023-01-02,1692,190,6,19.43,0.22,90.9324,6,West,Credit Card,...,2,36,Other,Books,3.8,Not Returned,Negative,5.87,nan,1.6
2,2023-01-03,1974,172,5,50.32,0.16,211.3440,7,South,Cash,...,6,38,Female,Food,2.2,Returned,Negative,8.27,FREESHIP,1.1
3,2023-01-04,1458,134,3,62.13,0.19,150.9759,9,North,Credit Card,...,6,33,Male,Books,2.0,Returned,Negative,17.48,WELCOME5,NaN
4,2023-01-05,1390,198,3,98.34,0.26,218.3148,9,South,Credit Card,...,6,21,Male,Food,3.0,Returned,Negative,9.32,WELCOME5,1.3
5,2023-01-06,1131,117,9,78.59,0.16,594.1404,7,North,Online,...,6,57,Other,Electronics,2.2,Not Returned,Positive,NaN,FREESHIP,4.9
6,2023-01-07,1499,143,6,86.45,0.09,472.0170,2,North,Credit Card,...,4,56,Male,Books,5.0,Returned,Positive,6.31,nan,NaN
7,2023-01-08,1626,130,6,20.23,0.22,94.6764,4,West,Online,...,3,24,Female,Electronics,3.6,Not Returned,Negative,10.11,SAVE10,3.0
8,2023-01-09,1129,134,6,39.85,0.17,198.4530,6,North,Credit Card,...,2,19,Female,Books,3.1,Returned,Neutral,16.63,FREESHIP,NaN
9,2023-01-10,1314,139,3,54.57,0.03,158.7987,7,South,Cash,...,3,65,Other,Electronics,5.0,Returned,Positive,17.69,WELCOME5,2.9
10,2023-01-11,1291,191,3,65.29,0.30,137.1090,2,South,Online,...,5,55,Female,Books,4.9,Not Returned,Negative,13.92,WELCOME5,4.3
11,2023-01-12,1531,144,8,51.04,0.29,289.9072,8,West,Credit Card,...,3,61,Male,Clothing,1.4,Not Returned,Negative,12.79,SAVE10,NaN
12,2023-01-13,1708,158,3,41.58,0.26,92.3076,8,West,Online,...,4,41,Female,Books,3.1,Returned,Positive,NaN,FREESHIP,3.8
13,2023-01-14,1258,168,8,15.88,0.21,100.3616,4,North,Online,...,2,57,Male,Food,3.7,Returned,Negative,16.44,WELCOME5,3.8
14,2023-01-15,1215,182,2,66.95,0.09,121.8490,8,South,Credit Card,...,6,21,Female,Books,4.9,Returned,Positive,8.74,nan,4.8
15,2023-01-16,1319,175,6,84.17,0.13,439.3674,5,West,Cash,...,2,25,Male,Books,3.9,Returned,Negative,9.45,nan,NaN
16,2023-01-17,1325,180,6,84.41,0.30,354.5220,9,East,Cash,...,5,45,Other,Electronics,4.0,Not Returned,Neutral,13.11,nan,2.1
17,2023-01-18,1996,110,8,12.90,0.09,93.9120,1,North,Online,...,2,43,Female,Electronics,4.9,Not Returned,Neutral,NaN,nan,4.8
18,2023-01-19,1256,108,7,32.28,0.29,160.4316,4,West,Online,...,5,24,Female,Food,4.7,Not Returned,Negative,11.48,FREESHIP,NaN
19,2023-01-20,1963,177,9,54.46,0.00,490.1400,2,South,Cash,...,5,38,Other,Electronics,2.4,Returned,Neutral,9.76,FREESHIP,NaN
20,2023-01-21,1764,187,5,31.09,0.08,143.0140,3,East,Credit Card,...,2,19,Male,Clothing,2.0,Returned,Neutral,11.17,SAVE10,4.5
21,2023-01-22,1049,143,2,31.72,0.02,62.1712,1,South,Online,...,4,19,Female,Electronics,3.8,Not Returned,Negative,5.69,nan,NaN
22,2023-01-23,1475,102,8,52.06,0.00,416.4800,6,South,Cash,...,5,43,Female,Electronics,1.3,Not Returned,Neutral,16.67,nan,NaN
23,2023-01-24,1370,107,2,38.37,0.02,75.2052,2,East,Online,...,2,25,Other,Clothing,5.0,Returned,Neutral,19.46,SAVE10,NaN
24,2023-01-25,1032,136,7,78.06,0.21,431.6718,1,North,Cash,...,2,41,Female,Books,2.6,Not Returned,Negative,NaN,FREESHIP,2.8
25,2023-01-26,1053,199,9,23.83,0.07,199.4571,6,North,Online,...,2,35,Male,Clothing,2.2,Not Returned,Neutral,18.40,SAVE10,4.8
26,2023-01-27,1407,198,3,81.67,0.11,218.0589,5,West,Credit Card,...,3,42,Female,Food,2.7,Returned,Positive,9.72,SAVE10,2.9
27,2023-01-28,1219,129,7,45.50,0.03,308.9450,5,South,Cash,...,1,30,Male,Clothing,1.1,Not Returned,Positive,18.96,SAVE10,4.5
28,2023-01-29,1329,183,6,15.48,0.27,67.8024,4,West,Credit Card,...,6,19,Male,Food,2.0,Not Returned,Positive,17.84,nan,4.2
29,2023-01-30,1343,110,5,94.71,0.10,426.1950,6,West,Cash,...,4,26,Male,Food,1.6,Returned,Neutral,7.33,nan,NaN
30,2023-01-31,1964,127,7,52.54,0.04,353.0688,2,South,Online,...,5,50,Male,Books,1.8,Not Returned,Negative,NaN,nan,3.8
31,2023-02-01,1643,179,6,33.02,0.21,156.5148,8,West,Credit Card,...,1,44,Other,Clothing,4.3,Not Returned,Negative,19.42,WELCOME5,NaN
32,2023-02-02,1341,164,6,86.23,0.06,486.3372,1,North,Cash,...,5,31,Female,Food,3.2,Returned,Positive,14.47,SAVE10,1.4
33,2023-02-03,1786,161,6,95.00,0.04,547.2000,5,West,Cash,...,2,68,Male,Electronics,3.7,Not Returned,Negative,NaN,WELCOME5,2.2
34,2023-02-04,1207,187,6,80.21,0.28,346.5072,7,East,Credit Card,...,5,57,Female,Books,2.3,Returned,Positive,7.03,nan,1.7

<div class="alert alert-success">

**Solution 02:**
</div>

In [5]:
# 2. Ensuring Consistent Data Types of All Columns
# Write a Pandas program to check and ensure that the data types of all columns are consistent.

# Check data types
data_types = df.dtypes
data_types

date                datetime64[ns]
customer_id                  int64
product_id                   int64
quantity                     int64
price                      float64
discount                   float64
revenue                    float64
store_id                     int64
region                      object
payment_method              object
is_member                     bool
delivery_days                int64
customer_age                 int64
gender                      object
product_category            object
rating                     float64
return_status               object
feedback                    object
shipping_cost              float64
coupon_code                 object
delivery_rating            float64
dtype: object