[Pandas Data Validation](https://www.w3resource.com/python-exercises/pandas/pandas-data-validation.php)

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

<div class="alert alert-warning">

**1. Checking Missing Values in a DataFrame**

**Write a Pandas program to check for missing values in a DataFrame.**

</div>

In [2]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1189,172,6,62.65,0.04,360.8640,3,West,Cash,True,4,69,Female,Clothing,1.3,Returned,Negative,19.44,nan,4.4
1,2023-01-02,1290,163,8,49.22,0.11,350.4464,3,East,Credit Card,False,1,34,Female,Books,4.9,Not Returned,Positive,11.07,SAVE10,3.9
2,2023-01-03,1822,166,8,64.10,0.20,410.2400,2,North,Online,False,2,34,Other,Electronics,3.2,Not Returned,Neutral,16.02,nan,2.6
3,2023-01-04,1498,183,1,23.58,0.12,20.7504,4,East,Online,False,3,24,Other,Clothing,4.1,Returned,Positive,NaN,nan,2.2
4,2023-01-05,1611,138,1,91.52,0.14,78.7072,1,East,Credit Card,False,3,34,Female,Electronics,4.8,Not Returned,Positive,17.43,FREESHIP,2.1
5,2023-01-06,1536,192,4,25.42,0.01,100.6632,5,East,Online,False,2,27,Female,Books,3.2,Returned,Neutral,16.43,nan,1.6
6,2023-01-07,1633,151,1,84.19,0.22,65.6682,7,East,Cash,True,2,31,Other,Clothing,3.6,Not Returned,Negative,7.79,FREESHIP,NaN
7,2023-01-08,1046,139,1,21.42,0.25,16.0650,4,West,Cash,False,1,57,Other,Clothing,3.3,Returned,Neutral,12.52,nan,3.4
8,2023-01-09,1625,129,2,55.80,0.10,100.4400,3,East,Credit Card,False,2,46,Male,Clothing,3.8,Not Returned,Positive,18.46,FREESHIP,4.2
9,2023-01-10,1153,135,3,41.29,0.12,109.0056,3,East,Online,False,2,50,Other,Food,1.1,Not Returned,Positive,NaN,nan,NaN
10,2023-01-11,1491,181,3,56.59,0.05,161.2815,8,North,Cash,False,2,21,Female,Clothing,3.3,Returned,Positive,7.12,nan,3.6
11,2023-01-12,1137,144,4,27.29,0.12,96.0608,7,East,Cash,True,3,43,Male,Food,4.9,Not Returned,Positive,19.48,nan,3.0
12,2023-01-13,1351,128,6,42.40,0.29,180.6240,1,East,Credit Card,True,2,19,Male,Clothing,3.0,Not Returned,Neutral,7.84,FREESHIP,NaN
13,2023-01-14,1629,124,4,35.76,0.07,133.0272,9,North,Credit Card,False,2,35,Male,Clothing,3.9,Returned,Positive,7.16,nan,3.9
14,2023-01-15,1985,184,3,52.59,0.11,140.4153,1,East,Credit Card,False,1,60,Male,Electronics,1.4,Returned,Negative,10.82,FREESHIP,4.2
15,2023-01-16,1467,110,9,47.41,0.30,298.6830,1,North,Cash,True,5,37,Male,Electronics,3.6,Not Returned,Neutral,9.08,FREESHIP,NaN
16,2023-01-17,1077,158,9,16.71,0.00,150.3900,9,West,Cash,False,4,49,Other,Books,2.4,Returned,Negative,NaN,FREESHIP,1.1
17,2023-01-18,1606,138,9,96.89,0.01,863.2899,3,South,Credit Card,False,5,35,Other,Books,2.3,Not Returned,Negative,13.99,SAVE10,1.0
18,2023-01-19,1938,136,7,58.85,0.11,366.6355,2,West,Credit Card,True,5,52,Male,Clothing,2.6,Not Returned,Negative,11.77,WELCOME5,3.1
19,2023-01-20,1052,102,6,34.95,0.04,201.3120,6,North,Credit Card,False,6,52,Female,Books,4.3,Not Returned,Neutral,6.89,FREESHIP,4.5
20,2023-01-21,1897,130,4,39.02,0.08,143.5936,8,East,Cash,False,5,22,Other,Food,4.4,Not Returned,Positive,14.48,nan,NaN
21,2023-01-22,1393,164,6,43.49,0.16,219.1896,3,West,Cash,True,6,43,Female,Books,3.0,Returned,Neutral,7.81,FREESHIP,NaN
22,2023-01-23,1321,175,4,47.42,0.28,136.5696,4,South,Online,False,3,63,Male,Food,1.3,Returned,Negative,NaN,FREESHIP,4.0
23,2023-01-24,1595,162,9,27.65,0.01,246.3615,4,South,Cash,False,2,43,Female,Food,4.3,Returned,Positive,NaN,FREESHIP,NaN
24,2023-01-25,1239,100,2,19.77,0.10,35.5860,1,East,Cash,False,4,64,Other,Electronics,3.0,Not Returned,Positive,13.02,FREESHIP,1.5
25,2023-01-26,1950,146,3,58.61,0.11,156.4887,1,East,Cash,True,2,67,Male,Clothing,5.0,Not Returned,Neutral,6.70,WELCOME5,NaN
26,2023-01-27,1017,126,9,12.58,0.19,91.7082,9,North,Online,False,2,30,Female,Clothing,3.7,Not Returned,Positive,19.93,nan,NaN
27,2023-01-28,1665,115,3,82.76,0.28,178.7616,3,East,Credit Card,True,2,63,Female,Electronics,2.9,Returned,Negative,6.03,FREESHIP,NaN
28,2023-01-29,1799,146,6,54.43,0.19,264.5298,6,East,Online,False,4,22,Female,Electronics,2.8,Returned,Negative,17.05,SAVE10,1.3
29,2023-01-30,1183,102,8,95.17,0.27,555.7928,6,West,Credit Card,True,3,41,Other,Electronics,4.0,Returned,Negative,NaN,nan,1.3
30,2023-01-31,1536,151,6,20.28,0.20,97.3440,6,East,Cash,False,2,46,Male,Electronics,3.9,Not Returned,Positive,14.47,WELCOME5,1.9
31,2023-02-01,1482,112,7,61.37,0.14,369.4474,7,South,Online,True,1,43,Male,Food,2.9,Returned,Positive,16.45,nan,2.2
32,2023-02-02,1629,187,3,11.90,0.10,32.1300,2,East,Online,False,3,40,Female,Electronics,2.2,Returned,Negative,18.78,nan,1.2
33,2023-02-03,1470,103,9,75.74,0.08,627.1272,4,East,Online,True,6,21,Male,Clothing,4.3,Returned,Negative,13.25,nan,3.7
34,2023-02-04,1167,162,7,47.62,0.04,320.0064,3,East,Credit Card,True,5,50,Other,Clothing,2.6,Returned,Positive,18.82,WELCOME5,3.3

<div class="alert alert-success">

**Solution 01:**
</div>

In [3]:
# 1. Checking Missing Values in a DataFrame
# Write a Pandas program to check for missing values in a DataFrame.

# Check for missing values
missing_values = df.isnull().sum()
missing_values[missing_values > 0]

shipping_cost       6
delivery_rating    10
dtype: int64

<div class="alert alert-warning">

**2. Ensuring Consistent Data Types of All Columns**

**Write a Pandas program to check and ensure that the data types of all columns are consistent.**

</div>

In [4]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1462,160,4,83.23,0.24,253.0192,1,West,Online,True,6,41,Female,Books,1.4,Returned,Neutral,NaN,SAVE10,2.1
1,2023-01-02,1986,155,4,24.48,0.07,91.0656,8,South,Cash,False,3,31,Male,Electronics,3.4,Not Returned,Positive,NaN,SAVE10,3.6
2,2023-01-03,1764,135,3,87.12,0.08,240.4512,4,South,Online,True,3,47,Other,Clothing,2.3,Not Returned,Negative,17.56,FREESHIP,3.1
3,2023-01-04,1251,106,7,92.08,0.15,547.8760,1,West,Online,True,1,25,Male,Electronics,4.4,Returned,Negative,11.61,FREESHIP,NaN
4,2023-01-05,1064,159,9,85.36,0.19,622.2744,6,North,Credit Card,False,5,69,Male,Electronics,3.7,Returned,Negative,5.29,SAVE10,4.8
5,2023-01-06,1110,122,4,87.57,0.00,350.2800,4,North,Cash,True,4,39,Other,Food,3.9,Not Returned,Neutral,18.50,nan,3.7
6,2023-01-07,1123,199,4,20.62,0.29,58.5608,9,South,Credit Card,False,6,69,Male,Food,4.2,Returned,Negative,15.77,SAVE10,NaN
7,2023-01-08,1746,147,7,40.25,0.10,253.5750,2,North,Credit Card,True,6,54,Female,Books,1.1,Returned,Positive,18.64,WELCOME5,3.0
8,2023-01-09,1598,168,1,96.10,0.07,89.3730,7,North,Online,False,2,54,Male,Food,2.6,Not Returned,Negative,14.51,WELCOME5,NaN
9,2023-01-10,1497,102,6,88.64,0.14,457.3824,2,East,Online,True,3,33,Male,Food,4.9,Not Returned,Neutral,17.97,FREESHIP,3.1
10,2023-01-11,1295,116,8,33.23,0.03,257.8648,4,North,Cash,True,2,67,Other,Books,1.5,Not Returned,Positive,19.04,WELCOME5,NaN
11,2023-01-12,1470,102,1,73.77,0.24,56.0652,7,South,Cash,False,5,65,Male,Food,2.6,Not Returned,Negative,16.99,nan,4.2
12,2023-01-13,1087,157,9,11.51,0.01,102.5541,6,South,Cash,False,1,19,Female,Books,4.1,Returned,Negative,11.52,WELCOME5,NaN
13,2023-01-14,1709,142,7,26.21,0.29,130.2637,1,South,Cash,True,5,68,Female,Food,1.9,Not Returned,Negative,7.39,SAVE10,NaN
14,2023-01-15,1845,164,9,33.02,0.23,228.8286,3,South,Credit Card,True,1,69,Other,Food,1.1,Not Returned,Neutral,9.71,SAVE10,3.1
15,2023-01-16,1779,131,7,35.75,0.13,217.7175,5,West,Credit Card,False,1,64,Other,Electronics,1.6,Returned,Negative,NaN,WELCOME5,3.1
16,2023-01-17,1380,112,9,56.04,0.06,474.0984,1,East,Credit Card,False,5,29,Male,Clothing,3.1,Not Returned,Positive,6.48,SAVE10,1.5
17,2023-01-18,1227,180,8,32.28,0.27,188.5152,7,North,Cash,True,4,67,Male,Electronics,5.0,Not Returned,Negative,13.52,nan,1.5
18,2023-01-19,1391,124,6,19.65,0.30,82.5300,4,West,Online,True,2,44,Male,Electronics,2.5,Returned,Negative,17.39,WELCOME5,4.5
19,2023-01-20,1291,191,2,57.19,0.25,85.7850,6,South,Online,False,5,23,Male,Books,2.7,Not Returned,Neutral,10.29,SAVE10,1.1
20,2023-01-21,1628,138,3,14.37,0.03,41.8167,6,West,Online,False,5,28,Other,Food,3.3,Returned,Positive,8.81,nan,3.3
21,2023-01-22,1120,125,9,38.19,0.13,299.0277,8,East,Cash,True,5,33,Female,Books,4.9,Not Returned,Neutral,7.51,WELCOME5,4.0
22,2023-01-23,1336,105,2,63.61,0.17,105.5926,4,West,Cash,True,2,35,Female,Books,2.6,Returned,Negative,15.72,WELCOME5,4.3
23,2023-01-24,1229,160,4,82.66,0.24,251.2864,4,East,Credit Card,True,6,45,Male,Clothing,3.4,Returned,Negative,13.39,SAVE10,NaN
24,2023-01-25,1247,198,1,61.27,0.01,60.6573,8,North,Cash,True,1,45,Other,Books,1.0,Returned,Positive,12.38,FREESHIP,1.9
25,2023-01-26,1536,182,1,96.66,0.29,68.6286,7,North,Online,False,5,37,Male,Clothing,3.8,Not Returned,Neutral,15.60,SAVE10,1.9
26,2023-01-27,1087,160,2,78.87,0.01,156.1626,6,South,Credit Card,False,2,18,Female,Books,3.0,Returned,Positive,17.16,FREESHIP,3.4
27,2023-01-28,1750,155,9,96.06,0.03,838.6038,2,North,Online,True,4,54,Other,Electronics,1.5,Returned,Neutral,10.97,FREESHIP,2.4
28,2023-01-29,1986,120,4,48.46,0.06,182.2096,5,East,Credit Card,True,2,28,Male,Electronics,3.8,Not Returned,Neutral,6.69,WELCOME5,NaN
29,2023-01-30,1549,191,4,24.18,0.14,83.1792,5,East,Cash,False,6,43,Female,Electronics,1.2,Returned,Negative,9.62,FREESHIP,1.6
30,2023-01-31,1040,118,2,46.69,0.13,81.2406,9,North,Online,True,3,62,Female,Electronics,1.7,Returned,Neutral,18.02,SAVE10,1.6
31,2023-02-01,1335,143,3,26.83,0.17,66.8067,2,East,Credit Card,True,3,48,Other,Books,4.3,Returned,Neutral,9.90,SAVE10,2.0
32,2023-02-02,1253,137,2,18.06,0.28,26.0064,9,West,Credit Card,False,1,33,Other,Books,3.6,Returned,Positive,12.25,FREESHIP,1.5
33,2023-02-03,1906,101,4,23.51,0.09,85.5764,2,East,Cash,True,6,26,Male,Books,2.4,Not Returned,Negative,10.57,nan,3.7
34,2023-02-04,1364,179,4,85.90,0.03,333.2920,1,North,Credit Card,False,5,23,Male,Food,2.1,Not Returned,Negative,NaN,WELCOME5,4.8

<div class="alert alert-success">

**Solution 02:**
</div>

In [5]:
# 2. Ensuring Consistent Data Types of All Columns
# Write a Pandas program to check and ensure that the data types of all columns are consistent.

# Check data types
data_types = df.dtypes
data_types

date                datetime64[ns]
customer_id                  int64
product_id                   int64
quantity                     int64
price                      float64
discount                   float64
revenue                    float64
store_id                     int64
region                      object
payment_method              object
is_member                     bool
delivery_days                int64
customer_age                 int64
gender                      object
product_category            object
rating                     float64
return_status               object
feedback                    object
shipping_cost              float64
coupon_code                 object
delivery_rating            float64
dtype: object

<div class="alert alert-warning">

**3. Validating the Data Type of a Specific Column**

**Write a Pandas program to validate the data type of a specific column in a DataFrame.**

</div>

In [6]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1212,136,9,74.47,0.12,589.8024,1,West,Cash,True,3,57,Other,Books,2.0,Returned,Negative,10.22,SAVE10,NaN
1,2023-01-02,1799,155,5,99.14,0.06,465.9580,1,East,Credit Card,True,6,38,Male,Food,4.2,Not Returned,Negative,6.09,nan,3.1
2,2023-01-03,1353,193,8,81.62,0.09,594.1936,4,West,Online,False,5,60,Male,Books,1.9,Not Returned,Negative,NaN,SAVE10,3.4
3,2023-01-04,1060,192,2,72.77,0.15,123.7090,5,West,Online,False,5,41,Male,Clothing,3.4,Not Returned,Neutral,NaN,WELCOME5,3.4
4,2023-01-05,1363,147,4,16.42,0.17,54.5144,5,West,Cash,True,2,36,Male,Books,2.9,Not Returned,Neutral,19.68,FREESHIP,1.7
5,2023-01-06,1552,183,4,93.28,0.13,324.6144,9,East,Credit Card,True,6,49,Male,Books,3.3,Returned,Negative,11.56,WELCOME5,NaN
6,2023-01-07,1448,119,8,68.75,0.04,528.0000,4,West,Cash,False,3,20,Female,Clothing,4.5,Not Returned,Negative,11.86,SAVE10,2.9
7,2023-01-08,1530,132,1,95.38,0.15,81.0730,7,East,Credit Card,False,1,24,Female,Electronics,2.6,Returned,Neutral,18.66,WELCOME5,4.3
8,2023-01-09,1560,168,5,84.83,0.19,343.5615,6,South,Online,False,5,34,Male,Electronics,1.6,Returned,Positive,NaN,WELCOME5,1.9
9,2023-01-10,1727,159,7,33.34,0.19,189.0378,9,East,Credit Card,True,4,36,Female,Books,2.3,Returned,Positive,13.54,nan,2.5
10,2023-01-11,1753,132,8,28.71,0.09,209.0088,2,West,Online,False,5,44,Male,Clothing,4.5,Not Returned,Negative,15.69,WELCOME5,3.7
11,2023-01-12,1369,173,5,79.52,0.06,373.7440,5,East,Credit Card,False,2,66,Other,Books,1.6,Returned,Neutral,NaN,WELCOME5,NaN
12,2023-01-13,1486,161,3,95.83,0.30,201.2430,2,West,Credit Card,True,4,41,Female,Books,4.0,Not Returned,Positive,18.53,nan,NaN
13,2023-01-14,1556,172,7,18.56,0.02,127.3216,1,East,Cash,True,2,57,Male,Electronics,2.4,Not Returned,Negative,10.60,WELCOME5,4.2
14,2023-01-15,1334,159,7,68.01,0.03,461.7879,8,North,Cash,False,2,37,Male,Food,4.1,Returned,Neutral,15.31,SAVE10,NaN
15,2023-01-16,1091,138,3,44.83,0.23,103.5573,4,North,Credit Card,True,5,61,Female,Food,2.3,Not Returned,Positive,16.54,nan,4.9
16,2023-01-17,1109,102,2,20.54,0.03,39.8476,6,West,Credit Card,False,3,43,Female,Food,4.3,Returned,Negative,NaN,FREESHIP,NaN
17,2023-01-18,1760,193,1,94.48,0.26,69.9152,7,West,Cash,True,3,61,Other,Clothing,4.3,Returned,Negative,18.90,SAVE10,NaN
18,2023-01-19,1479,179,3,98.79,0.10,266.7330,3,West,Credit Card,False,6,69,Female,Clothing,3.5,Returned,Neutral,6.96,nan,NaN
19,2023-01-20,1236,122,8,62.73,0.28,361.3248,4,East,Online,False,6,23,Male,Electronics,2.6,Returned,Negative,14.07,SAVE10,3.0
20,2023-01-21,1549,178,5,61.55,0.25,230.8125,1,South,Credit Card,False,5,39,Other,Books,4.2,Returned,Negative,NaN,SAVE10,1.5
21,2023-01-22,1470,121,1,14.27,0.26,10.5598,5,North,Cash,True,4,18,Female,Books,1.1,Returned,Neutral,7.42,FREESHIP,4.7
22,2023-01-23,1953,124,2,42.97,0.05,81.6430,1,West,Cash,False,5,59,Other,Electronics,3.7,Returned,Positive,NaN,WELCOME5,NaN
23,2023-01-24,1101,184,7,99.40,0.15,591.4300,1,North,Credit Card,True,3,41,Female,Books,3.5,Returned,Negative,11.37,nan,1.5
24,2023-01-25,1980,127,7,12.48,0.13,76.0032,4,West,Cash,True,4,44,Male,Clothing,1.1,Returned,Neutral,8.45,nan,2.2
25,2023-01-26,1426,104,7,50.93,0.11,317.2939,5,West,Online,True,6,52,Female,Electronics,1.7,Returned,Positive,12.20,nan,NaN
26,2023-01-27,1389,147,6,59.38,0.28,256.5216,3,South,Online,True,1,28,Female,Food,4.1,Returned,Negative,13.33,SAVE10,1.4
27,2023-01-28,1392,102,3,84.06,0.13,219.3966,2,West,Cash,False,6,22,Other,Food,3.0,Not Returned,Negative,17.60,WELCOME5,1.1
28,2023-01-29,1252,122,8,72.56,0.08,534.0416,2,West,Online,True,6,21,Female,Books,2.6,Not Returned,Positive,15.01,WELCOME5,NaN
29,2023-01-30,1732,142,9,45.00,0.23,311.8500,3,East,Credit Card,True,3,31,Other,Clothing,1.0,Not Returned,Positive,12.69,FREESHIP,4.3
30,2023-01-31,1322,148,9,53.61,0.05,458.3655,4,North,Cash,False,5,46,Other,Food,4.1,Returned,Positive,11.44,FREESHIP,NaN
31,2023-02-01,1302,111,2,41.82,0.13,72.7668,4,North,Online,True,5,44,Other,Electronics,1.2,Returned,Neutral,12.94,FREESHIP,4.7
32,2023-02-02,1733,149,6,46.56,0.14,240.2496,9,West,Cash,True,1,56,Female,Books,4.9,Returned,Positive,10.28,SAVE10,5.0
33,2023-02-03,1627,196,4,78.35,0.11,278.9260,5,East,Credit Card,False,4,54,Female,Books,1.9,Returned,Positive,13.03,WELCOME5,4.3
34,2023-02-04,1739,134,2,13.46,0.16,22.6128,9,South,Online,True,4,33,Male,Electronics,2.8,Not Returned,Neutral,13.66,nan,5.0

<div class="alert alert-success">

**Solution 03:**
</div>

In [7]:
# 3. Validating the Data Type of a Specific Column
# Write a Pandas program to validate the data type of a specific column in a DataFrame.

# Check if 'price' column is of type float
is_of_type = 'float64'
is_price_float = df['price'].dtype == is_of_type
is_price_float

# Validate the data type of 'price' column
if is_price_float:
    print("The 'price' column is of type {}.".format(df['price'].dtype))
else:
    print("The 'price' column is not of type {}, it is {}.".format(is_of_type, df['price'].dtype))

The 'price' column is of type float64.

<div class="alert alert-warning">

**4. Checking Duplicate Rows in a DataFrame**

**Write a Pandas program to check duplicate rows in a DataFrame.**

</div>

In [8]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Add 3 duplicate rows
df = pd.concat([df, df.sample(n=3, random_state=42)], ignore_index=True)

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1575,101,3,40.41,0.15,103.0455,4,West,Cash,True,1,40,Other,Electronics,3.7,Returned,Negative,11.93,WELCOME5,3.4
1,2023-01-02,1241,109,7,50.88,0.26,263.5584,6,North,Cash,False,1,49,Female,Books,1.7,Returned,Neutral,NaN,FREESHIP,4.1
2,2023-01-03,1518,101,8,56.90,0.30,318.6400,4,North,Cash,False,3,65,Male,Clothing,2.9,Not Returned,Negative,10.56,SAVE10,3.4
3,2023-01-04,1663,164,7,27.01,0.02,185.2886,9,North,Cash,False,1,58,Other,Food,4.2,Not Returned,Positive,17.84,WELCOME5,1.3
4,2023-01-05,1013,103,4,61.57,0.05,233.9660,6,East,Cash,False,1,63,Other,Books,4.3,Returned,Neutral,14.86,nan,1.8
5,2023-01-06,1964,174,9,91.34,0.28,591.8832,8,South,Cash,True,2,69,Female,Books,4.5,Not Returned,Positive,16.24,WELCOME5,NaN
6,2023-01-07,1448,102,4,90.51,0.14,311.3544,4,West,Credit Card,False,2,37,Male,Electronics,3.9,Returned,Negative,5.32,WELCOME5,1.9
7,2023-01-08,1277,141,2,30.56,0.12,53.7856,2,East,Cash,True,2,30,Other,Books,1.4,Returned,Neutral,6.90,SAVE10,NaN
8,2023-01-09,1998,190,9,59.14,0.24,404.5176,1,East,Online,True,1,25,Female,Books,3.6,Not Returned,Neutral,13.09,SAVE10,3.9
9,2023-01-10,1047,157,2,47.73,0.13,83.0502,2,South,Online,False,2,41,Female,Electronics,3.2,Not Returned,Negative,6.93,nan,1.9
10,2023-01-11,1477,127,8,23.36,0.28,134.5536,8,North,Credit Card,True,5,57,Other,Electronics,4.0,Not Returned,Negative,9.29,FREESHIP,1.7
11,2023-01-12,1985,132,1,77.65,0.08,71.4380,1,East,Online,False,3,25,Male,Food,4.0,Not Returned,Negative,10.29,nan,NaN
12,2023-01-13,1195,136,9,28.80,0.24,196.9920,9,West,Online,True,2,21,Other,Clothing,1.1,Not Returned,Negative,14.79,WELCOME5,4.9
13,2023-01-14,1913,187,9,40.49,0.20,291.5280,1,East,Online,False,1,69,Male,Electronics,2.9,Returned,Neutral,5.98,nan,4.6
14,2023-01-15,1929,172,5,33.55,0.00,167.7500,8,North,Cash,True,5,43,Female,Clothing,1.0,Returned,Negative,17.35,FREESHIP,NaN
15,2023-01-16,1708,178,8,21.02,0.17,139.5728,4,South,Cash,False,5,43,Female,Clothing,3.8,Returned,Neutral,NaN,FREESHIP,1.3
16,2023-01-17,1612,111,3,11.48,0.18,28.2408,5,West,Online,True,1,45,Male,Food,3.3,Returned,Positive,8.44,WELCOME5,3.1
17,2023-01-18,1110,111,2,71.10,0.07,132.2460,7,South,Cash,True,4,30,Female,Clothing,2.7,Returned,Negative,13.89,nan,3.0
18,2023-01-19,1244,133,2,44.74,0.14,76.9528,2,North,Credit Card,True,6,51,Male,Electronics,3.0,Returned,Negative,NaN,WELCOME5,NaN
19,2023-01-20,1142,197,9,86.08,0.28,557.7984,8,North,Cash,False,6,26,Other,Books,2.8,Not Returned,Negative,14.31,nan,3.0
20,2023-01-21,1246,136,5,90.91,0.08,418.1860,6,West,Cash,True,1,61,Male,Food,4.9,Returned,Positive,NaN,nan,2.9
21,2023-01-22,1619,194,9,63.76,0.26,424.6416,7,West,Online,True,1,34,Female,Books,4.1,Not Returned,Neutral,8.10,nan,2.3
22,2023-01-23,1570,175,8,58.12,0.14,399.8656,8,North,Credit Card,True,3,59,Other,Food,1.5,Not Returned,Negative,18.24,nan,3.2
23,2023-01-24,1458,149,6,81.14,0.22,379.7352,1,South,Credit Card,False,1,31,Other,Electronics,1.3,Not Returned,Neutral,7.09,SAVE10,5.0
24,2023-01-25,1657,154,2,34.90,0.03,67.7060,4,South,Online,False,1,30,Other,Electronics,1.5,Not Returned,Negative,NaN,WELCOME5,1.7
25,2023-01-26,1741,192,8,41.14,0.24,250.1312,6,South,Cash,False,2,27,Female,Books,4.4,Returned,Negative,11.28,nan,4.5
26,2023-01-27,1643,172,3,13.14,0.22,30.7476,6,South,Credit Card,False,2,33,Female,Electronics,4.2,Not Returned,Positive,17.60,nan,NaN
27,2023-01-28,1667,109,6,48.40,0.09,264.2640,2,East,Credit Card,False,1,39,Other,Books,4.5,Not Returned,Positive,8.72,nan,4.6
28,2023-01-29,1101,128,4,31.14,0.15,105.8760,8,East,Online,True,4,66,Male,Electronics,4.0,Returned,Negative,7.31,FREESHIP,3.8
29,2023-01-30,1598,196,9,13.69,0.08,113.3532,8,East,Cash,True,4,37,Other,Electronics,3.4,Not Returned,Neutral,7.67,SAVE10,3.7
30,2023-01-31,1109,169,9,83.52,0.04,721.6128,1,North,Cash,True,2,37,Other,Books,3.7,Returned,Positive,10.66,nan,3.9
31,2023-02-01,1139,111,3,96.56,0.03,280.9896,9,West,Credit Card,False,6,27,Female,Electronics,1.4,Not Returned,Positive,18.25,SAVE10,3.3
32,2023-02-02,1056,160,3,60.82,0.04,175.1616,2,South,Cash,True,3,43,Other,Food,2.0,Not Returned,Negative,7.79,nan,2.2
33,2023-02-03,1734,121,9,88.13,0.18,650.3994,2,West,Cash,False,6,51,Other,Clothing,3.4,Not Returned,Negative,5.82,WELCOME5,NaN
34,2023-02-04,1813,126,1,99.95,0.01,98.9505,4,West,Online,False,3,32,Female,Electronics,4.8,Returned,Neutral,18.20,nan,2.6
35,2023-01-27,1643,172,3,13.14,0.22,30.7476,6,South,Credit Card,False,2,33,Female,Electronics,4.2,Not Returned,Positive,17.60,nan,NaN
36,2023-01-14,1913,187,9,40.49,0.20,291.5280,1,East,Online,False,1,69,Male,Electronics,2.9,Returned,Neutral,5.98,nan,4.6
37,2023-01-25,1657,154,2,34.90,0.03,67.7060,4,South,Online,False,1,30,Other,Electronics,1.5,Not Returned,Negative,NaN,WELCOME5,1.7

<div class="alert alert-success">

**Solution 04:**
</div>

In [9]:
# 4. Checking Duplicate Rows in a DataFrame
# Write a Pandas program to check duplicate rows in a DataFrame.

# Check for duplicate rows
duplicate_rows = df[df.duplicated()]
duplicate_rows

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
35,2023-01-27,1643,172,3,13.14,0.22,30.7476,6,South,Credit Card,False,2,33,Female,Electronics,4.2,Not Returned,Positive,17.60,nan,NaN
36,2023-01-14,1913,187,9,40.49,0.20,291.5280,1,East,Online,False,1,69,Male,Electronics,2.9,Returned,Neutral,5.98,nan,4.6
37,2023-01-25,1657,154,2,34.90,0.03,67.7060,4,South,Online,False,1,30,Other,Electronics,1.5,Not Returned,Negative,NaN,WELCOME5,1.7

<div class="alert alert-warning">

**5. Removing Duplicate Rows from a DataFrame**

**Write a Pandas program to remove duplicate rows from a DataFrame.**

</div>

In [10]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Add 3 duplicate rows
df = pd.concat([df, df.sample(n=3, random_state=42)], ignore_index=True)

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1981,141,2,32.81,0.03,63.6514,6,East,Cash,False,3,39,Other,Food,3.7,Not Returned,Negative,NaN,nan,4.5
1,2023-01-02,1620,177,5,22.06,0.18,90.4460,6,East,Credit Card,False,5,41,Female,Clothing,2.4,Not Returned,Positive,13.34,FREESHIP,4.7
2,2023-01-03,1113,183,2,25.73,0.25,38.5950,7,East,Credit Card,True,6,35,Other,Electronics,4.3,Not Returned,Neutral,8.99,WELCOME5,NaN
3,2023-01-04,1930,149,1,41.74,0.28,30.0528,5,East,Cash,False,5,62,Other,Books,2.5,Returned,Neutral,15.14,nan,2.1
4,2023-01-05,1093,148,6,93.50,0.00,561.0000,1,North,Cash,True,1,55,Female,Food,2.4,Returned,Positive,6.50,FREESHIP,2.5
5,2023-01-06,1321,159,7,30.87,0.04,207.4464,8,East,Cash,False,6,21,Male,Electronics,3.6,Not Returned,Neutral,12.50,nan,4.2
6,2023-01-07,1804,118,6,99.07,0.17,493.3686,2,North,Credit Card,False,6,41,Other,Food,3.9,Returned,Positive,13.76,nan,NaN
7,2023-01-08,1698,172,2,19.72,0.22,30.7632,9,South,Online,True,1,55,Male,Books,1.8,Not Returned,Neutral,17.37,WELCOME5,NaN
8,2023-01-09,1168,119,1,54.20,0.08,49.8640,1,South,Online,True,2,24,Female,Clothing,2.2,Not Returned,Neutral,NaN,nan,1.8
9,2023-01-10,1007,155,3,50.09,0.29,106.6917,1,North,Online,False,3,18,Male,Food,2.7,Returned,Positive,8.99,SAVE10,NaN
10,2023-01-11,1709,107,5,28.34,0.16,119.0280,1,North,Cash,True,6,48,Female,Books,3.8,Returned,Negative,14.78,WELCOME5,4.9
11,2023-01-12,1663,160,1,56.55,0.01,55.9845,5,South,Online,False,3,44,Female,Electronics,4.0,Not Returned,Neutral,11.18,nan,NaN
12,2023-01-13,1731,186,4,24.26,0.11,86.3656,4,North,Online,True,3,38,Female,Electronics,3.2,Not Returned,Negative,5.99,nan,NaN
13,2023-01-14,1658,190,2,31.45,0.09,57.2390,1,West,Cash,False,4,58,Female,Books,3.3,Not Returned,Negative,15.84,FREESHIP,2.2
14,2023-01-15,1367,194,8,41.38,0.11,294.6256,2,South,Credit Card,False,3,57,Other,Books,2.3,Returned,Positive,12.81,nan,2.2
15,2023-01-16,1038,179,7,21.59,0.16,126.9492,5,North,Cash,True,6,44,Male,Books,4.4,Returned,Positive,NaN,nan,NaN
16,2023-01-17,1633,135,1,13.52,0.21,10.6808,3,East,Credit Card,True,3,43,Female,Books,2.2,Not Returned,Negative,9.56,nan,4.8
17,2023-01-18,1587,140,9,69.88,0.02,616.3416,1,South,Online,False,3,20,Female,Food,3.7,Not Returned,Negative,18.83,FREESHIP,NaN
18,2023-01-19,1742,125,6,95.86,0.21,454.3764,3,South,Online,False,4,18,Other,Books,1.5,Returned,Negative,18.39,FREESHIP,1.5
19,2023-01-20,1042,182,9,75.92,0.22,532.9584,7,East,Credit Card,True,4,26,Female,Food,1.4,Not Returned,Neutral,7.24,WELCOME5,NaN
20,2023-01-21,1009,162,5,85.99,0.13,374.0565,4,North,Credit Card,False,3,27,Male,Clothing,1.1,Returned,Positive,8.21,nan,2.2
21,2023-01-22,1546,138,8,17.39,0.25,104.3400,2,South,Online,True,1,56,Male,Books,5.0,Returned,Negative,9.00,SAVE10,NaN
22,2023-01-23,1976,158,7,23.25,0.09,148.1025,5,North,Cash,True,1,39,Male,Electronics,4.2,Not Returned,Positive,18.59,SAVE10,NaN
23,2023-01-24,1053,151,5,42.45,0.17,176.1675,7,North,Credit Card,False,5,60,Other,Clothing,4.2,Not Returned,Negative,14.52,FREESHIP,NaN
24,2023-01-25,1810,150,9,92.68,0.17,692.3196,4,South,Online,False,5,27,Other,Electronics,2.4,Returned,Negative,10.79,WELCOME5,2.4
25,2023-01-26,1671,178,1,71.30,0.26,52.7620,5,South,Credit Card,False,2,63,Other,Books,1.4,Not Returned,Negative,12.85,nan,NaN
26,2023-01-27,1608,157,7,45.93,0.07,299.0043,3,West,Credit Card,True,2,50,Other,Food,2.4,Returned,Neutral,13.09,WELCOME5,NaN
27,2023-01-28,1699,122,8,74.82,0.04,574.6176,9,North,Cash,False,4,23,Male,Food,1.0,Not Returned,Neutral,NaN,nan,NaN
28,2023-01-29,1804,153,8,80.82,0.19,523.7136,9,East,Credit Card,True,5,63,Female,Electronics,1.9,Returned,Positive,13.46,nan,4.4
29,2023-01-30,1893,109,9,64.66,0.19,471.3714,8,North,Credit Card,True,6,39,Female,Electronics,4.7,Not Returned,Neutral,6.15,WELCOME5,2.1
30,2023-01-31,1289,132,6,66.61,0.13,347.7042,1,East,Cash,True,1,27,Male,Electronics,1.2,Not Returned,Positive,18.34,WELCOME5,2.2
31,2023-02-01,1455,104,7,40.88,0.18,234.6512,7,West,Credit Card,False,1,65,Male,Electronics,3.1,Returned,Neutral,NaN,nan,4.8
32,2023-02-02,1593,131,1,98.53,0.02,96.5594,7,South,Cash,True,4,32,Other,Books,4.6,Not Returned,Neutral,NaN,SAVE10,3.0
33,2023-02-03,1300,151,6,68.38,0.11,365.1492,9,West,Online,True,4,52,Male,Books,1.7,Returned,Negative,7.89,WELCOME5,3.8
34,2023-02-04,1152,155,5,65.53,0.27,239.1845,9,North,Credit Card,False,3,52,Male,Clothing,3.6,Returned,Neutral,5.39,nan,4.7
35,2023-01-27,1608,157,7,45.93,0.07,299.0043,3,West,Credit Card,True,2,50,Other,Food,2.4,Returned,Neutral,13.09,WELCOME5,NaN
36,2023-01-14,1658,190,2,31.45,0.09,57.2390,1,West,Cash,False,4,58,Female,Books,3.3,Not Returned,Negative,15.84,FREESHIP,2.2
37,2023-01-25,1810,150,9,92.68,0.17,692.3196,4,South,Online,False,5,27,Other,Electronics,2.4,Returned,Negative,10.79,WELCOME5,2.4

<div class="alert alert-success">

**Solution 05:**
</div>

In [11]:
# 5. Removing Duplicate Rows from a DataFrame
# Write a Pandas program to remove duplicate rows from a DataFrame.

print("Shape of DataFrame before removing duplicates:\n", df.shape)
# Remove duplicate rows
df = df.drop_duplicates()
print("Shape of DataFrame after removing duplicates:\n", df.shape)

Shape of DataFrame before removing duplicates:
 (38, 21)
Shape of DataFrame after removing duplicates:
 (35, 21)

<div class="alert alert-warning">

**6. Validating Data Based on Custom Conditions**

**Write a Pandas program to validate data based on custom conditions.**

</div>

In [12]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Add 3 duplicate rows
df = pd.concat([df, df.sample(n=3, random_state=42)], ignore_index=True)

# Add 3 more rows with negative price
df = pd.concat([df, pd.DataFrame({
    'date': pd.date_range(start='2023-02-05', periods=3, freq='D'),
    'customer_id': [1500, 1501, 1502],
    'product_id': [150, 151, 152],
    'quantity': [2, 3, 1],
    'price': [-20.00, -15.00, -30.00],  # Negative prices
    'discount': [0.1, 0.2, 0.15],
    'revenue': [0, 0, 0],  # Placeholder; will be recalculated
    'store_id': [5, 6, 7],
    'region': ['North', 'South', 'East'],
    'payment_method': ['Credit Card', 'Cash', 'Online'],
    'is_member': [True, False, True],
    'delivery_days': [3, 4, 2],
    'customer_age': [25, 34, 45],
    'gender': ['Male', 'Female', 'Other'],
    'product_category': ['Electronics', 'Clothing', 'Books'],
    'rating': [4.5, 3.0, 5.0],
    'return_status': ['Not Returned', 'Returned', 'Not Returned'],
    'feedback': ['Positive', 'Neutral', 'Negative'],
})], ignore_index=True)

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1597,190,8,80.38,0.18,527.2928,9,South,Cash,False,2,45,Male,Clothing,1.1,Not Returned,Neutral,8.94,WELCOME5,3.3
1,2023-01-02,1565,170,4,56.01,0.26,165.7896,8,South,Online,True,4,43,Female,Electronics,4.3,Not Returned,Positive,6.17,nan,NaN
2,2023-01-03,1818,143,5,23.21,0.11,103.2845,9,West,Cash,True,3,29,Female,Clothing,4.9,Not Returned,Neutral,5.59,nan,NaN
3,2023-01-04,1442,106,5,71.88,0.06,337.8360,9,South,Credit Card,True,6,55,Male,Electronics,3.7,Returned,Neutral,5.00,FREESHIP,3.4
4,2023-01-05,1882,196,2,34.48,0.25,51.7200,4,North,Cash,True,5,50,Female,Food,4.2,Not Returned,Neutral,5.72,nan,4.1
5,2023-01-06,1570,134,6,38.97,0.13,203.4234,8,North,Credit Card,False,5,32,Female,Clothing,2.0,Not Returned,Negative,19.27,nan,3.1
6,2023-01-07,1023,161,5,54.52,0.09,248.0660,5,South,Cash,False,5,33,Male,Clothing,1.2,Returned,Neutral,10.68,nan,1.7
7,2023-01-08,1475,144,2,14.13,0.16,23.7384,9,West,Cash,True,3,22,Female,Clothing,2.0,Returned,Negative,16.37,WELCOME5,4.4
8,2023-01-09,1659,189,1,93.08,0.29,66.0868,6,North,Credit Card,True,4,42,Other,Food,3.2,Not Returned,Neutral,17.74,nan,NaN
9,2023-01-10,1560,196,3,30.52,0.07,85.1508,3,South,Cash,False,1,44,Other,Electronics,1.8,Not Returned,Negative,13.48,nan,NaN
10,2023-01-11,1981,137,8,90.77,0.19,588.1896,2,South,Credit Card,True,4,57,Female,Books,2.0,Returned,Positive,9.59,SAVE10,4.3
11,2023-01-12,1492,106,3,40.85,0.10,110.2950,4,South,Online,True,6,22,Male,Books,1.9,Returned,Positive,13.69,FREESHIP,1.0
12,2023-01-13,1971,161,2,36.62,0.28,52.7328,5,East,Credit Card,False,1,27,Other,Clothing,3.7,Not Returned,Negative,NaN,SAVE10,2.8
13,2023-01-14,1441,166,1,73.97,0.28,53.2584,1,South,Cash,True,6,37,Other,Clothing,1.4,Not Returned,Neutral,10.89,nan,4.5
14,2023-01-15,1689,124,6,46.76,0.14,241.2816,8,North,Online,False,6,30,Female,Clothing,3.3,Not Returned,Neutral,16.63,FREESHIP,NaN
15,2023-01-16,1134,153,9,32.64,0.12,258.5088,7,North,Cash,False,6,26,Other,Clothing,3.1,Returned,Positive,NaN,SAVE10,NaN
16,2023-01-17,1693,190,3,73.24,0.01,217.5228,8,East,Cash,False,5,51,Other,Food,4.3,Returned,Positive,17.22,SAVE10,1.4
17,2023-01-18,1994,184,1,16.65,0.22,12.9870,9,West,Online,False,3,27,Male,Books,3.7,Returned,Neutral,15.76,SAVE10,3.6
18,2023-01-19,1242,190,6,33.11,0.12,174.8208,9,South,Credit Card,False,2,40,Female,Clothing,4.2,Not Returned,Negative,17.32,nan,NaN
19,2023-01-20,1237,196,1,29.39,0.02,28.8022,9,East,Online,True,4,57,Other,Books,1.8,Not Returned,Neutral,12.68,SAVE10,4.8
20,2023-01-21,1120,129,1,23.52,0.00,23.5200,6,North,Online,True,2,67,Male,Food,2.8,Returned,Neutral,19.84,FREESHIP,NaN
21,2023-01-22,1128,172,5,40.07,0.30,140.2450,3,East,Online,True,6,68,Female,Books,3.1,Not Returned,Positive,16.24,nan,4.4
22,2023-01-23,1275,114,3,74.52,0.26,165.4344,7,South,Online,True,1,48,Female,Clothing,4.9,Not Returned,Positive,7.86,nan,3.0
23,2023-01-24,1683,177,9,72.90,0.08,603.6120,6,East,Online,True,1,19,Other,Books,1.2,Returned,Negative,15.35,FREESHIP,3.7
24,2023-01-25,1413,113,6,82.99,0.23,383.4138,2,North,Credit Card,True,1,50,Female,Electronics,3.4,Returned,Negative,8.69,nan,NaN
25,2023-01-26,1831,142,3,82.17,0.28,177.4872,3,North,Online,False,2,67,Female,Food,1.3,Not Returned,Negative,12.83,nan,3.4
26,2023-01-27,1027,178,8,17.65,0.20,112.9600,5,North,Credit Card,True,2,52,Other,Electronics,3.4,Returned,Neutral,8.24,WELCOME5,2.1
27,2023-01-28,1370,157,9,85.92,0.10,695.9520,1,North,Cash,True,6,38,Other,Electronics,3.9,Returned,Neutral,7.81,WELCOME5,NaN
28,2023-01-29,1392,168,6,21.63,0.01,128.4822,4,North,Cash,False,1,31,Female,Electronics,1.9,Returned,Positive,11.54,WELCOME5,3.5
29,2023-01-30,1766,127,2,31.17,0.00,62.3400,4,East,Online,True,1,44,Female,Food,1.9,Not Returned,Negative,10.29,FREESHIP,4.8
30,2023-01-31,1564,168,4,79.26,0.23,244.1208,7,East,Cash,True,5,29,Male,Electronics,1.0,Not Returned,Neutral,17.22,SAVE10,4.4
31,2023-02-01,1734,126,7,35.74,0.17,207.6494,6,East,Credit Card,False,4,42,Other,Food,2.3,Not Returned,Neutral,19.32,nan,2.5
32,2023-02-02,1783,115,1,24.26,0.29,17.2246,6,North,Credit Card,True,2,57,Other,Food,4.1,Not Returned,Positive,12.16,SAVE10,2.8
33,2023-02-03,1473,155,8,96.44,0.13,671.2224,8,West,Credit Card,False,4,31,Male,Clothing,4.4,Not Returned,Neutral,13.79,FREESHIP,3.0
34,2023-02-04,1781,195,1,43.71,0.22,34.0938,5,South,Online,False,6,33,Male,Food,4.2,Not Returned,Negative,16.45,SAVE10,4.7
35,2023-01-27,1027,178,8,17.65,0.20,112.9600,5,North,Credit Card,True,2,52,Other,Electronics,3.4,Returned,Neutral,8.24,WELCOME5,2.1
36,2023-01-14,1441,166,1,73.97,0.28,53.2584,1,South,Cash,True,6,37,Other,Clothing,1.4,Not Returned,Neutral,10.89,nan,4.5
37,2023-01-25,1413,113,6,82.99,0.23,383.4138,2,North,Credit Card,True,1,50,Female,Electronics,3.4,Returned,Negative,8.69,nan,NaN
38,2023-02-05,1500,150,2,-20.00,0.10,0.0000,5,North,Credit Card,True,3,25,Male,Electronics,4.5,Not Returned,Positive,NaN,NaN,NaN
39,2023-02-06,1501,151,3,-15.00,0.20,0.0000,6,South,Cash,False,4,34,Female,Clothing,3.0,Returned,Neutral,NaN,NaN,NaN
40,2023-02-07,1502,152,1,-30.00,0.15,0.0000,7,East,Online,True,2,45,Other,Books,5.0,Not Returned,Negative,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 06:**
</div>

In [13]:
# 6. Validating Data Based on Custom Conditions
# Write a Pandas program to validate data based on custom conditions.

# Check if 'price' is greater than 0
valid_price = df['price'] > 0
if valid_price.all():
    print("All prices are valid.")
else:
    print("Some prices are invalid:")
    display(df[~valid_price])

Some prices are invalid:

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
38,2023-02-05,1500,150,2,-20.0,0.10,0.0,5,North,Credit Card,True,3,25,Male,Electronics,4.5,Not Returned,Positive,NaN,NaN,NaN
39,2023-02-06,1501,151,3,-15.0,0.20,0.0,6,South,Cash,False,4,34,Female,Clothing,3.0,Returned,Neutral,NaN,NaN,NaN
40,2023-02-07,1502,152,1,-30.0,0.15,0.0,7,East,Online,True,2,45,Other,Books,5.0,Not Returned,Negative,NaN,NaN,NaN

<div class="alert alert-warning">

**7. Checking That a Specific Column Contains Only Unique Values**

**Write a Pandas program to check that a specific column contains only unique values.**

</div>

In [14]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Add 3 duplicate rows
df = pd.concat([df, df.sample(n=3, random_state=42)], ignore_index=True)

# Add 3 more rows with negative price
df = pd.concat([df, pd.DataFrame({
    'date': pd.date_range(start='2023-02-05', periods=3, freq='D'),
    'customer_id': [1500, 1501, 1502],
    'product_id': [150, 151, 152],
    'quantity': [2, 3, 1],
    'price': [-20.00, -15.00, -30.00],  # Negative prices
    'discount': [0.1, 0.2, 0.15],
    'revenue': [0, 0, 0],  # Placeholder; will be recalculated
    'store_id': [5, 6, 7],
    'region': ['North', 'South', 'East'],
    'payment_method': ['Credit Card', 'Cash', 'Online'],
    'is_member': [True, False, True],
    'delivery_days': [3, 4, 2],
    'customer_age': [25, 34, 45],
    'gender': ['Male', 'Female', 'Other'],
    'product_category': ['Electronics', 'Clothing', 'Books'],
    'rating': [4.5, 3.0, 5.0],
    'return_status': ['Not Returned', 'Returned', 'Not Returned'],
    'feedback': ['Positive', 'Neutral', 'Negative'],
})], ignore_index=True)

# add column with unique value
df['unique_id'] = pd.Series(range(1, len(df) + 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,unique_id
0,2023-01-01,1864,187,1,94.29,0.29,66.9459,3,West,Credit Card,False,6,59,Other,Electronics,4.9,Not Returned,Positive,6.63,WELCOME5,NaN,1
1,2023-01-02,1637,142,2,26.24,0.13,45.6576,7,East,Online,True,5,44,Other,Books,2.0,Returned,Positive,7.28,nan,2.1,2
2,2023-01-03,1722,110,8,14.96,0.20,95.7440,1,East,Online,True,4,21,Male,Electronics,2.1,Not Returned,Neutral,16.18,nan,NaN,3
3,2023-01-04,1847,114,7,92.68,0.21,512.5204,7,East,Online,False,5,48,Female,Clothing,5.0,Returned,Positive,15.68,WELCOME5,2.2,4
4,2023-01-05,1690,175,6,22.31,0.05,127.1670,8,East,Cash,False,5,44,Other,Electronics,2.7,Returned,Neutral,15.66,nan,NaN,5
5,2023-01-06,1344,189,6,60.39,0.23,279.0018,8,North,Credit Card,True,3,48,Male,Food,2.9,Not Returned,Negative,14.09,WELCOME5,2.3,6
6,2023-01-07,1964,147,7,46.09,0.28,232.2936,6,East,Credit Card,True,1,39,Female,Clothing,1.4,Not Returned,Positive,18.26,WELCOME5,1.9,7
7,2023-01-08,1154,164,6,81.13,0.21,384.5562,5,South,Credit Card,False,6,58,Other,Food,2.6,Returned,Positive,12.38,FREESHIP,2.5,8
8,2023-01-09,1746,135,2,19.64,0.03,38.1016,2,South,Credit Card,True,2,66,Female,Food,1.6,Returned,Positive,5.10,SAVE10,3.9,9
9,2023-01-10,1302,165,9,13.23,0.11,105.9723,7,East,Cash,True,3,51,Female,Food,3.2,Returned,Negative,10.78,WELCOME5,NaN,10
10,2023-01-11,1003,154,7,52.63,0.00,368.4100,4,North,Online,False,5,49,Female,Clothing,4.2,Not Returned,Positive,5.08,SAVE10,4.4,11
11,2023-01-12,1916,132,2,98.22,0.04,188.5824,3,East,Online,True,5,52,Male,Electronics,1.9,Returned,Neutral,9.07,SAVE10,3.7,12
12,2023-01-13,1333,132,5,75.87,0.20,303.4800,7,West,Cash,False,1,31,Other,Books,3.1,Returned,Negative,NaN,nan,1.9,13
13,2023-01-14,1057,159,5,63.90,0.21,252.4050,8,West,Online,False,5,50,Other,Clothing,3.1,Returned,Negative,15.54,nan,NaN,14
14,2023-01-15,1518,152,5,84.77,0.25,317.8875,5,South,Credit Card,True,3,31,Female,Books,2.6,Returned,Positive,15.23,WELCOME5,2.1,15
15,2023-01-16,1418,143,9,36.24,0.24,247.8816,3,South,Cash,False,6,48,Male,Food,3.9,Returned,Negative,19.40,nan,3.7,16
16,2023-01-17,1569,120,3,14.56,0.13,38.0016,8,East,Credit Card,True,6,23,Male,Electronics,2.0,Returned,Negative,18.35,FREESHIP,1.0,17
17,2023-01-18,1660,152,4,33.11,0.11,117.8716,6,West,Online,False,6,65,Female,Books,1.3,Returned,Positive,8.45,SAVE10,2.1,18
18,2023-01-19,1434,174,2,46.43,0.11,82.6454,3,North,Credit Card,True,4,69,Other,Electronics,4.6,Not Returned,Positive,6.04,nan,3.9,19
19,2023-01-20,1244,168,2,90.80,0.23,139.8320,2,South,Cash,True,5,47,Other,Books,1.5,Returned,Positive,7.70,SAVE10,NaN,20
20,2023-01-21,1828,185,9,55.28,0.15,422.8920,9,South,Credit Card,False,4,52,Male,Electronics,3.4,Not Returned,Positive,18.11,FREESHIP,2.6,21
21,2023-01-22,1916,142,6,41.38,0.14,213.5208,4,East,Credit Card,True,6,52,Male,Books,1.8,Returned,Positive,16.60,WELCOME5,NaN,22
22,2023-01-23,1755,124,5,11.11,0.27,40.5515,5,South,Online,True,2,69,Female,Clothing,4.6,Not Returned,Neutral,18.95,SAVE10,1.9,23
23,2023-01-24,1749,109,5,70.58,0.12,310.5520,2,North,Online,True,4,37,Other,Books,2.9,Not Returned,Neutral,NaN,FREESHIP,2.2,24
24,2023-01-25,1534,194,2,46.42,0.02,90.9832,4,North,Credit Card,False,5,41,Other,Books,4.1,Returned,Negative,NaN,nan,3.3,25
25,2023-01-26,1826,149,1,77.41,0.24,58.8316,5,West,Cash,False,5,47,Male,Electronics,1.2,Returned,Neutral,15.82,nan,1.9,26
26,2023-01-27,1839,152,7,62.04,0.04,416.9088,4,West,Online,True,4,52,Male,Books,1.5,Returned,Positive,6.63,SAVE10,NaN,27
27,2023-01-28,1938,101,4,89.48,0.23,275.5984,9,West,Credit Card,True,6,36,Female,Clothing,1.9,Not Returned,Positive,NaN,nan,3.9,28
28,2023-01-29,1241,195,2,15.01,0.20,24.0160,5,West,Online,True,4,68,Female,Books,3.8,Not Returned,Negative,8.94,SAVE10,2.6,29
29,2023-01-30,1293,152,6,76.84,0.29,327.3384,7,West,Credit Card,False,6,54,Other,Books,4.0,Not Returned,Neutral,8.03,WELCOME5,3.5,30
30,2023-01-31,1350,188,7,70.22,0.05,466.9630,3,South,Credit Card,False,5,35,Other,Food,1.4,Not Returned,Positive,7.97,SAVE10,NaN,31
31,2023-02-01,1304,159,6,46.66,0.08,257.5632,5,East,Credit Card,True,2,24,Female,Books,2.3,Returned,Negative,NaN,FREESHIP,1.6,32
32,2023-02-02,1260,195,6,54.52,0.29,232.2552,6,South,Cash,False,2,32,Male,Books,1.0,Returned,Negative,12.78,WELCOME5,3.9,33
33,2023-02-03,1382,191,1,48.04,0.09,43.7164,7,West,Cash,True,4,27,Other,Books,3.8,Not Returned,Negative,11.80,nan,1.8,34
34,2023-02-04,1988,100,1,27.15,0.20,21.7200,8,East,Online,False,1,22,Male,Food,4.4,Not Returned,Positive,7.27,SAVE10,4.9,35
35,2023-01-27,1839,152,7,62.04,0.04,416.9088,4,West,Online,True,4,52,Male,Books,1.5,Returned,Positive,6.63,SAVE10,NaN,36
36,2023-01-14,1057,159,5,63.90,0.21,252.4050,8,West,Online,False,5,50,Other,Clothing,3.1,Returned,Negative,15.54,nan,NaN,37
37,2023-01-25,1534,194,2,46.42,0.02,90.9832,4,North,Credit Card,False,5,41,Other,Books,4.1,Returned,Negative,NaN,nan,3.3,38
38,2023-02-05,1500,150,2,-20.00,0.10,0.0000,5,North,Credit Card,True,3,25,Male,Electronics,4.5,Not Returned,Positive,NaN,NaN,NaN,39
39,2023-02-06,1501,151,3,-15.00,0.20,0.0000,6,South,Cash,False,4,34,Female,Clothing,3.0,Returned,Neutral,NaN,NaN,NaN,40
40,2023-02-07,1502,152,1,-30.00,0.15,0.0000,7,East,Online,True,2,45,Other,Books,5.0,Not Returned,Negative,NaN,NaN,NaN,41

<div class="alert alert-success">

**Solution 07:**
</div>

In [15]:
pd.Series.is_unique?

Type:        property
String form: <property object at 0x10bc5c220>
Docstring:
Return boolean if values in the object are unique.

Returns
-------
bool

Examples
--------
>>> s = pd.Series([1, 2, 3])
>>> s.is_unique
True

>>> s = pd.Series([1, 2, 3, 1])
>>> s.is_unique
False

In [16]:
# 7. Checking That a Specific Column Contains Only Unique Values
# Write a Pandas program to check that a specific column contains only unique values.


def is_unique(column_name, dataframe):
    if dataframe[column_name].is_unique:
        print("The column {:<20} contains only unique values.".format(column_name))
    else:
        print("The column {:<20} has more than one unique value - has duplicates.".format(column_name))

for col in df.columns:
    is_unique(col, df)

The column date                 has more than one unique value - has duplicates.
The column customer_id          has more than one unique value - has duplicates.
The column product_id           has more than one unique value - has duplicates.
The column quantity             has more than one unique value - has duplicates.
The column price                has more than one unique value - has duplicates.
The column discount             has more than one unique value - has duplicates.
The column revenue              has more than one unique value - has duplicates.
The column store_id             has more than one unique value - has duplicates.
The column region               has more than one unique value - has duplicates.
The column payment_method       has more than one unique value - has duplicates.
The column is_member            has more than one unique value - has duplicates.
The column delivery_days        has more than one unique value - has duplicates.
The column customer_age         has more than one unique value - has duplicates.
The column gender               has more than one unique value - has duplicates.
The column product_category     has more than one unique value - has duplicates.
The column rating               has more than one unique value - has duplicates.
The column return_status        has more than one unique value - has duplicates.
The column feedback             has more than one unique value - has duplicates.
The column shipping_cost        has more than one unique value - has duplicates.
The column coupon_code          has more than one unique value - has duplicates.
The column delivery_rating      has more than one unique value - has duplicates.
The column unique_id            contains only unique values.

<div class="alert alert-warning">

**8. Detecting Outliers in a DataFrame**

**Write a Pandas program to detect outliers in a DataFrame.**

</div>

In [17]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Add 3 duplicate rows
df = pd.concat([df, df.sample(n=3, random_state=42)], ignore_index=True)

# Add 3 more rows with negative price
df = pd.concat([df, pd.DataFrame({
    'date': pd.date_range(start='2023-02-05', periods=3, freq='D'),
    'customer_id': [1500, 1501, 1502],
    'product_id': [150, 151, 152],
    'quantity': [2, 3, 1],
    'price': [-20.00, -15.00, -30.00],  # Negative prices
    'discount': [0.1, 0.2, 0.15],
    'revenue': [0, 0, 0],  # Placeholder; will be recalculated
    'store_id': [5, 6, 7],
    'region': ['North', 'South', 'East'],
    'payment_method': ['Credit Card', 'Cash', 'Online'],
    'is_member': [True, False, True],
    'delivery_days': [3, 4, 2],
    'customer_age': [25, 34, 45],
    'gender': ['Male', 'Female', 'Other'],
    'product_category': ['Electronics', 'Clothing', 'Books'],
    'rating': [4.5, 3.0, 5.0],
    'return_status': ['Not Returned', 'Returned', 'Not Returned'],
    'feedback': ['Positive', 'Neutral', 'Negative'],
})], ignore_index=True)

# add column with unique value
df['unique_id'] = pd.Series(range(1, len(df) + 1))

# add outliers
df.loc[[0,3,5], ['price']] = [9999.99, 8888.88, 7777.77]

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,unique_id
0,2023-01-01,1959,197,7,9999.99,0.10,480.3120,7,North,Cash,False,4,58,Female,Food,3.1,Returned,Negative,12.14,nan,3.8,1
1,2023-01-02,1195,140,5,39.88,0.19,161.5140,4,South,Credit Card,True,6,45,Other,Books,2.1,Not Returned,Neutral,NaN,nan,2.3,2
2,2023-01-03,1502,119,6,11.56,0.28,49.9392,7,North,Cash,False,1,44,Other,Books,3.2,Returned,Positive,15.49,nan,2.1,3
3,2023-01-04,1140,142,4,8888.88,0.11,294.2340,5,East,Cash,True,4,57,Female,Books,4.5,Returned,Positive,NaN,SAVE10,3.4,4
4,2023-01-05,1272,186,3,81.04,0.24,184.7712,5,North,Online,True,4,42,Female,Electronics,2.7,Returned,Neutral,13.20,nan,NaN,5
5,2023-01-06,1616,182,2,7777.77,0.26,130.8616,4,South,Cash,False,1,43,Female,Books,1.2,Not Returned,Positive,17.94,WELCOME5,2.2,6
6,2023-01-07,1851,124,7,41.94,0.21,231.9282,3,North,Cash,False,1,32,Male,Books,4.3,Not Returned,Negative,NaN,SAVE10,4.5,7
7,2023-01-08,1105,135,6,91.60,0.04,527.6160,1,South,Online,False,5,34,Female,Clothing,4.1,Not Returned,Positive,NaN,WELCOME5,NaN,8
8,2023-01-09,1162,182,5,22.56,0.12,99.2640,5,North,Cash,False,1,47,Male,Food,4.7,Returned,Negative,5.23,nan,3.9,9
9,2023-01-10,1953,104,2,64.89,0.03,125.8866,8,South,Credit Card,True,2,36,Male,Books,1.7,Not Returned,Positive,9.74,nan,4.8,10
10,2023-01-11,1285,169,5,58.07,0.25,217.7625,8,North,Credit Card,True,2,22,Other,Electronics,1.6,Returned,Positive,8.00,FREESHIP,2.7,11
11,2023-01-12,1177,101,9,87.12,0.23,603.7416,9,South,Online,False,1,49,Male,Electronics,1.5,Not Returned,Negative,18.69,nan,2.5,12
12,2023-01-13,1149,150,6,72.45,0.20,347.7600,3,West,Online,True,3,52,Male,Books,1.1,Not Returned,Negative,9.57,nan,NaN,13
13,2023-01-14,1256,166,6,15.62,0.26,69.3528,8,West,Credit Card,False,6,28,Male,Clothing,3.1,Not Returned,Negative,14.42,WELCOME5,3.5,14
14,2023-01-15,1478,191,1,91.08,0.13,79.2396,8,West,Cash,False,2,24,Female,Food,2.2,Not Returned,Neutral,17.40,WELCOME5,2.4,15
15,2023-01-16,1291,183,8,51.62,0.18,338.6272,9,East,Credit Card,False,2,48,Male,Food,4.1,Not Returned,Negative,9.14,WELCOME5,NaN,16
16,2023-01-17,1766,181,9,20.29,0.17,151.5663,7,West,Credit Card,False,6,49,Other,Food,4.8,Returned,Neutral,NaN,SAVE10,2.0,17
17,2023-01-18,1839,115,1,89.19,0.01,88.2981,6,West,Cash,False,4,23,Male,Electronics,4.9,Not Returned,Negative,18.11,nan,1.4,18
18,2023-01-19,1489,146,6,24.26,0.11,129.5484,5,West,Credit Card,True,5,39,Female,Clothing,4.0,Not Returned,Negative,5.47,nan,3.8,19
19,2023-01-20,1640,109,2,35.23,0.24,53.5496,3,North,Credit Card,True,3,38,Other,Electronics,4.8,Not Returned,Negative,19.07,WELCOME5,NaN,20
20,2023-01-21,1562,171,1,98.50,0.15,83.7250,4,East,Cash,False,1,22,Other,Electronics,1.0,Returned,Negative,NaN,SAVE10,4.5,21
21,2023-01-22,1638,173,8,82.43,0.14,567.1184,5,West,Cash,True,3,48,Female,Food,3.0,Returned,Neutral,12.06,nan,3.9,22
22,2023-01-23,1374,105,6,59.60,0.21,282.5040,5,East,Online,True,2,47,Other,Books,4.0,Not Returned,Positive,18.69,WELCOME5,NaN,23
23,2023-01-24,1602,106,3,41.88,0.04,120.6144,3,West,Credit Card,True,6,28,Male,Clothing,4.7,Returned,Negative,15.79,nan,3.2,24
24,2023-01-25,1764,179,3,31.95,0.12,84.3480,3,North,Credit Card,True,1,35,Female,Clothing,1.7,Returned,Neutral,9.14,WELCOME5,4.5,25
25,2023-01-26,1722,139,4,32.98,0.28,94.9824,4,North,Credit Card,False,3,25,Male,Electronics,2.0,Not Returned,Negative,14.32,nan,3.1,26
26,2023-01-27,1350,197,8,94.34,0.10,679.2480,8,East,Cash,True,5,67,Female,Books,2.2,Returned,Neutral,17.23,nan,1.3,27
27,2023-01-28,1543,116,8,25.55,0.21,161.4760,8,West,Online,False,5,27,Female,Books,2.1,Returned,Negative,NaN,FREESHIP,4.8,28
28,2023-01-29,1073,173,4,60.60,0.23,186.6480,1,East,Online,True,5,21,Female,Food,3.8,Not Returned,Neutral,15.04,nan,NaN,29
29,2023-01-30,1096,120,8,47.39,0.05,360.1640,7,West,Online,True,1,18,Other,Electronics,1.2,Returned,Negative,7.08,WELCOME5,NaN,30
30,2023-01-31,1177,103,7,89.97,0.18,516.4278,8,East,Credit Card,False,3,30,Male,Food,2.8,Not Returned,Neutral,9.93,FREESHIP,NaN,31
31,2023-02-01,1777,105,6,14.37,0.05,81.9090,6,West,Online,True,5,43,Female,Food,2.5,Returned,Positive,9.33,nan,NaN,32
32,2023-02-02,1387,109,5,65.68,0.01,325.1160,1,North,Credit Card,True,2,36,Female,Clothing,4.1,Returned,Negative,6.84,SAVE10,3.3,33
33,2023-02-03,1504,174,5,55.81,0.04,267.8880,2,North,Credit Card,False,6,64,Female,Electronics,3.5,Returned,Neutral,NaN,FREESHIP,5.0,34
34,2023-02-04,1355,107,9,10.55,0.02,93.0510,2,South,Credit Card,True,4,27,Other,Food,1.7,Returned,Neutral,NaN,nan,NaN,35
35,2023-01-27,1350,197,8,94.34,0.10,679.2480,8,East,Cash,True,5,67,Female,Books,2.2,Returned,Neutral,17.23,nan,1.3,36
36,2023-01-14,1256,166,6,15.62,0.26,69.3528,8,West,Credit Card,False,6,28,Male,Clothing,3.1,Not Returned,Negative,14.42,WELCOME5,3.5,37
37,2023-01-25,1764,179,3,31.95,0.12,84.3480,3,North,Credit Card,True,1,35,Female,Clothing,1.7,Returned,Neutral,9.14,WELCOME5,4.5,38
38,2023-02-05,1500,150,2,-20.00,0.10,0.0000,5,North,Credit Card,True,3,25,Male,Electronics,4.5,Not Returned,Positive,NaN,NaN,NaN,39
39,2023-02-06,1501,151,3,-15.00,0.20,0.0000,6,South,Cash,False,4,34,Female,Clothing,3.0,Returned,Neutral,NaN,NaN,NaN,40
40,2023-02-07,1502,152,1,-30.00,0.15,0.0000,7,East,Online,True,2,45,Other,Books,5.0,Not Returned,Negative,NaN,NaN,NaN,41

<div class="alert alert-success">

**Solution 08:**
</div>

In [18]:
# 8. Detecting Outliers in a DataFrame
# Write a Pandas program to detect outliers in a DataFrame.

def detect_outliers(column_name, dataframe):
    if dataframe[column_name].dtype not in [np.float64, np.int64]:
        print("Column {:>30} is not numeric and will be skipped.".format(column_name))
        return
    else:
        Q1 = dataframe[column_name].quantile(0.25)
        Q3 = dataframe[column_name].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        outliers = dataframe[(dataframe[column_name] < lower_bound) | (dataframe[column_name] > upper_bound)]
    if not outliers.empty:
        print("Column {:>30} OUTLIERS DETECTED.\n####### OUTLIERS #######".format(column_name))
        display(outliers)
    else:
        print("Column {:>30} has no outliers detected.".format(column_name))

for col in df.columns:
    detect_outliers(col, df)

Column                           date is not numeric and will be skipped.
Column                    customer_id has no outliers detected.
Column                     product_id has no outliers detected.
Column                       quantity has no outliers detected.
Column                          price OUTLIERS DETECTED.
####### OUTLIERS #######

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,unique_id
0,2023-01-01,1959,197,7,9999.99,0.10,480.3120,7,North,Cash,False,4,58,Female,Food,3.1,Returned,Negative,12.14,nan,3.8,1
3,2023-01-04,1140,142,4,8888.88,0.11,294.2340,5,East,Cash,True,4,57,Female,Books,4.5,Returned,Positive,NaN,SAVE10,3.4,4
5,2023-01-06,1616,182,2,7777.77,0.26,130.8616,4,South,Cash,False,1,43,Female,Books,1.2,Not Returned,Positive,17.94,WELCOME5,2.2,6

Column                       discount has no outliers detected.
Column                        revenue has no outliers detected.
Column                       store_id has no outliers detected.
Column                         region is not numeric and will be skipped.
Column                 payment_method is not numeric and will be skipped.
Column                      is_member is not numeric and will be skipped.
Column                  delivery_days has no outliers detected.
Column                   customer_age has no outliers detected.
Column                         gender is not numeric and will be skipped.
Column               product_category is not numeric and will be skipped.
Column                         rating has no outliers detected.
Column                  return_status is not numeric and will be skipped.
Column                       feedback is not numeric and will be skipped.
Column                  shipping_cost has no outliers detected.
Column                    coupon_code is not numeric and will be skipped.
Column                delivery_rating has no outliers detected.
Column                      unique_id has no outliers detected.

In [19]:
# finding outliers using the 3-σ rule

def detect_outliers_3sigma(column_name, dataframe):
    if dataframe[column_name].dtype not in [np.float64, np.int64]:
        print("Column {:>30} is not numeric and will be skipped.".format(column_name))
        return
    else:
        mean = dataframe[column_name].mean()
        std = dataframe[column_name].std()
        lower_bound = mean - 3 * std
        upper_bound = mean + 3 * std
        outliers = dataframe[(dataframe[column_name] < lower_bound) | (dataframe[column_name] > upper_bound)]
    
    if not outliers.empty:
        print("Column {:>30} OUTLIERS DETECTED (3σ rule).\n####### OUTLIERS #######".format(column_name))
        display(outliers)
    else:
        print("Column {:>30} has no outliers detected.".format(column_name))

# Apply to all columns
for col in df.columns:
    detect_outliers_3sigma(col, df)

Column                           date is not numeric and will be skipped.
Column                    customer_id has no outliers detected.
Column                     product_id has no outliers detected.
Column                       quantity has no outliers detected.
Column                          price OUTLIERS DETECTED (3σ rule).
####### OUTLIERS #######

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,unique_id
0,2023-01-01,1959,197,7,9999.99,0.10,480.3120,7,North,Cash,False,4,58,Female,Food,3.1,Returned,Negative,12.14,nan,3.8,1
3,2023-01-04,1140,142,4,8888.88,0.11,294.2340,5,East,Cash,True,4,57,Female,Books,4.5,Returned,Positive,NaN,SAVE10,3.4,4
5,2023-01-06,1616,182,2,7777.77,0.26,130.8616,4,South,Cash,False,1,43,Female,Books,1.2,Not Returned,Positive,17.94,WELCOME5,2.2,6

Column                       discount has no outliers detected.
Column                        revenue has no outliers detected.
Column                       store_id has no outliers detected.
Column                         region is not numeric and will be skipped.
Column                 payment_method is not numeric and will be skipped.
Column                      is_member is not numeric and will be skipped.
Column                  delivery_days has no outliers detected.
Column                   customer_age has no outliers detected.
Column                         gender is not numeric and will be skipped.
Column               product_category is not numeric and will be skipped.
Column                         rating has no outliers detected.
Column                  return_status is not numeric and will be skipped.
Column                       feedback is not numeric and will be skipped.
Column                  shipping_cost has no outliers detected.
Column                    coupon_code is not numeric and will be skipped.
Column                delivery_rating has no outliers detected.
Column                      unique_id has no outliers detected.

<div class="alert alert-warning">

**9. Validating Date Formats in a DataFrame**

**Write a Pandas program to validate date formats in a DataFrame.**

</div>

In [20]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Add 3 duplicate rows
df = pd.concat([df, df.sample(n=3, random_state=42)], ignore_index=True)

# Add 3 more rows with negative price
df = pd.concat([df, pd.DataFrame({
    'date': pd.date_range(start='2023-02-05', periods=3, freq='D'),
    'customer_id': [1500, 1501, 1502],
    'product_id': [150, 151, 152],
    'quantity': [2, 3, 1],
    'price': [-20.00, -15.00, -30.00],  # Negative prices
    'discount': [0.1, 0.2, 0.15],
    'revenue': [0, 0, 0],  # Placeholder; will be recalculated
    'store_id': [5, 6, 7],
    'region': ['North', 'South', 'East'],
    'payment_method': ['Credit Card', 'Cash', 'Online'],
    'is_member': [True, False, True],
    'delivery_days': [3, 4, 2],
    'customer_age': [25, 34, 45],
    'gender': ['Male', 'Female', 'Other'],
    'product_category': ['Electronics', 'Clothing', 'Books'],
    'rating': [4.5, 3.0, 5.0],
    'return_status': ['Not Returned', 'Returned', 'Not Returned'],
    'feedback': ['Positive', 'Neutral', 'Negative'],
})], ignore_index=True)

# add column with unique value
df['unique_id'] = pd.Series(range(1, len(df) + 1))

# add outliers
df.loc[[0,3,5], ['price']] = [9999.99, 8888.88, 7777.77]

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,unique_id
0,2023-01-01,1523,173,6,9999.99,0.03,87.3000,2,North,Online,True,1,46,Female,Clothing,2.7,Not Returned,Positive,9.41,FREESHIP,NaN,1
1,2023-01-02,1644,192,3,11.17,0.01,33.1749,1,South,Credit Card,False,5,57,Other,Clothing,3.4,Returned,Positive,NaN,SAVE10,4.6,2
2,2023-01-03,1642,186,9,66.33,0.28,429.8184,4,East,Credit Card,True,3,67,Male,Clothing,4.9,Returned,Positive,18.80,FREESHIP,NaN,3
3,2023-01-04,1343,146,1,8888.88,0.02,48.3826,6,West,Credit Card,True,1,67,Other,Clothing,2.0,Returned,Positive,9.85,FREESHIP,3.4,4
4,2023-01-05,1074,115,5,85.57,0.27,312.3305,6,South,Cash,False,6,40,Female,Clothing,5.0,Not Returned,Neutral,9.45,nan,1.2,5
5,2023-01-06,1823,127,1,7777.77,0.11,67.5421,4,South,Online,False,1,34,Female,Food,2.1,Returned,Negative,15.00,WELCOME5,2.3,6
6,2023-01-07,1480,193,2,73.18,0.21,115.6244,9,West,Credit Card,True,1,21,Male,Books,3.4,Not Returned,Neutral,6.85,nan,3.6,7
7,2023-01-08,1747,149,1,74.13,0.26,54.8562,3,East,Online,True,5,62,Male,Books,2.2,Not Returned,Positive,12.32,nan,1.1,8
8,2023-01-09,1939,129,8,75.49,0.09,549.5672,5,South,Cash,False,1,37,Female,Electronics,1.4,Not Returned,Neutral,11.06,nan,2.0,9
9,2023-01-10,1393,147,2,49.76,0.12,87.5776,1,East,Online,True,6,69,Other,Electronics,2.7,Returned,Negative,15.42,SAVE10,NaN,10
10,2023-01-11,1149,190,3,26.71,0.25,60.0975,7,West,Cash,True,4,49,Male,Electronics,4.1,Not Returned,Neutral,11.87,WELCOME5,1.2,11
11,2023-01-12,1042,177,9,33.34,0.29,213.0426,7,East,Cash,True,3,55,Other,Books,2.6,Returned,Neutral,15.27,FREESHIP,3.4,12
12,2023-01-13,1576,175,6,92.94,0.22,434.9592,6,West,Online,False,6,53,Other,Electronics,2.5,Returned,Negative,16.48,WELCOME5,NaN,13
13,2023-01-14,1117,185,2,14.22,0.12,25.0272,7,East,Cash,False,3,23,Female,Food,4.3,Returned,Negative,7.34,FREESHIP,4.0,14
14,2023-01-15,1733,135,6,78.06,0.04,449.6256,6,South,Online,True,4,18,Female,Clothing,1.6,Not Returned,Positive,10.54,WELCOME5,3.7,15
15,2023-01-16,1178,157,9,41.30,0.09,338.2470,3,South,Cash,False,2,37,Female,Books,2.5,Returned,Negative,16.17,SAVE10,NaN,16
16,2023-01-17,1712,125,6,75.14,0.07,419.2812,8,North,Credit Card,False,2,60,Other,Electronics,1.5,Not Returned,Positive,NaN,FREESHIP,2.6,17
17,2023-01-18,1201,199,6,87.50,0.13,456.7500,3,South,Online,True,1,36,Female,Books,1.6,Not Returned,Negative,17.75,nan,1.5,18
18,2023-01-19,1986,123,9,91.50,0.14,708.2100,8,North,Cash,True,6,63,Male,Clothing,1.9,Not Returned,Neutral,19.34,FREESHIP,1.3,19
19,2023-01-20,1566,173,3,86.58,0.20,207.7920,4,West,Online,True,1,23,Male,Books,4.3,Not Returned,Neutral,10.20,nan,NaN,20
20,2023-01-21,1999,136,3,78.26,0.14,201.9108,7,West,Online,False,3,44,Male,Food,1.2,Returned,Positive,18.52,FREESHIP,NaN,21
21,2023-01-22,1139,111,5,66.03,0.08,303.7380,4,North,Online,True,4,27,Male,Books,1.4,Returned,Positive,15.27,WELCOME5,NaN,22
22,2023-01-23,1829,112,2,16.26,0.12,28.6176,5,North,Online,False,1,36,Female,Electronics,3.4,Returned,Neutral,10.01,nan,1.0,23
23,2023-01-24,1653,147,5,74.43,0.06,349.8210,2,South,Online,True,2,47,Male,Electronics,1.3,Not Returned,Positive,10.60,nan,2.6,24
24,2023-01-25,1338,168,3,29.68,0.09,81.0264,7,East,Cash,True,3,46,Other,Electronics,1.4,Returned,Neutral,19.17,WELCOME5,3.4,25
25,2023-01-26,1248,154,7,63.55,0.02,435.9530,8,West,Online,False,3,44,Female,Clothing,2.8,Returned,Neutral,17.90,nan,1.1,26
26,2023-01-27,1621,195,1,52.52,0.18,43.0664,6,South,Cash,True,4,45,Female,Electronics,1.2,Not Returned,Negative,6.18,FREESHIP,1.2,27
27,2023-01-28,1075,185,4,65.82,0.11,234.3192,3,East,Online,True,4,60,Female,Clothing,3.3,Not Returned,Positive,10.48,FREESHIP,NaN,28
28,2023-01-29,1941,162,2,14.08,0.08,25.9072,1,East,Credit Card,False,1,62,Male,Clothing,1.3,Not Returned,Positive,6.95,nan,NaN,29
29,2023-01-30,1877,183,9,68.99,0.23,478.1007,8,East,Cash,False,1,30,Male,Electronics,4.8,Returned,Positive,12.70,WELCOME5,NaN,30
30,2023-01-31,1930,191,4,72.22,0.08,265.7696,3,South,Cash,True,4,53,Female,Food,1.5,Returned,Neutral,NaN,nan,3.3,31
31,2023-02-01,1811,130,7,22.75,0.17,132.1775,5,East,Cash,False,6,62,Female,Electronics,2.8,Returned,Positive,14.11,nan,4.2,32
32,2023-02-02,1463,118,5,15.89,0.18,65.1490,9,East,Cash,False,5,40,Other,Food,2.4,Not Returned,Negative,17.51,nan,1.4,33
33,2023-02-03,1110,129,1,25.91,0.14,22.2826,3,North,Credit Card,False,1,43,Female,Electronics,4.5,Returned,Neutral,19.19,SAVE10,2.6,34
34,2023-02-04,1969,139,3,39.35,0.29,83.8155,8,East,Online,True,5,21,Male,Clothing,3.0,Returned,Negative,9.16,FREESHIP,2.0,35
35,2023-01-27,1621,195,1,52.52,0.18,43.0664,6,South,Cash,True,4,45,Female,Electronics,1.2,Not Returned,Negative,6.18,FREESHIP,1.2,36
36,2023-01-14,1117,185,2,14.22,0.12,25.0272,7,East,Cash,False,3,23,Female,Food,4.3,Returned,Negative,7.34,FREESHIP,4.0,37
37,2023-01-25,1338,168,3,29.68,0.09,81.0264,7,East,Cash,True,3,46,Other,Electronics,1.4,Returned,Neutral,19.17,WELCOME5,3.4,38
38,2023-02-05,1500,150,2,-20.00,0.10,0.0000,5,North,Credit Card,True,3,25,Male,Electronics,4.5,Not Returned,Positive,NaN,NaN,NaN,39
39,2023-02-06,1501,151,3,-15.00,0.20,0.0000,6,South,Cash,False,4,34,Female,Clothing,3.0,Returned,Neutral,NaN,NaN,NaN,40
40,2023-02-07,1502,152,1,-30.00,0.15,0.0000,7,East,Online,True,2,45,Other,Books,5.0,Not Returned,Negative,NaN,NaN,NaN,41

<div class="alert alert-success">

**Solution 09:**
</div>

In [21]:
# 9. Validating Date Formats in a DataFrame
# Write a Pandas program to validate date formats in a DataFrame.

def validate_date_formats(date_column, dataframe):
    if not pd.api.types.is_datetime64_any_dtype(dataframe[date_column]):
        print("Column {:>30} is not a datetime type and will be skipped.".format(date_column))
        return
    else:
        invalid_dates = dataframe[~dataframe[date_column].dt.strftime('%Y-%m-%d').str.match(r'^\d{4}-\d{2}-\d{2}$')]
    if not invalid_dates.empty:
        print("Column {:>30} INVALID DATES DETECTED.\n####### INVALID DATES #######".format(date_column))
        display(invalid_dates)
    else:
        print("Column {:>30} has no invalid dates detected.".format(date_column))

# Apply to all columns
for col in df.columns:
    validate_date_formats(col, df)

Column                           date has no invalid dates detected.
Column                    customer_id is not a datetime type and will be skipped.
Column                     product_id is not a datetime type and will be skipped.
Column                       quantity is not a datetime type and will be skipped.
Column                          price is not a datetime type and will be skipped.
Column                       discount is not a datetime type and will be skipped.
Column                        revenue is not a datetime type and will be skipped.
Column                       store_id is not a datetime type and will be skipped.
Column                         region is not a datetime type and will be skipped.
Column                 payment_method is not a datetime type and will be skipped.
Column                      is_member is not a datetime type and will be skipped.
Column                  delivery_days is not a datetime type and will be skipped.
Column                   customer_age is not a datetime type and will be skipped.
Column                         gender is not a datetime type and will be skipped.
Column               product_category is not a datetime type and will be skipped.
Column                         rating is not a datetime type and will be skipped.
Column                  return_status is not a datetime type and will be skipped.
Column                       feedback is not a datetime type and will be skipped.
Column                  shipping_cost is not a datetime type and will be skipped.
Column                    coupon_code is not a datetime type and will be skipped.
Column                delivery_rating is not a datetime type and will be skipped.
Column                      unique_id is not a datetime type and will be skipped.

<div class="alert alert-warning">

**10. Ensuring No Missing Values in a Critical Column**

**Write a Pandas program that ensures no missing values in a critical column.**

</div>

In [22]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Add 3 duplicate rows
df = pd.concat([df, df.sample(n=3, random_state=42)], ignore_index=True)

# Add 3 more rows with negative price
df = pd.concat([df, pd.DataFrame({
    'date': pd.date_range(start='2023-02-05', periods=3, freq='D'),
    'customer_id': [1500, 1501, 1502],
    'product_id': [150, 151, 152],
    'quantity': [2, 3, 1],
    'price': [-20.00, -15.00, -30.00],  # Negative prices
    'discount': [0.1, 0.2, 0.15],
    'revenue': [0, 0, 0],  # Placeholder; will be recalculated
    'store_id': [5, 6, 7],
    'region': ['North', 'South', 'East'],
    'payment_method': ['Credit Card', 'Cash', 'Online'],
    'is_member': [True, False, True],
    'delivery_days': [3, 4, 2],
    'customer_age': [25, 34, 45],
    'gender': ['Male', 'Female', 'Other'],
    'product_category': ['Electronics', 'Clothing', 'Books'],
    'rating': [4.5, 3.0, 5.0],
    'return_status': ['Not Returned', 'Returned', 'Not Returned'],
    'feedback': ['Positive', 'Neutral', 'Negative'],
})], ignore_index=True)

# add column with unique value
df['unique_id'] = pd.Series(range(1, len(df) + 1))

# add outliers
df.loc[[0,3,5], ['price']] = [9999.99, 8888.88, 7777.77]

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,unique_id
0,2023-01-01,1409,187,6,9999.99,0.28,393.1200,6,South,Cash,False,6,54,Male,Food,5.0,Not Returned,Neutral,13.61,nan,4.4,1
1,2023-01-02,1245,122,6,56.23,0.04,323.8848,1,North,Online,True,1,27,Male,Books,3.5,Returned,Neutral,5.42,FREESHIP,NaN,2
2,2023-01-03,1529,149,8,98.66,0.28,568.2816,4,North,Online,False,3,27,Female,Books,1.1,Not Returned,Positive,7.35,SAVE10,NaN,3
3,2023-01-04,1361,140,5,8888.88,0.04,460.8480,1,West,Credit Card,False,1,68,Other,Electronics,2.9,Returned,Neutral,15.20,SAVE10,1.8,4
4,2023-01-05,1739,191,3,46.62,0.15,118.8810,6,East,Cash,True,1,61,Male,Clothing,4.4,Returned,Positive,11.61,nan,NaN,5
5,2023-01-06,1106,138,3,7777.77,0.27,181.5948,9,South,Cash,True,2,24,Female,Electronics,4.1,Not Returned,Neutral,NaN,nan,NaN,6
6,2023-01-07,1477,165,4,86.90,0.03,337.1720,9,East,Credit Card,False,1,66,Other,Clothing,4.8,Not Returned,Negative,19.40,SAVE10,4.7,7
7,2023-01-08,1566,157,7,26.69,0.22,145.7274,9,North,Credit Card,False,2,68,Female,Clothing,2.9,Not Returned,Positive,NaN,SAVE10,4.2,8
8,2023-01-09,1453,115,9,54.12,0.07,452.9844,6,South,Credit Card,False,3,67,Male,Clothing,2.7,Not Returned,Negative,16.62,SAVE10,NaN,9
9,2023-01-10,1985,112,3,29.66,0.13,77.4126,3,South,Credit Card,True,6,31,Male,Food,4.8,Not Returned,Negative,12.03,WELCOME5,3.6,10
10,2023-01-11,1991,182,6,45.34,0.12,239.3952,9,West,Credit Card,False,6,34,Male,Books,3.9,Not Returned,Neutral,6.62,nan,4.9,11
11,2023-01-12,1369,174,2,59.11,0.02,115.8556,6,North,Cash,True,4,32,Other,Food,4.8,Returned,Positive,13.27,WELCOME5,NaN,12
12,2023-01-13,1448,152,4,34.58,0.14,118.9552,3,North,Credit Card,False,2,33,Other,Clothing,4.0,Not Returned,Neutral,18.42,FREESHIP,1.6,13
13,2023-01-14,1841,185,4,65.77,0.09,239.4028,6,East,Credit Card,True,1,57,Female,Books,4.1,Not Returned,Neutral,NaN,SAVE10,2.8,14
14,2023-01-15,1531,198,9,77.61,0.11,621.6561,1,North,Online,False,6,32,Other,Books,1.8,Not Returned,Positive,17.69,nan,2.5,15
15,2023-01-16,1698,129,7,88.71,0.03,602.3409,7,West,Cash,False,6,19,Other,Books,4.6,Returned,Negative,10.87,SAVE10,1.1,16
16,2023-01-17,1314,192,3,69.57,0.27,152.3583,8,South,Cash,True,1,57,Male,Food,3.4,Returned,Positive,13.89,WELCOME5,4.8,17
17,2023-01-18,1165,115,7,45.23,0.08,291.2812,3,West,Online,True,4,41,Female,Clothing,3.5,Not Returned,Neutral,12.16,WELCOME5,NaN,18
18,2023-01-19,1942,107,3,66.28,0.29,141.1764,1,North,Online,False,5,20,Other,Food,3.1,Not Returned,Positive,13.40,WELCOME5,2.4,19
19,2023-01-20,1019,182,8,80.73,0.08,594.1728,4,East,Online,False,1,42,Female,Electronics,1.2,Not Returned,Neutral,11.36,nan,2.0,20
20,2023-01-21,1497,142,1,22.77,0.21,17.9883,6,South,Credit Card,True,2,21,Male,Clothing,3.0,Not Returned,Neutral,NaN,nan,3.0,21
21,2023-01-22,1820,170,5,44.63,0.17,185.2145,8,North,Online,True,3,37,Male,Food,2.9,Not Returned,Negative,11.65,FREESHIP,NaN,22
22,2023-01-23,1191,177,8,65.18,0.25,391.0800,8,East,Online,False,3,62,Female,Books,1.3,Not Returned,Neutral,5.34,nan,4.9,23
23,2023-01-24,1092,127,7,38.42,0.24,204.3944,7,South,Cash,True,6,33,Other,Food,2.5,Not Returned,Positive,16.86,SAVE10,NaN,24
24,2023-01-25,1638,191,6,86.14,0.27,377.2932,6,West,Credit Card,True,5,57,Female,Clothing,3.2,Returned,Neutral,5.75,FREESHIP,NaN,25
25,2023-01-26,1235,173,4,29.63,0.26,87.7048,1,West,Cash,True,3,60,Male,Books,3.4,Returned,Negative,5.92,FREESHIP,NaN,26
26,2023-01-27,1062,136,1,54.49,0.07,50.6757,1,South,Credit Card,True,4,39,Male,Clothing,3.0,Returned,Negative,15.21,nan,NaN,27
27,2023-01-28,1142,148,4,15.68,0.17,52.0576,9,South,Online,False,3,43,Female,Clothing,3.3,Not Returned,Negative,18.82,FREESHIP,4.4,28
28,2023-01-29,1922,105,2,97.85,0.24,148.7320,1,South,Cash,True,1,39,Male,Electronics,3.4,Returned,Neutral,17.48,nan,2.5,29
29,2023-01-30,1470,165,9,74.29,0.04,641.8656,2,North,Cash,False,3,52,Female,Food,4.3,Not Returned,Positive,NaN,SAVE10,3.2,30
30,2023-01-31,1603,143,8,43.77,0.02,343.1568,2,South,Cash,False,5,57,Female,Food,4.3,Not Returned,Negative,15.10,SAVE10,2.0,31
31,2023-02-01,1669,180,7,34.36,0.30,168.3640,5,South,Online,False,3,61,Female,Food,1.7,Not Returned,Neutral,18.62,nan,3.4,32
32,2023-02-02,1429,115,3,48.48,0.23,111.9888,3,West,Cash,False,5,20,Female,Books,2.1,Not Returned,Negative,17.34,FREESHIP,1.5,33
33,2023-02-03,1778,161,5,14.54,0.05,69.0650,8,West,Cash,False,5,41,Female,Food,4.4,Not Returned,Positive,10.53,FREESHIP,2.2,34
34,2023-02-04,1344,100,6,33.14,0.19,161.0604,4,East,Online,False,4,26,Other,Clothing,3.3,Not Returned,Negative,14.06,nan,1.8,35
35,2023-01-27,1062,136,1,54.49,0.07,50.6757,1,South,Credit Card,True,4,39,Male,Clothing,3.0,Returned,Negative,15.21,nan,NaN,36
36,2023-01-14,1841,185,4,65.77,0.09,239.4028,6,East,Credit Card,True,1,57,Female,Books,4.1,Not Returned,Neutral,NaN,SAVE10,2.8,37
37,2023-01-25,1638,191,6,86.14,0.27,377.2932,6,West,Credit Card,True,5,57,Female,Clothing,3.2,Returned,Neutral,5.75,FREESHIP,NaN,38
38,2023-02-05,1500,150,2,-20.00,0.10,0.0000,5,North,Credit Card,True,3,25,Male,Electronics,4.5,Not Returned,Positive,NaN,NaN,NaN,39
39,2023-02-06,1501,151,3,-15.00,0.20,0.0000,6,South,Cash,False,4,34,Female,Clothing,3.0,Returned,Neutral,NaN,NaN,NaN,40
40,2023-02-07,1502,152,1,-30.00,0.15,0.0000,7,East,Online,True,2,45,Other,Books,5.0,Not Returned,Negative,NaN,NaN,NaN,41

<div class="alert alert-success">

**Solution 10:**
</div>

In [23]:
# 10. Ensuring No Missing Values in a Critical Column
# Write a Pandas program that ensures no missing values in a critical column.

def check_missing_values(column_name, dataframe):
    missing_values = dataframe[column_name].isnull().sum()
    if missing_values > 0:
        print("Column {:>30} has {} missing values.".format(column_name, missing_values))
        display(dataframe[dataframe[column_name].isnull()])
    else:
        print("Column {:>30} has no missing values.".format(column_name))

# Apply to all columns
for col in df.columns:
    check_missing_values(col, df)

Column                           date has no missing values.
Column                    customer_id has no missing values.
Column                     product_id has no missing values.
Column                       quantity has no missing values.
Column                          price has no missing values.
Column                       discount has no missing values.
Column                        revenue has no missing values.
Column                       store_id has no missing values.
Column                         region has no missing values.
Column                 payment_method has no missing values.
Column                      is_member has no missing values.
Column                  delivery_days has no missing values.
Column                   customer_age has no missing values.
Column                         gender has no missing values.
Column               product_category has no missing values.
Column                         rating has no missing values.
Column                  return_status has no missing values.
Column                       feedback has no missing values.
Column                  shipping_cost has 9 missing values.

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,unique_id
5,2023-01-06,1106,138,3,7777.77,0.27,181.5948,9,South,Cash,True,2,24,Female,Electronics,4.1,Not Returned,Neutral,NaN,nan,NaN,6
7,2023-01-08,1566,157,7,26.69,0.22,145.7274,9,North,Credit Card,False,2,68,Female,Clothing,2.9,Not Returned,Positive,NaN,SAVE10,4.2,8
13,2023-01-14,1841,185,4,65.77,0.09,239.4028,6,East,Credit Card,True,1,57,Female,Books,4.1,Not Returned,Neutral,NaN,SAVE10,2.8,14
20,2023-01-21,1497,142,1,22.77,0.21,17.9883,6,South,Credit Card,True,2,21,Male,Clothing,3.0,Not Returned,Neutral,NaN,nan,3.0,21
29,2023-01-30,1470,165,9,74.29,0.04,641.8656,2,North,Cash,False,3,52,Female,Food,4.3,Not Returned,Positive,NaN,SAVE10,3.2,30
36,2023-01-14,1841,185,4,65.77,0.09,239.4028,6,East,Credit Card,True,1,57,Female,Books,4.1,Not Returned,Neutral,NaN,SAVE10,2.8,37
38,2023-02-05,1500,150,2,-20.00,0.10,0.0000,5,North,Credit Card,True,3,25,Male,Electronics,4.5,Not Returned,Positive,NaN,NaN,NaN,39
39,2023-02-06,1501,151,3,-15.00,0.20,0.0000,6,South,Cash,False,4,34,Female,Clothing,3.0,Returned,Neutral,NaN,NaN,NaN,40
40,2023-02-07,1502,152,1,-30.00,0.15,0.0000,7,East,Online,True,2,45,Other,Books,5.0,Not Returned,Negative,NaN,NaN,NaN,41

Column                    coupon_code has 3 missing values.

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,unique_id
38,2023-02-05,1500,150,2,-20.0,0.10,0.0,5,North,Credit Card,True,3,25,Male,Electronics,4.5,Not Returned,Positive,NaN,NaN,NaN,39
39,2023-02-06,1501,151,3,-15.0,0.20,0.0,6,South,Cash,False,4,34,Female,Clothing,3.0,Returned,Neutral,NaN,NaN,NaN,40
40,2023-02-07,1502,152,1,-30.0,0.15,0.0,7,East,Online,True,2,45,Other,Books,5.0,Not Returned,Negative,NaN,NaN,NaN,41

Column                delivery_rating has 17 missing values.

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,unique_id
1,2023-01-02,1245,122,6,56.23,0.04,323.8848,1,North,Online,True,1,27,Male,Books,3.5,Returned,Neutral,5.42,FREESHIP,NaN,2
2,2023-01-03,1529,149,8,98.66,0.28,568.2816,4,North,Online,False,3,27,Female,Books,1.1,Not Returned,Positive,7.35,SAVE10,NaN,3
4,2023-01-05,1739,191,3,46.62,0.15,118.8810,6,East,Cash,True,1,61,Male,Clothing,4.4,Returned,Positive,11.61,nan,NaN,5
5,2023-01-06,1106,138,3,7777.77,0.27,181.5948,9,South,Cash,True,2,24,Female,Electronics,4.1,Not Returned,Neutral,NaN,nan,NaN,6
8,2023-01-09,1453,115,9,54.12,0.07,452.9844,6,South,Credit Card,False,3,67,Male,Clothing,2.7,Not Returned,Negative,16.62,SAVE10,NaN,9
11,2023-01-12,1369,174,2,59.11,0.02,115.8556,6,North,Cash,True,4,32,Other,Food,4.8,Returned,Positive,13.27,WELCOME5,NaN,12
17,2023-01-18,1165,115,7,45.23,0.08,291.2812,3,West,Online,True,4,41,Female,Clothing,3.5,Not Returned,Neutral,12.16,WELCOME5,NaN,18
21,2023-01-22,1820,170,5,44.63,0.17,185.2145,8,North,Online,True,3,37,Male,Food,2.9,Not Returned,Negative,11.65,FREESHIP,NaN,22
23,2023-01-24,1092,127,7,38.42,0.24,204.3944,7,South,Cash,True,6,33,Other,Food,2.5,Not Returned,Positive,16.86,SAVE10,NaN,24
24,2023-01-25,1638,191,6,86.14,0.27,377.2932,6,West,Credit Card,True,5,57,Female,Clothing,3.2,Returned,Neutral,5.75,FREESHIP,NaN,25
25,2023-01-26,1235,173,4,29.63,0.26,87.7048,1,West,Cash,True,3,60,Male,Books,3.4,Returned,Negative,5.92,FREESHIP,NaN,26
26,2023-01-27,1062,136,1,54.49,0.07,50.6757,1,South,Credit Card,True,4,39,Male,Clothing,3.0,Returned,Negative,15.21,nan,NaN,27
35,2023-01-27,1062,136,1,54.49,0.07,50.6757,1,South,Credit Card,True,4,39,Male,Clothing,3.0,Returned,Negative,15.21,nan,NaN,36
37,2023-01-25,1638,191,6,86.14,0.27,377.2932,6,West,Credit Card,True,5,57,Female,Clothing,3.2,Returned,Neutral,5.75,FREESHIP,NaN,38
38,2023-02-05,1500,150,2,-20.00,0.10,0.0000,5,North,Credit Card,True,3,25,Male,Electronics,4.5,Not Returned,Positive,NaN,NaN,NaN,39
39,2023-02-06,1501,151,3,-15.00,0.20,0.0000,6,South,Cash,False,4,34,Female,Clothing,3.0,Returned,Neutral,NaN,NaN,NaN,40
40,2023-02-07,1502,152,1,-30.00,0.15,0.0000,7,East,Online,True,2,45,Other,Books,5.0,Not Returned,Negative,NaN,NaN,NaN,41

Column                      unique_id has no missing values.

<div class="alert alert-warning">

**11. Validating String Length in a DataFrame Column**

**Write a Pandas program that validates string length in a DataFrame column.**

</div>

In [24]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Add 3 duplicate rows
df = pd.concat([df, df.sample(n=3, random_state=42)], ignore_index=True)

# Add 3 more rows with negative price
df = pd.concat([df, pd.DataFrame({
    'date': pd.date_range(start='2023-02-05', periods=3, freq='D'),
    'customer_id': [1500, 1501, 1502],
    'product_id': [150, 151, 152],
    'quantity': [2, 3, 1],
    'price': [-20.00, -15.00, -30.00],  # Negative prices
    'discount': [0.1, 0.2, 0.15],
    'revenue': [0, 0, 0],  # Placeholder; will be recalculated
    'store_id': [5, 6, 7],
    'region': ['North', 'South', 'East'],
    'payment_method': ['Credit Card', 'Cash', 'Online'],
    'is_member': [True, False, True],
    'delivery_days': [3, 4, 2],
    'customer_age': [25, 34, 45],
    'gender': ['Male', 'Female', 'Other'],
    'product_category': ['Electronics', 'Clothing', 'Books'],
    'rating': [4.5, 3.0, 5.0],
    'return_status': ['Not Returned', 'Returned', 'Not Returned'],
    'feedback': ['Positive', 'Neutral', 'Negative'],
})], ignore_index=True)

# add column with unique value
df['unique_id'] = pd.Series(range(1, len(df) + 1))

# add outliers
df.loc[[0,3,5], ['price']] = [9999.99, 8888.88, 7777.77]

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,unique_id
0,2023-01-01,1792,161,6,9999.99,0.21,449.2098,5,East,Online,False,6,45,Other,Clothing,3.2,Not Returned,Neutral,8.21,nan,4.9,1
1,2023-01-02,1478,175,4,11.96,0.18,39.2288,9,East,Cash,True,3,25,Male,Books,1.3,Returned,Positive,8.44,SAVE10,1.9,2
2,2023-01-03,1164,153,4,99.41,0.07,369.8052,9,North,Cash,True,6,25,Female,Clothing,4.9,Returned,Negative,NaN,nan,4.6,3
3,2023-01-04,1377,142,4,8888.88,0.21,241.8032,6,North,Cash,False,4,37,Female,Electronics,2.8,Not Returned,Negative,10.22,nan,3.9,4
4,2023-01-05,1247,153,3,85.99,0.26,190.8978,3,South,Online,False,3,27,Male,Electronics,4.7,Not Returned,Neutral,NaN,FREESHIP,4.4,5
5,2023-01-06,1129,169,8,7777.77,0.03,692.5800,2,West,Online,True,5,55,Male,Food,3.8,Not Returned,Positive,NaN,SAVE10,NaN,6
6,2023-01-07,1923,180,4,68.77,0.14,236.5688,5,East,Credit Card,False,1,41,Male,Food,4.8,Returned,Neutral,NaN,SAVE10,NaN,7
7,2023-01-08,1443,128,5,95.84,0.22,373.7760,9,East,Cash,False,5,18,Male,Clothing,2.7,Not Returned,Neutral,19.67,nan,4.6,8
8,2023-01-09,1188,141,6,26.66,0.26,118.3704,3,East,Credit Card,True,4,41,Female,Books,3.3,Not Returned,Neutral,NaN,nan,2.4,9
9,2023-01-10,1224,132,1,50.80,0.06,47.7520,8,East,Cash,True,4,21,Other,Food,1.9,Not Returned,Positive,7.46,nan,NaN,10
10,2023-01-11,1818,197,9,55.84,0.11,447.2784,9,South,Credit Card,False,5,30,Female,Food,1.9,Returned,Neutral,7.25,FREESHIP,NaN,11
11,2023-01-12,1201,103,5,94.40,0.27,344.5600,5,West,Cash,False,2,29,Female,Clothing,5.0,Not Returned,Positive,10.90,nan,4.0,12
12,2023-01-13,1337,196,7,38.04,0.23,205.0356,9,West,Credit Card,True,3,35,Male,Clothing,1.9,Not Returned,Negative,16.34,WELCOME5,NaN,13
13,2023-01-14,1659,172,1,67.33,0.00,67.3300,4,West,Credit Card,False,5,38,Female,Books,3.2,Returned,Neutral,NaN,WELCOME5,3.5,14
14,2023-01-15,1434,199,5,81.03,0.24,307.9140,9,East,Cash,True,3,25,Other,Electronics,3.2,Not Returned,Positive,7.25,SAVE10,NaN,15
15,2023-01-16,1687,149,5,85.78,0.07,398.8770,2,East,Cash,False,2,58,Male,Electronics,2.9,Returned,Positive,6.86,WELCOME5,1.8,16
16,2023-01-17,1384,189,5,29.98,0.16,125.9160,4,East,Online,True,4,34,Female,Food,2.1,Returned,Positive,19.25,nan,NaN,17
17,2023-01-18,1180,185,4,71.48,0.04,274.4832,4,North,Cash,True,3,54,Female,Books,3.3,Not Returned,Negative,13.84,nan,4.4,18
18,2023-01-19,1905,181,9,24.53,0.21,174.4083,8,West,Cash,False,4,21,Other,Electronics,1.1,Returned,Positive,8.02,WELCOME5,NaN,19
19,2023-01-20,1289,190,6,38.36,0.15,195.6360,5,West,Credit Card,False,3,64,Female,Clothing,2.6,Not Returned,Positive,17.19,FREESHIP,1.4,20
20,2023-01-21,1758,149,7,38.64,0.14,232.6128,4,North,Credit Card,True,6,60,Female,Books,4.2,Returned,Neutral,18.90,nan,NaN,21
21,2023-01-22,1262,139,3,34.57,0.17,86.0793,6,East,Cash,True,2,49,Other,Electronics,1.7,Not Returned,Positive,14.21,FREESHIP,2.9,22
22,2023-01-23,1258,104,6,41.20,0.16,207.6480,3,North,Cash,True,1,52,Female,Books,1.0,Not Returned,Neutral,19.35,nan,NaN,23
23,2023-01-24,1384,174,9,13.55,0.04,117.0720,2,East,Cash,False,2,63,Female,Food,3.8,Returned,Negative,10.86,WELCOME5,4.2,24
24,2023-01-25,1400,115,2,67.76,0.01,134.1648,8,West,Cash,False,6,20,Other,Clothing,2.1,Returned,Positive,NaN,nan,4.3,25
25,2023-01-26,1248,172,9,38.61,0.23,267.5673,8,North,Cash,True,6,52,Other,Books,2.4,Not Returned,Positive,14.31,FREESHIP,1.7,26
26,2023-01-27,1927,183,5,93.92,0.24,356.8960,7,South,Cash,False,3,32,Other,Clothing,2.6,Not Returned,Neutral,10.46,nan,1.5,27
27,2023-01-28,1858,134,9,91.73,0.05,784.2915,4,South,Credit Card,False,6,69,Male,Food,3.4,Not Returned,Neutral,17.41,SAVE10,3.3,28
28,2023-01-29,1496,171,9,64.48,0.26,429.4368,7,North,Credit Card,True,1,52,Male,Electronics,3.8,Not Returned,Neutral,14.75,nan,3.5,29
29,2023-01-30,1732,174,4,51.33,0.21,162.2028,5,North,Cash,True,3,40,Other,Food,2.5,Not Returned,Positive,NaN,SAVE10,4.8,30
30,2023-01-31,1122,118,4,46.07,0.28,132.6816,1,North,Credit Card,True,6,59,Female,Electronics,3.8,Not Returned,Positive,7.69,FREESHIP,NaN,31
31,2023-02-01,1858,168,1,41.71,0.04,40.0416,7,North,Credit Card,False,6,42,Male,Books,2.9,Not Returned,Neutral,18.21,WELCOME5,3.6,32
32,2023-02-02,1191,182,6,45.41,0.02,267.0108,9,West,Credit Card,False,2,45,Other,Food,4.4,Not Returned,Neutral,NaN,FREESHIP,NaN,33
33,2023-02-03,1622,140,5,42.39,0.02,207.7110,4,East,Online,True,2,66,Other,Electronics,1.5,Returned,Neutral,15.26,FREESHIP,NaN,34
34,2023-02-04,1708,173,2,87.90,0.11,156.4620,6,East,Cash,False,1,60,Male,Books,1.7,Returned,Neutral,8.04,nan,4.6,35
35,2023-01-27,1927,183,5,93.92,0.24,356.8960,7,South,Cash,False,3,32,Other,Clothing,2.6,Not Returned,Neutral,10.46,nan,1.5,36
36,2023-01-14,1659,172,1,67.33,0.00,67.3300,4,West,Credit Card,False,5,38,Female,Books,3.2,Returned,Neutral,NaN,WELCOME5,3.5,37
37,2023-01-25,1400,115,2,67.76,0.01,134.1648,8,West,Cash,False,6,20,Other,Clothing,2.1,Returned,Positive,NaN,nan,4.3,38
38,2023-02-05,1500,150,2,-20.00,0.10,0.0000,5,North,Credit Card,True,3,25,Male,Electronics,4.5,Not Returned,Positive,NaN,NaN,NaN,39
39,2023-02-06,1501,151,3,-15.00,0.20,0.0000,6,South,Cash,False,4,34,Female,Clothing,3.0,Returned,Neutral,NaN,NaN,NaN,40
40,2023-02-07,1502,152,1,-30.00,0.15,0.0000,7,East,Online,True,2,45,Other,Books,5.0,Not Returned,Negative,NaN,NaN,NaN,41

<div class="alert alert-success">

**Solution 11:**
</div>

In [25]:
# 11. Validating String Length in a DataFrame Column
# Write a Pandas program that validates string length in a DataFrame column.

def validate_string_length(dataframe, column_name, min_length: int=0, max_length: int=100):
    if not pd.api.types.is_string_dtype(dataframe[column_name]):
        print("Column {:>30} is not a string type and will be skipped.".format(column_name))
        return
    else:
        invalid_length = dataframe[(dataframe[column_name].str.len() < min_length) | (dataframe[column_name].str.len() > max_length)]
    if not invalid_length.empty:
        print("Column {:>30} INVALID LENGTH DETECTED.\n####### INVALID LENGTH #######".format(column_name))
        display(invalid_length)
    else:
        print("Column {:>30} has no invalid length detected.".format(column_name))

# Apply to all columns
for col in df.columns:
    validate_string_length(df, col, min_length=0, max_length=4)

Column                           date is not a string type and will be skipped.
Column                    customer_id is not a string type and will be skipped.
Column                     product_id is not a string type and will be skipped.
Column                       quantity is not a string type and will be skipped.
Column                          price is not a string type and will be skipped.
Column                       discount is not a string type and will be skipped.
Column                        revenue is not a string type and will be skipped.
Column                       store_id is not a string type and will be skipped.
Column                         region INVALID LENGTH DETECTED.
####### INVALID LENGTH #######

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,unique_id
2,2023-01-03,1164,153,4,99.41,0.07,369.8052,9,North,Cash,True,6,25,Female,Clothing,4.9,Returned,Negative,NaN,nan,4.6,3
3,2023-01-04,1377,142,4,8888.88,0.21,241.8032,6,North,Cash,False,4,37,Female,Electronics,2.8,Not Returned,Negative,10.22,nan,3.9,4
4,2023-01-05,1247,153,3,85.99,0.26,190.8978,3,South,Online,False,3,27,Male,Electronics,4.7,Not Returned,Neutral,NaN,FREESHIP,4.4,5
10,2023-01-11,1818,197,9,55.84,0.11,447.2784,9,South,Credit Card,False,5,30,Female,Food,1.9,Returned,Neutral,7.25,FREESHIP,NaN,11
17,2023-01-18,1180,185,4,71.48,0.04,274.4832,4,North,Cash,True,3,54,Female,Books,3.3,Not Returned,Negative,13.84,nan,4.4,18
20,2023-01-21,1758,149,7,38.64,0.14,232.6128,4,North,Credit Card,True,6,60,Female,Books,4.2,Returned,Neutral,18.90,nan,NaN,21
22,2023-01-23,1258,104,6,41.20,0.16,207.6480,3,North,Cash,True,1,52,Female,Books,1.0,Not Returned,Neutral,19.35,nan,NaN,23
25,2023-01-26,1248,172,9,38.61,0.23,267.5673,8,North,Cash,True,6,52,Other,Books,2.4,Not Returned,Positive,14.31,FREESHIP,1.7,26
26,2023-01-27,1927,183,5,93.92,0.24,356.8960,7,South,Cash,False,3,32,Other,Clothing,2.6,Not Returned,Neutral,10.46,nan,1.5,27
27,2023-01-28,1858,134,9,91.73,0.05,784.2915,4,South,Credit Card,False,6,69,Male,Food,3.4,Not Returned,Neutral,17.41,SAVE10,3.3,28
28,2023-01-29,1496,171,9,64.48,0.26,429.4368,7,North,Credit Card,True,1,52,Male,Electronics,3.8,Not Returned,Neutral,14.75,nan,3.5,29
29,2023-01-30,1732,174,4,51.33,0.21,162.2028,5,North,Cash,True,3,40,Other,Food,2.5,Not Returned,Positive,NaN,SAVE10,4.8,30
30,2023-01-31,1122,118,4,46.07,0.28,132.6816,1,North,Credit Card,True,6,59,Female,Electronics,3.8,Not Returned,Positive,7.69,FREESHIP,NaN,31
31,2023-02-01,1858,168,1,41.71,0.04,40.0416,7,North,Credit Card,False,6,42,Male,Books,2.9,Not Returned,Neutral,18.21,WELCOME5,3.6,32
35,2023-01-27,1927,183,5,93.92,0.24,356.8960,7,South,Cash,False,3,32,Other,Clothing,2.6,Not Returned,Neutral,10.46,nan,1.5,36
38,2023-02-05,1500,150,2,-20.00,0.10,0.0000,5,North,Credit Card,True,3,25,Male,Electronics,4.5,Not Returned,Positive,NaN,NaN,NaN,39
39,2023-02-06,1501,151,3,-15.00,0.20,0.0000,6,South,Cash,False,4,34,Female,Clothing,3.0,Returned,Neutral,NaN,NaN,NaN,40

Column                 payment_method INVALID LENGTH DETECTED.
####### INVALID LENGTH #######

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,unique_id
0,2023-01-01,1792,161,6,9999.99,0.21,449.2098,5,East,Online,False,6,45,Other,Clothing,3.2,Not Returned,Neutral,8.21,nan,4.9,1
4,2023-01-05,1247,153,3,85.99,0.26,190.8978,3,South,Online,False,3,27,Male,Electronics,4.7,Not Returned,Neutral,NaN,FREESHIP,4.4,5
5,2023-01-06,1129,169,8,7777.77,0.03,692.5800,2,West,Online,True,5,55,Male,Food,3.8,Not Returned,Positive,NaN,SAVE10,NaN,6
6,2023-01-07,1923,180,4,68.77,0.14,236.5688,5,East,Credit Card,False,1,41,Male,Food,4.8,Returned,Neutral,NaN,SAVE10,NaN,7
8,2023-01-09,1188,141,6,26.66,0.26,118.3704,3,East,Credit Card,True,4,41,Female,Books,3.3,Not Returned,Neutral,NaN,nan,2.4,9
10,2023-01-11,1818,197,9,55.84,0.11,447.2784,9,South,Credit Card,False,5,30,Female,Food,1.9,Returned,Neutral,7.25,FREESHIP,NaN,11
12,2023-01-13,1337,196,7,38.04,0.23,205.0356,9,West,Credit Card,True,3,35,Male,Clothing,1.9,Not Returned,Negative,16.34,WELCOME5,NaN,13
13,2023-01-14,1659,172,1,67.33,0.00,67.3300,4,West,Credit Card,False,5,38,Female,Books,3.2,Returned,Neutral,NaN,WELCOME5,3.5,14
16,2023-01-17,1384,189,5,29.98,0.16,125.9160,4,East,Online,True,4,34,Female,Food,2.1,Returned,Positive,19.25,nan,NaN,17
19,2023-01-20,1289,190,6,38.36,0.15,195.6360,5,West,Credit Card,False,3,64,Female,Clothing,2.6,Not Returned,Positive,17.19,FREESHIP,1.4,20
20,2023-01-21,1758,149,7,38.64,0.14,232.6128,4,North,Credit Card,True,6,60,Female,Books,4.2,Returned,Neutral,18.90,nan,NaN,21
27,2023-01-28,1858,134,9,91.73,0.05,784.2915,4,South,Credit Card,False,6,69,Male,Food,3.4,Not Returned,Neutral,17.41,SAVE10,3.3,28
28,2023-01-29,1496,171,9,64.48,0.26,429.4368,7,North,Credit Card,True,1,52,Male,Electronics,3.8,Not Returned,Neutral,14.75,nan,3.5,29
30,2023-01-31,1122,118,4,46.07,0.28,132.6816,1,North,Credit Card,True,6,59,Female,Electronics,3.8,Not Returned,Positive,7.69,FREESHIP,NaN,31
31,2023-02-01,1858,168,1,41.71,0.04,40.0416,7,North,Credit Card,False,6,42,Male,Books,2.9,Not Returned,Neutral,18.21,WELCOME5,3.6,32
32,2023-02-02,1191,182,6,45.41,0.02,267.0108,9,West,Credit Card,False,2,45,Other,Food,4.4,Not Returned,Neutral,NaN,FREESHIP,NaN,33
33,2023-02-03,1622,140,5,42.39,0.02,207.7110,4,East,Online,True,2,66,Other,Electronics,1.5,Returned,Neutral,15.26,FREESHIP,NaN,34
36,2023-01-14,1659,172,1,67.33,0.00,67.3300,4,West,Credit Card,False,5,38,Female,Books,3.2,Returned,Neutral,NaN,WELCOME5,3.5,37
38,2023-02-05,1500,150,2,-20.00,0.10,0.0000,5,North,Credit Card,True,3,25,Male,Electronics,4.5,Not Returned,Positive,NaN,NaN,NaN,39
40,2023-02-07,1502,152,1,-30.00,0.15,0.0000,7,East,Online,True,2,45,Other,Books,5.0,Not Returned,Negative,NaN,NaN,NaN,41

Column                      is_member is not a string type and will be skipped.
Column                  delivery_days is not a string type and will be skipped.
Column                   customer_age is not a string type and will be skipped.
Column                         gender INVALID LENGTH DETECTED.
####### INVALID LENGTH #######

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,unique_id
0,2023-01-01,1792,161,6,9999.99,0.21,449.2098,5,East,Online,False,6,45,Other,Clothing,3.2,Not Returned,Neutral,8.21,nan,4.9,1
2,2023-01-03,1164,153,4,99.41,0.07,369.8052,9,North,Cash,True,6,25,Female,Clothing,4.9,Returned,Negative,NaN,nan,4.6,3
3,2023-01-04,1377,142,4,8888.88,0.21,241.8032,6,North,Cash,False,4,37,Female,Electronics,2.8,Not Returned,Negative,10.22,nan,3.9,4
8,2023-01-09,1188,141,6,26.66,0.26,118.3704,3,East,Credit Card,True,4,41,Female,Books,3.3,Not Returned,Neutral,NaN,nan,2.4,9
9,2023-01-10,1224,132,1,50.80,0.06,47.7520,8,East,Cash,True,4,21,Other,Food,1.9,Not Returned,Positive,7.46,nan,NaN,10
10,2023-01-11,1818,197,9,55.84,0.11,447.2784,9,South,Credit Card,False,5,30,Female,Food,1.9,Returned,Neutral,7.25,FREESHIP,NaN,11
11,2023-01-12,1201,103,5,94.40,0.27,344.5600,5,West,Cash,False,2,29,Female,Clothing,5.0,Not Returned,Positive,10.90,nan,4.0,12
13,2023-01-14,1659,172,1,67.33,0.00,67.3300,4,West,Credit Card,False,5,38,Female,Books,3.2,Returned,Neutral,NaN,WELCOME5,3.5,14
14,2023-01-15,1434,199,5,81.03,0.24,307.9140,9,East,Cash,True,3,25,Other,Electronics,3.2,Not Returned,Positive,7.25,SAVE10,NaN,15
16,2023-01-17,1384,189,5,29.98,0.16,125.9160,4,East,Online,True,4,34,Female,Food,2.1,Returned,Positive,19.25,nan,NaN,17
17,2023-01-18,1180,185,4,71.48,0.04,274.4832,4,North,Cash,True,3,54,Female,Books,3.3,Not Returned,Negative,13.84,nan,4.4,18
18,2023-01-19,1905,181,9,24.53,0.21,174.4083,8,West,Cash,False,4,21,Other,Electronics,1.1,Returned,Positive,8.02,WELCOME5,NaN,19
19,2023-01-20,1289,190,6,38.36,0.15,195.6360,5,West,Credit Card,False,3,64,Female,Clothing,2.6,Not Returned,Positive,17.19,FREESHIP,1.4,20
20,2023-01-21,1758,149,7,38.64,0.14,232.6128,4,North,Credit Card,True,6,60,Female,Books,4.2,Returned,Neutral,18.90,nan,NaN,21
21,2023-01-22,1262,139,3,34.57,0.17,86.0793,6,East,Cash,True,2,49,Other,Electronics,1.7,Not Returned,Positive,14.21,FREESHIP,2.9,22
22,2023-01-23,1258,104,6,41.20,0.16,207.6480,3,North,Cash,True,1,52,Female,Books,1.0,Not Returned,Neutral,19.35,nan,NaN,23
23,2023-01-24,1384,174,9,13.55,0.04,117.0720,2,East,Cash,False,2,63,Female,Food,3.8,Returned,Negative,10.86,WELCOME5,4.2,24
24,2023-01-25,1400,115,2,67.76,0.01,134.1648,8,West,Cash,False,6,20,Other,Clothing,2.1,Returned,Positive,NaN,nan,4.3,25
25,2023-01-26,1248,172,9,38.61,0.23,267.5673,8,North,Cash,True,6,52,Other,Books,2.4,Not Returned,Positive,14.31,FREESHIP,1.7,26
26,2023-01-27,1927,183,5,93.92,0.24,356.8960,7,South,Cash,False,3,32,Other,Clothing,2.6,Not Returned,Neutral,10.46,nan,1.5,27
29,2023-01-30,1732,174,4,51.33,0.21,162.2028,5,North,Cash,True,3,40,Other,Food,2.5,Not Returned,Positive,NaN,SAVE10,4.8,30
30,2023-01-31,1122,118,4,46.07,0.28,132.6816,1,North,Credit Card,True,6,59,Female,Electronics,3.8,Not Returned,Positive,7.69,FREESHIP,NaN,31
32,2023-02-02,1191,182,6,45.41,0.02,267.0108,9,West,Credit Card,False,2,45,Other,Food,4.4,Not Returned,Neutral,NaN,FREESHIP,NaN,33
33,2023-02-03,1622,140,5,42.39,0.02,207.7110,4,East,Online,True,2,66,Other,Electronics,1.5,Returned,Neutral,15.26,FREESHIP,NaN,34
35,2023-01-27,1927,183,5,93.92,0.24,356.8960,7,South,Cash,False,3,32,Other,Clothing,2.6,Not Returned,Neutral,10.46,nan,1.5,36
36,2023-01-14,1659,172,1,67.33,0.00,67.3300,4,West,Credit Card,False,5,38,Female,Books,3.2,Returned,Neutral,NaN,WELCOME5,3.5,37
37,2023-01-25,1400,115,2,67.76,0.01,134.1648,8,West,Cash,False,6,20,Other,Clothing,2.1,Returned,Positive,NaN,nan,4.3,38
39,2023-02-06,1501,151,3,-15.00,0.20,0.0000,6,South,Cash,False,4,34,Female,Clothing,3.0,Returned,Neutral,NaN,NaN,NaN,40
40,2023-02-07,1502,152,1,-30.00,0.15,0.0000,7,East,Online,True,2,45,Other,Books,5.0,Not Returned,Negative,NaN,NaN,NaN,41

Column               product_category INVALID LENGTH DETECTED.
####### INVALID LENGTH #######

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,unique_id
0,2023-01-01,1792,161,6,9999.99,0.21,449.2098,5,East,Online,False,6,45,Other,Clothing,3.2,Not Returned,Neutral,8.21,nan,4.9,1
1,2023-01-02,1478,175,4,11.96,0.18,39.2288,9,East,Cash,True,3,25,Male,Books,1.3,Returned,Positive,8.44,SAVE10,1.9,2
2,2023-01-03,1164,153,4,99.41,0.07,369.8052,9,North,Cash,True,6,25,Female,Clothing,4.9,Returned,Negative,NaN,nan,4.6,3
3,2023-01-04,1377,142,4,8888.88,0.21,241.8032,6,North,Cash,False,4,37,Female,Electronics,2.8,Not Returned,Negative,10.22,nan,3.9,4
4,2023-01-05,1247,153,3,85.99,0.26,190.8978,3,South,Online,False,3,27,Male,Electronics,4.7,Not Returned,Neutral,NaN,FREESHIP,4.4,5
7,2023-01-08,1443,128,5,95.84,0.22,373.7760,9,East,Cash,False,5,18,Male,Clothing,2.7,Not Returned,Neutral,19.67,nan,4.6,8
8,2023-01-09,1188,141,6,26.66,0.26,118.3704,3,East,Credit Card,True,4,41,Female,Books,3.3,Not Returned,Neutral,NaN,nan,2.4,9
11,2023-01-12,1201,103,5,94.40,0.27,344.5600,5,West,Cash,False,2,29,Female,Clothing,5.0,Not Returned,Positive,10.90,nan,4.0,12
12,2023-01-13,1337,196,7,38.04,0.23,205.0356,9,West,Credit Card,True,3,35,Male,Clothing,1.9,Not Returned,Negative,16.34,WELCOME5,NaN,13
13,2023-01-14,1659,172,1,67.33,0.00,67.3300,4,West,Credit Card,False,5,38,Female,Books,3.2,Returned,Neutral,NaN,WELCOME5,3.5,14
14,2023-01-15,1434,199,5,81.03,0.24,307.9140,9,East,Cash,True,3,25,Other,Electronics,3.2,Not Returned,Positive,7.25,SAVE10,NaN,15
15,2023-01-16,1687,149,5,85.78,0.07,398.8770,2,East,Cash,False,2,58,Male,Electronics,2.9,Returned,Positive,6.86,WELCOME5,1.8,16
17,2023-01-18,1180,185,4,71.48,0.04,274.4832,4,North,Cash,True,3,54,Female,Books,3.3,Not Returned,Negative,13.84,nan,4.4,18
18,2023-01-19,1905,181,9,24.53,0.21,174.4083,8,West,Cash,False,4,21,Other,Electronics,1.1,Returned,Positive,8.02,WELCOME5,NaN,19
19,2023-01-20,1289,190,6,38.36,0.15,195.6360,5,West,Credit Card,False,3,64,Female,Clothing,2.6,Not Returned,Positive,17.19,FREESHIP,1.4,20
20,2023-01-21,1758,149,7,38.64,0.14,232.6128,4,North,Credit Card,True,6,60,Female,Books,4.2,Returned,Neutral,18.90,nan,NaN,21
21,2023-01-22,1262,139,3,34.57,0.17,86.0793,6,East,Cash,True,2,49,Other,Electronics,1.7,Not Returned,Positive,14.21,FREESHIP,2.9,22
22,2023-01-23,1258,104,6,41.20,0.16,207.6480,3,North,Cash,True,1,52,Female,Books,1.0,Not Returned,Neutral,19.35,nan,NaN,23
24,2023-01-25,1400,115,2,67.76,0.01,134.1648,8,West,Cash,False,6,20,Other,Clothing,2.1,Returned,Positive,NaN,nan,4.3,25
25,2023-01-26,1248,172,9,38.61,0.23,267.5673,8,North,Cash,True,6,52,Other,Books,2.4,Not Returned,Positive,14.31,FREESHIP,1.7,26
26,2023-01-27,1927,183,5,93.92,0.24,356.8960,7,South,Cash,False,3,32,Other,Clothing,2.6,Not Returned,Neutral,10.46,nan,1.5,27
28,2023-01-29,1496,171,9,64.48,0.26,429.4368,7,North,Credit Card,True,1,52,Male,Electronics,3.8,Not Returned,Neutral,14.75,nan,3.5,29
30,2023-01-31,1122,118,4,46.07,0.28,132.6816,1,North,Credit Card,True,6,59,Female,Electronics,3.8,Not Returned,Positive,7.69,FREESHIP,NaN,31
31,2023-02-01,1858,168,1,41.71,0.04,40.0416,7,North,Credit Card,False,6,42,Male,Books,2.9,Not Returned,Neutral,18.21,WELCOME5,3.6,32
33,2023-02-03,1622,140,5,42.39,0.02,207.7110,4,East,Online,True,2,66,Other,Electronics,1.5,Returned,Neutral,15.26,FREESHIP,NaN,34
34,2023-02-04,1708,173,2,87.90,0.11,156.4620,6,East,Cash,False,1,60,Male,Books,1.7,Returned,Neutral,8.04,nan,4.6,35
35,2023-01-27,1927,183,5,93.92,0.24,356.8960,7,South,Cash,False,3,32,Other,Clothing,2.6,Not Returned,Neutral,10.46,nan,1.5,36
36,2023-01-14,1659,172,1,67.33,0.00,67.3300,4,West,Credit Card,False,5,38,Female,Books,3.2,Returned,Neutral,NaN,WELCOME5,3.5,37
37,2023-01-25,1400,115,2,67.76,0.01,134.1648,8,West,Cash,False,6,20,Other,Clothing,2.1,Returned,Positive,NaN,nan,4.3,38
38,2023-02-05,1500,150,2,-20.00,0.10,0.0000,5,North,Credit Card,True,3,25,Male,Electronics,4.5,Not Returned,Positive,NaN,NaN,NaN,39
39,2023-02-06,1501,151,3,-15.00,0.20,0.0000,6,South,Cash,False,4,34,Female,Clothing,3.0,Returned,Neutral,NaN,NaN,NaN,40
40,2023-02-07,1502,152,1,-30.00,0.15,0.0000,7,East,Online,True,2,45,Other,Books,5.0,Not Returned,Negative,NaN,NaN,NaN,41

Column                         rating is not a string type and will be skipped.
Column                  return_status INVALID LENGTH DETECTED.
####### INVALID LENGTH #######

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,unique_id
0,2023-01-01,1792,161,6,9999.99,0.21,449.2098,5,East,Online,False,6,45,Other,Clothing,3.2,Not Returned,Neutral,8.21,nan,4.9,1
1,2023-01-02,1478,175,4,11.96,0.18,39.2288,9,East,Cash,True,3,25,Male,Books,1.3,Returned,Positive,8.44,SAVE10,1.9,2
2,2023-01-03,1164,153,4,99.41,0.07,369.8052,9,North,Cash,True,6,25,Female,Clothing,4.9,Returned,Negative,NaN,nan,4.6,3
3,2023-01-04,1377,142,4,8888.88,0.21,241.8032,6,North,Cash,False,4,37,Female,Electronics,2.8,Not Returned,Negative,10.22,nan,3.9,4
4,2023-01-05,1247,153,3,85.99,0.26,190.8978,3,South,Online,False,3,27,Male,Electronics,4.7,Not Returned,Neutral,NaN,FREESHIP,4.4,5
5,2023-01-06,1129,169,8,7777.77,0.03,692.5800,2,West,Online,True,5,55,Male,Food,3.8,Not Returned,Positive,NaN,SAVE10,NaN,6
6,2023-01-07,1923,180,4,68.77,0.14,236.5688,5,East,Credit Card,False,1,41,Male,Food,4.8,Returned,Neutral,NaN,SAVE10,NaN,7
7,2023-01-08,1443,128,5,95.84,0.22,373.7760,9,East,Cash,False,5,18,Male,Clothing,2.7,Not Returned,Neutral,19.67,nan,4.6,8
8,2023-01-09,1188,141,6,26.66,0.26,118.3704,3,East,Credit Card,True,4,41,Female,Books,3.3,Not Returned,Neutral,NaN,nan,2.4,9
9,2023-01-10,1224,132,1,50.80,0.06,47.7520,8,East,Cash,True,4,21,Other,Food,1.9,Not Returned,Positive,7.46,nan,NaN,10
10,2023-01-11,1818,197,9,55.84,0.11,447.2784,9,South,Credit Card,False,5,30,Female,Food,1.9,Returned,Neutral,7.25,FREESHIP,NaN,11
11,2023-01-12,1201,103,5,94.40,0.27,344.5600,5,West,Cash,False,2,29,Female,Clothing,5.0,Not Returned,Positive,10.90,nan,4.0,12
12,2023-01-13,1337,196,7,38.04,0.23,205.0356,9,West,Credit Card,True,3,35,Male,Clothing,1.9,Not Returned,Negative,16.34,WELCOME5,NaN,13
13,2023-01-14,1659,172,1,67.33,0.00,67.3300,4,West,Credit Card,False,5,38,Female,Books,3.2,Returned,Neutral,NaN,WELCOME5,3.5,14
14,2023-01-15,1434,199,5,81.03,0.24,307.9140,9,East,Cash,True,3,25,Other,Electronics,3.2,Not Returned,Positive,7.25,SAVE10,NaN,15
15,2023-01-16,1687,149,5,85.78,0.07,398.8770,2,East,Cash,False,2,58,Male,Electronics,2.9,Returned,Positive,6.86,WELCOME5,1.8,16
16,2023-01-17,1384,189,5,29.98,0.16,125.9160,4,East,Online,True,4,34,Female,Food,2.1,Returned,Positive,19.25,nan,NaN,17
17,2023-01-18,1180,185,4,71.48,0.04,274.4832,4,North,Cash,True,3,54,Female,Books,3.3,Not Returned,Negative,13.84,nan,4.4,18
18,2023-01-19,1905,181,9,24.53,0.21,174.4083,8,West,Cash,False,4,21,Other,Electronics,1.1,Returned,Positive,8.02,WELCOME5,NaN,19
19,2023-01-20,1289,190,6,38.36,0.15,195.6360,5,West,Credit Card,False,3,64,Female,Clothing,2.6,Not Returned,Positive,17.19,FREESHIP,1.4,20
20,2023-01-21,1758,149,7,38.64,0.14,232.6128,4,North,Credit Card,True,6,60,Female,Books,4.2,Returned,Neutral,18.90,nan,NaN,21
21,2023-01-22,1262,139,3,34.57,0.17,86.0793,6,East,Cash,True,2,49,Other,Electronics,1.7,Not Returned,Positive,14.21,FREESHIP,2.9,22
22,2023-01-23,1258,104,6,41.20,0.16,207.6480,3,North,Cash,True,1,52,Female,Books,1.0,Not Returned,Neutral,19.35,nan,NaN,23
23,2023-01-24,1384,174,9,13.55,0.04,117.0720,2,East,Cash,False,2,63,Female,Food,3.8,Returned,Negative,10.86,WELCOME5,4.2,24
24,2023-01-25,1400,115,2,67.76,0.01,134.1648,8,West,Cash,False,6,20,Other,Clothing,2.1,Returned,Positive,NaN,nan,4.3,25
25,2023-01-26,1248,172,9,38.61,0.23,267.5673,8,North,Cash,True,6,52,Other,Books,2.4,Not Returned,Positive,14.31,FREESHIP,1.7,26
26,2023-01-27,1927,183,5,93.92,0.24,356.8960,7,South,Cash,False,3,32,Other,Clothing,2.6,Not Returned,Neutral,10.46,nan,1.5,27
27,2023-01-28,1858,134,9,91.73,0.05,784.2915,4,South,Credit Card,False,6,69,Male,Food,3.4,Not Returned,Neutral,17.41,SAVE10,3.3,28
28,2023-01-29,1496,171,9,64.48,0.26,429.4368,7,North,Credit Card,True,1,52,Male,Electronics,3.8,Not Returned,Neutral,14.75,nan,3.5,29
29,2023-01-30,1732,174,4,51.33,0.21,162.2028,5,North,Cash,True,3,40,Other,Food,2.5,Not Returned,Positive,NaN,SAVE10,4.8,30
30,2023-01-31,1122,118,4,46.07,0.28,132.6816,1,North,Credit Card,True,6,59,Female,Electronics,3.8,Not Returned,Positive,7.69,FREESHIP,NaN,31
31,2023-02-01,1858,168,1,41.71,0.04,40.0416,7,North,Credit Card,False,6,42,Male,Books,2.9,Not Returned,Neutral,18.21,WELCOME5,3.6,32
32,2023-02-02,1191,182,6,45.41,0.02,267.0108,9,West,Credit Card,False,2,45,Other,Food,4.4,Not Returned,Neutral,NaN,FREESHIP,NaN,33
33,2023-02-03,1622,140,5,42.39,0.02,207.7110,4,East,Online,True,2,66,Other,Electronics,1.5,Returned,Neutral,15.26,FREESHIP,NaN,34
34,2023-02-04,1708,173,2,87.90,0.11,156.4620,6,East,Cash,False,1,60,Male,Books,1.7,Returned,Neutral,8.04,nan,4.6,35
35,2023-01-27,1927,183,5,93.92,0.24,356.8960,7,South,Cash,False,3,32,Other,Clothing,2.6,Not Returned,Neutral,10.46,nan,1.5,36
36,2023-01-14,1659,172,1,67.33,0.00,67.3300,4,West,Credit Card,False,5,38,Female,Books,3.2,Returned,Neutral,NaN,WELCOME5,3.5,37
37,2023-01-25,1400,115,2,67.76,0.01,134.1648,8,West,Cash,False,6,20,Other,Clothing,2.1,Returned,Positive,NaN,nan,4.3,38
38,2023-02-05,1500,150,2,-20.00,0.10,0.0000,5,North,Credit Card,True,3,25,Male,Electronics,4.5,Not Returned,Positive,NaN,NaN,NaN,39
39,2023-02-06,1501,151,3,-15.00,0.20,0.0000,6,South,Cash,False,4,34,Female,Clothing,3.0,Returned,Neutral,NaN,NaN,NaN,40
40,2023-02-07,1502,152,1,-30.00,0.15,0.0000,7,East,Online,True,2,45,Other,Books,5.0,Not Returned,Negative,NaN,NaN,NaN,41

Column                       feedback INVALID LENGTH DETECTED.
####### INVALID LENGTH #######

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,unique_id
0,2023-01-01,1792,161,6,9999.99,0.21,449.2098,5,East,Online,False,6,45,Other,Clothing,3.2,Not Returned,Neutral,8.21,nan,4.9,1
1,2023-01-02,1478,175,4,11.96,0.18,39.2288,9,East,Cash,True,3,25,Male,Books,1.3,Returned,Positive,8.44,SAVE10,1.9,2
2,2023-01-03,1164,153,4,99.41,0.07,369.8052,9,North,Cash,True,6,25,Female,Clothing,4.9,Returned,Negative,NaN,nan,4.6,3
3,2023-01-04,1377,142,4,8888.88,0.21,241.8032,6,North,Cash,False,4,37,Female,Electronics,2.8,Not Returned,Negative,10.22,nan,3.9,4
4,2023-01-05,1247,153,3,85.99,0.26,190.8978,3,South,Online,False,3,27,Male,Electronics,4.7,Not Returned,Neutral,NaN,FREESHIP,4.4,5
5,2023-01-06,1129,169,8,7777.77,0.03,692.5800,2,West,Online,True,5,55,Male,Food,3.8,Not Returned,Positive,NaN,SAVE10,NaN,6
6,2023-01-07,1923,180,4,68.77,0.14,236.5688,5,East,Credit Card,False,1,41,Male,Food,4.8,Returned,Neutral,NaN,SAVE10,NaN,7
7,2023-01-08,1443,128,5,95.84,0.22,373.7760,9,East,Cash,False,5,18,Male,Clothing,2.7,Not Returned,Neutral,19.67,nan,4.6,8
8,2023-01-09,1188,141,6,26.66,0.26,118.3704,3,East,Credit Card,True,4,41,Female,Books,3.3,Not Returned,Neutral,NaN,nan,2.4,9
9,2023-01-10,1224,132,1,50.80,0.06,47.7520,8,East,Cash,True,4,21,Other,Food,1.9,Not Returned,Positive,7.46,nan,NaN,10
10,2023-01-11,1818,197,9,55.84,0.11,447.2784,9,South,Credit Card,False,5,30,Female,Food,1.9,Returned,Neutral,7.25,FREESHIP,NaN,11
11,2023-01-12,1201,103,5,94.40,0.27,344.5600,5,West,Cash,False,2,29,Female,Clothing,5.0,Not Returned,Positive,10.90,nan,4.0,12
12,2023-01-13,1337,196,7,38.04,0.23,205.0356,9,West,Credit Card,True,3,35,Male,Clothing,1.9,Not Returned,Negative,16.34,WELCOME5,NaN,13
13,2023-01-14,1659,172,1,67.33,0.00,67.3300,4,West,Credit Card,False,5,38,Female,Books,3.2,Returned,Neutral,NaN,WELCOME5,3.5,14
14,2023-01-15,1434,199,5,81.03,0.24,307.9140,9,East,Cash,True,3,25,Other,Electronics,3.2,Not Returned,Positive,7.25,SAVE10,NaN,15
15,2023-01-16,1687,149,5,85.78,0.07,398.8770,2,East,Cash,False,2,58,Male,Electronics,2.9,Returned,Positive,6.86,WELCOME5,1.8,16
16,2023-01-17,1384,189,5,29.98,0.16,125.9160,4,East,Online,True,4,34,Female,Food,2.1,Returned,Positive,19.25,nan,NaN,17
17,2023-01-18,1180,185,4,71.48,0.04,274.4832,4,North,Cash,True,3,54,Female,Books,3.3,Not Returned,Negative,13.84,nan,4.4,18
18,2023-01-19,1905,181,9,24.53,0.21,174.4083,8,West,Cash,False,4,21,Other,Electronics,1.1,Returned,Positive,8.02,WELCOME5,NaN,19
19,2023-01-20,1289,190,6,38.36,0.15,195.6360,5,West,Credit Card,False,3,64,Female,Clothing,2.6,Not Returned,Positive,17.19,FREESHIP,1.4,20
20,2023-01-21,1758,149,7,38.64,0.14,232.6128,4,North,Credit Card,True,6,60,Female,Books,4.2,Returned,Neutral,18.90,nan,NaN,21
21,2023-01-22,1262,139,3,34.57,0.17,86.0793,6,East,Cash,True,2,49,Other,Electronics,1.7,Not Returned,Positive,14.21,FREESHIP,2.9,22
22,2023-01-23,1258,104,6,41.20,0.16,207.6480,3,North,Cash,True,1,52,Female,Books,1.0,Not Returned,Neutral,19.35,nan,NaN,23
23,2023-01-24,1384,174,9,13.55,0.04,117.0720,2,East,Cash,False,2,63,Female,Food,3.8,Returned,Negative,10.86,WELCOME5,4.2,24
24,2023-01-25,1400,115,2,67.76,0.01,134.1648,8,West,Cash,False,6,20,Other,Clothing,2.1,Returned,Positive,NaN,nan,4.3,25
25,2023-01-26,1248,172,9,38.61,0.23,267.5673,8,North,Cash,True,6,52,Other,Books,2.4,Not Returned,Positive,14.31,FREESHIP,1.7,26
26,2023-01-27,1927,183,5,93.92,0.24,356.8960,7,South,Cash,False,3,32,Other,Clothing,2.6,Not Returned,Neutral,10.46,nan,1.5,27
27,2023-01-28,1858,134,9,91.73,0.05,784.2915,4,South,Credit Card,False,6,69,Male,Food,3.4,Not Returned,Neutral,17.41,SAVE10,3.3,28
28,2023-01-29,1496,171,9,64.48,0.26,429.4368,7,North,Credit Card,True,1,52,Male,Electronics,3.8,Not Returned,Neutral,14.75,nan,3.5,29
29,2023-01-30,1732,174,4,51.33,0.21,162.2028,5,North,Cash,True,3,40,Other,Food,2.5,Not Returned,Positive,NaN,SAVE10,4.8,30
30,2023-01-31,1122,118,4,46.07,0.28,132.6816,1,North,Credit Card,True,6,59,Female,Electronics,3.8,Not Returned,Positive,7.69,FREESHIP,NaN,31
31,2023-02-01,1858,168,1,41.71,0.04,40.0416,7,North,Credit Card,False,6,42,Male,Books,2.9,Not Returned,Neutral,18.21,WELCOME5,3.6,32
32,2023-02-02,1191,182,6,45.41,0.02,267.0108,9,West,Credit Card,False,2,45,Other,Food,4.4,Not Returned,Neutral,NaN,FREESHIP,NaN,33
33,2023-02-03,1622,140,5,42.39,0.02,207.7110,4,East,Online,True,2,66,Other,Electronics,1.5,Returned,Neutral,15.26,FREESHIP,NaN,34
34,2023-02-04,1708,173,2,87.90,0.11,156.4620,6,East,Cash,False,1,60,Male,Books,1.7,Returned,Neutral,8.04,nan,4.6,35
35,2023-01-27,1927,183,5,93.92,0.24,356.8960,7,South,Cash,False,3,32,Other,Clothing,2.6,Not Returned,Neutral,10.46,nan,1.5,36
36,2023-01-14,1659,172,1,67.33,0.00,67.3300,4,West,Credit Card,False,5,38,Female,Books,3.2,Returned,Neutral,NaN,WELCOME5,3.5,37
37,2023-01-25,1400,115,2,67.76,0.01,134.1648,8,West,Cash,False,6,20,Other,Clothing,2.1,Returned,Positive,NaN,nan,4.3,38
38,2023-02-05,1500,150,2,-20.00,0.10,0.0000,5,North,Credit Card,True,3,25,Male,Electronics,4.5,Not Returned,Positive,NaN,NaN,NaN,39
39,2023-02-06,1501,151,3,-15.00,0.20,0.0000,6,South,Cash,False,4,34,Female,Clothing,3.0,Returned,Neutral,NaN,NaN,NaN,40
40,2023-02-07,1502,152,1,-30.00,0.15,0.0000,7,East,Online,True,2,45,Other,Books,5.0,Not Returned,Negative,NaN,NaN,NaN,41

Column                  shipping_cost is not a string type and will be skipped.
Column                    coupon_code is not a string type and will be skipped.
Column                delivery_rating is not a string type and will be skipped.
Column                      unique_id is not a string type and will be skipped.

<div class="alert alert-warning">

**12. Verifying Numeric Range in a DataFrame Column**

**Write a Pandas program to verify numeric range in a DataFrame column.**

</div>

In [26]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Add 3 duplicate rows
df = pd.concat([df, df.sample(n=3, random_state=42)], ignore_index=True)

# Add 3 more rows with negative price
df = pd.concat([df, pd.DataFrame({
    'date': pd.date_range(start='2023-02-05', periods=3, freq='D'),
    'customer_id': [1500, 1501, 1502],
    'product_id': [150, 151, 152],
    'quantity': [2, 3, 1],
    'price': [-20.00, -15.00, -30.00],  # Negative prices
    'discount': [0.1, 0.2, 0.15],
    'revenue': [0, 0, 0],  # Placeholder; will be recalculated
    'store_id': [5, 6, 7],
    'region': ['North', 'South', 'East'],
    'payment_method': ['Credit Card', 'Cash', 'Online'],
    'is_member': [True, False, True],
    'delivery_days': [3, 4, 2],
    'customer_age': [25, 34, 45],
    'gender': ['Male', 'Female', 'Other'],
    'product_category': ['Electronics', 'Clothing', 'Books'],
    'rating': [4.5, 3.0, 5.0],
    'return_status': ['Not Returned', 'Returned', 'Not Returned'],
    'feedback': ['Positive', 'Neutral', 'Negative'],
})], ignore_index=True)

# add column with unique value
df['unique_id'] = pd.Series(range(1, len(df) + 1))

# add outliers
df.loc[[0,3,5], ['price']] = [9999.99, 8888.88, 7777.77]

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,unique_id
0,2023-01-01,1989,183,2,9999.99,0.23,18.4646,3,West,Online,True,4,20,Female,Books,1.7,Returned,Neutral,16.70,FREESHIP,NaN,1
1,2023-01-02,1415,113,6,25.35,0.03,147.5370,3,West,Online,False,1,34,Female,Electronics,3.5,Returned,Positive,18.49,nan,2.2,2
2,2023-01-03,1540,111,9,11.65,0.06,98.5590,6,West,Credit Card,False,4,46,Male,Electronics,3.8,Returned,Positive,18.06,SAVE10,4.6,3
3,2023-01-04,1758,128,4,8888.88,0.27,236.9288,3,South,Cash,True,3,50,Female,Food,2.6,Not Returned,Neutral,5.33,FREESHIP,4.4,4
4,2023-01-05,1480,190,7,73.92,0.17,429.4752,9,South,Online,False,6,35,Female,Food,1.6,Returned,Negative,17.44,FREESHIP,3.8,5
5,2023-01-06,1780,118,6,7777.77,0.06,543.9780,9,West,Credit Card,True,6,61,Male,Books,4.6,Not Returned,Negative,6.87,SAVE10,4.1,6
6,2023-01-07,1787,161,5,41.99,0.10,188.9550,1,East,Online,True,2,69,Female,Clothing,2.1,Returned,Positive,11.52,nan,2.8,7
7,2023-01-08,1156,188,8,69.90,0.01,553.6080,8,West,Cash,False,4,40,Other,Food,1.4,Returned,Neutral,NaN,WELCOME5,3.5,8
8,2023-01-09,1886,162,1,81.96,0.07,76.2228,5,East,Online,False,3,22,Male,Clothing,4.8,Returned,Negative,16.87,WELCOME5,2.1,9
9,2023-01-10,1150,190,3,77.36,0.11,206.5512,9,South,Online,False,1,22,Other,Clothing,3.9,Not Returned,Negative,16.85,nan,NaN,10
10,2023-01-11,1561,138,7,95.67,0.19,542.4489,9,South,Online,True,1,36,Female,Books,4.4,Not Returned,Positive,19.29,FREESHIP,1.2,11
11,2023-01-12,1309,159,2,78.15,0.06,146.9220,5,North,Credit Card,False,4,37,Other,Clothing,4.1,Not Returned,Negative,6.98,nan,NaN,12
12,2023-01-13,1459,192,8,56.18,0.10,404.4960,9,East,Online,False,6,45,Male,Food,1.7,Not Returned,Neutral,14.86,WELCOME5,NaN,13
13,2023-01-14,1157,128,3,69.99,0.30,146.9790,7,East,Credit Card,True,6,45,Male,Clothing,2.5,Not Returned,Neutral,17.45,FREESHIP,NaN,14
14,2023-01-15,1695,122,9,75.47,0.10,611.3070,6,North,Online,True,5,30,Other,Electronics,4.2,Not Returned,Neutral,7.85,WELCOME5,3.7,15
15,2023-01-16,1940,171,5,92.21,0.09,419.5555,5,North,Online,False,4,43,Male,Clothing,4.6,Not Returned,Positive,17.64,nan,3.7,16
16,2023-01-17,1222,129,2,78.09,0.11,139.0002,1,South,Credit Card,False,3,60,Female,Food,2.1,Not Returned,Negative,19.29,FREESHIP,NaN,17
17,2023-01-18,1145,136,6,33.88,0.25,152.4600,8,North,Cash,False,5,44,Other,Food,4.2,Not Returned,Neutral,12.47,FREESHIP,NaN,18
18,2023-01-19,1025,156,9,16.98,0.24,116.1432,5,East,Online,True,1,40,Other,Books,3.4,Not Returned,Neutral,17.36,nan,2.6,19
19,2023-01-20,1174,187,3,75.60,0.15,192.7800,1,South,Cash,True,3,69,Other,Electronics,1.5,Not Returned,Positive,10.49,nan,1.3,20
20,2023-01-21,1791,131,4,38.55,0.17,127.9860,1,West,Cash,True,3,55,Other,Electronics,3.9,Not Returned,Negative,5.19,nan,3.3,21
21,2023-01-22,1572,179,1,52.62,0.07,48.9366,2,South,Credit Card,False,6,35,Other,Food,2.2,Not Returned,Negative,NaN,WELCOME5,3.9,22
22,2023-01-23,1869,195,9,36.83,0.12,291.6936,4,East,Credit Card,True,5,41,Other,Books,4.2,Returned,Negative,11.72,FREESHIP,NaN,23
23,2023-01-24,1889,103,5,87.90,0.23,338.4150,9,West,Credit Card,True,1,64,Male,Food,3.1,Returned,Negative,19.48,FREESHIP,4.0,24
24,2023-01-25,1026,169,8,58.54,0.13,407.4384,9,East,Online,False,2,54,Other,Food,3.7,Not Returned,Neutral,NaN,WELCOME5,4.3,25
25,2023-01-26,1659,182,2,38.49,0.28,55.4256,7,East,Cash,False,3,38,Female,Clothing,4.9,Returned,Positive,7.53,nan,2.8,26
26,2023-01-27,1605,187,1,81.13,0.22,63.2814,4,East,Online,True,3,63,Female,Electronics,1.7,Returned,Positive,16.98,WELCOME5,4.5,27
27,2023-01-28,1260,120,2,61.14,0.08,112.4976,1,East,Online,True,1,26,Other,Electronics,1.6,Not Returned,Neutral,15.94,SAVE10,1.6,28
28,2023-01-29,1108,122,2,78.81,0.16,132.4008,1,West,Online,False,5,43,Other,Electronics,4.7,Not Returned,Negative,11.25,FREESHIP,2.7,29
29,2023-01-30,1613,180,3,62.77,0.05,178.8945,2,East,Online,True,3,50,Other,Electronics,1.4,Returned,Positive,6.95,FREESHIP,NaN,30
30,2023-01-31,1519,183,1,76.91,0.22,59.9898,9,North,Online,False,4,67,Female,Electronics,3.1,Returned,Negative,17.98,SAVE10,2.1,31
31,2023-02-01,1652,155,6,93.67,0.17,466.4766,3,East,Credit Card,False,4,63,Other,Clothing,4.0,Not Returned,Negative,13.70,WELCOME5,3.1,32
32,2023-02-02,1628,143,2,72.06,0.18,118.1784,4,East,Online,False,2,49,Male,Electronics,2.6,Returned,Negative,13.85,SAVE10,1.6,33
33,2023-02-03,1526,167,9,58.51,0.22,410.7402,2,North,Credit Card,True,3,26,Female,Books,1.7,Not Returned,Positive,17.16,SAVE10,4.5,34
34,2023-02-04,1946,173,9,77.54,0.17,579.2238,4,East,Online,True,2,57,Other,Clothing,4.9,Returned,Negative,7.04,nan,NaN,35
35,2023-01-27,1605,187,1,81.13,0.22,63.2814,4,East,Online,True,3,63,Female,Electronics,1.7,Returned,Positive,16.98,WELCOME5,4.5,36
36,2023-01-14,1157,128,3,69.99,0.30,146.9790,7,East,Credit Card,True,6,45,Male,Clothing,2.5,Not Returned,Neutral,17.45,FREESHIP,NaN,37
37,2023-01-25,1026,169,8,58.54,0.13,407.4384,9,East,Online,False,2,54,Other,Food,3.7,Not Returned,Neutral,NaN,WELCOME5,4.3,38
38,2023-02-05,1500,150,2,-20.00,0.10,0.0000,5,North,Credit Card,True,3,25,Male,Electronics,4.5,Not Returned,Positive,NaN,NaN,NaN,39
39,2023-02-06,1501,151,3,-15.00,0.20,0.0000,6,South,Cash,False,4,34,Female,Clothing,3.0,Returned,Neutral,NaN,NaN,NaN,40
40,2023-02-07,1502,152,1,-30.00,0.15,0.0000,7,East,Online,True,2,45,Other,Books,5.0,Not Returned,Negative,NaN,NaN,NaN,41

<div class="alert alert-success">

**Solution 12:**
</div>

In [27]:
# 12. Verifying Numeric Range in a DataFrame Column
# Write a Pandas program to verify numeric range in a DataFrame column.

def verify_numeric_range(dataframe, column_name, min_value, max_value):
    if not pd.api.types.is_numeric_dtype(dataframe[column_name]):
        print("Column {:>30} is not numeric and will be skipped.".format(column_name))
        return
    else:
        out_of_range = dataframe[(dataframe[column_name] < min_value) | (dataframe[column_name] > max_value)]
    if not out_of_range.empty:
        print("Column {:>30} OUT OF RANGE DETECTED.\n####### OUT OF RANGE #######".format(column_name))
        display(out_of_range)
    else:
        print("Column {:>30} has no out of range values detected.".format(column_name))

# Apply to price column only
verify_numeric_range(df, 'price', min_value=0, max_value=100)

Column                          price OUT OF RANGE DETECTED.
####### OUT OF RANGE #######

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,unique_id
0,2023-01-01,1989,183,2,9999.99,0.23,18.4646,3,West,Online,True,4,20,Female,Books,1.7,Returned,Neutral,16.70,FREESHIP,NaN,1
3,2023-01-04,1758,128,4,8888.88,0.27,236.9288,3,South,Cash,True,3,50,Female,Food,2.6,Not Returned,Neutral,5.33,FREESHIP,4.4,4
5,2023-01-06,1780,118,6,7777.77,0.06,543.9780,9,West,Credit Card,True,6,61,Male,Books,4.6,Not Returned,Negative,6.87,SAVE10,4.1,6
38,2023-02-05,1500,150,2,-20.00,0.10,0.0000,5,North,Credit Card,True,3,25,Male,Electronics,4.5,Not Returned,Positive,NaN,NaN,NaN,39
39,2023-02-06,1501,151,3,-15.00,0.20,0.0000,6,South,Cash,False,4,34,Female,Clothing,3.0,Returned,Neutral,NaN,NaN,NaN,40
40,2023-02-07,1502,152,1,-30.00,0.15,0.0000,7,East,Online,True,2,45,Other,Books,5.0,Not Returned,Negative,NaN,NaN,NaN,41