[Pandas Data Validation](https://www.w3resource.com/python-exercises/pandas/pandas-data-validation.php)

In [1]:
import pandas as pd
import numpy as np

<div class="alert alert-warning">

**1. Checking Missing Values in a DataFrame**

**Write a Pandas program to check for missing values in a DataFrame.**

</div>

In [2]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1234,194,6,41.09,0.29,175.0434,8,East,Cash,...,4,30,Female,Books,2.9,Returned,Positive,6.02,SAVE10,1.0
1,2023-01-02,1236,117,3,32.59,0.06,91.9038,6,West,Cash,...,3,48,Other,Clothing,4.5,Not Returned,Positive,12.71,WELCOME5,2.7
2,2023-01-03,1035,103,5,87.29,0.27,318.6085,9,South,Cash,...,4,30,Male,Food,2.6,Not Returned,Negative,9.36,nan,3.0
3,2023-01-04,1090,111,2,51.45,0.04,98.7840,2,West,Cash,...,2,53,Other,Clothing,1.3,Returned,Negative,18.52,WELCOME5,3.4
4,2023-01-05,1660,123,5,75.64,0.29,268.5220,8,South,Cash,...,6,36,Other,Food,3.7,Not Returned,Neutral,7.23,SAVE10,2.3
5,2023-01-06,1407,169,3,57.80,0.15,147.3900,5,South,Credit Card,...,2,25,Female,Books,2.2,Not Returned,Negative,19.10,nan,NaN
6,2023-01-07,1267,188,7,93.16,0.21,515.1748,8,North,Cash,...,6,61,Male,Books,3.3,Not Returned,Neutral,NaN,SAVE10,2.5
7,2023-01-08,1230,129,2,14.86,0.15,25.2620,7,North,Cash,...,5,39,Female,Food,4.1,Not Returned,Positive,8.51,nan,3.5
8,2023-01-09,1142,176,5,40.82,0.24,155.1160,5,North,Online,...,1,39,Other,Electronics,1.9,Returned,Negative,13.54,nan,NaN
9,2023-01-10,1704,123,4,21.92,0.29,62.2528,3,West,Online,...,6,41,Other,Books,1.4,Returned,Positive,6.61,WELCOME5,NaN
10,2023-01-11,1059,100,7,74.70,0.11,465.3810,8,West,Credit Card,...,2,21,Female,Electronics,4.8,Returned,Negative,18.61,WELCOME5,2.6
11,2023-01-12,1993,151,7,38.55,0.06,253.6590,4,South,Credit Card,...,2,49,Female,Clothing,3.9,Not Returned,Neutral,5.71,FREESHIP,2.7
12,2023-01-13,1259,196,7,58.82,0.08,378.8008,8,North,Credit Card,...,6,67,Male,Food,2.7,Not Returned,Neutral,17.00,FREESHIP,3.0
13,2023-01-14,1440,128,3,95.26,0.23,220.0506,4,North,Cash,...,6,49,Female,Food,4.6,Returned,Positive,17.09,nan,1.7
14,2023-01-15,1945,133,5,82.57,0.06,388.0790,7,East,Credit Card,...,3,62,Other,Electronics,1.4,Not Returned,Positive,15.47,SAVE10,NaN
15,2023-01-16,1337,124,2,38.50,0.28,55.4400,8,East,Credit Card,...,5,38,Other,Electronics,1.7,Not Returned,Negative,15.89,SAVE10,4.4
16,2023-01-17,1076,168,8,92.36,0.20,591.1040,3,West,Cash,...,1,69,Male,Clothing,4.7,Returned,Negative,7.77,FREESHIP,3.7
17,2023-01-18,1193,113,3,64.85,0.19,157.5855,3,North,Credit Card,...,1,30,Female,Food,3.0,Returned,Neutral,19.52,FREESHIP,3.7
18,2023-01-19,1884,119,6,82.47,0.21,390.9078,1,North,Cash,...,2,57,Female,Clothing,1.2,Not Returned,Negative,17.33,SAVE10,3.6
19,2023-01-20,1760,119,7,13.39,0.04,89.9808,6,West,Cash,...,5,22,Female,Electronics,4.7,Not Returned,Negative,NaN,nan,2.2
20,2023-01-21,1572,192,4,22.70,0.20,72.6400,6,North,Cash,...,4,58,Female,Electronics,5.0,Not Returned,Negative,9.09,nan,4.7
21,2023-01-22,1183,190,5,53.92,0.26,199.5040,4,East,Cash,...,6,49,Female,Books,3.7,Returned,Negative,8.24,SAVE10,2.2
22,2023-01-23,1332,110,7,72.01,0.11,448.6223,9,North,Online,...,4,52,Other,Clothing,1.3,Not Returned,Neutral,16.53,SAVE10,2.7
23,2023-01-24,1980,140,9,44.68,0.15,341.8020,1,West,Cash,...,6,46,Other,Food,1.9,Not Returned,Negative,16.43,FREESHIP,3.8
24,2023-01-25,1285,187,3,38.06,0.12,100.4784,6,North,Credit Card,...,2,45,Female,Electronics,2.5,Returned,Neutral,9.82,SAVE10,3.4
25,2023-01-26,1115,160,1,58.86,0.12,51.7968,1,South,Online,...,2,54,Male,Electronics,2.6,Returned,Positive,NaN,nan,3.3
26,2023-01-27,1797,113,6,45.45,0.27,199.0710,1,East,Cash,...,4,53,Female,Electronics,4.2,Returned,Neutral,14.02,nan,4.8
27,2023-01-28,1017,148,6,34.41,0.12,181.6848,8,East,Credit Card,...,1,57,Other,Food,3.4,Not Returned,Negative,12.34,nan,2.9
28,2023-01-29,1481,101,6,13.41,0.25,60.3450,7,North,Cash,...,3,57,Male,Food,1.7,Not Returned,Positive,16.36,WELCOME5,3.9
29,2023-01-30,1215,177,8,86.87,0.19,562.9176,4,East,Credit Card,...,4,60,Other,Books,1.7,Not Returned,Positive,11.52,SAVE10,NaN
30,2023-01-31,1315,119,7,86.79,0.08,558.9276,2,West,Cash,...,3,29,Other,Food,1.5,Returned,Negative,14.86,FREESHIP,4.0
31,2023-02-01,1537,170,3,92.85,0.13,242.3385,7,South,Cash,...,3,44,Female,Electronics,4.7,Not Returned,Negative,10.48,WELCOME5,1.1
32,2023-02-02,1484,165,8,30.45,0.26,180.2640,3,North,Credit Card,...,1,19,Other,Books,4.5,Not Returned,Neutral,6.87,SAVE10,4.5
33,2023-02-03,1784,169,9,53.80,0.09,440.6220,8,North,Cash,...,5,34,Male,Electronics,3.7,Returned,Negative,8.40,WELCOME5,1.8
34,2023-02-04,1896,190,4,92.98,0.17,308.6936,6,North,Credit Card,...,4,49,Male,Books,3.5,Not Returned,Positive,14.75,SAVE10,NaN

<div class="alert alert-success">

**Solution 01:**
</div>

In [3]:
# 1. Checking Missing Values in a DataFrame
# Write a Pandas program to check for missing values in a DataFrame.

# Check for missing values
missing_values = df.isnull().sum()
missing_values[missing_values > 0]

shipping_cost      3
delivery_rating    6
dtype: int64

<div class="alert alert-warning">

**2. Ensuring Consistent Data Types of All Columns**

**Write a Pandas program to check and ensure that the data types of all columns are consistent.**

</div>

In [4]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1412,103,3,92.64,0.29,197.3232,2,East,Cash,...,2,67,Other,Books,4.4,Returned,Positive,18.09,FREESHIP,NaN
1,2023-01-02,1873,163,3,52.88,0.21,125.3256,1,West,Cash,...,3,52,Female,Electronics,4.5,Not Returned,Neutral,18.52,nan,1.5
2,2023-01-03,1554,166,9,40.48,0.21,287.8128,8,South,Cash,...,4,42,Female,Food,4.5,Returned,Negative,5.08,SAVE10,1.6
3,2023-01-04,1887,171,4,77.21,0.06,290.3096,3,South,Credit Card,...,5,20,Male,Clothing,3.8,Not Returned,Positive,15.95,WELCOME5,3.3
4,2023-01-05,1120,196,9,39.78,0.07,332.9586,2,North,Credit Card,...,2,56,Female,Food,1.9,Not Returned,Neutral,16.16,nan,1.8
5,2023-01-06,1734,178,1,36.40,0.15,30.9400,5,South,Cash,...,6,26,Other,Clothing,4.9,Returned,Neutral,5.71,nan,NaN
6,2023-01-07,1694,137,1,49.18,0.15,41.8030,5,North,Online,...,3,38,Male,Electronics,3.1,Returned,Neutral,15.18,FREESHIP,4.2
7,2023-01-08,1492,183,2,22.68,0.14,39.0096,5,South,Credit Card,...,4,46,Female,Books,5.0,Returned,Negative,NaN,SAVE10,NaN
8,2023-01-09,1259,100,7,73.13,0.26,378.8134,1,South,Cash,...,2,41,Male,Food,2.9,Returned,Neutral,7.18,SAVE10,NaN
9,2023-01-10,1373,135,7,34.10,0.19,193.3470,4,West,Credit Card,...,6,19,Male,Electronics,1.2,Not Returned,Positive,16.09,WELCOME5,1.9
10,2023-01-11,1142,166,5,44.04,0.15,187.1700,6,South,Credit Card,...,6,61,Female,Electronics,1.5,Returned,Positive,13.52,FREESHIP,4.3
11,2023-01-12,1936,118,8,92.16,0.03,715.1616,3,West,Cash,...,2,40,Male,Books,1.2,Not Returned,Neutral,5.05,FREESHIP,3.9
12,2023-01-13,1771,192,8,96.66,0.28,556.7616,4,South,Credit Card,...,1,42,Female,Books,4.7,Returned,Neutral,17.24,FREESHIP,NaN
13,2023-01-14,1446,155,5,91.89,0.01,454.8555,9,South,Online,...,5,69,Male,Books,4.7,Returned,Negative,8.75,SAVE10,1.1
14,2023-01-15,1618,106,6,52.31,0.24,238.5336,9,East,Cash,...,5,68,Male,Books,4.1,Not Returned,Positive,12.81,FREESHIP,4.0
15,2023-01-16,1062,134,3,32.26,0.13,84.1986,7,East,Cash,...,4,32,Other,Books,2.2,Not Returned,Neutral,NaN,WELCOME5,4.4
16,2023-01-17,1287,168,8,61.32,0.23,377.7312,4,North,Cash,...,2,33,Male,Food,4.3,Not Returned,Neutral,17.06,WELCOME5,5.0
17,2023-01-18,1215,150,1,96.52,0.05,91.6940,6,North,Credit Card,...,3,69,Female,Books,2.4,Returned,Negative,15.40,FREESHIP,2.0
18,2023-01-19,1401,127,7,53.67,0.29,266.7399,9,West,Online,...,2,61,Male,Clothing,4.5,Not Returned,Positive,5.53,WELCOME5,4.9
19,2023-01-20,1919,197,3,18.32,0.05,52.2120,2,East,Online,...,1,56,Other,Clothing,3.3,Returned,Positive,10.87,FREESHIP,1.3
20,2023-01-21,1120,112,9,96.46,0.30,607.6980,4,North,Online,...,2,20,Male,Food,1.5,Returned,Neutral,8.37,nan,2.6
21,2023-01-22,1361,152,9,68.67,0.07,574.7679,7,North,Online,...,2,27,Male,Electronics,3.0,Returned,Negative,15.11,WELCOME5,2.5
22,2023-01-23,1718,154,4,61.58,0.14,211.8352,3,East,Cash,...,2,31,Other,Books,3.1,Returned,Negative,19.75,nan,NaN
23,2023-01-24,1490,120,4,84.16,0.01,333.2736,7,West,Online,...,4,21,Female,Electronics,4.9,Not Returned,Positive,17.18,SAVE10,4.5
24,2023-01-25,1563,191,3,83.91,0.16,211.4532,8,North,Credit Card,...,1,33,Male,Electronics,1.0,Returned,Neutral,5.17,nan,3.5
25,2023-01-26,1868,140,3,22.65,0.06,63.8730,8,East,Online,...,1,33,Other,Clothing,1.7,Not Returned,Positive,NaN,nan,1.7
26,2023-01-27,1043,117,4,23.72,0.05,90.1360,7,South,Online,...,4,18,Other,Electronics,1.9,Not Returned,Negative,NaN,WELCOME5,1.2
27,2023-01-28,1433,113,3,49.27,0.15,125.6385,3,East,Credit Card,...,2,50,Male,Food,3.5,Returned,Positive,12.78,nan,NaN
28,2023-01-29,1126,169,7,60.29,0.15,358.7255,1,East,Online,...,1,42,Male,Food,4.6,Not Returned,Negative,NaN,WELCOME5,NaN
29,2023-01-30,1003,165,4,73.69,0.26,218.1224,9,East,Cash,...,2,37,Female,Food,3.1,Returned,Neutral,NaN,SAVE10,4.5
30,2023-01-31,1755,185,2,99.91,0.23,153.8614,9,West,Online,...,1,42,Female,Electronics,4.7,Not Returned,Positive,NaN,FREESHIP,2.7
31,2023-02-01,1369,167,6,51.09,0.04,294.2784,5,South,Credit Card,...,5,19,Male,Electronics,3.5,Not Returned,Positive,19.67,FREESHIP,2.2
32,2023-02-02,1504,160,4,57.43,0.30,160.8040,9,West,Online,...,3,28,Other,Clothing,3.2,Returned,Positive,10.95,FREESHIP,1.8
33,2023-02-03,1711,191,6,44.11,0.01,262.0134,8,East,Online,...,3,54,Other,Books,1.8,Not Returned,Positive,8.79,WELCOME5,NaN
34,2023-02-04,1812,108,7,42.44,0.28,213.8976,9,West,Cash,...,2,62,Female,Electronics,4.5,Returned,Positive,10.82,WELCOME5,NaN

<div class="alert alert-success">

**Solution 02:**
</div>

In [5]:
# 2. Ensuring Consistent Data Types of All Columns
# Write a Pandas program to check and ensure that the data types of all columns are consistent.

# Check data types
data_types = df.dtypes
data_types

date                datetime64[ns]
customer_id                  int64
product_id                   int64
quantity                     int64
price                      float64
discount                   float64
revenue                    float64
store_id                     int64
region                      object
payment_method              object
is_member                     bool
delivery_days                int64
customer_age                 int64
gender                      object
product_category            object
rating                     float64
return_status               object
feedback                    object
shipping_cost              float64
coupon_code                 object
delivery_rating            float64
dtype: object

<div class="alert alert-warning">

**3. Validating the Data Type of a Specific Column**

**Write a Pandas program to validate the data type of a specific column in a DataFrame.**

</div>

In [6]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1165,108,7,64.09,0.01,444.1437,9,North,Online,...,2,67,Other,Electronics,4.5,Not Returned,Neutral,11.54,WELCOME5,2.1
1,2023-01-02,1736,178,2,77.24,0.09,140.5768,9,East,Cash,...,1,65,Female,Books,1.1,Returned,Neutral,14.08,nan,NaN
2,2023-01-03,1759,190,4,34.30,0.27,100.1560,2,East,Credit Card,...,3,23,Female,Electronics,1.5,Not Returned,Positive,13.63,FREESHIP,4.6
3,2023-01-04,1883,195,9,56.13,0.10,454.6530,8,West,Cash,...,1,69,Female,Electronics,3.7,Not Returned,Positive,15.32,WELCOME5,NaN
4,2023-01-05,1817,104,8,60.82,0.28,350.3232,6,West,Online,...,6,58,Other,Books,2.2,Not Returned,Negative,13.80,nan,1.9
5,2023-01-06,1381,118,8,28.24,0.02,221.4016,8,West,Online,...,2,69,Female,Clothing,2.5,Returned,Negative,11.85,FREESHIP,4.8
6,2023-01-07,1246,106,2,40.59,0.19,65.7558,3,West,Online,...,1,29,Male,Electronics,1.8,Not Returned,Neutral,NaN,SAVE10,3.2
7,2023-01-08,1380,133,8,83.09,0.11,591.6008,8,North,Credit Card,...,3,63,Other,Books,3.6,Returned,Positive,NaN,nan,NaN
8,2023-01-09,1181,164,2,78.37,0.25,117.5550,5,West,Credit Card,...,1,61,Other,Food,3.2,Returned,Positive,13.64,nan,1.8
9,2023-01-10,1386,178,8,27.52,0.14,189.3376,2,West,Cash,...,1,61,Male,Electronics,2.4,Returned,Negative,16.18,FREESHIP,2.6
10,2023-01-11,1711,124,7,37.31,0.20,208.9360,8,East,Online,...,3,27,Other,Food,4.0,Not Returned,Positive,NaN,nan,NaN
11,2023-01-12,1484,102,7,21.07,0.14,126.8414,8,North,Online,...,6,25,Other,Electronics,2.0,Not Returned,Positive,11.66,nan,NaN
12,2023-01-13,1447,143,4,15.54,0.06,58.4304,3,East,Credit Card,...,2,41,Male,Food,1.6,Returned,Positive,19.37,nan,NaN
13,2023-01-14,1326,109,5,18.08,0.12,79.5520,3,East,Cash,...,3,37,Female,Books,5.0,Not Returned,Negative,16.14,nan,2.5
14,2023-01-15,1104,112,9,19.77,0.23,137.0061,9,South,Credit Card,...,2,19,Other,Electronics,5.0,Not Returned,Negative,5.15,WELCOME5,NaN
15,2023-01-16,1377,115,5,85.40,0.29,303.1700,2,East,Cash,...,2,35,Male,Food,2.1,Not Returned,Neutral,NaN,SAVE10,2.8
16,2023-01-17,1598,121,7,40.65,0.06,267.4770,6,East,Online,...,1,57,Male,Electronics,3.2,Not Returned,Neutral,5.28,nan,NaN
17,2023-01-18,1584,132,1,21.91,0.20,17.5280,1,East,Online,...,2,42,Male,Clothing,1.2,Returned,Neutral,16.67,SAVE10,3.0
18,2023-01-19,1217,199,7,53.30,0.03,361.9070,9,West,Cash,...,6,67,Male,Food,1.3,Returned,Negative,15.21,SAVE10,3.8
19,2023-01-20,1268,187,1,88.22,0.04,84.6912,2,North,Credit Card,...,2,19,Female,Clothing,2.3,Returned,Positive,14.02,nan,3.1
20,2023-01-21,1727,188,9,89.64,0.27,588.9348,6,East,Cash,...,4,55,Female,Food,2.0,Not Returned,Neutral,12.12,FREESHIP,NaN
21,2023-01-22,1313,116,3,29.21,0.15,74.4855,3,North,Credit Card,...,4,29,Other,Food,1.9,Not Returned,Positive,13.60,FREESHIP,1.4
22,2023-01-23,1065,153,4,99.02,0.28,285.1776,8,West,Credit Card,...,5,42,Male,Books,2.9,Returned,Negative,NaN,SAVE10,4.3
23,2023-01-24,1099,142,9,15.56,0.25,105.0300,5,South,Cash,...,4,38,Other,Food,2.8,Not Returned,Neutral,17.75,WELCOME5,3.7
24,2023-01-25,1906,145,6,28.91,0.07,161.3178,5,North,Online,...,6,41,Male,Books,4.5,Returned,Negative,15.64,nan,3.4
25,2023-01-26,1186,116,1,11.81,0.25,8.8575,7,South,Credit Card,...,5,18,Male,Clothing,1.7,Returned,Neutral,16.19,nan,NaN
26,2023-01-27,1639,138,9,45.65,0.07,382.0905,1,East,Cash,...,1,50,Other,Clothing,4.2,Returned,Negative,10.44,nan,4.6
27,2023-01-28,1020,107,4,28.56,0.02,111.9552,3,North,Cash,...,2,33,Male,Food,3.7,Not Returned,Neutral,9.22,nan,2.3
28,2023-01-29,1519,131,5,33.43,0.27,122.0195,1,East,Credit Card,...,6,30,Male,Electronics,3.1,Not Returned,Positive,NaN,nan,2.9
29,2023-01-30,1238,142,4,34.82,0.25,104.4600,8,East,Online,...,5,40,Other,Clothing,4.7,Not Returned,Neutral,13.79,nan,3.6
30,2023-01-31,1680,124,1,81.39,0.09,74.0649,9,South,Cash,...,6,44,Male,Food,1.5,Returned,Positive,NaN,SAVE10,1.3
31,2023-02-01,1711,113,8,32.11,0.02,251.7424,5,North,Online,...,2,48,Female,Clothing,2.2,Returned,Neutral,15.83,SAVE10,3.6
32,2023-02-02,1530,137,9,48.45,0.05,414.2475,5,South,Credit Card,...,6,24,Female,Clothing,3.2,Not Returned,Negative,5.53,FREESHIP,NaN
33,2023-02-03,1107,195,8,72.97,0.10,525.3840,4,South,Credit Card,...,5,62,Female,Food,3.7,Not Returned,Neutral,NaN,WELCOME5,4.2
34,2023-02-04,1935,123,5,78.57,0.08,361.4220,7,South,Online,...,4,18,Female,Clothing,4.6,Not Returned,Positive,12.04,nan,1.7

<div class="alert alert-success">

**Solution 03:**
</div>

In [7]:
# 3. Validating the Data Type of a Specific Column
# Write a Pandas program to validate the data type of a specific column in a DataFrame.

# Check if 'price' column is of type float
is_of_type = 'float64'
is_price_float = df['price'].dtype == is_of_type
is_price_float

# Validate the data type of 'price' column
if is_price_float:
    print("The 'price' column is of type {}.".format(df['price'].dtype))
else:
    print("The 'price' column is not of type {}, it is {}.".format(is_of_type, df['price'].dtype))

The 'price' column is of type float64.

<div class="alert alert-warning">

**4. Checking Duplicate Rows in a DataFrame**

**Write a Pandas program to check duplicate rows in a DataFrame.**

</div>

In [8]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Add 3 duplicate rows
df = pd.concat([df, df.sample(n=3, random_state=42)], ignore_index=True)

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1596,164,3,80.56,0.07,224.7624,9,South,Cash,...,5,21,Male,Food,3.4,Not Returned,Neutral,14.14,SAVE10,2.1
1,2023-01-02,1047,176,9,85.03,0.10,688.7430,3,South,Online,...,2,55,Male,Books,1.4,Not Returned,Neutral,10.95,SAVE10,4.9
2,2023-01-03,1001,119,8,74.93,0.30,419.6080,1,South,Credit Card,...,3,19,Male,Clothing,4.0,Not Returned,Neutral,14.11,WELCOME5,1.4
3,2023-01-04,1669,147,5,54.39,0.16,228.4380,6,North,Online,...,2,31,Female,Electronics,1.8,Not Returned,Positive,9.04,WELCOME5,3.7
4,2023-01-05,1658,124,7,27.26,0.29,135.4822,9,East,Online,...,3,25,Female,Food,3.4,Not Returned,Negative,NaN,SAVE10,3.2
5,2023-01-06,1733,189,3,60.21,0.29,128.2473,4,West,Online,...,6,47,Female,Books,4.8,Returned,Negative,NaN,nan,NaN
6,2023-01-07,1873,117,5,60.45,0.26,223.6650,2,West,Credit Card,...,6,69,Other,Clothing,3.2,Returned,Negative,NaN,SAVE10,3.8
7,2023-01-08,1202,135,7,54.59,0.24,290.4188,8,West,Online,...,2,28,Male,Food,3.3,Not Returned,Neutral,15.54,FREESHIP,3.7
8,2023-01-09,1716,145,1,18.31,0.03,17.7607,9,East,Cash,...,1,66,Male,Electronics,2.9,Returned,Positive,16.27,nan,3.3
9,2023-01-10,1279,120,2,83.92,0.08,154.4128,8,East,Credit Card,...,1,59,Male,Electronics,3.0,Not Returned,Negative,15.71,SAVE10,4.8
10,2023-01-11,1306,154,1,65.41,0.04,62.7936,3,East,Online,...,2,26,Other,Food,4.6,Returned,Negative,NaN,FREESHIP,4.4
11,2023-01-12,1507,114,9,59.47,0.22,417.4794,7,North,Credit Card,...,4,61,Male,Food,4.4,Not Returned,Positive,NaN,FREESHIP,NaN
12,2023-01-13,1843,175,9,20.47,0.19,149.2263,5,East,Credit Card,...,3,55,Other,Books,3.2,Not Returned,Negative,16.23,WELCOME5,NaN
13,2023-01-14,1142,116,8,95.33,0.12,671.1232,9,South,Credit Card,...,2,22,Female,Food,2.8,Not Returned,Negative,5.40,FREESHIP,NaN
14,2023-01-15,1946,191,6,75.68,0.19,367.8048,3,West,Cash,...,3,41,Female,Clothing,2.7,Returned,Negative,6.31,nan,NaN
15,2023-01-16,1070,141,9,77.23,0.20,556.0560,4,North,Credit Card,...,6,58,Other,Books,1.3,Not Returned,Neutral,5.65,WELCOME5,1.9
16,2023-01-17,1973,167,4,29.32,0.20,93.8240,2,South,Cash,...,1,39,Other,Books,2.7,Not Returned,Neutral,5.07,WELCOME5,2.5
17,2023-01-18,1197,153,8,50.23,0.17,333.5272,5,East,Cash,...,3,38,Female,Food,2.4,Not Returned,Positive,10.04,SAVE10,2.1
18,2023-01-19,1672,143,3,85.81,0.01,254.8557,5,West,Online,...,3,57,Female,Clothing,4.5,Not Returned,Negative,NaN,nan,4.1
19,2023-01-20,1295,152,6,14.60,0.26,64.8240,7,East,Credit Card,...,5,57,Male,Food,3.7,Returned,Neutral,NaN,nan,1.2
20,2023-01-21,1022,120,6,91.27,0.07,509.2866,8,East,Credit Card,...,2,34,Male,Clothing,2.4,Not Returned,Neutral,13.59,nan,3.7
21,2023-01-22,1477,124,4,43.75,0.15,148.7500,3,North,Credit Card,...,1,48,Male,Clothing,4.3,Not Returned,Positive,12.53,FREESHIP,3.5
22,2023-01-23,1869,124,9,32.09,0.12,254.1528,4,South,Online,...,3,45,Female,Books,2.5,Not Returned,Neutral,18.68,nan,3.4
23,2023-01-24,1949,186,9,86.84,0.30,547.0920,1,East,Credit Card,...,2,45,Female,Food,1.2,Not Returned,Positive,8.04,nan,4.7
24,2023-01-25,1320,186,3,31.19,0.03,90.7629,6,West,Cash,...,1,67,Male,Electronics,1.7,Returned,Negative,13.80,FREESHIP,4.9
25,2023-01-26,1880,196,7,94.00,0.03,638.2600,8,South,Credit Card,...,4,60,Other,Books,2.3,Not Returned,Positive,18.26,nan,2.0
26,2023-01-27,1634,194,4,40.83,0.07,151.8876,2,North,Online,...,5,63,Female,Food,2.4,Not Returned,Negative,8.97,SAVE10,4.9
27,2023-01-28,1654,152,8,66.87,0.09,486.8136,2,North,Online,...,4,44,Male,Food,2.2,Returned,Negative,15.50,FREESHIP,3.0
28,2023-01-29,1476,105,1,46.39,0.18,38.0398,7,East,Credit Card,...,1,37,Female,Food,2.3,Returned,Positive,10.54,nan,4.9
29,2023-01-30,1501,146,7,52.73,0.25,276.8325,8,East,Credit Card,...,6,63,Female,Books,2.2,Not Returned,Negative,17.13,nan,4.1
30,2023-01-31,1171,165,2,98.35,0.03,190.7990,4,West,Cash,...,1,32,Male,Clothing,1.1,Not Returned,Negative,8.27,FREESHIP,NaN
31,2023-02-01,1875,137,7,77.65,0.04,521.8080,3,West,Online,...,6,61,Female,Clothing,3.1,Not Returned,Negative,11.93,nan,4.2
32,2023-02-02,1704,117,9,38.36,0.15,293.4540,8,West,Cash,...,2,45,Other,Electronics,2.4,Not Returned,Positive,7.78,nan,2.9
33,2023-02-03,1807,106,5,38.35,0.13,166.8225,4,South,Credit Card,...,6,20,Female,Clothing,1.4,Not Returned,Neutral,12.61,WELCOME5,2.5
34,2023-02-04,1836,129,8,92.86,0.14,638.8768,7,South,Cash,...,4,52,Other,Electronics,3.0,Not Returned,Negative,18.30,WELCOME5,3.5
35,2023-01-27,1634,194,4,40.83,0.07,151.8876,2,North,Online,...,5,63,Female,Food,2.4,Not Returned,Negative,8.97,SAVE10,4.9
36,2023-01-14,1142,116,8,95.33,0.12,671.1232,9,South,Credit Card,...,2,22,Female,Food,2.8,Not Returned,Negative,5.40,FREESHIP,NaN
37,2023-01-25,1320,186,3,31.19,0.03,90.7629,6,West,Cash,...,1,67,Male,Electronics,1.7,Returned,Negative,13.80,FREESHIP,4.9

<div class="alert alert-success">

**Solution 04:**
</div>

In [9]:
# 4. Checking Duplicate Rows in a DataFrame
# Write a Pandas program to check duplicate rows in a DataFrame.

# Check for duplicate rows
duplicate_rows = df[df.duplicated()]
duplicate_rows

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
35,2023-01-27,1634,194,4,40.83,0.07,151.8876,2,North,Online,...,5,63,Female,Food,2.4,Not Returned,Negative,8.97,SAVE10,4.9
36,2023-01-14,1142,116,8,95.33,0.12,671.1232,9,South,Credit Card,...,2,22,Female,Food,2.8,Not Returned,Negative,5.40,FREESHIP,NaN
37,2023-01-25,1320,186,3,31.19,0.03,90.7629,6,West,Cash,...,1,67,Male,Electronics,1.7,Returned,Negative,13.80,FREESHIP,4.9