[Pandas Data Validation](https://www.w3resource.com/python-exercises/pandas/pandas-data-validation.php)

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

<div class="alert alert-warning">

**1. Checking Missing Values in a DataFrame**

**Write a Pandas program to check for missing values in a DataFrame.**

</div>

In [2]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1398,166,5,38.13,0.09,173.4915,2,West,Cash,False,3,64,Female,Electronics,4.8,Not Returned,Neutral,8.27,SAVE10,NaN
1,2023-01-02,1773,171,7,77.66,0.23,418.5874,4,West,Credit Card,True,4,44,Other,Clothing,1.3,Not Returned,Neutral,12.30,nan,4.7
2,2023-01-03,1631,146,4,25.76,0.04,98.9184,3,West,Cash,True,5,56,Male,Electronics,2.6,Returned,Positive,9.23,FREESHIP,NaN
3,2023-01-04,1262,169,6,15.02,0.27,65.7876,9,West,Credit Card,True,6,30,Female,Books,3.0,Returned,Neutral,11.39,SAVE10,3.9
4,2023-01-05,1747,196,6,82.90,0.20,397.9200,8,North,Credit Card,False,4,59,Female,Books,2.1,Returned,Negative,7.13,FREESHIP,4.6
5,2023-01-06,1520,174,9,64.29,0.29,410.8131,6,North,Cash,False,3,52,Other,Food,4.6,Not Returned,Negative,5.80,FREESHIP,4.6
6,2023-01-07,1184,118,5,69.69,0.07,324.0585,6,West,Cash,True,5,32,Female,Food,4.0,Returned,Negative,16.42,FREESHIP,1.6
7,2023-01-08,1838,152,6,18.42,0.01,109.4148,5,North,Cash,False,2,62,Male,Books,1.3,Not Returned,Positive,9.59,WELCOME5,3.4
8,2023-01-09,1634,169,7,16.24,0.06,106.8592,6,West,Online,False,5,68,Female,Electronics,1.7,Returned,Neutral,NaN,SAVE10,NaN
9,2023-01-10,1614,164,8,79.16,0.23,487.6256,8,South,Online,False,5,18,Female,Electronics,3.9,Not Returned,Negative,NaN,SAVE10,1.1
10,2023-01-11,1393,146,4,43.73,0.17,145.1836,1,North,Credit Card,True,3,34,Female,Food,3.8,Returned,Negative,15.09,FREESHIP,NaN
11,2023-01-12,1559,195,1,52.90,0.07,49.1970,4,West,Cash,False,1,52,Other,Food,2.2,Not Returned,Negative,10.37,SAVE10,NaN
12,2023-01-13,1966,185,7,38.61,0.06,254.0538,4,East,Cash,False,2,22,Other,Books,4.9,Returned,Neutral,17.20,FREESHIP,2.5
13,2023-01-14,1782,130,1,91.21,0.06,85.7374,7,South,Cash,False,1,37,Male,Food,4.1,Returned,Neutral,9.46,nan,NaN
14,2023-01-15,1561,135,4,52.10,0.29,147.9640,2,East,Online,True,1,18,Female,Books,4.9,Returned,Neutral,8.31,nan,4.8
15,2023-01-16,1387,149,4,88.94,0.17,295.2808,3,East,Cash,False,1,34,Male,Food,2.9,Not Returned,Neutral,14.80,nan,1.8
16,2023-01-17,1495,145,3,17.60,0.16,44.3520,1,West,Cash,False,3,60,Other,Books,1.7,Not Returned,Positive,16.71,FREESHIP,3.0
17,2023-01-18,1041,118,4,93.31,0.06,350.8456,7,South,Cash,True,6,36,Female,Books,4.3,Not Returned,Positive,5.66,nan,3.6
18,2023-01-19,1395,124,5,72.12,0.07,335.3580,7,North,Online,True,5,51,Female,Food,3.7,Not Returned,Neutral,14.57,FREESHIP,NaN
19,2023-01-20,1901,122,3,24.55,0.21,58.1835,5,West,Online,False,5,26,Other,Food,1.6,Not Returned,Neutral,5.83,nan,1.7
20,2023-01-21,1557,131,4,95.55,0.26,282.8280,1,South,Cash,True,1,63,Female,Electronics,3.6,Returned,Neutral,14.02,nan,NaN
21,2023-01-22,1509,121,5,52.11,0.07,242.3115,7,South,Credit Card,True,1,35,Other,Books,4.3,Returned,Negative,17.12,FREESHIP,NaN
22,2023-01-23,1392,191,3,34.79,0.05,99.1515,5,East,Online,False,4,31,Other,Clothing,4.0,Returned,Positive,10.86,nan,2.9
23,2023-01-24,1578,189,1,90.21,0.24,68.5596,6,South,Online,True,5,60,Male,Food,4.0,Not Returned,Positive,10.38,WELCOME5,3.7
24,2023-01-25,1185,108,7,46.57,0.23,251.0123,1,West,Online,False,4,55,Male,Clothing,1.1,Returned,Negative,NaN,FREESHIP,2.6
25,2023-01-26,1111,187,2,84.27,0.29,119.6634,8,South,Cash,False,1,41,Male,Food,4.3,Not Returned,Positive,13.81,nan,5.0
26,2023-01-27,1291,190,6,71.50,0.19,347.4900,6,West,Online,True,6,58,Other,Food,4.9,Returned,Neutral,5.35,FREESHIP,NaN
27,2023-01-28,1891,139,7,20.41,0.06,134.2978,7,East,Online,True,2,68,Other,Books,2.8,Not Returned,Negative,NaN,nan,2.8
28,2023-01-29,1330,124,7,31.59,0.14,190.1718,2,East,Credit Card,True,6,25,Other,Food,2.5,Not Returned,Negative,12.05,nan,1.1
29,2023-01-30,1412,167,1,60.20,0.18,49.3640,8,North,Cash,False,4,52,Male,Food,3.0,Not Returned,Positive,19.89,nan,4.3
30,2023-01-31,1464,172,3,55.76,0.06,157.2432,5,South,Online,True,3,56,Male,Food,3.3,Not Returned,Neutral,15.54,FREESHIP,NaN
31,2023-02-01,1295,130,3,76.39,0.15,194.7945,3,East,Online,True,5,64,Male,Books,3.2,Returned,Negative,NaN,WELCOME5,1.7
32,2023-02-02,1909,179,1,38.31,0.04,36.7776,6,South,Cash,False,2,29,Male,Clothing,4.4,Returned,Positive,19.27,nan,4.6
33,2023-02-03,1659,195,7,80.44,0.24,427.9408,1,West,Cash,True,4,68,Male,Clothing,1.9,Not Returned,Neutral,14.61,WELCOME5,4.5
34,2023-02-04,1641,163,3,52.57,0.25,118.2825,7,South,Online,True,1,39,Male,Electronics,3.1,Returned,Negative,9.93,nan,4.6

<div class="alert alert-success">

**Solution 01:**
</div>

In [3]:
# 1. Checking Missing Values in a DataFrame
# Write a Pandas program to check for missing values in a DataFrame.

# Check for missing values
missing_values = df.isnull().sum()
missing_values[missing_values > 0]

shipping_cost       5
delivery_rating    11
dtype: int64

<div class="alert alert-warning">

**2. Ensuring Consistent Data Types of All Columns**

**Write a Pandas program to check and ensure that the data types of all columns are consistent.**

</div>

In [4]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1720,104,7,23.78,0.26,123.1804,2,East,Cash,True,6,27,Other,Electronics,1.8,Returned,Neutral,11.76,nan,4.6
1,2023-01-02,1217,126,6,15.50,0.30,65.1000,3,South,Credit Card,False,1,50,Male,Electronics,3.5,Returned,Neutral,NaN,nan,3.5
2,2023-01-03,1954,117,3,19.27,0.24,43.9356,2,West,Online,True,1,47,Male,Food,2.2,Not Returned,Positive,NaN,nan,3.0
3,2023-01-04,1283,132,4,13.37,0.08,49.2016,9,East,Online,True,4,43,Male,Clothing,2.8,Returned,Positive,10.76,FREESHIP,4.7
4,2023-01-05,1666,174,7,44.82,0.14,269.8164,4,South,Online,True,5,40,Male,Food,3.0,Not Returned,Neutral,12.29,FREESHIP,NaN
5,2023-01-06,1261,170,7,25.92,0.24,137.8944,6,West,Online,False,2,36,Female,Food,2.2,Not Returned,Negative,NaN,FREESHIP,3.8
6,2023-01-07,1205,196,8,25.24,0.18,165.5744,1,North,Online,True,2,21,Male,Books,3.3,Returned,Positive,15.93,nan,NaN
7,2023-01-08,1560,168,6,49.09,0.22,229.7412,3,East,Online,False,4,38,Male,Books,2.8,Not Returned,Negative,8.32,WELCOME5,2.0
8,2023-01-09,1298,195,6,35.01,0.24,159.6456,4,East,Credit Card,False,3,66,Male,Clothing,4.6,Returned,Positive,7.27,WELCOME5,2.4
9,2023-01-10,1846,119,9,30.15,0.07,252.3555,1,South,Online,True,3,19,Male,Electronics,3.1,Returned,Neutral,17.98,SAVE10,4.4
10,2023-01-11,1290,119,9,57.21,0.09,468.5499,5,East,Online,True,2,19,Female,Electronics,4.9,Not Returned,Neutral,14.75,nan,2.6
11,2023-01-12,1887,191,8,50.65,0.11,360.6280,9,East,Cash,True,5,42,Male,Food,1.1,Not Returned,Positive,15.17,nan,4.3
12,2023-01-13,1568,111,5,95.60,0.16,401.5200,6,West,Online,False,2,39,Other,Food,2.0,Not Returned,Negative,8.69,WELCOME5,2.5
13,2023-01-14,1518,166,3,20.07,0.25,45.1575,4,West,Online,False,1,50,Male,Clothing,1.4,Not Returned,Negative,NaN,SAVE10,2.8
14,2023-01-15,1104,151,2,49.61,0.15,84.3370,7,East,Online,True,2,59,Other,Clothing,1.1,Not Returned,Negative,7.33,nan,4.7
15,2023-01-16,1508,105,8,35.04,0.22,218.6496,6,East,Online,True,1,31,Other,Electronics,4.5,Not Returned,Negative,11.58,FREESHIP,3.7
16,2023-01-17,1893,108,1,47.64,0.28,34.3008,6,North,Cash,True,6,23,Other,Clothing,1.6,Returned,Negative,16.52,WELCOME5,2.9
17,2023-01-18,1042,139,3,51.46,0.09,140.4858,9,North,Credit Card,False,5,39,Female,Food,1.9,Not Returned,Negative,12.95,SAVE10,NaN
18,2023-01-19,1685,169,4,15.60,0.28,44.9280,7,East,Cash,True,3,45,Female,Books,3.6,Not Returned,Neutral,NaN,SAVE10,3.6
19,2023-01-20,1518,172,4,65.99,0.24,200.6096,9,East,Credit Card,True,1,20,Male,Clothing,4.3,Returned,Negative,15.91,nan,2.5
20,2023-01-21,1768,167,4,72.93,0.04,280.0512,6,East,Online,True,5,26,Other,Books,3.3,Not Returned,Negative,17.99,WELCOME5,4.7
21,2023-01-22,1466,118,8,72.18,0.04,554.3424,8,East,Credit Card,True,5,55,Female,Books,4.1,Not Returned,Neutral,8.07,nan,1.8
22,2023-01-23,1232,108,5,42.17,0.04,202.4160,8,North,Online,False,2,33,Other,Clothing,2.5,Returned,Negative,NaN,nan,4.0
23,2023-01-24,1415,174,3,32.64,0.02,95.9616,1,South,Credit Card,True,2,47,Female,Clothing,1.9,Returned,Neutral,NaN,nan,1.4
24,2023-01-25,1687,109,8,91.05,0.06,684.6960,7,East,Online,False,4,35,Other,Electronics,3.2,Not Returned,Negative,8.68,FREESHIP,3.2
25,2023-01-26,1745,151,2,84.90,0.07,157.9140,8,South,Online,True,2,36,Female,Food,2.1,Returned,Negative,10.61,WELCOME5,NaN
26,2023-01-27,1471,137,5,70.16,0.28,252.5760,6,East,Credit Card,True,4,20,Female,Food,4.0,Returned,Positive,18.24,nan,NaN
27,2023-01-28,1821,133,3,65.71,0.00,197.1300,5,West,Cash,True,2,61,Male,Clothing,2.8,Not Returned,Negative,18.90,nan,1.0
28,2023-01-29,1876,129,3,29.31,0.28,63.3096,2,East,Credit Card,False,5,56,Female,Food,1.8,Not Returned,Negative,NaN,FREESHIP,4.6
29,2023-01-30,1278,157,8,20.08,0.04,154.2144,3,West,Online,False,4,53,Female,Electronics,4.2,Not Returned,Positive,14.81,SAVE10,2.6
30,2023-01-31,1507,131,9,85.52,0.06,723.4992,7,North,Online,False,1,57,Female,Electronics,4.8,Not Returned,Neutral,7.10,SAVE10,1.0
31,2023-02-01,1005,102,5,20.81,0.17,86.3615,9,West,Online,False,1,49,Other,Books,3.2,Not Returned,Neutral,NaN,SAVE10,1.5
32,2023-02-02,1459,156,2,29.81,0.05,56.6390,5,East,Online,True,2,18,Other,Food,1.4,Not Returned,Neutral,16.95,nan,1.4
33,2023-02-03,1056,167,3,29.99,0.21,71.0763,6,North,Online,False,3,57,Other,Electronics,2.7,Not Returned,Neutral,6.65,SAVE10,NaN
34,2023-02-04,1264,102,7,46.53,0.23,250.7967,9,East,Credit Card,True,3,64,Other,Clothing,4.8,Returned,Positive,16.06,nan,NaN

<div class="alert alert-success">

**Solution 02:**
</div>

In [5]:
# 2. Ensuring Consistent Data Types of All Columns
# Write a Pandas program to check and ensure that the data types of all columns are consistent.

# Check data types
data_types = df.dtypes
data_types

date                datetime64[ns]
customer_id                  int64
product_id                   int64
quantity                     int64
price                      float64
discount                   float64
revenue                    float64
store_id                     int64
region                      object
payment_method              object
is_member                     bool
delivery_days                int64
customer_age                 int64
gender                      object
product_category            object
rating                     float64
return_status               object
feedback                    object
shipping_cost              float64
coupon_code                 object
delivery_rating            float64
dtype: object

<div class="alert alert-warning">

**3. Validating the Data Type of a Specific Column**

**Write a Pandas program to validate the data type of a specific column in a DataFrame.**

</div>

In [6]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1522,190,2,19.57,0.03,37.9658,1,West,Cash,True,3,67,Other,Food,2.9,Not Returned,Neutral,12.50,nan,NaN
1,2023-01-02,1037,183,4,16.11,0.17,53.4852,9,North,Credit Card,False,4,40,Male,Books,1.2,Returned,Neutral,NaN,WELCOME5,1.9
2,2023-01-03,1704,122,9,29.11,0.13,227.9313,2,East,Cash,False,4,53,Other,Food,2.9,Not Returned,Positive,17.63,nan,4.0
3,2023-01-04,1090,167,7,49.52,0.14,298.1104,8,West,Cash,True,6,62,Other,Food,2.7,Returned,Negative,NaN,FREESHIP,4.0
4,2023-01-05,1404,147,6,49.77,0.28,215.0064,3,East,Online,True,5,64,Other,Books,3.2,Returned,Neutral,12.95,WELCOME5,NaN
5,2023-01-06,1053,125,6,67.69,0.21,320.8506,4,East,Credit Card,False,1,50,Other,Food,4.9,Returned,Neutral,NaN,nan,2.1
6,2023-01-07,1931,169,2,19.84,0.04,38.0928,6,North,Online,False,2,56,Female,Food,4.6,Not Returned,Neutral,13.67,nan,NaN
7,2023-01-08,1724,106,5,80.13,0.06,376.6110,6,North,Online,False,3,40,Female,Electronics,1.2,Not Returned,Neutral,15.90,WELCOME5,NaN
8,2023-01-09,1141,173,4,38.24,0.04,146.8416,6,South,Cash,False,4,31,Other,Electronics,4.5,Returned,Neutral,NaN,nan,NaN
9,2023-01-10,1167,124,2,20.59,0.14,35.4148,3,South,Online,False,2,21,Female,Clothing,3.5,Not Returned,Negative,16.03,nan,NaN
10,2023-01-11,1215,105,1,88.86,0.08,81.7512,3,West,Credit Card,True,5,66,Other,Food,1.6,Not Returned,Neutral,5.62,nan,2.3
11,2023-01-12,1636,112,7,56.58,0.19,320.8086,2,North,Credit Card,False,4,22,Male,Books,1.1,Returned,Neutral,13.07,FREESHIP,2.4
12,2023-01-13,1714,113,5,74.12,0.14,318.7160,6,East,Credit Card,False,5,23,Other,Food,4.8,Not Returned,Negative,8.44,FREESHIP,1.2
13,2023-01-14,1720,132,4,33.83,0.29,96.0772,4,West,Online,True,6,64,Other,Food,4.9,Not Returned,Positive,5.28,SAVE10,2.2
14,2023-01-15,1674,116,2,10.66,0.17,17.6956,2,West,Credit Card,True,4,38,Other,Food,2.2,Not Returned,Neutral,7.97,FREESHIP,NaN
15,2023-01-16,1956,108,4,35.44,0.27,103.4848,5,East,Credit Card,False,4,33,Female,Electronics,3.3,Returned,Positive,5.58,nan,2.3
16,2023-01-17,1287,149,9,58.75,0.18,433.5750,3,South,Cash,False,4,18,Female,Clothing,1.8,Returned,Positive,15.84,nan,NaN
17,2023-01-18,1091,184,2,34.75,0.14,59.7700,3,North,Credit Card,True,4,57,Male,Clothing,2.7,Not Returned,Neutral,NaN,FREESHIP,NaN
18,2023-01-19,1823,184,2,45.99,0.04,88.3008,1,West,Credit Card,True,4,37,Female,Clothing,1.7,Not Returned,Positive,17.72,nan,5.0
19,2023-01-20,1572,180,5,53.82,0.20,215.2800,8,West,Credit Card,False,1,36,Male,Books,4.2,Returned,Positive,NaN,nan,4.2
20,2023-01-21,1591,103,8,39.31,0.00,314.4800,8,South,Credit Card,False,2,52,Female,Clothing,3.4,Returned,Negative,9.57,FREESHIP,3.4
21,2023-01-22,1536,197,9,93.56,0.28,606.2688,4,West,Online,False,5,50,Other,Clothing,3.6,Returned,Neutral,11.04,nan,3.5
22,2023-01-23,1171,108,4,33.97,0.16,114.1392,6,West,Credit Card,True,6,20,Male,Books,1.2,Not Returned,Positive,NaN,FREESHIP,2.0
23,2023-01-24,1173,122,8,21.61,0.01,171.1512,7,East,Online,False,5,40,Other,Books,4.7,Not Returned,Negative,11.03,FREESHIP,NaN
24,2023-01-25,1172,171,7,54.23,0.18,311.2802,3,South,Credit Card,True,5,30,Female,Food,1.8,Returned,Neutral,10.89,nan,4.2
25,2023-01-26,1895,181,4,84.44,0.14,290.4736,8,North,Online,True,6,23,Male,Clothing,3.6,Returned,Negative,10.74,SAVE10,NaN
26,2023-01-27,1623,198,2,90.35,0.04,173.4720,6,North,Cash,True,1,36,Male,Electronics,1.2,Not Returned,Neutral,6.40,nan,1.6
27,2023-01-28,1332,181,6,30.51,0.23,140.9562,6,North,Credit Card,False,6,38,Male,Clothing,1.5,Not Returned,Positive,8.42,WELCOME5,NaN
28,2023-01-29,1758,167,6,35.59,0.08,196.4568,5,West,Online,False,4,47,Male,Books,1.6,Not Returned,Negative,NaN,SAVE10,2.1
29,2023-01-30,1411,137,6,56.86,0.21,269.5164,1,East,Online,False,5,28,Female,Electronics,2.3,Returned,Negative,6.34,FREESHIP,2.4
30,2023-01-31,1823,165,5,79.29,0.22,309.2310,4,West,Online,False,6,18,Other,Electronics,3.5,Not Returned,Negative,12.92,FREESHIP,NaN
31,2023-02-01,1721,101,7,82.08,0.09,522.8496,3,West,Cash,False,3,29,Male,Food,4.5,Not Returned,Negative,6.55,nan,4.6
32,2023-02-02,1540,171,9,47.28,0.03,412.7544,5,East,Cash,True,6,67,Male,Books,3.0,Returned,Negative,7.56,FREESHIP,3.3
33,2023-02-03,1311,118,7,82.24,0.06,541.1392,8,North,Online,False,2,36,Other,Food,1.7,Not Returned,Negative,14.46,nan,4.4
34,2023-02-04,1658,176,6,13.55,0.06,76.4220,7,South,Online,True,1,26,Male,Food,2.1,Not Returned,Negative,11.64,WELCOME5,4.9

<div class="alert alert-success">

**Solution 03:**
</div>

In [7]:
# 3. Validating the Data Type of a Specific Column
# Write a Pandas program to validate the data type of a specific column in a DataFrame.

# Check if 'price' column is of type float
is_of_type = 'float64'
is_price_float = df['price'].dtype == is_of_type
is_price_float

# Validate the data type of 'price' column
if is_price_float:
    print("The 'price' column is of type {}.".format(df['price'].dtype))
else:
    print("The 'price' column is not of type {}, it is {}.".format(is_of_type, df['price'].dtype))

The 'price' column is of type float64.

<div class="alert alert-warning">

**4. Checking Duplicate Rows in a DataFrame**

**Write a Pandas program to check duplicate rows in a DataFrame.**

</div>

In [8]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Add 3 duplicate rows
df = pd.concat([df, df.sample(n=3, random_state=42)], ignore_index=True)

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1584,138,4,74.05,0.22,231.0360,5,South,Online,False,1,40,Female,Clothing,4.5,Returned,Positive,10.63,nan,NaN
1,2023-01-02,1292,174,7,21.82,0.13,132.8838,6,North,Cash,False,2,18,Female,Electronics,4.8,Returned,Neutral,19.88,SAVE10,NaN
2,2023-01-03,1145,187,8,62.82,0.07,467.3808,5,North,Cash,True,3,55,Male,Clothing,1.3,Not Returned,Negative,8.39,WELCOME5,4.7
3,2023-01-04,1200,184,5,26.93,0.21,106.3735,4,East,Online,True,4,49,Male,Food,2.1,Returned,Neutral,18.78,SAVE10,2.7
4,2023-01-05,1942,155,5,47.32,0.07,220.0380,1,North,Credit Card,True,3,61,Male,Food,3.3,Returned,Positive,14.22,nan,NaN
5,2023-01-06,1938,141,8,91.66,0.03,711.2816,1,East,Credit Card,False,2,38,Other,Books,2.3,Not Returned,Neutral,15.52,nan,4.4
6,2023-01-07,1694,179,2,40.00,0.13,69.6000,6,South,Online,True,3,43,Male,Clothing,4.4,Not Returned,Negative,19.06,FREESHIP,1.1
7,2023-01-08,1453,178,6,52.31,0.11,279.3354,6,West,Cash,False,3,55,Male,Food,3.2,Returned,Negative,12.63,nan,NaN
8,2023-01-09,1357,107,4,77.75,0.15,264.3500,8,North,Cash,True,5,60,Female,Electronics,4.5,Not Returned,Negative,7.87,SAVE10,1.4
9,2023-01-10,1048,172,7,40.36,0.25,211.8900,1,East,Credit Card,False,4,27,Other,Books,2.5,Not Returned,Negative,17.92,FREESHIP,3.5
10,2023-01-11,1172,161,3,43.84,0.01,130.2048,2,West,Online,False,3,65,Female,Clothing,3.3,Not Returned,Neutral,8.26,FREESHIP,3.9
11,2023-01-12,1335,112,4,49.78,0.01,197.1288,6,East,Online,True,4,28,Male,Food,3.6,Returned,Positive,NaN,SAVE10,2.6
12,2023-01-13,1654,173,2,85.68,0.07,159.3648,7,South,Online,True,6,28,Male,Clothing,1.7,Returned,Neutral,11.09,WELCOME5,NaN
13,2023-01-14,1811,148,1,54.80,0.07,50.9640,9,South,Cash,True,4,23,Female,Electronics,1.5,Returned,Neutral,8.14,FREESHIP,NaN
14,2023-01-15,1425,193,5,79.30,0.24,301.3400,3,West,Online,False,1,48,Female,Electronics,1.8,Returned,Negative,NaN,nan,3.6
15,2023-01-16,1266,142,9,67.98,0.17,507.8106,7,North,Credit Card,True,3,33,Male,Food,4.2,Not Returned,Positive,6.84,FREESHIP,4.3
16,2023-01-17,1394,195,6,46.90,0.01,278.5860,4,North,Online,True,1,47,Other,Clothing,3.1,Not Returned,Negative,13.45,SAVE10,4.5
17,2023-01-18,1407,193,7,53.81,0.21,297.5693,3,North,Credit Card,False,3,20,Other,Books,2.4,Returned,Positive,11.53,FREESHIP,NaN
18,2023-01-19,1922,120,1,40.08,0.25,30.0600,8,East,Credit Card,False,4,35,Other,Food,1.5,Not Returned,Positive,NaN,FREESHIP,NaN
19,2023-01-20,1179,129,7,13.57,0.27,69.3427,1,West,Online,False,4,68,Female,Books,2.8,Not Returned,Neutral,12.63,nan,NaN
20,2023-01-21,1837,173,1,33.20,0.09,30.2120,2,East,Online,False,1,63,Female,Books,3.0,Returned,Negative,14.75,nan,4.6
21,2023-01-22,1976,198,4,40.64,0.13,141.4272,1,North,Credit Card,True,6,34,Male,Food,2.9,Returned,Positive,11.10,FREESHIP,2.0
22,2023-01-23,1494,149,9,24.55,0.17,183.3885,2,North,Cash,True,5,69,Male,Food,3.9,Returned,Neutral,11.92,nan,4.5
23,2023-01-24,1983,108,8,96.07,0.30,537.9920,5,South,Credit Card,True,1,30,Other,Food,4.4,Returned,Neutral,NaN,FREESHIP,4.7
24,2023-01-25,1289,128,7,42.04,0.07,273.6804,8,North,Cash,False,1,35,Other,Books,1.9,Returned,Positive,6.48,SAVE10,2.0
25,2023-01-26,1393,175,7,99.54,0.13,606.1986,1,South,Cash,False,5,49,Male,Electronics,4.1,Not Returned,Negative,6.21,nan,NaN
26,2023-01-27,1669,195,8,68.59,0.03,532.2584,2,South,Credit Card,True,1,24,Male,Electronics,3.9,Returned,Negative,NaN,WELCOME5,3.1
27,2023-01-28,1157,197,1,31.45,0.04,30.1920,6,South,Credit Card,True,1,21,Male,Clothing,3.4,Returned,Positive,19.50,SAVE10,1.1
28,2023-01-29,1260,142,3,95.55,0.01,283.7835,7,North,Online,False,2,40,Female,Clothing,4.6,Not Returned,Negative,7.51,nan,NaN
29,2023-01-30,1871,103,3,33.56,0.17,83.5644,4,West,Credit Card,False,1,29,Other,Food,4.8,Returned,Positive,6.61,nan,4.7
30,2023-01-31,1549,173,8,22.24,0.01,176.1408,7,East,Cash,False,3,63,Male,Clothing,1.9,Not Returned,Neutral,13.10,nan,3.7
31,2023-02-01,1934,115,7,51.20,0.15,304.6400,6,East,Online,False,5,39,Female,Electronics,3.7,Returned,Neutral,NaN,SAVE10,3.5
32,2023-02-02,1659,196,2,13.86,0.14,23.8392,3,South,Cash,False,2,45,Other,Electronics,2.8,Returned,Neutral,16.52,nan,2.1
33,2023-02-03,1963,124,9,95.27,0.21,677.3697,4,North,Online,False,2,20,Other,Food,4.9,Returned,Negative,8.38,SAVE10,4.2
34,2023-02-04,1015,163,8,31.64,0.28,182.2464,9,South,Cash,True,5,26,Male,Books,4.0,Not Returned,Neutral,15.88,nan,NaN
35,2023-01-27,1669,195,8,68.59,0.03,532.2584,2,South,Credit Card,True,1,24,Male,Electronics,3.9,Returned,Negative,NaN,WELCOME5,3.1
36,2023-01-14,1811,148,1,54.80,0.07,50.9640,9,South,Cash,True,4,23,Female,Electronics,1.5,Returned,Neutral,8.14,FREESHIP,NaN
37,2023-01-25,1289,128,7,42.04,0.07,273.6804,8,North,Cash,False,1,35,Other,Books,1.9,Returned,Positive,6.48,SAVE10,2.0

<div class="alert alert-success">

**Solution 04:**
</div>

In [9]:
# 4. Checking Duplicate Rows in a DataFrame
# Write a Pandas program to check duplicate rows in a DataFrame.

# Check for duplicate rows
duplicate_rows = df[df.duplicated()]
duplicate_rows

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
35,2023-01-27,1669,195,8,68.59,0.03,532.2584,2,South,Credit Card,True,1,24,Male,Electronics,3.9,Returned,Negative,NaN,WELCOME5,3.1
36,2023-01-14,1811,148,1,54.80,0.07,50.9640,9,South,Cash,True,4,23,Female,Electronics,1.5,Returned,Neutral,8.14,FREESHIP,NaN
37,2023-01-25,1289,128,7,42.04,0.07,273.6804,8,North,Cash,False,1,35,Other,Books,1.9,Returned,Positive,6.48,SAVE10,2.0

<div class="alert alert-warning">

**5. Removing Duplicate Rows from a DataFrame**

**Write a Pandas program to remove duplicate rows from a DataFrame.**

</div>

In [10]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Add 3 duplicate rows
df = pd.concat([df, df.sample(n=3, random_state=42)], ignore_index=True)

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1765,149,8,23.92,0.11,170.3104,2,South,Online,False,1,28,Male,Clothing,5.0,Returned,Neutral,16.40,WELCOME5,1.7
1,2023-01-02,1745,133,2,84.79,0.12,149.2304,2,North,Online,True,2,36,Male,Books,2.7,Not Returned,Negative,6.65,nan,4.5
2,2023-01-03,1936,183,6,48.04,0.12,253.6512,5,South,Cash,True,3,50,Other,Books,5.0,Not Returned,Negative,5.93,nan,4.4
3,2023-01-04,1637,142,4,24.17,0.18,79.2776,2,East,Credit Card,False,3,59,Other,Books,3.1,Not Returned,Neutral,NaN,nan,NaN
4,2023-01-05,1623,168,5,10.99,0.29,39.0145,3,East,Cash,False,2,41,Female,Clothing,3.1,Returned,Positive,15.72,nan,1.1
5,2023-01-06,1751,101,3,78.57,0.12,207.4248,3,East,Online,False,3,32,Other,Electronics,1.1,Returned,Positive,NaN,WELCOME5,NaN
6,2023-01-07,1391,160,6,67.33,0.21,319.1442,3,South,Credit Card,False,4,49,Female,Books,4.2,Not Returned,Positive,17.12,SAVE10,5.0
7,2023-01-08,1780,106,8,94.96,0.15,645.7280,2,West,Cash,True,5,43,Other,Electronics,2.8,Not Returned,Positive,14.20,nan,NaN
8,2023-01-09,1348,137,1,27.33,0.21,21.5907,8,West,Cash,False,3,65,Male,Food,3.9,Not Returned,Negative,5.20,FREESHIP,NaN
9,2023-01-10,1579,196,1,81.71,0.12,71.9048,2,East,Credit Card,False,2,32,Other,Food,3.8,Returned,Neutral,10.61,nan,4.5
10,2023-01-11,1202,190,4,51.95,0.30,145.4600,8,South,Online,True,4,58,Other,Clothing,2.5,Returned,Neutral,10.66,FREESHIP,NaN
11,2023-01-12,1674,178,9,71.02,0.11,568.8702,4,West,Online,True,4,35,Male,Books,2.3,Returned,Neutral,8.16,nan,4.2
12,2023-01-13,1230,183,7,14.42,0.23,77.7238,8,North,Cash,True,2,49,Other,Electronics,2.0,Not Returned,Positive,15.86,FREESHIP,2.1
13,2023-01-14,1815,114,6,30.60,0.28,132.1920,7,East,Credit Card,True,2,41,Male,Electronics,3.9,Returned,Neutral,6.43,WELCOME5,3.0
14,2023-01-15,1598,118,7,47.81,0.10,301.2030,5,North,Credit Card,True,3,19,Female,Food,4.3,Returned,Neutral,12.76,WELCOME5,2.9
15,2023-01-16,1602,120,7,18.18,0.02,124.7148,9,South,Online,True,3,62,Female,Food,1.9,Returned,Neutral,6.19,nan,2.8
16,2023-01-17,1299,132,6,85.72,0.20,411.4560,6,East,Credit Card,True,3,33,Other,Food,2.2,Not Returned,Negative,19.71,nan,2.6
17,2023-01-18,1166,141,3,57.89,0.06,163.2498,4,South,Online,True,1,22,Male,Books,3.3,Not Returned,Positive,10.52,nan,NaN
18,2023-01-19,1819,193,1,70.37,0.27,51.3701,6,East,Credit Card,True,1,35,Other,Books,2.4,Returned,Positive,14.28,WELCOME5,2.2
19,2023-01-20,1353,172,9,45.38,0.01,404.3358,6,North,Credit Card,True,6,37,Other,Electronics,2.3,Not Returned,Positive,6.23,WELCOME5,2.6
20,2023-01-21,1651,103,4,54.80,0.04,210.4320,1,East,Credit Card,True,6,23,Other,Clothing,4.2,Returned,Positive,NaN,nan,4.3
21,2023-01-22,1869,107,3,14.13,0.09,38.5749,3,West,Cash,True,5,60,Male,Clothing,1.7,Not Returned,Positive,11.33,nan,4.3
22,2023-01-23,1256,100,1,16.69,0.08,15.3548,3,West,Cash,True,5,65,Female,Clothing,3.8,Returned,Negative,12.17,WELCOME5,3.9
23,2023-01-24,1248,169,6,77.22,0.17,384.5556,1,East,Online,True,2,36,Male,Books,3.7,Returned,Negative,14.47,SAVE10,NaN
24,2023-01-25,1372,110,1,28.59,0.26,21.1566,9,West,Online,True,5,43,Male,Books,4.0,Returned,Negative,5.43,nan,2.8
25,2023-01-26,1617,160,2,92.77,0.19,150.2874,8,North,Cash,True,6,37,Female,Food,1.3,Returned,Neutral,7.30,nan,4.5
26,2023-01-27,1255,104,6,14.79,0.03,86.0778,5,South,Online,False,5,42,Other,Electronics,4.2,Returned,Neutral,12.06,WELCOME5,1.1
27,2023-01-28,1232,171,7,79.04,0.28,398.3616,4,South,Credit Card,False,2,28,Other,Clothing,3.6,Not Returned,Positive,12.63,FREESHIP,1.6
28,2023-01-29,1221,120,3,26.62,0.06,75.0684,8,West,Online,True,5,36,Male,Books,4.9,Not Returned,Neutral,5.49,FREESHIP,3.3
29,2023-01-30,1499,115,2,63.95,0.12,112.5520,5,West,Online,False,3,48,Female,Clothing,3.2,Returned,Negative,NaN,WELCOME5,NaN
30,2023-01-31,1794,149,9,11.82,0.11,94.6782,3,North,Online,True,3,34,Female,Electronics,2.9,Not Returned,Negative,12.57,SAVE10,3.4
31,2023-02-01,1149,138,9,49.53,0.27,325.4121,4,East,Credit Card,False,2,31,Female,Books,4.6,Returned,Negative,17.69,SAVE10,3.5
32,2023-02-02,1400,119,2,23.62,0.28,34.0128,6,West,Credit Card,True,2,27,Male,Food,4.8,Not Returned,Negative,9.35,nan,1.3
33,2023-02-03,1722,191,2,37.32,0.22,58.2192,6,North,Credit Card,True,6,67,Male,Clothing,3.2,Returned,Neutral,NaN,nan,4.4
34,2023-02-04,1626,131,5,53.94,0.26,199.5780,5,North,Online,False,2,55,Female,Clothing,2.2,Returned,Neutral,12.80,WELCOME5,2.6
35,2023-01-27,1255,104,6,14.79,0.03,86.0778,5,South,Online,False,5,42,Other,Electronics,4.2,Returned,Neutral,12.06,WELCOME5,1.1
36,2023-01-14,1815,114,6,30.60,0.28,132.1920,7,East,Credit Card,True,2,41,Male,Electronics,3.9,Returned,Neutral,6.43,WELCOME5,3.0
37,2023-01-25,1372,110,1,28.59,0.26,21.1566,9,West,Online,True,5,43,Male,Books,4.0,Returned,Negative,5.43,nan,2.8

<div class="alert alert-success">

**Solution 05:**
</div>

In [11]:
# 5. Removing Duplicate Rows from a DataFrame
# Write a Pandas program to remove duplicate rows from a DataFrame.

print("Shape of DataFrame before removing duplicates:\n", df.shape)
# Remove duplicate rows
df = df.drop_duplicates()
print("Shape of DataFrame after removing duplicates:\n", df.shape)

Shape of DataFrame before removing duplicates:
 (38, 21)
Shape of DataFrame after removing duplicates:
 (35, 21)

<div class="alert alert-warning">

**6. Validating Data Based on Custom Conditions**

**Write a Pandas program to validate data based on custom conditions.**

</div>

In [12]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Add 3 duplicate rows
df = pd.concat([df, df.sample(n=3, random_state=42)], ignore_index=True)

# Add 3 more rows with negative price
df = pd.concat([df, pd.DataFrame({
    'date': pd.date_range(start='2023-02-05', periods=3, freq='D'),
    'customer_id': [1500, 1501, 1502],
    'product_id': [150, 151, 152],
    'quantity': [2, 3, 1],
    'price': [-20.00, -15.00, -30.00],  # Negative prices
    'discount': [0.1, 0.2, 0.15],
    'revenue': [0, 0, 0],  # Placeholder; will be recalculated
    'store_id': [5, 6, 7],
    'region': ['North', 'South', 'East'],
    'payment_method': ['Credit Card', 'Cash', 'Online'],
    'is_member': [True, False, True],
    'delivery_days': [3, 4, 2],
    'customer_age': [25, 34, 45],
    'gender': ['Male', 'Female', 'Other'],
    'product_category': ['Electronics', 'Clothing', 'Books'],
    'rating': [4.5, 3.0, 5.0],
    'return_status': ['Not Returned', 'Returned', 'Not Returned'],
    'feedback': ['Positive', 'Neutral', 'Negative'],
})], ignore_index=True)

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1255,119,7,67.95,0.22,371.0070,5,West,Online,False,6,45,Male,Food,2.2,Not Returned,Neutral,18.47,WELCOME5,4.2
1,2023-01-02,1942,173,8,20.39,0.18,133.7584,7,East,Credit Card,True,2,61,Male,Clothing,2.7,Not Returned,Negative,5.16,FREESHIP,4.0
2,2023-01-03,1773,198,5,48.06,0.08,221.0760,5,West,Cash,False,1,30,Other,Clothing,2.8,Returned,Neutral,15.26,FREESHIP,NaN
3,2023-01-04,1724,166,8,29.25,0.10,210.6000,6,North,Cash,True,5,44,Female,Clothing,4.6,Returned,Negative,15.19,nan,NaN
4,2023-01-05,1164,188,3,59.38,0.02,174.5772,6,South,Cash,True,2,46,Other,Electronics,4.4,Returned,Positive,6.10,nan,4.8
5,2023-01-06,1214,113,6,79.59,0.24,362.9304,5,North,Online,False,4,56,Female,Electronics,1.8,Not Returned,Negative,NaN,FREESHIP,3.9
6,2023-01-07,1044,174,8,73.06,0.05,555.2560,6,South,Cash,False,2,65,Female,Electronics,1.3,Returned,Neutral,14.11,SAVE10,NaN
7,2023-01-08,1436,189,5,60.45,0.01,299.2275,4,West,Online,True,2,33,Female,Electronics,1.0,Not Returned,Negative,8.11,FREESHIP,3.3
8,2023-01-09,1987,131,6,68.56,0.28,296.1792,7,West,Online,True,6,40,Male,Books,3.2,Returned,Neutral,14.35,nan,NaN
9,2023-01-10,1524,121,6,22.28,0.27,97.5864,4,South,Credit Card,True,1,35,Female,Electronics,3.5,Not Returned,Positive,11.45,WELCOME5,3.1
10,2023-01-11,1011,161,5,52.31,0.22,204.0090,7,South,Credit Card,False,3,52,Female,Clothing,1.0,Returned,Positive,12.54,SAVE10,2.2
11,2023-01-12,1059,116,6,99.97,0.04,575.8272,4,East,Credit Card,False,4,39,Other,Electronics,4.9,Returned,Positive,14.61,WELCOME5,1.7
12,2023-01-13,1117,185,2,72.87,0.14,125.3364,8,North,Cash,True,1,52,Other,Books,1.0,Not Returned,Neutral,9.69,WELCOME5,NaN
13,2023-01-14,1700,176,6,91.55,0.07,510.8490,3,West,Credit Card,False,4,69,Male,Electronics,1.4,Returned,Neutral,18.57,nan,2.9
14,2023-01-15,1425,118,6,11.18,0.05,63.7260,7,North,Online,False,4,20,Female,Clothing,3.3,Returned,Negative,NaN,FREESHIP,4.8
15,2023-01-16,1974,118,5,85.78,0.21,338.8310,1,North,Online,True,3,52,Male,Clothing,3.5,Returned,Positive,16.05,nan,2.0
16,2023-01-17,1266,190,1,36.94,0.01,36.5706,8,West,Cash,False,5,48,Male,Clothing,1.7,Returned,Neutral,NaN,nan,1.3
17,2023-01-18,1039,125,4,75.78,0.00,303.1200,6,South,Credit Card,False,6,22,Male,Books,2.1,Not Returned,Neutral,NaN,nan,5.0
18,2023-01-19,1481,105,9,94.48,0.26,629.2368,1,South,Cash,True,4,68,Male,Electronics,1.2,Returned,Neutral,11.51,WELCOME5,4.4
19,2023-01-20,1286,108,8,94.98,0.15,645.8640,8,South,Cash,True,1,43,Female,Food,2.6,Not Returned,Negative,18.25,nan,1.2
20,2023-01-21,1083,173,8,70.44,0.22,439.5456,6,North,Cash,True,5,20,Male,Electronics,1.4,Not Returned,Neutral,7.40,nan,3.0
21,2023-01-22,1056,195,6,43.13,0.08,238.0776,6,North,Credit Card,False,5,25,Female,Food,4.0,Not Returned,Positive,17.44,WELCOME5,3.6
22,2023-01-23,1163,118,4,29.50,0.20,94.4000,4,East,Online,False,1,52,Male,Food,4.5,Not Returned,Positive,11.71,SAVE10,1.0
23,2023-01-24,1415,168,2,94.16,0.27,137.4736,6,West,Online,False,3,52,Other,Electronics,4.1,Returned,Positive,11.85,SAVE10,2.6
24,2023-01-25,1720,192,7,80.46,0.04,540.6912,4,North,Online,True,6,44,Female,Food,3.4,Returned,Positive,9.65,FREESHIP,3.7
25,2023-01-26,1065,128,2,67.86,0.16,114.0048,7,East,Online,False,5,51,Other,Clothing,3.0,Returned,Positive,NaN,FREESHIP,4.6
26,2023-01-27,1346,169,6,17.87,0.01,106.1478,6,West,Online,False,2,36,Other,Food,3.9,Not Returned,Negative,5.39,WELCOME5,3.1
27,2023-01-28,1355,105,7,51.00,0.21,282.0300,6,East,Cash,True,5,18,Male,Books,3.9,Not Returned,Negative,16.75,SAVE10,4.6
28,2023-01-29,1411,129,4,78.82,0.11,280.5992,4,West,Credit Card,True,5,44,Other,Clothing,2.4,Not Returned,Negative,13.43,WELCOME5,4.7
29,2023-01-30,1215,165,1,27.44,0.28,19.7568,7,East,Cash,True,6,24,Other,Clothing,2.8,Returned,Positive,15.77,SAVE10,4.2
30,2023-01-31,1843,123,5,84.94,0.17,352.5010,6,North,Credit Card,True,1,51,Female,Clothing,1.6,Not Returned,Negative,10.18,nan,NaN
31,2023-02-01,1424,126,2,38.01,0.20,60.8160,2,South,Online,True,3,56,Other,Food,4.9,Returned,Negative,6.10,SAVE10,4.9
32,2023-02-02,1754,130,2,50.81,0.28,73.1664,2,West,Cash,True,3,30,Male,Clothing,2.5,Returned,Positive,19.21,nan,NaN
33,2023-02-03,1487,177,4,30.09,0.22,93.8808,1,North,Credit Card,False,1,27,Other,Clothing,3.3,Not Returned,Neutral,NaN,FREESHIP,3.8
34,2023-02-04,1911,198,8,95.31,0.22,594.7344,1,North,Credit Card,False,5,34,Other,Food,4.0,Not Returned,Positive,NaN,nan,1.9
35,2023-01-27,1346,169,6,17.87,0.01,106.1478,6,West,Online,False,2,36,Other,Food,3.9,Not Returned,Negative,5.39,WELCOME5,3.1
36,2023-01-14,1700,176,6,91.55,0.07,510.8490,3,West,Credit Card,False,4,69,Male,Electronics,1.4,Returned,Neutral,18.57,nan,2.9
37,2023-01-25,1720,192,7,80.46,0.04,540.6912,4,North,Online,True,6,44,Female,Food,3.4,Returned,Positive,9.65,FREESHIP,3.7
38,2023-02-05,1500,150,2,-20.00,0.10,0.0000,5,North,Credit Card,True,3,25,Male,Electronics,4.5,Not Returned,Positive,NaN,NaN,NaN
39,2023-02-06,1501,151,3,-15.00,0.20,0.0000,6,South,Cash,False,4,34,Female,Clothing,3.0,Returned,Neutral,NaN,NaN,NaN
40,2023-02-07,1502,152,1,-30.00,0.15,0.0000,7,East,Online,True,2,45,Other,Books,5.0,Not Returned,Negative,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 06:**
</div>

In [13]:
# 6. Validating Data Based on Custom Conditions
# Write a Pandas program to validate data based on custom conditions.

# Check if 'price' is greater than 0
valid_price = df['price'] > 0
if valid_price.all():
    print("All prices are valid.")
else:
    print("Some prices are invalid:")
    display(df[~valid_price])

Some prices are invalid:

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
38,2023-02-05,1500,150,2,-20.0,0.10,0.0,5,North,Credit Card,True,3,25,Male,Electronics,4.5,Not Returned,Positive,NaN,NaN,NaN
39,2023-02-06,1501,151,3,-15.0,0.20,0.0,6,South,Cash,False,4,34,Female,Clothing,3.0,Returned,Neutral,NaN,NaN,NaN
40,2023-02-07,1502,152,1,-30.0,0.15,0.0,7,East,Online,True,2,45,Other,Books,5.0,Not Returned,Negative,NaN,NaN,NaN

<div class="alert alert-warning">

**7. Checking That a Specific Column Contains Only Unique Values**

**Write a Pandas program to check that a specific column contains only unique values.**

</div>

In [14]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Add 3 duplicate rows
df = pd.concat([df, df.sample(n=3, random_state=42)], ignore_index=True)

# Add 3 more rows with negative price
df = pd.concat([df, pd.DataFrame({
    'date': pd.date_range(start='2023-02-05', periods=3, freq='D'),
    'customer_id': [1500, 1501, 1502],
    'product_id': [150, 151, 152],
    'quantity': [2, 3, 1],
    'price': [-20.00, -15.00, -30.00],  # Negative prices
    'discount': [0.1, 0.2, 0.15],
    'revenue': [0, 0, 0],  # Placeholder; will be recalculated
    'store_id': [5, 6, 7],
    'region': ['North', 'South', 'East'],
    'payment_method': ['Credit Card', 'Cash', 'Online'],
    'is_member': [True, False, True],
    'delivery_days': [3, 4, 2],
    'customer_age': [25, 34, 45],
    'gender': ['Male', 'Female', 'Other'],
    'product_category': ['Electronics', 'Clothing', 'Books'],
    'rating': [4.5, 3.0, 5.0],
    'return_status': ['Not Returned', 'Returned', 'Not Returned'],
    'feedback': ['Positive', 'Neutral', 'Negative'],
})], ignore_index=True)

# add column with unique value
df['unique_id'] = pd.Series(range(1, len(df) + 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,unique_id
0,2023-01-01,1066,199,1,30.60,0.25,22.9500,4,East,Cash,False,6,66,Male,Food,1.0,Not Returned,Positive,15.45,FREESHIP,NaN,1
1,2023-01-02,1160,106,9,61.10,0.20,439.9200,6,North,Cash,True,5,19,Female,Clothing,1.9,Returned,Neutral,10.89,SAVE10,2.5,2
2,2023-01-03,1853,136,5,99.43,0.17,412.6345,3,East,Online,False,4,48,Female,Electronics,3.3,Not Returned,Positive,NaN,FREESHIP,3.1,3
3,2023-01-04,1458,187,3,74.92,0.26,166.3224,6,North,Credit Card,False,6,67,Female,Clothing,1.3,Not Returned,Positive,17.36,nan,1.2,4
4,2023-01-05,1668,107,8,26.32,0.30,147.3920,4,North,Cash,False,2,20,Other,Food,2.7,Returned,Negative,NaN,FREESHIP,3.8,5
5,2023-01-06,1417,144,4,40.21,0.11,143.1476,7,East,Credit Card,False,3,65,Male,Food,1.1,Returned,Negative,12.25,nan,1.1,6
6,2023-01-07,1971,129,9,86.45,0.10,700.2450,6,South,Cash,True,4,49,Other,Electronics,4.2,Returned,Positive,10.71,nan,3.6,7
7,2023-01-08,1846,153,1,50.04,0.19,40.5324,1,East,Online,True,1,56,Male,Books,1.1,Not Returned,Neutral,14.95,FREESHIP,2.9,8
8,2023-01-09,1676,164,3,80.92,0.01,240.3324,3,East,Online,True,6,37,Other,Books,1.9,Returned,Neutral,NaN,SAVE10,NaN,9
9,2023-01-10,1391,154,8,48.46,0.27,283.0064,5,West,Online,False,5,46,Male,Books,4.5,Returned,Neutral,NaN,FREESHIP,3.8,10
10,2023-01-11,1927,173,3,80.51,0.13,210.1311,5,West,Online,True,4,39,Male,Books,4.1,Returned,Neutral,7.74,FREESHIP,2.6,11
11,2023-01-12,1877,171,3,54.54,0.12,143.9856,9,East,Credit Card,True,4,41,Other,Clothing,2.0,Returned,Negative,7.56,nan,3.2,12
12,2023-01-13,1667,184,4,43.91,0.22,136.9992,8,North,Cash,True,1,30,Male,Clothing,2.9,Not Returned,Neutral,14.33,FREESHIP,1.8,13
13,2023-01-14,1874,162,8,94.12,0.18,617.4272,8,North,Cash,False,1,55,Other,Electronics,2.5,Returned,Positive,9.38,FREESHIP,4.3,14
14,2023-01-15,1560,166,6,41.77,0.23,192.9774,1,South,Credit Card,True,3,37,Male,Books,2.6,Returned,Positive,5.29,FREESHIP,NaN,15
15,2023-01-16,1366,115,4,10.77,0.20,34.4640,2,North,Online,True,4,23,Male,Books,4.5,Not Returned,Negative,5.22,FREESHIP,4.1,16
16,2023-01-17,1212,134,6,38.34,0.06,216.2376,9,South,Cash,True,2,66,Other,Clothing,2.9,Returned,Positive,17.59,nan,2.1,17
17,2023-01-18,1982,147,9,48.65,0.10,394.0650,5,South,Credit Card,False,4,45,Female,Electronics,3.0,Returned,Positive,11.44,WELCOME5,NaN,18
18,2023-01-19,1357,184,8,94.79,0.11,674.9048,6,East,Online,False,6,33,Female,Electronics,1.1,Returned,Positive,NaN,nan,NaN,19
19,2023-01-20,1361,169,5,65.74,0.08,302.4040,4,East,Online,False,4,42,Male,Electronics,1.2,Returned,Neutral,11.36,nan,1.4,20
20,2023-01-21,1889,186,8,52.13,0.07,387.8472,3,East,Online,True,2,28,Other,Electronics,1.8,Returned,Positive,9.83,SAVE10,1.1,21
21,2023-01-22,1562,148,3,25.68,0.20,61.6320,9,West,Online,True,4,51,Female,Food,4.4,Not Returned,Positive,5.28,WELCOME5,3.5,22
22,2023-01-23,1386,188,6,79.16,0.17,394.2168,4,East,Cash,True,1,58,Male,Books,3.1,Returned,Negative,6.72,FREESHIP,2.2,23
23,2023-01-24,1989,161,5,35.52,0.18,145.6320,1,East,Cash,False,5,29,Male,Food,1.6,Not Returned,Positive,17.74,nan,NaN,24
24,2023-01-25,1711,142,7,70.73,0.29,351.5281,1,West,Online,True,2,31,Male,Books,2.0,Returned,Negative,NaN,nan,3.5,25
25,2023-01-26,1747,108,8,71.34,0.07,530.7696,1,North,Credit Card,True,1,57,Female,Food,4.3,Returned,Positive,8.87,nan,NaN,26
26,2023-01-27,1211,175,5,11.07,0.12,48.7080,4,North,Credit Card,True,3,27,Female,Clothing,1.9,Not Returned,Negative,13.73,nan,2.6,27
27,2023-01-28,1617,159,6,11.92,0.16,60.0768,4,West,Online,True,4,53,Other,Electronics,4.7,Not Returned,Negative,NaN,WELCOME5,3.4,28
28,2023-01-29,1878,113,6,91.19,0.18,448.6548,6,West,Online,False,1,25,Other,Clothing,1.1,Not Returned,Negative,8.67,nan,3.8,29
29,2023-01-30,1034,126,4,40.73,0.08,149.8864,2,West,Credit Card,False,1,63,Female,Books,1.3,Returned,Negative,NaN,FREESHIP,1.6,30
30,2023-01-31,1522,146,8,96.53,0.14,664.1264,4,West,Online,False,1,34,Other,Books,2.8,Not Returned,Neutral,10.82,SAVE10,2.1,31
31,2023-02-01,1258,151,5,67.05,0.27,244.7325,9,East,Online,False,5,65,Female,Electronics,4.8,Not Returned,Negative,7.81,nan,NaN,32
32,2023-02-02,1438,110,3,67.30,0.12,177.6720,2,East,Online,False,2,27,Other,Books,1.3,Returned,Negative,15.05,WELCOME5,3.6,33
33,2023-02-03,1345,138,5,51.54,0.17,213.8910,7,North,Credit Card,True,1,44,Male,Electronics,2.9,Returned,Negative,7.02,FREESHIP,NaN,34
34,2023-02-04,1941,165,9,30.06,0.30,189.3780,1,North,Credit Card,True,6,33,Other,Food,1.0,Not Returned,Neutral,12.10,nan,NaN,35
35,2023-01-27,1211,175,5,11.07,0.12,48.7080,4,North,Credit Card,True,3,27,Female,Clothing,1.9,Not Returned,Negative,13.73,nan,2.6,36
36,2023-01-14,1874,162,8,94.12,0.18,617.4272,8,North,Cash,False,1,55,Other,Electronics,2.5,Returned,Positive,9.38,FREESHIP,4.3,37
37,2023-01-25,1711,142,7,70.73,0.29,351.5281,1,West,Online,True,2,31,Male,Books,2.0,Returned,Negative,NaN,nan,3.5,38
38,2023-02-05,1500,150,2,-20.00,0.10,0.0000,5,North,Credit Card,True,3,25,Male,Electronics,4.5,Not Returned,Positive,NaN,NaN,NaN,39
39,2023-02-06,1501,151,3,-15.00,0.20,0.0000,6,South,Cash,False,4,34,Female,Clothing,3.0,Returned,Neutral,NaN,NaN,NaN,40
40,2023-02-07,1502,152,1,-30.00,0.15,0.0000,7,East,Online,True,2,45,Other,Books,5.0,Not Returned,Negative,NaN,NaN,NaN,41

<div class="alert alert-success">

**Solution 07:**
</div>

In [15]:
pd.Series.is_unique?

Type:        property
String form: <property object at 0x12465c6d0>
Docstring:
Return boolean if values in the object are unique.

Returns
-------
bool

Examples
--------
>>> s = pd.Series([1, 2, 3])
>>> s.is_unique
True

>>> s = pd.Series([1, 2, 3, 1])
>>> s.is_unique
False

In [16]:
# 7. Checking That a Specific Column Contains Only Unique Values
# Write a Pandas program to check that a specific column contains only unique values.


def is_unique(column_name, dataframe):
    if dataframe[column_name].is_unique:
        print("The column {:<20} contains only unique values.".format(column_name))
    else:
        print("The column {:<20} has more than one unique value - has duplicates.".format(column_name))

for col in df.columns:
    is_unique(col, df)

The column date                 has more than one unique value - has duplicates.
The column customer_id          has more than one unique value - has duplicates.
The column product_id           has more than one unique value - has duplicates.
The column quantity             has more than one unique value - has duplicates.
The column price                has more than one unique value - has duplicates.
The column discount             has more than one unique value - has duplicates.
The column revenue              has more than one unique value - has duplicates.
The column store_id             has more than one unique value - has duplicates.
The column region               has more than one unique value - has duplicates.
The column payment_method       has more than one unique value - has duplicates.
The column is_member            has more than one unique value - has duplicates.
The column delivery_days        has more than one unique value - has duplicates.
The column customer_age         has more than one unique value - has duplicates.
The column gender               has more than one unique value - has duplicates.
The column product_category     has more than one unique value - has duplicates.
The column rating               has more than one unique value - has duplicates.
The column return_status        has more than one unique value - has duplicates.
The column feedback             has more than one unique value - has duplicates.
The column shipping_cost        has more than one unique value - has duplicates.
The column coupon_code          has more than one unique value - has duplicates.
The column delivery_rating      has more than one unique value - has duplicates.
The column unique_id            contains only unique values.

<div class="alert alert-warning">

**8. Detecting Outliers in a DataFrame**

**Write a Pandas program to detect outliers in a DataFrame.**

</div>

In [17]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Add 3 duplicate rows
df = pd.concat([df, df.sample(n=3, random_state=42)], ignore_index=True)

# Add 3 more rows with negative price
df = pd.concat([df, pd.DataFrame({
    'date': pd.date_range(start='2023-02-05', periods=3, freq='D'),
    'customer_id': [1500, 1501, 1502],
    'product_id': [150, 151, 152],
    'quantity': [2, 3, 1],
    'price': [-20.00, -15.00, -30.00],  # Negative prices
    'discount': [0.1, 0.2, 0.15],
    'revenue': [0, 0, 0],  # Placeholder; will be recalculated
    'store_id': [5, 6, 7],
    'region': ['North', 'South', 'East'],
    'payment_method': ['Credit Card', 'Cash', 'Online'],
    'is_member': [True, False, True],
    'delivery_days': [3, 4, 2],
    'customer_age': [25, 34, 45],
    'gender': ['Male', 'Female', 'Other'],
    'product_category': ['Electronics', 'Clothing', 'Books'],
    'rating': [4.5, 3.0, 5.0],
    'return_status': ['Not Returned', 'Returned', 'Not Returned'],
    'feedback': ['Positive', 'Neutral', 'Negative'],
})], ignore_index=True)

# add column with unique value
df['unique_id'] = pd.Series(range(1, len(df) + 1))

# add outliers
df.loc[[0,3,5], ['price']] = [9999.99, 8888.88, 7777.77]

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,unique_id
0,2023-01-01,1458,149,9,9999.99,0.24,90.2196,7,West,Credit Card,True,4,59,Other,Clothing,2.4,Returned,Neutral,16.83,WELCOME5,1.0,1
1,2023-01-02,1682,179,5,68.11,0.21,269.0345,5,South,Credit Card,False,6,49,Other,Electronics,4.0,Returned,Neutral,16.24,nan,4.3,2
2,2023-01-03,1865,105,8,60.15,0.28,346.4640,5,West,Online,False,6,46,Female,Books,1.2,Not Returned,Negative,NaN,nan,4.6,3
3,2023-01-04,1711,154,4,8888.88,0.04,150.7200,1,North,Credit Card,False,5,52,Male,Clothing,2.8,Not Returned,Neutral,11.88,SAVE10,3.5,4
4,2023-01-05,1975,183,4,77.01,0.09,280.3164,2,West,Online,False,1,22,Male,Electronics,4.6,Not Returned,Positive,18.45,WELCOME5,NaN,5
5,2023-01-06,1867,171,2,7777.77,0.10,138.8340,9,South,Cash,True,4,26,Other,Food,4.2,Returned,Positive,10.79,nan,NaN,6
6,2023-01-07,1080,123,2,21.48,0.29,30.5016,1,East,Credit Card,False,6,66,Male,Food,4.4,Returned,Negative,19.86,SAVE10,NaN,7
7,2023-01-08,1675,196,1,45.33,0.27,33.0909,7,East,Online,False,1,54,Other,Food,1.3,Returned,Positive,7.21,FREESHIP,NaN,8
8,2023-01-09,1618,159,7,45.32,0.01,314.0676,6,South,Cash,False,5,35,Other,Books,3.8,Not Returned,Negative,12.71,FREESHIP,NaN,9
9,2023-01-10,1091,138,9,12.84,0.26,85.5144,1,West,Credit Card,False,1,65,Male,Electronics,2.9,Not Returned,Positive,NaN,WELCOME5,3.9,10
10,2023-01-11,1063,175,6,58.12,0.11,310.3608,9,South,Credit Card,True,4,36,Female,Clothing,3.6,Not Returned,Positive,9.41,SAVE10,2.6,11
11,2023-01-12,1050,159,1,66.66,0.21,52.6614,5,East,Cash,False,2,49,Female,Electronics,4.6,Returned,Negative,13.84,WELCOME5,1.5,12
12,2023-01-13,1679,186,8,79.13,0.13,550.7448,4,North,Credit Card,True,6,42,Other,Food,3.9,Not Returned,Positive,6.55,WELCOME5,4.8,13
13,2023-01-14,1052,176,4,56.95,0.29,161.7380,9,South,Credit Card,True,6,35,Male,Electronics,2.1,Returned,Neutral,NaN,nan,NaN,14
14,2023-01-15,1460,106,6,60.06,0.05,342.3420,3,West,Cash,False,5,19,Female,Food,3.3,Returned,Neutral,17.28,nan,2.4,15
15,2023-01-16,1290,189,3,45.49,0.10,122.8230,1,East,Credit Card,False,1,19,Female,Electronics,3.8,Not Returned,Neutral,11.50,FREESHIP,2.8,16
16,2023-01-17,1074,197,8,70.18,0.02,550.2112,9,North,Cash,False,2,19,Female,Clothing,2.1,Not Returned,Neutral,7.00,nan,NaN,17
17,2023-01-18,1896,174,4,54.98,0.28,158.3424,2,South,Cash,False,2,62,Female,Clothing,4.2,Not Returned,Neutral,NaN,FREESHIP,1.8,18
18,2023-01-19,1141,195,5,11.78,0.30,41.2300,7,West,Cash,True,1,30,Other,Books,2.8,Not Returned,Positive,NaN,nan,4.1,19
19,2023-01-20,1090,172,5,41.56,0.20,166.2400,7,North,Online,False,4,48,Other,Books,3.2,Not Returned,Neutral,17.35,nan,NaN,20
20,2023-01-21,1294,130,8,94.91,0.13,660.5736,1,West,Credit Card,True,3,34,Male,Electronics,3.7,Not Returned,Positive,5.55,WELCOME5,3.0,21
21,2023-01-22,1287,191,5,44.92,0.25,168.4500,1,West,Online,False,4,64,Male,Books,4.8,Not Returned,Negative,NaN,nan,2.7,22
22,2023-01-23,1781,151,6,83.90,0.28,362.4480,1,East,Online,False,6,68,Male,Electronics,2.8,Not Returned,Positive,5.53,SAVE10,4.7,23
23,2023-01-24,1092,139,4,83.46,0.25,250.3800,9,East,Cash,False,4,40,Other,Electronics,1.7,Returned,Neutral,14.63,FREESHIP,NaN,24
24,2023-01-25,1130,119,6,91.84,0.01,545.5296,7,North,Cash,False,6,30,Other,Books,1.8,Not Returned,Positive,8.83,FREESHIP,3.3,25
25,2023-01-26,1647,193,8,11.10,0.07,82.5840,3,West,Online,True,4,47,Male,Books,5.0,Not Returned,Negative,16.68,nan,NaN,26
26,2023-01-27,1120,140,5,61.41,0.22,239.4990,6,East,Cash,False,6,21,Other,Food,1.9,Returned,Positive,15.16,SAVE10,2.4,27
27,2023-01-28,1933,106,8,62.10,0.09,452.0880,3,East,Cash,False,4,38,Female,Food,3.8,Returned,Negative,8.16,WELCOME5,4.1,28
28,2023-01-29,1234,118,2,10.65,0.10,19.1700,9,North,Cash,False,3,65,Male,Food,2.3,Not Returned,Neutral,9.47,nan,3.2,29
29,2023-01-30,1195,160,2,35.29,0.21,55.7582,5,South,Credit Card,False,5,52,Other,Clothing,3.7,Returned,Negative,9.84,FREESHIP,NaN,30
30,2023-01-31,1389,123,9,23.88,0.27,156.8916,5,West,Credit Card,True,4,26,Male,Clothing,4.4,Not Returned,Neutral,14.52,SAVE10,NaN,31
31,2023-02-01,1369,142,1,28.01,0.13,24.3687,5,South,Cash,True,1,52,Other,Food,4.3,Returned,Negative,15.31,SAVE10,NaN,32
32,2023-02-02,1854,175,6,45.75,0.20,219.6000,2,East,Cash,True,5,41,Other,Electronics,1.4,Not Returned,Negative,5.16,nan,NaN,33
33,2023-02-03,1218,195,5,27.97,0.00,139.8500,3,West,Credit Card,False,1,65,Male,Food,1.8,Returned,Neutral,12.54,SAVE10,4.0,34
34,2023-02-04,1898,140,7,24.81,0.01,171.9333,7,East,Credit Card,True,5,27,Other,Clothing,1.8,Not Returned,Neutral,15.35,nan,4.0,35
35,2023-01-27,1120,140,5,61.41,0.22,239.4990,6,East,Cash,False,6,21,Other,Food,1.9,Returned,Positive,15.16,SAVE10,2.4,36
36,2023-01-14,1052,176,4,56.95,0.29,161.7380,9,South,Credit Card,True,6,35,Male,Electronics,2.1,Returned,Neutral,NaN,nan,NaN,37
37,2023-01-25,1130,119,6,91.84,0.01,545.5296,7,North,Cash,False,6,30,Other,Books,1.8,Not Returned,Positive,8.83,FREESHIP,3.3,38
38,2023-02-05,1500,150,2,-20.00,0.10,0.0000,5,North,Credit Card,True,3,25,Male,Electronics,4.5,Not Returned,Positive,NaN,NaN,NaN,39
39,2023-02-06,1501,151,3,-15.00,0.20,0.0000,6,South,Cash,False,4,34,Female,Clothing,3.0,Returned,Neutral,NaN,NaN,NaN,40
40,2023-02-07,1502,152,1,-30.00,0.15,0.0000,7,East,Online,True,2,45,Other,Books,5.0,Not Returned,Negative,NaN,NaN,NaN,41

<div class="alert alert-success">

**Solution 08:**
</div>

In [18]:
# 8. Detecting Outliers in a DataFrame
# Write a Pandas program to detect outliers in a DataFrame.

def detect_outliers(column_name, dataframe):
    if dataframe[column_name].dtype not in [np.float64, np.int64]:
        print("Column {:>30} is not numeric and will be skipped.".format(column_name))
        return
    else:
        Q1 = dataframe[column_name].quantile(0.25)
        Q3 = dataframe[column_name].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        outliers = dataframe[(dataframe[column_name] < lower_bound) | (dataframe[column_name] > upper_bound)]
    if not outliers.empty:
        print("Column {:>30} OUTLIERS DETECTED.\n####### OUTLIERS #######".format(column_name))
        display(outliers)
    else:
        print("Column {:>30} has no outliers detected.".format(column_name))

for col in df.columns:
    detect_outliers(col, df)

Column                           date is not numeric and will be skipped.
Column                    customer_id has no outliers detected.
Column                     product_id has no outliers detected.
Column                       quantity has no outliers detected.
Column                          price OUTLIERS DETECTED.
####### OUTLIERS #######

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,unique_id
0,2023-01-01,1458,149,9,9999.99,0.24,90.2196,7,West,Credit Card,True,4,59,Other,Clothing,2.4,Returned,Neutral,16.83,WELCOME5,1.0,1
3,2023-01-04,1711,154,4,8888.88,0.04,150.7200,1,North,Credit Card,False,5,52,Male,Clothing,2.8,Not Returned,Neutral,11.88,SAVE10,3.5,4
5,2023-01-06,1867,171,2,7777.77,0.10,138.8340,9,South,Cash,True,4,26,Other,Food,4.2,Returned,Positive,10.79,nan,NaN,6

Column                       discount has no outliers detected.
Column                        revenue OUTLIERS DETECTED.
####### OUTLIERS #######

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,unique_id
20,2023-01-21,1294,130,8,94.91,0.13,660.5736,1,West,Credit Card,True,3,34,Male,Electronics,3.7,Not Returned,Positive,5.55,WELCOME5,3.0,21

Column                       store_id has no outliers detected.
Column                         region is not numeric and will be skipped.
Column                 payment_method is not numeric and will be skipped.
Column                      is_member is not numeric and will be skipped.
Column                  delivery_days has no outliers detected.
Column                   customer_age has no outliers detected.
Column                         gender is not numeric and will be skipped.
Column               product_category is not numeric and will be skipped.
Column                         rating has no outliers detected.
Column                  return_status is not numeric and will be skipped.
Column                       feedback is not numeric and will be skipped.
Column                  shipping_cost has no outliers detected.
Column                    coupon_code is not numeric and will be skipped.
Column                delivery_rating has no outliers detected.
Column                      unique_id has no outliers detected.