[Pandas Data Validation](https://www.w3resource.com/python-exercises/pandas/pandas-data-validation.php)

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

<div class="alert alert-warning">

**1. Checking Missing Values in a DataFrame**

**Write a Pandas program to check for missing values in a DataFrame.**

</div>

In [2]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1672,150,2,20.95,0.23,32.2630,6,North,Credit Card,False,1,22,Other,Electronics,2.8,Not Returned,Negative,NaN,nan,NaN
1,2023-01-02,1852,100,9,20.23,0.13,158.4009,2,East,Cash,False,1,56,Other,Food,3.2,Returned,Positive,17.02,FREESHIP,3.4
2,2023-01-03,1480,141,8,88.70,0.11,631.5440,1,South,Credit Card,True,5,43,Female,Books,3.1,Not Returned,Negative,7.14,nan,2.5
3,2023-01-04,1167,179,5,70.86,0.16,297.6120,9,North,Cash,True,2,65,Male,Books,1.5,Returned,Neutral,10.93,WELCOME5,1.5
4,2023-01-05,1654,198,2,34.17,0.16,57.4056,8,East,Cash,True,3,54,Other,Books,5.0,Returned,Neutral,NaN,SAVE10,NaN
5,2023-01-06,1667,199,4,51.38,0.22,160.3056,6,South,Cash,True,6,49,Other,Books,3.7,Returned,Positive,NaN,nan,NaN
6,2023-01-07,1460,160,2,20.39,0.17,33.8474,3,North,Cash,True,1,32,Male,Electronics,1.2,Returned,Positive,6.42,FREESHIP,NaN
7,2023-01-08,1623,139,5,53.02,0.19,214.7310,6,East,Online,True,1,35,Other,Books,2.3,Returned,Positive,5.29,nan,4.9
8,2023-01-09,1661,147,3,35.32,0.26,78.4104,6,South,Credit Card,True,6,63,Female,Books,4.3,Not Returned,Neutral,NaN,WELCOME5,2.6
9,2023-01-10,1617,167,9,68.99,0.22,484.3098,3,North,Cash,True,1,55,Other,Food,1.1,Not Returned,Negative,13.60,SAVE10,NaN
10,2023-01-11,1629,131,4,94.67,0.29,268.8628,9,North,Cash,False,2,49,Other,Books,3.1,Returned,Positive,14.19,SAVE10,NaN
11,2023-01-12,1702,192,6,19.78,0.27,86.6364,6,West,Online,False,6,36,Male,Electronics,3.0,Not Returned,Negative,7.03,SAVE10,2.7
12,2023-01-13,1885,102,6,79.48,0.26,352.8912,6,North,Credit Card,True,2,19,Male,Books,4.3,Returned,Negative,11.97,nan,1.2
13,2023-01-14,1937,161,1,61.95,0.26,45.8430,6,West,Credit Card,False,4,44,Female,Clothing,3.4,Not Returned,Positive,7.17,nan,3.4
14,2023-01-15,1726,150,5,77.61,0.25,291.0375,7,West,Credit Card,False,1,68,Male,Food,2.5,Returned,Neutral,NaN,FREESHIP,1.7
15,2023-01-16,1719,146,1,49.59,0.17,41.1597,8,East,Credit Card,False,2,24,Other,Books,4.1,Returned,Negative,7.84,nan,3.4
16,2023-01-17,1169,189,2,67.28,0.23,103.6112,6,West,Cash,True,2,21,Other,Food,1.3,Returned,Negative,NaN,FREESHIP,NaN
17,2023-01-18,1154,115,3,57.78,0.25,130.0050,5,North,Credit Card,True,3,39,Other,Clothing,1.6,Not Returned,Positive,16.67,nan,1.4
18,2023-01-19,1668,160,4,63.01,0.15,214.2340,2,East,Cash,False,4,32,Other,Clothing,1.1,Returned,Positive,12.92,WELCOME5,1.4
19,2023-01-20,1618,111,8,41.60,0.13,289.5360,4,South,Online,True,1,62,Female,Food,4.0,Not Returned,Negative,9.20,WELCOME5,2.6
20,2023-01-21,1752,106,5,89.96,0.06,422.8120,4,East,Credit Card,False,1,64,Male,Books,1.9,Returned,Negative,17.67,nan,3.6
21,2023-01-22,1890,116,4,69.37,0.30,194.2360,8,South,Online,True,5,41,Male,Clothing,3.1,Returned,Negative,NaN,nan,3.2
22,2023-01-23,1826,109,2,28.29,0.05,53.7510,7,South,Credit Card,True,2,57,Female,Electronics,2.8,Returned,Negative,16.01,FREESHIP,3.0
23,2023-01-24,1049,170,7,57.25,0.24,304.5700,8,West,Credit Card,False,2,69,Male,Books,1.8,Not Returned,Neutral,5.76,SAVE10,1.4
24,2023-01-25,1497,185,3,24.09,0.18,59.2614,9,West,Cash,True,5,64,Female,Electronics,3.3,Returned,Negative,15.63,SAVE10,NaN
25,2023-01-26,1552,153,7,97.60,0.18,560.2240,8,East,Online,True,6,26,Male,Clothing,2.4,Returned,Negative,11.60,nan,NaN
26,2023-01-27,1632,165,9,54.33,0.20,391.1760,5,West,Cash,False,3,19,Male,Clothing,3.7,Returned,Negative,10.22,SAVE10,3.2
27,2023-01-28,1654,131,9,81.93,0.13,641.5119,3,North,Online,True,3,19,Male,Clothing,3.6,Not Returned,Positive,NaN,FREESHIP,NaN
28,2023-01-29,1563,100,8,80.09,0.19,518.9832,8,East,Cash,True,6,34,Other,Electronics,3.7,Not Returned,Neutral,8.75,nan,4.5
29,2023-01-30,1699,114,3,85.95,0.27,188.2305,7,East,Credit Card,True,6,19,Male,Books,2.9,Returned,Positive,19.99,WELCOME5,1.5
30,2023-01-31,1541,189,7,61.10,0.24,325.0520,9,North,Credit Card,True,1,68,Female,Books,3.0,Not Returned,Neutral,15.55,SAVE10,4.6
31,2023-02-01,1769,172,8,99.27,0.21,627.3864,1,West,Online,False,5,65,Other,Books,3.1,Not Returned,Neutral,14.03,SAVE10,4.0
32,2023-02-02,1273,171,8,60.12,0.23,370.3392,7,North,Online,False,6,37,Other,Electronics,2.3,Returned,Positive,15.23,nan,NaN
33,2023-02-03,1082,176,2,34.34,0.06,64.5592,7,North,Cash,False,2,69,Female,Electronics,4.5,Returned,Neutral,NaN,FREESHIP,NaN
34,2023-02-04,1923,140,4,80.15,0.25,240.4500,1,North,Credit Card,False,1,28,Male,Electronics,4.0,Returned,Negative,NaN,FREESHIP,2.8

<div class="alert alert-success">

**Solution 01:**
</div>

In [3]:
# 1. Checking Missing Values in a DataFrame
# Write a Pandas program to check for missing values in a DataFrame.

# Check for missing values
missing_values = df.isnull().sum()
missing_values[missing_values > 0]

shipping_cost      10
delivery_rating    12
dtype: int64

<div class="alert alert-warning">

**2. Ensuring Consistent Data Types of All Columns**

**Write a Pandas program to check and ensure that the data types of all columns are consistent.**

</div>

In [4]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1937,110,6,58.92,0.24,268.6752,4,South,Online,False,3,41,Female,Clothing,2.6,Returned,Neutral,5.92,FREESHIP,4.1
1,2023-01-02,1998,159,9,85.09,0.13,666.2547,5,South,Credit Card,False,1,34,Female,Food,3.1,Not Returned,Neutral,8.50,WELCOME5,2.0
2,2023-01-03,1375,120,4,56.37,0.26,166.8552,5,South,Online,True,4,41,Other,Electronics,3.2,Returned,Positive,13.82,nan,NaN
3,2023-01-04,1883,159,9,17.85,0.24,122.0940,2,North,Cash,False,5,55,Male,Books,1.5,Not Returned,Negative,NaN,FREESHIP,NaN
4,2023-01-05,1707,103,1,62.62,0.16,52.6008,8,West,Credit Card,False,3,58,Other,Food,2.9,Returned,Neutral,16.75,nan,NaN
5,2023-01-06,1125,155,2,17.24,0.10,31.0320,3,West,Credit Card,False,4,64,Female,Food,3.5,Returned,Negative,13.47,nan,NaN
6,2023-01-07,1779,128,6,45.94,0.27,201.2172,6,West,Cash,False,4,43,Female,Clothing,2.5,Returned,Negative,15.79,SAVE10,NaN
7,2023-01-08,1050,119,5,41.83,0.21,165.2285,1,East,Credit Card,False,6,35,Other,Clothing,3.8,Not Returned,Negative,12.99,SAVE10,5.0
8,2023-01-09,1380,154,7,67.33,0.24,358.1956,9,East,Cash,False,3,40,Female,Electronics,3.2,Returned,Negative,9.10,nan,3.1
9,2023-01-10,1817,134,8,39.57,0.14,272.2416,3,West,Online,False,4,57,Female,Electronics,4.0,Returned,Negative,NaN,FREESHIP,NaN
10,2023-01-11,1373,145,2,12.98,0.12,22.8448,4,South,Online,True,1,48,Other,Electronics,4.1,Not Returned,Neutral,16.57,nan,2.8
11,2023-01-12,1376,198,7,72.51,0.22,395.9046,1,East,Cash,True,2,47,Other,Clothing,3.2,Returned,Negative,14.02,nan,4.6
12,2023-01-13,1352,183,7,54.45,0.01,377.3385,1,East,Credit Card,False,2,38,Female,Clothing,3.4,Returned,Negative,NaN,SAVE10,NaN
13,2023-01-14,1189,160,7,58.65,0.00,410.5500,8,South,Cash,True,2,30,Male,Electronics,3.3,Returned,Neutral,13.62,nan,NaN
14,2023-01-15,1667,116,9,93.64,0.18,691.0632,6,North,Credit Card,False,1,59,Female,Electronics,4.5,Not Returned,Positive,16.76,FREESHIP,NaN
15,2023-01-16,1877,128,5,34.96,0.28,125.8560,1,East,Online,False,1,42,Male,Electronics,2.2,Not Returned,Negative,NaN,nan,3.9
16,2023-01-17,1748,129,4,73.79,0.15,250.8860,4,West,Credit Card,True,3,65,Male,Electronics,1.9,Not Returned,Negative,7.46,FREESHIP,NaN
17,2023-01-18,1941,128,6,71.94,0.19,349.6284,6,North,Cash,True,2,27,Other,Electronics,1.2,Not Returned,Neutral,11.78,nan,4.2
18,2023-01-19,1373,140,8,43.46,0.12,305.9584,5,East,Online,False,5,47,Other,Electronics,3.3,Not Returned,Neutral,8.13,nan,3.2
19,2023-01-20,1434,188,7,97.51,0.04,655.2672,5,South,Cash,True,5,48,Female,Food,2.1,Not Returned,Neutral,19.85,WELCOME5,1.7
20,2023-01-21,1926,189,6,72.66,0.29,309.5316,1,South,Online,True,4,25,Other,Clothing,1.8,Not Returned,Negative,9.78,SAVE10,1.5
21,2023-01-22,1566,157,5,50.57,0.24,192.1660,2,East,Cash,True,5,27,Male,Food,4.9,Not Returned,Neutral,9.48,nan,3.7
22,2023-01-23,1989,176,6,45.46,0.09,248.2116,9,East,Credit Card,True,6,44,Female,Food,2.2,Returned,Neutral,18.58,nan,4.3
23,2023-01-24,1496,161,8,51.49,0.28,296.5824,6,South,Cash,False,1,64,Other,Electronics,4.6,Not Returned,Positive,14.95,SAVE10,3.9
24,2023-01-25,1643,154,9,55.13,0.28,357.2424,6,West,Online,False,2,27,Female,Food,1.7,Returned,Negative,NaN,WELCOME5,4.8
25,2023-01-26,1558,113,6,93.60,0.15,477.3600,5,East,Cash,True,5,33,Male,Food,4.3,Not Returned,Positive,NaN,nan,NaN
26,2023-01-27,1279,189,6,16.80,0.16,84.6720,7,North,Credit Card,True,2,39,Male,Books,2.6,Returned,Neutral,15.29,FREESHIP,2.5
27,2023-01-28,1215,112,9,80.37,0.22,564.1974,5,North,Credit Card,True,5,57,Other,Clothing,2.5,Not Returned,Negative,19.10,FREESHIP,NaN
28,2023-01-29,1427,108,7,93.62,0.21,517.7186,5,South,Credit Card,True,2,60,Female,Clothing,3.9,Not Returned,Neutral,NaN,nan,NaN
29,2023-01-30,1332,126,4,92.61,0.16,311.1696,4,South,Online,False,4,65,Other,Food,3.8,Returned,Neutral,NaN,SAVE10,NaN
30,2023-01-31,1714,165,5,13.93,0.13,60.5955,7,North,Online,False,5,21,Male,Books,4.6,Not Returned,Neutral,8.68,nan,2.1
31,2023-02-01,1617,118,6,12.36,0.28,53.3952,7,South,Credit Card,False,3,42,Female,Food,4.2,Returned,Negative,14.81,nan,NaN
32,2023-02-02,1070,142,3,20.28,0.06,57.1896,1,North,Cash,True,4,49,Male,Electronics,2.1,Returned,Positive,NaN,WELCOME5,4.1
33,2023-02-03,1011,195,4,25.48,0.24,77.4592,2,South,Online,True,6,53,Other,Food,1.2,Returned,Neutral,10.72,WELCOME5,4.5
34,2023-02-04,1135,151,2,12.46,0.16,20.9328,6,East,Online,False,2,47,Male,Clothing,1.9,Not Returned,Neutral,NaN,nan,1.7

<div class="alert alert-success">

**Solution 02:**
</div>

In [5]:
# 2. Ensuring Consistent Data Types of All Columns
# Write a Pandas program to check and ensure that the data types of all columns are consistent.

# Check data types
data_types = df.dtypes
data_types

date                datetime64[ns]
customer_id                  int64
product_id                   int64
quantity                     int64
price                      float64
discount                   float64
revenue                    float64
store_id                     int64
region                      object
payment_method              object
is_member                     bool
delivery_days                int64
customer_age                 int64
gender                      object
product_category            object
rating                     float64
return_status               object
feedback                    object
shipping_cost              float64
coupon_code                 object
delivery_rating            float64
dtype: object

<div class="alert alert-warning">

**3. Validating the Data Type of a Specific Column**

**Write a Pandas program to validate the data type of a specific column in a DataFrame.**

</div>

In [6]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1440,197,6,87.42,0.04,503.5392,8,West,Cash,False,2,35,Other,Clothing,3.9,Not Returned,Negative,NaN,SAVE10,2.3
1,2023-01-02,1677,140,2,47.33,0.27,69.1018,7,East,Cash,True,5,52,Female,Electronics,4.8,Returned,Neutral,15.40,nan,NaN
2,2023-01-03,1704,150,7,85.58,0.20,479.2480,7,West,Credit Card,True,3,63,Female,Food,2.6,Not Returned,Negative,17.84,nan,2.9
3,2023-01-04,1546,120,5,49.04,0.11,218.2280,6,South,Credit Card,False,4,37,Female,Food,2.0,Not Returned,Positive,NaN,nan,1.3
4,2023-01-05,1270,128,5,14.04,0.23,54.0540,5,West,Cash,False,1,57,Other,Food,1.5,Returned,Positive,NaN,FREESHIP,3.9
5,2023-01-06,1806,187,9,22.47,0.22,157.7394,8,East,Cash,False,1,49,Male,Electronics,1.3,Not Returned,Positive,NaN,WELCOME5,NaN
6,2023-01-07,1527,102,9,67.47,0.18,497.9286,5,South,Online,False,1,44,Female,Clothing,3.3,Returned,Positive,19.53,nan,4.1
7,2023-01-08,1352,112,8,68.50,0.18,449.3600,1,East,Online,False,6,34,Male,Food,2.6,Not Returned,Neutral,18.21,FREESHIP,4.6
8,2023-01-09,1030,129,3,99.58,0.11,265.8786,4,East,Online,True,2,49,Female,Books,4.6,Returned,Positive,18.27,FREESHIP,NaN
9,2023-01-10,1565,171,2,50.64,0.22,78.9984,1,West,Credit Card,False,5,29,Male,Electronics,2.5,Not Returned,Positive,9.30,WELCOME5,NaN
10,2023-01-11,1402,149,1,71.43,0.12,62.8584,7,South,Credit Card,False,1,30,Male,Food,1.5,Not Returned,Negative,13.24,SAVE10,3.7
11,2023-01-12,1936,183,5,62.87,0.13,273.4845,4,South,Credit Card,False,5,65,Male,Clothing,3.0,Not Returned,Positive,7.57,FREESHIP,4.0
12,2023-01-13,1724,178,8,16.27,0.18,106.7312,7,West,Online,False,1,27,Female,Electronics,4.9,Not Returned,Negative,12.97,nan,NaN
13,2023-01-14,1918,149,7,49.00,0.02,336.1400,1,North,Cash,True,3,37,Male,Clothing,3.1,Returned,Neutral,11.91,nan,2.5
14,2023-01-15,1873,137,9,67.92,0.25,458.4600,5,West,Credit Card,False,3,24,Male,Food,1.7,Returned,Positive,18.55,FREESHIP,2.7
15,2023-01-16,1067,120,6,65.35,0.22,305.8380,1,South,Online,True,3,32,Other,Food,2.2,Returned,Negative,13.29,nan,1.1
16,2023-01-17,1440,174,6,59.83,0.29,254.8758,3,South,Online,True,5,48,Other,Food,1.0,Not Returned,Positive,NaN,WELCOME5,3.1
17,2023-01-18,1213,180,7,45.95,0.00,321.6500,1,West,Cash,False,6,52,Other,Electronics,3.3,Not Returned,Neutral,18.55,WELCOME5,4.5
18,2023-01-19,1284,164,2,51.83,0.30,72.5620,3,East,Cash,True,6,66,Male,Clothing,1.2,Not Returned,Positive,7.04,SAVE10,2.6
19,2023-01-20,1700,131,8,61.29,0.02,480.5136,2,West,Cash,False,5,53,Other,Food,1.9,Not Returned,Neutral,5.91,nan,3.8
20,2023-01-21,1392,182,6,55.84,0.18,274.7328,8,East,Cash,True,2,43,Female,Electronics,3.6,Returned,Positive,6.43,WELCOME5,3.1
21,2023-01-22,1939,176,1,75.49,0.11,67.1861,9,South,Online,True,2,65,Female,Food,1.1,Not Returned,Negative,NaN,FREESHIP,1.9
22,2023-01-23,1878,145,8,16.92,0.06,127.2384,1,North,Credit Card,False,1,44,Other,Food,3.8,Not Returned,Neutral,5.91,nan,3.2
23,2023-01-24,1567,163,5,96.62,0.15,410.6350,2,North,Cash,False,4,68,Male,Books,2.9,Returned,Positive,10.47,nan,1.9
24,2023-01-25,1511,127,1,94.89,0.09,86.3499,5,West,Credit Card,True,2,50,Female,Food,2.9,Not Returned,Negative,13.12,nan,1.0
25,2023-01-26,1199,138,6,27.18,0.13,141.8796,2,East,Online,True,6,66,Female,Electronics,4.8,Returned,Neutral,NaN,nan,4.4
26,2023-01-27,1129,164,6,23.73,0.22,111.0564,8,South,Cash,True,4,29,Other,Clothing,1.2,Not Returned,Neutral,15.87,WELCOME5,1.5
27,2023-01-28,1089,130,9,95.91,0.01,854.5581,8,South,Online,False,1,49,Male,Food,2.5,Not Returned,Negative,9.28,WELCOME5,4.5
28,2023-01-29,1737,183,4,38.60,0.10,138.9600,4,West,Credit Card,False,5,24,Female,Clothing,3.1,Not Returned,Negative,6.80,WELCOME5,3.5
29,2023-01-30,1362,107,2,42.56,0.08,78.3104,5,West,Cash,True,5,59,Male,Electronics,3.6,Not Returned,Neutral,5.49,nan,NaN
30,2023-01-31,1010,163,1,54.53,0.27,39.8069,6,North,Credit Card,False,3,52,Female,Clothing,1.3,Returned,Negative,16.02,SAVE10,1.4
31,2023-02-01,1077,141,3,99.53,0.26,220.9566,3,South,Cash,True,2,21,Male,Electronics,2.9,Returned,Positive,19.67,SAVE10,NaN
32,2023-02-02,1493,180,6,66.08,0.07,368.7264,2,South,Credit Card,True,5,35,Female,Books,3.7,Returned,Positive,14.19,WELCOME5,NaN
33,2023-02-03,1722,161,1,71.85,0.06,67.5390,8,South,Credit Card,True,6,64,Female,Clothing,2.4,Not Returned,Neutral,9.88,SAVE10,3.7
34,2023-02-04,1367,199,5,42.55,0.27,155.3075,6,East,Online,False,6,20,Female,Clothing,3.2,Not Returned,Negative,NaN,nan,4.5

<div class="alert alert-success">

**Solution 03:**
</div>

In [7]:
# 3. Validating the Data Type of a Specific Column
# Write a Pandas program to validate the data type of a specific column in a DataFrame.

# Check if 'price' column is of type float
is_of_type = 'float64'
is_price_float = df['price'].dtype == is_of_type
is_price_float

# Validate the data type of 'price' column
if is_price_float:
    print("The 'price' column is of type {}.".format(df['price'].dtype))
else:
    print("The 'price' column is not of type {}, it is {}.".format(is_of_type, df['price'].dtype))

The 'price' column is of type float64.

<div class="alert alert-warning">

**4. Checking Duplicate Rows in a DataFrame**

**Write a Pandas program to check duplicate rows in a DataFrame.**

</div>

In [8]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Add 3 duplicate rows
df = pd.concat([df, df.sample(n=3, random_state=42)], ignore_index=True)

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1482,110,1,48.76,0.03,47.2972,6,East,Cash,True,1,24,Other,Books,2.3,Not Returned,Positive,9.75,nan,4.0
1,2023-01-02,1586,192,6,47.19,0.06,266.1516,9,East,Cash,True,5,64,Other,Electronics,3.2,Not Returned,Negative,17.69,nan,4.2
2,2023-01-03,1717,185,9,21.36,0.14,165.3264,7,North,Online,False,6,27,Other,Clothing,2.2,Not Returned,Negative,12.11,SAVE10,4.9
3,2023-01-04,1116,110,2,88.25,0.20,141.2000,3,North,Cash,False,1,26,Other,Books,3.1,Returned,Negative,17.88,WELCOME5,3.4
4,2023-01-05,1900,122,1,67.99,0.01,67.3101,2,South,Cash,False,6,30,Male,Food,1.3,Returned,Positive,13.93,nan,3.3
5,2023-01-06,1563,154,4,62.78,0.12,220.9856,8,East,Credit Card,False,3,45,Female,Books,1.6,Not Returned,Negative,13.08,WELCOME5,NaN
6,2023-01-07,1224,127,1,38.45,0.26,28.4530,7,East,Cash,False,1,35,Other,Books,2.5,Returned,Neutral,9.03,nan,NaN
7,2023-01-08,1042,151,3,45.61,0.25,102.6225,1,East,Cash,False,2,46,Other,Food,1.2,Returned,Positive,6.50,nan,1.1
8,2023-01-09,1251,103,1,79.77,0.26,59.0298,5,West,Cash,False,3,43,Female,Books,2.1,Returned,Positive,18.59,nan,1.3
9,2023-01-10,1336,136,2,87.43,0.11,155.6254,9,East,Cash,False,2,21,Male,Food,4.6,Returned,Negative,NaN,nan,1.2
10,2023-01-11,1216,131,9,89.59,0.13,701.4897,9,North,Cash,True,1,23,Female,Food,2.2,Not Returned,Neutral,NaN,FREESHIP,NaN
11,2023-01-12,1803,137,2,80.24,0.27,117.1504,7,West,Online,True,5,48,Female,Clothing,3.6,Returned,Negative,12.54,WELCOME5,2.4
12,2023-01-13,1922,158,1,69.72,0.27,50.8956,4,West,Online,True,6,53,Female,Electronics,3.9,Not Returned,Negative,10.90,WELCOME5,NaN
13,2023-01-14,1321,155,1,30.75,0.10,27.6750,3,South,Online,False,2,50,Other,Electronics,4.4,Not Returned,Neutral,19.64,nan,NaN
14,2023-01-15,1716,170,5,68.44,0.15,290.8700,1,West,Cash,True,5,20,Female,Food,2.6,Returned,Neutral,NaN,WELCOME5,3.4
15,2023-01-16,1820,193,2,20.66,0.19,33.4692,4,West,Cash,True,4,19,Other,Food,3.8,Returned,Negative,16.81,SAVE10,3.9
16,2023-01-17,1828,134,1,13.75,0.06,12.9250,7,East,Credit Card,False,5,25,Female,Clothing,5.0,Returned,Negative,12.04,SAVE10,NaN
17,2023-01-18,1490,177,5,72.04,0.02,352.9960,2,North,Cash,True,1,66,Other,Food,3.9,Not Returned,Positive,17.62,nan,NaN
18,2023-01-19,1552,101,5,69.74,0.07,324.2910,3,South,Credit Card,True,1,41,Male,Clothing,4.6,Returned,Negative,7.21,nan,3.6
19,2023-01-20,1583,169,2,23.45,0.16,39.3960,6,South,Credit Card,True,6,28,Other,Clothing,4.4,Not Returned,Neutral,NaN,nan,NaN
20,2023-01-21,1971,124,9,43.57,0.17,325.4679,8,East,Cash,True,2,68,Male,Food,1.4,Returned,Positive,11.97,FREESHIP,NaN
21,2023-01-22,1696,157,4,71.47,0.03,277.3036,7,South,Cash,True,2,42,Female,Clothing,3.0,Returned,Positive,19.29,nan,NaN
22,2023-01-23,1447,168,6,75.96,0.30,319.0320,4,North,Credit Card,False,5,67,Female,Books,4.7,Not Returned,Negative,5.01,nan,1.5
23,2023-01-24,1360,163,2,76.28,0.21,120.5224,7,North,Credit Card,False,4,66,Other,Clothing,3.7,Not Returned,Positive,14.38,nan,3.5
24,2023-01-25,1947,104,2,17.13,0.14,29.4636,8,West,Credit Card,True,1,51,Other,Clothing,4.2,Not Returned,Positive,12.32,nan,NaN
25,2023-01-26,1484,185,4,55.25,0.27,161.3300,9,West,Credit Card,False,3,21,Female,Food,1.7,Not Returned,Neutral,NaN,FREESHIP,1.7
26,2023-01-27,1464,176,3,47.40,0.07,132.2460,5,East,Cash,False,6,52,Other,Clothing,1.8,Returned,Positive,8.95,SAVE10,4.7
27,2023-01-28,1122,131,3,41.50,0.28,89.6400,1,West,Cash,True,4,22,Male,Food,3.2,Returned,Neutral,11.40,SAVE10,3.6
28,2023-01-29,1980,107,9,72.88,0.13,570.6504,6,North,Credit Card,True,3,18,Other,Books,1.6,Not Returned,Positive,11.35,nan,1.5
29,2023-01-30,1366,143,9,30.57,0.04,264.1248,5,West,Online,True,6,62,Male,Books,4.5,Not Returned,Positive,18.85,FREESHIP,NaN
30,2023-01-31,1878,147,9,36.21,0.14,280.2654,7,West,Credit Card,True,4,45,Other,Food,1.8,Returned,Neutral,NaN,FREESHIP,3.6
31,2023-02-01,1366,138,4,88.29,0.20,282.5280,5,North,Credit Card,False,4,28,Male,Clothing,1.0,Returned,Positive,7.37,nan,4.0
32,2023-02-02,1008,111,7,80.70,0.11,502.7610,3,South,Online,False,5,41,Other,Food,1.6,Returned,Neutral,NaN,nan,NaN
33,2023-02-03,1267,176,4,56.98,0.12,200.5696,5,East,Online,False,3,31,Other,Food,3.8,Returned,Negative,15.86,WELCOME5,NaN
34,2023-02-04,1943,159,1,97.54,0.14,83.8844,1,East,Cash,True,4,41,Female,Electronics,1.8,Returned,Positive,19.09,nan,3.1
35,2023-01-27,1464,176,3,47.40,0.07,132.2460,5,East,Cash,False,6,52,Other,Clothing,1.8,Returned,Positive,8.95,SAVE10,4.7
36,2023-01-14,1321,155,1,30.75,0.10,27.6750,3,South,Online,False,2,50,Other,Electronics,4.4,Not Returned,Neutral,19.64,nan,NaN
37,2023-01-25,1947,104,2,17.13,0.14,29.4636,8,West,Credit Card,True,1,51,Other,Clothing,4.2,Not Returned,Positive,12.32,nan,NaN

<div class="alert alert-success">

**Solution 04:**
</div>

In [9]:
# 4. Checking Duplicate Rows in a DataFrame
# Write a Pandas program to check duplicate rows in a DataFrame.

# Check for duplicate rows
duplicate_rows = df[df.duplicated()]
duplicate_rows

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
35,2023-01-27,1464,176,3,47.40,0.07,132.2460,5,East,Cash,False,6,52,Other,Clothing,1.8,Returned,Positive,8.95,SAVE10,4.7
36,2023-01-14,1321,155,1,30.75,0.10,27.6750,3,South,Online,False,2,50,Other,Electronics,4.4,Not Returned,Neutral,19.64,nan,NaN
37,2023-01-25,1947,104,2,17.13,0.14,29.4636,8,West,Credit Card,True,1,51,Other,Clothing,4.2,Not Returned,Positive,12.32,nan,NaN

<div class="alert alert-warning">

**5. Removing Duplicate Rows from a DataFrame**

**Write a Pandas program to remove duplicate rows from a DataFrame.**

</div>

In [10]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Add 3 duplicate rows
df = pd.concat([df, df.sample(n=3, random_state=42)], ignore_index=True)

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1930,103,2,41.86,0.22,65.3016,1,West,Online,True,3,22,Other,Electronics,2.0,Not Returned,Negative,17.27,FREESHIP,NaN
1,2023-01-02,1895,138,3,36.57,0.11,97.6419,7,South,Cash,True,4,54,Female,Clothing,2.9,Not Returned,Positive,15.03,WELCOME5,2.4
2,2023-01-03,1728,185,2,31.09,0.09,56.5838,8,South,Online,True,6,39,Female,Books,4.5,Returned,Neutral,8.27,nan,1.7
3,2023-01-04,1297,180,9,34.63,0.06,292.9698,2,North,Credit Card,True,2,35,Male,Books,1.9,Returned,Neutral,13.59,FREESHIP,4.2
4,2023-01-05,1863,119,7,62.39,0.24,331.9148,6,North,Cash,True,2,43,Other,Books,4.2,Not Returned,Negative,NaN,FREESHIP,2.4
5,2023-01-06,1813,139,1,72.02,0.06,67.6988,7,East,Cash,False,4,42,Other,Electronics,1.3,Returned,Neutral,NaN,FREESHIP,NaN
6,2023-01-07,1903,194,6,74.09,0.07,413.4222,9,West,Online,False,2,26,Male,Books,4.9,Not Returned,Negative,9.46,nan,3.5
7,2023-01-08,1544,141,5,46.36,0.12,203.9840,6,West,Cash,True,4,22,Other,Food,3.2,Not Returned,Positive,17.02,nan,2.1
8,2023-01-09,1213,146,5,11.27,0.09,51.2785,3,West,Cash,False,2,64,Female,Food,3.4,Returned,Neutral,7.76,SAVE10,4.9
9,2023-01-10,1535,116,4,64.25,0.15,218.4500,2,West,Cash,False,6,26,Other,Clothing,1.1,Returned,Neutral,NaN,nan,NaN
10,2023-01-11,1308,184,2,62.42,0.06,117.3496,2,South,Credit Card,True,1,58,Male,Books,3.8,Returned,Negative,6.51,nan,NaN
11,2023-01-12,1031,109,6,94.44,0.17,470.3112,1,East,Credit Card,True,6,37,Male,Food,2.9,Not Returned,Positive,14.02,nan,3.1
12,2023-01-13,1385,148,3,96.68,0.27,211.7292,1,West,Cash,True,5,36,Female,Electronics,1.9,Returned,Negative,13.70,SAVE10,4.1
13,2023-01-14,1830,133,9,25.62,0.28,166.0176,7,East,Cash,True,1,40,Female,Electronics,3.6,Returned,Positive,NaN,FREESHIP,3.4
14,2023-01-15,1261,167,2,72.82,0.04,139.8144,3,West,Credit Card,True,3,35,Male,Books,4.0,Not Returned,Neutral,11.29,nan,NaN
15,2023-01-16,1771,198,6,13.30,0.15,67.8300,6,East,Online,False,4,63,Female,Food,4.4,Returned,Negative,18.95,nan,NaN
16,2023-01-17,1861,199,9,25.94,0.18,191.4372,6,North,Cash,False,3,31,Female,Clothing,3.2,Returned,Neutral,17.70,FREESHIP,4.3
17,2023-01-18,1701,152,3,64.46,0.30,135.3660,1,East,Cash,True,3,61,Female,Food,2.0,Returned,Neutral,NaN,WELCOME5,1.1
18,2023-01-19,1439,158,5,17.14,0.29,60.8470,9,North,Cash,True,2,27,Other,Food,4.8,Not Returned,Negative,17.61,FREESHIP,3.4
19,2023-01-20,1777,140,7,86.99,0.18,499.3226,4,West,Cash,True,1,42,Other,Food,2.4,Not Returned,Negative,NaN,SAVE10,3.6
20,2023-01-21,1713,192,2,45.55,0.14,78.3460,2,East,Cash,True,1,62,Female,Clothing,2.7,Not Returned,Positive,16.59,FREESHIP,4.6
21,2023-01-22,1003,136,5,34.97,0.23,134.6345,3,South,Credit Card,False,5,39,Female,Food,4.7,Returned,Negative,11.77,FREESHIP,1.5
22,2023-01-23,1454,171,4,87.08,0.19,282.1392,3,East,Cash,False,2,27,Other,Books,1.1,Returned,Neutral,8.42,nan,NaN
23,2023-01-24,1683,158,2,43.36,0.08,79.7824,6,East,Online,True,2,27,Male,Electronics,4.6,Returned,Positive,5.15,FREESHIP,NaN
24,2023-01-25,1898,156,9,75.72,0.03,661.0356,8,West,Online,True,4,33,Male,Books,2.6,Not Returned,Positive,14.53,FREESHIP,2.5
25,2023-01-26,1093,199,5,69.46,0.07,322.9890,5,North,Cash,True,5,48,Other,Electronics,4.6,Returned,Neutral,9.82,WELCOME5,3.6
26,2023-01-27,1437,176,9,53.55,0.20,385.5600,7,North,Credit Card,True,1,32,Male,Books,1.8,Returned,Negative,NaN,SAVE10,2.3
27,2023-01-28,1112,116,6,24.62,0.21,116.6988,9,West,Cash,True,6,38,Male,Electronics,2.7,Returned,Negative,19.68,SAVE10,4.6
28,2023-01-29,1500,179,6,24.81,0.09,135.4626,4,East,Online,False,3,24,Female,Books,4.5,Not Returned,Positive,12.88,nan,2.4
29,2023-01-30,1975,137,6,93.94,0.18,462.1848,2,West,Online,True,4,54,Male,Food,4.4,Not Returned,Positive,19.06,nan,1.1
30,2023-01-31,1599,159,5,14.60,0.15,62.0500,6,West,Credit Card,True,2,50,Other,Food,4.7,Not Returned,Negative,NaN,nan,NaN
31,2023-02-01,1868,100,8,26.76,0.19,173.4048,4,East,Online,False,4,52,Male,Electronics,3.3,Returned,Positive,17.67,WELCOME5,4.4
32,2023-02-02,1042,134,1,40.05,0.03,38.8485,9,South,Credit Card,False,2,26,Male,Clothing,3.8,Not Returned,Positive,11.70,nan,3.5
33,2023-02-03,1023,191,7,88.34,0.13,537.9906,3,West,Cash,True,5,29,Male,Electronics,1.2,Returned,Negative,14.00,nan,3.3
34,2023-02-04,1076,126,4,56.14,0.18,184.1392,2,East,Cash,False,1,67,Other,Electronics,3.7,Returned,Positive,7.37,FREESHIP,1.4
35,2023-01-27,1437,176,9,53.55,0.20,385.5600,7,North,Credit Card,True,1,32,Male,Books,1.8,Returned,Negative,NaN,SAVE10,2.3
36,2023-01-14,1830,133,9,25.62,0.28,166.0176,7,East,Cash,True,1,40,Female,Electronics,3.6,Returned,Positive,NaN,FREESHIP,3.4
37,2023-01-25,1898,156,9,75.72,0.03,661.0356,8,West,Online,True,4,33,Male,Books,2.6,Not Returned,Positive,14.53,FREESHIP,2.5

<div class="alert alert-success">

**Solution 05:**
</div>

In [11]:
# 5. Removing Duplicate Rows from a DataFrame
# Write a Pandas program to remove duplicate rows from a DataFrame.

print("Shape of DataFrame before removing duplicates:\n", df.shape)
# Remove duplicate rows
df = df.drop_duplicates()
print("Shape of DataFrame after removing duplicates:\n", df.shape)

Shape of DataFrame before removing duplicates:
 (38, 21)
Shape of DataFrame after removing duplicates:
 (35, 21)

<div class="alert alert-warning">

**6. Validating Data Based on Custom Conditions**

**Write a Pandas program to validate data based on custom conditions.**

</div>

In [12]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Add 3 duplicate rows
df = pd.concat([df, df.sample(n=3, random_state=42)], ignore_index=True)

# Add 3 more rows with negative price
df = pd.concat([df, pd.DataFrame({
    'date': pd.date_range(start='2023-02-05', periods=3, freq='D'),
    'customer_id': [1500, 1501, 1502],
    'product_id': [150, 151, 152],
    'quantity': [2, 3, 1],
    'price': [-20.00, -15.00, -30.00],  # Negative prices
    'discount': [0.1, 0.2, 0.15],
    'revenue': [0, 0, 0],  # Placeholder; will be recalculated
    'store_id': [5, 6, 7],
    'region': ['North', 'South', 'East'],
    'payment_method': ['Credit Card', 'Cash', 'Online'],
    'is_member': [True, False, True],
    'delivery_days': [3, 4, 2],
    'customer_age': [25, 34, 45],
    'gender': ['Male', 'Female', 'Other'],
    'product_category': ['Electronics', 'Clothing', 'Books'],
    'rating': [4.5, 3.0, 5.0],
    'return_status': ['Not Returned', 'Returned', 'Not Returned'],
    'feedback': ['Positive', 'Neutral', 'Negative'],
})], ignore_index=True)

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1819,173,6,64.90,0.19,315.4140,7,East,Online,False,5,43,Female,Food,1.1,Not Returned,Positive,7.32,SAVE10,4.7
1,2023-01-02,1977,116,1,52.17,0.27,38.0841,7,East,Cash,False,5,64,Female,Clothing,1.1,Not Returned,Neutral,18.00,nan,2.0
2,2023-01-03,1763,168,8,12.34,0.03,95.7584,1,East,Cash,False,1,27,Female,Electronics,3.0,Not Returned,Negative,19.15,nan,NaN
3,2023-01-04,1888,141,2,47.76,0.20,76.4160,1,West,Cash,True,3,69,Male,Clothing,3.0,Returned,Negative,10.47,WELCOME5,NaN
4,2023-01-05,1632,176,6,51.66,0.06,291.3624,5,South,Online,False,2,41,Other,Clothing,2.2,Not Returned,Positive,NaN,FREESHIP,3.4
5,2023-01-06,1110,176,5,55.07,0.07,256.0755,1,West,Cash,False,6,54,Other,Books,4.4,Not Returned,Neutral,9.02,nan,3.7
6,2023-01-07,1207,189,1,41.10,0.01,40.6890,1,North,Credit Card,True,5,52,Male,Electronics,3.6,Not Returned,Neutral,5.79,FREESHIP,2.6
7,2023-01-08,1284,116,4,28.12,0.05,106.8560,4,South,Online,True,5,49,Female,Books,4.0,Returned,Negative,12.32,FREESHIP,NaN
8,2023-01-09,1429,143,8,12.06,0.08,88.7616,3,West,Credit Card,False,2,61,Other,Electronics,4.7,Returned,Positive,19.83,nan,3.9
9,2023-01-10,1029,142,1,18.46,0.15,15.6910,9,East,Cash,True,4,52,Female,Electronics,1.9,Not Returned,Positive,11.18,SAVE10,NaN
10,2023-01-11,1963,130,1,29.12,0.15,24.7520,6,West,Credit Card,True,1,35,Male,Books,3.4,Returned,Positive,12.24,FREESHIP,3.5
11,2023-01-12,1061,127,1,28.93,0.18,23.7226,7,West,Online,True,5,32,Female,Books,1.5,Not Returned,Positive,13.19,WELCOME5,NaN
12,2023-01-13,1040,186,8,38.37,0.22,239.4288,3,South,Online,False,6,59,Female,Food,4.0,Returned,Negative,17.00,SAVE10,NaN
13,2023-01-14,1207,187,2,23.75,0.18,38.9500,6,South,Credit Card,True,6,24,Female,Food,4.1,Returned,Neutral,13.63,SAVE10,2.0
14,2023-01-15,1155,178,1,21.35,0.03,20.7095,1,North,Online,False,4,34,Other,Clothing,4.2,Not Returned,Positive,NaN,SAVE10,NaN
15,2023-01-16,1974,146,4,49.94,0.14,171.7936,4,East,Online,True,3,54,Female,Electronics,2.1,Not Returned,Neutral,6.48,SAVE10,4.5
16,2023-01-17,1196,153,8,58.37,0.10,420.2640,3,North,Cash,False,6,66,Other,Books,4.8,Returned,Neutral,5.12,FREESHIP,4.7
17,2023-01-18,1156,138,2,40.30,0.23,62.0620,2,South,Cash,True,5,31,Other,Clothing,3.2,Returned,Negative,NaN,FREESHIP,1.5
18,2023-01-19,1429,123,3,10.88,0.25,24.4800,5,North,Credit Card,True,1,21,Other,Food,3.0,Not Returned,Negative,18.05,FREESHIP,4.4
19,2023-01-20,1143,105,2,11.18,0.26,16.5464,3,South,Credit Card,True,4,36,Female,Clothing,4.8,Not Returned,Negative,16.09,nan,4.4
20,2023-01-21,1700,146,4,67.92,0.30,190.1760,9,West,Credit Card,True,4,67,Other,Clothing,1.0,Not Returned,Positive,9.70,FREESHIP,1.0
21,2023-01-22,1252,168,8,57.95,0.13,403.3320,8,East,Cash,True,3,56,Other,Food,3.0,Returned,Positive,9.29,nan,4.2
22,2023-01-23,1952,171,8,13.68,0.08,100.6848,7,West,Online,True,3,64,Female,Electronics,2.5,Not Returned,Negative,7.18,FREESHIP,2.8
23,2023-01-24,1370,124,5,52.81,0.02,258.7690,5,South,Credit Card,False,6,23,Female,Clothing,3.9,Not Returned,Negative,9.51,nan,4.1
24,2023-01-25,1112,151,4,85.32,0.16,286.6752,5,East,Credit Card,False,2,19,Female,Electronics,1.4,Not Returned,Negative,17.16,nan,4.8
25,2023-01-26,1509,154,7,30.55,0.11,190.3265,9,North,Online,True,6,49,Other,Books,1.4,Not Returned,Negative,18.16,SAVE10,2.4
26,2023-01-27,1540,101,7,69.83,0.28,351.9432,5,West,Cash,True,4,49,Male,Clothing,4.3,Not Returned,Negative,NaN,nan,NaN
27,2023-01-28,1606,174,4,60.90,0.18,199.7520,7,East,Credit Card,False,2,57,Male,Books,3.4,Returned,Neutral,14.10,WELCOME5,NaN
28,2023-01-29,1459,176,8,11.60,0.01,91.8720,8,East,Credit Card,False,1,40,Male,Books,1.3,Returned,Negative,18.41,WELCOME5,4.4
29,2023-01-30,1881,147,1,58.20,0.12,51.2160,3,West,Credit Card,False,5,31,Other,Food,1.7,Returned,Neutral,NaN,nan,3.5
30,2023-01-31,1881,168,1,41.54,0.25,31.1550,8,North,Cash,False,1,27,Other,Electronics,4.3,Returned,Negative,NaN,nan,2.2
31,2023-02-01,1582,133,9,69.11,0.03,603.3303,7,North,Credit Card,False,3,67,Other,Clothing,5.0,Returned,Neutral,5.89,SAVE10,1.3
32,2023-02-02,1159,103,2,30.12,0.05,57.2280,9,East,Cash,False,4,27,Female,Clothing,4.8,Not Returned,Positive,8.30,nan,NaN
33,2023-02-03,1329,158,5,96.03,0.26,355.3110,5,West,Cash,False,3,57,Other,Clothing,3.0,Not Returned,Neutral,10.53,WELCOME5,3.6
34,2023-02-04,1062,182,6,57.97,0.10,313.0380,2,West,Credit Card,True,5,57,Other,Books,2.6,Returned,Negative,18.67,SAVE10,NaN
35,2023-01-27,1540,101,7,69.83,0.28,351.9432,5,West,Cash,True,4,49,Male,Clothing,4.3,Not Returned,Negative,NaN,nan,NaN
36,2023-01-14,1207,187,2,23.75,0.18,38.9500,6,South,Credit Card,True,6,24,Female,Food,4.1,Returned,Neutral,13.63,SAVE10,2.0
37,2023-01-25,1112,151,4,85.32,0.16,286.6752,5,East,Credit Card,False,2,19,Female,Electronics,1.4,Not Returned,Negative,17.16,nan,4.8
38,2023-02-05,1500,150,2,-20.00,0.10,0.0000,5,North,Credit Card,True,3,25,Male,Electronics,4.5,Not Returned,Positive,NaN,NaN,NaN
39,2023-02-06,1501,151,3,-15.00,0.20,0.0000,6,South,Cash,False,4,34,Female,Clothing,3.0,Returned,Neutral,NaN,NaN,NaN
40,2023-02-07,1502,152,1,-30.00,0.15,0.0000,7,East,Online,True,2,45,Other,Books,5.0,Not Returned,Negative,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 06:**
</div>

In [13]:
# 6. Validating Data Based on Custom Conditions
# Write a Pandas program to validate data based on custom conditions.

# Check if 'price' is greater than 0
valid_price = df['price'] > 0
if valid_price.all():
    print("All prices are valid.")
else:
    print("Some prices are invalid:")
    display(df[~valid_price])

Some prices are invalid:

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,is_member,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
38,2023-02-05,1500,150,2,-20.0,0.10,0.0,5,North,Credit Card,True,3,25,Male,Electronics,4.5,Not Returned,Positive,NaN,NaN,NaN
39,2023-02-06,1501,151,3,-15.0,0.20,0.0,6,South,Cash,False,4,34,Female,Clothing,3.0,Returned,Neutral,NaN,NaN,NaN
40,2023-02-07,1502,152,1,-30.0,0.15,0.0,7,East,Online,True,2,45,Other,Books,5.0,Not Returned,Negative,NaN,NaN,NaN