[Pandas Missing Values](https://www.w3resource.com/python-exercises/pandas/missing-values/index.php)

In [1]:
import pandas as pd
import numpy as np

<div class="alert alert-warning">

**1. Detect Missing Values**

**Write a Pandas program to detect missing values of a given DataFrame. Display True or False.**

</div>

In [2]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1187,198,7,87.68,0.01,607.6224,6,North,Online,...,4,46,Other,Food,2.4,Not Returned,Positive,11.65,nan,4.6
1,2023-01-02,1637,105,1,35.78,0.15,30.4130,1,West,Credit Card,...,4,30,Female,Books,1.6,Not Returned,Neutral,14.98,FREESHIP,NaN
2,2023-01-03,1013,173,7,51.78,0.14,311.7156,7,South,Credit Card,...,1,31,Other,Electronics,2.9,Not Returned,Neutral,19.44,FREESHIP,4.9
3,2023-01-04,1381,199,5,11.67,0.12,51.3480,2,East,Credit Card,...,4,19,Male,Books,2.3,Returned,Neutral,7.87,FREESHIP,3.7
4,2023-01-05,1402,186,5,41.13,0.26,152.1810,5,North,Credit Card,...,6,30,Female,Electronics,4.9,Returned,Neutral,5.94,SAVE10,2.5
5,2023-01-06,1874,161,7,33.09,0.16,194.5692,6,West,Credit Card,...,2,56,Female,Electronics,3.8,Returned,Negative,7.79,nan,2.4
6,2023-01-07,1953,168,8,38.97,0.09,283.7016,8,South,Credit Card,...,1,46,Female,Clothing,2.2,Not Returned,Neutral,18.68,SAVE10,3.4
7,2023-01-08,1600,143,4,62.91,0.30,176.1480,8,North,Credit Card,...,2,32,Male,Food,3.9,Returned,Negative,10.62,WELCOME5,NaN
8,2023-01-09,1705,197,2,19.27,0.08,35.4568,7,South,Online,...,1,41,Male,Books,2.2,Returned,Positive,19.00,WELCOME5,2.3
9,2023-01-10,1054,117,3,64.20,0.08,177.1920,3,East,Credit Card,...,3,33,Male,Food,2.6,Returned,Positive,NaN,nan,3.7
10,2023-01-11,1891,108,7,21.48,0.23,115.7772,7,West,Online,...,6,38,Male,Books,2.5,Returned,Positive,12.71,nan,5.0
11,2023-01-12,1189,132,6,50.11,0.13,261.5742,3,West,Cash,...,2,38,Male,Clothing,2.0,Returned,Negative,13.03,nan,NaN
12,2023-01-13,1031,193,3,66.74,0.24,152.1672,8,West,Credit Card,...,5,43,Female,Clothing,3.4,Returned,Negative,16.54,nan,3.0
13,2023-01-14,1497,152,5,93.89,0.10,422.5050,5,South,Cash,...,1,42,Female,Electronics,1.1,Not Returned,Negative,9.63,SAVE10,1.9
14,2023-01-15,1780,127,5,76.69,0.30,268.4150,1,East,Online,...,4,28,Female,Food,1.4,Not Returned,Positive,10.34,FREESHIP,4.6
15,2023-01-16,1557,118,8,41.11,0.14,282.8368,8,South,Online,...,3,40,Other,Clothing,4.5,Not Returned,Negative,NaN,WELCOME5,1.5
16,2023-01-17,1651,167,2,46.20,0.06,86.8560,9,East,Credit Card,...,1,26,Other,Books,3.5,Returned,Neutral,NaN,WELCOME5,NaN
17,2023-01-18,1568,196,6,87.54,0.02,514.7352,7,South,Online,...,1,59,Male,Food,2.5,Returned,Neutral,7.20,SAVE10,NaN
18,2023-01-19,1946,199,8,97.72,0.27,570.6848,9,South,Cash,...,3,33,Other,Electronics,1.2,Returned,Neutral,11.52,SAVE10,3.9
19,2023-01-20,1738,146,6,50.01,0.07,279.0558,5,North,Credit Card,...,4,33,Other,Electronics,2.5,Not Returned,Negative,18.06,nan,2.9
20,2023-01-21,1548,144,2,68.92,0.19,111.6504,2,South,Online,...,2,63,Other,Clothing,1.6,Not Returned,Positive,12.61,SAVE10,NaN
21,2023-01-22,1123,173,3,22.08,0.18,54.3168,7,East,Cash,...,3,30,Male,Clothing,4.8,Returned,Negative,16.37,nan,2.0
22,2023-01-23,1271,181,5,65.23,0.07,303.3195,1,East,Credit Card,...,4,52,Male,Clothing,3.6,Returned,Negative,17.77,WELCOME5,1.3
23,2023-01-24,1761,160,9,15.65,0.11,125.3565,6,East,Cash,...,5,42,Other,Books,2.3,Returned,Negative,NaN,nan,3.8
24,2023-01-25,1588,126,4,28.12,0.19,91.1088,1,South,Credit Card,...,4,62,Male,Clothing,3.8,Returned,Positive,NaN,SAVE10,3.1
25,2023-01-26,1163,184,1,35.84,0.13,31.1808,2,South,Online,...,5,65,Female,Clothing,3.3,Not Returned,Positive,NaN,FREESHIP,4.2
26,2023-01-27,1256,120,8,15.54,0.09,113.1312,7,North,Cash,...,4,61,Female,Electronics,1.1,Not Returned,Negative,11.90,nan,3.0
27,2023-01-28,1427,164,8,51.29,0.15,348.7720,4,East,Cash,...,6,21,Female,Clothing,1.5,Not Returned,Positive,17.82,SAVE10,2.7
28,2023-01-29,1438,161,1,77.34,0.22,60.3252,8,East,Credit Card,...,4,22,Female,Clothing,2.2,Returned,Negative,5.32,FREESHIP,3.4
29,2023-01-30,1856,126,8,29.46,0.12,207.3984,5,North,Online,...,1,50,Other,Books,4.5,Returned,Negative,5.72,nan,NaN
30,2023-01-31,1299,141,3,82.78,0.28,178.8048,3,South,Cash,...,1,49,Other,Electronics,4.2,Not Returned,Neutral,13.38,FREESHIP,3.0
31,2023-02-01,1593,106,3,61.65,0.22,144.2610,3,South,Credit Card,...,2,42,Male,Clothing,4.0,Not Returned,Negative,NaN,SAVE10,4.9
32,2023-02-02,1229,136,6,66.48,0.21,315.1152,9,South,Cash,...,4,57,Male,Food,3.7,Not Returned,Negative,17.96,nan,NaN
33,2023-02-03,1056,161,3,84.78,0.04,244.1664,5,South,Credit Card,...,2,59,Male,Food,1.9,Not Returned,Negative,19.61,WELCOME5,2.7
34,2023-02-04,1350,103,6,96.98,0.20,465.5040,2,North,Online,...,4,25,Other,Books,3.9,Not Returned,Positive,17.35,FREESHIP,3.8

<div class="alert alert-success">

**Solution 01:**
</div>

In [3]:
print(type(df.isna()))
df.isna()

<class 'pandas.core.frame.DataFrame'>

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
17,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
30,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
32,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
33,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [4]:
print(df.isna().any())  
df.isna().sum()

date                False
customer_id         False
product_id          False
quantity            False
price               False
discount            False
revenue             False
store_id            False
region              False
payment_method      False
is_member           False
delivery_days       False
customer_age        False
gender              False
product_category    False
rating              False
return_status       False
feedback            False
shipping_cost        True
coupon_code         False
delivery_rating      True
dtype: bool

date                0
customer_id         0
product_id          0
quantity            0
price               0
discount            0
revenue             0
store_id            0
region              0
payment_method      0
is_member           0
delivery_days       0
customer_age        0
gender              0
product_category    0
rating              0
return_status       0
feedback            0
shipping_cost       7
coupon_code         0
delivery_rating     8
dtype: int64

<div class="alert alert-warning">

**2. Identify Columns with Missing Values**

**Write a Pandas program to identify the column(s) of a given DataFrame which have at least one missing value.**

</div>

In [5]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1435,192,2,52.99,0.20,84.7840,6,West,Cash,...,3,42,Other,Food,4.7,Not Returned,Negative,19.38,WELCOME5,3.0
1,2023-01-02,1166,147,3,19.89,0.26,44.1558,3,North,Credit Card,...,6,51,Female,Clothing,3.4,Returned,Negative,11.31,FREESHIP,2.7
2,2023-01-03,1793,101,4,31.93,0.06,120.0568,1,West,Online,...,5,30,Male,Books,1.6,Not Returned,Positive,8.05,nan,3.7
3,2023-01-04,1721,190,7,84.69,0.12,521.6904,3,South,Online,...,3,26,Male,Food,2.0,Not Returned,Neutral,16.70,WELCOME5,NaN
4,2023-01-05,1859,126,3,41.82,0.18,102.8772,4,North,Online,...,5,37,Other,Books,1.4,Returned,Neutral,6.42,WELCOME5,1.1
5,2023-01-06,1071,141,2,50.83,0.07,94.5438,9,East,Online,...,5,20,Other,Food,3.9,Returned,Neutral,10.72,WELCOME5,NaN
6,2023-01-07,1119,150,9,73.44,0.13,575.0352,5,North,Credit Card,...,6,29,Female,Food,2.9,Not Returned,Negative,8.75,FREESHIP,NaN
7,2023-01-08,1878,172,1,34.81,0.12,30.6328,9,South,Credit Card,...,5,57,Male,Clothing,4.0,Returned,Neutral,13.63,SAVE10,NaN
8,2023-01-09,1557,169,3,53.16,0.17,132.3684,4,North,Cash,...,4,34,Other,Books,1.6,Not Returned,Neutral,7.50,WELCOME5,NaN
9,2023-01-10,1413,104,7,37.44,0.23,201.8016,5,West,Cash,...,1,28,Female,Clothing,3.0,Not Returned,Negative,13.88,nan,2.4
10,2023-01-11,1366,196,5,86.55,0.24,328.8900,1,South,Online,...,3,36,Female,Electronics,3.3,Not Returned,Neutral,11.71,SAVE10,3.9
11,2023-01-12,1526,138,4,39.71,0.08,146.1328,1,South,Online,...,2,24,Other,Food,3.9,Not Returned,Neutral,11.50,nan,4.5
12,2023-01-13,1719,196,9,89.24,0.12,706.7808,8,North,Cash,...,1,69,Female,Clothing,1.2,Not Returned,Positive,19.64,FREESHIP,NaN
13,2023-01-14,1807,125,9,10.62,0.15,81.2430,4,North,Credit Card,...,5,40,Male,Clothing,4.0,Returned,Negative,8.92,nan,2.4
14,2023-01-15,1925,164,6,10.13,0.27,44.3694,8,North,Online,...,5,36,Male,Books,4.9,Not Returned,Negative,5.65,nan,3.2
15,2023-01-16,1262,148,4,10.54,0.05,40.0520,6,South,Online,...,3,42,Female,Clothing,3.3,Not Returned,Positive,17.40,SAVE10,NaN
16,2023-01-17,1179,123,5,17.28,0.04,82.9440,5,East,Cash,...,2,64,Other,Books,2.2,Returned,Neutral,NaN,WELCOME5,NaN
17,2023-01-18,1900,101,2,73.75,0.24,112.1000,8,West,Online,...,5,64,Other,Electronics,1.6,Returned,Negative,6.92,FREESHIP,4.1
18,2023-01-19,1391,127,2,68.17,0.28,98.1648,7,South,Credit Card,...,4,28,Male,Food,1.5,Not Returned,Neutral,12.79,SAVE10,1.7
19,2023-01-20,1787,190,2,30.07,0.09,54.7274,1,West,Cash,...,5,37,Female,Books,1.6,Not Returned,Neutral,13.97,WELCOME5,2.6
20,2023-01-21,1536,164,8,94.48,0.30,529.0880,5,North,Cash,...,4,60,Female,Clothing,1.4,Returned,Negative,7.43,nan,NaN
21,2023-01-22,1409,160,5,46.70,0.14,200.8100,1,South,Cash,...,4,18,Other,Books,2.4,Not Returned,Neutral,17.51,FREESHIP,1.7
22,2023-01-23,1484,151,8,68.83,0.10,495.5760,4,North,Online,...,2,69,Male,Electronics,3.9,Not Returned,Neutral,15.78,nan,2.5
23,2023-01-24,1327,108,2,88.06,0.03,170.8364,1,South,Credit Card,...,4,42,Female,Clothing,4.5,Not Returned,Negative,12.36,FREESHIP,NaN
24,2023-01-25,1278,110,8,47.30,0.05,359.4800,4,North,Online,...,6,40,Female,Books,3.0,Returned,Positive,NaN,WELCOME5,NaN
25,2023-01-26,1785,159,1,39.14,0.17,32.4862,4,North,Online,...,1,49,Other,Books,1.7,Not Returned,Neutral,8.65,nan,2.0
26,2023-01-27,1669,131,8,73.93,0.10,532.2960,5,East,Credit Card,...,2,25,Other,Books,1.4,Returned,Negative,9.05,nan,4.2
27,2023-01-28,1129,103,1,49.95,0.18,40.9590,3,North,Cash,...,4,58,Other,Electronics,4.7,Not Returned,Neutral,15.68,SAVE10,NaN
28,2023-01-29,1055,185,3,43.10,0.30,90.5100,2,East,Online,...,6,35,Other,Electronics,3.2,Not Returned,Neutral,NaN,WELCOME5,NaN
29,2023-01-30,1699,109,3,66.67,0.06,188.0094,4,South,Cash,...,1,35,Female,Electronics,1.5,Returned,Positive,NaN,WELCOME5,4.1
30,2023-01-31,1480,144,6,33.40,0.12,176.3520,6,East,Online,...,2,65,Male,Clothing,1.4,Returned,Neutral,5.37,nan,1.9
31,2023-02-01,1796,190,8,88.41,0.11,629.4792,3,East,Online,...,1,30,Female,Books,1.7,Not Returned,Neutral,NaN,SAVE10,3.2
32,2023-02-02,1835,119,3,77.83,0.23,179.7873,4,South,Credit Card,...,3,62,Female,Books,1.0,Returned,Negative,17.29,nan,3.9
33,2023-02-03,1499,139,1,72.06,0.13,62.6922,2,North,Credit Card,...,1,50,Male,Books,2.0,Returned,Positive,16.59,WELCOME5,3.4
34,2023-02-04,1680,159,3,38.08,0.16,95.9616,4,East,Cash,...,6,42,Other,Clothing,3.4,Not Returned,Negative,NaN,nan,NaN

<div class="alert alert-success">

**Solution 02:**
</div>

In [6]:
df.isna().any()
cols_have_na = df.isna().any()[lambda x: x].index.tolist()

<div class="alert alert-warning">

**3. Count Missing Values in Each Column**

**Write a Pandas program to count the number of missing values in each column of a given DataFrame.**

</div>

In [7]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1252,183,5,24.01,0.01,118.8495,8,North,Cash,...,4,36,Female,Books,4.2,Not Returned,Negative,14.17,FREESHIP,NaN
1,2023-01-02,1031,179,3,67.76,0.05,193.1160,5,South,Credit Card,...,2,60,Female,Food,1.2,Not Returned,Neutral,14.65,nan,2.8
2,2023-01-03,1968,115,2,39.80,0.14,68.4560,1,East,Online,...,5,35,Female,Electronics,2.0,Returned,Positive,7.37,FREESHIP,1.9
3,2023-01-04,1792,197,3,77.10,0.07,215.1090,7,East,Cash,...,5,47,Other,Electronics,3.0,Returned,Positive,9.66,FREESHIP,2.5
4,2023-01-05,1862,179,3,79.49,0.24,181.2372,2,East,Cash,...,3,29,Male,Food,3.0,Not Returned,Negative,10.69,nan,4.4
5,2023-01-06,1261,184,9,84.05,0.23,582.4665,1,East,Online,...,1,64,Male,Electronics,3.6,Not Returned,Neutral,8.65,WELCOME5,1.1
6,2023-01-07,1157,104,1,89.89,0.16,75.5076,8,North,Cash,...,2,60,Female,Clothing,4.2,Returned,Negative,7.86,FREESHIP,1.3
7,2023-01-08,1293,156,3,79.94,0.02,235.0236,8,North,Credit Card,...,1,36,Other,Food,4.6,Returned,Positive,18.64,SAVE10,3.6
8,2023-01-09,1602,135,5,48.00,0.21,189.6000,6,South,Online,...,5,21,Male,Clothing,2.3,Returned,Positive,15.52,FREESHIP,NaN
9,2023-01-10,1001,198,1,63.25,0.02,61.9850,8,South,Credit Card,...,6,68,Other,Books,2.5,Not Returned,Negative,NaN,FREESHIP,NaN
10,2023-01-11,1692,163,7,71.90,0.03,488.2010,8,West,Online,...,1,19,Male,Food,1.7,Not Returned,Neutral,18.86,SAVE10,3.9
11,2023-01-12,1522,148,8,98.53,0.02,772.4752,3,West,Credit Card,...,5,35,Male,Electronics,2.2,Not Returned,Positive,16.33,nan,1.8
12,2023-01-13,1189,106,5,46.10,0.10,207.4500,6,East,Cash,...,5,28,Male,Books,1.5,Not Returned,Positive,17.60,nan,1.6
13,2023-01-14,1125,141,7,81.56,0.14,490.9912,3,East,Online,...,1,57,Female,Food,4.5,Not Returned,Positive,9.86,nan,2.9
14,2023-01-15,1135,120,7,92.99,0.18,533.7626,1,East,Credit Card,...,6,20,Other,Electronics,1.2,Returned,Positive,18.83,nan,3.6
15,2023-01-16,1984,194,4,59.29,0.17,196.8428,5,South,Online,...,3,45,Male,Clothing,1.2,Not Returned,Positive,18.55,FREESHIP,NaN
16,2023-01-17,1385,149,6,93.62,0.25,421.2900,2,West,Cash,...,1,55,Other,Clothing,4.9,Returned,Positive,NaN,FREESHIP,NaN
17,2023-01-18,1829,178,2,93.66,0.09,170.4612,9,South,Cash,...,1,59,Male,Books,4.3,Returned,Positive,13.66,nan,2.2
18,2023-01-19,1969,166,9,81.87,0.29,523.1493,7,North,Online,...,1,60,Female,Food,3.0,Not Returned,Neutral,NaN,nan,3.8
19,2023-01-20,1148,144,6,65.14,0.02,383.0232,4,East,Online,...,3,33,Other,Books,3.4,Returned,Neutral,10.06,FREESHIP,3.4
20,2023-01-21,1113,196,8,99.04,0.05,752.7040,9,South,Online,...,6,30,Other,Electronics,2.1,Returned,Positive,6.59,SAVE10,NaN
21,2023-01-22,1862,155,6,96.72,0.10,522.2880,9,South,Cash,...,2,32,Female,Electronics,1.8,Not Returned,Positive,8.69,nan,NaN
22,2023-01-23,1079,189,3,91.79,0.29,195.5127,5,West,Credit Card,...,4,53,Female,Clothing,3.8,Not Returned,Negative,5.04,SAVE10,NaN
23,2023-01-24,1445,138,2,29.66,0.22,46.2696,5,North,Cash,...,6,23,Female,Electronics,5.0,Returned,Positive,16.63,nan,3.0
24,2023-01-25,1673,193,5,76.87,0.20,307.4800,1,West,Cash,...,5,55,Female,Food,3.9,Not Returned,Negative,15.92,WELCOME5,1.0
25,2023-01-26,1598,101,5,27.95,0.00,139.7500,2,South,Cash,...,2,29,Female,Food,2.3,Returned,Negative,NaN,WELCOME5,NaN
26,2023-01-27,1088,132,4,23.33,0.29,66.2572,9,West,Credit Card,...,1,48,Female,Clothing,3.6,Not Returned,Negative,17.09,nan,1.3
27,2023-01-28,1868,103,1,77.10,0.13,67.0770,3,West,Online,...,6,44,Other,Food,4.6,Not Returned,Positive,6.38,nan,2.7
28,2023-01-29,1632,146,1,71.95,0.01,71.2305,8,North,Cash,...,2,39,Female,Electronics,1.8,Returned,Positive,19.15,WELCOME5,NaN
29,2023-01-30,1318,181,4,53.81,0.27,157.1252,1,East,Credit Card,...,1,58,Female,Books,3.3,Returned,Neutral,6.20,SAVE10,1.8
30,2023-01-31,1666,183,3,15.68,0.24,35.7504,8,East,Online,...,4,19,Male,Electronics,1.8,Not Returned,Neutral,NaN,SAVE10,3.4
31,2023-02-01,1361,178,5,75.20,0.28,270.7200,6,South,Online,...,5,44,Male,Clothing,1.9,Not Returned,Neutral,NaN,nan,4.7
32,2023-02-02,1212,142,6,90.61,0.23,418.6182,2,West,Online,...,1,34,Other,Electronics,1.6,Returned,Positive,7.36,FREESHIP,1.9
33,2023-02-03,1951,193,8,59.37,0.07,441.7128,2,North,Online,...,6,25,Other,Books,2.6,Returned,Negative,17.85,FREESHIP,3.2
34,2023-02-04,1938,167,4,30.32,0.27,88.5344,7,North,Credit Card,...,5,19,Other,Clothing,4.8,Not Returned,Negative,5.04,WELCOME5,NaN

<div class="alert alert-success">

**Solution 03:**
</div>

In [8]:
df.isna().sum()

date                 0
customer_id          0
product_id           0
quantity             0
price                0
discount             0
revenue              0
store_id             0
region               0
payment_method       0
is_member            0
delivery_days        0
customer_age         0
gender               0
product_category     0
rating               0
return_status        0
feedback             0
shipping_cost        6
coupon_code          0
delivery_rating     11
dtype: int64

<div class="alert alert-warning">

**4. Replace Non-Valuable Missing Values**

**Write a Pandas program to find and replace the missing values in a given DataFrame which do not have any valuable information.**

</div>

In [9]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values
0,2023-01-01,1940,163,5,78.77,0.27,287.5105,2,East,Credit Card,...,Male,Books,1.2,Returned,Negative,NaN,nan,4.4,Preferred morning delivery,no_data
1,2023-01-02,1544,117,2,58.21,0.14,100.1212,6,West,Online,...,Female,Books,2.4,Returned,Neutral,12.47,WELCOME5,NaN,unknown,no_data
2,2023-01-03,1205,129,6,23.75,0.14,122.5500,9,West,Credit Card,...,Male,Food,2.6,Not Returned,Negative,14.81,SAVE10,1.5,no_data,value_1
3,2023-01-04,1753,156,7,19.21,0.07,125.0571,2,East,Cash,...,Male,Clothing,4.0,Not Returned,Neutral,17.57,nan,4.7,unknown,no_data
4,2023-01-05,1576,166,2,29.50,0.19,47.7900,1,East,Credit Card,...,Male,Books,3.4,Returned,Positive,18.42,nan,2.4,unknown,value_1
5,2023-01-06,1185,129,2,66.82,0.28,96.2208,7,West,Credit Card,...,Female,Electronics,4.2,Not Returned,Neutral,NaN,nan,NaN,no_data,value_2
6,2023-01-07,1693,124,7,53.31,0.14,320.9262,4,East,Credit Card,...,Female,Electronics,1.7,Not Returned,Negative,15.66,nan,1.8,Used loyalty points,no_data
7,2023-01-08,1220,183,6,79.16,0.09,432.2136,2,South,Online,...,Female,Clothing,2.9,Returned,Positive,17.47,nan,4.8,unknown,value_5
8,2023-01-09,1649,120,3,76.34,0.08,210.6984,5,North,Cash,...,Other,Books,2.8,Returned,Neutral,8.42,FREESHIP,1.5,unknown,unknown
9,2023-01-10,1334,146,1,41.45,0.10,37.3050,9,North,Credit Card,...,Other,Clothing,2.8,Returned,Positive,NaN,FREESHIP,3.2,unknown,value_4
10,2023-01-11,1406,191,4,36.53,0.30,102.2840,5,South,Credit Card,...,Male,Clothing,4.8,Not Returned,Negative,13.37,SAVE10,1.3,Requested gift wrap,value_5
11,2023-01-12,1140,134,1,46.48,0.05,44.1560,7,East,Cash,...,Other,Food,2.5,Not Returned,Positive,8.03,nan,4.3,unknown,value_1
12,2023-01-13,1065,120,3,34.81,0.19,84.5883,7,North,Online,...,Male,Electronics,2.8,Returned,Negative,18.17,FREESHIP,1.9,Frequent buyer,value_4
13,2023-01-14,1785,130,8,49.48,0.14,340.4224,9,North,Credit Card,...,Female,Electronics,4.1,Returned,Neutral,10.07,SAVE10,NaN,no_data,value_5
14,2023-01-15,1393,137,8,10.84,0.21,68.5088,4,South,Cash,...,Female,Food,3.4,Returned,Negative,8.05,SAVE10,2.4,Used loyalty points,value_2
15,2023-01-16,1214,192,2,47.57,0.06,89.4316,3,West,Online,...,Female,Food,3.1,Not Returned,Negative,15.12,nan,4.7,no_data,unknown
16,2023-01-17,1418,101,2,77.46,0.09,140.9772,2,North,Online,...,Female,Books,3.9,Returned,Neutral,15.89,nan,2.7,First-time customer,no_data
17,2023-01-18,1392,178,7,76.03,0.09,484.3111,5,North,Credit Card,...,Male,Clothing,4.2,Not Returned,Negative,16.41,nan,3.8,unknown,unknown
18,2023-01-19,1509,134,9,89.74,0.27,589.5918,2,East,Cash,...,Female,Food,1.8,Not Returned,Neutral,7.95,SAVE10,NaN,no_data,value_3
19,2023-01-20,1697,106,2,76.60,0.24,116.4320,9,South,Online,...,Other,Electronics,1.8,Not Returned,Negative,5.13,nan,NaN,First-time customer,unknown
20,2023-01-21,1795,157,7,80.18,0.26,415.3324,6,North,Cash,...,Male,Clothing,2.9,Not Returned,Positive,16.09,nan,NaN,Used loyalty points,unknown
21,2023-01-22,1330,127,1,69.76,0.26,51.6224,6,North,Credit Card,...,Other,Books,3.7,Returned,Negative,19.59,nan,2.1,First-time customer,no_data
22,2023-01-23,1813,173,1,74.73,0.25,56.0475,9,North,Cash,...,Male,Books,2.8,Not Returned,Negative,17.48,FREESHIP,4.7,no_data,value_2
23,2023-01-24,1175,122,4,14.06,0.27,41.0552,9,West,Credit Card,...,Other,Books,2.0,Returned,Neutral,14.99,FREESHIP,NaN,no_data,value_1
24,2023-01-25,1614,157,1,80.74,0.16,67.8216,9,West,Credit Card,...,Female,Clothing,4.3,Returned,Neutral,5.20,nan,3.1,First-time customer,value_4
25,2023-01-26,1317,111,4,84.56,0.22,263.8272,8,North,Cash,...,Male,Electronics,4.4,Not Returned,Positive,11.14,nan,1.7,no_data,no_data
26,2023-01-27,1198,109,2,76.39,0.04,146.6688,2,West,Credit Card,...,Male,Electronics,3.8,Returned,Neutral,15.98,SAVE10,2.2,no_data,unknown
27,2023-01-28,1801,198,8,84.67,0.29,480.9256,2,West,Cash,...,Male,Clothing,4.2,Returned,Positive,14.90,WELCOME5,2.0,no_data,no_data
28,2023-01-29,1505,175,2,43.67,0.09,79.4794,9,North,Online,...,Female,Clothing,4.3,Not Returned,Negative,6.51,nan,2.5,no_data,value_5
29,2023-01-30,1487,189,6,57.88,0.11,309.0792,5,East,Credit Card,...,Female,Electronics,4.3,Not Returned,Positive,18.95,SAVE10,NaN,no_data,value_2
30,2023-01-31,1932,174,2,69.79,0.25,104.6850,9,North,Online,...,Female,Food,1.7,Returned,Neutral,5.19,SAVE10,NaN,no_data,no_data
31,2023-02-01,1970,140,7,18.65,0.19,105.7455,3,South,Online,...,Other,Electronics,3.5,Not Returned,Negative,18.64,FREESHIP,NaN,Preferred morning delivery,unknown
32,2023-02-02,1288,172,5,50.35,0.10,226.5750,3,East,Credit Card,...,Female,Food,2.8,Returned,Positive,19.15,nan,1.2,Frequent buyer,unknown
33,2023-02-03,1987,154,2,51.92,0.23,79.9568,8,East,Online,...,Female,Food,4.9,Not Returned,Negative,8.38,FREESHIP,NaN,unknown,no_data
34,2023-02-04,1771,120,6,33.02,0.23,152.5524,3,West,Online,...,Other,Clothing,2.1,Not Returned,Positive,18.33,nan,4.4,no_data,unknown

<div class="alert alert-success">

**Solution 04:**
</div>

In [10]:
df.replace({
    'customer_note': {
        'no_data': np.nan,
        'unknown': np.nan
    },
    'customer_values': {
        'no_data': np.nan,
        'unknown': np.nan
    }
}, inplace=True)

display(df.isna().any())
display(df.isna().sum())

date                False
customer_id         False
product_id          False
quantity            False
price               False
discount            False
revenue             False
store_id            False
region              False
payment_method      False
is_member           False
delivery_days       False
customer_age        False
gender              False
product_category    False
rating              False
return_status       False
feedback            False
shipping_cost        True
coupon_code         False
delivery_rating      True
customer_note        True
customer_values      True
dtype: bool

date                 0
customer_id          0
product_id           0
quantity             0
price                0
discount             0
revenue              0
store_id             0
region               0
payment_method       0
is_member            0
delivery_days        0
customer_age         0
gender               0
product_category     0
rating               0
return_status        0
feedback             0
shipping_cost        3
coupon_code          0
delivery_rating     11
customer_note       23
customer_values     19
dtype: int64