[Pandas Missing Values](https://www.w3resource.com/python-exercises/pandas/missing-values/index.php)

In [1]:
import pandas as pd
import numpy as np

<div class="alert alert-warning">

**1. Detect Missing Values**

**Write a Pandas program to detect missing values of a given DataFrame. Display True or False.**

</div>

In [2]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1727,192,7,78.87,0.15,469.2765,9,North,Credit Card,...,2,66,Male,Food,1.7,Not Returned,Neutral,7.90,nan,1.1
1,2023-01-02,1689,193,1,88.63,0.26,65.5862,4,West,Online,...,1,67,Male,Food,3.8,Returned,Positive,17.52,nan,1.1
2,2023-01-03,1882,114,7,59.77,0.29,297.0569,2,East,Credit Card,...,4,67,Other,Food,1.3,Not Returned,Positive,14.87,FREESHIP,NaN
3,2023-01-04,1156,101,3,73.25,0.17,182.3925,1,West,Cash,...,4,28,Male,Books,3.1,Returned,Neutral,6.43,nan,2.3
4,2023-01-05,1529,179,2,53.58,0.13,93.2292,8,East,Cash,...,5,20,Other,Electronics,4.0,Not Returned,Neutral,14.25,nan,2.0
5,2023-01-06,1237,110,5,35.48,0.16,149.0160,3,East,Online,...,6,24,Other,Books,4.5,Returned,Neutral,19.28,FREESHIP,NaN
6,2023-01-07,1017,131,5,75.60,0.25,283.5000,9,North,Online,...,1,58,Female,Clothing,4.2,Not Returned,Negative,NaN,nan,NaN
7,2023-01-08,1437,109,6,91.08,0.24,415.3248,3,West,Online,...,2,27,Other,Books,4.0,Not Returned,Positive,9.34,nan,NaN
8,2023-01-09,1862,141,5,15.29,0.30,53.5150,2,East,Credit Card,...,4,64,Other,Clothing,4.1,Not Returned,Neutral,NaN,FREESHIP,1.1
9,2023-01-10,1476,177,9,66.01,0.07,552.5037,1,East,Cash,...,3,26,Female,Food,2.9,Returned,Positive,18.53,WELCOME5,4.5
10,2023-01-11,1871,133,3,13.30,0.27,29.1270,8,South,Online,...,5,25,Female,Electronics,2.2,Returned,Neutral,6.50,FREESHIP,NaN
11,2023-01-12,1563,135,3,43.14,0.20,103.5360,8,West,Online,...,5,48,Other,Electronics,3.6,Not Returned,Neutral,7.07,nan,2.2
12,2023-01-13,1336,195,4,60.93,0.25,182.7900,1,South,Cash,...,5,50,Other,Food,4.1,Not Returned,Negative,NaN,nan,4.6
13,2023-01-14,1637,163,5,44.83,0.20,179.3200,6,North,Cash,...,2,38,Male,Food,1.0,Not Returned,Positive,6.19,nan,4.7
14,2023-01-15,1764,187,9,95.09,0.21,676.0899,6,South,Cash,...,3,46,Other,Food,4.4,Not Returned,Neutral,9.43,SAVE10,4.6
15,2023-01-16,1813,137,6,83.92,0.20,402.8160,2,West,Online,...,2,57,Male,Food,2.1,Not Returned,Negative,5.42,nan,4.6
16,2023-01-17,1549,187,1,29.27,0.27,21.3671,3,North,Cash,...,1,65,Other,Electronics,4.8,Returned,Neutral,8.62,nan,1.9
17,2023-01-18,1317,136,1,27.92,0.12,24.5696,8,West,Cash,...,2,60,Other,Electronics,2.9,Not Returned,Neutral,19.57,nan,1.3
18,2023-01-19,1531,178,8,15.18,0.07,112.9392,2,South,Credit Card,...,1,37,Male,Clothing,2.9,Not Returned,Neutral,15.36,WELCOME5,NaN
19,2023-01-20,1038,129,4,99.36,0.27,290.1312,6,West,Credit Card,...,3,37,Male,Electronics,4.4,Not Returned,Positive,5.33,nan,2.9
20,2023-01-21,1207,122,5,56.20,0.22,219.1800,1,South,Online,...,3,24,Female,Electronics,4.1,Not Returned,Positive,19.73,WELCOME5,NaN
21,2023-01-22,1724,150,6,65.92,0.01,391.5648,8,West,Credit Card,...,3,53,Female,Clothing,2.4,Not Returned,Negative,14.53,nan,2.0
22,2023-01-23,1974,163,7,67.73,0.29,336.6181,7,East,Credit Card,...,4,22,Female,Books,3.9,Not Returned,Negative,7.53,SAVE10,2.9
23,2023-01-24,1008,179,1,21.33,0.26,15.7842,7,East,Cash,...,4,26,Other,Books,1.9,Returned,Negative,NaN,nan,3.6
24,2023-01-25,1781,158,9,92.25,0.03,805.3425,5,North,Cash,...,1,20,Male,Books,2.3,Not Returned,Neutral,6.89,WELCOME5,4.1
25,2023-01-26,1475,102,9,20.04,0.28,129.8592,5,North,Online,...,3,42,Other,Food,2.9,Not Returned,Positive,12.68,nan,NaN
26,2023-01-27,1872,121,2,44.33,0.03,86.0002,9,West,Credit Card,...,6,67,Female,Electronics,3.3,Returned,Neutral,19.39,WELCOME5,2.1
27,2023-01-28,1620,128,8,52.40,0.07,389.8560,8,South,Credit Card,...,2,19,Male,Books,4.0,Not Returned,Neutral,NaN,WELCOME5,2.4
28,2023-01-29,1104,129,4,55.64,0.04,213.6576,8,South,Cash,...,3,21,Other,Clothing,3.3,Not Returned,Negative,9.30,SAVE10,3.7
29,2023-01-30,1807,128,4,81.98,0.18,268.8944,9,West,Online,...,3,68,Male,Books,4.1,Returned,Neutral,8.53,nan,3.3
30,2023-01-31,1409,191,7,25.44,0.01,176.2992,8,East,Credit Card,...,3,38,Female,Food,4.8,Returned,Negative,13.89,WELCOME5,NaN
31,2023-02-01,1148,141,8,67.05,0.21,423.7560,1,North,Credit Card,...,3,23,Other,Books,3.9,Not Returned,Neutral,10.31,SAVE10,1.3
32,2023-02-02,1492,154,4,48.06,0.08,176.8608,5,North,Credit Card,...,4,59,Other,Food,1.1,Returned,Neutral,15.33,nan,NaN
33,2023-02-03,1509,109,9,10.74,0.23,74.4282,3,East,Online,...,5,46,Male,Electronics,3.9,Not Returned,Neutral,7.95,SAVE10,NaN
34,2023-02-04,1604,129,8,41.59,0.23,256.1944,5,North,Online,...,6,27,Female,Electronics,1.2,Returned,Negative,14.24,FREESHIP,3.4

<div class="alert alert-success">

**Solution 01:**
</div>

In [3]:
print(type(df.isna()))
df.isna()

<class 'pandas.core.frame.DataFrame'>

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
31,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
33,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
34,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [4]:
print(df.isna().any())  
df.isna().sum()

date                False
customer_id         False
product_id          False
quantity            False
price               False
discount            False
revenue             False
store_id            False
region              False
payment_method      False
is_member           False
delivery_days       False
customer_age        False
gender              False
product_category    False
rating              False
return_status       False
feedback            False
shipping_cost        True
coupon_code         False
delivery_rating      True
dtype: bool

date                 0
customer_id          0
product_id           0
quantity             0
price                0
discount             0
revenue              0
store_id             0
region               0
payment_method       0
is_member            0
delivery_days        0
customer_age         0
gender               0
product_category     0
rating               0
return_status        0
feedback             0
shipping_cost        5
coupon_code          0
delivery_rating     11
dtype: int64

<div class="alert alert-warning">

**2. Identify Columns with Missing Values**

**Write a Pandas program to identify the column(s) of a given DataFrame which have at least one missing value.**

</div>

In [5]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1490,189,5,84.21,0.07,391.5765,7,North,Credit Card,...,5,64,Other,Electronics,2.2,Not Returned,Neutral,19.58,SAVE10,4.4
1,2023-01-02,1432,195,1,58.68,0.02,57.5064,3,South,Cash,...,3,56,Male,Books,2.4,Returned,Negative,8.45,nan,4.5
2,2023-01-03,1746,192,9,80.06,0.15,612.4590,4,East,Cash,...,4,21,Other,Electronics,1.8,Returned,Negative,8.56,SAVE10,1.4
3,2023-01-04,1074,193,6,48.76,0.05,277.9320,9,North,Online,...,1,56,Female,Books,3.1,Returned,Negative,10.52,nan,2.5
4,2023-01-05,1751,116,4,92.45,0.21,292.1420,8,South,Credit Card,...,1,62,Male,Food,4.9,Returned,Neutral,15.25,WELCOME5,1.9
5,2023-01-06,1437,184,9,61.19,0.09,501.1461,6,West,Cash,...,4,23,Other,Books,3.9,Not Returned,Positive,8.98,nan,NaN
6,2023-01-07,1161,136,9,28.06,0.01,250.0146,5,North,Credit Card,...,6,22,Male,Food,4.0,Returned,Negative,9.28,nan,4.2
7,2023-01-08,1568,152,3,99.39,0.06,280.2798,4,North,Credit Card,...,5,61,Female,Clothing,4.1,Not Returned,Positive,5.43,FREESHIP,3.1
8,2023-01-09,1092,135,6,38.16,0.27,167.1408,7,West,Credit Card,...,3,55,Other,Books,3.0,Not Returned,Negative,NaN,SAVE10,4.5
9,2023-01-10,1671,118,9,24.44,0.07,204.5628,3,South,Cash,...,6,54,Male,Electronics,3.7,Not Returned,Neutral,14.47,nan,1.1
10,2023-01-11,1407,157,1,82.57,0.26,61.1018,6,South,Credit Card,...,3,21,Male,Books,2.3,Not Returned,Neutral,5.17,FREESHIP,4.1
11,2023-01-12,1985,179,8,93.41,0.25,560.4600,3,West,Online,...,4,27,Female,Food,2.8,Not Returned,Positive,5.34,WELCOME5,3.2
12,2023-01-13,1035,120,4,33.63,0.13,117.0324,7,South,Credit Card,...,6,35,Male,Electronics,1.2,Returned,Neutral,6.25,SAVE10,2.0
13,2023-01-14,1786,157,4,53.08,0.11,188.9648,5,North,Cash,...,2,20,Female,Food,4.3,Not Returned,Negative,NaN,FREESHIP,NaN
14,2023-01-15,1528,124,7,92.96,0.11,579.1408,7,West,Credit Card,...,3,21,Male,Food,1.8,Returned,Neutral,11.25,nan,3.3
15,2023-01-16,1896,191,5,15.29,0.11,68.0405,2,West,Credit Card,...,6,69,Male,Electronics,1.1,Returned,Negative,14.48,WELCOME5,NaN
16,2023-01-17,1375,174,3,90.22,0.03,262.5402,7,North,Credit Card,...,1,41,Other,Food,2.3,Returned,Negative,18.26,WELCOME5,3.7
17,2023-01-18,1521,152,5,60.24,0.11,268.0680,6,South,Credit Card,...,6,68,Other,Electronics,3.0,Returned,Neutral,9.31,nan,NaN
18,2023-01-19,1436,166,9,55.63,0.28,360.4824,9,West,Online,...,4,41,Female,Books,4.8,Returned,Positive,NaN,SAVE10,4.2
19,2023-01-20,1306,141,9,19.07,0.24,130.4388,3,North,Cash,...,2,65,Female,Books,3.8,Returned,Negative,11.49,WELCOME5,1.2
20,2023-01-21,1872,194,1,82.45,0.25,61.8375,9,South,Cash,...,6,54,Male,Clothing,3.8,Not Returned,Neutral,9.31,nan,NaN
21,2023-01-22,1834,196,2,36.79,0.21,58.1282,7,South,Credit Card,...,3,49,Female,Food,4.6,Not Returned,Positive,NaN,FREESHIP,NaN
22,2023-01-23,1064,109,5,86.36,0.04,414.5280,4,South,Cash,...,2,30,Male,Electronics,1.8,Not Returned,Negative,NaN,WELCOME5,3.8
23,2023-01-24,1179,112,5,52.11,0.22,203.2290,6,West,Online,...,1,57,Male,Electronics,3.7,Returned,Positive,13.63,WELCOME5,3.3
24,2023-01-25,1943,115,7,32.47,0.19,184.1049,5,West,Cash,...,1,41,Female,Clothing,1.5,Not Returned,Positive,15.67,SAVE10,NaN
25,2023-01-26,1476,140,4,67.00,0.05,254.6000,9,North,Credit Card,...,3,57,Male,Clothing,2.3,Returned,Positive,12.93,FREESHIP,1.8
26,2023-01-27,1206,132,5,21.61,0.13,94.0035,8,South,Online,...,6,37,Female,Electronics,2.7,Returned,Positive,8.43,WELCOME5,NaN
27,2023-01-28,1082,185,3,65.95,0.10,178.0650,7,South,Cash,...,1,46,Male,Electronics,2.0,Returned,Neutral,16.79,WELCOME5,3.1
28,2023-01-29,1263,106,1,85.11,0.02,83.4078,5,West,Credit Card,...,3,25,Other,Electronics,4.6,Returned,Positive,NaN,nan,NaN
29,2023-01-30,1769,108,5,17.66,0.02,86.5340,9,South,Cash,...,5,61,Other,Clothing,4.2,Returned,Negative,18.50,WELCOME5,NaN
30,2023-01-31,1017,169,1,94.26,0.13,82.0062,5,North,Credit Card,...,1,65,Other,Clothing,1.3,Returned,Negative,16.20,FREESHIP,NaN
31,2023-02-01,1706,188,2,88.68,0.11,157.8504,3,West,Cash,...,2,65,Female,Electronics,4.3,Not Returned,Neutral,7.18,SAVE10,1.0
32,2023-02-02,1554,149,9,23.81,0.10,192.8610,6,North,Credit Card,...,4,56,Male,Food,2.4,Not Returned,Negative,5.09,WELCOME5,3.5
33,2023-02-03,1473,157,4,35.17,0.29,99.8828,3,South,Online,...,4,25,Female,Food,1.2,Returned,Positive,6.50,nan,NaN
34,2023-02-04,1617,116,2,91.23,0.27,133.1958,2,West,Cash,...,2,64,Female,Clothing,3.6,Returned,Neutral,NaN,nan,NaN

<div class="alert alert-success">

**Solution 02:**
</div>

In [6]:
df.isna().any()
cols_have_na = df.isna().any()[lambda x: x].index.tolist()

<div class="alert alert-warning">

**3. Count Missing Values in Each Column**

**Write a Pandas program to count the number of missing values in each column of a given DataFrame.**

</div>

In [7]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1655,133,3,58.20,0.24,132.6960,6,North,Cash,...,4,42,Female,Food,1.5,Returned,Negative,8.78,nan,NaN
1,2023-01-02,1912,182,2,19.54,0.05,37.1260,9,South,Cash,...,3,56,Other,Electronics,4.6,Not Returned,Negative,6.70,WELCOME5,1.4
2,2023-01-03,1649,155,2,35.27,0.26,52.1996,6,North,Cash,...,2,33,Other,Books,2.3,Not Returned,Neutral,9.72,nan,4.3
3,2023-01-04,1495,166,8,33.00,0.03,256.0800,5,North,Cash,...,6,63,Other,Books,1.8,Not Returned,Negative,19.91,WELCOME5,3.5
4,2023-01-05,1093,125,6,58.51,0.02,344.0388,7,West,Cash,...,2,59,Male,Electronics,1.6,Not Returned,Negative,8.81,FREESHIP,2.1
5,2023-01-06,1533,189,1,73.99,0.29,52.5329,1,South,Credit Card,...,5,28,Other,Clothing,2.7,Not Returned,Negative,18.94,nan,4.3
6,2023-01-07,1887,154,2,52.74,0.05,100.2060,7,North,Cash,...,6,25,Male,Electronics,4.4,Returned,Positive,7.08,FREESHIP,2.1
7,2023-01-08,1721,127,7,69.64,0.17,404.6084,1,North,Cash,...,6,41,Female,Food,4.0,Not Returned,Negative,15.64,SAVE10,NaN
8,2023-01-09,1528,114,9,89.32,0.07,747.6084,2,East,Online,...,1,41,Female,Clothing,3.9,Not Returned,Negative,15.71,nan,4.0
9,2023-01-10,1246,137,5,52.35,0.01,259.1325,7,East,Online,...,4,58,Male,Electronics,2.2,Returned,Positive,11.33,FREESHIP,4.8
10,2023-01-11,1070,150,4,75.24,0.09,273.8736,9,West,Online,...,6,55,Male,Electronics,3.9,Not Returned,Neutral,17.01,SAVE10,NaN
11,2023-01-12,1754,194,8,77.77,0.10,559.9440,7,West,Online,...,3,35,Female,Clothing,1.5,Returned,Negative,NaN,SAVE10,NaN
12,2023-01-13,1650,157,1,78.88,0.25,59.1600,1,North,Credit Card,...,4,68,Female,Clothing,4.9,Not Returned,Neutral,NaN,nan,NaN
13,2023-01-14,1763,196,6,65.71,0.07,366.6618,6,West,Cash,...,4,24,Male,Food,3.8,Returned,Positive,12.12,nan,NaN
14,2023-01-15,1478,147,3,15.29,0.18,37.6134,4,South,Online,...,4,20,Male,Electronics,1.3,Returned,Negative,NaN,nan,2.2
15,2023-01-16,1916,113,8,17.00,0.04,130.5600,5,East,Cash,...,1,24,Other,Books,3.2,Not Returned,Negative,5.27,WELCOME5,1.6
16,2023-01-17,1956,181,7,61.11,0.28,307.9944,5,East,Cash,...,5,29,Other,Electronics,3.8,Not Returned,Negative,14.03,nan,NaN
17,2023-01-18,1697,110,2,56.70,0.02,111.1320,5,South,Cash,...,6,21,Female,Electronics,3.8,Not Returned,Negative,18.00,nan,1.3
18,2023-01-19,1644,191,4,34.04,0.08,125.2672,5,South,Cash,...,1,38,Male,Clothing,2.7,Not Returned,Positive,8.72,SAVE10,4.2
19,2023-01-20,1823,175,2,36.84,0.26,54.5232,9,West,Online,...,6,40,Female,Food,3.6,Returned,Positive,NaN,WELCOME5,NaN
20,2023-01-21,1372,159,5,73.11,0.16,307.0620,8,West,Cash,...,5,22,Other,Clothing,2.9,Returned,Neutral,10.84,WELCOME5,NaN
21,2023-01-22,1039,144,8,69.19,0.17,459.4216,4,South,Cash,...,3,22,Female,Electronics,1.3,Returned,Positive,13.83,nan,NaN
22,2023-01-23,1262,183,1,39.72,0.01,39.3228,1,North,Cash,...,1,34,Female,Electronics,1.5,Returned,Positive,5.36,nan,3.8
23,2023-01-24,1884,104,6,82.52,0.23,381.2424,8,South,Cash,...,6,52,Male,Clothing,4.3,Not Returned,Neutral,10.37,FREESHIP,1.4
24,2023-01-25,1200,156,9,85.65,0.04,740.0160,9,North,Credit Card,...,6,21,Male,Clothing,3.4,Returned,Neutral,10.51,WELCOME5,2.7
25,2023-01-26,1934,187,9,66.97,0.09,548.4843,3,South,Cash,...,6,22,Male,Food,4.5,Not Returned,Neutral,14.17,nan,2.9
26,2023-01-27,1391,110,8,50.99,0.28,293.7024,4,North,Credit Card,...,6,45,Female,Books,1.4,Returned,Neutral,6.11,SAVE10,4.1
27,2023-01-28,1871,188,9,49.22,0.21,349.9542,5,North,Online,...,4,21,Male,Electronics,2.0,Returned,Positive,8.41,nan,1.3
28,2023-01-29,1294,113,1,32.84,0.23,25.2868,8,East,Credit Card,...,4,31,Other,Electronics,4.6,Not Returned,Positive,5.36,WELCOME5,1.9
29,2023-01-30,1336,149,7,69.55,0.00,486.8500,8,East,Credit Card,...,4,18,Other,Clothing,2.9,Not Returned,Neutral,17.09,SAVE10,NaN
30,2023-01-31,1611,113,5,59.59,0.06,280.0730,5,South,Online,...,6,53,Other,Clothing,2.3,Not Returned,Negative,10.53,SAVE10,3.4
31,2023-02-01,1503,181,8,93.33,0.06,701.8416,2,East,Credit Card,...,6,19,Female,Food,2.3,Not Returned,Negative,NaN,nan,4.1
32,2023-02-02,1207,157,5,69.27,0.21,273.6165,6,West,Credit Card,...,2,19,Male,Books,4.2,Not Returned,Negative,7.05,SAVE10,2.3
33,2023-02-03,1685,131,3,55.38,0.28,119.6208,7,East,Cash,...,4,39,Female,Electronics,3.3,Returned,Negative,NaN,FREESHIP,NaN
34,2023-02-04,1379,179,5,91.57,0.27,334.2305,2,South,Credit Card,...,5,44,Other,Clothing,3.8,Returned,Neutral,NaN,nan,4.2

<div class="alert alert-success">

**Solution 03:**
</div>

In [8]:
df.isna().sum()

date                 0
customer_id          0
product_id           0
quantity             0
price                0
discount             0
revenue              0
store_id             0
region               0
payment_method       0
is_member            0
delivery_days        0
customer_age         0
gender               0
product_category     0
rating               0
return_status        0
feedback             0
shipping_cost        7
coupon_code          0
delivery_rating     12
dtype: int64

<div class="alert alert-warning">

**4. Replace Non-Valuable Missing Values**

**Write a Pandas program to find and replace the missing values in a given DataFrame which do not have any valuable information.**

</div>

In [9]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values
0,2023-01-01,1107,148,2,82.40,0.22,128.5440,8,East,Online,...,Female,Books,4.8,Returned,Neutral,7.88,nan,2.0,unknown,unknown
1,2023-01-02,1426,183,4,34.85,0.15,118.4900,6,West,Online,...,Other,Food,2.7,Returned,Neutral,12.87,nan,NaN,no_data,unknown
2,2023-01-03,1652,166,2,56.65,0.04,108.7680,3,East,Cash,...,Male,Books,2.6,Returned,Negative,7.79,nan,NaN,Frequent buyer,unknown
3,2023-01-04,1848,106,4,69.78,0.13,242.8344,8,East,Credit Card,...,Other,Books,1.9,Not Returned,Positive,5.24,WELCOME5,3.2,Used loyalty points,unknown
4,2023-01-05,1167,198,6,77.48,0.21,367.2552,5,North,Online,...,Male,Clothing,1.6,Returned,Negative,19.75,nan,4.7,no_data,value_1
5,2023-01-06,1314,170,2,73.73,0.02,144.5108,8,West,Cash,...,Male,Electronics,3.6,Not Returned,Negative,14.69,nan,4.3,unknown,value_1
6,2023-01-07,1093,192,5,17.36,0.26,64.2320,2,South,Cash,...,Other,Electronics,3.6,Returned,Positive,5.93,nan,1.5,no_data,no_data
7,2023-01-08,1320,160,8,97.10,0.08,714.6560,5,North,Cash,...,Other,Books,2.8,Not Returned,Positive,18.75,WELCOME5,NaN,Preferred morning delivery,no_data
8,2023-01-09,1702,195,7,56.74,0.01,393.2082,1,South,Credit Card,...,Male,Clothing,2.0,Not Returned,Neutral,NaN,FREESHIP,2.6,Used loyalty points,no_data
9,2023-01-10,1921,163,1,55.18,0.23,42.4886,1,South,Credit Card,...,Other,Food,4.9,Not Returned,Positive,10.09,SAVE10,4.7,Requested gift wrap,no_data
10,2023-01-11,1133,141,8,15.74,0.27,91.9216,2,South,Credit Card,...,Male,Food,1.1,Returned,Neutral,15.16,WELCOME5,5.0,no_data,value_5
11,2023-01-12,1425,155,7,21.98,0.11,136.9354,2,North,Online,...,Other,Clothing,2.1,Not Returned,Negative,16.17,nan,3.4,no_data,value_2
12,2023-01-13,1263,166,9,73.11,0.21,519.8121,8,West,Cash,...,Male,Food,3.9,Returned,Negative,11.49,FREESHIP,NaN,Preferred morning delivery,no_data
13,2023-01-14,1217,103,9,87.93,0.06,743.8878,2,South,Cash,...,Other,Clothing,3.8,Not Returned,Negative,16.69,WELCOME5,NaN,Requested gift wrap,unknown
14,2023-01-15,1069,111,6,12.40,0.25,55.8000,2,South,Cash,...,Female,Books,3.9,Not Returned,Positive,15.57,nan,4.3,unknown,value_5
15,2023-01-16,1282,120,5,17.19,0.03,83.3715,5,South,Online,...,Female,Electronics,1.3,Returned,Positive,13.13,nan,2.9,unknown,value_1
16,2023-01-17,1163,128,8,56.42,0.07,419.7648,1,North,Online,...,Other,Electronics,4.4,Returned,Negative,8.30,FREESHIP,NaN,no_data,unknown
17,2023-01-18,1059,196,8,17.64,0.27,103.0176,9,South,Cash,...,Female,Food,1.4,Not Returned,Negative,NaN,WELCOME5,NaN,no_data,value_3
18,2023-01-19,1828,103,5,35.94,0.16,150.9480,3,South,Cash,...,Male,Food,4.5,Not Returned,Positive,13.08,nan,3.9,unknown,no_data
19,2023-01-20,1542,111,3,41.97,0.22,98.2098,5,West,Credit Card,...,Male,Food,1.9,Returned,Negative,18.40,nan,1.5,Requested gift wrap,no_data
20,2023-01-21,1431,119,7,71.36,0.09,454.5632,1,West,Credit Card,...,Female,Electronics,3.6,Returned,Neutral,NaN,nan,4.8,no_data,value_4
21,2023-01-22,1546,124,7,48.52,0.04,326.0544,9,East,Credit Card,...,Female,Clothing,2.5,Returned,Negative,11.77,WELCOME5,1.2,First-time customer,unknown
22,2023-01-23,1524,109,4,58.72,0.02,230.1824,4,East,Cash,...,Other,Food,4.8,Returned,Neutral,17.38,nan,2.7,no_data,value_2
23,2023-01-24,1268,146,2,86.03,0.01,170.3394,1,North,Credit Card,...,Male,Electronics,3.3,Not Returned,Positive,14.04,SAVE10,4.9,unknown,unknown
24,2023-01-25,1566,110,3,81.83,0.21,193.9371,3,North,Cash,...,Male,Electronics,4.3,Not Returned,Neutral,NaN,nan,NaN,Requested gift wrap,value_2
25,2023-01-26,1636,193,7,94.78,0.13,577.2102,4,North,Cash,...,Other,Clothing,2.1,Not Returned,Positive,12.94,nan,NaN,Frequent buyer,value_4
26,2023-01-27,1309,130,1,91.61,0.24,69.6236,3,West,Cash,...,Other,Books,4.6,Returned,Neutral,15.62,SAVE10,NaN,Requested gift wrap,unknown
27,2023-01-28,1387,154,5,56.84,0.03,275.6740,6,North,Cash,...,Other,Food,3.0,Not Returned,Negative,16.61,nan,NaN,no_data,unknown
28,2023-01-29,1497,134,3,25.42,0.24,57.9576,7,North,Credit Card,...,Female,Electronics,4.6,Not Returned,Neutral,10.24,WELCOME5,NaN,First-time customer,value_4
29,2023-01-30,1768,109,7,33.43,0.29,166.1471,7,East,Credit Card,...,Female,Books,1.1,Returned,Positive,13.43,WELCOME5,2.2,Used loyalty points,value_3
30,2023-01-31,1768,183,4,34.95,0.14,120.2280,4,West,Online,...,Male,Books,2.4,Returned,Negative,14.52,nan,2.1,Frequent buyer,unknown
31,2023-02-01,1684,148,5,23.62,0.05,112.1950,9,North,Credit Card,...,Female,Food,3.0,Not Returned,Neutral,11.35,FREESHIP,NaN,no_data,no_data
32,2023-02-02,1149,137,7,12.90,0.22,70.4340,9,North,Online,...,Other,Clothing,3.8,Returned,Negative,16.05,SAVE10,4.0,Used loyalty points,value_3
33,2023-02-03,1144,121,7,72.83,0.02,499.6138,9,West,Cash,...,Male,Books,2.0,Not Returned,Neutral,NaN,nan,4.5,unknown,no_data
34,2023-02-04,1853,138,4,73.77,0.28,212.4576,5,North,Online,...,Female,Clothing,2.4,Returned,Positive,13.79,WELCOME5,4.5,First-time customer,value_5

<div class="alert alert-success">

**Solution 04:**
</div>

In [10]:
df.replace({
    'customer_note': {
        'no_data': np.nan,
        'unknown': np.nan
    },
    'customer_values': {
        'no_data': np.nan,
        'unknown': np.nan
    }
}, inplace=True)

display(df.isna().any())
display(df.isna().sum())

date                False
customer_id         False
product_id          False
quantity            False
price               False
discount            False
revenue             False
store_id            False
region              False
payment_method      False
is_member           False
delivery_days       False
customer_age        False
gender              False
product_category    False
rating              False
return_status       False
feedback            False
shipping_cost        True
coupon_code         False
delivery_rating      True
customer_note        True
customer_values      True
dtype: bool

date                 0
customer_id          0
product_id           0
quantity             0
price                0
discount             0
revenue              0
store_id             0
region               0
payment_method       0
is_member            0
delivery_days        0
customer_age         0
gender               0
product_category     0
rating               0
return_status        0
feedback             0
shipping_cost        5
coupon_code          0
delivery_rating     13
customer_note       18
customer_values     20
dtype: int64

<div class="alert alert-warning">

**5. Drop Rows with Any Missing Value**

**Write a Pandas program to drop the rows where at least one element is missing in a given DataFrame.**

</div>

In [11]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values
0,2023-01-01,1423,169,6,34.37,0.25,154.6650,6,North,Online,...,Female,Electronics,1.3,Returned,Negative,18.08,nan,NaN,no_data,value_4
1,2023-01-02,1709,122,5,23.10,0.01,114.3450,5,North,Cash,...,Female,Clothing,4.4,Returned,Neutral,8.54,nan,2.5,First-time customer,no_data
2,2023-01-03,1850,159,9,57.29,0.25,386.7075,9,East,Cash,...,Male,Clothing,4.0,Not Returned,Negative,NaN,nan,NaN,no_data,no_data
3,2023-01-04,1139,143,5,56.64,0.27,206.7360,6,East,Cash,...,Male,Electronics,2.1,Not Returned,Negative,17.56,nan,2.9,no_data,value_5
4,2023-01-05,1742,101,9,46.04,0.16,348.0624,6,East,Credit Card,...,Female,Electronics,3.3,Returned,Negative,5.58,SAVE10,2.3,Preferred morning delivery,no_data
5,2023-01-06,1396,164,2,47.65,0.05,90.5350,1,West,Credit Card,...,Male,Books,3.8,Returned,Positive,6.21,nan,NaN,unknown,value_2
6,2023-01-07,1590,133,6,99.93,0.09,545.6178,5,South,Online,...,Female,Clothing,2.5,Not Returned,Negative,9.98,SAVE10,3.6,no_data,value_4
7,2023-01-08,1675,101,6,77.90,0.12,411.3120,6,West,Credit Card,...,Male,Food,4.2,Returned,Negative,5.43,FREESHIP,4.9,no_data,no_data
8,2023-01-09,1118,170,8,12.77,0.17,84.7928,2,West,Online,...,Other,Electronics,1.9,Returned,Positive,16.80,SAVE10,NaN,Used loyalty points,value_4
9,2023-01-10,1629,170,4,47.99,0.25,143.9700,9,North,Cash,...,Other,Food,4.5,Returned,Negative,18.19,nan,3.8,no_data,value_5
10,2023-01-11,1557,119,1,39.90,0.10,35.9100,8,West,Online,...,Male,Electronics,4.3,Returned,Negative,NaN,SAVE10,1.5,no_data,value_4
11,2023-01-12,1517,116,2,95.07,0.27,138.8022,4,East,Cash,...,Female,Electronics,2.7,Not Returned,Negative,18.61,SAVE10,2.0,Requested gift wrap,unknown
12,2023-01-13,1881,134,3,66.76,0.16,168.2352,5,North,Credit Card,...,Female,Clothing,4.2,Not Returned,Neutral,12.28,nan,NaN,Frequent buyer,unknown
13,2023-01-14,1110,104,3,91.37,0.28,197.3592,1,East,Cash,...,Male,Electronics,2.1,Returned,Neutral,NaN,SAVE10,NaN,no_data,value_3
14,2023-01-15,1254,185,8,72.61,0.09,528.6008,8,South,Online,...,Other,Books,3.1,Not Returned,Positive,15.57,SAVE10,5.0,Preferred morning delivery,no_data
15,2023-01-16,1993,132,8,99.03,0.30,554.5680,8,East,Online,...,Male,Clothing,2.8,Returned,Neutral,11.53,nan,1.4,unknown,unknown
16,2023-01-17,1292,107,3,71.48,0.15,182.2740,9,West,Credit Card,...,Other,Electronics,2.1,Not Returned,Positive,9.37,FREESHIP,4.1,unknown,unknown
17,2023-01-18,1148,104,8,23.83,0.22,148.6992,1,North,Online,...,Female,Clothing,1.9,Returned,Positive,14.57,nan,4.7,unknown,no_data
18,2023-01-19,1546,113,1,53.49,0.17,44.3967,2,South,Credit Card,...,Female,Food,4.8,Returned,Positive,NaN,SAVE10,1.8,Preferred morning delivery,unknown
19,2023-01-20,1150,198,9,36.59,0.06,309.5514,5,North,Credit Card,...,Male,Clothing,2.1,Returned,Positive,17.09,WELCOME5,3.1,Used loyalty points,value_5
20,2023-01-21,1001,170,3,79.06,0.23,182.6286,4,East,Online,...,Other,Books,1.6,Returned,Negative,14.06,SAVE10,NaN,First-time customer,unknown
21,2023-01-22,1854,144,2,66.33,0.10,119.3940,4,North,Credit Card,...,Other,Clothing,3.1,Not Returned,Negative,6.42,SAVE10,2.1,Used loyalty points,value_1
22,2023-01-23,1384,115,7,62.61,0.11,390.0603,2,North,Online,...,Male,Books,4.1,Returned,Negative,14.79,WELCOME5,1.2,Frequent buyer,value_3
23,2023-01-24,1113,119,2,84.05,0.08,154.6520,1,North,Cash,...,Female,Books,2.7,Returned,Positive,9.21,nan,2.7,Used loyalty points,no_data
24,2023-01-25,1073,112,8,47.39,0.04,363.9552,7,North,Credit Card,...,Female,Food,4.3,Not Returned,Neutral,NaN,nan,1.7,Frequent buyer,no_data
25,2023-01-26,1914,103,3,31.49,0.25,70.8525,4,West,Cash,...,Male,Clothing,1.1,Not Returned,Negative,17.99,FREESHIP,3.9,Preferred morning delivery,no_data
26,2023-01-27,1148,191,1,24.45,0.03,23.7165,9,South,Credit Card,...,Female,Electronics,4.5,Not Returned,Positive,17.95,FREESHIP,4.7,First-time customer,no_data
27,2023-01-28,1305,101,8,85.42,0.27,498.8528,7,South,Cash,...,Female,Clothing,3.5,Returned,Positive,18.45,FREESHIP,1.2,First-time customer,no_data
28,2023-01-29,1878,132,1,87.65,0.02,85.8970,9,North,Online,...,Female,Books,4.9,Not Returned,Neutral,NaN,nan,1.6,unknown,value_1
29,2023-01-30,1642,172,9,61.19,0.13,479.1177,5,North,Online,...,Male,Electronics,4.9,Returned,Negative,7.19,SAVE10,2.7,no_data,no_data
30,2023-01-31,1035,176,5,62.84,0.15,267.0700,8,West,Credit Card,...,Female,Electronics,1.2,Returned,Negative,NaN,nan,3.1,no_data,value_5
31,2023-02-01,1271,138,4,32.48,0.03,126.0224,5,West,Online,...,Male,Food,2.7,Returned,Neutral,11.50,FREESHIP,NaN,Requested gift wrap,value_3
32,2023-02-02,1673,169,8,57.71,0.24,350.8768,9,North,Online,...,Female,Electronics,3.8,Returned,Negative,17.59,SAVE10,2.4,unknown,value_4
33,2023-02-03,1540,121,3,27.34,0.03,79.5594,6,East,Cash,...,Male,Books,1.3,Returned,Positive,19.19,FREESHIP,NaN,Preferred morning delivery,value_4
34,2023-02-04,1758,175,1,91.73,0.09,83.4743,6,South,Online,...,Other,Electronics,3.2,Returned,Positive,9.57,WELCOME5,4.3,Frequent buyer,no_data

<div class="alert alert-success">

**Solution 05:**
</div>

In [12]:
dropped_df = df.dropna(how='any')
display(dropped_df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values
1,2023-01-02,1709,122,5,23.10,0.01,114.3450,5,North,Cash,...,Female,Clothing,4.4,Returned,Neutral,8.54,nan,2.5,First-time customer,no_data
3,2023-01-04,1139,143,5,56.64,0.27,206.7360,6,East,Cash,...,Male,Electronics,2.1,Not Returned,Negative,17.56,nan,2.9,no_data,value_5
4,2023-01-05,1742,101,9,46.04,0.16,348.0624,6,East,Credit Card,...,Female,Electronics,3.3,Returned,Negative,5.58,SAVE10,2.3,Preferred morning delivery,no_data
6,2023-01-07,1590,133,6,99.93,0.09,545.6178,5,South,Online,...,Female,Clothing,2.5,Not Returned,Negative,9.98,SAVE10,3.6,no_data,value_4
7,2023-01-08,1675,101,6,77.90,0.12,411.3120,6,West,Credit Card,...,Male,Food,4.2,Returned,Negative,5.43,FREESHIP,4.9,no_data,no_data
9,2023-01-10,1629,170,4,47.99,0.25,143.9700,9,North,Cash,...,Other,Food,4.5,Returned,Negative,18.19,nan,3.8,no_data,value_5
11,2023-01-12,1517,116,2,95.07,0.27,138.8022,4,East,Cash,...,Female,Electronics,2.7,Not Returned,Negative,18.61,SAVE10,2.0,Requested gift wrap,unknown
14,2023-01-15,1254,185,8,72.61,0.09,528.6008,8,South,Online,...,Other,Books,3.1,Not Returned,Positive,15.57,SAVE10,5.0,Preferred morning delivery,no_data
15,2023-01-16,1993,132,8,99.03,0.30,554.5680,8,East,Online,...,Male,Clothing,2.8,Returned,Neutral,11.53,nan,1.4,unknown,unknown
16,2023-01-17,1292,107,3,71.48,0.15,182.2740,9,West,Credit Card,...,Other,Electronics,2.1,Not Returned,Positive,9.37,FREESHIP,4.1,unknown,unknown
17,2023-01-18,1148,104,8,23.83,0.22,148.6992,1,North,Online,...,Female,Clothing,1.9,Returned,Positive,14.57,nan,4.7,unknown,no_data
19,2023-01-20,1150,198,9,36.59,0.06,309.5514,5,North,Credit Card,...,Male,Clothing,2.1,Returned,Positive,17.09,WELCOME5,3.1,Used loyalty points,value_5
21,2023-01-22,1854,144,2,66.33,0.10,119.3940,4,North,Credit Card,...,Other,Clothing,3.1,Not Returned,Negative,6.42,SAVE10,2.1,Used loyalty points,value_1
22,2023-01-23,1384,115,7,62.61,0.11,390.0603,2,North,Online,...,Male,Books,4.1,Returned,Negative,14.79,WELCOME5,1.2,Frequent buyer,value_3
23,2023-01-24,1113,119,2,84.05,0.08,154.6520,1,North,Cash,...,Female,Books,2.7,Returned,Positive,9.21,nan,2.7,Used loyalty points,no_data
25,2023-01-26,1914,103,3,31.49,0.25,70.8525,4,West,Cash,...,Male,Clothing,1.1,Not Returned,Negative,17.99,FREESHIP,3.9,Preferred morning delivery,no_data
26,2023-01-27,1148,191,1,24.45,0.03,23.7165,9,South,Credit Card,...,Female,Electronics,4.5,Not Returned,Positive,17.95,FREESHIP,4.7,First-time customer,no_data
27,2023-01-28,1305,101,8,85.42,0.27,498.8528,7,South,Cash,...,Female,Clothing,3.5,Returned,Positive,18.45,FREESHIP,1.2,First-time customer,no_data
29,2023-01-30,1642,172,9,61.19,0.13,479.1177,5,North,Online,...,Male,Electronics,4.9,Returned,Negative,7.19,SAVE10,2.7,no_data,no_data
32,2023-02-02,1673,169,8,57.71,0.24,350.8768,9,North,Online,...,Female,Electronics,3.8,Returned,Negative,17.59,SAVE10,2.4,unknown,value_4
34,2023-02-04,1758,175,1,91.73,0.09,83.4743,6,South,Online,...,Other,Electronics,3.2,Returned,Positive,9.57,WELCOME5,4.3,Frequent buyer,no_data

<div class="alert alert-warning">

**6. Drop Columns with Any Missing Value**

**Write a Pandas program to drop the columns where at least one element is missing in a given DataFrame.**

</div>

In [13]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values
0,2023-01-01,1590,130,6,53.40,0.14,275.5440,2,West,Online,...,Male,Food,1.5,Returned,Positive,NaN,SAVE10,4.3,Used loyalty points,unknown
1,2023-01-02,1313,121,5,98.91,0.21,390.6945,7,East,Online,...,Female,Books,4.8,Returned,Negative,11.55,SAVE10,NaN,First-time customer,no_data
2,2023-01-03,1317,170,1,67.30,0.15,57.2050,9,West,Cash,...,Male,Food,3.6,Not Returned,Negative,9.97,nan,1.3,no_data,unknown
3,2023-01-04,1438,164,5,95.78,0.07,445.3770,6,West,Cash,...,Other,Clothing,4.4,Not Returned,Neutral,11.34,FREESHIP,3.3,no_data,unknown
4,2023-01-05,1685,194,6,16.52,0.01,98.1288,3,South,Credit Card,...,Male,Food,4.9,Not Returned,Positive,15.72,WELCOME5,4.7,unknown,value_5
5,2023-01-06,1239,107,6,77.50,0.15,395.2500,8,West,Online,...,Other,Electronics,4.8,Not Returned,Neutral,8.52,SAVE10,NaN,no_data,value_2
6,2023-01-07,1993,136,4,94.73,0.12,333.4496,4,East,Online,...,Male,Clothing,4.1,Not Returned,Neutral,NaN,WELCOME5,NaN,Preferred morning delivery,no_data
7,2023-01-08,1308,168,2,10.98,0.29,15.5916,5,North,Online,...,Male,Electronics,2.2,Not Returned,Negative,5.14,SAVE10,2.5,Used loyalty points,no_data
8,2023-01-09,1157,145,6,91.29,0.14,471.0564,3,West,Credit Card,...,Other,Food,4.9,Returned,Positive,6.86,nan,NaN,no_data,value_2
9,2023-01-10,1333,102,2,15.89,0.00,31.7800,8,South,Cash,...,Other,Clothing,2.4,Returned,Negative,15.53,nan,1.7,unknown,unknown
10,2023-01-11,1935,147,4,31.73,0.29,90.1132,6,South,Online,...,Male,Clothing,2.8,Returned,Neutral,9.25,SAVE10,1.7,Preferred morning delivery,unknown
11,2023-01-12,1123,172,8,79.86,0.07,594.1584,4,South,Cash,...,Other,Electronics,3.4,Not Returned,Positive,18.22,FREESHIP,2.4,Requested gift wrap,no_data
12,2023-01-13,1917,191,3,73.15,0.21,173.3655,5,South,Cash,...,Male,Clothing,1.2,Not Returned,Negative,12.59,SAVE10,NaN,unknown,value_5
13,2023-01-14,1611,155,6,59.13,0.12,312.2064,2,West,Online,...,Male,Clothing,3.0,Returned,Negative,12.79,SAVE10,4.7,Preferred morning delivery,value_3
14,2023-01-15,1716,149,1,69.27,0.26,51.2598,3,North,Credit Card,...,Male,Clothing,1.8,Not Returned,Positive,18.48,nan,2.8,Preferred morning delivery,value_5
15,2023-01-16,1652,127,9,15.04,0.20,108.2880,7,South,Cash,...,Other,Books,4.8,Not Returned,Negative,5.98,nan,2.8,no_data,value_4
16,2023-01-17,1975,164,9,48.09,0.12,380.8728,6,South,Cash,...,Male,Food,4.3,Returned,Positive,8.59,SAVE10,1.5,Preferred morning delivery,value_5
17,2023-01-18,1242,191,4,53.03,0.30,148.4840,3,North,Credit Card,...,Other,Clothing,2.3,Returned,Negative,17.69,SAVE10,3.7,First-time customer,no_data
18,2023-01-19,1429,161,3,36.96,0.12,97.5744,4,West,Online,...,Female,Books,2.2,Not Returned,Neutral,14.27,FREESHIP,1.2,unknown,no_data
19,2023-01-20,1101,103,4,26.16,0.26,77.4336,3,North,Credit Card,...,Male,Food,3.7,Not Returned,Neutral,17.10,nan,NaN,Preferred morning delivery,no_data
20,2023-01-21,1515,105,7,43.79,0.00,306.5300,2,West,Cash,...,Male,Food,3.1,Not Returned,Positive,5.10,nan,1.9,Requested gift wrap,value_3
21,2023-01-22,1943,168,5,18.31,0.14,78.7330,4,South,Cash,...,Male,Clothing,4.7,Returned,Neutral,10.59,nan,NaN,no_data,no_data
22,2023-01-23,1552,151,8,31.45,0.10,226.4400,4,North,Online,...,Male,Clothing,2.3,Not Returned,Negative,16.42,SAVE10,4.0,Used loyalty points,unknown
23,2023-01-24,1423,164,2,16.10,0.04,30.9120,3,East,Cash,...,Male,Food,4.2,Not Returned,Neutral,16.94,WELCOME5,NaN,Preferred morning delivery,value_2
24,2023-01-25,1301,120,4,15.99,0.26,47.3304,7,West,Credit Card,...,Male,Clothing,4.3,Not Returned,Positive,15.19,WELCOME5,4.3,Used loyalty points,value_1
25,2023-01-26,1307,157,9,38.22,0.14,295.8228,8,South,Credit Card,...,Female,Books,1.5,Returned,Negative,NaN,nan,NaN,First-time customer,value_4
26,2023-01-27,1222,137,9,40.84,0.22,286.6968,8,West,Online,...,Male,Food,1.9,Returned,Neutral,10.59,nan,NaN,no_data,no_data
27,2023-01-28,1717,146,1,86.58,0.28,62.3376,1,North,Cash,...,Male,Books,3.8,Returned,Negative,7.99,WELCOME5,4.1,unknown,value_3
28,2023-01-29,1414,112,7,30.86,0.16,181.4568,2,North,Online,...,Female,Books,2.0,Not Returned,Negative,19.93,nan,3.9,no_data,value_5
29,2023-01-30,1240,160,2,23.15,0.13,40.2810,1,West,Cash,...,Male,Food,2.8,Returned,Neutral,10.19,WELCOME5,2.2,unknown,value_2
30,2023-01-31,1475,195,4,69.11,0.24,210.0944,4,West,Cash,...,Other,Clothing,5.0,Not Returned,Negative,8.55,nan,1.7,no_data,value_2
31,2023-02-01,1464,151,6,18.62,0.13,97.1964,9,West,Cash,...,Male,Clothing,4.8,Not Returned,Positive,NaN,nan,3.5,no_data,value_4
32,2023-02-02,1695,164,6,16.87,0.27,73.8906,3,South,Cash,...,Female,Books,5.0,Returned,Positive,NaN,nan,1.9,no_data,value_5
33,2023-02-03,1470,112,7,84.39,0.12,519.8424,6,South,Credit Card,...,Other,Clothing,4.2,Returned,Negative,13.20,nan,3.8,Frequent buyer,no_data
34,2023-02-04,1494,139,9,27.25,0.07,228.0825,7,East,Cash,...,Female,Books,2.4,Not Returned,Neutral,18.66,FREESHIP,1.8,Preferred morning delivery,value_4

<div class="alert alert-success">

**Solution 06:**
</div>

In [14]:
# Drop columns with any missing value
dropped_df = df.dropna(axis=1, how='any')
display(dropped_df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,coupon_code,customer_note,customer_values
0,2023-01-01,1590,130,6,53.40,0.14,275.5440,2,West,Online,...,1,32,Male,Food,1.5,Returned,Positive,SAVE10,Used loyalty points,unknown
1,2023-01-02,1313,121,5,98.91,0.21,390.6945,7,East,Online,...,5,26,Female,Books,4.8,Returned,Negative,SAVE10,First-time customer,no_data
2,2023-01-03,1317,170,1,67.30,0.15,57.2050,9,West,Cash,...,3,60,Male,Food,3.6,Not Returned,Negative,nan,no_data,unknown
3,2023-01-04,1438,164,5,95.78,0.07,445.3770,6,West,Cash,...,4,25,Other,Clothing,4.4,Not Returned,Neutral,FREESHIP,no_data,unknown
4,2023-01-05,1685,194,6,16.52,0.01,98.1288,3,South,Credit Card,...,1,58,Male,Food,4.9,Not Returned,Positive,WELCOME5,unknown,value_5
5,2023-01-06,1239,107,6,77.50,0.15,395.2500,8,West,Online,...,6,22,Other,Electronics,4.8,Not Returned,Neutral,SAVE10,no_data,value_2
6,2023-01-07,1993,136,4,94.73,0.12,333.4496,4,East,Online,...,2,67,Male,Clothing,4.1,Not Returned,Neutral,WELCOME5,Preferred morning delivery,no_data
7,2023-01-08,1308,168,2,10.98,0.29,15.5916,5,North,Online,...,2,68,Male,Electronics,2.2,Not Returned,Negative,SAVE10,Used loyalty points,no_data
8,2023-01-09,1157,145,6,91.29,0.14,471.0564,3,West,Credit Card,...,4,57,Other,Food,4.9,Returned,Positive,nan,no_data,value_2
9,2023-01-10,1333,102,2,15.89,0.00,31.7800,8,South,Cash,...,4,21,Other,Clothing,2.4,Returned,Negative,nan,unknown,unknown
10,2023-01-11,1935,147,4,31.73,0.29,90.1132,6,South,Online,...,1,60,Male,Clothing,2.8,Returned,Neutral,SAVE10,Preferred morning delivery,unknown
11,2023-01-12,1123,172,8,79.86,0.07,594.1584,4,South,Cash,...,6,63,Other,Electronics,3.4,Not Returned,Positive,FREESHIP,Requested gift wrap,no_data
12,2023-01-13,1917,191,3,73.15,0.21,173.3655,5,South,Cash,...,5,62,Male,Clothing,1.2,Not Returned,Negative,SAVE10,unknown,value_5
13,2023-01-14,1611,155,6,59.13,0.12,312.2064,2,West,Online,...,5,65,Male,Clothing,3.0,Returned,Negative,SAVE10,Preferred morning delivery,value_3
14,2023-01-15,1716,149,1,69.27,0.26,51.2598,3,North,Credit Card,...,4,46,Male,Clothing,1.8,Not Returned,Positive,nan,Preferred morning delivery,value_5
15,2023-01-16,1652,127,9,15.04,0.20,108.2880,7,South,Cash,...,5,43,Other,Books,4.8,Not Returned,Negative,nan,no_data,value_4
16,2023-01-17,1975,164,9,48.09,0.12,380.8728,6,South,Cash,...,1,56,Male,Food,4.3,Returned,Positive,SAVE10,Preferred morning delivery,value_5
17,2023-01-18,1242,191,4,53.03,0.30,148.4840,3,North,Credit Card,...,3,28,Other,Clothing,2.3,Returned,Negative,SAVE10,First-time customer,no_data
18,2023-01-19,1429,161,3,36.96,0.12,97.5744,4,West,Online,...,3,41,Female,Books,2.2,Not Returned,Neutral,FREESHIP,unknown,no_data
19,2023-01-20,1101,103,4,26.16,0.26,77.4336,3,North,Credit Card,...,5,51,Male,Food,3.7,Not Returned,Neutral,nan,Preferred morning delivery,no_data
20,2023-01-21,1515,105,7,43.79,0.00,306.5300,2,West,Cash,...,3,56,Male,Food,3.1,Not Returned,Positive,nan,Requested gift wrap,value_3
21,2023-01-22,1943,168,5,18.31,0.14,78.7330,4,South,Cash,...,2,32,Male,Clothing,4.7,Returned,Neutral,nan,no_data,no_data
22,2023-01-23,1552,151,8,31.45,0.10,226.4400,4,North,Online,...,1,55,Male,Clothing,2.3,Not Returned,Negative,SAVE10,Used loyalty points,unknown
23,2023-01-24,1423,164,2,16.10,0.04,30.9120,3,East,Cash,...,2,37,Male,Food,4.2,Not Returned,Neutral,WELCOME5,Preferred morning delivery,value_2
24,2023-01-25,1301,120,4,15.99,0.26,47.3304,7,West,Credit Card,...,4,37,Male,Clothing,4.3,Not Returned,Positive,WELCOME5,Used loyalty points,value_1
25,2023-01-26,1307,157,9,38.22,0.14,295.8228,8,South,Credit Card,...,1,37,Female,Books,1.5,Returned,Negative,nan,First-time customer,value_4
26,2023-01-27,1222,137,9,40.84,0.22,286.6968,8,West,Online,...,3,54,Male,Food,1.9,Returned,Neutral,nan,no_data,no_data
27,2023-01-28,1717,146,1,86.58,0.28,62.3376,1,North,Cash,...,1,50,Male,Books,3.8,Returned,Negative,WELCOME5,unknown,value_3
28,2023-01-29,1414,112,7,30.86,0.16,181.4568,2,North,Online,...,4,63,Female,Books,2.0,Not Returned,Negative,nan,no_data,value_5
29,2023-01-30,1240,160,2,23.15,0.13,40.2810,1,West,Cash,...,1,44,Male,Food,2.8,Returned,Neutral,WELCOME5,unknown,value_2
30,2023-01-31,1475,195,4,69.11,0.24,210.0944,4,West,Cash,...,6,58,Other,Clothing,5.0,Not Returned,Negative,nan,no_data,value_2
31,2023-02-01,1464,151,6,18.62,0.13,97.1964,9,West,Cash,...,1,20,Male,Clothing,4.8,Not Returned,Positive,nan,no_data,value_4
32,2023-02-02,1695,164,6,16.87,0.27,73.8906,3,South,Cash,...,3,62,Female,Books,5.0,Returned,Positive,nan,no_data,value_5
33,2023-02-03,1470,112,7,84.39,0.12,519.8424,6,South,Credit Card,...,2,25,Other,Clothing,4.2,Returned,Negative,nan,Frequent buyer,no_data
34,2023-02-04,1494,139,9,27.25,0.07,228.0825,7,East,Cash,...,1,35,Female,Books,2.4,Not Returned,Neutral,FREESHIP,Preferred morning delivery,value_4

<div class="alert alert-warning">

**7. Drop Rows with All Missing Values**

**Write a Pandas program to drop the rows where all elements are missing in a given DataFrame.**

</div>

In [15]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_6482/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1928.0,145.0,1.0,28.16,0.19,22.8096,5.0,South,Cash,...,Electronics,3.9,Returned,Positive,13.28,WELCOME5,1.1,Frequent buyer,no_data,NaN
1,2023-01-02,1677.0,130.0,3.0,62.05,0.17,154.5045,7.0,North,Credit Card,...,Electronics,5.0,Not Returned,Neutral,15.36,nan,2.9,Used loyalty points,unknown,NaN
2,2023-01-03,1303.0,121.0,5.0,55.64,0.25,208.6500,8.0,East,Credit Card,...,Electronics,1.5,Not Returned,Neutral,16.59,WELCOME5,2.6,unknown,unknown,NaN
3,2023-01-04,1050.0,122.0,1.0,83.58,0.14,71.8788,3.0,West,Cash,...,Books,3.3,Returned,Positive,NaN,nan,2.4,Used loyalty points,value_4,NaN
4,2023-01-05,1220.0,154.0,1.0,76.73,0.25,57.5475,4.0,North,Online,...,Food,1.5,Returned,Neutral,6.99,nan,2.7,no_data,value_2,NaN
5,2023-01-06,1154.0,180.0,1.0,47.06,0.14,40.4716,7.0,South,Online,...,Electronics,3.2,Returned,Neutral,18.88,nan,2.2,unknown,no_data,NaN
6,2023-01-07,1231.0,149.0,1.0,41.36,0.12,36.3968,9.0,South,Cash,...,Electronics,4.6,Returned,Positive,6.18,FREESHIP,3.7,Frequent buyer,unknown,NaN
7,2023-01-08,1162.0,173.0,8.0,71.61,0.01,567.1512,3.0,West,Online,...,Electronics,4.1,Returned,Negative,18.51,SAVE10,2.0,Requested gift wrap,value_4,NaN
8,2023-01-09,1908.0,180.0,2.0,38.37,0.06,72.1356,9.0,West,Online,...,Books,4.1,Returned,Positive,11.36,FREESHIP,4.6,unknown,unknown,NaN
9,2023-01-10,1310.0,177.0,5.0,68.61,0.12,301.8840,3.0,West,Credit Card,...,Clothing,3.9,Returned,Negative,NaN,FREESHIP,NaN,First-time customer,value_1,NaN
10,2023-01-11,1014.0,160.0,5.0,13.32,0.25,49.9500,2.0,West,Online,...,Food,4.1,Returned,Neutral,17.93,SAVE10,4.1,unknown,value_2,NaN
11,2023-01-12,1614.0,180.0,1.0,10.39,0.15,8.8315,9.0,South,Credit Card,...,Food,4.4,Not Returned,Neutral,16.62,SAVE10,1.0,unknown,no_data,NaN
12,2023-01-13,1536.0,161.0,9.0,54.84,0.18,404.7192,6.0,North,Cash,...,Electronics,4.3,Returned,Negative,NaN,SAVE10,3.4,unknown,unknown,NaN
13,2023-01-14,1536.0,195.0,9.0,11.42,0.27,75.0294,4.0,North,Online,...,Books,3.3,Not Returned,Positive,5.43,FREESHIP,NaN,unknown,unknown,NaN
14,2023-01-15,1025.0,130.0,1.0,36.89,0.29,26.1919,7.0,East,Cash,...,Books,2.8,Returned,Negative,6.32,nan,2.5,no_data,no_data,NaN
15,2023-01-16,1940.0,126.0,2.0,44.01,0.07,81.8586,2.0,North,Online,...,Electronics,4.0,Not Returned,Negative,17.46,FREESHIP,2.3,First-time customer,unknown,NaN
16,2023-01-17,1531.0,111.0,4.0,87.33,0.12,307.4016,8.0,West,Online,...,Food,4.6,Returned,Positive,11.20,nan,1.8,unknown,unknown,NaN
17,2023-01-18,1903.0,144.0,8.0,31.91,0.16,214.4352,1.0,East,Credit Card,...,Clothing,3.7,Not Returned,Negative,5.40,nan,NaN,unknown,unknown,NaN
18,2023-01-19,1815.0,144.0,8.0,42.68,0.02,334.6112,3.0,North,Credit Card,...,Food,2.3,Not Returned,Neutral,15.55,nan,2.0,Requested gift wrap,unknown,NaN
19,2023-01-20,1244.0,166.0,3.0,76.90,0.15,196.0950,7.0,East,Credit Card,...,Food,4.9,Not Returned,Neutral,8.18,SAVE10,NaN,Requested gift wrap,no_data,NaN
20,2023-01-21,1450.0,114.0,2.0,38.48,0.01,76.1904,5.0,East,Credit Card,...,Books,2.7,Not Returned,Positive,14.93,nan,NaN,First-time customer,no_data,NaN
21,2023-01-22,1333.0,111.0,7.0,35.85,0.07,233.3835,3.0,East,Credit Card,...,Books,4.8,Returned,Neutral,15.62,WELCOME5,4.8,no_data,value_2,NaN
22,2023-01-23,1619.0,148.0,7.0,47.10,0.13,286.8390,2.0,West,Online,...,Electronics,1.7,Returned,Neutral,8.12,nan,3.6,Used loyalty points,value_1,NaN
23,2023-01-24,1100.0,181.0,1.0,57.57,0.12,50.6616,8.0,North,Credit Card,...,Clothing,1.8,Returned,Neutral,8.99,FREESHIP,NaN,Requested gift wrap,no_data,NaN
24,2023-01-25,1668.0,111.0,5.0,83.95,0.00,419.7500,8.0,South,Online,...,Books,1.2,Returned,Positive,17.04,nan,3.0,unknown,unknown,NaN
25,2023-01-26,1831.0,154.0,5.0,59.85,0.00,299.2500,3.0,South,Credit Card,...,Clothing,2.3,Not Returned,Positive,13.61,WELCOME5,NaN,unknown,unknown,NaN
26,2023-01-27,1029.0,148.0,2.0,27.97,0.21,44.1926,8.0,West,Credit Card,...,Clothing,2.0,Not Returned,Neutral,5.28,WELCOME5,4.5,no_data,value_1,NaN
27,2023-01-28,1934.0,104.0,4.0,46.10,0.11,164.1160,2.0,North,Online,...,Electronics,1.9,Not Returned,Negative,7.11,SAVE10,4.9,no_data,no_data,NaN
28,2023-01-29,1983.0,158.0,1.0,68.92,0.15,58.5820,8.0,West,Online,...,Electronics,2.1,Not Returned,Positive,15.00,FREESHIP,2.1,Preferred morning delivery,value_5,NaN
29,2023-01-30,1387.0,185.0,9.0,87.92,0.23,609.2856,7.0,South,Cash,...,Clothing,3.7,Returned,Neutral,14.62,nan,2.7,no_data,no_data,NaN
30,2023-01-31,1720.0,185.0,1.0,60.29,0.25,45.2175,4.0,West,Credit Card,...,Electronics,5.0,Returned,Neutral,NaN,FREESHIP,NaN,no_data,value_2,NaN
31,2023-02-01,1841.0,199.0,4.0,17.82,0.03,69.1416,9.0,West,Credit Card,...,Electronics,2.5,Not Returned,Negative,14.42,WELCOME5,NaN,unknown,no_data,NaN
32,2023-02-02,1196.0,101.0,3.0,70.98,0.17,176.7402,4.0,East,Credit Card,...,Electronics,4.7,Not Returned,Negative,17.96,nan,3.4,First-time customer,unknown,NaN
33,2023-02-03,1667.0,121.0,2.0,70.04,0.26,103.6592,3.0,South,Online,...,Electronics,2.8,Not Returned,Negative,6.77,WELCOME5,NaN,no_data,unknown,NaN
34,2023-02-04,1573.0,127.0,4.0,27.32,0.04,104.9088,3.0,East,Online,...,Electronics,2.0,Returned,Positive,NaN,SAVE10,NaN,Frequent buyer,value_4,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 07:**
</div>

In [16]:
# Write a Pandas program to drop the rows where all elements are missing in a given DataFrame
df_dropped = df.dropna(how='all')

# Display the DataFrame after dropping rows
display(df_dropped)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1928.0,145.0,1.0,28.16,0.19,22.8096,5.0,South,Cash,...,Electronics,3.9,Returned,Positive,13.28,WELCOME5,1.1,Frequent buyer,no_data,NaN
1,2023-01-02,1677.0,130.0,3.0,62.05,0.17,154.5045,7.0,North,Credit Card,...,Electronics,5.0,Not Returned,Neutral,15.36,nan,2.9,Used loyalty points,unknown,NaN
2,2023-01-03,1303.0,121.0,5.0,55.64,0.25,208.6500,8.0,East,Credit Card,...,Electronics,1.5,Not Returned,Neutral,16.59,WELCOME5,2.6,unknown,unknown,NaN
3,2023-01-04,1050.0,122.0,1.0,83.58,0.14,71.8788,3.0,West,Cash,...,Books,3.3,Returned,Positive,NaN,nan,2.4,Used loyalty points,value_4,NaN
4,2023-01-05,1220.0,154.0,1.0,76.73,0.25,57.5475,4.0,North,Online,...,Food,1.5,Returned,Neutral,6.99,nan,2.7,no_data,value_2,NaN
5,2023-01-06,1154.0,180.0,1.0,47.06,0.14,40.4716,7.0,South,Online,...,Electronics,3.2,Returned,Neutral,18.88,nan,2.2,unknown,no_data,NaN
6,2023-01-07,1231.0,149.0,1.0,41.36,0.12,36.3968,9.0,South,Cash,...,Electronics,4.6,Returned,Positive,6.18,FREESHIP,3.7,Frequent buyer,unknown,NaN
7,2023-01-08,1162.0,173.0,8.0,71.61,0.01,567.1512,3.0,West,Online,...,Electronics,4.1,Returned,Negative,18.51,SAVE10,2.0,Requested gift wrap,value_4,NaN
8,2023-01-09,1908.0,180.0,2.0,38.37,0.06,72.1356,9.0,West,Online,...,Books,4.1,Returned,Positive,11.36,FREESHIP,4.6,unknown,unknown,NaN
9,2023-01-10,1310.0,177.0,5.0,68.61,0.12,301.8840,3.0,West,Credit Card,...,Clothing,3.9,Returned,Negative,NaN,FREESHIP,NaN,First-time customer,value_1,NaN
10,2023-01-11,1014.0,160.0,5.0,13.32,0.25,49.9500,2.0,West,Online,...,Food,4.1,Returned,Neutral,17.93,SAVE10,4.1,unknown,value_2,NaN
11,2023-01-12,1614.0,180.0,1.0,10.39,0.15,8.8315,9.0,South,Credit Card,...,Food,4.4,Not Returned,Neutral,16.62,SAVE10,1.0,unknown,no_data,NaN
12,2023-01-13,1536.0,161.0,9.0,54.84,0.18,404.7192,6.0,North,Cash,...,Electronics,4.3,Returned,Negative,NaN,SAVE10,3.4,unknown,unknown,NaN
13,2023-01-14,1536.0,195.0,9.0,11.42,0.27,75.0294,4.0,North,Online,...,Books,3.3,Not Returned,Positive,5.43,FREESHIP,NaN,unknown,unknown,NaN
14,2023-01-15,1025.0,130.0,1.0,36.89,0.29,26.1919,7.0,East,Cash,...,Books,2.8,Returned,Negative,6.32,nan,2.5,no_data,no_data,NaN
15,2023-01-16,1940.0,126.0,2.0,44.01,0.07,81.8586,2.0,North,Online,...,Electronics,4.0,Not Returned,Negative,17.46,FREESHIP,2.3,First-time customer,unknown,NaN
16,2023-01-17,1531.0,111.0,4.0,87.33,0.12,307.4016,8.0,West,Online,...,Food,4.6,Returned,Positive,11.20,nan,1.8,unknown,unknown,NaN
17,2023-01-18,1903.0,144.0,8.0,31.91,0.16,214.4352,1.0,East,Credit Card,...,Clothing,3.7,Not Returned,Negative,5.40,nan,NaN,unknown,unknown,NaN
18,2023-01-19,1815.0,144.0,8.0,42.68,0.02,334.6112,3.0,North,Credit Card,...,Food,2.3,Not Returned,Neutral,15.55,nan,2.0,Requested gift wrap,unknown,NaN
19,2023-01-20,1244.0,166.0,3.0,76.90,0.15,196.0950,7.0,East,Credit Card,...,Food,4.9,Not Returned,Neutral,8.18,SAVE10,NaN,Requested gift wrap,no_data,NaN
20,2023-01-21,1450.0,114.0,2.0,38.48,0.01,76.1904,5.0,East,Credit Card,...,Books,2.7,Not Returned,Positive,14.93,nan,NaN,First-time customer,no_data,NaN
21,2023-01-22,1333.0,111.0,7.0,35.85,0.07,233.3835,3.0,East,Credit Card,...,Books,4.8,Returned,Neutral,15.62,WELCOME5,4.8,no_data,value_2,NaN
22,2023-01-23,1619.0,148.0,7.0,47.10,0.13,286.8390,2.0,West,Online,...,Electronics,1.7,Returned,Neutral,8.12,nan,3.6,Used loyalty points,value_1,NaN
23,2023-01-24,1100.0,181.0,1.0,57.57,0.12,50.6616,8.0,North,Credit Card,...,Clothing,1.8,Returned,Neutral,8.99,FREESHIP,NaN,Requested gift wrap,no_data,NaN
24,2023-01-25,1668.0,111.0,5.0,83.95,0.00,419.7500,8.0,South,Online,...,Books,1.2,Returned,Positive,17.04,nan,3.0,unknown,unknown,NaN
25,2023-01-26,1831.0,154.0,5.0,59.85,0.00,299.2500,3.0,South,Credit Card,...,Clothing,2.3,Not Returned,Positive,13.61,WELCOME5,NaN,unknown,unknown,NaN
26,2023-01-27,1029.0,148.0,2.0,27.97,0.21,44.1926,8.0,West,Credit Card,...,Clothing,2.0,Not Returned,Neutral,5.28,WELCOME5,4.5,no_data,value_1,NaN
27,2023-01-28,1934.0,104.0,4.0,46.10,0.11,164.1160,2.0,North,Online,...,Electronics,1.9,Not Returned,Negative,7.11,SAVE10,4.9,no_data,no_data,NaN
28,2023-01-29,1983.0,158.0,1.0,68.92,0.15,58.5820,8.0,West,Online,...,Electronics,2.1,Not Returned,Positive,15.00,FREESHIP,2.1,Preferred morning delivery,value_5,NaN
29,2023-01-30,1387.0,185.0,9.0,87.92,0.23,609.2856,7.0,South,Cash,...,Clothing,3.7,Returned,Neutral,14.62,nan,2.7,no_data,no_data,NaN
30,2023-01-31,1720.0,185.0,1.0,60.29,0.25,45.2175,4.0,West,Credit Card,...,Electronics,5.0,Returned,Neutral,NaN,FREESHIP,NaN,no_data,value_2,NaN
31,2023-02-01,1841.0,199.0,4.0,17.82,0.03,69.1416,9.0,West,Credit Card,...,Electronics,2.5,Not Returned,Negative,14.42,WELCOME5,NaN,unknown,no_data,NaN
32,2023-02-02,1196.0,101.0,3.0,70.98,0.17,176.7402,4.0,East,Credit Card,...,Electronics,4.7,Not Returned,Negative,17.96,nan,3.4,First-time customer,unknown,NaN
33,2023-02-03,1667.0,121.0,2.0,70.04,0.26,103.6592,3.0,South,Online,...,Electronics,2.8,Not Returned,Negative,6.77,WELCOME5,NaN,no_data,unknown,NaN
34,2023-02-04,1573.0,127.0,4.0,27.32,0.04,104.9088,3.0,East,Online,...,Electronics,2.0,Returned,Positive,NaN,SAVE10,NaN,Frequent buyer,value_4,NaN

<div class="alert alert-warning">

**8. Keep Rows with at Least 2 NaN Values**

**Write a Pandas program to keep the rows with at least 2 NaN values in a given DataFrame.**

</div>

In [17]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_6482/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1937.0,139.0,3.0,20.89,0.15,53.2695,9.0,North,Credit Card,...,Books,2.5,Not Returned,Negative,7.03,nan,2.4,unknown,value_3,NaN
1,2023-01-02,1514.0,105.0,5.0,26.19,0.12,115.2360,7.0,West,Credit Card,...,Clothing,3.3,Not Returned,Positive,13.33,SAVE10,NaN,unknown,value_2,NaN
2,2023-01-03,1482.0,117.0,6.0,58.41,0.24,266.3496,1.0,West,Credit Card,...,Electronics,4.6,Not Returned,Neutral,17.85,WELCOME5,4.8,Frequent buyer,unknown,NaN
3,2023-01-04,1200.0,100.0,6.0,62.25,0.12,328.6800,9.0,West,Online,...,Electronics,4.6,Returned,Negative,7.46,FREESHIP,1.4,no_data,value_3,NaN
4,2023-01-05,1490.0,105.0,6.0,12.63,0.26,56.0772,7.0,West,Online,...,Electronics,4.1,Not Returned,Positive,NaN,nan,3.2,unknown,value_1,NaN
5,2023-01-06,1874.0,117.0,6.0,84.09,0.28,363.2688,8.0,South,Online,...,Clothing,4.3,Returned,Negative,14.07,SAVE10,4.9,Frequent buyer,no_data,NaN
6,2023-01-07,1983.0,110.0,5.0,65.56,0.16,275.3520,6.0,East,Online,...,Electronics,3.7,Returned,Positive,7.52,nan,2.8,Frequent buyer,unknown,NaN
7,2023-01-08,1609.0,110.0,6.0,17.60,0.13,91.8720,8.0,East,Cash,...,Books,3.9,Not Returned,Negative,13.67,FREESHIP,NaN,unknown,no_data,NaN
8,2023-01-09,1065.0,110.0,2.0,62.47,0.14,107.4484,1.0,South,Online,...,Electronics,4.8,Not Returned,Positive,17.51,nan,NaN,Requested gift wrap,value_5,NaN
9,2023-01-10,1768.0,144.0,5.0,94.13,0.01,465.9435,1.0,South,Credit Card,...,Clothing,3.0,Not Returned,Negative,5.73,FREESHIP,NaN,no_data,value_5,NaN
10,2023-01-11,1718.0,114.0,6.0,71.70,0.13,374.2740,1.0,South,Online,...,Food,2.9,Not Returned,Positive,15.65,nan,3.8,Used loyalty points,value_1,NaN
11,2023-01-12,1919.0,165.0,3.0,14.96,0.25,33.6600,8.0,North,Credit Card,...,Food,3.5,Returned,Negative,16.58,FREESHIP,NaN,unknown,value_2,NaN
12,2023-01-13,1207.0,185.0,6.0,57.16,0.03,332.6712,9.0,East,Cash,...,Clothing,4.5,Not Returned,Negative,16.48,nan,2.6,Requested gift wrap,unknown,NaN
13,2023-01-14,1416.0,190.0,5.0,28.73,0.13,124.9755,5.0,East,Cash,...,Food,4.0,Returned,Negative,5.28,SAVE10,2.0,unknown,no_data,NaN
14,2023-01-15,1077.0,158.0,5.0,23.44,0.08,107.8240,5.0,South,Credit Card,...,Books,4.9,Returned,Negative,NaN,SAVE10,4.8,no_data,value_3,NaN
15,2023-01-16,1494.0,116.0,6.0,20.33,0.25,91.4850,6.0,East,Cash,...,Electronics,1.8,Returned,Negative,NaN,nan,NaN,unknown,value_2,NaN
16,2023-01-17,1747.0,135.0,9.0,52.39,0.28,339.4872,1.0,East,Cash,...,Clothing,1.4,Not Returned,Negative,12.21,FREESHIP,3.5,unknown,value_3,NaN
17,2023-01-18,1177.0,135.0,5.0,95.66,0.08,440.0360,3.0,North,Credit Card,...,Food,4.9,Returned,Positive,NaN,FREESHIP,1.2,Used loyalty points,unknown,NaN
18,2023-01-19,1342.0,120.0,2.0,40.48,0.24,61.5296,6.0,East,Cash,...,Books,3.1,Returned,Negative,NaN,nan,4.7,no_data,value_4,NaN
19,2023-01-20,1489.0,179.0,3.0,24.23,0.04,69.7824,7.0,South,Credit Card,...,Electronics,3.2,Returned,Neutral,16.47,nan,NaN,Frequent buyer,unknown,NaN
20,2023-01-21,1206.0,129.0,1.0,97.69,0.19,79.1289,9.0,North,Cash,...,Electronics,4.2,Not Returned,Positive,16.80,SAVE10,1.2,Preferred morning delivery,unknown,NaN
21,2023-01-22,1577.0,106.0,3.0,90.55,0.08,249.9180,2.0,South,Cash,...,Electronics,4.2,Returned,Negative,12.32,WELCOME5,4.3,Used loyalty points,no_data,NaN
22,2023-01-23,1363.0,148.0,8.0,23.22,0.25,139.3200,5.0,South,Credit Card,...,Electronics,2.6,Returned,Positive,11.52,nan,NaN,Requested gift wrap,unknown,NaN
23,2023-01-24,1542.0,170.0,8.0,85.89,0.01,680.2488,2.0,South,Cash,...,Books,1.4,Returned,Negative,6.63,nan,NaN,Used loyalty points,no_data,NaN
24,2023-01-25,1934.0,142.0,5.0,12.50,0.15,53.1250,9.0,East,Cash,...,Books,3.2,Returned,Neutral,NaN,WELCOME5,NaN,Requested gift wrap,value_1,NaN
25,2023-01-26,1411.0,159.0,2.0,44.89,0.15,76.3130,9.0,East,Credit Card,...,Books,4.3,Not Returned,Neutral,15.94,WELCOME5,3.8,unknown,unknown,NaN
26,2023-01-27,1739.0,183.0,8.0,74.05,0.01,586.4760,7.0,West,Cash,...,Food,1.9,Not Returned,Negative,18.54,nan,1.9,unknown,no_data,NaN
27,2023-01-28,1187.0,141.0,3.0,58.04,0.25,130.5900,3.0,West,Cash,...,Electronics,4.6,Returned,Positive,19.96,nan,5.0,no_data,no_data,NaN
28,2023-01-29,1997.0,104.0,8.0,18.98,0.25,113.8800,2.0,East,Cash,...,Books,3.1,Returned,Positive,NaN,SAVE10,NaN,Preferred morning delivery,value_5,NaN
29,2023-01-30,1602.0,165.0,2.0,83.13,0.10,149.6340,4.0,West,Credit Card,...,Electronics,3.4,Not Returned,Positive,5.39,nan,1.3,Requested gift wrap,value_3,NaN
30,2023-01-31,1089.0,179.0,3.0,50.28,0.10,135.7560,4.0,North,Cash,...,Electronics,4.9,Not Returned,Negative,16.08,WELCOME5,NaN,no_data,no_data,NaN
31,2023-02-01,1206.0,111.0,6.0,97.10,0.25,436.9500,9.0,East,Online,...,Electronics,3.5,Not Returned,Negative,8.84,nan,4.8,Used loyalty points,unknown,NaN
32,2023-02-02,1853.0,132.0,5.0,65.67,0.16,275.8140,3.0,East,Online,...,Books,3.0,Returned,Neutral,7.39,WELCOME5,NaN,Frequent buyer,no_data,NaN
33,2023-02-03,1274.0,137.0,7.0,96.11,0.28,484.3944,5.0,West,Online,...,Electronics,1.6,Returned,Negative,NaN,nan,NaN,Frequent buyer,unknown,NaN
34,2023-02-04,1043.0,100.0,6.0,32.74,0.18,161.0808,7.0,East,Online,...,Books,4.6,Returned,Neutral,14.81,SAVE10,NaN,unknown,unknown,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 08:**
</div>

In [18]:
pd.DataFrame.sum?

Signature:
pd.DataFrame.sum(
    self,
    axis: 'Axis | None' = 0,
    skipna: 'bool' = True,
    numeric_only: 'bool' = False,
    min_count: 'int' = 0,
    **kwargs,
)
Docstring:
Return the sum of the values over the requested axis.

This is equivalent to the method ``numpy.sum``.

Parameters
----------
axis : {index (0), columns (1)}
    Axis for the function to be applied on.
    For `Series` this parameter is unused and defaults to 0.

    .. warning::

        The behavior of DataFrame.sum with ``axis=None`` is deprecated,
        in a future version this will reduce over both axes and return a scalar
        To retain the old behavior, pass axis=0 (or do not pass axis).

    .. versionadded:: 2.0.0

skipna : bool, default True
    Exclude NA/null values when computing the result.
numeric_only : bool, default False
    Include only float, int, boolean columns. Not implemented for Series.

min_count : int, default 0
    The required number of valid values to perform the operation. If fewer than
    ``min_count`` non-NA values are present the result will be NA.
**kwargs
    Additional keyword arguments to be passed to the function.

Returns
-------
Series or scalar

See Also
--------
Series.sum : Return the sum.
Series.min : Return the minimum.
Series.max : Return the maximum.
Series.idxmin : Return the index of the minimum.
Series.idxmax : Return the index of the maximum.
DataFrame.sum : Return the sum over the requested axis.
DataFrame.min : Return the minimum over the requested axis.
DataFrame.max : Return the maximum over the requested axis.
DataFrame.idxmin : Return the index of the minimum over the requested axis.
DataFrame.idxmax : Return the index of the maximum over the requested axis.

Examples
--------
>>> idx = pd.MultiIndex.from_arrays([
...     ['warm', 'warm', 'cold', 'cold'],
...     ['dog', 'falcon', 'fish', 'spider']],
...     names=['blooded', 'animal'])
>>> s = pd.Series([4, 2, 0, 8], name='legs', index=idx)
>>> s
blooded  animal
warm     dog       4
         falcon    2
cold     fish      0
         spider    8
Name: legs, dtype: int64

>>> s.sum()
14

By default, the sum of an empty or all-NA Series is ``0``.

>>> pd.Series([], dtype="float64").sum()  # min_count=0 is the default
0.0

This can be controlled with the ``min_count`` parameter. For example, if
you'd like the sum of an empty series to be NaN, pass ``min_count=1``.

>>> pd.Series([], dtype="float64").sum(min_count=1)
nan

Thanks to the ``skipna`` parameter, ``min_count`` handles all-NA and
empty series identically.

>>> pd.Series([np.nan]).sum()
0.0

>>> pd.Series([np.nan]).sum(min_count=1)
nan
File:      ~/dev/pandas-exercises/.venv/lib/python3.12/site-packages/pandas/core/frame.py
Type:      function

In [19]:
df.isnull().sum(axis=0)

date                 1
customer_id          1
product_id           1
quantity             1
price                1
discount             1
revenue              1
store_id             1
region               1
payment_method       1
is_member            1
delivery_days        1
customer_age         1
gender               1
product_category     1
rating               1
return_status        1
feedback             1
shipping_cost        9
coupon_code          1
delivery_rating     16
customer_note        1
customer_values      1
all_nan_column      36
dtype: int64

In [20]:
df.isnull().sum(axis=1)

0      1
1      2
2      1
3      1
4      2
5      1
6      1
7      2
8      2
9      2
10     1
11     2
12     1
13     1
14     2
15     3
16     1
17     2
18     2
19     2
20     1
21     1
22     2
23     2
24     3
25     1
26     1
27     1
28     3
29     1
30     2
31     1
32     2
33     3
34     2
35    24
dtype: int64

In [21]:
df_kept = df[df.isnull().sum(axis=1) >= 2]

# Display the DataFrame after keeping rows
display(df_kept.reset_index(drop=True))

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-02,1514.0,105.0,5.0,26.19,0.12,115.2360,7.0,West,Credit Card,...,Clothing,3.3,Not Returned,Positive,13.33,SAVE10,NaN,unknown,value_2,NaN
1,2023-01-05,1490.0,105.0,6.0,12.63,0.26,56.0772,7.0,West,Online,...,Electronics,4.1,Not Returned,Positive,NaN,nan,3.2,unknown,value_1,NaN
2,2023-01-08,1609.0,110.0,6.0,17.60,0.13,91.8720,8.0,East,Cash,...,Books,3.9,Not Returned,Negative,13.67,FREESHIP,NaN,unknown,no_data,NaN
3,2023-01-09,1065.0,110.0,2.0,62.47,0.14,107.4484,1.0,South,Online,...,Electronics,4.8,Not Returned,Positive,17.51,nan,NaN,Requested gift wrap,value_5,NaN
4,2023-01-10,1768.0,144.0,5.0,94.13,0.01,465.9435,1.0,South,Credit Card,...,Clothing,3.0,Not Returned,Negative,5.73,FREESHIP,NaN,no_data,value_5,NaN
5,2023-01-12,1919.0,165.0,3.0,14.96,0.25,33.6600,8.0,North,Credit Card,...,Food,3.5,Returned,Negative,16.58,FREESHIP,NaN,unknown,value_2,NaN
6,2023-01-15,1077.0,158.0,5.0,23.44,0.08,107.8240,5.0,South,Credit Card,...,Books,4.9,Returned,Negative,NaN,SAVE10,4.8,no_data,value_3,NaN
7,2023-01-16,1494.0,116.0,6.0,20.33,0.25,91.4850,6.0,East,Cash,...,Electronics,1.8,Returned,Negative,NaN,nan,NaN,unknown,value_2,NaN
8,2023-01-18,1177.0,135.0,5.0,95.66,0.08,440.0360,3.0,North,Credit Card,...,Food,4.9,Returned,Positive,NaN,FREESHIP,1.2,Used loyalty points,unknown,NaN
9,2023-01-19,1342.0,120.0,2.0,40.48,0.24,61.5296,6.0,East,Cash,...,Books,3.1,Returned,Negative,NaN,nan,4.7,no_data,value_4,NaN
10,2023-01-20,1489.0,179.0,3.0,24.23,0.04,69.7824,7.0,South,Credit Card,...,Electronics,3.2,Returned,Neutral,16.47,nan,NaN,Frequent buyer,unknown,NaN
11,2023-01-23,1363.0,148.0,8.0,23.22,0.25,139.3200,5.0,South,Credit Card,...,Electronics,2.6,Returned,Positive,11.52,nan,NaN,Requested gift wrap,unknown,NaN
12,2023-01-24,1542.0,170.0,8.0,85.89,0.01,680.2488,2.0,South,Cash,...,Books,1.4,Returned,Negative,6.63,nan,NaN,Used loyalty points,no_data,NaN
13,2023-01-25,1934.0,142.0,5.0,12.50,0.15,53.1250,9.0,East,Cash,...,Books,3.2,Returned,Neutral,NaN,WELCOME5,NaN,Requested gift wrap,value_1,NaN
14,2023-01-29,1997.0,104.0,8.0,18.98,0.25,113.8800,2.0,East,Cash,...,Books,3.1,Returned,Positive,NaN,SAVE10,NaN,Preferred morning delivery,value_5,NaN
15,2023-01-31,1089.0,179.0,3.0,50.28,0.10,135.7560,4.0,North,Cash,...,Electronics,4.9,Not Returned,Negative,16.08,WELCOME5,NaN,no_data,no_data,NaN
16,2023-02-02,1853.0,132.0,5.0,65.67,0.16,275.8140,3.0,East,Online,...,Books,3.0,Returned,Neutral,7.39,WELCOME5,NaN,Frequent buyer,no_data,NaN
17,2023-02-03,1274.0,137.0,7.0,96.11,0.28,484.3944,5.0,West,Online,...,Electronics,1.6,Returned,Negative,NaN,nan,NaN,Frequent buyer,unknown,NaN
18,2023-02-04,1043.0,100.0,6.0,32.74,0.18,161.0808,7.0,East,Online,...,Books,4.6,Returned,Neutral,14.81,SAVE10,NaN,unknown,unknown,NaN
19,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-warning">

**9. Drop Rows with Missing Values in Specific Columns**

**Write a Pandas program to drop those rows from a given DataFrame in which specific columns have missing values.**

</div>

In [22]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_6482/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1506.0,113.0,7.0,45.71,0.19,259.1757,2.0,East,Online,...,Food,1.3,Not Returned,Positive,19.42,WELCOME5,1.4,no_data,value_1,NaN
1,2023-01-02,1997.0,115.0,1.0,99.37,0.11,88.4393,8.0,East,Credit Card,...,Clothing,1.5,Returned,Neutral,11.84,SAVE10,NaN,no_data,unknown,NaN
2,2023-01-03,1966.0,166.0,5.0,49.85,0.13,216.8475,9.0,North,Cash,...,Books,5.0,Not Returned,Positive,12.61,FREESHIP,1.3,unknown,unknown,NaN
3,2023-01-04,1593.0,189.0,6.0,79.01,0.17,393.4698,1.0,South,Online,...,Books,3.9,Returned,Positive,18.79,nan,NaN,unknown,value_1,NaN
4,2023-01-05,1042.0,178.0,1.0,85.06,0.26,62.9444,2.0,West,Online,...,Electronics,4.7,Returned,Positive,NaN,SAVE10,4.7,Frequent buyer,no_data,NaN
5,2023-01-06,1726.0,141.0,4.0,55.30,0.28,159.2640,7.0,West,Cash,...,Clothing,3.5,Returned,Negative,14.64,FREESHIP,1.7,no_data,value_1,NaN
6,2023-01-07,1218.0,196.0,1.0,19.48,0.22,15.1944,3.0,South,Cash,...,Books,4.1,Not Returned,Neutral,NaN,WELCOME5,3.7,no_data,no_data,NaN
7,2023-01-08,1151.0,154.0,7.0,68.24,0.26,353.4832,4.0,South,Cash,...,Electronics,2.0,Not Returned,Negative,NaN,nan,3.6,Preferred morning delivery,unknown,NaN
8,2023-01-09,1271.0,129.0,3.0,49.32,0.09,134.6436,4.0,West,Online,...,Clothing,2.2,Returned,Neutral,14.82,SAVE10,NaN,unknown,value_5,NaN
9,2023-01-10,1584.0,113.0,2.0,45.54,0.25,68.3100,4.0,South,Cash,...,Electronics,1.4,Returned,Positive,9.53,FREESHIP,2.9,Used loyalty points,value_2,NaN
10,2023-01-11,1820.0,135.0,1.0,54.10,0.18,44.3620,1.0,East,Online,...,Food,4.5,Returned,Positive,NaN,nan,2.2,no_data,value_5,NaN
11,2023-01-12,1106.0,114.0,5.0,68.86,0.13,299.5410,3.0,West,Credit Card,...,Electronics,1.6,Not Returned,Positive,NaN,nan,2.3,no_data,value_4,NaN
12,2023-01-13,1065.0,193.0,3.0,57.12,0.06,161.0784,9.0,North,Online,...,Food,4.0,Not Returned,Negative,13.95,SAVE10,NaN,Frequent buyer,value_3,NaN
13,2023-01-14,1250.0,100.0,6.0,78.22,0.13,408.3084,3.0,East,Cash,...,Electronics,1.3,Returned,Positive,16.41,nan,3.6,Used loyalty points,value_5,NaN
14,2023-01-15,1815.0,116.0,6.0,67.42,0.02,396.4296,9.0,East,Credit Card,...,Electronics,4.5,Returned,Positive,16.18,nan,4.9,unknown,value_5,NaN
15,2023-01-16,1170.0,132.0,6.0,47.36,0.28,204.5952,6.0,West,Cash,...,Electronics,2.7,Returned,Neutral,12.05,SAVE10,1.8,Requested gift wrap,value_3,NaN
16,2023-01-17,1538.0,184.0,7.0,92.56,0.05,615.5240,9.0,South,Credit Card,...,Clothing,1.6,Returned,Neutral,NaN,WELCOME5,2.5,no_data,value_2,NaN
17,2023-01-18,1540.0,134.0,6.0,29.59,0.04,170.4384,5.0,North,Credit Card,...,Food,4.7,Not Returned,Positive,19.48,nan,4.1,First-time customer,value_5,NaN
18,2023-01-19,1933.0,176.0,1.0,24.00,0.29,17.0400,2.0,East,Cash,...,Food,4.6,Returned,Negative,15.97,SAVE10,4.2,First-time customer,value_5,NaN
19,2023-01-20,1766.0,123.0,1.0,52.26,0.18,42.8532,9.0,North,Cash,...,Electronics,1.9,Not Returned,Positive,18.30,SAVE10,4.5,Preferred morning delivery,value_2,NaN
20,2023-01-21,1882.0,189.0,8.0,35.46,0.20,226.9440,7.0,North,Credit Card,...,Clothing,3.6,Returned,Neutral,17.21,FREESHIP,NaN,no_data,value_3,NaN
21,2023-01-22,1710.0,199.0,5.0,69.14,0.19,280.0170,9.0,West,Cash,...,Electronics,1.4,Returned,Negative,17.26,SAVE10,1.1,Preferred morning delivery,unknown,NaN
22,2023-01-23,1506.0,195.0,9.0,80.43,0.26,535.6638,9.0,South,Credit Card,...,Clothing,3.2,Not Returned,Positive,NaN,FREESHIP,4.9,Frequent buyer,value_5,NaN
23,2023-01-24,1973.0,106.0,5.0,26.88,0.24,102.1440,8.0,South,Credit Card,...,Clothing,2.2,Returned,Negative,15.02,FREESHIP,NaN,unknown,value_1,NaN
24,2023-01-25,1611.0,182.0,8.0,74.62,0.26,441.7504,5.0,North,Credit Card,...,Electronics,5.0,Not Returned,Negative,5.81,FREESHIP,1.9,unknown,unknown,NaN
25,2023-01-26,1269.0,187.0,6.0,68.99,0.04,397.3824,3.0,South,Online,...,Food,4.1,Not Returned,Negative,8.57,WELCOME5,1.1,unknown,unknown,NaN
26,2023-01-27,1805.0,165.0,9.0,37.33,0.26,248.6178,5.0,East,Cash,...,Electronics,4.2,Returned,Negative,16.55,nan,2.2,First-time customer,value_2,NaN
27,2023-01-28,1364.0,155.0,1.0,73.55,0.26,54.4270,1.0,South,Credit Card,...,Clothing,4.6,Returned,Neutral,19.56,FREESHIP,3.7,unknown,unknown,NaN
28,2023-01-29,1784.0,181.0,4.0,24.89,0.08,91.5952,7.0,North,Cash,...,Electronics,1.0,Not Returned,Neutral,7.02,SAVE10,2.2,unknown,unknown,NaN
29,2023-01-30,1021.0,196.0,4.0,77.39,0.08,284.7952,9.0,North,Cash,...,Clothing,2.0,Not Returned,Negative,NaN,FREESHIP,2.8,no_data,no_data,NaN
30,2023-01-31,1276.0,155.0,8.0,52.73,0.19,341.6904,9.0,East,Credit Card,...,Clothing,5.0,Not Returned,Negative,16.50,WELCOME5,2.6,unknown,no_data,NaN
31,2023-02-01,1172.0,176.0,7.0,45.63,0.22,249.1398,6.0,North,Online,...,Books,3.7,Returned,Neutral,13.93,WELCOME5,NaN,Frequent buyer,value_3,NaN
32,2023-02-02,1033.0,157.0,3.0,11.94,0.00,35.8200,4.0,East,Cash,...,Food,2.1,Returned,Negative,NaN,nan,3.7,unknown,no_data,NaN
33,2023-02-03,1411.0,102.0,4.0,79.94,0.24,243.0176,2.0,North,Credit Card,...,Electronics,1.0,Not Returned,Neutral,8.56,nan,4.9,Used loyalty points,value_5,NaN
34,2023-02-04,1533.0,104.0,8.0,30.83,0.24,187.4464,3.0,South,Cash,...,Electronics,4.6,Returned,Neutral,16.74,SAVE10,NaN,Requested gift wrap,value_2,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 09:**
</div>

In [23]:
# Write a Pandas program to drop those rows from a given DataFrame in which specific columns have missing values
dropped_df = df.dropna(subset=['shipping_cost', 'coupon_code', 'delivery_rating'])
dropped_df

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1506.0,113.0,7.0,45.71,0.19,259.1757,2.0,East,Online,...,Food,1.3,Not Returned,Positive,19.42,WELCOME5,1.4,no_data,value_1,NaN
2,2023-01-03,1966.0,166.0,5.0,49.85,0.13,216.8475,9.0,North,Cash,...,Books,5.0,Not Returned,Positive,12.61,FREESHIP,1.3,unknown,unknown,NaN
5,2023-01-06,1726.0,141.0,4.0,55.30,0.28,159.2640,7.0,West,Cash,...,Clothing,3.5,Returned,Negative,14.64,FREESHIP,1.7,no_data,value_1,NaN
9,2023-01-10,1584.0,113.0,2.0,45.54,0.25,68.3100,4.0,South,Cash,...,Electronics,1.4,Returned,Positive,9.53,FREESHIP,2.9,Used loyalty points,value_2,NaN
13,2023-01-14,1250.0,100.0,6.0,78.22,0.13,408.3084,3.0,East,Cash,...,Electronics,1.3,Returned,Positive,16.41,nan,3.6,Used loyalty points,value_5,NaN
14,2023-01-15,1815.0,116.0,6.0,67.42,0.02,396.4296,9.0,East,Credit Card,...,Electronics,4.5,Returned,Positive,16.18,nan,4.9,unknown,value_5,NaN
15,2023-01-16,1170.0,132.0,6.0,47.36,0.28,204.5952,6.0,West,Cash,...,Electronics,2.7,Returned,Neutral,12.05,SAVE10,1.8,Requested gift wrap,value_3,NaN
17,2023-01-18,1540.0,134.0,6.0,29.59,0.04,170.4384,5.0,North,Credit Card,...,Food,4.7,Not Returned,Positive,19.48,nan,4.1,First-time customer,value_5,NaN
18,2023-01-19,1933.0,176.0,1.0,24.00,0.29,17.0400,2.0,East,Cash,...,Food,4.6,Returned,Negative,15.97,SAVE10,4.2,First-time customer,value_5,NaN
19,2023-01-20,1766.0,123.0,1.0,52.26,0.18,42.8532,9.0,North,Cash,...,Electronics,1.9,Not Returned,Positive,18.30,SAVE10,4.5,Preferred morning delivery,value_2,NaN
21,2023-01-22,1710.0,199.0,5.0,69.14,0.19,280.0170,9.0,West,Cash,...,Electronics,1.4,Returned,Negative,17.26,SAVE10,1.1,Preferred morning delivery,unknown,NaN
24,2023-01-25,1611.0,182.0,8.0,74.62,0.26,441.7504,5.0,North,Credit Card,...,Electronics,5.0,Not Returned,Negative,5.81,FREESHIP,1.9,unknown,unknown,NaN
25,2023-01-26,1269.0,187.0,6.0,68.99,0.04,397.3824,3.0,South,Online,...,Food,4.1,Not Returned,Negative,8.57,WELCOME5,1.1,unknown,unknown,NaN
26,2023-01-27,1805.0,165.0,9.0,37.33,0.26,248.6178,5.0,East,Cash,...,Electronics,4.2,Returned,Negative,16.55,nan,2.2,First-time customer,value_2,NaN
27,2023-01-28,1364.0,155.0,1.0,73.55,0.26,54.4270,1.0,South,Credit Card,...,Clothing,4.6,Returned,Neutral,19.56,FREESHIP,3.7,unknown,unknown,NaN
28,2023-01-29,1784.0,181.0,4.0,24.89,0.08,91.5952,7.0,North,Cash,...,Electronics,1.0,Not Returned,Neutral,7.02,SAVE10,2.2,unknown,unknown,NaN
30,2023-01-31,1276.0,155.0,8.0,52.73,0.19,341.6904,9.0,East,Credit Card,...,Clothing,5.0,Not Returned,Negative,16.50,WELCOME5,2.6,unknown,no_data,NaN
33,2023-02-03,1411.0,102.0,4.0,79.94,0.24,243.0176,2.0,North,Credit Card,...,Electronics,1.0,Not Returned,Neutral,8.56,nan,4.9,Used loyalty points,value_5,NaN

<div class="alert alert-warning">

**10. Keep Only Valid Entries**

**Write a Pandas program to keep the valid entries of a given DataFrame.**

</div>

In [24]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_6482/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1793.0,191.0,1.0,27.36,0.06,25.7184,1.0,North,Online,...,Food,3.0,Returned,Positive,7.24,nan,2.2,no_data,unknown,NaN
1,2023-01-02,1723.0,168.0,6.0,75.63,0.11,403.8642,5.0,South,Cash,...,Food,4.2,Returned,Negative,7.30,nan,NaN,Used loyalty points,unknown,NaN
2,2023-01-03,1233.0,169.0,5.0,29.64,0.04,142.2720,4.0,East,Online,...,Food,2.1,Returned,Neutral,11.71,WELCOME5,NaN,no_data,no_data,NaN
3,2023-01-04,1233.0,173.0,9.0,99.95,0.06,845.5770,5.0,East,Credit Card,...,Clothing,1.1,Not Returned,Negative,7.10,WELCOME5,1.9,no_data,value_2,NaN
4,2023-01-05,1083.0,174.0,3.0,72.52,0.16,182.7504,5.0,East,Credit Card,...,Books,1.0,Returned,Negative,9.94,SAVE10,2.8,Requested gift wrap,value_3,NaN
5,2023-01-06,1892.0,175.0,5.0,33.84,0.21,133.6680,2.0,North,Cash,...,Electronics,2.5,Returned,Positive,7.88,FREESHIP,2.2,Frequent buyer,value_1,NaN
6,2023-01-07,1525.0,182.0,2.0,81.57,0.07,151.7202,4.0,East,Credit Card,...,Electronics,1.0,Not Returned,Neutral,NaN,WELCOME5,4.1,Requested gift wrap,value_1,NaN
7,2023-01-08,1577.0,142.0,7.0,14.84,0.04,99.7248,3.0,South,Online,...,Books,4.4,Not Returned,Neutral,NaN,FREESHIP,NaN,unknown,unknown,NaN
8,2023-01-09,1911.0,116.0,2.0,10.18,0.03,19.7492,2.0,East,Credit Card,...,Food,2.5,Returned,Negative,19.22,WELCOME5,2.4,no_data,no_data,NaN
9,2023-01-10,1652.0,116.0,9.0,13.92,0.22,97.7184,6.0,South,Online,...,Books,4.0,Not Returned,Neutral,14.57,nan,4.6,Requested gift wrap,unknown,NaN
10,2023-01-11,1424.0,122.0,1.0,89.04,0.29,63.2184,4.0,North,Online,...,Food,1.2,Not Returned,Positive,13.85,WELCOME5,2.5,no_data,unknown,NaN
11,2023-01-12,1014.0,148.0,6.0,47.83,0.17,238.1934,9.0,North,Credit Card,...,Clothing,4.9,Returned,Neutral,14.01,WELCOME5,1.5,Frequent buyer,value_2,NaN
12,2023-01-13,1795.0,163.0,8.0,48.29,0.17,320.6456,5.0,West,Cash,...,Food,3.7,Returned,Neutral,15.59,nan,2.1,First-time customer,unknown,NaN
13,2023-01-14,1226.0,112.0,8.0,53.17,0.15,361.5560,9.0,East,Cash,...,Clothing,3.8,Returned,Positive,6.12,nan,NaN,no_data,value_4,NaN
14,2023-01-15,1938.0,180.0,8.0,16.92,0.19,109.6416,8.0,North,Online,...,Electronics,4.1,Returned,Negative,NaN,nan,2.8,no_data,no_data,NaN
15,2023-01-16,1497.0,169.0,2.0,86.59,0.24,131.6168,1.0,South,Online,...,Electronics,2.7,Returned,Neutral,8.04,WELCOME5,NaN,Preferred morning delivery,value_5,NaN
16,2023-01-17,1521.0,183.0,5.0,72.66,0.18,297.9060,8.0,North,Online,...,Food,3.2,Returned,Positive,9.53,WELCOME5,2.4,no_data,value_4,NaN
17,2023-01-18,1032.0,126.0,1.0,49.43,0.02,48.4414,6.0,West,Cash,...,Food,4.9,Not Returned,Negative,10.22,WELCOME5,4.3,Preferred morning delivery,no_data,NaN
18,2023-01-19,1139.0,145.0,1.0,18.40,0.19,14.9040,9.0,North,Online,...,Books,2.2,Returned,Negative,6.87,nan,NaN,unknown,no_data,NaN
19,2023-01-20,1222.0,134.0,5.0,47.66,0.19,193.0230,3.0,West,Credit Card,...,Food,1.1,Not Returned,Neutral,5.93,nan,2.5,no_data,unknown,NaN
20,2023-01-21,1732.0,120.0,8.0,91.36,0.26,540.8512,5.0,South,Online,...,Food,4.3,Returned,Positive,6.03,WELCOME5,NaN,Preferred morning delivery,value_1,NaN
21,2023-01-22,1364.0,192.0,1.0,76.02,0.30,53.2140,9.0,East,Online,...,Books,3.3,Not Returned,Neutral,NaN,nan,4.0,no_data,value_1,NaN
22,2023-01-23,1325.0,182.0,7.0,51.85,0.17,301.2485,3.0,South,Credit Card,...,Clothing,4.2,Not Returned,Negative,16.97,SAVE10,NaN,unknown,value_3,NaN
23,2023-01-24,1051.0,150.0,4.0,70.71,0.22,220.6152,8.0,South,Online,...,Food,4.4,Returned,Negative,12.05,WELCOME5,NaN,Used loyalty points,value_1,NaN
24,2023-01-25,1450.0,163.0,3.0,47.02,0.05,134.0070,3.0,South,Credit Card,...,Books,4.1,Not Returned,Neutral,5.17,SAVE10,3.6,no_data,unknown,NaN
25,2023-01-26,1254.0,119.0,1.0,16.93,0.01,16.7607,6.0,South,Credit Card,...,Books,3.1,Returned,Neutral,NaN,SAVE10,NaN,Frequent buyer,value_5,NaN
26,2023-01-27,1910.0,111.0,8.0,50.20,0.18,329.3120,8.0,North,Credit Card,...,Clothing,4.7,Not Returned,Positive,14.21,nan,3.5,Used loyalty points,no_data,NaN
27,2023-01-28,1948.0,175.0,4.0,39.54,0.11,140.7624,1.0,East,Online,...,Food,1.7,Not Returned,Neutral,11.91,WELCOME5,1.2,unknown,value_4,NaN
28,2023-01-29,1553.0,110.0,5.0,80.16,0.19,324.6480,6.0,East,Online,...,Books,1.1,Not Returned,Positive,12.37,nan,4.1,Used loyalty points,unknown,NaN
29,2023-01-30,1711.0,117.0,3.0,45.94,0.27,100.6086,4.0,East,Credit Card,...,Electronics,3.1,Returned,Positive,8.90,nan,3.0,unknown,value_4,NaN
30,2023-01-31,1570.0,190.0,9.0,81.67,0.20,588.0240,6.0,North,Online,...,Electronics,4.6,Returned,Positive,13.38,nan,NaN,First-time customer,value_4,NaN
31,2023-02-01,1171.0,118.0,9.0,28.21,0.06,238.6566,7.0,North,Cash,...,Books,2.2,Returned,Positive,15.57,nan,2.1,Frequent buyer,no_data,NaN
32,2023-02-02,1998.0,198.0,3.0,60.12,0.29,128.0556,8.0,North,Cash,...,Books,2.1,Returned,Neutral,5.94,SAVE10,NaN,no_data,no_data,NaN
33,2023-02-03,1955.0,123.0,8.0,55.10,0.21,348.2320,6.0,South,Credit Card,...,Clothing,2.0,Returned,Positive,9.74,SAVE10,2.5,unknown,value_4,NaN
34,2023-02-04,1635.0,171.0,8.0,10.73,0.18,70.3888,2.0,West,Online,...,Books,4.9,Not Returned,Neutral,11.45,nan,NaN,Frequent buyer,value_3,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 10:**
</div>

In [25]:
# Write a Pandas program to keep the valid entries of a given DataFrame
valid_entries_df = df.dropna(subset=['customer_id', 'product_id', 'quantity', 'price', 'revenue', 'delivery_rating'])
display(valid_entries_df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1793.0,191.0,1.0,27.36,0.06,25.7184,1.0,North,Online,...,Food,3.0,Returned,Positive,7.24,nan,2.2,no_data,unknown,NaN
3,2023-01-04,1233.0,173.0,9.0,99.95,0.06,845.5770,5.0,East,Credit Card,...,Clothing,1.1,Not Returned,Negative,7.10,WELCOME5,1.9,no_data,value_2,NaN
4,2023-01-05,1083.0,174.0,3.0,72.52,0.16,182.7504,5.0,East,Credit Card,...,Books,1.0,Returned,Negative,9.94,SAVE10,2.8,Requested gift wrap,value_3,NaN
5,2023-01-06,1892.0,175.0,5.0,33.84,0.21,133.6680,2.0,North,Cash,...,Electronics,2.5,Returned,Positive,7.88,FREESHIP,2.2,Frequent buyer,value_1,NaN
6,2023-01-07,1525.0,182.0,2.0,81.57,0.07,151.7202,4.0,East,Credit Card,...,Electronics,1.0,Not Returned,Neutral,NaN,WELCOME5,4.1,Requested gift wrap,value_1,NaN
8,2023-01-09,1911.0,116.0,2.0,10.18,0.03,19.7492,2.0,East,Credit Card,...,Food,2.5,Returned,Negative,19.22,WELCOME5,2.4,no_data,no_data,NaN
9,2023-01-10,1652.0,116.0,9.0,13.92,0.22,97.7184,6.0,South,Online,...,Books,4.0,Not Returned,Neutral,14.57,nan,4.6,Requested gift wrap,unknown,NaN
10,2023-01-11,1424.0,122.0,1.0,89.04,0.29,63.2184,4.0,North,Online,...,Food,1.2,Not Returned,Positive,13.85,WELCOME5,2.5,no_data,unknown,NaN
11,2023-01-12,1014.0,148.0,6.0,47.83,0.17,238.1934,9.0,North,Credit Card,...,Clothing,4.9,Returned,Neutral,14.01,WELCOME5,1.5,Frequent buyer,value_2,NaN
12,2023-01-13,1795.0,163.0,8.0,48.29,0.17,320.6456,5.0,West,Cash,...,Food,3.7,Returned,Neutral,15.59,nan,2.1,First-time customer,unknown,NaN
14,2023-01-15,1938.0,180.0,8.0,16.92,0.19,109.6416,8.0,North,Online,...,Electronics,4.1,Returned,Negative,NaN,nan,2.8,no_data,no_data,NaN
16,2023-01-17,1521.0,183.0,5.0,72.66,0.18,297.9060,8.0,North,Online,...,Food,3.2,Returned,Positive,9.53,WELCOME5,2.4,no_data,value_4,NaN
17,2023-01-18,1032.0,126.0,1.0,49.43,0.02,48.4414,6.0,West,Cash,...,Food,4.9,Not Returned,Negative,10.22,WELCOME5,4.3,Preferred morning delivery,no_data,NaN
19,2023-01-20,1222.0,134.0,5.0,47.66,0.19,193.0230,3.0,West,Credit Card,...,Food,1.1,Not Returned,Neutral,5.93,nan,2.5,no_data,unknown,NaN
21,2023-01-22,1364.0,192.0,1.0,76.02,0.30,53.2140,9.0,East,Online,...,Books,3.3,Not Returned,Neutral,NaN,nan,4.0,no_data,value_1,NaN
24,2023-01-25,1450.0,163.0,3.0,47.02,0.05,134.0070,3.0,South,Credit Card,...,Books,4.1,Not Returned,Neutral,5.17,SAVE10,3.6,no_data,unknown,NaN
26,2023-01-27,1910.0,111.0,8.0,50.20,0.18,329.3120,8.0,North,Credit Card,...,Clothing,4.7,Not Returned,Positive,14.21,nan,3.5,Used loyalty points,no_data,NaN
27,2023-01-28,1948.0,175.0,4.0,39.54,0.11,140.7624,1.0,East,Online,...,Food,1.7,Not Returned,Neutral,11.91,WELCOME5,1.2,unknown,value_4,NaN
28,2023-01-29,1553.0,110.0,5.0,80.16,0.19,324.6480,6.0,East,Online,...,Books,1.1,Not Returned,Positive,12.37,nan,4.1,Used loyalty points,unknown,NaN
29,2023-01-30,1711.0,117.0,3.0,45.94,0.27,100.6086,4.0,East,Credit Card,...,Electronics,3.1,Returned,Positive,8.90,nan,3.0,unknown,value_4,NaN
31,2023-02-01,1171.0,118.0,9.0,28.21,0.06,238.6566,7.0,North,Cash,...,Books,2.2,Returned,Positive,15.57,nan,2.1,Frequent buyer,no_data,NaN
33,2023-02-03,1955.0,123.0,8.0,55.10,0.21,348.2320,6.0,South,Credit Card,...,Clothing,2.0,Returned,Positive,9.74,SAVE10,2.5,unknown,value_4,NaN

<div class="alert alert-warning">

**11. Total Number of Missing Values in DataFrame**

**Write a Pandas program to calculate the total number of missing values in a DataFrame.**

</div>

In [26]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_6482/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1444.0,100.0,9.0,42.21,0.11,338.1021,6.0,South,Credit Card,...,Food,3.2,Not Returned,Negative,NaN,WELCOME5,NaN,no_data,no_data,NaN
1,2023-01-02,1294.0,177.0,1.0,44.46,0.02,43.5708,8.0,East,Online,...,Clothing,4.9,Not Returned,Neutral,16.15,FREESHIP,2.5,no_data,value_3,NaN
2,2023-01-03,1794.0,126.0,2.0,15.12,0.05,28.7280,4.0,West,Credit Card,...,Electronics,1.2,Returned,Negative,NaN,FREESHIP,1.2,unknown,unknown,NaN
3,2023-01-04,1540.0,191.0,2.0,68.49,0.07,127.3914,2.0,West,Online,...,Food,2.3,Not Returned,Negative,16.33,SAVE10,NaN,unknown,value_2,NaN
4,2023-01-05,1058.0,132.0,2.0,54.20,0.24,82.3840,9.0,East,Cash,...,Books,4.3,Returned,Neutral,17.27,SAVE10,4.2,Used loyalty points,value_1,NaN
5,2023-01-06,1394.0,105.0,7.0,43.77,0.09,278.8149,8.0,East,Credit Card,...,Books,2.5,Returned,Negative,NaN,nan,NaN,no_data,value_3,NaN
6,2023-01-07,1871.0,147.0,1.0,24.34,0.10,21.9060,3.0,North,Credit Card,...,Food,2.3,Returned,Positive,17.53,nan,4.9,Preferred morning delivery,value_2,NaN
7,2023-01-08,1634.0,138.0,9.0,41.44,0.25,279.7200,5.0,South,Online,...,Books,1.8,Returned,Positive,14.19,nan,NaN,Preferred morning delivery,unknown,NaN
8,2023-01-09,1215.0,107.0,4.0,22.14,0.27,64.6488,2.0,West,Online,...,Clothing,4.3,Not Returned,Positive,18.07,FREESHIP,1.6,Preferred morning delivery,value_3,NaN
9,2023-01-10,1435.0,117.0,1.0,67.64,0.23,52.0828,4.0,East,Cash,...,Books,1.0,Not Returned,Neutral,11.64,nan,1.6,Requested gift wrap,value_2,NaN
10,2023-01-11,1485.0,187.0,8.0,50.07,0.03,388.5432,7.0,West,Credit Card,...,Books,1.1,Not Returned,Negative,16.74,SAVE10,4.9,unknown,value_2,NaN
11,2023-01-12,1544.0,172.0,4.0,63.98,0.05,243.1240,1.0,West,Cash,...,Food,2.9,Returned,Neutral,NaN,WELCOME5,3.3,no_data,value_5,NaN
12,2023-01-13,1391.0,101.0,2.0,32.32,0.07,60.1152,8.0,West,Credit Card,...,Clothing,3.5,Not Returned,Positive,18.52,SAVE10,NaN,First-time customer,value_4,NaN
13,2023-01-14,1842.0,150.0,6.0,43.12,0.19,209.5632,7.0,East,Credit Card,...,Clothing,3.5,Returned,Positive,NaN,nan,3.1,Frequent buyer,no_data,NaN
14,2023-01-15,1312.0,199.0,2.0,83.57,0.18,137.0548,1.0,South,Credit Card,...,Clothing,3.1,Returned,Neutral,NaN,SAVE10,4.5,no_data,no_data,NaN
15,2023-01-16,1669.0,164.0,4.0,45.86,0.24,139.4144,7.0,South,Cash,...,Food,3.4,Returned,Positive,9.57,SAVE10,2.6,unknown,unknown,NaN
16,2023-01-17,1558.0,146.0,3.0,62.17,0.08,171.5892,7.0,West,Credit Card,...,Electronics,2.4,Returned,Neutral,5.17,nan,4.2,no_data,value_2,NaN
17,2023-01-18,1754.0,135.0,6.0,24.50,0.06,138.1800,4.0,South,Online,...,Food,3.1,Returned,Positive,12.54,nan,NaN,unknown,unknown,NaN
18,2023-01-19,1113.0,183.0,7.0,84.76,0.12,522.1216,5.0,South,Credit Card,...,Food,3.2,Returned,Negative,5.44,SAVE10,NaN,no_data,value_3,NaN
19,2023-01-20,1799.0,170.0,4.0,30.88,0.21,97.5808,9.0,East,Cash,...,Electronics,4.8,Not Returned,Positive,NaN,nan,NaN,Frequent buyer,value_4,NaN
20,2023-01-21,1282.0,162.0,1.0,74.16,0.18,60.8112,2.0,South,Credit Card,...,Food,1.5,Returned,Negative,11.56,SAVE10,2.4,no_data,unknown,NaN
21,2023-01-22,1580.0,136.0,3.0,27.63,0.19,67.1409,8.0,North,Cash,...,Food,2.0,Not Returned,Negative,13.40,nan,2.8,no_data,value_4,NaN
22,2023-01-23,1074.0,184.0,7.0,65.87,0.08,424.2028,7.0,North,Credit Card,...,Books,4.9,Not Returned,Positive,NaN,FREESHIP,1.6,Frequent buyer,unknown,NaN
23,2023-01-24,1186.0,125.0,6.0,85.81,0.02,504.5628,4.0,East,Online,...,Electronics,4.7,Not Returned,Negative,5.10,SAVE10,NaN,no_data,no_data,NaN
24,2023-01-25,1889.0,129.0,3.0,69.16,0.29,147.3108,9.0,East,Credit Card,...,Clothing,4.7,Returned,Positive,7.57,nan,2.5,First-time customer,value_1,NaN
25,2023-01-26,1541.0,126.0,4.0,51.53,0.24,156.6512,3.0,West,Cash,...,Books,1.6,Not Returned,Positive,7.95,SAVE10,NaN,no_data,value_3,NaN
26,2023-01-27,1447.0,162.0,2.0,88.89,0.28,128.0016,6.0,South,Cash,...,Books,3.5,Returned,Negative,NaN,nan,NaN,First-time customer,no_data,NaN
27,2023-01-28,1814.0,115.0,4.0,14.45,0.25,43.3500,6.0,South,Cash,...,Books,4.7,Not Returned,Negative,19.86,FREESHIP,2.4,no_data,unknown,NaN
28,2023-01-29,1938.0,162.0,5.0,39.44,0.01,195.2280,3.0,North,Cash,...,Clothing,4.0,Returned,Neutral,6.40,WELCOME5,3.8,First-time customer,unknown,NaN
29,2023-01-30,1576.0,143.0,7.0,46.97,0.16,276.1836,2.0,West,Online,...,Books,1.0,Returned,Neutral,14.31,FREESHIP,NaN,Frequent buyer,unknown,NaN
30,2023-01-31,1899.0,104.0,1.0,84.71,0.08,77.9332,6.0,South,Credit Card,...,Clothing,4.5,Not Returned,Negative,NaN,nan,NaN,Used loyalty points,unknown,NaN
31,2023-02-01,1961.0,182.0,7.0,39.18,0.14,235.8636,2.0,East,Cash,...,Clothing,4.7,Not Returned,Neutral,18.43,nan,NaN,First-time customer,value_3,NaN
32,2023-02-02,1443.0,150.0,8.0,10.80,0.26,63.9360,5.0,East,Online,...,Electronics,4.8,Returned,Positive,11.03,nan,1.8,Used loyalty points,unknown,NaN
33,2023-02-03,1506.0,129.0,5.0,21.62,0.09,98.3710,6.0,West,Online,...,Food,2.1,Not Returned,Negative,10.46,WELCOME5,1.7,no_data,value_3,NaN
34,2023-02-04,1578.0,190.0,2.0,31.26,0.20,50.0160,3.0,North,Cash,...,Books,3.1,Returned,Negative,9.82,SAVE10,1.9,First-time customer,unknown,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 11:**
</div>

In [27]:
print(df.isna().sum().sum())

83

<div class="alert alert-warning">

**12. Replace NaNs with a Constant in Specified Columns**

**Write a Pandas program to replace NaNs with a single constant value in specified columns in a DataFrame.**

</div>

In [28]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_6482/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1255.0,140.0,6.0,53.54,0.20,256.9920,3.0,West,Online,...,Food,1.0,Returned,Negative,6.12,nan,1.5,Requested gift wrap,value_2,NaN
1,2023-01-02,1202.0,116.0,9.0,11.95,0.10,96.7950,4.0,West,Online,...,Books,3.5,Not Returned,Negative,17.62,nan,NaN,no_data,no_data,NaN
2,2023-01-03,1475.0,173.0,6.0,12.92,0.00,77.5200,4.0,North,Credit Card,...,Books,3.2,Returned,Positive,7.72,WELCOME5,2.7,Used loyalty points,unknown,NaN
3,2023-01-04,1821.0,108.0,5.0,28.85,0.19,116.8425,4.0,East,Cash,...,Clothing,4.3,Not Returned,Neutral,NaN,nan,3.4,no_data,unknown,NaN
4,2023-01-05,1103.0,107.0,3.0,23.59,0.11,62.9853,4.0,South,Online,...,Clothing,3.3,Returned,Positive,16.99,WELCOME5,NaN,unknown,value_1,NaN
5,2023-01-06,1782.0,140.0,1.0,16.81,0.23,12.9437,7.0,South,Credit Card,...,Books,4.7,Not Returned,Neutral,16.98,SAVE10,4.9,Requested gift wrap,unknown,NaN
6,2023-01-07,1557.0,181.0,3.0,72.89,0.10,196.8030,8.0,North,Cash,...,Books,4.4,Not Returned,Positive,NaN,SAVE10,2.3,unknown,unknown,NaN
7,2023-01-08,1493.0,169.0,7.0,38.54,0.28,194.2416,4.0,East,Cash,...,Books,1.3,Returned,Negative,16.85,SAVE10,NaN,no_data,value_5,NaN
8,2023-01-09,1483.0,190.0,3.0,55.98,0.16,141.0696,5.0,North,Cash,...,Electronics,4.5,Not Returned,Negative,7.89,WELCOME5,2.3,Used loyalty points,value_1,NaN
9,2023-01-10,1711.0,168.0,8.0,81.18,0.09,590.9904,2.0,West,Cash,...,Food,1.2,Not Returned,Negative,6.99,nan,1.4,unknown,no_data,NaN
10,2023-01-11,1560.0,138.0,9.0,14.17,0.20,102.0240,1.0,North,Online,...,Food,2.9,Returned,Negative,NaN,nan,NaN,Used loyalty points,value_4,NaN
11,2023-01-12,1092.0,181.0,6.0,26.95,0.18,132.5940,2.0,West,Credit Card,...,Books,2.3,Returned,Positive,NaN,SAVE10,3.0,no_data,no_data,NaN
12,2023-01-13,1383.0,157.0,8.0,46.43,0.25,278.5800,7.0,South,Credit Card,...,Electronics,3.4,Returned,Positive,5.72,nan,2.2,Used loyalty points,value_2,NaN
13,2023-01-14,1827.0,183.0,5.0,67.62,0.10,304.2900,5.0,East,Credit Card,...,Books,3.3,Returned,Neutral,9.32,WELCOME5,2.9,Used loyalty points,value_4,NaN
14,2023-01-15,1652.0,183.0,3.0,74.73,0.27,163.6587,3.0,South,Cash,...,Books,2.9,Not Returned,Neutral,19.38,nan,NaN,no_data,no_data,NaN
15,2023-01-16,1266.0,170.0,4.0,50.39,0.28,145.1232,4.0,East,Credit Card,...,Electronics,3.9,Not Returned,Positive,18.24,SAVE10,NaN,no_data,no_data,NaN
16,2023-01-17,1826.0,112.0,5.0,99.15,0.06,466.0050,1.0,West,Cash,...,Clothing,2.9,Not Returned,Positive,18.68,SAVE10,2.5,no_data,no_data,NaN
17,2023-01-18,1563.0,186.0,7.0,68.93,0.04,463.2096,4.0,North,Online,...,Books,1.1,Not Returned,Positive,6.99,WELCOME5,4.5,Preferred morning delivery,unknown,NaN
18,2023-01-19,1730.0,137.0,8.0,95.80,0.22,597.7920,5.0,East,Credit Card,...,Food,3.5,Not Returned,Neutral,13.04,nan,5.0,Preferred morning delivery,value_5,NaN
19,2023-01-20,1274.0,182.0,7.0,17.76,0.12,109.4016,2.0,West,Online,...,Clothing,3.4,Returned,Neutral,7.30,WELCOME5,NaN,Frequent buyer,value_3,NaN
20,2023-01-21,1066.0,111.0,1.0,63.90,0.26,47.2860,2.0,South,Credit Card,...,Electronics,1.7,Not Returned,Positive,5.86,SAVE10,4.5,First-time customer,value_5,NaN
21,2023-01-22,1337.0,173.0,8.0,19.76,0.02,154.9184,2.0,South,Cash,...,Electronics,2.1,Returned,Positive,14.35,WELCOME5,4.1,Used loyalty points,no_data,NaN
22,2023-01-23,1418.0,162.0,9.0,11.14,0.16,84.2184,1.0,South,Cash,...,Food,2.3,Not Returned,Neutral,NaN,WELCOME5,1.6,no_data,no_data,NaN
23,2023-01-24,1419.0,160.0,7.0,88.11,0.14,530.4222,5.0,North,Online,...,Books,3.1,Returned,Positive,6.40,nan,2.4,Requested gift wrap,unknown,NaN
24,2023-01-25,1132.0,128.0,6.0,57.86,0.17,288.1428,4.0,North,Credit Card,...,Books,4.0,Not Returned,Negative,11.08,FREESHIP,1.1,First-time customer,value_5,NaN
25,2023-01-26,1710.0,163.0,4.0,41.81,0.16,140.4816,8.0,East,Credit Card,...,Clothing,4.0,Returned,Positive,18.20,FREESHIP,4.2,no_data,no_data,NaN
26,2023-01-27,1260.0,179.0,7.0,81.07,0.07,527.7657,1.0,North,Online,...,Books,2.4,Returned,Positive,12.10,nan,NaN,Requested gift wrap,value_4,NaN
27,2023-01-28,1130.0,100.0,8.0,10.38,0.06,78.0576,9.0,South,Cash,...,Clothing,2.1,Returned,Positive,15.17,SAVE10,NaN,Frequent buyer,value_2,NaN
28,2023-01-29,1564.0,185.0,3.0,15.14,0.24,34.5192,8.0,West,Credit Card,...,Books,3.8,Returned,Neutral,13.53,nan,2.1,Preferred morning delivery,unknown,NaN
29,2023-01-30,1524.0,185.0,6.0,32.50,0.24,148.2000,6.0,North,Credit Card,...,Food,1.2,Not Returned,Positive,12.07,nan,NaN,unknown,value_2,NaN
30,2023-01-31,1259.0,175.0,1.0,97.39,0.29,69.1469,8.0,East,Online,...,Clothing,1.5,Not Returned,Neutral,15.09,WELCOME5,1.6,Frequent buyer,value_5,NaN
31,2023-02-01,1788.0,115.0,1.0,35.02,0.23,26.9654,5.0,East,Online,...,Books,2.4,Not Returned,Negative,NaN,FREESHIP,NaN,Preferred morning delivery,value_1,NaN
32,2023-02-02,1530.0,105.0,6.0,15.01,0.02,88.2588,3.0,South,Cash,...,Clothing,1.2,Returned,Neutral,11.25,nan,2.9,unknown,unknown,NaN
33,2023-02-03,1202.0,165.0,2.0,57.11,0.10,102.7980,2.0,South,Online,...,Books,4.2,Not Returned,Positive,NaN,WELCOME5,3.1,no_data,value_1,NaN
34,2023-02-04,1847.0,166.0,1.0,95.23,0.09,86.6593,7.0,West,Credit Card,...,Electronics,1.2,Not Returned,Positive,14.05,nan,2.3,unknown,value_1,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 12:**
</div>

In [29]:
# Write a Pandas program to fill the missing values in specific columns of a given DataFrame
df_filled = df.fillna({'shipping_cost': 0, 'coupon_code': 'NO_COUPON', 'delivery_rating': 0})
df_filled

# or we can use the `fillna` method directly on the DataFrame
df['shipping_cost'].fillna(0, inplace=True)

# or we can use the `fillna` method directly on the DataFrame with multiple columns
df.fillna(
    {
        'shipping_cost': 0
        , 'coupon_code': 'NO_COUPON'
        , 'delivery_rating': 0
    }
    , inplace=True
)

df

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_6482/3401518830.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['shipping_cost'].fillna(0, inplace=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1255.0,140.0,6.0,53.54,0.20,256.9920,3.0,West,Online,...,Food,1.0,Returned,Negative,6.12,nan,1.5,Requested gift wrap,value_2,NaN
1,2023-01-02,1202.0,116.0,9.0,11.95,0.10,96.7950,4.0,West,Online,...,Books,3.5,Not Returned,Negative,17.62,nan,0.0,no_data,no_data,NaN
2,2023-01-03,1475.0,173.0,6.0,12.92,0.00,77.5200,4.0,North,Credit Card,...,Books,3.2,Returned,Positive,7.72,WELCOME5,2.7,Used loyalty points,unknown,NaN
3,2023-01-04,1821.0,108.0,5.0,28.85,0.19,116.8425,4.0,East,Cash,...,Clothing,4.3,Not Returned,Neutral,0.00,nan,3.4,no_data,unknown,NaN
4,2023-01-05,1103.0,107.0,3.0,23.59,0.11,62.9853,4.0,South,Online,...,Clothing,3.3,Returned,Positive,16.99,WELCOME5,0.0,unknown,value_1,NaN
5,2023-01-06,1782.0,140.0,1.0,16.81,0.23,12.9437,7.0,South,Credit Card,...,Books,4.7,Not Returned,Neutral,16.98,SAVE10,4.9,Requested gift wrap,unknown,NaN
6,2023-01-07,1557.0,181.0,3.0,72.89,0.10,196.8030,8.0,North,Cash,...,Books,4.4,Not Returned,Positive,0.00,SAVE10,2.3,unknown,unknown,NaN
7,2023-01-08,1493.0,169.0,7.0,38.54,0.28,194.2416,4.0,East,Cash,...,Books,1.3,Returned,Negative,16.85,SAVE10,0.0,no_data,value_5,NaN
8,2023-01-09,1483.0,190.0,3.0,55.98,0.16,141.0696,5.0,North,Cash,...,Electronics,4.5,Not Returned,Negative,7.89,WELCOME5,2.3,Used loyalty points,value_1,NaN
9,2023-01-10,1711.0,168.0,8.0,81.18,0.09,590.9904,2.0,West,Cash,...,Food,1.2,Not Returned,Negative,6.99,nan,1.4,unknown,no_data,NaN
10,2023-01-11,1560.0,138.0,9.0,14.17,0.20,102.0240,1.0,North,Online,...,Food,2.9,Returned,Negative,0.00,nan,0.0,Used loyalty points,value_4,NaN
11,2023-01-12,1092.0,181.0,6.0,26.95,0.18,132.5940,2.0,West,Credit Card,...,Books,2.3,Returned,Positive,0.00,SAVE10,3.0,no_data,no_data,NaN
12,2023-01-13,1383.0,157.0,8.0,46.43,0.25,278.5800,7.0,South,Credit Card,...,Electronics,3.4,Returned,Positive,5.72,nan,2.2,Used loyalty points,value_2,NaN
13,2023-01-14,1827.0,183.0,5.0,67.62,0.10,304.2900,5.0,East,Credit Card,...,Books,3.3,Returned,Neutral,9.32,WELCOME5,2.9,Used loyalty points,value_4,NaN
14,2023-01-15,1652.0,183.0,3.0,74.73,0.27,163.6587,3.0,South,Cash,...,Books,2.9,Not Returned,Neutral,19.38,nan,0.0,no_data,no_data,NaN
15,2023-01-16,1266.0,170.0,4.0,50.39,0.28,145.1232,4.0,East,Credit Card,...,Electronics,3.9,Not Returned,Positive,18.24,SAVE10,0.0,no_data,no_data,NaN
16,2023-01-17,1826.0,112.0,5.0,99.15,0.06,466.0050,1.0,West,Cash,...,Clothing,2.9,Not Returned,Positive,18.68,SAVE10,2.5,no_data,no_data,NaN
17,2023-01-18,1563.0,186.0,7.0,68.93,0.04,463.2096,4.0,North,Online,...,Books,1.1,Not Returned,Positive,6.99,WELCOME5,4.5,Preferred morning delivery,unknown,NaN
18,2023-01-19,1730.0,137.0,8.0,95.80,0.22,597.7920,5.0,East,Credit Card,...,Food,3.5,Not Returned,Neutral,13.04,nan,5.0,Preferred morning delivery,value_5,NaN
19,2023-01-20,1274.0,182.0,7.0,17.76,0.12,109.4016,2.0,West,Online,...,Clothing,3.4,Returned,Neutral,7.30,WELCOME5,0.0,Frequent buyer,value_3,NaN
20,2023-01-21,1066.0,111.0,1.0,63.90,0.26,47.2860,2.0,South,Credit Card,...,Electronics,1.7,Not Returned,Positive,5.86,SAVE10,4.5,First-time customer,value_5,NaN
21,2023-01-22,1337.0,173.0,8.0,19.76,0.02,154.9184,2.0,South,Cash,...,Electronics,2.1,Returned,Positive,14.35,WELCOME5,4.1,Used loyalty points,no_data,NaN
22,2023-01-23,1418.0,162.0,9.0,11.14,0.16,84.2184,1.0,South,Cash,...,Food,2.3,Not Returned,Neutral,0.00,WELCOME5,1.6,no_data,no_data,NaN
23,2023-01-24,1419.0,160.0,7.0,88.11,0.14,530.4222,5.0,North,Online,...,Books,3.1,Returned,Positive,6.40,nan,2.4,Requested gift wrap,unknown,NaN
24,2023-01-25,1132.0,128.0,6.0,57.86,0.17,288.1428,4.0,North,Credit Card,...,Books,4.0,Not Returned,Negative,11.08,FREESHIP,1.1,First-time customer,value_5,NaN
25,2023-01-26,1710.0,163.0,4.0,41.81,0.16,140.4816,8.0,East,Credit Card,...,Clothing,4.0,Returned,Positive,18.20,FREESHIP,4.2,no_data,no_data,NaN
26,2023-01-27,1260.0,179.0,7.0,81.07,0.07,527.7657,1.0,North,Online,...,Books,2.4,Returned,Positive,12.10,nan,0.0,Requested gift wrap,value_4,NaN
27,2023-01-28,1130.0,100.0,8.0,10.38,0.06,78.0576,9.0,South,Cash,...,Clothing,2.1,Returned,Positive,15.17,SAVE10,0.0,Frequent buyer,value_2,NaN
28,2023-01-29,1564.0,185.0,3.0,15.14,0.24,34.5192,8.0,West,Credit Card,...,Books,3.8,Returned,Neutral,13.53,nan,2.1,Preferred morning delivery,unknown,NaN
29,2023-01-30,1524.0,185.0,6.0,32.50,0.24,148.2000,6.0,North,Credit Card,...,Food,1.2,Not Returned,Positive,12.07,nan,0.0,unknown,value_2,NaN
30,2023-01-31,1259.0,175.0,1.0,97.39,0.29,69.1469,8.0,East,Online,...,Clothing,1.5,Not Returned,Neutral,15.09,WELCOME5,1.6,Frequent buyer,value_5,NaN
31,2023-02-01,1788.0,115.0,1.0,35.02,0.23,26.9654,5.0,East,Online,...,Books,2.4,Not Returned,Negative,0.00,FREESHIP,0.0,Preferred morning delivery,value_1,NaN
32,2023-02-02,1530.0,105.0,6.0,15.01,0.02,88.2588,3.0,South,Cash,...,Clothing,1.2,Returned,Neutral,11.25,nan,2.9,unknown,unknown,NaN
33,2023-02-03,1202.0,165.0,2.0,57.11,0.10,102.7980,2.0,South,Online,...,Books,4.2,Not Returned,Positive,0.00,WELCOME5,3.1,no_data,value_1,NaN
34,2023-02-04,1847.0,166.0,1.0,95.23,0.09,86.6593,7.0,West,Credit Card,...,Electronics,1.2,Not Returned,Positive,14.05,nan,2.3,unknown,value_1,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.00,NO_COUPON,0.0,NaN,NaN,NaN

<div class="alert alert-warning">

**13. Replace NaNs Using Forward or Backward Fill**

**Write a Pandas program to replace NaNs with the value from the previous row or the next row in a given DataFrame.**

</div>

In [30]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_6482/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1701.0,117.0,2.0,73.94,0.28,106.4736,8.0,North,Credit Card,...,Electronics,1.1,Not Returned,Positive,16.90,SAVE10,1.7,Preferred morning delivery,value_1,NaN
1,2023-01-02,1606.0,179.0,8.0,55.95,0.22,349.1280,7.0,East,Credit Card,...,Electronics,2.3,Not Returned,Negative,6.96,nan,3.0,no_data,unknown,NaN
2,2023-01-03,1346.0,169.0,1.0,64.62,0.12,56.8656,3.0,West,Credit Card,...,Books,1.8,Not Returned,Positive,NaN,nan,3.5,Frequent buyer,unknown,NaN
3,2023-01-04,1337.0,167.0,6.0,80.07,0.29,341.0982,4.0,East,Online,...,Books,4.8,Returned,Positive,NaN,SAVE10,2.6,unknown,value_2,NaN
4,2023-01-05,1811.0,142.0,3.0,61.96,0.28,133.8336,3.0,East,Online,...,Electronics,3.1,Returned,Positive,NaN,nan,NaN,unknown,unknown,NaN
5,2023-01-06,1240.0,121.0,5.0,46.03,0.29,163.4065,5.0,South,Credit Card,...,Electronics,3.0,Not Returned,Neutral,14.84,SAVE10,4.5,unknown,value_1,NaN
6,2023-01-07,1805.0,145.0,8.0,31.16,0.23,191.9456,6.0,West,Credit Card,...,Food,4.8,Returned,Negative,6.25,SAVE10,4.3,Preferred morning delivery,no_data,NaN
7,2023-01-08,1679.0,149.0,2.0,24.87,0.02,48.7452,4.0,North,Cash,...,Clothing,4.6,Not Returned,Positive,17.97,nan,4.6,First-time customer,unknown,NaN
8,2023-01-09,1961.0,112.0,6.0,17.05,0.04,98.2080,9.0,West,Credit Card,...,Clothing,1.6,Returned,Positive,NaN,FREESHIP,NaN,unknown,unknown,NaN
9,2023-01-10,1095.0,101.0,2.0,76.40,0.01,151.2720,6.0,West,Credit Card,...,Clothing,1.8,Returned,Negative,17.92,SAVE10,NaN,Requested gift wrap,unknown,NaN
10,2023-01-11,1045.0,169.0,2.0,69.08,0.25,103.6200,5.0,North,Credit Card,...,Books,4.7,Not Returned,Neutral,NaN,SAVE10,4.0,unknown,value_3,NaN
11,2023-01-12,1173.0,175.0,3.0,64.36,0.23,148.6716,3.0,East,Online,...,Clothing,2.3,Not Returned,Negative,12.06,FREESHIP,3.8,Requested gift wrap,unknown,NaN
12,2023-01-13,1253.0,154.0,1.0,50.44,0.17,41.8652,9.0,West,Online,...,Books,1.3,Not Returned,Neutral,19.16,nan,NaN,Frequent buyer,no_data,NaN
13,2023-01-14,1432.0,143.0,1.0,95.83,0.20,76.6640,7.0,East,Cash,...,Books,4.7,Returned,Positive,17.62,nan,3.8,Preferred morning delivery,unknown,NaN
14,2023-01-15,1731.0,190.0,1.0,72.26,0.22,56.3628,5.0,North,Online,...,Clothing,2.5,Not Returned,Neutral,5.07,nan,NaN,Preferred morning delivery,value_3,NaN
15,2023-01-16,1408.0,158.0,2.0,54.03,0.01,106.9794,8.0,South,Credit Card,...,Electronics,1.1,Not Returned,Negative,NaN,WELCOME5,NaN,unknown,no_data,NaN
16,2023-01-17,1223.0,116.0,8.0,50.61,0.04,388.6848,4.0,East,Online,...,Food,2.6,Returned,Neutral,12.60,FREESHIP,4.8,First-time customer,value_3,NaN
17,2023-01-18,1694.0,137.0,4.0,68.49,0.23,210.9492,1.0,South,Cash,...,Clothing,4.6,Returned,Positive,12.56,FREESHIP,1.0,Requested gift wrap,unknown,NaN
18,2023-01-19,1644.0,130.0,2.0,26.57,0.14,45.7004,8.0,East,Credit Card,...,Clothing,2.0,Not Returned,Negative,NaN,FREESHIP,NaN,Frequent buyer,value_1,NaN
19,2023-01-20,1809.0,165.0,2.0,45.92,0.24,69.7984,1.0,East,Online,...,Electronics,4.8,Returned,Neutral,NaN,FREESHIP,4.9,unknown,value_3,NaN
20,2023-01-21,1905.0,142.0,7.0,98.62,0.09,628.2094,2.0,West,Online,...,Books,4.0,Not Returned,Positive,19.21,nan,2.2,unknown,value_3,NaN
21,2023-01-22,1007.0,109.0,3.0,12.67,0.17,31.5483,1.0,South,Credit Card,...,Books,1.8,Returned,Positive,6.70,nan,3.8,First-time customer,value_4,NaN
22,2023-01-23,1575.0,180.0,7.0,47.92,0.12,295.1872,7.0,West,Credit Card,...,Food,4.1,Returned,Neutral,13.63,FREESHIP,3.6,unknown,value_4,NaN
23,2023-01-24,1023.0,139.0,3.0,95.20,0.03,277.0320,3.0,East,Credit Card,...,Clothing,2.0,Returned,Negative,NaN,nan,3.2,First-time customer,unknown,NaN
24,2023-01-25,1416.0,171.0,6.0,51.30,0.26,227.7720,2.0,West,Cash,...,Clothing,4.0,Returned,Neutral,8.84,SAVE10,NaN,no_data,value_3,NaN
25,2023-01-26,1466.0,186.0,1.0,92.28,0.12,81.2064,1.0,South,Credit Card,...,Clothing,4.6,Not Returned,Positive,17.26,WELCOME5,3.3,Preferred morning delivery,value_1,NaN
26,2023-01-27,1851.0,190.0,1.0,26.35,0.10,23.7150,1.0,East,Credit Card,...,Clothing,2.3,Not Returned,Positive,NaN,FREESHIP,4.8,Frequent buyer,value_4,NaN
27,2023-01-28,1950.0,197.0,8.0,71.51,0.07,532.0344,6.0,East,Online,...,Books,2.3,Not Returned,Neutral,19.98,WELCOME5,NaN,no_data,value_5,NaN
28,2023-01-29,1083.0,180.0,7.0,54.67,0.07,355.9017,7.0,South,Online,...,Clothing,4.2,Not Returned,Negative,8.73,SAVE10,4.1,unknown,no_data,NaN
29,2023-01-30,1855.0,108.0,1.0,52.36,0.17,43.4588,6.0,West,Credit Card,...,Books,1.6,Returned,Positive,8.45,WELCOME5,2.9,Frequent buyer,value_3,NaN
30,2023-01-31,1329.0,185.0,5.0,18.24,0.15,77.5200,1.0,South,Credit Card,...,Clothing,1.3,Returned,Neutral,17.86,FREESHIP,1.3,Used loyalty points,value_4,NaN
31,2023-02-01,1389.0,133.0,5.0,22.78,0.18,93.3980,6.0,West,Credit Card,...,Food,5.0,Not Returned,Positive,NaN,SAVE10,2.4,Used loyalty points,value_3,NaN
32,2023-02-02,1660.0,128.0,2.0,46.58,0.13,81.0492,5.0,West,Credit Card,...,Electronics,5.0,Not Returned,Negative,18.90,nan,NaN,First-time customer,value_3,NaN
33,2023-02-03,1945.0,142.0,4.0,67.63,0.04,259.6992,2.0,North,Credit Card,...,Food,1.7,Not Returned,Neutral,NaN,WELCOME5,2.3,Used loyalty points,value_5,NaN
34,2023-02-04,1340.0,171.0,5.0,97.80,0.22,381.4200,9.0,East,Cash,...,Electronics,4.1,Not Returned,Negative,11.12,nan,2.4,unknown,no_data,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 13:**
</div>

In [31]:
# Write a Pandas program to replace NaNs with the value from the previous row or the next row in a given DataFrame.
pd.set_option('future.no_silent_downcasting', True)
df_bfill = df.bfill().infer_objects(copy=False)  # Backward fill
df_ffill = df.ffill().infer_objects(copy=False)  # Forward fill

display(df_bfill)
display(df_ffill)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1701.0,117.0,2.0,73.94,0.28,106.4736,8.0,North,Credit Card,...,Electronics,1.1,Not Returned,Positive,16.90,SAVE10,1.7,Preferred morning delivery,value_1,NaN
1,2023-01-02,1606.0,179.0,8.0,55.95,0.22,349.1280,7.0,East,Credit Card,...,Electronics,2.3,Not Returned,Negative,6.96,nan,3.0,no_data,unknown,NaN
2,2023-01-03,1346.0,169.0,1.0,64.62,0.12,56.8656,3.0,West,Credit Card,...,Books,1.8,Not Returned,Positive,14.84,nan,3.5,Frequent buyer,unknown,NaN
3,2023-01-04,1337.0,167.0,6.0,80.07,0.29,341.0982,4.0,East,Online,...,Books,4.8,Returned,Positive,14.84,SAVE10,2.6,unknown,value_2,NaN
4,2023-01-05,1811.0,142.0,3.0,61.96,0.28,133.8336,3.0,East,Online,...,Electronics,3.1,Returned,Positive,14.84,nan,4.5,unknown,unknown,NaN
5,2023-01-06,1240.0,121.0,5.0,46.03,0.29,163.4065,5.0,South,Credit Card,...,Electronics,3.0,Not Returned,Neutral,14.84,SAVE10,4.5,unknown,value_1,NaN
6,2023-01-07,1805.0,145.0,8.0,31.16,0.23,191.9456,6.0,West,Credit Card,...,Food,4.8,Returned,Negative,6.25,SAVE10,4.3,Preferred morning delivery,no_data,NaN
7,2023-01-08,1679.0,149.0,2.0,24.87,0.02,48.7452,4.0,North,Cash,...,Clothing,4.6,Not Returned,Positive,17.97,nan,4.6,First-time customer,unknown,NaN
8,2023-01-09,1961.0,112.0,6.0,17.05,0.04,98.2080,9.0,West,Credit Card,...,Clothing,1.6,Returned,Positive,17.92,FREESHIP,4.0,unknown,unknown,NaN
9,2023-01-10,1095.0,101.0,2.0,76.40,0.01,151.2720,6.0,West,Credit Card,...,Clothing,1.8,Returned,Negative,17.92,SAVE10,4.0,Requested gift wrap,unknown,NaN
10,2023-01-11,1045.0,169.0,2.0,69.08,0.25,103.6200,5.0,North,Credit Card,...,Books,4.7,Not Returned,Neutral,12.06,SAVE10,4.0,unknown,value_3,NaN
11,2023-01-12,1173.0,175.0,3.0,64.36,0.23,148.6716,3.0,East,Online,...,Clothing,2.3,Not Returned,Negative,12.06,FREESHIP,3.8,Requested gift wrap,unknown,NaN
12,2023-01-13,1253.0,154.0,1.0,50.44,0.17,41.8652,9.0,West,Online,...,Books,1.3,Not Returned,Neutral,19.16,nan,3.8,Frequent buyer,no_data,NaN
13,2023-01-14,1432.0,143.0,1.0,95.83,0.20,76.6640,7.0,East,Cash,...,Books,4.7,Returned,Positive,17.62,nan,3.8,Preferred morning delivery,unknown,NaN
14,2023-01-15,1731.0,190.0,1.0,72.26,0.22,56.3628,5.0,North,Online,...,Clothing,2.5,Not Returned,Neutral,5.07,nan,4.8,Preferred morning delivery,value_3,NaN
15,2023-01-16,1408.0,158.0,2.0,54.03,0.01,106.9794,8.0,South,Credit Card,...,Electronics,1.1,Not Returned,Negative,12.60,WELCOME5,4.8,unknown,no_data,NaN
16,2023-01-17,1223.0,116.0,8.0,50.61,0.04,388.6848,4.0,East,Online,...,Food,2.6,Returned,Neutral,12.60,FREESHIP,4.8,First-time customer,value_3,NaN
17,2023-01-18,1694.0,137.0,4.0,68.49,0.23,210.9492,1.0,South,Cash,...,Clothing,4.6,Returned,Positive,12.56,FREESHIP,1.0,Requested gift wrap,unknown,NaN
18,2023-01-19,1644.0,130.0,2.0,26.57,0.14,45.7004,8.0,East,Credit Card,...,Clothing,2.0,Not Returned,Negative,19.21,FREESHIP,4.9,Frequent buyer,value_1,NaN
19,2023-01-20,1809.0,165.0,2.0,45.92,0.24,69.7984,1.0,East,Online,...,Electronics,4.8,Returned,Neutral,19.21,FREESHIP,4.9,unknown,value_3,NaN
20,2023-01-21,1905.0,142.0,7.0,98.62,0.09,628.2094,2.0,West,Online,...,Books,4.0,Not Returned,Positive,19.21,nan,2.2,unknown,value_3,NaN
21,2023-01-22,1007.0,109.0,3.0,12.67,0.17,31.5483,1.0,South,Credit Card,...,Books,1.8,Returned,Positive,6.70,nan,3.8,First-time customer,value_4,NaN
22,2023-01-23,1575.0,180.0,7.0,47.92,0.12,295.1872,7.0,West,Credit Card,...,Food,4.1,Returned,Neutral,13.63,FREESHIP,3.6,unknown,value_4,NaN
23,2023-01-24,1023.0,139.0,3.0,95.20,0.03,277.0320,3.0,East,Credit Card,...,Clothing,2.0,Returned,Negative,8.84,nan,3.2,First-time customer,unknown,NaN
24,2023-01-25,1416.0,171.0,6.0,51.30,0.26,227.7720,2.0,West,Cash,...,Clothing,4.0,Returned,Neutral,8.84,SAVE10,3.3,no_data,value_3,NaN
25,2023-01-26,1466.0,186.0,1.0,92.28,0.12,81.2064,1.0,South,Credit Card,...,Clothing,4.6,Not Returned,Positive,17.26,WELCOME5,3.3,Preferred morning delivery,value_1,NaN
26,2023-01-27,1851.0,190.0,1.0,26.35,0.10,23.7150,1.0,East,Credit Card,...,Clothing,2.3,Not Returned,Positive,19.98,FREESHIP,4.8,Frequent buyer,value_4,NaN
27,2023-01-28,1950.0,197.0,8.0,71.51,0.07,532.0344,6.0,East,Online,...,Books,2.3,Not Returned,Neutral,19.98,WELCOME5,4.1,no_data,value_5,NaN
28,2023-01-29,1083.0,180.0,7.0,54.67,0.07,355.9017,7.0,South,Online,...,Clothing,4.2,Not Returned,Negative,8.73,SAVE10,4.1,unknown,no_data,NaN
29,2023-01-30,1855.0,108.0,1.0,52.36,0.17,43.4588,6.0,West,Credit Card,...,Books,1.6,Returned,Positive,8.45,WELCOME5,2.9,Frequent buyer,value_3,NaN
30,2023-01-31,1329.0,185.0,5.0,18.24,0.15,77.5200,1.0,South,Credit Card,...,Clothing,1.3,Returned,Neutral,17.86,FREESHIP,1.3,Used loyalty points,value_4,NaN
31,2023-02-01,1389.0,133.0,5.0,22.78,0.18,93.3980,6.0,West,Credit Card,...,Food,5.0,Not Returned,Positive,18.90,SAVE10,2.4,Used loyalty points,value_3,NaN
32,2023-02-02,1660.0,128.0,2.0,46.58,0.13,81.0492,5.0,West,Credit Card,...,Electronics,5.0,Not Returned,Negative,18.90,nan,2.3,First-time customer,value_3,NaN
33,2023-02-03,1945.0,142.0,4.0,67.63,0.04,259.6992,2.0,North,Credit Card,...,Food,1.7,Not Returned,Neutral,11.12,WELCOME5,2.3,Used loyalty points,value_5,NaN
34,2023-02-04,1340.0,171.0,5.0,97.80,0.22,381.4200,9.0,East,Cash,...,Electronics,4.1,Not Returned,Negative,11.12,nan,2.4,unknown,no_data,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1701.0,117.0,2.0,73.94,0.28,106.4736,8.0,North,Credit Card,...,Electronics,1.1,Not Returned,Positive,16.90,SAVE10,1.7,Preferred morning delivery,value_1,NaN
1,2023-01-02,1606.0,179.0,8.0,55.95,0.22,349.1280,7.0,East,Credit Card,...,Electronics,2.3,Not Returned,Negative,6.96,nan,3.0,no_data,unknown,NaN
2,2023-01-03,1346.0,169.0,1.0,64.62,0.12,56.8656,3.0,West,Credit Card,...,Books,1.8,Not Returned,Positive,6.96,nan,3.5,Frequent buyer,unknown,NaN
3,2023-01-04,1337.0,167.0,6.0,80.07,0.29,341.0982,4.0,East,Online,...,Books,4.8,Returned,Positive,6.96,SAVE10,2.6,unknown,value_2,NaN
4,2023-01-05,1811.0,142.0,3.0,61.96,0.28,133.8336,3.0,East,Online,...,Electronics,3.1,Returned,Positive,6.96,nan,2.6,unknown,unknown,NaN
5,2023-01-06,1240.0,121.0,5.0,46.03,0.29,163.4065,5.0,South,Credit Card,...,Electronics,3.0,Not Returned,Neutral,14.84,SAVE10,4.5,unknown,value_1,NaN
6,2023-01-07,1805.0,145.0,8.0,31.16,0.23,191.9456,6.0,West,Credit Card,...,Food,4.8,Returned,Negative,6.25,SAVE10,4.3,Preferred morning delivery,no_data,NaN
7,2023-01-08,1679.0,149.0,2.0,24.87,0.02,48.7452,4.0,North,Cash,...,Clothing,4.6,Not Returned,Positive,17.97,nan,4.6,First-time customer,unknown,NaN
8,2023-01-09,1961.0,112.0,6.0,17.05,0.04,98.2080,9.0,West,Credit Card,...,Clothing,1.6,Returned,Positive,17.97,FREESHIP,4.6,unknown,unknown,NaN
9,2023-01-10,1095.0,101.0,2.0,76.40,0.01,151.2720,6.0,West,Credit Card,...,Clothing,1.8,Returned,Negative,17.92,SAVE10,4.6,Requested gift wrap,unknown,NaN
10,2023-01-11,1045.0,169.0,2.0,69.08,0.25,103.6200,5.0,North,Credit Card,...,Books,4.7,Not Returned,Neutral,17.92,SAVE10,4.0,unknown,value_3,NaN
11,2023-01-12,1173.0,175.0,3.0,64.36,0.23,148.6716,3.0,East,Online,...,Clothing,2.3,Not Returned,Negative,12.06,FREESHIP,3.8,Requested gift wrap,unknown,NaN
12,2023-01-13,1253.0,154.0,1.0,50.44,0.17,41.8652,9.0,West,Online,...,Books,1.3,Not Returned,Neutral,19.16,nan,3.8,Frequent buyer,no_data,NaN
13,2023-01-14,1432.0,143.0,1.0,95.83,0.20,76.6640,7.0,East,Cash,...,Books,4.7,Returned,Positive,17.62,nan,3.8,Preferred morning delivery,unknown,NaN
14,2023-01-15,1731.0,190.0,1.0,72.26,0.22,56.3628,5.0,North,Online,...,Clothing,2.5,Not Returned,Neutral,5.07,nan,3.8,Preferred morning delivery,value_3,NaN
15,2023-01-16,1408.0,158.0,2.0,54.03,0.01,106.9794,8.0,South,Credit Card,...,Electronics,1.1,Not Returned,Negative,5.07,WELCOME5,3.8,unknown,no_data,NaN
16,2023-01-17,1223.0,116.0,8.0,50.61,0.04,388.6848,4.0,East,Online,...,Food,2.6,Returned,Neutral,12.60,FREESHIP,4.8,First-time customer,value_3,NaN
17,2023-01-18,1694.0,137.0,4.0,68.49,0.23,210.9492,1.0,South,Cash,...,Clothing,4.6,Returned,Positive,12.56,FREESHIP,1.0,Requested gift wrap,unknown,NaN
18,2023-01-19,1644.0,130.0,2.0,26.57,0.14,45.7004,8.0,East,Credit Card,...,Clothing,2.0,Not Returned,Negative,12.56,FREESHIP,1.0,Frequent buyer,value_1,NaN
19,2023-01-20,1809.0,165.0,2.0,45.92,0.24,69.7984,1.0,East,Online,...,Electronics,4.8,Returned,Neutral,12.56,FREESHIP,4.9,unknown,value_3,NaN
20,2023-01-21,1905.0,142.0,7.0,98.62,0.09,628.2094,2.0,West,Online,...,Books,4.0,Not Returned,Positive,19.21,nan,2.2,unknown,value_3,NaN
21,2023-01-22,1007.0,109.0,3.0,12.67,0.17,31.5483,1.0,South,Credit Card,...,Books,1.8,Returned,Positive,6.70,nan,3.8,First-time customer,value_4,NaN
22,2023-01-23,1575.0,180.0,7.0,47.92,0.12,295.1872,7.0,West,Credit Card,...,Food,4.1,Returned,Neutral,13.63,FREESHIP,3.6,unknown,value_4,NaN
23,2023-01-24,1023.0,139.0,3.0,95.20,0.03,277.0320,3.0,East,Credit Card,...,Clothing,2.0,Returned,Negative,13.63,nan,3.2,First-time customer,unknown,NaN
24,2023-01-25,1416.0,171.0,6.0,51.30,0.26,227.7720,2.0,West,Cash,...,Clothing,4.0,Returned,Neutral,8.84,SAVE10,3.2,no_data,value_3,NaN
25,2023-01-26,1466.0,186.0,1.0,92.28,0.12,81.2064,1.0,South,Credit Card,...,Clothing,4.6,Not Returned,Positive,17.26,WELCOME5,3.3,Preferred morning delivery,value_1,NaN
26,2023-01-27,1851.0,190.0,1.0,26.35,0.10,23.7150,1.0,East,Credit Card,...,Clothing,2.3,Not Returned,Positive,17.26,FREESHIP,4.8,Frequent buyer,value_4,NaN
27,2023-01-28,1950.0,197.0,8.0,71.51,0.07,532.0344,6.0,East,Online,...,Books,2.3,Not Returned,Neutral,19.98,WELCOME5,4.8,no_data,value_5,NaN
28,2023-01-29,1083.0,180.0,7.0,54.67,0.07,355.9017,7.0,South,Online,...,Clothing,4.2,Not Returned,Negative,8.73,SAVE10,4.1,unknown,no_data,NaN
29,2023-01-30,1855.0,108.0,1.0,52.36,0.17,43.4588,6.0,West,Credit Card,...,Books,1.6,Returned,Positive,8.45,WELCOME5,2.9,Frequent buyer,value_3,NaN
30,2023-01-31,1329.0,185.0,5.0,18.24,0.15,77.5200,1.0,South,Credit Card,...,Clothing,1.3,Returned,Neutral,17.86,FREESHIP,1.3,Used loyalty points,value_4,NaN
31,2023-02-01,1389.0,133.0,5.0,22.78,0.18,93.3980,6.0,West,Credit Card,...,Food,5.0,Not Returned,Positive,17.86,SAVE10,2.4,Used loyalty points,value_3,NaN
32,2023-02-02,1660.0,128.0,2.0,46.58,0.13,81.0492,5.0,West,Credit Card,...,Electronics,5.0,Not Returned,Negative,18.90,nan,2.4,First-time customer,value_3,NaN
33,2023-02-03,1945.0,142.0,4.0,67.63,0.04,259.6992,2.0,North,Credit Card,...,Food,1.7,Not Returned,Neutral,18.90,WELCOME5,2.3,Used loyalty points,value_5,NaN
34,2023-02-04,1340.0,171.0,5.0,97.80,0.22,381.4200,9.0,East,Cash,...,Electronics,4.1,Not Returned,Negative,11.12,nan,2.4,unknown,no_data,NaN
35,2023-02-04,1340.0,171.0,5.0,97.80,0.22,381.4200,9.0,East,Cash,...,Electronics,4.1,Not Returned,Negative,11.12,nan,2.4,unknown,no_data,NaN

<div class="alert alert-warning">

**14. Replace NaNs with Median or Mean**

**Write a Pandas program to replace NaNs with median or mean of the specified columns in a given DataFrame.**

</div>

In [32]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_6482/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1769.0,196.0,6.0,99.48,0.18,489.4416,8.0,West,Online,...,Electronics,3.3,Not Returned,Positive,11.17,FREESHIP,3.9,no_data,value_2,NaN
1,2023-01-02,1174.0,129.0,5.0,59.79,0.02,292.9710,9.0,North,Online,...,Food,2.7,Returned,Negative,14.75,FREESHIP,NaN,no_data,unknown,NaN
2,2023-01-03,1085.0,159.0,3.0,80.92,0.26,179.6424,3.0,South,Credit Card,...,Electronics,4.3,Returned,Positive,12.39,FREESHIP,1.0,unknown,unknown,NaN
3,2023-01-04,1769.0,162.0,8.0,56.00,0.01,443.5200,2.0,North,Online,...,Books,3.0,Returned,Positive,13.46,nan,1.9,First-time customer,value_5,NaN
4,2023-01-05,1201.0,123.0,8.0,89.16,0.10,641.9520,4.0,West,Cash,...,Electronics,5.0,Returned,Positive,NaN,FREESHIP,NaN,unknown,value_1,NaN
5,2023-01-06,1459.0,166.0,2.0,83.49,0.07,155.2914,6.0,West,Online,...,Books,4.8,Not Returned,Negative,7.38,nan,2.7,unknown,no_data,NaN
6,2023-01-07,1404.0,169.0,4.0,98.85,0.27,288.6420,3.0,East,Credit Card,...,Electronics,4.3,Returned,Neutral,5.81,SAVE10,NaN,no_data,value_1,NaN
7,2023-01-08,1621.0,172.0,8.0,21.17,0.29,120.2456,8.0,South,Credit Card,...,Food,4.1,Not Returned,Negative,5.68,WELCOME5,NaN,First-time customer,value_2,NaN
8,2023-01-09,1012.0,100.0,9.0,40.27,0.03,351.5571,9.0,North,Cash,...,Electronics,4.1,Returned,Neutral,14.29,SAVE10,1.8,no_data,value_5,NaN
9,2023-01-10,1441.0,198.0,2.0,48.17,0.12,84.7792,6.0,North,Credit Card,...,Books,4.5,Returned,Negative,13.33,WELCOME5,3.4,no_data,value_5,NaN
10,2023-01-11,1065.0,159.0,8.0,65.93,0.09,479.9704,9.0,South,Online,...,Electronics,3.7,Not Returned,Negative,NaN,SAVE10,NaN,Used loyalty points,no_data,NaN
11,2023-01-12,1828.0,117.0,9.0,49.15,0.14,380.4210,7.0,North,Online,...,Food,1.1,Returned,Positive,15.89,nan,1.1,Requested gift wrap,value_3,NaN
12,2023-01-13,1326.0,140.0,7.0,17.92,0.22,97.8432,4.0,East,Credit Card,...,Electronics,3.1,Returned,Neutral,10.89,nan,NaN,no_data,value_5,NaN
13,2023-01-14,1889.0,183.0,6.0,62.40,0.00,374.4000,4.0,North,Credit Card,...,Electronics,3.4,Not Returned,Neutral,9.74,nan,NaN,unknown,value_5,NaN
14,2023-01-15,1638.0,135.0,2.0,73.93,0.13,128.6382,5.0,South,Online,...,Food,4.8,Not Returned,Neutral,16.58,nan,3.4,unknown,value_3,NaN
15,2023-01-16,1547.0,177.0,4.0,81.15,0.21,256.4340,3.0,East,Online,...,Electronics,1.5,Not Returned,Positive,14.04,nan,NaN,Frequent buyer,unknown,NaN
16,2023-01-17,1633.0,198.0,2.0,24.79,0.28,35.6976,2.0,West,Credit Card,...,Food,2.6,Not Returned,Negative,9.67,nan,NaN,no_data,value_3,NaN
17,2023-01-18,1892.0,112.0,8.0,11.01,0.11,78.3912,6.0,North,Credit Card,...,Food,4.2,Not Returned,Positive,14.15,WELCOME5,NaN,Frequent buyer,no_data,NaN
18,2023-01-19,1666.0,104.0,3.0,91.35,0.02,268.5690,1.0,North,Online,...,Books,4.7,Returned,Neutral,8.36,FREESHIP,NaN,unknown,value_1,NaN
19,2023-01-20,1224.0,134.0,7.0,20.67,0.06,136.0086,3.0,West,Credit Card,...,Books,1.2,Not Returned,Negative,12.13,nan,2.0,First-time customer,value_1,NaN
20,2023-01-21,1704.0,102.0,9.0,29.49,0.27,193.7493,5.0,West,Online,...,Clothing,4.6,Returned,Positive,NaN,WELCOME5,3.9,First-time customer,value_1,NaN
21,2023-01-22,1237.0,181.0,6.0,50.40,0.02,296.3520,2.0,North,Credit Card,...,Food,3.7,Not Returned,Positive,7.64,nan,1.4,unknown,unknown,NaN
22,2023-01-23,1321.0,130.0,9.0,29.06,0.05,248.4630,8.0,West,Cash,...,Electronics,1.1,Not Returned,Neutral,5.13,SAVE10,4.8,Used loyalty points,unknown,NaN
23,2023-01-24,1344.0,123.0,5.0,63.11,0.22,246.1290,5.0,West,Online,...,Clothing,2.0,Returned,Neutral,18.28,nan,1.0,unknown,value_3,NaN
24,2023-01-25,1290.0,130.0,8.0,28.17,0.19,182.5416,2.0,North,Credit Card,...,Food,4.9,Not Returned,Negative,NaN,SAVE10,1.8,First-time customer,value_3,NaN
25,2023-01-26,1023.0,105.0,5.0,14.54,0.07,67.6110,7.0,East,Online,...,Clothing,1.8,Returned,Negative,7.04,SAVE10,4.1,Requested gift wrap,value_2,NaN
26,2023-01-27,1753.0,122.0,4.0,13.12,0.14,45.1328,5.0,North,Credit Card,...,Food,2.7,Returned,Neutral,NaN,WELCOME5,4.7,Preferred morning delivery,unknown,NaN
27,2023-01-28,1520.0,108.0,8.0,56.57,0.23,348.4712,1.0,East,Credit Card,...,Food,4.6,Returned,Positive,NaN,nan,5.0,Frequent buyer,value_5,NaN
28,2023-01-29,1825.0,161.0,4.0,40.75,0.29,115.7300,6.0,East,Cash,...,Books,1.2,Returned,Negative,NaN,SAVE10,2.3,First-time customer,value_1,NaN
29,2023-01-30,1986.0,143.0,8.0,53.92,0.04,414.1056,4.0,North,Credit Card,...,Electronics,3.9,Not Returned,Positive,18.71,FREESHIP,2.0,unknown,no_data,NaN
30,2023-01-31,1371.0,137.0,6.0,23.53,0.03,136.9446,4.0,South,Credit Card,...,Books,3.7,Not Returned,Negative,13.67,nan,NaN,Requested gift wrap,no_data,NaN
31,2023-02-01,1641.0,184.0,6.0,96.36,0.13,502.9992,1.0,West,Credit Card,...,Electronics,2.3,Returned,Positive,6.15,SAVE10,2.1,Frequent buyer,value_2,NaN
32,2023-02-02,1699.0,143.0,6.0,15.77,0.08,87.0504,3.0,South,Online,...,Electronics,1.2,Not Returned,Negative,10.20,SAVE10,3.7,no_data,unknown,NaN
33,2023-02-03,1354.0,130.0,9.0,61.73,0.01,550.0143,4.0,South,Credit Card,...,Clothing,3.1,Returned,Positive,19.41,FREESHIP,2.0,Frequent buyer,value_4,NaN
34,2023-02-04,1256.0,149.0,3.0,72.99,0.29,155.4687,5.0,East,Credit Card,...,Electronics,1.8,Not Returned,Negative,14.05,WELCOME5,3.0,unknown,value_3,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 14:**
</div>

In [33]:
df.fillna({
    'delivery_rating': df['delivery_rating'].median(),
    'shipping_cost': df['shipping_cost'].mean()
}, inplace=True)

df

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1769.0,196.0,6.0,99.48,0.18,489.4416,8.0,West,Online,...,Electronics,3.3,Not Returned,Positive,11.170000,FREESHIP,3.9,no_data,value_2,NaN
1,2023-01-02,1174.0,129.0,5.0,59.79,0.02,292.9710,9.0,North,Online,...,Food,2.7,Returned,Negative,14.750000,FREESHIP,2.3,no_data,unknown,NaN
2,2023-01-03,1085.0,159.0,3.0,80.92,0.26,179.6424,3.0,South,Credit Card,...,Electronics,4.3,Returned,Positive,12.390000,FREESHIP,1.0,unknown,unknown,NaN
3,2023-01-04,1769.0,162.0,8.0,56.00,0.01,443.5200,2.0,North,Online,...,Books,3.0,Returned,Positive,13.460000,nan,1.9,First-time customer,value_5,NaN
4,2023-01-05,1201.0,123.0,8.0,89.16,0.10,641.9520,4.0,West,Cash,...,Electronics,5.0,Returned,Positive,11.785357,FREESHIP,2.3,unknown,value_1,NaN
5,2023-01-06,1459.0,166.0,2.0,83.49,0.07,155.2914,6.0,West,Online,...,Books,4.8,Not Returned,Negative,7.380000,nan,2.7,unknown,no_data,NaN
6,2023-01-07,1404.0,169.0,4.0,98.85,0.27,288.6420,3.0,East,Credit Card,...,Electronics,4.3,Returned,Neutral,5.810000,SAVE10,2.3,no_data,value_1,NaN
7,2023-01-08,1621.0,172.0,8.0,21.17,0.29,120.2456,8.0,South,Credit Card,...,Food,4.1,Not Returned,Negative,5.680000,WELCOME5,2.3,First-time customer,value_2,NaN
8,2023-01-09,1012.0,100.0,9.0,40.27,0.03,351.5571,9.0,North,Cash,...,Electronics,4.1,Returned,Neutral,14.290000,SAVE10,1.8,no_data,value_5,NaN
9,2023-01-10,1441.0,198.0,2.0,48.17,0.12,84.7792,6.0,North,Credit Card,...,Books,4.5,Returned,Negative,13.330000,WELCOME5,3.4,no_data,value_5,NaN
10,2023-01-11,1065.0,159.0,8.0,65.93,0.09,479.9704,9.0,South,Online,...,Electronics,3.7,Not Returned,Negative,11.785357,SAVE10,2.3,Used loyalty points,no_data,NaN
11,2023-01-12,1828.0,117.0,9.0,49.15,0.14,380.4210,7.0,North,Online,...,Food,1.1,Returned,Positive,15.890000,nan,1.1,Requested gift wrap,value_3,NaN
12,2023-01-13,1326.0,140.0,7.0,17.92,0.22,97.8432,4.0,East,Credit Card,...,Electronics,3.1,Returned,Neutral,10.890000,nan,2.3,no_data,value_5,NaN
13,2023-01-14,1889.0,183.0,6.0,62.40,0.00,374.4000,4.0,North,Credit Card,...,Electronics,3.4,Not Returned,Neutral,9.740000,nan,2.3,unknown,value_5,NaN
14,2023-01-15,1638.0,135.0,2.0,73.93,0.13,128.6382,5.0,South,Online,...,Food,4.8,Not Returned,Neutral,16.580000,nan,3.4,unknown,value_3,NaN
15,2023-01-16,1547.0,177.0,4.0,81.15,0.21,256.4340,3.0,East,Online,...,Electronics,1.5,Not Returned,Positive,14.040000,nan,2.3,Frequent buyer,unknown,NaN
16,2023-01-17,1633.0,198.0,2.0,24.79,0.28,35.6976,2.0,West,Credit Card,...,Food,2.6,Not Returned,Negative,9.670000,nan,2.3,no_data,value_3,NaN
17,2023-01-18,1892.0,112.0,8.0,11.01,0.11,78.3912,6.0,North,Credit Card,...,Food,4.2,Not Returned,Positive,14.150000,WELCOME5,2.3,Frequent buyer,no_data,NaN
18,2023-01-19,1666.0,104.0,3.0,91.35,0.02,268.5690,1.0,North,Online,...,Books,4.7,Returned,Neutral,8.360000,FREESHIP,2.3,unknown,value_1,NaN
19,2023-01-20,1224.0,134.0,7.0,20.67,0.06,136.0086,3.0,West,Credit Card,...,Books,1.2,Not Returned,Negative,12.130000,nan,2.0,First-time customer,value_1,NaN
20,2023-01-21,1704.0,102.0,9.0,29.49,0.27,193.7493,5.0,West,Online,...,Clothing,4.6,Returned,Positive,11.785357,WELCOME5,3.9,First-time customer,value_1,NaN
21,2023-01-22,1237.0,181.0,6.0,50.40,0.02,296.3520,2.0,North,Credit Card,...,Food,3.7,Not Returned,Positive,7.640000,nan,1.4,unknown,unknown,NaN
22,2023-01-23,1321.0,130.0,9.0,29.06,0.05,248.4630,8.0,West,Cash,...,Electronics,1.1,Not Returned,Neutral,5.130000,SAVE10,4.8,Used loyalty points,unknown,NaN
23,2023-01-24,1344.0,123.0,5.0,63.11,0.22,246.1290,5.0,West,Online,...,Clothing,2.0,Returned,Neutral,18.280000,nan,1.0,unknown,value_3,NaN
24,2023-01-25,1290.0,130.0,8.0,28.17,0.19,182.5416,2.0,North,Credit Card,...,Food,4.9,Not Returned,Negative,11.785357,SAVE10,1.8,First-time customer,value_3,NaN
25,2023-01-26,1023.0,105.0,5.0,14.54,0.07,67.6110,7.0,East,Online,...,Clothing,1.8,Returned,Negative,7.040000,SAVE10,4.1,Requested gift wrap,value_2,NaN
26,2023-01-27,1753.0,122.0,4.0,13.12,0.14,45.1328,5.0,North,Credit Card,...,Food,2.7,Returned,Neutral,11.785357,WELCOME5,4.7,Preferred morning delivery,unknown,NaN
27,2023-01-28,1520.0,108.0,8.0,56.57,0.23,348.4712,1.0,East,Credit Card,...,Food,4.6,Returned,Positive,11.785357,nan,5.0,Frequent buyer,value_5,NaN
28,2023-01-29,1825.0,161.0,4.0,40.75,0.29,115.7300,6.0,East,Cash,...,Books,1.2,Returned,Negative,11.785357,SAVE10,2.3,First-time customer,value_1,NaN
29,2023-01-30,1986.0,143.0,8.0,53.92,0.04,414.1056,4.0,North,Credit Card,...,Electronics,3.9,Not Returned,Positive,18.710000,FREESHIP,2.0,unknown,no_data,NaN
30,2023-01-31,1371.0,137.0,6.0,23.53,0.03,136.9446,4.0,South,Credit Card,...,Books,3.7,Not Returned,Negative,13.670000,nan,2.3,Requested gift wrap,no_data,NaN
31,2023-02-01,1641.0,184.0,6.0,96.36,0.13,502.9992,1.0,West,Credit Card,...,Electronics,2.3,Returned,Positive,6.150000,SAVE10,2.1,Frequent buyer,value_2,NaN
32,2023-02-02,1699.0,143.0,6.0,15.77,0.08,87.0504,3.0,South,Online,...,Electronics,1.2,Not Returned,Negative,10.200000,SAVE10,3.7,no_data,unknown,NaN
33,2023-02-03,1354.0,130.0,9.0,61.73,0.01,550.0143,4.0,South,Credit Card,...,Clothing,3.1,Returned,Positive,19.410000,FREESHIP,2.0,Frequent buyer,value_4,NaN
34,2023-02-04,1256.0,149.0,3.0,72.99,0.29,155.4687,5.0,East,Credit Card,...,Electronics,1.8,Not Returned,Negative,14.050000,WELCOME5,3.0,unknown,value_3,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,11.785357,NaN,2.3,NaN,NaN,NaN

<div class="alert alert-warning">

**15. Interpolate Missing Values Using Linear Method**

**Write a Pandas program to interpolate the missing values using the Linear Interpolation method in a given DataFrame.**

</div>

In [34]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_6482/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1621.0,161.0,4.0,31.60,0.27,92.2720,5.0,West,Credit Card,...,Books,4.0,Not Returned,Neutral,13.40,nan,1.6,Preferred morning delivery,value_3,NaN
1,2023-01-02,1106.0,114.0,8.0,88.85,0.08,653.9360,1.0,East,Credit Card,...,Electronics,4.2,Returned,Positive,NaN,nan,2.9,Requested gift wrap,no_data,NaN
2,2023-01-03,1272.0,107.0,4.0,82.04,0.04,315.0336,7.0,East,Cash,...,Books,3.1,Not Returned,Negative,10.01,nan,1.7,Used loyalty points,no_data,NaN
3,2023-01-04,1150.0,132.0,6.0,41.95,0.17,208.9110,4.0,North,Credit Card,...,Food,4.2,Not Returned,Neutral,NaN,WELCOME5,2.2,no_data,no_data,NaN
4,2023-01-05,1364.0,184.0,2.0,99.66,0.16,167.4288,7.0,West,Online,...,Clothing,4.8,Returned,Positive,11.50,nan,4.2,unknown,value_4,NaN
5,2023-01-06,1717.0,194.0,5.0,83.33,0.06,391.6510,8.0,North,Cash,...,Clothing,4.5,Returned,Neutral,7.12,SAVE10,3.4,Used loyalty points,no_data,NaN
6,2023-01-07,1864.0,192.0,7.0,55.06,0.13,335.3154,2.0,East,Cash,...,Clothing,1.8,Returned,Negative,6.64,FREESHIP,2.5,Requested gift wrap,value_5,NaN
7,2023-01-08,1559.0,185.0,5.0,79.66,0.27,290.7590,5.0,South,Credit Card,...,Clothing,2.7,Not Returned,Positive,NaN,nan,1.4,Used loyalty points,no_data,NaN
8,2023-01-09,1614.0,190.0,1.0,26.71,0.14,22.9706,1.0,North,Online,...,Food,4.5,Returned,Negative,NaN,nan,NaN,Used loyalty points,value_3,NaN
9,2023-01-10,1074.0,121.0,1.0,55.04,0.19,44.5824,7.0,North,Cash,...,Food,2.6,Returned,Negative,7.93,SAVE10,1.5,unknown,value_1,NaN
10,2023-01-11,1182.0,186.0,8.0,59.70,0.12,420.2880,5.0,North,Credit Card,...,Electronics,4.2,Not Returned,Negative,NaN,FREESHIP,NaN,no_data,unknown,NaN
11,2023-01-12,1439.0,114.0,7.0,58.29,0.15,346.8255,3.0,South,Credit Card,...,Clothing,4.1,Returned,Neutral,9.95,WELCOME5,4.3,unknown,unknown,NaN
12,2023-01-13,1534.0,186.0,2.0,15.08,0.12,26.5408,3.0,South,Cash,...,Clothing,4.9,Not Returned,Positive,6.90,FREESHIP,NaN,unknown,no_data,NaN
13,2023-01-14,1884.0,148.0,1.0,57.52,0.28,41.4144,8.0,South,Cash,...,Food,2.0,Not Returned,Positive,NaN,SAVE10,2.4,Frequent buyer,no_data,NaN
14,2023-01-15,1219.0,144.0,1.0,65.60,0.29,46.5760,9.0,West,Cash,...,Books,2.6,Not Returned,Neutral,14.32,SAVE10,2.7,no_data,no_data,NaN
15,2023-01-16,1479.0,118.0,3.0,35.35,0.06,99.6870,1.0,South,Credit Card,...,Clothing,4.3,Returned,Neutral,12.28,WELCOME5,3.5,Requested gift wrap,no_data,NaN
16,2023-01-17,1574.0,175.0,8.0,62.10,0.20,397.4400,2.0,West,Cash,...,Books,1.8,Not Returned,Neutral,NaN,SAVE10,3.3,no_data,unknown,NaN
17,2023-01-18,1150.0,129.0,6.0,87.90,0.18,432.4680,1.0,North,Credit Card,...,Electronics,4.2,Not Returned,Neutral,19.61,nan,1.5,Used loyalty points,value_2,NaN
18,2023-01-19,1059.0,143.0,7.0,74.07,0.20,414.7920,3.0,West,Online,...,Clothing,1.9,Returned,Positive,15.06,SAVE10,3.7,Requested gift wrap,no_data,NaN
19,2023-01-20,1833.0,140.0,7.0,26.22,0.03,178.0338,5.0,West,Cash,...,Food,3.6,Returned,Positive,NaN,nan,NaN,no_data,value_5,NaN
20,2023-01-21,1401.0,163.0,5.0,67.56,0.23,260.1060,2.0,West,Cash,...,Food,3.1,Not Returned,Negative,15.20,nan,NaN,unknown,no_data,NaN
21,2023-01-22,1598.0,168.0,1.0,97.96,0.27,71.5108,1.0,East,Credit Card,...,Electronics,4.7,Returned,Negative,NaN,nan,1.7,Preferred morning delivery,no_data,NaN
22,2023-01-23,1484.0,131.0,9.0,25.87,0.28,167.6376,6.0,North,Online,...,Electronics,4.2,Returned,Neutral,9.78,nan,2.3,Preferred morning delivery,value_2,NaN
23,2023-01-24,1029.0,103.0,3.0,94.63,0.16,238.4676,2.0,North,Online,...,Food,2.7,Not Returned,Positive,NaN,nan,3.7,no_data,value_2,NaN
24,2023-01-25,1011.0,165.0,1.0,47.62,0.29,33.8102,5.0,West,Credit Card,...,Books,4.7,Returned,Negative,17.70,WELCOME5,NaN,Preferred morning delivery,no_data,NaN
25,2023-01-26,1811.0,133.0,8.0,64.23,0.07,477.8712,9.0,West,Credit Card,...,Clothing,3.2,Not Returned,Neutral,13.32,SAVE10,3.9,no_data,value_1,NaN
26,2023-01-27,1367.0,181.0,3.0,15.05,0.23,34.7655,1.0,South,Credit Card,...,Books,4.9,Not Returned,Negative,NaN,SAVE10,NaN,Preferred morning delivery,value_2,NaN
27,2023-01-28,1149.0,170.0,6.0,89.60,0.09,489.2160,1.0,East,Credit Card,...,Books,1.6,Not Returned,Positive,5.09,WELCOME5,4.8,Requested gift wrap,no_data,NaN
28,2023-01-29,1017.0,159.0,4.0,37.95,0.12,133.5840,4.0,East,Online,...,Books,4.0,Returned,Negative,13.19,SAVE10,2.6,no_data,no_data,NaN
29,2023-01-30,1325.0,146.0,1.0,70.79,0.15,60.1715,8.0,West,Credit Card,...,Electronics,4.8,Returned,Negative,5.93,nan,4.9,no_data,unknown,NaN
30,2023-01-31,1184.0,108.0,3.0,29.19,0.18,71.8074,3.0,North,Credit Card,...,Electronics,2.3,Returned,Negative,NaN,FREESHIP,3.2,no_data,no_data,NaN
31,2023-02-01,1999.0,168.0,5.0,74.77,0.21,295.3415,4.0,North,Credit Card,...,Books,2.3,Not Returned,Neutral,NaN,WELCOME5,NaN,no_data,no_data,NaN
32,2023-02-02,1455.0,101.0,5.0,63.23,0.07,294.0195,2.0,East,Cash,...,Food,2.7,Not Returned,Neutral,16.37,nan,2.9,Used loyalty points,no_data,NaN
33,2023-02-03,1005.0,133.0,6.0,15.83,0.27,69.3354,2.0,North,Online,...,Books,1.1,Not Returned,Positive,12.75,nan,2.3,unknown,value_1,NaN
34,2023-02-04,1282.0,159.0,3.0,13.99,0.03,40.7109,1.0,South,Cash,...,Food,3.9,Returned,Negative,NaN,WELCOME5,4.8,Requested gift wrap,no_data,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 15:**
</div>

In [35]:
df['shipping_cost_interpolated'] = df['shipping_cost'].interpolate(method='linear', direction='forward')
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column,shipping_cost_interpolated
0,2023-01-01,1621.0,161.0,4.0,31.60,0.27,92.2720,5.0,West,Credit Card,...,4.0,Not Returned,Neutral,13.40,nan,1.6,Preferred morning delivery,value_3,NaN,13.400
1,2023-01-02,1106.0,114.0,8.0,88.85,0.08,653.9360,1.0,East,Credit Card,...,4.2,Returned,Positive,NaN,nan,2.9,Requested gift wrap,no_data,NaN,11.705
2,2023-01-03,1272.0,107.0,4.0,82.04,0.04,315.0336,7.0,East,Cash,...,3.1,Not Returned,Negative,10.01,nan,1.7,Used loyalty points,no_data,NaN,10.010
3,2023-01-04,1150.0,132.0,6.0,41.95,0.17,208.9110,4.0,North,Credit Card,...,4.2,Not Returned,Neutral,NaN,WELCOME5,2.2,no_data,no_data,NaN,10.755
4,2023-01-05,1364.0,184.0,2.0,99.66,0.16,167.4288,7.0,West,Online,...,4.8,Returned,Positive,11.50,nan,4.2,unknown,value_4,NaN,11.500
5,2023-01-06,1717.0,194.0,5.0,83.33,0.06,391.6510,8.0,North,Cash,...,4.5,Returned,Neutral,7.12,SAVE10,3.4,Used loyalty points,no_data,NaN,7.120
6,2023-01-07,1864.0,192.0,7.0,55.06,0.13,335.3154,2.0,East,Cash,...,1.8,Returned,Negative,6.64,FREESHIP,2.5,Requested gift wrap,value_5,NaN,6.640
7,2023-01-08,1559.0,185.0,5.0,79.66,0.27,290.7590,5.0,South,Credit Card,...,2.7,Not Returned,Positive,NaN,nan,1.4,Used loyalty points,no_data,NaN,7.070
8,2023-01-09,1614.0,190.0,1.0,26.71,0.14,22.9706,1.0,North,Online,...,4.5,Returned,Negative,NaN,nan,NaN,Used loyalty points,value_3,NaN,7.500
9,2023-01-10,1074.0,121.0,1.0,55.04,0.19,44.5824,7.0,North,Cash,...,2.6,Returned,Negative,7.93,SAVE10,1.5,unknown,value_1,NaN,7.930
10,2023-01-11,1182.0,186.0,8.0,59.70,0.12,420.2880,5.0,North,Credit Card,...,4.2,Not Returned,Negative,NaN,FREESHIP,NaN,no_data,unknown,NaN,8.940
11,2023-01-12,1439.0,114.0,7.0,58.29,0.15,346.8255,3.0,South,Credit Card,...,4.1,Returned,Neutral,9.95,WELCOME5,4.3,unknown,unknown,NaN,9.950
12,2023-01-13,1534.0,186.0,2.0,15.08,0.12,26.5408,3.0,South,Cash,...,4.9,Not Returned,Positive,6.90,FREESHIP,NaN,unknown,no_data,NaN,6.900
13,2023-01-14,1884.0,148.0,1.0,57.52,0.28,41.4144,8.0,South,Cash,...,2.0,Not Returned,Positive,NaN,SAVE10,2.4,Frequent buyer,no_data,NaN,10.610
14,2023-01-15,1219.0,144.0,1.0,65.60,0.29,46.5760,9.0,West,Cash,...,2.6,Not Returned,Neutral,14.32,SAVE10,2.7,no_data,no_data,NaN,14.320
15,2023-01-16,1479.0,118.0,3.0,35.35,0.06,99.6870,1.0,South,Credit Card,...,4.3,Returned,Neutral,12.28,WELCOME5,3.5,Requested gift wrap,no_data,NaN,12.280
16,2023-01-17,1574.0,175.0,8.0,62.10,0.20,397.4400,2.0,West,Cash,...,1.8,Not Returned,Neutral,NaN,SAVE10,3.3,no_data,unknown,NaN,15.945
17,2023-01-18,1150.0,129.0,6.0,87.90,0.18,432.4680,1.0,North,Credit Card,...,4.2,Not Returned,Neutral,19.61,nan,1.5,Used loyalty points,value_2,NaN,19.610
18,2023-01-19,1059.0,143.0,7.0,74.07,0.20,414.7920,3.0,West,Online,...,1.9,Returned,Positive,15.06,SAVE10,3.7,Requested gift wrap,no_data,NaN,15.060
19,2023-01-20,1833.0,140.0,7.0,26.22,0.03,178.0338,5.0,West,Cash,...,3.6,Returned,Positive,NaN,nan,NaN,no_data,value_5,NaN,15.130
20,2023-01-21,1401.0,163.0,5.0,67.56,0.23,260.1060,2.0,West,Cash,...,3.1,Not Returned,Negative,15.20,nan,NaN,unknown,no_data,NaN,15.200
21,2023-01-22,1598.0,168.0,1.0,97.96,0.27,71.5108,1.0,East,Credit Card,...,4.7,Returned,Negative,NaN,nan,1.7,Preferred morning delivery,no_data,NaN,12.490
22,2023-01-23,1484.0,131.0,9.0,25.87,0.28,167.6376,6.0,North,Online,...,4.2,Returned,Neutral,9.78,nan,2.3,Preferred morning delivery,value_2,NaN,9.780
23,2023-01-24,1029.0,103.0,3.0,94.63,0.16,238.4676,2.0,North,Online,...,2.7,Not Returned,Positive,NaN,nan,3.7,no_data,value_2,NaN,13.740
24,2023-01-25,1011.0,165.0,1.0,47.62,0.29,33.8102,5.0,West,Credit Card,...,4.7,Returned,Negative,17.70,WELCOME5,NaN,Preferred morning delivery,no_data,NaN,17.700
25,2023-01-26,1811.0,133.0,8.0,64.23,0.07,477.8712,9.0,West,Credit Card,...,3.2,Not Returned,Neutral,13.32,SAVE10,3.9,no_data,value_1,NaN,13.320
26,2023-01-27,1367.0,181.0,3.0,15.05,0.23,34.7655,1.0,South,Credit Card,...,4.9,Not Returned,Negative,NaN,SAVE10,NaN,Preferred morning delivery,value_2,NaN,9.205
27,2023-01-28,1149.0,170.0,6.0,89.60,0.09,489.2160,1.0,East,Credit Card,...,1.6,Not Returned,Positive,5.09,WELCOME5,4.8,Requested gift wrap,no_data,NaN,5.090
28,2023-01-29,1017.0,159.0,4.0,37.95,0.12,133.5840,4.0,East,Online,...,4.0,Returned,Negative,13.19,SAVE10,2.6,no_data,no_data,NaN,13.190
29,2023-01-30,1325.0,146.0,1.0,70.79,0.15,60.1715,8.0,West,Credit Card,...,4.8,Returned,Negative,5.93,nan,4.9,no_data,unknown,NaN,5.930
30,2023-01-31,1184.0,108.0,3.0,29.19,0.18,71.8074,3.0,North,Credit Card,...,2.3,Returned,Negative,NaN,FREESHIP,3.2,no_data,no_data,NaN,9.410
31,2023-02-01,1999.0,168.0,5.0,74.77,0.21,295.3415,4.0,North,Credit Card,...,2.3,Not Returned,Neutral,NaN,WELCOME5,NaN,no_data,no_data,NaN,12.890
32,2023-02-02,1455.0,101.0,5.0,63.23,0.07,294.0195,2.0,East,Cash,...,2.7,Not Returned,Neutral,16.37,nan,2.9,Used loyalty points,no_data,NaN,16.370
33,2023-02-03,1005.0,133.0,6.0,15.83,0.27,69.3354,2.0,North,Online,...,1.1,Not Returned,Positive,12.75,nan,2.3,unknown,value_1,NaN,12.750
34,2023-02-04,1282.0,159.0,3.0,13.99,0.03,40.7109,1.0,South,Cash,...,3.9,Returned,Negative,NaN,WELCOME5,4.8,Requested gift wrap,no_data,NaN,12.750
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.750

<div class="alert alert-warning">

**16. Count Missing Values in a Specified Column**

**Write a Pandas program to count the number of missing values of a specified column in a given DataFrame.**

</div>

In [36]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_6482/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1548.0,144.0,1.0,46.16,0.15,39.2360,3.0,South,Credit Card,...,Food,2.7,Not Returned,Negative,16.15,SAVE10,3.5,First-time customer,value_5,NaN
1,2023-01-02,1000.0,135.0,2.0,39.93,0.18,65.4852,4.0,South,Online,...,Clothing,4.1,Returned,Negative,NaN,FREESHIP,NaN,Preferred morning delivery,value_2,NaN
2,2023-01-03,1103.0,174.0,1.0,75.17,0.22,58.6326,3.0,West,Credit Card,...,Electronics,3.9,Not Returned,Neutral,5.18,SAVE10,2.0,Requested gift wrap,value_4,NaN
3,2023-01-04,1440.0,115.0,2.0,51.31,0.10,92.3580,6.0,West,Cash,...,Electronics,1.4,Not Returned,Negative,11.07,nan,3.7,Requested gift wrap,value_2,NaN
4,2023-01-05,1766.0,115.0,5.0,42.16,0.23,162.3160,5.0,West,Cash,...,Books,3.6,Not Returned,Negative,19.94,nan,1.8,no_data,no_data,NaN
5,2023-01-06,1202.0,148.0,1.0,96.00,0.23,73.9200,7.0,East,Cash,...,Electronics,4.7,Not Returned,Neutral,5.19,WELCOME5,3.6,unknown,value_5,NaN
6,2023-01-07,1980.0,102.0,5.0,68.06,0.10,306.2700,7.0,West,Credit Card,...,Food,4.8,Returned,Negative,14.23,FREESHIP,2.9,Frequent buyer,unknown,NaN
7,2023-01-08,1771.0,143.0,9.0,97.34,0.16,735.8904,2.0,South,Online,...,Clothing,4.1,Not Returned,Negative,7.19,nan,NaN,unknown,value_4,NaN
8,2023-01-09,1423.0,154.0,8.0,12.04,0.29,68.3872,9.0,West,Online,...,Clothing,4.1,Not Returned,Negative,19.08,SAVE10,1.8,unknown,value_5,NaN
9,2023-01-10,1153.0,161.0,7.0,13.07,0.02,89.6602,5.0,South,Cash,...,Electronics,2.0,Returned,Neutral,9.60,WELCOME5,NaN,no_data,no_data,NaN
10,2023-01-11,1636.0,153.0,4.0,29.24,0.09,106.4336,7.0,North,Online,...,Clothing,1.2,Not Returned,Negative,6.70,SAVE10,2.7,no_data,value_4,NaN
11,2023-01-12,1218.0,182.0,8.0,41.03,0.02,321.6752,9.0,South,Cash,...,Food,2.7,Not Returned,Neutral,18.32,SAVE10,NaN,unknown,value_3,NaN
12,2023-01-13,1028.0,170.0,3.0,93.95,0.09,256.4835,3.0,West,Credit Card,...,Clothing,1.9,Not Returned,Neutral,15.14,WELCOME5,NaN,unknown,no_data,NaN
13,2023-01-14,1898.0,135.0,2.0,31.74,0.07,59.0364,5.0,West,Online,...,Books,1.7,Returned,Neutral,16.41,FREESHIP,NaN,unknown,value_4,NaN
14,2023-01-15,1916.0,102.0,6.0,23.17,0.03,134.8494,6.0,South,Credit Card,...,Clothing,1.4,Not Returned,Positive,16.91,WELCOME5,4.3,no_data,value_3,NaN
15,2023-01-16,1376.0,156.0,8.0,59.40,0.20,380.1600,5.0,South,Cash,...,Electronics,1.5,Returned,Positive,11.04,SAVE10,NaN,unknown,value_3,NaN
16,2023-01-17,1677.0,184.0,7.0,23.55,0.27,120.3405,1.0,South,Credit Card,...,Electronics,2.6,Returned,Neutral,13.95,FREESHIP,NaN,Used loyalty points,no_data,NaN
17,2023-01-18,1855.0,110.0,8.0,38.14,0.29,216.6352,2.0,North,Cash,...,Electronics,4.2,Not Returned,Negative,13.95,nan,2.2,no_data,no_data,NaN
18,2023-01-19,1635.0,104.0,2.0,51.34,0.09,93.4388,6.0,West,Online,...,Electronics,1.6,Returned,Neutral,11.60,nan,2.3,Used loyalty points,no_data,NaN
19,2023-01-20,1069.0,144.0,6.0,32.95,0.23,152.2290,6.0,West,Credit Card,...,Electronics,1.4,Not Returned,Neutral,NaN,nan,4.1,Preferred morning delivery,value_4,NaN
20,2023-01-21,1869.0,138.0,4.0,93.06,0.21,294.0696,3.0,South,Credit Card,...,Electronics,2.0,Returned,Negative,6.41,WELCOME5,3.1,no_data,unknown,NaN
21,2023-01-22,1823.0,199.0,2.0,81.40,0.01,161.1720,1.0,East,Cash,...,Books,2.2,Not Returned,Negative,NaN,nan,NaN,no_data,value_4,NaN
22,2023-01-23,1137.0,165.0,8.0,63.17,0.04,485.1456,5.0,South,Online,...,Electronics,1.8,Returned,Positive,11.66,FREESHIP,NaN,Preferred morning delivery,unknown,NaN
23,2023-01-24,1963.0,148.0,1.0,26.98,0.00,26.9800,8.0,South,Cash,...,Books,1.0,Not Returned,Neutral,NaN,WELCOME5,3.4,First-time customer,value_2,NaN
24,2023-01-25,1552.0,109.0,2.0,91.43,0.17,151.7738,9.0,South,Credit Card,...,Books,3.1,Not Returned,Negative,11.58,WELCOME5,1.0,First-time customer,unknown,NaN
25,2023-01-26,1609.0,197.0,2.0,32.45,0.27,47.3770,2.0,South,Cash,...,Electronics,4.1,Returned,Positive,NaN,nan,2.2,Frequent buyer,no_data,NaN
26,2023-01-27,1124.0,179.0,5.0,79.34,0.12,349.0960,8.0,West,Credit Card,...,Electronics,3.0,Not Returned,Negative,15.97,nan,3.9,Frequent buyer,value_4,NaN
27,2023-01-28,1143.0,153.0,8.0,98.88,0.09,719.8464,6.0,West,Credit Card,...,Electronics,4.2,Not Returned,Positive,8.48,FREESHIP,NaN,no_data,value_1,NaN
28,2023-01-29,1446.0,184.0,5.0,15.66,0.12,68.9040,2.0,East,Cash,...,Food,3.7,Not Returned,Positive,12.58,FREESHIP,4.7,Used loyalty points,value_5,NaN
29,2023-01-30,1900.0,123.0,6.0,79.89,0.25,359.5050,1.0,South,Online,...,Electronics,1.6,Returned,Neutral,8.50,SAVE10,NaN,First-time customer,value_3,NaN
30,2023-01-31,1325.0,129.0,5.0,16.79,0.20,67.1600,9.0,West,Cash,...,Food,1.7,Returned,Neutral,13.08,nan,NaN,unknown,no_data,NaN
31,2023-02-01,1779.0,153.0,3.0,26.25,0.19,63.7875,1.0,East,Online,...,Electronics,1.3,Returned,Negative,10.67,WELCOME5,3.1,no_data,value_4,NaN
32,2023-02-02,1967.0,157.0,1.0,49.94,0.01,49.4406,7.0,North,Cash,...,Books,3.4,Not Returned,Neutral,NaN,SAVE10,NaN,Preferred morning delivery,no_data,NaN
33,2023-02-03,1770.0,132.0,8.0,68.05,0.26,402.8560,4.0,North,Cash,...,Food,2.3,Returned,Positive,17.95,FREESHIP,1.9,unknown,unknown,NaN
34,2023-02-04,1031.0,163.0,3.0,33.23,0.00,99.6900,4.0,East,Credit Card,...,Books,2.1,Returned,Positive,19.53,WELCOME5,4.4,Frequent buyer,no_data,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 16:**
</div>

In [37]:
# ordered by number of missing values list of columns with missing values
import pandas as pd
import numpy as np
missing_columns = df.columns[df.isnull().any()].tolist()
missing_columns.sort(key=lambda col: df[col].isnull().sum(), reverse=True)

for col in missing_columns:
    print(f"Column {col:<20} has {df[col].isnull().sum()} missing values.")

Column all_nan_column       has 36 missing values.
Column delivery_rating      has 15 missing values.
Column shipping_cost        has 7 missing values.
Column date                 has 1 missing values.
Column customer_id          has 1 missing values.
Column product_id           has 1 missing values.
Column quantity             has 1 missing values.
Column price                has 1 missing values.
Column discount             has 1 missing values.
Column revenue              has 1 missing values.
Column store_id             has 1 missing values.
Column region               has 1 missing values.
Column payment_method       has 1 missing values.
Column is_member            has 1 missing values.
Column delivery_days        has 1 missing values.
Column customer_age         has 1 missing values.
Column gender               has 1 missing values.
Column product_category     has 1 missing values.
Column rating               has 1 missing values.
Column return_status        has 1 missing values.
Column feedback             has 1 missing values.
Column coupon_code          has 1 missing values.
Column customer_note        has 1 missing values.
Column customer_values      has 1 missing values.