[Pandas Missing Values](https://www.w3resource.com/python-exercises/pandas/missing-values/index.php)

In [1]:
import pandas as pd
import numpy as np

<div class="alert alert-warning">

**1. Detect Missing Values**

**Write a Pandas program to detect missing values of a given DataFrame. Display True or False.**

</div>

In [2]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1565,188,1,98.14,0.15,83.4190,2,West,Credit Card,...,1,45,Other,Books,2.9,Not Returned,Positive,15.74,SAVE10,2.1
1,2023-01-02,1738,138,4,23.17,0.21,73.2172,1,East,Cash,...,5,32,Other,Electronics,1.8,Returned,Neutral,17.60,WELCOME5,1.6
2,2023-01-03,1212,127,6,48.76,0.22,228.1968,7,West,Cash,...,4,57,Male,Books,3.2,Not Returned,Positive,5.87,SAVE10,3.4
3,2023-01-04,1852,126,7,41.72,0.11,259.9156,5,West,Credit Card,...,6,60,Male,Food,1.3,Not Returned,Neutral,13.57,WELCOME5,2.1
4,2023-01-05,1552,145,9,53.55,0.24,366.2820,1,East,Credit Card,...,4,18,Female,Electronics,2.9,Returned,Negative,NaN,nan,3.3
5,2023-01-06,1037,174,3,32.38,0.10,87.4260,1,West,Online,...,6,58,Female,Electronics,3.5,Returned,Negative,NaN,nan,5.0
6,2023-01-07,1825,115,4,71.20,0.01,281.9520,9,East,Online,...,5,24,Female,Books,3.7,Returned,Positive,NaN,FREESHIP,2.5
7,2023-01-08,1785,153,5,44.70,0.01,221.2650,8,North,Online,...,4,55,Female,Books,2.5,Not Returned,Positive,10.21,nan,NaN
8,2023-01-09,1619,186,5,90.46,0.26,334.7020,6,West,Credit Card,...,6,26,Female,Clothing,1.8,Returned,Positive,16.61,nan,1.7
9,2023-01-10,1558,138,4,27.69,0.04,106.3296,5,West,Credit Card,...,4,56,Female,Clothing,2.8,Not Returned,Negative,18.45,nan,2.9
10,2023-01-11,1436,133,2,75.34,0.26,111.5032,4,West,Online,...,1,61,Male,Electronics,2.0,Returned,Positive,NaN,FREESHIP,4.8
11,2023-01-12,1901,158,2,43.49,0.16,73.0632,1,East,Cash,...,4,31,Female,Books,4.3,Returned,Negative,17.86,WELCOME5,2.3
12,2023-01-13,1058,115,2,23.77,0.08,43.7368,3,East,Cash,...,5,33,Other,Electronics,3.5,Returned,Positive,13.36,nan,2.1
13,2023-01-14,1264,119,6,82.51,0.24,376.2456,3,North,Credit Card,...,5,23,Male,Clothing,4.0,Not Returned,Neutral,7.53,FREESHIP,NaN
14,2023-01-15,1878,195,7,32.98,0.22,180.0708,4,South,Online,...,5,57,Male,Food,2.5,Not Returned,Neutral,10.06,WELCOME5,NaN
15,2023-01-16,1840,104,3,79.06,0.18,194.4876,3,East,Online,...,6,61,Female,Electronics,1.6,Returned,Positive,NaN,nan,3.5
16,2023-01-17,1891,182,3,61.15,0.28,132.0840,9,West,Cash,...,1,22,Female,Books,3.5,Returned,Positive,10.24,WELCOME5,1.8
17,2023-01-18,1319,116,5,14.27,0.22,55.6530,1,North,Online,...,3,39,Male,Clothing,1.7,Not Returned,Positive,5.17,FREESHIP,NaN
18,2023-01-19,1324,157,9,98.34,0.28,637.2432,8,South,Online,...,3,45,Other,Clothing,4.0,Not Returned,Neutral,9.95,FREESHIP,4.8
19,2023-01-20,1380,125,5,45.16,0.18,185.1560,1,West,Cash,...,6,29,Female,Clothing,1.7,Not Returned,Positive,15.43,WELCOME5,3.2
20,2023-01-21,1603,198,6,90.39,0.18,444.7188,8,West,Online,...,3,19,Female,Electronics,3.0,Not Returned,Neutral,14.25,SAVE10,NaN
21,2023-01-22,1022,180,6,46.66,0.07,260.3628,9,South,Online,...,4,42,Male,Books,4.1,Returned,Positive,NaN,WELCOME5,NaN
22,2023-01-23,1750,162,7,86.57,0.25,454.4925,2,West,Online,...,1,47,Other,Food,2.4,Not Returned,Negative,11.98,FREESHIP,3.7
23,2023-01-24,1745,143,8,82.27,0.12,579.1808,8,South,Online,...,4,31,Male,Books,2.1,Returned,Neutral,15.55,SAVE10,4.7
24,2023-01-25,1443,107,4,61.57,0.16,206.8752,7,North,Online,...,6,62,Male,Food,2.6,Not Returned,Negative,8.44,nan,3.9
25,2023-01-26,1190,138,2,84.05,0.16,141.2040,4,East,Cash,...,1,47,Male,Books,2.2,Returned,Neutral,11.07,nan,4.8
26,2023-01-27,1042,127,6,37.92,0.16,191.1168,4,South,Cash,...,4,29,Other,Clothing,1.7,Returned,Negative,6.97,FREESHIP,1.9
27,2023-01-28,1906,149,4,20.23,0.21,63.9268,2,North,Cash,...,2,63,Female,Books,2.0,Not Returned,Negative,16.31,FREESHIP,1.3
28,2023-01-29,1588,124,2,35.82,0.07,66.6252,8,West,Credit Card,...,5,54,Female,Books,5.0,Not Returned,Negative,14.97,FREESHIP,NaN
29,2023-01-30,1940,114,1,40.49,0.17,33.6067,6,East,Credit Card,...,4,27,Other,Books,3.3,Not Returned,Neutral,15.81,nan,NaN
30,2023-01-31,1496,118,2,73.72,0.24,112.0544,1,West,Online,...,3,38,Male,Food,4.2,Returned,Neutral,NaN,FREESHIP,4.3
31,2023-02-01,1013,156,3,87.09,0.01,258.6573,7,East,Online,...,6,41,Other,Clothing,2.8,Returned,Positive,NaN,FREESHIP,2.6
32,2023-02-02,1403,171,6,34.43,0.26,152.8692,8,North,Cash,...,5,56,Other,Electronics,2.7,Returned,Neutral,NaN,FREESHIP,4.0
33,2023-02-03,1839,115,3,98.16,0.20,235.5840,4,East,Online,...,1,49,Male,Food,1.5,Returned,Negative,16.54,FREESHIP,3.7
34,2023-02-04,1138,106,8,24.81,0.09,180.6168,7,North,Credit Card,...,3,39,Male,Books,4.8,Returned,Negative,NaN,nan,1.3

<div class="alert alert-success">

**Solution 01:**
</div>

In [3]:
print(type(df.isna()))
df.isna()

<class 'pandas.core.frame.DataFrame'>

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
15,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
29,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
30,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
31,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
32,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
33,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [4]:
print(df.isna().any())  
df.isna().sum()

date                False
customer_id         False
product_id          False
quantity            False
price               False
discount            False
revenue             False
store_id            False
region              False
payment_method      False
is_member           False
delivery_days       False
customer_age        False
gender              False
product_category    False
rating              False
return_status       False
feedback            False
shipping_cost        True
coupon_code         False
delivery_rating      True
dtype: bool

date                 0
customer_id          0
product_id           0
quantity             0
price                0
discount             0
revenue              0
store_id             0
region               0
payment_method       0
is_member            0
delivery_days        0
customer_age         0
gender               0
product_category     0
rating               0
return_status        0
feedback             0
shipping_cost       10
coupon_code          0
delivery_rating      8
dtype: int64

<div class="alert alert-warning">

**2. Identify Columns with Missing Values**

**Write a Pandas program to identify the column(s) of a given DataFrame which have at least one missing value.**

</div>

In [5]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1395,152,2,87.75,0.28,126.3600,9,East,Credit Card,...,1,69,Other,Clothing,1.1,Not Returned,Neutral,NaN,WELCOME5,2.4
1,2023-01-02,1009,121,3,62.05,0.19,150.7815,5,West,Cash,...,4,59,Male,Electronics,4.4,Returned,Neutral,7.01,FREESHIP,NaN
2,2023-01-03,1415,182,3,55.18,0.06,155.6076,6,West,Credit Card,...,6,54,Female,Clothing,1.7,Not Returned,Neutral,18.53,FREESHIP,NaN
3,2023-01-04,1999,198,9,77.35,0.19,563.8815,3,North,Credit Card,...,3,63,Female,Food,4.6,Not Returned,Positive,16.08,nan,NaN
4,2023-01-05,1839,124,9,51.63,0.25,348.5025,2,West,Online,...,3,66,Male,Electronics,4.6,Returned,Neutral,6.03,WELCOME5,NaN
5,2023-01-06,1162,109,3,96.70,0.05,275.5950,3,East,Credit Card,...,6,53,Other,Food,2.6,Returned,Positive,14.41,SAVE10,NaN
6,2023-01-07,1853,173,4,35.82,0.19,116.0568,5,East,Credit Card,...,6,44,Male,Books,1.3,Not Returned,Positive,5.10,nan,2.4
7,2023-01-08,1185,137,1,32.04,0.02,31.3992,5,South,Online,...,3,34,Female,Clothing,1.0,Returned,Negative,11.23,nan,1.7
8,2023-01-09,1103,132,9,19.64,0.03,171.4572,9,East,Cash,...,5,27,Other,Food,3.3,Not Returned,Positive,16.12,WELCOME5,4.4
9,2023-01-10,1788,166,1,15.39,0.10,13.8510,1,West,Cash,...,1,24,Female,Clothing,3.0,Returned,Negative,9.94,WELCOME5,NaN
10,2023-01-11,1024,164,6,80.67,0.02,474.3396,5,North,Online,...,2,46,Male,Books,4.9,Returned,Negative,6.48,nan,4.2
11,2023-01-12,1588,190,2,45.61,0.13,79.3614,6,North,Cash,...,3,45,Female,Clothing,3.5,Returned,Negative,16.28,nan,1.5
12,2023-01-13,1747,107,4,75.31,0.22,234.9672,6,West,Online,...,4,43,Other,Food,4.6,Returned,Neutral,7.27,FREESHIP,1.2
13,2023-01-14,1826,136,1,69.76,0.02,68.3648,3,North,Cash,...,5,48,Male,Electronics,2.6,Returned,Positive,15.50,nan,2.6
14,2023-01-15,1624,115,8,34.00,0.14,233.9200,3,West,Cash,...,5,57,Female,Electronics,3.5,Not Returned,Neutral,7.28,nan,3.2
15,2023-01-16,1982,173,8,79.14,0.18,519.1584,5,North,Cash,...,6,60,Male,Books,1.2,Not Returned,Positive,5.09,SAVE10,NaN
16,2023-01-17,1621,146,4,32.56,0.16,109.4016,9,South,Credit Card,...,1,19,Female,Electronics,3.1,Returned,Negative,16.09,SAVE10,NaN
17,2023-01-18,1539,139,5,41.40,0.10,186.3000,1,South,Online,...,1,25,Male,Electronics,4.7,Returned,Positive,12.51,FREESHIP,4.1
18,2023-01-19,1640,194,2,82.12,0.04,157.6704,6,North,Online,...,6,45,Female,Food,1.3,Returned,Neutral,10.57,nan,1.2
19,2023-01-20,1326,129,6,13.68,0.19,66.4848,9,South,Cash,...,5,39,Male,Food,3.2,Not Returned,Negative,19.20,nan,NaN
20,2023-01-21,1850,197,9,87.43,0.16,660.9708,2,South,Credit Card,...,2,56,Female,Electronics,3.9,Returned,Neutral,6.87,FREESHIP,NaN
21,2023-01-22,1020,141,3,53.08,0.02,156.0552,7,East,Credit Card,...,5,20,Female,Clothing,4.6,Returned,Neutral,11.24,SAVE10,3.5
22,2023-01-23,1501,125,5,58.46,0.18,239.6860,6,East,Credit Card,...,2,35,Male,Books,1.6,Returned,Positive,15.45,nan,3.1
23,2023-01-24,1779,128,7,12.14,0.08,78.1816,6,West,Online,...,4,30,Other,Electronics,2.7,Not Returned,Negative,NaN,nan,NaN
24,2023-01-25,1691,165,3,30.86,0.02,90.7284,8,West,Credit Card,...,4,24,Other,Electronics,3.9,Returned,Negative,5.53,FREESHIP,4.6
25,2023-01-26,1712,159,9,68.25,0.09,558.9675,6,East,Credit Card,...,4,45,Female,Books,1.6,Not Returned,Neutral,5.37,nan,NaN
26,2023-01-27,1197,193,4,16.07,0.09,58.4948,4,South,Cash,...,6,51,Male,Electronics,4.4,Returned,Negative,19.92,FREESHIP,2.3
27,2023-01-28,1744,146,3,66.66,0.29,141.9858,9,South,Credit Card,...,1,44,Other,Books,1.7,Not Returned,Neutral,NaN,SAVE10,1.2
28,2023-01-29,1453,190,2,13.80,0.16,23.1840,3,South,Online,...,1,68,Male,Clothing,1.1,Returned,Negative,16.74,FREESHIP,NaN
29,2023-01-30,1444,111,7,60.93,0.28,307.0872,6,East,Credit Card,...,6,54,Other,Electronics,1.4,Not Returned,Neutral,18.18,nan,3.6
30,2023-01-31,1331,191,2,41.59,0.11,74.0302,1,East,Credit Card,...,3,40,Male,Clothing,1.5,Not Returned,Positive,NaN,FREESHIP,NaN
31,2023-02-01,1321,157,1,59.78,0.02,58.5844,3,North,Credit Card,...,3,31,Male,Food,1.8,Returned,Positive,6.20,FREESHIP,4.1
32,2023-02-02,1908,162,8,52.76,0.25,316.5600,8,North,Cash,...,5,30,Male,Clothing,2.6,Returned,Positive,16.56,nan,1.1
33,2023-02-03,1292,153,4,40.25,0.18,132.0200,5,North,Credit Card,...,4,38,Male,Food,3.1,Returned,Neutral,9.82,nan,1.4
34,2023-02-04,1384,129,9,97.01,0.13,759.5883,3,West,Online,...,6,60,Other,Clothing,1.8,Returned,Positive,19.43,FREESHIP,2.6

<div class="alert alert-success">

**Solution 02:**
</div>

In [6]:
df.isna().any()
cols_have_na = df.isna().any()[lambda x: x].index.tolist()

<div class="alert alert-warning">

**3. Count Missing Values in Each Column**

**Write a Pandas program to count the number of missing values in each column of a given DataFrame.**

</div>

In [7]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1562,134,8,44.25,0.19,286.7400,6,South,Cash,...,1,33,Other,Electronics,1.8,Returned,Negative,14.36,WELCOME5,1.9
1,2023-01-02,1782,126,7,81.43,0.04,547.2096,5,East,Credit Card,...,3,52,Female,Clothing,1.1,Returned,Negative,8.54,nan,NaN
2,2023-01-03,1883,159,5,94.98,0.20,379.9200,5,West,Cash,...,6,24,Other,Electronics,1.4,Returned,Negative,16.18,FREESHIP,3.8
3,2023-01-04,1375,104,7,75.18,0.02,515.7348,2,South,Online,...,5,33,Other,Clothing,1.9,Not Returned,Positive,NaN,WELCOME5,NaN
4,2023-01-05,1184,133,5,73.45,0.29,260.7475,3,East,Cash,...,2,36,Other,Food,2.8,Not Returned,Positive,10.33,nan,4.8
5,2023-01-06,1430,161,3,22.86,0.20,54.8640,3,West,Online,...,4,32,Other,Electronics,1.7,Not Returned,Negative,16.92,nan,2.1
6,2023-01-07,1320,130,5,75.51,0.08,347.3460,4,North,Credit Card,...,5,40,Other,Clothing,1.6,Returned,Negative,11.08,nan,2.5
7,2023-01-08,1089,111,4,88.03,0.06,330.9928,6,West,Credit Card,...,2,50,Male,Clothing,1.1,Returned,Positive,8.19,nan,2.9
8,2023-01-09,1346,103,1,68.57,0.03,66.5129,3,South,Online,...,2,28,Other,Books,1.4,Returned,Neutral,6.22,WELCOME5,1.9
9,2023-01-10,1933,187,9,27.32,0.19,199.1628,3,North,Credit Card,...,3,51,Other,Clothing,1.5,Not Returned,Negative,13.85,nan,2.6
10,2023-01-11,1756,107,8,53.34,0.24,324.3072,3,West,Credit Card,...,4,37,Male,Electronics,1.7,Not Returned,Positive,17.19,nan,1.3
11,2023-01-12,1798,121,4,48.53,0.00,194.1200,7,South,Online,...,5,49,Female,Books,1.4,Not Returned,Negative,11.61,SAVE10,NaN
12,2023-01-13,1080,192,4,65.25,0.09,237.5100,4,North,Online,...,4,35,Male,Clothing,4.2,Not Returned,Negative,10.66,FREESHIP,1.2
13,2023-01-14,1610,123,3,35.16,0.07,98.0964,1,West,Online,...,2,65,Other,Books,3.8,Not Returned,Negative,13.86,FREESHIP,NaN
14,2023-01-15,1735,192,7,67.60,0.10,425.8800,7,West,Cash,...,2,65,Other,Food,2.6,Returned,Neutral,5.66,SAVE10,2.0
15,2023-01-16,1302,194,2,65.00,0.03,126.1000,5,East,Cash,...,4,21,Other,Clothing,1.4,Returned,Neutral,14.97,SAVE10,4.5
16,2023-01-17,1012,135,5,39.45,0.15,167.6625,5,North,Online,...,3,49,Female,Clothing,1.1,Not Returned,Positive,10.48,SAVE10,NaN
17,2023-01-18,1815,130,8,86.61,0.16,582.0192,4,North,Credit Card,...,3,52,Female,Clothing,1.0,Returned,Negative,15.89,nan,1.2
18,2023-01-19,1944,151,5,40.53,0.02,198.5970,2,East,Credit Card,...,5,31,Female,Books,1.9,Returned,Positive,12.05,SAVE10,NaN
19,2023-01-20,1611,128,9,56.49,0.21,401.6439,6,East,Credit Card,...,4,66,Female,Clothing,1.3,Not Returned,Positive,14.60,WELCOME5,4.1
20,2023-01-21,1378,154,3,75.64,0.01,224.6508,2,North,Credit Card,...,2,67,Other,Food,2.4,Returned,Neutral,9.53,WELCOME5,1.2
21,2023-01-22,1091,135,1,46.10,0.08,42.4120,9,North,Online,...,5,38,Other,Food,3.4,Returned,Neutral,5.01,nan,4.5
22,2023-01-23,1898,103,5,54.79,0.03,265.7315,4,South,Online,...,3,48,Other,Clothing,3.6,Not Returned,Negative,17.90,nan,4.4
23,2023-01-24,1289,129,6,56.05,0.28,242.1360,4,South,Credit Card,...,3,29,Female,Food,4.0,Not Returned,Neutral,14.26,WELCOME5,NaN
24,2023-01-25,1419,197,1,47.45,0.06,44.6030,7,South,Credit Card,...,3,18,Female,Electronics,4.3,Returned,Positive,11.26,FREESHIP,4.7
25,2023-01-26,1316,175,7,50.15,0.13,305.4135,1,West,Cash,...,4,63,Female,Clothing,3.0,Not Returned,Negative,19.14,FREESHIP,NaN
26,2023-01-27,1902,152,6,39.95,0.17,198.9510,9,East,Online,...,2,61,Male,Books,3.7,Returned,Neutral,14.07,nan,4.6
27,2023-01-28,1232,152,8,68.08,0.11,484.7296,2,South,Cash,...,4,36,Male,Clothing,1.7,Returned,Positive,14.53,WELCOME5,NaN
28,2023-01-29,1906,129,8,79.77,0.15,542.4360,8,North,Online,...,2,37,Male,Food,1.6,Not Returned,Neutral,5.07,WELCOME5,4.5
29,2023-01-30,1255,125,2,30.59,0.21,48.3322,2,North,Credit Card,...,4,27,Male,Clothing,1.9,Not Returned,Positive,16.34,FREESHIP,4.0
30,2023-01-31,1753,167,5,72.96,0.08,335.6160,2,South,Cash,...,2,37,Male,Clothing,1.2,Returned,Neutral,12.60,nan,1.8
31,2023-02-01,1578,198,6,29.11,0.11,155.4474,7,North,Cash,...,3,59,Other,Clothing,3.9,Not Returned,Positive,9.37,nan,1.2
32,2023-02-02,1020,145,6,34.12,0.02,200.6256,3,North,Credit Card,...,6,65,Other,Food,4.6,Not Returned,Positive,16.18,SAVE10,NaN
33,2023-02-03,1387,120,5,73.32,0.12,322.6080,2,North,Credit Card,...,1,55,Male,Electronics,2.1,Not Returned,Positive,19.70,SAVE10,4.7
34,2023-02-04,1996,177,1,30.02,0.00,30.0200,5,South,Cash,...,3,52,Male,Books,4.6,Not Returned,Positive,NaN,FREESHIP,NaN

<div class="alert alert-success">

**Solution 03:**
</div>

In [8]:
df.isna().sum()

date                 0
customer_id          0
product_id           0
quantity             0
price                0
discount             0
revenue              0
store_id             0
region               0
payment_method       0
is_member            0
delivery_days        0
customer_age         0
gender               0
product_category     0
rating               0
return_status        0
feedback             0
shipping_cost        2
coupon_code          0
delivery_rating     11
dtype: int64

<div class="alert alert-warning">

**4. Replace Non-Valuable Missing Values**

**Write a Pandas program to find and replace the missing values in a given DataFrame which do not have any valuable information.**

</div>

In [9]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values
0,2023-01-01,1739,114,3,16.38,0.05,46.6830,9,West,Credit Card,...,Male,Clothing,1.5,Not Returned,Negative,15.78,nan,2.9,unknown,value_1
1,2023-01-02,1020,183,9,12.63,0.24,86.3892,3,North,Cash,...,Female,Books,1.5,Returned,Neutral,10.14,nan,5.0,unknown,value_3
2,2023-01-03,1453,149,1,42.29,0.25,31.7175,3,West,Online,...,Female,Food,4.1,Returned,Positive,11.02,FREESHIP,2.4,no_data,value_5
3,2023-01-04,1058,172,7,16.25,0.13,98.9625,1,West,Credit Card,...,Other,Books,1.1,Not Returned,Positive,17.01,nan,NaN,unknown,value_5
4,2023-01-05,1210,164,5,29.51,0.16,123.9420,7,North,Cash,...,Female,Books,2.4,Not Returned,Positive,6.73,nan,NaN,no_data,unknown
5,2023-01-06,1819,192,4,98.13,0.09,357.1932,1,East,Online,...,Other,Food,2.7,Not Returned,Negative,8.56,WELCOME5,NaN,no_data,unknown
6,2023-01-07,1347,166,2,85.30,0.05,162.0700,4,North,Online,...,Other,Books,3.0,Not Returned,Neutral,14.92,nan,4.2,no_data,unknown
7,2023-01-08,1733,106,2,92.00,0.02,180.3200,4,South,Cash,...,Other,Books,1.5,Not Returned,Negative,11.35,nan,NaN,unknown,unknown
8,2023-01-09,1847,191,2,10.71,0.12,18.8496,4,South,Online,...,Other,Clothing,2.2,Returned,Positive,NaN,WELCOME5,4.1,unknown,unknown
9,2023-01-10,1148,194,1,49.77,0.20,39.8160,1,West,Cash,...,Female,Clothing,4.4,Not Returned,Neutral,11.11,SAVE10,4.9,Preferred morning delivery,no_data
10,2023-01-11,1570,122,3,41.97,0.23,96.9507,1,East,Credit Card,...,Male,Electronics,3.5,Not Returned,Neutral,11.99,SAVE10,2.4,Used loyalty points,unknown
11,2023-01-12,1768,107,6,17.34,0.09,94.6764,3,South,Cash,...,Male,Food,2.1,Returned,Negative,19.07,FREESHIP,4.9,Preferred morning delivery,no_data
12,2023-01-13,1387,160,7,68.76,0.17,399.4956,8,West,Credit Card,...,Other,Food,4.2,Returned,Neutral,14.54,nan,3.6,First-time customer,value_1
13,2023-01-14,1192,163,7,38.37,0.04,257.8464,5,West,Credit Card,...,Male,Clothing,5.0,Not Returned,Positive,8.90,WELCOME5,4.9,no_data,no_data
14,2023-01-15,1921,172,5,97.58,0.14,419.5940,2,East,Online,...,Male,Clothing,4.7,Returned,Negative,14.62,nan,2.1,First-time customer,value_2
15,2023-01-16,1367,161,6,14.55,0.28,62.8560,8,East,Cash,...,Female,Clothing,4.8,Not Returned,Positive,NaN,nan,3.0,Frequent buyer,unknown
16,2023-01-17,1052,128,1,59.34,0.05,56.3730,9,East,Online,...,Male,Food,3.4,Returned,Positive,14.05,nan,3.6,Used loyalty points,unknown
17,2023-01-18,1199,159,4,97.89,0.20,313.2480,7,West,Online,...,Female,Clothing,3.2,Not Returned,Positive,8.81,WELCOME5,NaN,unknown,no_data
18,2023-01-19,1117,119,7,88.80,0.04,596.7360,5,West,Credit Card,...,Male,Food,2.3,Returned,Positive,16.52,nan,NaN,unknown,unknown
19,2023-01-20,1122,164,2,38.18,0.14,65.6696,9,West,Online,...,Male,Electronics,3.7,Returned,Negative,13.06,nan,3.0,no_data,value_5
20,2023-01-21,1802,126,7,79.73,0.14,479.9746,6,North,Online,...,Male,Electronics,3.0,Not Returned,Neutral,17.69,SAVE10,2.0,unknown,no_data
21,2023-01-22,1976,109,3,53.82,0.06,151.7724,8,West,Credit Card,...,Male,Electronics,4.3,Not Returned,Negative,NaN,nan,2.5,Preferred morning delivery,no_data
22,2023-01-23,1526,148,7,61.36,0.00,429.5200,5,East,Online,...,Female,Electronics,4.0,Not Returned,Negative,18.65,nan,1.0,Frequent buyer,no_data
23,2023-01-24,1408,115,3,78.86,0.02,231.8484,8,West,Credit Card,...,Female,Books,1.4,Not Returned,Negative,17.67,nan,1.6,unknown,value_1
24,2023-01-25,1135,130,6,21.21,0.02,124.7148,7,East,Online,...,Male,Food,3.5,Not Returned,Negative,13.26,WELCOME5,3.4,unknown,unknown
25,2023-01-26,1424,184,9,46.76,0.17,349.2972,9,North,Cash,...,Female,Electronics,4.0,Not Returned,Negative,NaN,FREESHIP,3.1,First-time customer,unknown
26,2023-01-27,1469,185,1,60.42,0.17,50.1486,5,South,Cash,...,Male,Food,1.3,Not Returned,Positive,5.43,WELCOME5,2.8,unknown,no_data
27,2023-01-28,1164,124,6,49.94,0.04,287.6544,9,South,Online,...,Female,Food,4.0,Returned,Neutral,5.92,nan,NaN,Frequent buyer,no_data
28,2023-01-29,1280,185,3,69.04,0.29,147.0552,7,South,Cash,...,Female,Books,3.7,Returned,Positive,9.53,WELCOME5,NaN,Used loyalty points,unknown
29,2023-01-30,1926,109,5,51.64,0.21,203.9780,8,North,Credit Card,...,Other,Clothing,2.8,Not Returned,Neutral,5.57,SAVE10,2.5,Frequent buyer,no_data
30,2023-01-31,1961,196,2,60.51,0.25,90.7650,2,West,Online,...,Female,Food,4.2,Returned,Positive,5.06,WELCOME5,2.7,First-time customer,unknown
31,2023-02-01,1647,174,1,57.87,0.12,50.9256,6,East,Online,...,Female,Food,2.6,Not Returned,Positive,7.91,nan,NaN,unknown,value_4
32,2023-02-02,1895,145,6,14.36,0.27,62.8968,8,South,Online,...,Male,Electronics,2.1,Returned,Positive,19.67,nan,1.5,Requested gift wrap,no_data
33,2023-02-03,1165,155,2,22.50,0.15,38.2500,2,North,Online,...,Other,Clothing,4.1,Not Returned,Positive,13.35,FREESHIP,3.6,unknown,no_data
34,2023-02-04,1176,139,2,44.55,0.26,65.9340,4,East,Cash,...,Male,Food,3.1,Returned,Positive,10.09,nan,1.7,unknown,unknown

<div class="alert alert-success">

**Solution 04:**
</div>

In [10]:
df.replace({
    'customer_note': {
        'no_data': np.nan,
        'unknown': np.nan
    },
    'customer_values': {
        'no_data': np.nan,
        'unknown': np.nan
    }
}, inplace=True)

display(df.isna().any())
display(df.isna().sum())

date                False
customer_id         False
product_id          False
quantity            False
price               False
discount            False
revenue             False
store_id            False
region              False
payment_method      False
is_member           False
delivery_days       False
customer_age        False
gender              False
product_category    False
rating              False
return_status       False
feedback            False
shipping_cost        True
coupon_code         False
delivery_rating      True
customer_note        True
customer_values      True
dtype: bool

date                 0
customer_id          0
product_id           0
quantity             0
price                0
discount             0
revenue              0
store_id             0
region               0
payment_method       0
is_member            0
delivery_days        0
customer_age         0
gender               0
product_category     0
rating               0
return_status        0
feedback             0
shipping_cost        4
coupon_code          0
delivery_rating      9
customer_note       20
customer_values     26
dtype: int64

<div class="alert alert-warning">

**5. Drop Rows with Any Missing Value**

**Write a Pandas program to drop the rows where at least one element is missing in a given DataFrame.**

</div>

In [11]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values
0,2023-01-01,1686,192,9,63.66,0.08,527.1048,4,South,Online,...,Female,Food,1.3,Returned,Positive,NaN,WELCOME5,4.2,Frequent buyer,value_1
1,2023-01-02,1385,104,6,34.30,0.10,185.2200,8,West,Online,...,Other,Books,1.9,Not Returned,Positive,NaN,WELCOME5,3.3,unknown,unknown
2,2023-01-03,1252,115,3,21.02,0.20,50.4480,9,South,Cash,...,Other,Books,2.8,Returned,Positive,6.51,nan,1.6,no_data,value_5
3,2023-01-04,1247,171,9,10.40,0.02,91.7280,2,South,Credit Card,...,Female,Food,1.1,Not Returned,Positive,NaN,nan,1.3,unknown,value_1
4,2023-01-05,1212,157,7,92.68,0.25,486.5700,5,South,Credit Card,...,Other,Clothing,4.1,Not Returned,Negative,7.07,SAVE10,3.4,Frequent buyer,value_3
5,2023-01-06,1745,186,8,39.16,0.07,291.3504,2,South,Credit Card,...,Male,Books,4.1,Not Returned,Neutral,11.79,SAVE10,2.6,Frequent buyer,value_5
6,2023-01-07,1240,130,1,81.85,0.00,81.8500,1,North,Online,...,Other,Electronics,2.5,Not Returned,Neutral,14.57,nan,NaN,Frequent buyer,no_data
7,2023-01-08,1027,118,9,18.17,0.18,134.0946,4,South,Credit Card,...,Male,Clothing,1.5,Returned,Negative,NaN,nan,3.3,First-time customer,unknown
8,2023-01-09,1984,115,1,28.34,0.19,22.9554,1,East,Cash,...,Male,Food,1.7,Not Returned,Positive,11.33,WELCOME5,1.6,Requested gift wrap,no_data
9,2023-01-10,1003,157,7,34.83,0.05,231.6195,1,East,Cash,...,Male,Clothing,3.5,Not Returned,Positive,14.07,FREESHIP,4.0,First-time customer,unknown
10,2023-01-11,1082,188,3,34.03,0.16,85.7556,9,East,Online,...,Other,Food,3.0,Returned,Positive,19.76,SAVE10,2.6,Requested gift wrap,unknown
11,2023-01-12,1207,100,7,12.33,0.13,75.0897,9,East,Online,...,Other,Food,4.6,Not Returned,Neutral,10.11,nan,4.2,Preferred morning delivery,value_3
12,2023-01-13,1225,146,8,41.23,0.21,260.5736,8,West,Cash,...,Female,Clothing,2.7,Not Returned,Negative,9.69,SAVE10,4.8,unknown,value_1
13,2023-01-14,1680,119,4,52.82,0.27,154.2344,5,South,Cash,...,Female,Clothing,1.1,Returned,Neutral,9.40,WELCOME5,1.0,First-time customer,value_5
14,2023-01-15,1409,194,6,42.29,0.10,228.3660,1,East,Online,...,Male,Clothing,4.6,Returned,Positive,7.37,nan,4.5,First-time customer,value_4
15,2023-01-16,1634,100,7,72.68,0.23,391.7452,9,West,Online,...,Male,Books,3.2,Not Returned,Neutral,12.32,WELCOME5,2.4,Frequent buyer,value_4
16,2023-01-17,1398,161,9,83.33,0.15,637.4745,8,South,Cash,...,Male,Clothing,2.6,Not Returned,Negative,15.10,FREESHIP,4.1,unknown,value_1
17,2023-01-18,1162,101,8,30.06,0.27,175.5504,6,North,Online,...,Other,Clothing,1.7,Not Returned,Neutral,NaN,FREESHIP,NaN,no_data,value_2
18,2023-01-19,1025,140,5,27.84,0.09,126.6720,9,West,Credit Card,...,Male,Food,1.1,Not Returned,Negative,16.16,WELCOME5,4.4,Frequent buyer,value_3
19,2023-01-20,1903,137,4,60.09,0.15,204.3060,3,West,Credit Card,...,Other,Food,4.0,Not Returned,Neutral,16.83,SAVE10,4.8,unknown,no_data
20,2023-01-21,1123,191,3,73.03,0.08,201.5628,4,West,Online,...,Male,Clothing,1.3,Not Returned,Neutral,NaN,WELCOME5,4.2,unknown,value_2
21,2023-01-22,1719,133,3,84.89,0.07,236.8431,9,East,Credit Card,...,Other,Books,1.1,Returned,Positive,15.88,nan,NaN,no_data,no_data
22,2023-01-23,1185,182,1,53.05,0.01,52.5195,2,North,Online,...,Other,Books,3.5,Not Returned,Neutral,15.42,WELCOME5,NaN,no_data,value_1
23,2023-01-24,1298,109,7,26.59,0.07,173.1009,5,North,Credit Card,...,Female,Books,3.6,Returned,Positive,6.56,WELCOME5,2.5,no_data,value_4
24,2023-01-25,1866,125,2,13.21,0.11,23.5138,4,North,Online,...,Male,Books,4.7,Returned,Positive,18.12,nan,3.9,no_data,unknown
25,2023-01-26,1434,122,5,39.52,0.11,175.8640,3,South,Credit Card,...,Male,Food,3.5,Not Returned,Neutral,17.95,nan,3.9,unknown,value_3
26,2023-01-27,1102,185,6,28.83,0.16,145.3032,8,East,Cash,...,Female,Food,3.1,Not Returned,Positive,18.57,SAVE10,2.2,First-time customer,value_3
27,2023-01-28,1706,145,1,34.42,0.16,28.9128,8,West,Online,...,Male,Clothing,1.1,Not Returned,Neutral,NaN,FREESHIP,1.4,no_data,value_2
28,2023-01-29,1086,140,4,30.88,0.09,112.4032,5,South,Cash,...,Male,Clothing,4.3,Not Returned,Neutral,8.86,WELCOME5,2.6,no_data,value_5
29,2023-01-30,1055,182,6,32.30,0.02,189.9240,2,South,Credit Card,...,Male,Books,3.8,Returned,Negative,7.82,WELCOME5,2.1,unknown,value_2
30,2023-01-31,1184,183,7,76.58,0.27,391.3238,1,East,Online,...,Other,Books,4.1,Not Returned,Neutral,13.06,nan,NaN,unknown,value_1
31,2023-02-01,1334,145,2,49.87,0.09,90.7634,2,West,Credit Card,...,Male,Clothing,1.7,Not Returned,Positive,NaN,SAVE10,4.5,First-time customer,unknown
32,2023-02-02,1460,104,2,49.44,0.18,81.0816,2,South,Cash,...,Male,Electronics,2.9,Returned,Neutral,14.33,SAVE10,3.9,First-time customer,no_data
33,2023-02-03,1803,189,7,42.43,0.14,255.4286,3,East,Credit Card,...,Female,Books,3.4,Returned,Neutral,10.63,WELCOME5,3.5,First-time customer,value_2
34,2023-02-04,1740,123,8,88.40,0.10,636.4800,4,West,Credit Card,...,Female,Electronics,5.0,Not Returned,Neutral,10.55,FREESHIP,3.4,no_data,value_4

<div class="alert alert-success">

**Solution 05:**
</div>

In [12]:
dropped_df = df.dropna(how='any')
display(dropped_df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values
2,2023-01-03,1252,115,3,21.02,0.20,50.4480,9,South,Cash,...,Other,Books,2.8,Returned,Positive,6.51,nan,1.6,no_data,value_5
4,2023-01-05,1212,157,7,92.68,0.25,486.5700,5,South,Credit Card,...,Other,Clothing,4.1,Not Returned,Negative,7.07,SAVE10,3.4,Frequent buyer,value_3
5,2023-01-06,1745,186,8,39.16,0.07,291.3504,2,South,Credit Card,...,Male,Books,4.1,Not Returned,Neutral,11.79,SAVE10,2.6,Frequent buyer,value_5
8,2023-01-09,1984,115,1,28.34,0.19,22.9554,1,East,Cash,...,Male,Food,1.7,Not Returned,Positive,11.33,WELCOME5,1.6,Requested gift wrap,no_data
9,2023-01-10,1003,157,7,34.83,0.05,231.6195,1,East,Cash,...,Male,Clothing,3.5,Not Returned,Positive,14.07,FREESHIP,4.0,First-time customer,unknown
10,2023-01-11,1082,188,3,34.03,0.16,85.7556,9,East,Online,...,Other,Food,3.0,Returned,Positive,19.76,SAVE10,2.6,Requested gift wrap,unknown
11,2023-01-12,1207,100,7,12.33,0.13,75.0897,9,East,Online,...,Other,Food,4.6,Not Returned,Neutral,10.11,nan,4.2,Preferred morning delivery,value_3
12,2023-01-13,1225,146,8,41.23,0.21,260.5736,8,West,Cash,...,Female,Clothing,2.7,Not Returned,Negative,9.69,SAVE10,4.8,unknown,value_1
13,2023-01-14,1680,119,4,52.82,0.27,154.2344,5,South,Cash,...,Female,Clothing,1.1,Returned,Neutral,9.40,WELCOME5,1.0,First-time customer,value_5
14,2023-01-15,1409,194,6,42.29,0.10,228.3660,1,East,Online,...,Male,Clothing,4.6,Returned,Positive,7.37,nan,4.5,First-time customer,value_4
15,2023-01-16,1634,100,7,72.68,0.23,391.7452,9,West,Online,...,Male,Books,3.2,Not Returned,Neutral,12.32,WELCOME5,2.4,Frequent buyer,value_4
16,2023-01-17,1398,161,9,83.33,0.15,637.4745,8,South,Cash,...,Male,Clothing,2.6,Not Returned,Negative,15.10,FREESHIP,4.1,unknown,value_1
18,2023-01-19,1025,140,5,27.84,0.09,126.6720,9,West,Credit Card,...,Male,Food,1.1,Not Returned,Negative,16.16,WELCOME5,4.4,Frequent buyer,value_3
19,2023-01-20,1903,137,4,60.09,0.15,204.3060,3,West,Credit Card,...,Other,Food,4.0,Not Returned,Neutral,16.83,SAVE10,4.8,unknown,no_data
23,2023-01-24,1298,109,7,26.59,0.07,173.1009,5,North,Credit Card,...,Female,Books,3.6,Returned,Positive,6.56,WELCOME5,2.5,no_data,value_4
24,2023-01-25,1866,125,2,13.21,0.11,23.5138,4,North,Online,...,Male,Books,4.7,Returned,Positive,18.12,nan,3.9,no_data,unknown
25,2023-01-26,1434,122,5,39.52,0.11,175.8640,3,South,Credit Card,...,Male,Food,3.5,Not Returned,Neutral,17.95,nan,3.9,unknown,value_3
26,2023-01-27,1102,185,6,28.83,0.16,145.3032,8,East,Cash,...,Female,Food,3.1,Not Returned,Positive,18.57,SAVE10,2.2,First-time customer,value_3
28,2023-01-29,1086,140,4,30.88,0.09,112.4032,5,South,Cash,...,Male,Clothing,4.3,Not Returned,Neutral,8.86,WELCOME5,2.6,no_data,value_5
29,2023-01-30,1055,182,6,32.30,0.02,189.9240,2,South,Credit Card,...,Male,Books,3.8,Returned,Negative,7.82,WELCOME5,2.1,unknown,value_2
32,2023-02-02,1460,104,2,49.44,0.18,81.0816,2,South,Cash,...,Male,Electronics,2.9,Returned,Neutral,14.33,SAVE10,3.9,First-time customer,no_data
33,2023-02-03,1803,189,7,42.43,0.14,255.4286,3,East,Credit Card,...,Female,Books,3.4,Returned,Neutral,10.63,WELCOME5,3.5,First-time customer,value_2
34,2023-02-04,1740,123,8,88.40,0.10,636.4800,4,West,Credit Card,...,Female,Electronics,5.0,Not Returned,Neutral,10.55,FREESHIP,3.4,no_data,value_4

<div class="alert alert-warning">

**6. Drop Columns with Any Missing Value**

**Write a Pandas program to drop the columns where at least one element is missing in a given DataFrame.**

</div>

In [13]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values
0,2023-01-01,1711,194,6,67.69,0.16,341.1576,7,West,Cash,...,Other,Food,2.9,Returned,Neutral,6.86,SAVE10,NaN,Requested gift wrap,no_data
1,2023-01-02,1556,152,3,31.21,0.28,67.4136,3,West,Credit Card,...,Male,Electronics,3.0,Returned,Negative,15.04,nan,3.6,Requested gift wrap,no_data
2,2023-01-03,1422,166,4,84.81,0.07,315.4932,5,South,Cash,...,Female,Books,2.0,Returned,Negative,16.59,nan,3.7,Frequent buyer,unknown
3,2023-01-04,1998,152,8,46.69,0.06,351.1088,4,North,Online,...,Other,Electronics,3.3,Returned,Neutral,10.40,WELCOME5,3.5,unknown,value_3
4,2023-01-05,1540,127,4,46.58,0.25,139.7400,6,South,Credit Card,...,Female,Clothing,4.2,Returned,Neutral,15.90,WELCOME5,1.0,Preferred morning delivery,value_3
5,2023-01-06,1947,126,4,81.67,0.07,303.8124,9,North,Cash,...,Female,Books,4.7,Returned,Negative,7.21,nan,NaN,Requested gift wrap,value_3
6,2023-01-07,1036,135,9,67.24,0.22,472.0248,8,West,Cash,...,Female,Books,4.6,Returned,Neutral,NaN,FREESHIP,2.2,Preferred morning delivery,value_2
7,2023-01-08,1945,118,2,11.39,0.26,16.8572,1,West,Online,...,Male,Electronics,1.8,Not Returned,Neutral,NaN,nan,NaN,unknown,no_data
8,2023-01-09,1431,174,9,70.77,0.14,547.7598,4,West,Credit Card,...,Female,Food,2.4,Not Returned,Positive,9.50,nan,NaN,no_data,unknown
9,2023-01-10,1526,178,1,58.30,0.00,58.3000,1,East,Cash,...,Female,Books,3.8,Not Returned,Neutral,10.24,nan,2.4,Preferred morning delivery,value_2
10,2023-01-11,1569,136,6,73.39,0.20,352.2720,8,East,Online,...,Female,Food,4.7,Returned,Negative,5.39,nan,2.7,no_data,value_4
11,2023-01-12,1027,161,7,67.95,0.23,366.2505,6,East,Online,...,Male,Electronics,3.0,Returned,Positive,5.09,nan,NaN,Frequent buyer,unknown
12,2023-01-13,1843,122,8,98.63,0.06,741.6976,6,East,Cash,...,Male,Clothing,1.8,Not Returned,Positive,11.21,nan,2.2,unknown,value_5
13,2023-01-14,1755,152,5,32.99,0.21,130.3105,9,West,Credit Card,...,Male,Clothing,1.1,Not Returned,Neutral,7.58,nan,4.4,unknown,value_3
14,2023-01-15,1592,125,8,54.41,0.16,365.6352,9,East,Credit Card,...,Male,Clothing,3.1,Not Returned,Neutral,NaN,nan,2.5,Frequent buyer,value_1
15,2023-01-16,1606,167,2,46.41,0.20,74.2560,3,East,Cash,...,Other,Food,4.1,Returned,Positive,11.80,FREESHIP,3.6,Requested gift wrap,unknown
16,2023-01-17,1219,107,8,52.97,0.10,381.3840,5,East,Cash,...,Male,Electronics,1.9,Not Returned,Negative,15.10,FREESHIP,2.4,unknown,unknown
17,2023-01-18,1512,129,4,45.34,0.19,146.9016,6,South,Credit Card,...,Female,Clothing,3.2,Returned,Positive,16.72,nan,NaN,unknown,unknown
18,2023-01-19,1790,170,8,11.87,0.25,71.2200,1,West,Cash,...,Female,Food,4.5,Returned,Negative,5.47,SAVE10,1.4,unknown,value_4
19,2023-01-20,1838,161,9,42.92,0.21,305.1612,9,North,Credit Card,...,Other,Food,1.3,Not Returned,Negative,19.39,SAVE10,NaN,no_data,value_3
20,2023-01-21,1577,160,9,31.39,0.26,209.0574,4,East,Cash,...,Female,Clothing,3.4,Not Returned,Neutral,13.95,nan,4.9,Preferred morning delivery,value_2
21,2023-01-22,1068,106,1,28.17,0.18,23.0994,8,North,Cash,...,Male,Food,2.8,Not Returned,Positive,NaN,FREESHIP,NaN,Requested gift wrap,unknown
22,2023-01-23,1873,171,3,52.19,0.23,120.5589,5,West,Credit Card,...,Female,Food,3.4,Returned,Neutral,8.55,nan,4.9,unknown,value_4
23,2023-01-24,1226,186,9,37.52,0.11,300.5352,2,North,Online,...,Other,Books,1.3,Returned,Negative,6.94,SAVE10,4.4,First-time customer,no_data
24,2023-01-25,1432,153,8,72.64,0.02,569.4976,6,South,Cash,...,Male,Clothing,4.6,Not Returned,Positive,19.21,nan,NaN,no_data,value_1
25,2023-01-26,1442,157,3,41.76,0.11,111.4992,9,North,Cash,...,Other,Food,3.0,Not Returned,Neutral,9.54,nan,NaN,no_data,value_5
26,2023-01-27,1274,179,2,88.33,0.16,148.3944,5,West,Credit Card,...,Other,Food,3.0,Not Returned,Neutral,NaN,WELCOME5,4.3,unknown,no_data
27,2023-01-28,1624,162,5,73.57,0.08,338.4220,7,North,Online,...,Other,Clothing,3.4,Returned,Positive,6.91,SAVE10,NaN,unknown,unknown
28,2023-01-29,1518,103,5,37.31,0.13,162.2985,3,North,Credit Card,...,Female,Books,2.9,Not Returned,Positive,14.35,nan,2.0,Preferred morning delivery,no_data
29,2023-01-30,1555,132,1,85.36,0.30,59.7520,1,East,Credit Card,...,Other,Clothing,1.6,Returned,Negative,7.87,WELCOME5,1.3,no_data,unknown
30,2023-01-31,1010,137,5,74.67,0.21,294.9465,7,East,Online,...,Male,Books,2.1,Not Returned,Neutral,11.36,nan,3.1,Used loyalty points,value_1
31,2023-02-01,1211,126,4,25.71,0.21,81.2436,6,North,Online,...,Male,Food,1.6,Returned,Neutral,7.57,nan,3.4,unknown,no_data
32,2023-02-02,1238,153,3,23.27,0.00,69.8100,7,East,Cash,...,Male,Books,4.5,Returned,Negative,19.01,nan,4.3,First-time customer,value_5
33,2023-02-03,1159,173,3,26.03,0.17,64.8147,1,North,Credit Card,...,Male,Electronics,4.0,Returned,Neutral,19.66,nan,NaN,Frequent buyer,unknown
34,2023-02-04,1433,118,3,91.14,0.13,237.8754,4,West,Credit Card,...,Other,Electronics,1.2,Not Returned,Negative,17.13,WELCOME5,2.7,unknown,value_1

<div class="alert alert-success">

**Solution 06:**
</div>

In [14]:
# Drop columns with any missing value
dropped_df = df.dropna(axis=1, how='any')
display(dropped_df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,coupon_code,customer_note,customer_values
0,2023-01-01,1711,194,6,67.69,0.16,341.1576,7,West,Cash,...,2,45,Other,Food,2.9,Returned,Neutral,SAVE10,Requested gift wrap,no_data
1,2023-01-02,1556,152,3,31.21,0.28,67.4136,3,West,Credit Card,...,3,52,Male,Electronics,3.0,Returned,Negative,nan,Requested gift wrap,no_data
2,2023-01-03,1422,166,4,84.81,0.07,315.4932,5,South,Cash,...,3,35,Female,Books,2.0,Returned,Negative,nan,Frequent buyer,unknown
3,2023-01-04,1998,152,8,46.69,0.06,351.1088,4,North,Online,...,6,43,Other,Electronics,3.3,Returned,Neutral,WELCOME5,unknown,value_3
4,2023-01-05,1540,127,4,46.58,0.25,139.7400,6,South,Credit Card,...,5,30,Female,Clothing,4.2,Returned,Neutral,WELCOME5,Preferred morning delivery,value_3
5,2023-01-06,1947,126,4,81.67,0.07,303.8124,9,North,Cash,...,6,21,Female,Books,4.7,Returned,Negative,nan,Requested gift wrap,value_3
6,2023-01-07,1036,135,9,67.24,0.22,472.0248,8,West,Cash,...,4,69,Female,Books,4.6,Returned,Neutral,FREESHIP,Preferred morning delivery,value_2
7,2023-01-08,1945,118,2,11.39,0.26,16.8572,1,West,Online,...,4,46,Male,Electronics,1.8,Not Returned,Neutral,nan,unknown,no_data
8,2023-01-09,1431,174,9,70.77,0.14,547.7598,4,West,Credit Card,...,5,40,Female,Food,2.4,Not Returned,Positive,nan,no_data,unknown
9,2023-01-10,1526,178,1,58.30,0.00,58.3000,1,East,Cash,...,5,67,Female,Books,3.8,Not Returned,Neutral,nan,Preferred morning delivery,value_2
10,2023-01-11,1569,136,6,73.39,0.20,352.2720,8,East,Online,...,5,38,Female,Food,4.7,Returned,Negative,nan,no_data,value_4
11,2023-01-12,1027,161,7,67.95,0.23,366.2505,6,East,Online,...,3,46,Male,Electronics,3.0,Returned,Positive,nan,Frequent buyer,unknown
12,2023-01-13,1843,122,8,98.63,0.06,741.6976,6,East,Cash,...,6,57,Male,Clothing,1.8,Not Returned,Positive,nan,unknown,value_5
13,2023-01-14,1755,152,5,32.99,0.21,130.3105,9,West,Credit Card,...,4,51,Male,Clothing,1.1,Not Returned,Neutral,nan,unknown,value_3
14,2023-01-15,1592,125,8,54.41,0.16,365.6352,9,East,Credit Card,...,2,54,Male,Clothing,3.1,Not Returned,Neutral,nan,Frequent buyer,value_1
15,2023-01-16,1606,167,2,46.41,0.20,74.2560,3,East,Cash,...,4,63,Other,Food,4.1,Returned,Positive,FREESHIP,Requested gift wrap,unknown
16,2023-01-17,1219,107,8,52.97,0.10,381.3840,5,East,Cash,...,2,37,Male,Electronics,1.9,Not Returned,Negative,FREESHIP,unknown,unknown
17,2023-01-18,1512,129,4,45.34,0.19,146.9016,6,South,Credit Card,...,3,29,Female,Clothing,3.2,Returned,Positive,nan,unknown,unknown
18,2023-01-19,1790,170,8,11.87,0.25,71.2200,1,West,Cash,...,6,24,Female,Food,4.5,Returned,Negative,SAVE10,unknown,value_4
19,2023-01-20,1838,161,9,42.92,0.21,305.1612,9,North,Credit Card,...,1,29,Other,Food,1.3,Not Returned,Negative,SAVE10,no_data,value_3
20,2023-01-21,1577,160,9,31.39,0.26,209.0574,4,East,Cash,...,5,41,Female,Clothing,3.4,Not Returned,Neutral,nan,Preferred morning delivery,value_2
21,2023-01-22,1068,106,1,28.17,0.18,23.0994,8,North,Cash,...,6,35,Male,Food,2.8,Not Returned,Positive,FREESHIP,Requested gift wrap,unknown
22,2023-01-23,1873,171,3,52.19,0.23,120.5589,5,West,Credit Card,...,1,57,Female,Food,3.4,Returned,Neutral,nan,unknown,value_4
23,2023-01-24,1226,186,9,37.52,0.11,300.5352,2,North,Online,...,5,24,Other,Books,1.3,Returned,Negative,SAVE10,First-time customer,no_data
24,2023-01-25,1432,153,8,72.64,0.02,569.4976,6,South,Cash,...,4,31,Male,Clothing,4.6,Not Returned,Positive,nan,no_data,value_1
25,2023-01-26,1442,157,3,41.76,0.11,111.4992,9,North,Cash,...,2,34,Other,Food,3.0,Not Returned,Neutral,nan,no_data,value_5
26,2023-01-27,1274,179,2,88.33,0.16,148.3944,5,West,Credit Card,...,1,48,Other,Food,3.0,Not Returned,Neutral,WELCOME5,unknown,no_data
27,2023-01-28,1624,162,5,73.57,0.08,338.4220,7,North,Online,...,4,18,Other,Clothing,3.4,Returned,Positive,SAVE10,unknown,unknown
28,2023-01-29,1518,103,5,37.31,0.13,162.2985,3,North,Credit Card,...,3,30,Female,Books,2.9,Not Returned,Positive,nan,Preferred morning delivery,no_data
29,2023-01-30,1555,132,1,85.36,0.30,59.7520,1,East,Credit Card,...,6,26,Other,Clothing,1.6,Returned,Negative,WELCOME5,no_data,unknown
30,2023-01-31,1010,137,5,74.67,0.21,294.9465,7,East,Online,...,5,21,Male,Books,2.1,Not Returned,Neutral,nan,Used loyalty points,value_1
31,2023-02-01,1211,126,4,25.71,0.21,81.2436,6,North,Online,...,1,26,Male,Food,1.6,Returned,Neutral,nan,unknown,no_data
32,2023-02-02,1238,153,3,23.27,0.00,69.8100,7,East,Cash,...,6,36,Male,Books,4.5,Returned,Negative,nan,First-time customer,value_5
33,2023-02-03,1159,173,3,26.03,0.17,64.8147,1,North,Credit Card,...,5,34,Male,Electronics,4.0,Returned,Neutral,nan,Frequent buyer,unknown
34,2023-02-04,1433,118,3,91.14,0.13,237.8754,4,West,Credit Card,...,5,32,Other,Electronics,1.2,Not Returned,Negative,WELCOME5,unknown,value_1