[Pandas Missing Values](https://www.w3resource.com/python-exercises/pandas/missing-values/index.php)

In [1]:
import pandas as pd
import numpy as np

<div class="alert alert-warning">

**1. Detect Missing Values**

**Write a Pandas program to detect missing values of a given DataFrame. Display True or False.**

</div>

In [2]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1886,188,7,59.07,0.11,368.0061,3,West,Cash,...,2,18,Other,Clothing,1.9,Returned,Negative,NaN,WELCOME5,NaN
1,2023-01-02,1073,142,7,39.06,0.15,232.4070,8,South,Online,...,6,58,Other,Electronics,2.6,Not Returned,Positive,14.10,WELCOME5,NaN
2,2023-01-03,1867,138,4,27.04,0.00,108.1600,1,West,Cash,...,3,43,Male,Food,1.3,Not Returned,Neutral,12.51,WELCOME5,NaN
3,2023-01-04,1053,153,1,47.00,0.12,41.3600,5,West,Cash,...,3,50,Female,Food,2.4,Returned,Neutral,18.17,nan,2.3
4,2023-01-05,1697,145,9,49.27,0.02,434.5614,2,East,Credit Card,...,4,45,Male,Books,4.6,Returned,Neutral,7.81,WELCOME5,NaN
5,2023-01-06,1590,133,6,49.81,0.01,295.8714,2,West,Credit Card,...,4,65,Female,Food,1.8,Returned,Neutral,11.49,WELCOME5,4.6
6,2023-01-07,1806,173,1,74.63,0.23,57.4651,5,South,Cash,...,5,35,Other,Books,4.0,Returned,Neutral,18.66,nan,4.6
7,2023-01-08,1627,102,1,25.94,0.05,24.6430,9,East,Credit Card,...,2,22,Male,Electronics,1.6,Returned,Negative,5.23,nan,1.1
8,2023-01-09,1552,100,1,60.94,0.14,52.4084,7,South,Credit Card,...,5,45,Other,Food,1.5,Not Returned,Positive,NaN,nan,NaN
9,2023-01-10,1199,137,8,31.31,0.21,197.8792,9,North,Cash,...,3,32,Female,Electronics,4.4,Returned,Neutral,NaN,nan,4.6
10,2023-01-11,1364,178,6,94.48,0.12,498.8544,8,North,Online,...,3,19,Female,Electronics,1.8,Returned,Negative,6.43,nan,3.4
11,2023-01-12,1487,136,6,70.03,0.27,306.7314,6,South,Cash,...,2,24,Female,Food,1.1,Not Returned,Neutral,NaN,FREESHIP,1.3
12,2023-01-13,1447,133,8,40.40,0.01,319.9680,6,West,Credit Card,...,5,34,Male,Food,4.2,Returned,Positive,5.32,SAVE10,2.6
13,2023-01-14,1374,104,8,67.31,0.21,425.3992,2,South,Cash,...,2,45,Female,Books,1.2,Not Returned,Neutral,16.35,FREESHIP,NaN
14,2023-01-15,1941,159,5,44.77,0.17,185.7955,6,South,Cash,...,6,52,Other,Electronics,2.7,Not Returned,Negative,NaN,FREESHIP,2.4
15,2023-01-16,1133,158,1,11.30,0.21,8.9270,6,East,Online,...,1,45,Male,Books,2.5,Returned,Negative,18.24,WELCOME5,3.3
16,2023-01-17,1651,135,5,98.42,0.24,373.9960,4,North,Online,...,6,49,Male,Electronics,4.3,Not Returned,Neutral,13.10,WELCOME5,1.9
17,2023-01-18,1993,131,1,47.49,0.17,39.4167,7,North,Online,...,1,30,Male,Food,3.9,Not Returned,Positive,5.60,nan,5.0
18,2023-01-19,1243,168,8,67.94,0.17,451.1216,6,South,Cash,...,6,51,Female,Books,2.8,Not Returned,Neutral,5.83,SAVE10,2.0
19,2023-01-20,1498,149,4,28.37,0.03,110.0756,8,East,Credit Card,...,2,34,Other,Books,3.5,Returned,Neutral,17.66,WELCOME5,1.1
20,2023-01-21,1409,191,2,43.69,0.19,70.7778,2,North,Credit Card,...,3,64,Female,Clothing,2.2,Returned,Negative,7.05,WELCOME5,NaN
21,2023-01-22,1013,188,2,62.95,0.05,119.6050,6,South,Credit Card,...,3,60,Male,Books,4.9,Not Returned,Positive,15.03,FREESHIP,3.5
22,2023-01-23,1174,153,2,74.83,0.12,131.7008,2,North,Online,...,3,54,Female,Clothing,4.8,Returned,Neutral,6.39,WELCOME5,4.1
23,2023-01-24,1254,158,9,96.60,0.06,817.2360,2,East,Online,...,1,66,Male,Books,3.8,Not Returned,Negative,8.40,SAVE10,3.6
24,2023-01-25,1519,129,7,60.73,0.18,348.5902,1,North,Cash,...,5,39,Female,Electronics,3.1,Not Returned,Positive,16.98,nan,1.9
25,2023-01-26,1846,186,3,77.37,0.13,201.9357,2,East,Cash,...,2,22,Male,Food,1.3,Not Returned,Neutral,8.32,nan,NaN
26,2023-01-27,1469,175,4,87.21,0.05,331.3980,5,South,Credit Card,...,5,42,Other,Books,4.8,Not Returned,Neutral,5.28,nan,NaN
27,2023-01-28,1099,192,5,94.24,0.14,405.2320,4,West,Credit Card,...,1,31,Male,Food,2.9,Returned,Negative,NaN,FREESHIP,2.8
28,2023-01-29,1034,143,4,86.55,0.14,297.7320,1,East,Credit Card,...,2,46,Other,Electronics,2.8,Returned,Neutral,7.72,nan,2.4
29,2023-01-30,1034,140,3,44.01,0.22,102.9834,3,North,Credit Card,...,6,62,Female,Clothing,3.6,Returned,Negative,10.38,WELCOME5,1.6
30,2023-01-31,1482,123,1,34.24,0.24,26.0224,4,South,Cash,...,5,32,Female,Clothing,4.8,Not Returned,Neutral,18.48,WELCOME5,NaN
31,2023-02-01,1036,129,1,28.11,0.10,25.2990,4,North,Credit Card,...,2,64,Female,Clothing,3.1,Returned,Neutral,NaN,SAVE10,3.0
32,2023-02-02,1749,126,6,48.47,0.18,238.4724,4,South,Online,...,3,22,Other,Books,3.0,Not Returned,Positive,5.72,nan,3.5
33,2023-02-03,1432,125,6,25.45,0.29,108.4170,6,South,Credit Card,...,5,50,Male,Food,1.8,Not Returned,Positive,16.57,FREESHIP,1.6
34,2023-02-04,1672,161,9,10.59,0.16,80.0604,4,North,Credit Card,...,4,66,Female,Food,2.4,Returned,Positive,NaN,SAVE10,1.1

<div class="alert alert-success">

**Solution 01:**
</div>

In [3]:
print(type(df.isna()))
df.isna()

<class 'pandas.core.frame.DataFrame'>

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
31,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
32,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [4]:
print(df.isna().any())  
df.isna().sum()

date                False
customer_id         False
product_id          False
quantity            False
price               False
discount            False
revenue             False
store_id            False
region              False
payment_method      False
is_member           False
delivery_days       False
customer_age        False
gender              False
product_category    False
rating              False
return_status       False
feedback            False
shipping_cost        True
coupon_code         False
delivery_rating      True
dtype: bool

date                 0
customer_id          0
product_id           0
quantity             0
price                0
discount             0
revenue              0
store_id             0
region               0
payment_method       0
is_member            0
delivery_days        0
customer_age         0
gender               0
product_category     0
rating               0
return_status        0
feedback             0
shipping_cost        8
coupon_code          0
delivery_rating     10
dtype: int64

<div class="alert alert-warning">

**2. Identify Columns with Missing Values**

**Write a Pandas program to identify the column(s) of a given DataFrame which have at least one missing value.**

</div>

In [5]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1995,125,2,15.30,0.08,28.1520,6,East,Online,...,4,55,Male,Books,1.7,Returned,Negative,10.46,SAVE10,NaN
1,2023-01-02,1456,144,2,21.49,0.10,38.6820,1,East,Credit Card,...,4,34,Male,Food,2.4,Not Returned,Negative,6.75,nan,2.4
2,2023-01-03,1700,107,2,77.85,0.04,149.4720,8,South,Online,...,3,67,Other,Electronics,3.1,Returned,Positive,17.31,SAVE10,1.1
3,2023-01-04,1432,149,1,23.05,0.13,20.0535,4,North,Online,...,3,33,Other,Electronics,4.4,Returned,Neutral,6.45,SAVE10,4.6
4,2023-01-05,1615,149,9,50.95,0.06,431.0370,6,South,Credit Card,...,2,60,Other,Electronics,3.1,Not Returned,Negative,9.36,WELCOME5,NaN
5,2023-01-06,1997,181,9,97.20,0.26,647.3520,4,North,Online,...,6,63,Female,Electronics,3.9,Not Returned,Negative,NaN,nan,2.6
6,2023-01-07,1250,101,6,19.26,0.25,86.6700,6,South,Cash,...,1,44,Female,Food,2.2,Returned,Neutral,NaN,nan,2.8
7,2023-01-08,1942,125,9,26.44,0.15,202.2660,3,West,Credit Card,...,2,37,Other,Books,3.8,Not Returned,Negative,15.43,FREESHIP,1.9
8,2023-01-09,1258,174,9,57.11,0.13,447.1713,7,East,Online,...,3,59,Other,Books,1.6,Not Returned,Positive,9.28,FREESHIP,NaN
9,2023-01-10,1009,130,4,41.58,0.16,139.7088,5,West,Cash,...,5,61,Other,Electronics,2.1,Not Returned,Neutral,NaN,SAVE10,4.6
10,2023-01-11,1919,178,4,85.01,0.12,299.2352,1,North,Credit Card,...,2,47,Male,Clothing,2.4,Returned,Positive,8.49,nan,NaN
11,2023-01-12,1069,155,8,42.49,0.19,275.3352,7,East,Cash,...,5,50,Other,Food,3.3,Not Returned,Positive,5.70,SAVE10,NaN
12,2023-01-13,1317,182,7,70.81,0.09,451.0597,7,East,Cash,...,5,62,Male,Electronics,2.9,Returned,Negative,17.76,nan,3.6
13,2023-01-14,1199,118,1,67.99,0.18,55.7518,9,West,Cash,...,3,47,Female,Clothing,1.7,Returned,Neutral,16.43,WELCOME5,3.1
14,2023-01-15,1730,136,8,71.86,0.25,431.1600,8,South,Cash,...,5,25,Other,Books,2.5,Not Returned,Neutral,7.36,nan,3.8
15,2023-01-16,1100,110,2,87.91,0.23,135.3814,3,East,Cash,...,4,50,Female,Electronics,1.1,Returned,Neutral,10.93,nan,NaN
16,2023-01-17,1754,183,3,40.17,0.17,100.0233,4,North,Cash,...,5,29,Male,Electronics,3.1,Returned,Neutral,NaN,SAVE10,3.8
17,2023-01-18,1197,198,1,52.94,0.00,52.9400,4,South,Credit Card,...,4,26,Female,Clothing,1.2,Not Returned,Negative,18.82,FREESHIP,2.3
18,2023-01-19,1436,181,4,33.10,0.12,116.5120,7,West,Online,...,4,33,Female,Food,3.5,Not Returned,Negative,5.46,FREESHIP,4.2
19,2023-01-20,1324,114,8,33.51,0.14,230.5488,8,South,Online,...,4,62,Other,Clothing,3.0,Returned,Positive,6.19,WELCOME5,4.7
20,2023-01-21,1410,128,5,58.25,0.06,273.7750,8,East,Credit Card,...,1,26,Female,Clothing,1.2,Returned,Neutral,13.95,WELCOME5,1.7
21,2023-01-22,1927,113,8,48.76,0.30,273.0560,1,North,Cash,...,3,30,Other,Books,3.3,Not Returned,Negative,8.00,FREESHIP,NaN
22,2023-01-23,1169,173,9,80.07,0.28,518.8536,5,East,Cash,...,2,28,Male,Electronics,1.2,Returned,Negative,NaN,nan,2.4
23,2023-01-24,1975,137,4,63.91,0.01,253.0836,4,North,Credit Card,...,4,30,Female,Books,1.8,Returned,Neutral,NaN,FREESHIP,3.5
24,2023-01-25,1100,107,1,84.46,0.05,80.2370,4,North,Credit Card,...,3,35,Other,Food,3.2,Returned,Negative,9.29,nan,4.8
25,2023-01-26,1843,125,3,30.92,0.20,74.2080,5,North,Cash,...,1,26,Male,Books,3.8,Not Returned,Neutral,16.03,nan,NaN
26,2023-01-27,1169,110,7,59.07,0.08,380.4108,3,West,Cash,...,6,67,Other,Clothing,2.8,Returned,Neutral,11.35,FREESHIP,NaN
27,2023-01-28,1552,112,6,41.11,0.19,199.7946,5,West,Online,...,1,40,Other,Books,2.6,Returned,Positive,18.18,FREESHIP,2.8
28,2023-01-29,1915,119,3,15.61,0.24,35.5908,8,South,Cash,...,4,66,Female,Clothing,1.6,Returned,Neutral,12.78,nan,4.3
29,2023-01-30,1521,111,9,95.21,0.25,642.6675,6,North,Cash,...,1,22,Other,Clothing,3.8,Not Returned,Neutral,5.14,nan,NaN
30,2023-01-31,1780,152,8,75.79,0.05,576.0040,7,West,Credit Card,...,2,20,Male,Electronics,3.3,Not Returned,Neutral,12.41,SAVE10,4.2
31,2023-02-01,1873,150,3,78.16,0.25,175.8600,9,West,Credit Card,...,6,49,Female,Food,3.8,Returned,Neutral,5.76,WELCOME5,1.3
32,2023-02-02,1834,134,9,85.84,0.16,648.9504,5,North,Credit Card,...,4,58,Other,Electronics,3.4,Not Returned,Neutral,14.59,FREESHIP,1.3
33,2023-02-03,1470,120,9,11.99,0.17,89.5653,1,West,Online,...,4,31,Male,Books,3.5,Not Returned,Neutral,NaN,SAVE10,3.1
34,2023-02-04,1607,120,5,57.02,0.26,210.9740,3,South,Cash,...,2,66,Male,Clothing,4.9,Not Returned,Negative,10.65,FREESHIP,2.2

<div class="alert alert-success">

**Solution 02:**
</div>

In [6]:
df.isna().any()
cols_have_na = df.isna().any()[lambda x: x].index.tolist()

<div class="alert alert-warning">

**3. Count Missing Values in Each Column**

**Write a Pandas program to count the number of missing values in each column of a given DataFrame.**

</div>

In [7]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1411,144,1,65.75,0.25,49.3125,8,East,Cash,...,6,32,Other,Food,4.3,Not Returned,Negative,NaN,WELCOME5,2.0
1,2023-01-02,1899,135,8,99.45,0.01,787.6440,1,North,Online,...,3,58,Male,Clothing,4.0,Not Returned,Positive,14.13,nan,3.4
2,2023-01-03,1014,136,7,11.62,0.06,76.4596,2,East,Credit Card,...,2,65,Female,Clothing,4.6,Not Returned,Neutral,NaN,SAVE10,NaN
3,2023-01-04,1840,161,5,63.27,0.06,297.3690,6,West,Online,...,2,42,Male,Food,1.5,Not Returned,Negative,19.76,SAVE10,2.3
4,2023-01-05,1440,100,6,99.06,0.27,433.8828,4,North,Cash,...,6,59,Female,Electronics,1.4,Not Returned,Neutral,18.63,nan,NaN
5,2023-01-06,1910,133,5,54.36,0.26,201.1320,7,North,Cash,...,1,42,Male,Food,1.8,Returned,Positive,11.35,nan,3.0
6,2023-01-07,1128,155,3,73.48,0.20,176.3520,3,East,Credit Card,...,6,46,Female,Books,3.9,Not Returned,Negative,15.00,SAVE10,NaN
7,2023-01-08,1934,156,1,77.59,0.20,62.0720,2,South,Online,...,4,34,Female,Books,2.8,Not Returned,Positive,5.47,FREESHIP,4.9
8,2023-01-09,1538,146,7,77.81,0.07,506.5431,6,East,Credit Card,...,6,45,Other,Books,2.7,Returned,Positive,12.88,nan,NaN
9,2023-01-10,1974,150,2,73.05,0.20,116.8800,6,West,Online,...,5,21,Female,Food,4.0,Not Returned,Negative,8.01,FREESHIP,NaN
10,2023-01-11,1941,152,4,33.49,0.23,103.1492,2,East,Credit Card,...,4,52,Other,Books,3.8,Returned,Negative,11.43,nan,4.9
11,2023-01-12,1660,123,7,10.07,0.16,59.2116,3,North,Cash,...,4,26,Other,Electronics,3.2,Not Returned,Neutral,8.35,SAVE10,4.7
12,2023-01-13,1238,184,3,11.65,0.14,30.0570,5,East,Credit Card,...,3,40,Other,Electronics,4.9,Returned,Negative,13.47,WELCOME5,NaN
13,2023-01-14,1810,188,9,61.14,0.23,423.7002,5,East,Cash,...,1,53,Female,Books,2.3,Returned,Negative,12.42,nan,3.8
14,2023-01-15,1076,123,1,64.23,0.23,49.4571,2,East,Credit Card,...,1,69,Male,Clothing,2.9,Returned,Negative,14.15,WELCOME5,2.3
15,2023-01-16,1508,135,8,79.66,0.19,516.1968,5,North,Cash,...,1,31,Male,Books,3.5,Returned,Negative,13.84,FREESHIP,1.3
16,2023-01-17,1251,111,6,52.48,0.04,302.2848,7,South,Cash,...,2,29,Other,Food,3.7,Returned,Positive,9.49,WELCOME5,1.9
17,2023-01-18,1955,145,2,71.60,0.13,124.5840,6,East,Credit Card,...,2,46,Other,Books,1.9,Returned,Neutral,5.87,WELCOME5,3.2
18,2023-01-19,1859,160,7,91.22,0.02,625.7692,9,West,Online,...,4,65,Female,Clothing,3.5,Not Returned,Negative,7.98,nan,2.3
19,2023-01-20,1150,146,7,61.13,0.26,316.6534,1,North,Online,...,4,47,Male,Electronics,4.4,Not Returned,Negative,19.14,nan,1.4
20,2023-01-21,1713,130,4,51.94,0.19,168.2856,8,South,Cash,...,6,37,Male,Books,3.5,Returned,Negative,19.18,WELCOME5,2.2
21,2023-01-22,1040,189,2,27.96,0.19,45.2952,8,North,Cash,...,4,64,Other,Books,1.9,Not Returned,Neutral,16.31,FREESHIP,NaN
22,2023-01-23,1304,191,6,49.72,0.03,289.3704,9,South,Cash,...,1,42,Male,Electronics,3.3,Returned,Negative,NaN,SAVE10,NaN
23,2023-01-24,1452,199,5,96.12,0.25,360.4500,4,West,Online,...,6,32,Female,Food,3.8,Returned,Neutral,12.09,WELCOME5,NaN
24,2023-01-25,1504,169,6,92.52,0.16,466.3008,9,South,Online,...,1,54,Female,Clothing,1.7,Returned,Neutral,15.01,WELCOME5,1.9
25,2023-01-26,1182,173,7,66.67,0.21,368.6851,8,West,Online,...,1,45,Male,Clothing,3.2,Returned,Neutral,12.62,SAVE10,2.3
26,2023-01-27,1808,186,8,97.50,0.25,585.0000,1,South,Cash,...,6,57,Other,Clothing,1.7,Returned,Negative,10.78,FREESHIP,3.4
27,2023-01-28,1029,134,2,79.95,0.15,135.9150,7,West,Cash,...,1,38,Other,Food,2.4,Not Returned,Negative,6.26,SAVE10,NaN
28,2023-01-29,1058,127,4,48.68,0.09,177.1952,9,North,Online,...,4,44,Other,Clothing,1.7,Returned,Neutral,14.65,FREESHIP,4.9
29,2023-01-30,1547,182,7,43.92,0.13,267.4728,6,East,Cash,...,1,62,Other,Clothing,3.7,Returned,Neutral,12.79,nan,4.7
30,2023-01-31,1524,162,6,69.43,0.02,408.2484,7,East,Credit Card,...,6,23,Other,Clothing,3.4,Not Returned,Positive,11.94,FREESHIP,NaN
31,2023-02-01,1036,192,2,10.22,0.23,15.7388,6,North,Cash,...,6,35,Other,Electronics,3.6,Returned,Positive,19.53,nan,1.8
32,2023-02-02,1447,146,9,98.23,0.19,716.0967,6,North,Credit Card,...,6,26,Other,Clothing,3.2,Returned,Negative,NaN,WELCOME5,3.2
33,2023-02-03,1668,158,3,63.48,0.03,184.7268,5,East,Cash,...,1,34,Other,Electronics,1.5,Not Returned,Neutral,8.42,nan,1.1
34,2023-02-04,1421,188,6,15.02,0.22,70.2936,8,East,Online,...,5,49,Other,Clothing,1.7,Returned,Neutral,16.55,WELCOME5,NaN

<div class="alert alert-success">

**Solution 03:**
</div>

In [8]:
df.isna().sum()

date                 0
customer_id          0
product_id           0
quantity             0
price                0
discount             0
revenue              0
store_id             0
region               0
payment_method       0
is_member            0
delivery_days        0
customer_age         0
gender               0
product_category     0
rating               0
return_status        0
feedback             0
shipping_cost        4
coupon_code          0
delivery_rating     12
dtype: int64

<div class="alert alert-warning">

**4. Replace Non-Valuable Missing Values**

**Write a Pandas program to find and replace the missing values in a given DataFrame which do not have any valuable information.**

</div>

In [9]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values
0,2023-01-01,1138,172,7,58.68,0.21,324.5004,3,South,Online,...,Female,Electronics,3.4,Returned,Neutral,NaN,nan,1.9,Used loyalty points,no_data
1,2023-01-02,1719,141,4,53.01,0.23,163.2708,3,South,Online,...,Other,Clothing,4.4,Not Returned,Negative,NaN,SAVE10,NaN,Preferred morning delivery,value_1
2,2023-01-03,1385,141,6,41.14,0.06,232.0296,3,North,Online,...,Other,Books,1.5,Not Returned,Negative,15.91,nan,NaN,unknown,value_2
3,2023-01-04,1911,186,9,27.15,0.28,175.9320,8,East,Online,...,Other,Books,4.0,Not Returned,Negative,9.13,SAVE10,2.0,Requested gift wrap,value_1
4,2023-01-05,1512,128,1,73.44,0.17,60.9552,7,East,Credit Card,...,Other,Electronics,4.6,Not Returned,Negative,9.00,SAVE10,NaN,no_data,unknown
5,2023-01-06,1003,135,7,66.21,0.03,449.5659,2,North,Cash,...,Male,Electronics,2.1,Returned,Negative,NaN,SAVE10,1.1,Requested gift wrap,value_5
6,2023-01-07,1034,185,6,29.07,0.16,146.5128,9,South,Credit Card,...,Other,Books,1.4,Returned,Neutral,16.81,nan,NaN,Requested gift wrap,value_5
7,2023-01-08,1114,133,2,74.67,0.17,123.9522,5,East,Cash,...,Other,Clothing,2.3,Not Returned,Neutral,NaN,WELCOME5,4.4,unknown,unknown
8,2023-01-09,1320,153,7,46.07,0.11,287.0161,7,South,Credit Card,...,Female,Electronics,1.3,Not Returned,Negative,NaN,nan,NaN,Preferred morning delivery,value_5
9,2023-01-10,1852,134,1,83.28,0.19,67.4568,3,East,Cash,...,Other,Clothing,3.4,Returned,Negative,13.43,nan,2.2,no_data,value_4
10,2023-01-11,1662,123,1,17.84,0.08,16.4128,1,East,Credit Card,...,Other,Electronics,2.1,Not Returned,Negative,13.09,nan,NaN,no_data,no_data
11,2023-01-12,1584,119,7,29.07,0.29,144.4779,5,North,Online,...,Female,Electronics,2.5,Returned,Positive,5.21,WELCOME5,2.3,unknown,value_4
12,2023-01-13,1779,128,8,79.40,0.10,571.6800,1,East,Credit Card,...,Male,Food,4.9,Returned,Neutral,NaN,SAVE10,1.6,Frequent buyer,no_data
13,2023-01-14,1233,199,8,40.05,0.16,269.1360,4,North,Cash,...,Other,Electronics,1.8,Not Returned,Neutral,NaN,SAVE10,2.5,unknown,value_5
14,2023-01-15,1728,199,1,68.67,0.17,56.9961,3,West,Cash,...,Female,Books,1.5,Returned,Neutral,7.09,nan,NaN,Requested gift wrap,value_1
15,2023-01-16,1723,114,2,72.99,0.06,137.2212,6,South,Cash,...,Female,Electronics,3.2,Not Returned,Negative,12.26,nan,1.7,unknown,no_data
16,2023-01-17,1427,153,9,65.93,0.03,575.5689,9,West,Online,...,Other,Clothing,3.9,Returned,Negative,7.68,SAVE10,1.5,no_data,value_4
17,2023-01-18,1071,186,6,22.70,0.16,114.4080,5,West,Online,...,Male,Food,2.8,Not Returned,Positive,14.57,WELCOME5,NaN,Frequent buyer,value_1
18,2023-01-19,1304,184,1,21.27,0.21,16.8033,8,West,Credit Card,...,Other,Books,1.3,Returned,Negative,12.38,nan,1.7,no_data,value_5
19,2023-01-20,1135,174,9,94.66,0.07,792.3042,4,South,Credit Card,...,Other,Clothing,2.8,Returned,Neutral,10.47,WELCOME5,4.0,Frequent buyer,no_data
20,2023-01-21,1408,161,3,80.33,0.10,216.8910,5,West,Cash,...,Female,Food,1.3,Not Returned,Positive,9.00,WELCOME5,2.8,no_data,no_data
21,2023-01-22,1339,147,4,65.85,0.10,237.0600,8,West,Credit Card,...,Female,Clothing,2.4,Returned,Positive,13.40,WELCOME5,NaN,First-time customer,value_3
22,2023-01-23,1034,102,5,28.94,0.02,141.8060,3,North,Credit Card,...,Other,Electronics,3.8,Returned,Neutral,11.74,FREESHIP,3.0,unknown,unknown
23,2023-01-24,1118,199,7,40.82,0.23,220.0198,6,North,Credit Card,...,Other,Books,1.4,Returned,Neutral,17.58,nan,NaN,unknown,no_data
24,2023-01-25,1525,198,9,47.96,0.15,366.8940,3,West,Online,...,Female,Clothing,2.1,Returned,Positive,14.54,FREESHIP,1.5,unknown,value_3
25,2023-01-26,1602,184,4,87.94,0.29,249.7496,7,North,Online,...,Male,Clothing,4.9,Returned,Negative,13.03,WELCOME5,2.0,unknown,value_5
26,2023-01-27,1270,171,2,46.12,0.11,82.0936,8,East,Online,...,Male,Clothing,1.2,Not Returned,Positive,10.32,FREESHIP,NaN,no_data,no_data
27,2023-01-28,1853,189,9,88.67,0.03,774.0891,5,West,Credit Card,...,Male,Food,2.4,Not Returned,Neutral,10.22,SAVE10,4.1,Requested gift wrap,value_3
28,2023-01-29,1283,168,3,56.03,0.03,163.0473,5,South,Cash,...,Other,Books,4.6,Returned,Positive,15.74,WELCOME5,NaN,unknown,unknown
29,2023-01-30,1395,102,6,96.33,0.30,404.5860,7,East,Online,...,Female,Books,1.4,Returned,Neutral,NaN,SAVE10,2.8,no_data,value_5
30,2023-01-31,1706,151,3,17.90,0.21,42.4230,6,North,Credit Card,...,Other,Clothing,4.9,Not Returned,Neutral,17.61,FREESHIP,NaN,unknown,value_2
31,2023-02-01,1781,106,1,19.69,0.23,15.1613,5,East,Cash,...,Female,Clothing,2.7,Not Returned,Positive,NaN,SAVE10,2.1,Preferred morning delivery,no_data
32,2023-02-02,1419,155,8,74.14,0.26,438.9088,8,North,Cash,...,Other,Clothing,3.9,Not Returned,Neutral,15.35,nan,NaN,unknown,value_1
33,2023-02-03,1831,137,9,44.40,0.27,291.7080,1,East,Credit Card,...,Female,Books,5.0,Returned,Neutral,NaN,WELCOME5,NaN,Preferred morning delivery,unknown
34,2023-02-04,1382,195,9,76.77,0.27,504.3789,7,South,Online,...,Female,Electronics,4.2,Returned,Positive,17.91,WELCOME5,4.1,no_data,no_data

<div class="alert alert-success">

**Solution 04:**
</div>

In [10]:
df.replace({
    'customer_note': {
        'no_data': np.nan,
        'unknown': np.nan
    },
    'customer_values': {
        'no_data': np.nan,
        'unknown': np.nan
    }
}, inplace=True)

display(df.isna().any())
display(df.isna().sum())

date                False
customer_id         False
product_id          False
quantity            False
price               False
discount            False
revenue             False
store_id            False
region              False
payment_method      False
is_member           False
delivery_days       False
customer_age        False
gender              False
product_category    False
rating              False
return_status       False
feedback            False
shipping_cost        True
coupon_code         False
delivery_rating      True
customer_note        True
customer_values      True
dtype: bool

date                 0
customer_id          0
product_id           0
quantity             0
price                0
discount             0
revenue              0
store_id             0
region               0
payment_method       0
is_member            0
delivery_days        0
customer_age         0
gender               0
product_category     0
rating               0
return_status        0
feedback             0
shipping_cost       10
coupon_code          0
delivery_rating     15
customer_note       21
customer_values     15
dtype: int64

<div class="alert alert-warning">

**5. Drop Rows with Any Missing Value**

**Write a Pandas program to drop the rows where at least one element is missing in a given DataFrame.**

</div>

In [11]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values
0,2023-01-01,1486,160,6,40.29,0.03,234.4878,1,South,Online,...,Other,Clothing,2.9,Returned,Positive,9.27,nan,4.3,Requested gift wrap,value_3
1,2023-01-02,1761,107,2,82.75,0.12,145.6400,7,North,Cash,...,Other,Electronics,2.5,Returned,Negative,18.36,FREESHIP,2.6,Preferred morning delivery,unknown
2,2023-01-03,1769,160,9,66.51,0.18,490.8438,6,North,Online,...,Other,Books,2.9,Returned,Neutral,14.50,FREESHIP,NaN,Frequent buyer,no_data
3,2023-01-04,1168,109,9,63.96,0.08,529.5888,4,West,Cash,...,Other,Food,2.8,Not Returned,Neutral,10.69,SAVE10,NaN,unknown,no_data
4,2023-01-05,1671,196,1,88.19,0.11,78.4891,4,North,Credit Card,...,Male,Electronics,2.9,Not Returned,Neutral,13.62,nan,1.4,unknown,no_data
5,2023-01-06,1148,172,5,39.00,0.13,169.6500,8,South,Cash,...,Male,Books,3.8,Not Returned,Negative,NaN,nan,2.6,unknown,unknown
6,2023-01-07,1676,198,1,43.55,0.16,36.5820,8,East,Credit Card,...,Female,Clothing,4.4,Not Returned,Neutral,19.77,nan,NaN,unknown,unknown
7,2023-01-08,1845,126,9,11.64,0.19,84.8556,4,West,Credit Card,...,Female,Books,4.5,Returned,Neutral,14.89,nan,NaN,unknown,no_data
8,2023-01-09,1353,153,8,41.54,0.22,259.2096,5,North,Credit Card,...,Other,Books,3.3,Returned,Negative,5.14,WELCOME5,2.7,unknown,no_data
9,2023-01-10,1031,159,4,32.31,0.06,121.4856,8,South,Cash,...,Male,Electronics,4.6,Returned,Negative,16.47,SAVE10,2.6,First-time customer,value_1
10,2023-01-11,1029,195,2,24.17,0.12,42.5392,3,North,Cash,...,Male,Electronics,2.3,Returned,Neutral,13.41,SAVE10,4.7,Frequent buyer,value_3
11,2023-01-12,1983,172,9,55.18,0.30,347.6340,2,South,Cash,...,Male,Electronics,2.9,Not Returned,Positive,10.57,nan,3.8,no_data,value_3
12,2023-01-13,1265,120,9,24.56,0.09,201.1464,4,West,Credit Card,...,Other,Food,3.4,Returned,Negative,17.82,nan,NaN,Used loyalty points,value_1
13,2023-01-14,1918,180,6,98.95,0.22,463.0860,7,West,Cash,...,Female,Electronics,4.9,Not Returned,Positive,16.41,nan,NaN,unknown,no_data
14,2023-01-15,1786,175,2,59.53,0.27,86.9138,2,West,Cash,...,Other,Food,2.7,Returned,Neutral,14.16,nan,3.5,unknown,value_2
15,2023-01-16,1062,119,7,55.99,0.30,274.3510,4,East,Online,...,Male,Books,1.8,Not Returned,Positive,10.23,FREESHIP,NaN,no_data,value_2
16,2023-01-17,1825,141,4,39.20,0.15,133.2800,4,East,Online,...,Female,Clothing,4.6,Returned,Negative,14.35,FREESHIP,NaN,unknown,value_3
17,2023-01-18,1598,161,6,56.00,0.04,322.5600,9,East,Cash,...,Female,Clothing,4.1,Returned,Negative,9.25,FREESHIP,NaN,Frequent buyer,no_data
18,2023-01-19,1801,153,2,80.28,0.26,118.8144,7,West,Online,...,Female,Books,4.3,Not Returned,Negative,NaN,WELCOME5,NaN,no_data,value_1
19,2023-01-20,1594,133,5,48.08,0.27,175.4920,2,North,Online,...,Other,Food,1.3,Not Returned,Negative,NaN,FREESHIP,1.5,Preferred morning delivery,value_3
20,2023-01-21,1442,194,1,64.82,0.25,48.6150,8,North,Online,...,Female,Electronics,4.3,Not Returned,Negative,18.41,nan,1.6,Used loyalty points,value_2
21,2023-01-22,1915,120,1,76.76,0.23,59.1052,1,North,Online,...,Male,Electronics,3.4,Not Returned,Positive,19.37,nan,NaN,unknown,unknown
22,2023-01-23,1320,187,3,80.61,0.29,171.6993,8,East,Credit Card,...,Female,Books,3.3,Not Returned,Negative,NaN,FREESHIP,2.3,Used loyalty points,value_5
23,2023-01-24,1748,156,9,14.19,0.12,112.3848,2,West,Online,...,Other,Books,4.9,Not Returned,Negative,11.89,WELCOME5,4.6,Preferred morning delivery,value_5
24,2023-01-25,1492,110,5,31.91,0.30,111.6850,2,West,Credit Card,...,Other,Food,2.4,Returned,Neutral,9.46,SAVE10,NaN,Used loyalty points,value_4
25,2023-01-26,1086,108,5,44.68,0.28,160.8480,6,North,Online,...,Other,Books,2.7,Not Returned,Neutral,11.32,SAVE10,3.9,unknown,value_1
26,2023-01-27,1364,172,4,11.43,0.27,33.3756,2,South,Online,...,Female,Electronics,1.3,Not Returned,Negative,NaN,WELCOME5,2.6,unknown,value_3
27,2023-01-28,1477,177,4,87.19,0.21,275.5204,3,East,Credit Card,...,Other,Books,4.7,Not Returned,Neutral,7.57,FREESHIP,4.8,unknown,unknown
28,2023-01-29,1891,118,9,72.39,0.01,644.9949,8,West,Cash,...,Male,Books,2.4,Returned,Positive,8.43,SAVE10,2.2,Frequent buyer,value_1
29,2023-01-30,1727,156,4,41.10,0.01,162.7560,7,West,Online,...,Other,Electronics,1.7,Not Returned,Negative,14.08,FREESHIP,3.7,Preferred morning delivery,unknown
30,2023-01-31,1497,199,9,65.71,0.22,461.2842,6,East,Online,...,Male,Food,3.6,Returned,Neutral,7.06,WELCOME5,2.6,unknown,unknown
31,2023-02-01,1319,149,6,90.16,0.02,530.1408,2,East,Credit Card,...,Male,Books,2.1,Returned,Negative,NaN,FREESHIP,4.9,Frequent buyer,value_4
32,2023-02-02,1981,133,7,72.73,0.12,448.0168,7,West,Credit Card,...,Other,Food,4.1,Not Returned,Negative,5.61,SAVE10,NaN,Preferred morning delivery,no_data
33,2023-02-03,1696,113,4,47.20,0.13,164.2560,5,West,Online,...,Male,Clothing,4.5,Not Returned,Positive,17.60,SAVE10,NaN,no_data,value_5
34,2023-02-04,1735,118,1,61.74,0.27,45.0702,4,East,Online,...,Female,Books,3.5,Not Returned,Positive,16.74,WELCOME5,4.4,no_data,value_3

<div class="alert alert-success">

**Solution 05:**
</div>

In [12]:
dropped_df = df.dropna(how='any')
display(dropped_df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values
0,2023-01-01,1486,160,6,40.29,0.03,234.4878,1,South,Online,...,Other,Clothing,2.9,Returned,Positive,9.27,nan,4.3,Requested gift wrap,value_3
1,2023-01-02,1761,107,2,82.75,0.12,145.6400,7,North,Cash,...,Other,Electronics,2.5,Returned,Negative,18.36,FREESHIP,2.6,Preferred morning delivery,unknown
4,2023-01-05,1671,196,1,88.19,0.11,78.4891,4,North,Credit Card,...,Male,Electronics,2.9,Not Returned,Neutral,13.62,nan,1.4,unknown,no_data
8,2023-01-09,1353,153,8,41.54,0.22,259.2096,5,North,Credit Card,...,Other,Books,3.3,Returned,Negative,5.14,WELCOME5,2.7,unknown,no_data
9,2023-01-10,1031,159,4,32.31,0.06,121.4856,8,South,Cash,...,Male,Electronics,4.6,Returned,Negative,16.47,SAVE10,2.6,First-time customer,value_1
10,2023-01-11,1029,195,2,24.17,0.12,42.5392,3,North,Cash,...,Male,Electronics,2.3,Returned,Neutral,13.41,SAVE10,4.7,Frequent buyer,value_3
11,2023-01-12,1983,172,9,55.18,0.30,347.6340,2,South,Cash,...,Male,Electronics,2.9,Not Returned,Positive,10.57,nan,3.8,no_data,value_3
14,2023-01-15,1786,175,2,59.53,0.27,86.9138,2,West,Cash,...,Other,Food,2.7,Returned,Neutral,14.16,nan,3.5,unknown,value_2
20,2023-01-21,1442,194,1,64.82,0.25,48.6150,8,North,Online,...,Female,Electronics,4.3,Not Returned,Negative,18.41,nan,1.6,Used loyalty points,value_2
23,2023-01-24,1748,156,9,14.19,0.12,112.3848,2,West,Online,...,Other,Books,4.9,Not Returned,Negative,11.89,WELCOME5,4.6,Preferred morning delivery,value_5
25,2023-01-26,1086,108,5,44.68,0.28,160.8480,6,North,Online,...,Other,Books,2.7,Not Returned,Neutral,11.32,SAVE10,3.9,unknown,value_1
27,2023-01-28,1477,177,4,87.19,0.21,275.5204,3,East,Credit Card,...,Other,Books,4.7,Not Returned,Neutral,7.57,FREESHIP,4.8,unknown,unknown
28,2023-01-29,1891,118,9,72.39,0.01,644.9949,8,West,Cash,...,Male,Books,2.4,Returned,Positive,8.43,SAVE10,2.2,Frequent buyer,value_1
29,2023-01-30,1727,156,4,41.10,0.01,162.7560,7,West,Online,...,Other,Electronics,1.7,Not Returned,Negative,14.08,FREESHIP,3.7,Preferred morning delivery,unknown
30,2023-01-31,1497,199,9,65.71,0.22,461.2842,6,East,Online,...,Male,Food,3.6,Returned,Neutral,7.06,WELCOME5,2.6,unknown,unknown
34,2023-02-04,1735,118,1,61.74,0.27,45.0702,4,East,Online,...,Female,Books,3.5,Not Returned,Positive,16.74,WELCOME5,4.4,no_data,value_3

<div class="alert alert-warning">

**6. Drop Columns with Any Missing Value**

**Write a Pandas program to drop the columns where at least one element is missing in a given DataFrame.**

</div>

In [13]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values
0,2023-01-01,1098,113,8,31.42,0.27,183.4928,2,North,Cash,...,Other,Books,4.2,Returned,Neutral,14.33,FREESHIP,2.5,Frequent buyer,value_1
1,2023-01-02,1335,190,2,15.64,0.29,22.2088,5,West,Cash,...,Other,Electronics,1.5,Returned,Negative,NaN,nan,3.0,unknown,unknown
2,2023-01-03,1477,173,3,71.19,0.11,190.0773,1,West,Cash,...,Other,Clothing,2.7,Returned,Positive,16.96,SAVE10,1.6,unknown,no_data
3,2023-01-04,1876,158,1,13.27,0.02,13.0046,9,West,Credit Card,...,Female,Food,1.4,Not Returned,Negative,7.45,nan,4.6,Requested gift wrap,no_data
4,2023-01-05,1724,159,7,50.83,0.04,341.5776,6,North,Online,...,Female,Books,1.6,Not Returned,Positive,14.08,FREESHIP,4.6,Frequent buyer,value_5
5,2023-01-06,1354,146,6,64.10,0.26,284.6040,7,North,Online,...,Other,Books,1.8,Not Returned,Positive,17.43,FREESHIP,NaN,no_data,value_3
6,2023-01-07,1070,126,8,19.24,0.14,132.3712,4,West,Online,...,Other,Books,4.3,Returned,Positive,12.15,FREESHIP,4.2,no_data,unknown
7,2023-01-08,1376,128,4,59.27,0.19,192.0348,5,East,Cash,...,Male,Food,2.4,Not Returned,Neutral,NaN,SAVE10,3.5,no_data,no_data
8,2023-01-09,1216,163,4,61.17,0.30,171.2760,4,West,Online,...,Male,Books,1.4,Returned,Positive,13.54,nan,2.7,Used loyalty points,value_5
9,2023-01-10,1836,131,4,86.72,0.23,267.0976,2,South,Cash,...,Female,Food,1.8,Not Returned,Positive,16.14,SAVE10,4.5,Frequent buyer,no_data
10,2023-01-11,1179,178,7,49.25,0.24,262.0100,7,South,Credit Card,...,Male,Food,2.5,Returned,Negative,NaN,SAVE10,2.7,Preferred morning delivery,value_2
11,2023-01-12,1288,159,2,21.05,0.03,40.8370,3,East,Credit Card,...,Other,Books,5.0,Not Returned,Neutral,NaN,SAVE10,NaN,no_data,value_4
12,2023-01-13,1566,136,4,19.14,0.19,62.0136,1,South,Credit Card,...,Other,Clothing,2.0,Not Returned,Negative,14.87,WELCOME5,4.1,First-time customer,value_4
13,2023-01-14,1744,126,9,34.26,0.23,237.4218,7,West,Cash,...,Male,Electronics,1.3,Not Returned,Negative,12.55,nan,3.9,Requested gift wrap,unknown
14,2023-01-15,1147,125,3,33.30,0.06,93.9060,1,South,Credit Card,...,Male,Electronics,4.1,Not Returned,Negative,11.19,nan,2.1,unknown,unknown
15,2023-01-16,1332,129,7,12.16,0.27,62.1376,1,South,Credit Card,...,Male,Food,4.2,Not Returned,Positive,14.85,nan,NaN,unknown,value_4
16,2023-01-17,1847,175,9,26.92,0.18,198.6696,9,West,Online,...,Other,Food,1.0,Returned,Neutral,16.09,WELCOME5,NaN,Used loyalty points,value_3
17,2023-01-18,1557,177,4,69.32,0.15,235.6880,9,East,Online,...,Female,Clothing,1.2,Not Returned,Negative,16.66,WELCOME5,1.7,First-time customer,value_1
18,2023-01-19,1269,118,3,14.34,0.14,36.9972,9,East,Credit Card,...,Male,Clothing,1.7,Returned,Neutral,15.96,WELCOME5,5.0,no_data,no_data
19,2023-01-20,1474,125,7,37.80,0.19,214.3260,5,East,Credit Card,...,Female,Clothing,2.9,Not Returned,Negative,18.52,nan,4.2,First-time customer,no_data
20,2023-01-21,1770,136,7,26.45,0.05,175.8925,6,North,Cash,...,Male,Food,4.8,Returned,Neutral,18.48,SAVE10,NaN,Used loyalty points,value_3
21,2023-01-22,1456,192,2,43.73,0.07,81.3378,4,North,Online,...,Female,Books,5.0,Not Returned,Negative,19.87,WELCOME5,3.2,unknown,no_data
22,2023-01-23,1736,110,6,21.57,0.10,116.4780,9,South,Credit Card,...,Other,Clothing,3.6,Returned,Negative,12.82,SAVE10,2.7,Requested gift wrap,value_5
23,2023-01-24,1792,121,8,17.05,0.08,125.4880,6,East,Cash,...,Other,Electronics,1.5,Not Returned,Negative,14.29,FREESHIP,1.5,Requested gift wrap,value_4
24,2023-01-25,1229,181,8,91.00,0.20,582.4000,7,East,Credit Card,...,Other,Electronics,1.6,Not Returned,Negative,11.65,nan,2.9,Preferred morning delivery,no_data
25,2023-01-26,1876,165,2,33.91,0.04,65.1072,8,North,Cash,...,Male,Food,3.6,Not Returned,Positive,19.80,nan,NaN,no_data,value_5
26,2023-01-27,1217,108,8,91.07,0.13,633.8472,1,South,Cash,...,Female,Electronics,2.1,Not Returned,Positive,19.15,nan,2.7,no_data,value_3
27,2023-01-28,1446,179,3,33.82,0.10,91.3140,5,North,Cash,...,Female,Electronics,4.7,Not Returned,Negative,11.35,nan,1.1,Used loyalty points,unknown
28,2023-01-29,1582,127,2,34.85,0.28,50.1840,2,South,Cash,...,Female,Books,3.6,Returned,Positive,8.46,nan,3.4,no_data,value_3
29,2023-01-30,1167,160,6,77.17,0.29,328.7442,8,South,Credit Card,...,Other,Books,1.4,Not Returned,Neutral,19.16,nan,4.3,First-time customer,value_2
30,2023-01-31,1726,185,1,86.57,0.07,80.5101,4,South,Online,...,Female,Electronics,3.0,Not Returned,Neutral,10.25,WELCOME5,4.3,unknown,unknown
31,2023-02-01,1926,124,1,21.23,0.30,14.8610,3,South,Online,...,Male,Clothing,2.6,Not Returned,Positive,18.30,nan,2.8,Frequent buyer,no_data
32,2023-02-02,1231,198,7,37.51,0.23,202.1789,3,North,Cash,...,Female,Food,1.5,Not Returned,Negative,NaN,WELCOME5,3.4,Requested gift wrap,no_data
33,2023-02-03,1395,122,9,70.07,0.11,561.2607,5,North,Cash,...,Female,Food,3.2,Not Returned,Neutral,10.50,nan,2.6,no_data,value_1
34,2023-02-04,1301,157,3,55.09,0.16,138.8268,8,North,Credit Card,...,Male,Books,4.0,Not Returned,Positive,NaN,WELCOME5,4.1,no_data,unknown

<div class="alert alert-success">

**Solution 06:**
</div>

In [14]:
# Drop columns with any missing value
dropped_df = df.dropna(axis=1, how='any')
display(dropped_df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,coupon_code,customer_note,customer_values
0,2023-01-01,1098,113,8,31.42,0.27,183.4928,2,North,Cash,...,1,42,Other,Books,4.2,Returned,Neutral,FREESHIP,Frequent buyer,value_1
1,2023-01-02,1335,190,2,15.64,0.29,22.2088,5,West,Cash,...,4,44,Other,Electronics,1.5,Returned,Negative,nan,unknown,unknown
2,2023-01-03,1477,173,3,71.19,0.11,190.0773,1,West,Cash,...,3,38,Other,Clothing,2.7,Returned,Positive,SAVE10,unknown,no_data
3,2023-01-04,1876,158,1,13.27,0.02,13.0046,9,West,Credit Card,...,4,36,Female,Food,1.4,Not Returned,Negative,nan,Requested gift wrap,no_data
4,2023-01-05,1724,159,7,50.83,0.04,341.5776,6,North,Online,...,1,60,Female,Books,1.6,Not Returned,Positive,FREESHIP,Frequent buyer,value_5
5,2023-01-06,1354,146,6,64.10,0.26,284.6040,7,North,Online,...,1,65,Other,Books,1.8,Not Returned,Positive,FREESHIP,no_data,value_3
6,2023-01-07,1070,126,8,19.24,0.14,132.3712,4,West,Online,...,6,31,Other,Books,4.3,Returned,Positive,FREESHIP,no_data,unknown
7,2023-01-08,1376,128,4,59.27,0.19,192.0348,5,East,Cash,...,5,26,Male,Food,2.4,Not Returned,Neutral,SAVE10,no_data,no_data
8,2023-01-09,1216,163,4,61.17,0.30,171.2760,4,West,Online,...,5,57,Male,Books,1.4,Returned,Positive,nan,Used loyalty points,value_5
9,2023-01-10,1836,131,4,86.72,0.23,267.0976,2,South,Cash,...,2,69,Female,Food,1.8,Not Returned,Positive,SAVE10,Frequent buyer,no_data
10,2023-01-11,1179,178,7,49.25,0.24,262.0100,7,South,Credit Card,...,6,28,Male,Food,2.5,Returned,Negative,SAVE10,Preferred morning delivery,value_2
11,2023-01-12,1288,159,2,21.05,0.03,40.8370,3,East,Credit Card,...,3,39,Other,Books,5.0,Not Returned,Neutral,SAVE10,no_data,value_4
12,2023-01-13,1566,136,4,19.14,0.19,62.0136,1,South,Credit Card,...,2,34,Other,Clothing,2.0,Not Returned,Negative,WELCOME5,First-time customer,value_4
13,2023-01-14,1744,126,9,34.26,0.23,237.4218,7,West,Cash,...,1,21,Male,Electronics,1.3,Not Returned,Negative,nan,Requested gift wrap,unknown
14,2023-01-15,1147,125,3,33.30,0.06,93.9060,1,South,Credit Card,...,6,30,Male,Electronics,4.1,Not Returned,Negative,nan,unknown,unknown
15,2023-01-16,1332,129,7,12.16,0.27,62.1376,1,South,Credit Card,...,4,46,Male,Food,4.2,Not Returned,Positive,nan,unknown,value_4
16,2023-01-17,1847,175,9,26.92,0.18,198.6696,9,West,Online,...,4,37,Other,Food,1.0,Returned,Neutral,WELCOME5,Used loyalty points,value_3
17,2023-01-18,1557,177,4,69.32,0.15,235.6880,9,East,Online,...,6,56,Female,Clothing,1.2,Not Returned,Negative,WELCOME5,First-time customer,value_1
18,2023-01-19,1269,118,3,14.34,0.14,36.9972,9,East,Credit Card,...,1,22,Male,Clothing,1.7,Returned,Neutral,WELCOME5,no_data,no_data
19,2023-01-20,1474,125,7,37.80,0.19,214.3260,5,East,Credit Card,...,4,34,Female,Clothing,2.9,Not Returned,Negative,nan,First-time customer,no_data
20,2023-01-21,1770,136,7,26.45,0.05,175.8925,6,North,Cash,...,5,21,Male,Food,4.8,Returned,Neutral,SAVE10,Used loyalty points,value_3
21,2023-01-22,1456,192,2,43.73,0.07,81.3378,4,North,Online,...,1,47,Female,Books,5.0,Not Returned,Negative,WELCOME5,unknown,no_data
22,2023-01-23,1736,110,6,21.57,0.10,116.4780,9,South,Credit Card,...,3,43,Other,Clothing,3.6,Returned,Negative,SAVE10,Requested gift wrap,value_5
23,2023-01-24,1792,121,8,17.05,0.08,125.4880,6,East,Cash,...,3,55,Other,Electronics,1.5,Not Returned,Negative,FREESHIP,Requested gift wrap,value_4
24,2023-01-25,1229,181,8,91.00,0.20,582.4000,7,East,Credit Card,...,4,54,Other,Electronics,1.6,Not Returned,Negative,nan,Preferred morning delivery,no_data
25,2023-01-26,1876,165,2,33.91,0.04,65.1072,8,North,Cash,...,5,43,Male,Food,3.6,Not Returned,Positive,nan,no_data,value_5
26,2023-01-27,1217,108,8,91.07,0.13,633.8472,1,South,Cash,...,3,60,Female,Electronics,2.1,Not Returned,Positive,nan,no_data,value_3
27,2023-01-28,1446,179,3,33.82,0.10,91.3140,5,North,Cash,...,6,19,Female,Electronics,4.7,Not Returned,Negative,nan,Used loyalty points,unknown
28,2023-01-29,1582,127,2,34.85,0.28,50.1840,2,South,Cash,...,3,54,Female,Books,3.6,Returned,Positive,nan,no_data,value_3
29,2023-01-30,1167,160,6,77.17,0.29,328.7442,8,South,Credit Card,...,1,40,Other,Books,1.4,Not Returned,Neutral,nan,First-time customer,value_2
30,2023-01-31,1726,185,1,86.57,0.07,80.5101,4,South,Online,...,3,56,Female,Electronics,3.0,Not Returned,Neutral,WELCOME5,unknown,unknown
31,2023-02-01,1926,124,1,21.23,0.30,14.8610,3,South,Online,...,3,40,Male,Clothing,2.6,Not Returned,Positive,nan,Frequent buyer,no_data
32,2023-02-02,1231,198,7,37.51,0.23,202.1789,3,North,Cash,...,5,20,Female,Food,1.5,Not Returned,Negative,WELCOME5,Requested gift wrap,no_data
33,2023-02-03,1395,122,9,70.07,0.11,561.2607,5,North,Cash,...,3,48,Female,Food,3.2,Not Returned,Neutral,nan,no_data,value_1
34,2023-02-04,1301,157,3,55.09,0.16,138.8268,8,North,Credit Card,...,5,45,Male,Books,4.0,Not Returned,Positive,WELCOME5,no_data,unknown

<div class="alert alert-warning">

**7. Drop Rows with All Missing Values**

**Write a Pandas program to drop the rows where all elements are missing in a given DataFrame.**

</div>

In [15]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_11311/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1669.0,192.0,2.0,74.67,0.19,120.9654,5.0,West,Cash,...,Clothing,3.6,Not Returned,Negative,NaN,nan,4.9,Requested gift wrap,unknown,NaN
1,2023-01-02,1531.0,112.0,3.0,37.56,0.23,86.7636,5.0,South,Cash,...,Books,3.2,Returned,Positive,11.97,SAVE10,2.7,no_data,unknown,NaN
2,2023-01-03,1525.0,184.0,7.0,98.69,0.09,628.6553,2.0,South,Cash,...,Books,1.1,Not Returned,Neutral,NaN,WELCOME5,NaN,Preferred morning delivery,value_2,NaN
3,2023-01-04,1265.0,129.0,2.0,25.10,0.29,35.6420,6.0,West,Credit Card,...,Electronics,4.1,Returned,Neutral,11.72,nan,2.2,Used loyalty points,value_3,NaN
4,2023-01-05,1399.0,103.0,9.0,44.93,0.08,372.0204,2.0,East,Cash,...,Clothing,3.7,Not Returned,Negative,10.34,WELCOME5,NaN,Requested gift wrap,no_data,NaN
5,2023-01-06,1898.0,176.0,2.0,17.81,0.06,33.4828,6.0,South,Online,...,Food,2.9,Returned,Positive,9.28,nan,3.4,First-time customer,value_2,NaN
6,2023-01-07,1003.0,199.0,6.0,92.77,0.00,556.6200,5.0,North,Credit Card,...,Electronics,4.9,Not Returned,Negative,NaN,SAVE10,NaN,Requested gift wrap,no_data,NaN
7,2023-01-08,1665.0,103.0,3.0,31.09,0.23,71.8179,2.0,West,Cash,...,Electronics,3.2,Not Returned,Positive,19.30,SAVE10,1.8,Requested gift wrap,no_data,NaN
8,2023-01-09,1767.0,149.0,4.0,83.43,0.11,297.0108,2.0,South,Credit Card,...,Electronics,3.2,Returned,Positive,11.50,SAVE10,NaN,First-time customer,no_data,NaN
9,2023-01-10,1472.0,116.0,8.0,60.10,0.06,451.9520,8.0,North,Online,...,Clothing,3.8,Not Returned,Neutral,18.71,WELCOME5,NaN,no_data,value_2,NaN
10,2023-01-11,1099.0,120.0,8.0,87.58,0.11,623.5696,7.0,South,Credit Card,...,Electronics,3.7,Not Returned,Neutral,15.67,WELCOME5,2.3,unknown,no_data,NaN
11,2023-01-12,1303.0,103.0,3.0,90.33,0.05,257.4405,4.0,West,Credit Card,...,Food,1.5,Not Returned,Neutral,7.59,nan,NaN,Used loyalty points,unknown,NaN
12,2023-01-13,1774.0,105.0,2.0,43.19,0.08,79.4696,5.0,South,Credit Card,...,Electronics,2.6,Not Returned,Neutral,NaN,nan,1.9,unknown,unknown,NaN
13,2023-01-14,1142.0,140.0,4.0,72.21,0.22,225.2952,6.0,West,Cash,...,Books,1.5,Returned,Negative,15.79,nan,3.1,unknown,value_1,NaN
14,2023-01-15,1309.0,113.0,2.0,11.80,0.26,17.4640,3.0,East,Online,...,Clothing,1.4,Returned,Positive,NaN,SAVE10,NaN,Requested gift wrap,value_4,NaN
15,2023-01-16,1501.0,191.0,6.0,66.26,0.15,337.9260,2.0,West,Cash,...,Clothing,2.6,Returned,Neutral,17.07,FREESHIP,4.3,Used loyalty points,unknown,NaN
16,2023-01-17,1138.0,133.0,8.0,48.91,0.09,356.0648,5.0,West,Online,...,Food,3.4,Not Returned,Positive,19.08,SAVE10,NaN,unknown,value_2,NaN
17,2023-01-18,1860.0,196.0,9.0,69.89,0.18,515.7882,8.0,South,Cash,...,Food,2.3,Not Returned,Positive,NaN,nan,2.9,no_data,value_3,NaN
18,2023-01-19,1522.0,182.0,7.0,17.41,0.08,112.1204,8.0,East,Credit Card,...,Electronics,1.5,Returned,Neutral,12.66,WELCOME5,NaN,unknown,value_1,NaN
19,2023-01-20,1951.0,139.0,5.0,11.83,0.08,54.4180,6.0,East,Cash,...,Books,4.7,Not Returned,Neutral,6.58,nan,1.6,Used loyalty points,value_5,NaN
20,2023-01-21,1666.0,168.0,2.0,32.86,0.06,61.7768,4.0,East,Cash,...,Electronics,5.0,Not Returned,Neutral,10.10,SAVE10,NaN,Frequent buyer,value_4,NaN
21,2023-01-22,1400.0,144.0,7.0,85.94,0.26,445.1692,8.0,East,Credit Card,...,Food,3.5,Not Returned,Positive,NaN,nan,3.9,no_data,value_3,NaN
22,2023-01-23,1370.0,156.0,9.0,91.14,0.01,812.0574,9.0,South,Cash,...,Books,1.3,Not Returned,Positive,14.67,FREESHIP,2.5,Preferred morning delivery,value_5,NaN
23,2023-01-24,1777.0,177.0,1.0,26.83,0.22,20.9274,7.0,West,Online,...,Electronics,1.2,Not Returned,Neutral,NaN,WELCOME5,2.7,Preferred morning delivery,no_data,NaN
24,2023-01-25,1127.0,188.0,4.0,58.71,0.20,187.8720,9.0,West,Cash,...,Clothing,1.2,Returned,Neutral,16.96,WELCOME5,2.5,unknown,no_data,NaN
25,2023-01-26,1265.0,125.0,8.0,85.83,0.07,638.5752,7.0,South,Cash,...,Food,2.7,Returned,Neutral,18.70,FREESHIP,4.3,Frequent buyer,unknown,NaN
26,2023-01-27,1369.0,190.0,2.0,83.70,0.16,140.6160,2.0,North,Online,...,Food,2.9,Returned,Positive,NaN,FREESHIP,NaN,unknown,unknown,NaN
27,2023-01-28,1995.0,191.0,7.0,51.11,0.08,329.1484,6.0,North,Credit Card,...,Clothing,4.8,Returned,Positive,NaN,WELCOME5,3.6,Requested gift wrap,value_4,NaN
28,2023-01-29,1572.0,103.0,2.0,94.27,0.24,143.2904,4.0,West,Online,...,Electronics,3.0,Not Returned,Positive,NaN,nan,1.5,no_data,value_1,NaN
29,2023-01-30,1732.0,107.0,6.0,17.85,0.26,79.2540,1.0,North,Online,...,Books,2.8,Returned,Negative,17.41,WELCOME5,NaN,Preferred morning delivery,value_3,NaN
30,2023-01-31,1082.0,133.0,4.0,51.07,0.23,157.2956,1.0,South,Cash,...,Electronics,4.2,Not Returned,Negative,18.86,nan,NaN,Frequent buyer,value_4,NaN
31,2023-02-01,1651.0,130.0,4.0,70.77,0.02,277.4184,4.0,West,Credit Card,...,Food,2.3,Returned,Positive,NaN,FREESHIP,1.3,First-time customer,value_2,NaN
32,2023-02-02,1345.0,138.0,6.0,82.66,0.13,431.4852,3.0,North,Credit Card,...,Books,3.9,Returned,Positive,NaN,nan,2.7,Preferred morning delivery,unknown,NaN
33,2023-02-03,1556.0,144.0,1.0,70.80,0.29,50.2680,9.0,North,Online,...,Books,2.4,Not Returned,Neutral,NaN,nan,2.0,Used loyalty points,value_1,NaN
34,2023-02-04,1670.0,182.0,1.0,41.65,0.11,37.0685,3.0,West,Online,...,Food,1.7,Not Returned,Negative,14.46,SAVE10,NaN,Preferred morning delivery,unknown,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 07:**
</div>

In [16]:
# Write a Pandas program to drop the rows where all elements are missing in a given DataFrame
df_dropped = df.dropna(how='all')

# Display the DataFrame after dropping rows
display(df_dropped)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1669.0,192.0,2.0,74.67,0.19,120.9654,5.0,West,Cash,...,Clothing,3.6,Not Returned,Negative,NaN,nan,4.9,Requested gift wrap,unknown,NaN
1,2023-01-02,1531.0,112.0,3.0,37.56,0.23,86.7636,5.0,South,Cash,...,Books,3.2,Returned,Positive,11.97,SAVE10,2.7,no_data,unknown,NaN
2,2023-01-03,1525.0,184.0,7.0,98.69,0.09,628.6553,2.0,South,Cash,...,Books,1.1,Not Returned,Neutral,NaN,WELCOME5,NaN,Preferred morning delivery,value_2,NaN
3,2023-01-04,1265.0,129.0,2.0,25.10,0.29,35.6420,6.0,West,Credit Card,...,Electronics,4.1,Returned,Neutral,11.72,nan,2.2,Used loyalty points,value_3,NaN
4,2023-01-05,1399.0,103.0,9.0,44.93,0.08,372.0204,2.0,East,Cash,...,Clothing,3.7,Not Returned,Negative,10.34,WELCOME5,NaN,Requested gift wrap,no_data,NaN
5,2023-01-06,1898.0,176.0,2.0,17.81,0.06,33.4828,6.0,South,Online,...,Food,2.9,Returned,Positive,9.28,nan,3.4,First-time customer,value_2,NaN
6,2023-01-07,1003.0,199.0,6.0,92.77,0.00,556.6200,5.0,North,Credit Card,...,Electronics,4.9,Not Returned,Negative,NaN,SAVE10,NaN,Requested gift wrap,no_data,NaN
7,2023-01-08,1665.0,103.0,3.0,31.09,0.23,71.8179,2.0,West,Cash,...,Electronics,3.2,Not Returned,Positive,19.30,SAVE10,1.8,Requested gift wrap,no_data,NaN
8,2023-01-09,1767.0,149.0,4.0,83.43,0.11,297.0108,2.0,South,Credit Card,...,Electronics,3.2,Returned,Positive,11.50,SAVE10,NaN,First-time customer,no_data,NaN
9,2023-01-10,1472.0,116.0,8.0,60.10,0.06,451.9520,8.0,North,Online,...,Clothing,3.8,Not Returned,Neutral,18.71,WELCOME5,NaN,no_data,value_2,NaN
10,2023-01-11,1099.0,120.0,8.0,87.58,0.11,623.5696,7.0,South,Credit Card,...,Electronics,3.7,Not Returned,Neutral,15.67,WELCOME5,2.3,unknown,no_data,NaN
11,2023-01-12,1303.0,103.0,3.0,90.33,0.05,257.4405,4.0,West,Credit Card,...,Food,1.5,Not Returned,Neutral,7.59,nan,NaN,Used loyalty points,unknown,NaN
12,2023-01-13,1774.0,105.0,2.0,43.19,0.08,79.4696,5.0,South,Credit Card,...,Electronics,2.6,Not Returned,Neutral,NaN,nan,1.9,unknown,unknown,NaN
13,2023-01-14,1142.0,140.0,4.0,72.21,0.22,225.2952,6.0,West,Cash,...,Books,1.5,Returned,Negative,15.79,nan,3.1,unknown,value_1,NaN
14,2023-01-15,1309.0,113.0,2.0,11.80,0.26,17.4640,3.0,East,Online,...,Clothing,1.4,Returned,Positive,NaN,SAVE10,NaN,Requested gift wrap,value_4,NaN
15,2023-01-16,1501.0,191.0,6.0,66.26,0.15,337.9260,2.0,West,Cash,...,Clothing,2.6,Returned,Neutral,17.07,FREESHIP,4.3,Used loyalty points,unknown,NaN
16,2023-01-17,1138.0,133.0,8.0,48.91,0.09,356.0648,5.0,West,Online,...,Food,3.4,Not Returned,Positive,19.08,SAVE10,NaN,unknown,value_2,NaN
17,2023-01-18,1860.0,196.0,9.0,69.89,0.18,515.7882,8.0,South,Cash,...,Food,2.3,Not Returned,Positive,NaN,nan,2.9,no_data,value_3,NaN
18,2023-01-19,1522.0,182.0,7.0,17.41,0.08,112.1204,8.0,East,Credit Card,...,Electronics,1.5,Returned,Neutral,12.66,WELCOME5,NaN,unknown,value_1,NaN
19,2023-01-20,1951.0,139.0,5.0,11.83,0.08,54.4180,6.0,East,Cash,...,Books,4.7,Not Returned,Neutral,6.58,nan,1.6,Used loyalty points,value_5,NaN
20,2023-01-21,1666.0,168.0,2.0,32.86,0.06,61.7768,4.0,East,Cash,...,Electronics,5.0,Not Returned,Neutral,10.10,SAVE10,NaN,Frequent buyer,value_4,NaN
21,2023-01-22,1400.0,144.0,7.0,85.94,0.26,445.1692,8.0,East,Credit Card,...,Food,3.5,Not Returned,Positive,NaN,nan,3.9,no_data,value_3,NaN
22,2023-01-23,1370.0,156.0,9.0,91.14,0.01,812.0574,9.0,South,Cash,...,Books,1.3,Not Returned,Positive,14.67,FREESHIP,2.5,Preferred morning delivery,value_5,NaN
23,2023-01-24,1777.0,177.0,1.0,26.83,0.22,20.9274,7.0,West,Online,...,Electronics,1.2,Not Returned,Neutral,NaN,WELCOME5,2.7,Preferred morning delivery,no_data,NaN
24,2023-01-25,1127.0,188.0,4.0,58.71,0.20,187.8720,9.0,West,Cash,...,Clothing,1.2,Returned,Neutral,16.96,WELCOME5,2.5,unknown,no_data,NaN
25,2023-01-26,1265.0,125.0,8.0,85.83,0.07,638.5752,7.0,South,Cash,...,Food,2.7,Returned,Neutral,18.70,FREESHIP,4.3,Frequent buyer,unknown,NaN
26,2023-01-27,1369.0,190.0,2.0,83.70,0.16,140.6160,2.0,North,Online,...,Food,2.9,Returned,Positive,NaN,FREESHIP,NaN,unknown,unknown,NaN
27,2023-01-28,1995.0,191.0,7.0,51.11,0.08,329.1484,6.0,North,Credit Card,...,Clothing,4.8,Returned,Positive,NaN,WELCOME5,3.6,Requested gift wrap,value_4,NaN
28,2023-01-29,1572.0,103.0,2.0,94.27,0.24,143.2904,4.0,West,Online,...,Electronics,3.0,Not Returned,Positive,NaN,nan,1.5,no_data,value_1,NaN
29,2023-01-30,1732.0,107.0,6.0,17.85,0.26,79.2540,1.0,North,Online,...,Books,2.8,Returned,Negative,17.41,WELCOME5,NaN,Preferred morning delivery,value_3,NaN
30,2023-01-31,1082.0,133.0,4.0,51.07,0.23,157.2956,1.0,South,Cash,...,Electronics,4.2,Not Returned,Negative,18.86,nan,NaN,Frequent buyer,value_4,NaN
31,2023-02-01,1651.0,130.0,4.0,70.77,0.02,277.4184,4.0,West,Credit Card,...,Food,2.3,Returned,Positive,NaN,FREESHIP,1.3,First-time customer,value_2,NaN
32,2023-02-02,1345.0,138.0,6.0,82.66,0.13,431.4852,3.0,North,Credit Card,...,Books,3.9,Returned,Positive,NaN,nan,2.7,Preferred morning delivery,unknown,NaN
33,2023-02-03,1556.0,144.0,1.0,70.80,0.29,50.2680,9.0,North,Online,...,Books,2.4,Not Returned,Neutral,NaN,nan,2.0,Used loyalty points,value_1,NaN
34,2023-02-04,1670.0,182.0,1.0,41.65,0.11,37.0685,3.0,West,Online,...,Food,1.7,Not Returned,Negative,14.46,SAVE10,NaN,Preferred morning delivery,unknown,NaN

<div class="alert alert-warning">

**8. Keep Rows with at Least 2 NaN Values**

**Write a Pandas program to keep the rows with at least 2 NaN values in a given DataFrame.**

</div>

In [17]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_11311/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1213.0,159.0,4.0,48.26,0.16,162.1536,1.0,East,Online,...,Books,2.8,Returned,Positive,8.71,nan,2.8,unknown,unknown,NaN
1,2023-01-02,1826.0,108.0,8.0,43.30,0.25,259.8000,2.0,East,Online,...,Books,2.9,Returned,Neutral,6.98,nan,3.9,Frequent buyer,unknown,NaN
2,2023-01-03,1135.0,178.0,8.0,68.33,0.15,464.6440,9.0,West,Credit Card,...,Clothing,1.7,Not Returned,Neutral,8.91,WELCOME5,3.5,unknown,unknown,NaN
3,2023-01-04,1684.0,158.0,7.0,87.89,0.30,430.6610,6.0,North,Cash,...,Clothing,2.1,Not Returned,Neutral,12.49,nan,NaN,unknown,unknown,NaN
4,2023-01-05,1284.0,165.0,9.0,45.87,0.30,288.9810,1.0,North,Online,...,Electronics,2.2,Returned,Negative,13.41,nan,3.8,no_data,value_5,NaN
5,2023-01-06,1592.0,136.0,8.0,87.55,0.25,525.3000,8.0,South,Online,...,Electronics,2.5,Returned,Neutral,NaN,WELCOME5,4.2,unknown,unknown,NaN
6,2023-01-07,1988.0,187.0,8.0,56.48,0.26,334.3616,8.0,East,Credit Card,...,Books,2.7,Returned,Positive,11.30,WELCOME5,2.3,Requested gift wrap,no_data,NaN
7,2023-01-08,1541.0,162.0,5.0,24.94,0.14,107.2420,4.0,East,Cash,...,Books,4.1,Not Returned,Neutral,18.44,FREESHIP,1.7,unknown,no_data,NaN
8,2023-01-09,1284.0,129.0,9.0,37.58,0.30,236.7540,9.0,West,Credit Card,...,Electronics,1.9,Returned,Positive,10.71,WELCOME5,NaN,Requested gift wrap,value_2,NaN
9,2023-01-10,1830.0,144.0,5.0,84.72,0.28,304.9920,3.0,East,Credit Card,...,Books,3.3,Not Returned,Negative,8.95,FREESHIP,1.7,no_data,unknown,NaN
10,2023-01-11,1599.0,119.0,1.0,32.24,0.10,29.0160,8.0,East,Credit Card,...,Electronics,4.7,Returned,Negative,6.91,nan,3.7,Preferred morning delivery,unknown,NaN
11,2023-01-12,1049.0,187.0,8.0,56.48,0.20,361.4720,9.0,North,Online,...,Books,1.6,Not Returned,Neutral,10.63,nan,5.0,Used loyalty points,value_1,NaN
12,2023-01-13,1661.0,177.0,5.0,69.53,0.13,302.4555,2.0,South,Online,...,Food,1.9,Returned,Neutral,11.87,nan,NaN,no_data,value_2,NaN
13,2023-01-14,1807.0,185.0,2.0,73.43,0.10,132.1740,2.0,North,Online,...,Food,1.8,Returned,Negative,NaN,SAVE10,4.9,no_data,value_3,NaN
14,2023-01-15,1151.0,108.0,2.0,44.70,0.09,81.3540,4.0,North,Credit Card,...,Food,3.7,Not Returned,Negative,19.43,nan,NaN,Used loyalty points,value_1,NaN
15,2023-01-16,1033.0,115.0,5.0,88.76,0.09,403.8580,6.0,East,Online,...,Books,1.3,Not Returned,Negative,17.69,SAVE10,NaN,unknown,value_3,NaN
16,2023-01-17,1599.0,122.0,4.0,45.98,0.12,161.8496,2.0,West,Cash,...,Books,3.9,Not Returned,Negative,NaN,WELCOME5,1.1,Frequent buyer,unknown,NaN
17,2023-01-18,1584.0,107.0,2.0,48.54,0.12,85.4304,3.0,West,Online,...,Electronics,1.5,Returned,Negative,NaN,WELCOME5,3.3,unknown,unknown,NaN
18,2023-01-19,1951.0,166.0,5.0,47.79,0.17,198.3285,2.0,East,Online,...,Food,3.3,Not Returned,Positive,11.90,nan,1.3,no_data,no_data,NaN
19,2023-01-20,1492.0,110.0,8.0,17.60,0.23,108.4160,7.0,East,Online,...,Electronics,1.4,Returned,Neutral,16.63,SAVE10,3.7,no_data,value_2,NaN
20,2023-01-21,1338.0,113.0,6.0,94.47,0.06,532.8108,5.0,East,Online,...,Electronics,4.1,Not Returned,Positive,11.98,nan,3.4,no_data,unknown,NaN
21,2023-01-22,1989.0,144.0,6.0,94.18,0.01,559.4292,2.0,West,Online,...,Clothing,1.2,Returned,Positive,6.48,nan,4.7,unknown,value_5,NaN
22,2023-01-23,1556.0,139.0,8.0,71.26,0.06,535.8752,5.0,South,Credit Card,...,Food,4.4,Not Returned,Neutral,NaN,nan,4.6,no_data,no_data,NaN
23,2023-01-24,1705.0,125.0,8.0,72.59,0.23,447.1544,2.0,South,Cash,...,Clothing,4.9,Returned,Negative,13.07,nan,4.3,Used loyalty points,value_5,NaN
24,2023-01-25,1038.0,163.0,1.0,69.48,0.17,57.6684,6.0,North,Cash,...,Food,4.9,Not Returned,Positive,15.55,FREESHIP,NaN,unknown,value_2,NaN
25,2023-01-26,1446.0,120.0,4.0,51.92,0.26,153.6832,1.0,South,Online,...,Food,1.9,Not Returned,Negative,9.48,WELCOME5,2.2,First-time customer,no_data,NaN
26,2023-01-27,1508.0,121.0,2.0,25.86,0.28,37.2384,1.0,East,Credit Card,...,Electronics,4.2,Returned,Negative,18.29,WELCOME5,NaN,Preferred morning delivery,value_5,NaN
27,2023-01-28,1655.0,191.0,5.0,37.24,0.29,132.2020,4.0,East,Cash,...,Books,1.7,Returned,Positive,15.07,nan,2.8,Preferred morning delivery,value_1,NaN
28,2023-01-29,1384.0,137.0,8.0,13.46,0.20,86.1440,8.0,North,Credit Card,...,Clothing,2.4,Returned,Neutral,13.24,SAVE10,3.2,Used loyalty points,value_1,NaN
29,2023-01-30,1090.0,149.0,2.0,25.36,0.11,45.1408,6.0,East,Online,...,Electronics,2.9,Not Returned,Negative,NaN,SAVE10,NaN,Preferred morning delivery,value_5,NaN
30,2023-01-31,1355.0,162.0,8.0,70.61,0.19,457.5528,4.0,South,Credit Card,...,Clothing,3.6,Not Returned,Neutral,15.87,SAVE10,3.2,no_data,no_data,NaN
31,2023-02-01,1118.0,174.0,9.0,40.29,0.18,297.3402,4.0,North,Online,...,Clothing,3.7,Not Returned,Neutral,NaN,SAVE10,NaN,no_data,unknown,NaN
32,2023-02-02,1950.0,165.0,8.0,28.00,0.01,221.7600,2.0,North,Cash,...,Electronics,4.6,Not Returned,Positive,17.82,nan,1.9,no_data,no_data,NaN
33,2023-02-03,1526.0,185.0,8.0,57.14,0.21,361.1248,2.0,North,Online,...,Electronics,2.1,Not Returned,Neutral,15.45,WELCOME5,1.9,unknown,value_1,NaN
34,2023-02-04,1285.0,168.0,6.0,78.52,0.11,419.2968,5.0,South,Cash,...,Books,1.4,Returned,Negative,NaN,WELCOME5,4.7,Frequent buyer,value_3,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 08:**
</div>

In [18]:
pd.DataFrame.sum?

Signature:
pd.DataFrame.sum(
    self,
    axis: 'Axis | None' = 0,
    skipna: 'bool' = True,
    numeric_only: 'bool' = False,
    min_count: 'int' = 0,
    **kwargs,
)
Docstring:
Return the sum of the values over the requested axis.

This is equivalent to the method ``numpy.sum``.

Parameters
----------
axis : {index (0), columns (1)}
    Axis for the function to be applied on.
    For `Series` this parameter is unused and defaults to 0.

    .. warning::

        The behavior of DataFrame.sum with ``axis=None`` is deprecated,
        in a future version this will reduce over both axes and return a scalar
        To retain the old behavior, pass axis=0 (or do not pass axis).

    .. versionadded:: 2.0.0

skipna : bool, default True
    Exclude NA/null values when computing the result.
numeric_only : bool, default False
    Include only float, int, boolean columns. Not implemented for Series.

min_count : int, default 0
    The required number of valid values to perform the operation. If fewer than
    ``min_count`` non-NA values are present the result will be NA.
**kwargs
    Additional keyword arguments to be passed to the function.

Returns
-------
Series or scalar

See Also
--------
Series.sum : Return the sum.
Series.min : Return the minimum.
Series.max : Return the maximum.
Series.idxmin : Return the index of the minimum.
Series.idxmax : Return the index of the maximum.
DataFrame.sum : Return the sum over the requested axis.
DataFrame.min : Return the minimum over the requested axis.
DataFrame.max : Return the maximum over the requested axis.
DataFrame.idxmin : Return the index of the minimum over the requested axis.
DataFrame.idxmax : Return the index of the maximum over the requested axis.

Examples
--------
>>> idx = pd.MultiIndex.from_arrays([
...     ['warm', 'warm', 'cold', 'cold'],
...     ['dog', 'falcon', 'fish', 'spider']],
...     names=['blooded', 'animal'])
>>> s = pd.Series([4, 2, 0, 8], name='legs', index=idx)
>>> s
blooded  animal
warm     dog       4
         falcon    2
cold     fish      0
         spider    8
Name: legs, dtype: int64

>>> s.sum()
14

By default, the sum of an empty or all-NA Series is ``0``.

>>> pd.Series([], dtype="float64").sum()  # min_count=0 is the default
0.0

This can be controlled with the ``min_count`` parameter. For example, if
you'd like the sum of an empty series to be NaN, pass ``min_count=1``.

>>> pd.Series([], dtype="float64").sum(min_count=1)
nan

Thanks to the ``skipna`` parameter, ``min_count`` handles all-NA and
empty series identically.

>>> pd.Series([np.nan]).sum()
0.0

>>> pd.Series([np.nan]).sum(min_count=1)
nan
File:      ~/dev/pandas-exercises/.venv/lib/python3.12/site-packages/pandas/core/frame.py
Type:      function

In [19]:
df.isnull().sum(axis=0)

date                 1
customer_id          1
product_id           1
quantity             1
price                1
discount             1
revenue              1
store_id             1
region               1
payment_method       1
is_member            1
delivery_days        1
customer_age         1
gender               1
product_category     1
rating               1
return_status        1
feedback             1
shipping_cost        9
coupon_code          1
delivery_rating     10
customer_note        1
customer_values      1
all_nan_column      36
dtype: int64

In [20]:
df.isnull().sum(axis=1)

0      1
1      1
2      1
3      2
4      1
5      2
6      1
7      1
8      2
9      1
10     1
11     1
12     2
13     2
14     2
15     2
16     2
17     2
18     1
19     1
20     1
21     1
22     2
23     1
24     2
25     1
26     2
27     1
28     1
29     3
30     1
31     3
32     1
33     1
34     2
35    24
dtype: int64

In [21]:
df_kept = df[df.isnull().sum(axis=1) >= 2]

# Display the DataFrame after keeping rows
display(df_kept.reset_index(drop=True))

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-04,1684.0,158.0,7.0,87.89,0.30,430.6610,6.0,North,Cash,...,Clothing,2.1,Not Returned,Neutral,12.49,nan,NaN,unknown,unknown,NaN
1,2023-01-06,1592.0,136.0,8.0,87.55,0.25,525.3000,8.0,South,Online,...,Electronics,2.5,Returned,Neutral,NaN,WELCOME5,4.2,unknown,unknown,NaN
2,2023-01-09,1284.0,129.0,9.0,37.58,0.30,236.7540,9.0,West,Credit Card,...,Electronics,1.9,Returned,Positive,10.71,WELCOME5,NaN,Requested gift wrap,value_2,NaN
3,2023-01-13,1661.0,177.0,5.0,69.53,0.13,302.4555,2.0,South,Online,...,Food,1.9,Returned,Neutral,11.87,nan,NaN,no_data,value_2,NaN
4,2023-01-14,1807.0,185.0,2.0,73.43,0.10,132.1740,2.0,North,Online,...,Food,1.8,Returned,Negative,NaN,SAVE10,4.9,no_data,value_3,NaN
5,2023-01-15,1151.0,108.0,2.0,44.70,0.09,81.3540,4.0,North,Credit Card,...,Food,3.7,Not Returned,Negative,19.43,nan,NaN,Used loyalty points,value_1,NaN
6,2023-01-16,1033.0,115.0,5.0,88.76,0.09,403.8580,6.0,East,Online,...,Books,1.3,Not Returned,Negative,17.69,SAVE10,NaN,unknown,value_3,NaN
7,2023-01-17,1599.0,122.0,4.0,45.98,0.12,161.8496,2.0,West,Cash,...,Books,3.9,Not Returned,Negative,NaN,WELCOME5,1.1,Frequent buyer,unknown,NaN
8,2023-01-18,1584.0,107.0,2.0,48.54,0.12,85.4304,3.0,West,Online,...,Electronics,1.5,Returned,Negative,NaN,WELCOME5,3.3,unknown,unknown,NaN
9,2023-01-23,1556.0,139.0,8.0,71.26,0.06,535.8752,5.0,South,Credit Card,...,Food,4.4,Not Returned,Neutral,NaN,nan,4.6,no_data,no_data,NaN
10,2023-01-25,1038.0,163.0,1.0,69.48,0.17,57.6684,6.0,North,Cash,...,Food,4.9,Not Returned,Positive,15.55,FREESHIP,NaN,unknown,value_2,NaN
11,2023-01-27,1508.0,121.0,2.0,25.86,0.28,37.2384,1.0,East,Credit Card,...,Electronics,4.2,Returned,Negative,18.29,WELCOME5,NaN,Preferred morning delivery,value_5,NaN
12,2023-01-30,1090.0,149.0,2.0,25.36,0.11,45.1408,6.0,East,Online,...,Electronics,2.9,Not Returned,Negative,NaN,SAVE10,NaN,Preferred morning delivery,value_5,NaN
13,2023-02-01,1118.0,174.0,9.0,40.29,0.18,297.3402,4.0,North,Online,...,Clothing,3.7,Not Returned,Neutral,NaN,SAVE10,NaN,no_data,unknown,NaN
14,2023-02-04,1285.0,168.0,6.0,78.52,0.11,419.2968,5.0,South,Cash,...,Books,1.4,Returned,Negative,NaN,WELCOME5,4.7,Frequent buyer,value_3,NaN
15,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-warning">

**9. Drop Rows with Missing Values in Specific Columns**

**Write a Pandas program to drop those rows from a given DataFrame in which specific columns have missing values.**

</div>

In [22]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_11311/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1858.0,153.0,1.0,73.39,0.08,67.5188,7.0,East,Credit Card,...,Clothing,2.3,Returned,Negative,NaN,FREESHIP,1.7,unknown,value_3,NaN
1,2023-01-02,1813.0,118.0,2.0,29.74,0.07,55.3164,5.0,North,Online,...,Electronics,1.6,Returned,Positive,16.28,WELCOME5,NaN,no_data,value_4,NaN
2,2023-01-03,1266.0,173.0,9.0,38.05,0.28,246.5640,4.0,South,Online,...,Books,3.5,Returned,Negative,6.45,FREESHIP,3.4,Preferred morning delivery,no_data,NaN
3,2023-01-04,1916.0,189.0,5.0,97.64,0.09,444.2620,8.0,East,Online,...,Clothing,1.6,Not Returned,Negative,17.73,SAVE10,5.0,no_data,value_1,NaN
4,2023-01-05,1353.0,171.0,3.0,52.24,0.19,126.9432,3.0,North,Online,...,Food,4.3,Returned,Neutral,NaN,WELCOME5,4.8,Used loyalty points,unknown,NaN
5,2023-01-06,1279.0,110.0,6.0,99.68,0.07,556.2144,9.0,West,Cash,...,Food,3.1,Returned,Neutral,5.42,SAVE10,3.5,unknown,value_5,NaN
6,2023-01-07,1093.0,105.0,2.0,18.13,0.06,34.0844,2.0,East,Online,...,Books,1.3,Returned,Negative,19.99,nan,2.9,Frequent buyer,value_1,NaN
7,2023-01-08,1338.0,176.0,9.0,45.40,0.12,359.5680,3.0,North,Credit Card,...,Food,3.5,Returned,Negative,13.24,nan,NaN,unknown,value_5,NaN
8,2023-01-09,1064.0,143.0,3.0,42.89,0.07,119.6631,5.0,North,Cash,...,Food,3.3,Not Returned,Negative,17.02,nan,3.4,unknown,value_4,NaN
9,2023-01-10,1380.0,187.0,1.0,73.43,0.22,57.2754,4.0,West,Online,...,Food,4.9,Returned,Positive,17.14,FREESHIP,NaN,unknown,value_1,NaN
10,2023-01-11,1168.0,142.0,3.0,33.46,0.10,90.3420,4.0,West,Online,...,Books,4.4,Returned,Positive,15.84,nan,3.7,unknown,no_data,NaN
11,2023-01-12,1096.0,110.0,8.0,97.98,0.21,619.2336,7.0,West,Credit Card,...,Food,1.8,Not Returned,Positive,17.74,WELCOME5,NaN,Used loyalty points,unknown,NaN
12,2023-01-13,1266.0,182.0,1.0,56.98,0.29,40.4558,1.0,South,Cash,...,Books,1.5,Returned,Neutral,9.83,FREESHIP,4.8,unknown,no_data,NaN
13,2023-01-14,1433.0,185.0,6.0,91.67,0.02,539.0196,5.0,West,Online,...,Electronics,1.9,Returned,Positive,15.24,WELCOME5,4.2,First-time customer,unknown,NaN
14,2023-01-15,1072.0,123.0,5.0,20.37,0.07,94.7205,2.0,East,Online,...,Books,2.0,Returned,Neutral,15.17,SAVE10,1.4,no_data,unknown,NaN
15,2023-01-16,1012.0,143.0,2.0,70.36,0.16,118.2048,5.0,East,Credit Card,...,Food,4.8,Not Returned,Negative,18.57,FREESHIP,NaN,Frequent buyer,value_2,NaN
16,2023-01-17,1810.0,187.0,6.0,58.77,0.14,303.2532,5.0,West,Cash,...,Electronics,3.2,Returned,Neutral,11.94,FREESHIP,3.0,Frequent buyer,unknown,NaN
17,2023-01-18,1897.0,189.0,6.0,57.70,0.13,301.1940,9.0,North,Cash,...,Books,3.4,Returned,Neutral,NaN,WELCOME5,NaN,First-time customer,value_5,NaN
18,2023-01-19,1067.0,197.0,9.0,92.41,0.19,673.6689,4.0,North,Online,...,Electronics,2.7,Returned,Neutral,5.86,nan,NaN,Requested gift wrap,no_data,NaN
19,2023-01-20,1072.0,131.0,5.0,57.13,0.17,237.0895,6.0,West,Credit Card,...,Clothing,4.1,Not Returned,Positive,16.09,nan,3.9,Preferred morning delivery,value_3,NaN
20,2023-01-21,1407.0,146.0,1.0,57.25,0.11,50.9525,8.0,South,Online,...,Clothing,3.3,Not Returned,Neutral,7.07,nan,4.7,no_data,unknown,NaN
21,2023-01-22,1496.0,118.0,1.0,91.16,0.22,71.1048,9.0,North,Online,...,Electronics,2.8,Returned,Neutral,9.28,SAVE10,NaN,no_data,unknown,NaN
22,2023-01-23,1339.0,155.0,4.0,47.93,0.03,185.9684,5.0,North,Credit Card,...,Food,4.6,Not Returned,Neutral,10.33,nan,1.1,no_data,value_3,NaN
23,2023-01-24,1033.0,177.0,4.0,96.96,0.06,364.5696,9.0,North,Cash,...,Clothing,3.0,Returned,Neutral,19.72,nan,1.5,Used loyalty points,value_1,NaN
24,2023-01-25,1824.0,186.0,4.0,32.67,0.26,96.7032,8.0,South,Cash,...,Books,4.9,Not Returned,Negative,6.22,FREESHIP,NaN,First-time customer,no_data,NaN
25,2023-01-26,1418.0,121.0,3.0,20.33,0.27,44.5227,4.0,North,Cash,...,Food,3.3,Returned,Negative,6.06,nan,NaN,no_data,no_data,NaN
26,2023-01-27,1004.0,153.0,3.0,74.61,0.25,167.8725,6.0,North,Online,...,Food,1.2,Not Returned,Negative,7.91,nan,1.6,unknown,value_5,NaN
27,2023-01-28,1988.0,187.0,8.0,78.86,0.28,454.2336,6.0,West,Cash,...,Electronics,3.2,Returned,Positive,18.21,nan,NaN,no_data,value_1,NaN
28,2023-01-29,1056.0,143.0,9.0,64.44,0.15,492.9660,2.0,East,Credit Card,...,Electronics,3.7,Returned,Positive,16.82,nan,4.6,no_data,value_4,NaN
29,2023-01-30,1681.0,183.0,8.0,74.13,0.27,432.9192,3.0,East,Cash,...,Electronics,1.4,Returned,Positive,19.58,WELCOME5,NaN,Preferred morning delivery,value_5,NaN
30,2023-01-31,1039.0,148.0,8.0,14.36,0.07,106.8384,7.0,South,Cash,...,Books,3.5,Returned,Neutral,6.50,SAVE10,4.2,First-time customer,no_data,NaN
31,2023-02-01,1372.0,139.0,8.0,44.12,0.05,335.3120,9.0,North,Online,...,Books,3.5,Not Returned,Positive,19.74,nan,NaN,unknown,value_3,NaN
32,2023-02-02,1139.0,110.0,6.0,12.75,0.24,58.1400,2.0,West,Cash,...,Electronics,3.3,Returned,Positive,17.70,FREESHIP,1.3,Used loyalty points,value_4,NaN
33,2023-02-03,1282.0,198.0,6.0,94.37,0.23,435.9894,3.0,East,Online,...,Electronics,4.3,Not Returned,Negative,11.33,nan,3.0,unknown,unknown,NaN
34,2023-02-04,1001.0,154.0,7.0,49.57,0.24,263.7124,5.0,West,Online,...,Electronics,1.9,Returned,Negative,6.64,FREESHIP,NaN,First-time customer,unknown,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 09:**
</div>

In [23]:
# Write a Pandas program to drop those rows from a given DataFrame in which specific columns have missing values
dropped_df = df.dropna(subset=['shipping_cost', 'coupon_code', 'delivery_rating'])
dropped_df

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
2,2023-01-03,1266.0,173.0,9.0,38.05,0.28,246.5640,4.0,South,Online,...,Books,3.5,Returned,Negative,6.45,FREESHIP,3.4,Preferred morning delivery,no_data,NaN
3,2023-01-04,1916.0,189.0,5.0,97.64,0.09,444.2620,8.0,East,Online,...,Clothing,1.6,Not Returned,Negative,17.73,SAVE10,5.0,no_data,value_1,NaN
5,2023-01-06,1279.0,110.0,6.0,99.68,0.07,556.2144,9.0,West,Cash,...,Food,3.1,Returned,Neutral,5.42,SAVE10,3.5,unknown,value_5,NaN
6,2023-01-07,1093.0,105.0,2.0,18.13,0.06,34.0844,2.0,East,Online,...,Books,1.3,Returned,Negative,19.99,nan,2.9,Frequent buyer,value_1,NaN
8,2023-01-09,1064.0,143.0,3.0,42.89,0.07,119.6631,5.0,North,Cash,...,Food,3.3,Not Returned,Negative,17.02,nan,3.4,unknown,value_4,NaN
10,2023-01-11,1168.0,142.0,3.0,33.46,0.10,90.3420,4.0,West,Online,...,Books,4.4,Returned,Positive,15.84,nan,3.7,unknown,no_data,NaN
12,2023-01-13,1266.0,182.0,1.0,56.98,0.29,40.4558,1.0,South,Cash,...,Books,1.5,Returned,Neutral,9.83,FREESHIP,4.8,unknown,no_data,NaN
13,2023-01-14,1433.0,185.0,6.0,91.67,0.02,539.0196,5.0,West,Online,...,Electronics,1.9,Returned,Positive,15.24,WELCOME5,4.2,First-time customer,unknown,NaN
14,2023-01-15,1072.0,123.0,5.0,20.37,0.07,94.7205,2.0,East,Online,...,Books,2.0,Returned,Neutral,15.17,SAVE10,1.4,no_data,unknown,NaN
16,2023-01-17,1810.0,187.0,6.0,58.77,0.14,303.2532,5.0,West,Cash,...,Electronics,3.2,Returned,Neutral,11.94,FREESHIP,3.0,Frequent buyer,unknown,NaN
19,2023-01-20,1072.0,131.0,5.0,57.13,0.17,237.0895,6.0,West,Credit Card,...,Clothing,4.1,Not Returned,Positive,16.09,nan,3.9,Preferred morning delivery,value_3,NaN
20,2023-01-21,1407.0,146.0,1.0,57.25,0.11,50.9525,8.0,South,Online,...,Clothing,3.3,Not Returned,Neutral,7.07,nan,4.7,no_data,unknown,NaN
22,2023-01-23,1339.0,155.0,4.0,47.93,0.03,185.9684,5.0,North,Credit Card,...,Food,4.6,Not Returned,Neutral,10.33,nan,1.1,no_data,value_3,NaN
23,2023-01-24,1033.0,177.0,4.0,96.96,0.06,364.5696,9.0,North,Cash,...,Clothing,3.0,Returned,Neutral,19.72,nan,1.5,Used loyalty points,value_1,NaN
26,2023-01-27,1004.0,153.0,3.0,74.61,0.25,167.8725,6.0,North,Online,...,Food,1.2,Not Returned,Negative,7.91,nan,1.6,unknown,value_5,NaN
28,2023-01-29,1056.0,143.0,9.0,64.44,0.15,492.9660,2.0,East,Credit Card,...,Electronics,3.7,Returned,Positive,16.82,nan,4.6,no_data,value_4,NaN
30,2023-01-31,1039.0,148.0,8.0,14.36,0.07,106.8384,7.0,South,Cash,...,Books,3.5,Returned,Neutral,6.50,SAVE10,4.2,First-time customer,no_data,NaN
32,2023-02-02,1139.0,110.0,6.0,12.75,0.24,58.1400,2.0,West,Cash,...,Electronics,3.3,Returned,Positive,17.70,FREESHIP,1.3,Used loyalty points,value_4,NaN
33,2023-02-03,1282.0,198.0,6.0,94.37,0.23,435.9894,3.0,East,Online,...,Electronics,4.3,Not Returned,Negative,11.33,nan,3.0,unknown,unknown,NaN

<div class="alert alert-warning">

**10. Keep Only Valid Entries**

**Write a Pandas program to keep the valid entries of a given DataFrame.**

</div>

In [24]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_11311/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1578.0,165.0,7.0,12.49,0.23,67.3211,7.0,South,Cash,...,Clothing,1.2,Returned,Positive,13.90,FREESHIP,4.5,Preferred morning delivery,unknown,NaN
1,2023-01-02,1054.0,152.0,6.0,76.22,0.29,324.6972,6.0,West,Cash,...,Books,1.9,Not Returned,Positive,15.22,WELCOME5,NaN,Frequent buyer,value_5,NaN
2,2023-01-03,1982.0,169.0,6.0,78.98,0.26,350.6712,5.0,South,Cash,...,Clothing,1.2,Returned,Positive,19.78,FREESHIP,4.8,Preferred morning delivery,no_data,NaN
3,2023-01-04,1933.0,102.0,5.0,25.17,0.15,106.9725,3.0,South,Online,...,Books,2.0,Not Returned,Positive,18.77,FREESHIP,1.9,unknown,unknown,NaN
4,2023-01-05,1424.0,159.0,9.0,80.72,0.24,552.1248,6.0,East,Credit Card,...,Clothing,2.7,Returned,Neutral,17.41,FREESHIP,NaN,Requested gift wrap,value_4,NaN
5,2023-01-06,1586.0,179.0,5.0,22.61,0.15,96.0925,4.0,West,Online,...,Electronics,2.8,Not Returned,Negative,9.71,SAVE10,3.4,no_data,value_4,NaN
6,2023-01-07,1014.0,120.0,6.0,71.14,0.08,392.6928,9.0,South,Online,...,Clothing,3.0,Not Returned,Neutral,18.35,SAVE10,4.1,unknown,unknown,NaN
7,2023-01-08,1066.0,184.0,9.0,58.43,0.24,399.6612,1.0,North,Credit Card,...,Clothing,3.2,Returned,Positive,12.28,nan,4.7,Used loyalty points,value_5,NaN
8,2023-01-09,1184.0,141.0,8.0,29.63,0.09,215.7064,9.0,North,Cash,...,Clothing,2.3,Not Returned,Positive,NaN,nan,3.5,unknown,value_3,NaN
9,2023-01-10,1565.0,143.0,6.0,98.73,0.04,568.6848,9.0,East,Credit Card,...,Books,4.5,Not Returned,Neutral,17.98,FREESHIP,NaN,Preferred morning delivery,unknown,NaN
10,2023-01-11,1249.0,183.0,4.0,20.52,0.19,66.4848,7.0,West,Credit Card,...,Clothing,1.1,Not Returned,Negative,13.19,nan,NaN,no_data,unknown,NaN
11,2023-01-12,1966.0,167.0,1.0,82.86,0.12,72.9168,5.0,South,Cash,...,Food,4.7,Not Returned,Neutral,13.17,nan,NaN,First-time customer,value_1,NaN
12,2023-01-13,1040.0,153.0,5.0,66.44,0.18,272.4040,8.0,East,Cash,...,Electronics,3.6,Not Returned,Neutral,5.72,FREESHIP,2.7,unknown,unknown,NaN
13,2023-01-14,1495.0,147.0,4.0,17.65,0.22,55.0680,8.0,West,Credit Card,...,Food,2.0,Not Returned,Neutral,13.28,nan,4.3,unknown,value_1,NaN
14,2023-01-15,1631.0,122.0,6.0,88.24,0.20,423.5520,8.0,North,Online,...,Books,3.4,Not Returned,Negative,8.31,WELCOME5,1.8,unknown,value_5,NaN
15,2023-01-16,1955.0,144.0,5.0,30.25,0.17,125.5375,7.0,West,Online,...,Electronics,2.7,Not Returned,Positive,19.89,FREESHIP,NaN,no_data,unknown,NaN
16,2023-01-17,1136.0,190.0,1.0,96.19,0.07,89.4567,2.0,North,Credit Card,...,Books,2.5,Not Returned,Neutral,17.99,nan,NaN,Preferred morning delivery,no_data,NaN
17,2023-01-18,1697.0,194.0,6.0,66.33,0.29,282.5658,3.0,East,Credit Card,...,Clothing,4.3,Not Returned,Neutral,16.24,WELCOME5,2.0,no_data,no_data,NaN
18,2023-01-19,1478.0,184.0,2.0,13.92,0.26,20.6016,7.0,South,Credit Card,...,Books,1.6,Returned,Positive,14.08,FREESHIP,1.5,no_data,no_data,NaN
19,2023-01-20,1970.0,127.0,2.0,97.04,0.12,170.7904,1.0,West,Online,...,Food,2.1,Not Returned,Neutral,5.14,SAVE10,3.5,no_data,unknown,NaN
20,2023-01-21,1475.0,132.0,8.0,36.31,0.26,214.9552,7.0,South,Cash,...,Electronics,3.5,Returned,Positive,NaN,WELCOME5,3.4,no_data,value_5,NaN
21,2023-01-22,1274.0,164.0,7.0,97.03,0.17,563.7443,6.0,East,Online,...,Clothing,1.6,Not Returned,Negative,14.73,nan,NaN,First-time customer,unknown,NaN
22,2023-01-23,1396.0,185.0,3.0,14.81,0.27,32.4339,3.0,South,Cash,...,Food,3.1,Not Returned,Negative,NaN,SAVE10,1.5,no_data,value_3,NaN
23,2023-01-24,1577.0,121.0,9.0,96.56,0.02,851.6592,5.0,North,Credit Card,...,Electronics,2.3,Returned,Positive,5.17,WELCOME5,4.0,Used loyalty points,value_1,NaN
24,2023-01-25,1991.0,166.0,2.0,97.39,0.07,181.1454,6.0,East,Cash,...,Clothing,4.0,Not Returned,Positive,6.94,SAVE10,NaN,no_data,value_5,NaN
25,2023-01-26,1384.0,118.0,1.0,20.04,0.27,14.6292,5.0,South,Cash,...,Books,1.6,Returned,Negative,5.32,WELCOME5,3.7,First-time customer,unknown,NaN
26,2023-01-27,1267.0,189.0,6.0,55.24,0.07,308.2392,6.0,East,Credit Card,...,Food,1.4,Not Returned,Neutral,17.85,FREESHIP,4.0,Requested gift wrap,unknown,NaN
27,2023-01-28,1857.0,183.0,6.0,74.05,0.19,359.8830,2.0,East,Online,...,Clothing,2.5,Not Returned,Negative,18.72,nan,NaN,Requested gift wrap,no_data,NaN
28,2023-01-29,1445.0,113.0,2.0,40.35,0.08,74.2440,8.0,West,Cash,...,Books,3.9,Returned,Positive,18.66,WELCOME5,2.0,unknown,value_1,NaN
29,2023-01-30,1376.0,159.0,4.0,38.36,0.09,139.6304,8.0,South,Cash,...,Clothing,2.6,Not Returned,Negative,10.37,WELCOME5,NaN,Frequent buyer,unknown,NaN
30,2023-01-31,1931.0,177.0,3.0,30.63,0.13,79.9443,7.0,West,Online,...,Clothing,3.3,Returned,Positive,5.84,SAVE10,4.3,no_data,value_3,NaN
31,2023-02-01,1911.0,131.0,2.0,59.58,0.13,103.6692,5.0,North,Online,...,Clothing,1.7,Returned,Positive,5.15,FREESHIP,3.8,no_data,no_data,NaN
32,2023-02-02,1973.0,108.0,8.0,71.16,0.27,415.5744,8.0,South,Credit Card,...,Clothing,2.7,Not Returned,Negative,14.51,nan,3.9,Frequent buyer,no_data,NaN
33,2023-02-03,1239.0,122.0,8.0,58.51,0.03,454.0376,9.0,West,Online,...,Electronics,2.0,Returned,Positive,13.40,SAVE10,NaN,Preferred morning delivery,unknown,NaN
34,2023-02-04,1987.0,167.0,7.0,84.65,0.07,551.0715,3.0,East,Online,...,Books,3.3,Returned,Negative,6.59,nan,1.8,First-time customer,no_data,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 10:**
</div>

In [25]:
# Write a Pandas program to keep the valid entries of a given DataFrame
valid_entries_df = df.dropna(subset=['customer_id', 'product_id', 'quantity', 'price', 'revenue', 'delivery_rating'])
display(valid_entries_df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1578.0,165.0,7.0,12.49,0.23,67.3211,7.0,South,Cash,...,Clothing,1.2,Returned,Positive,13.90,FREESHIP,4.5,Preferred morning delivery,unknown,NaN
2,2023-01-03,1982.0,169.0,6.0,78.98,0.26,350.6712,5.0,South,Cash,...,Clothing,1.2,Returned,Positive,19.78,FREESHIP,4.8,Preferred morning delivery,no_data,NaN
3,2023-01-04,1933.0,102.0,5.0,25.17,0.15,106.9725,3.0,South,Online,...,Books,2.0,Not Returned,Positive,18.77,FREESHIP,1.9,unknown,unknown,NaN
5,2023-01-06,1586.0,179.0,5.0,22.61,0.15,96.0925,4.0,West,Online,...,Electronics,2.8,Not Returned,Negative,9.71,SAVE10,3.4,no_data,value_4,NaN
6,2023-01-07,1014.0,120.0,6.0,71.14,0.08,392.6928,9.0,South,Online,...,Clothing,3.0,Not Returned,Neutral,18.35,SAVE10,4.1,unknown,unknown,NaN
7,2023-01-08,1066.0,184.0,9.0,58.43,0.24,399.6612,1.0,North,Credit Card,...,Clothing,3.2,Returned,Positive,12.28,nan,4.7,Used loyalty points,value_5,NaN
8,2023-01-09,1184.0,141.0,8.0,29.63,0.09,215.7064,9.0,North,Cash,...,Clothing,2.3,Not Returned,Positive,NaN,nan,3.5,unknown,value_3,NaN
12,2023-01-13,1040.0,153.0,5.0,66.44,0.18,272.4040,8.0,East,Cash,...,Electronics,3.6,Not Returned,Neutral,5.72,FREESHIP,2.7,unknown,unknown,NaN
13,2023-01-14,1495.0,147.0,4.0,17.65,0.22,55.0680,8.0,West,Credit Card,...,Food,2.0,Not Returned,Neutral,13.28,nan,4.3,unknown,value_1,NaN
14,2023-01-15,1631.0,122.0,6.0,88.24,0.20,423.5520,8.0,North,Online,...,Books,3.4,Not Returned,Negative,8.31,WELCOME5,1.8,unknown,value_5,NaN
17,2023-01-18,1697.0,194.0,6.0,66.33,0.29,282.5658,3.0,East,Credit Card,...,Clothing,4.3,Not Returned,Neutral,16.24,WELCOME5,2.0,no_data,no_data,NaN
18,2023-01-19,1478.0,184.0,2.0,13.92,0.26,20.6016,7.0,South,Credit Card,...,Books,1.6,Returned,Positive,14.08,FREESHIP,1.5,no_data,no_data,NaN
19,2023-01-20,1970.0,127.0,2.0,97.04,0.12,170.7904,1.0,West,Online,...,Food,2.1,Not Returned,Neutral,5.14,SAVE10,3.5,no_data,unknown,NaN
20,2023-01-21,1475.0,132.0,8.0,36.31,0.26,214.9552,7.0,South,Cash,...,Electronics,3.5,Returned,Positive,NaN,WELCOME5,3.4,no_data,value_5,NaN
22,2023-01-23,1396.0,185.0,3.0,14.81,0.27,32.4339,3.0,South,Cash,...,Food,3.1,Not Returned,Negative,NaN,SAVE10,1.5,no_data,value_3,NaN
23,2023-01-24,1577.0,121.0,9.0,96.56,0.02,851.6592,5.0,North,Credit Card,...,Electronics,2.3,Returned,Positive,5.17,WELCOME5,4.0,Used loyalty points,value_1,NaN
25,2023-01-26,1384.0,118.0,1.0,20.04,0.27,14.6292,5.0,South,Cash,...,Books,1.6,Returned,Negative,5.32,WELCOME5,3.7,First-time customer,unknown,NaN
26,2023-01-27,1267.0,189.0,6.0,55.24,0.07,308.2392,6.0,East,Credit Card,...,Food,1.4,Not Returned,Neutral,17.85,FREESHIP,4.0,Requested gift wrap,unknown,NaN
28,2023-01-29,1445.0,113.0,2.0,40.35,0.08,74.2440,8.0,West,Cash,...,Books,3.9,Returned,Positive,18.66,WELCOME5,2.0,unknown,value_1,NaN
30,2023-01-31,1931.0,177.0,3.0,30.63,0.13,79.9443,7.0,West,Online,...,Clothing,3.3,Returned,Positive,5.84,SAVE10,4.3,no_data,value_3,NaN
31,2023-02-01,1911.0,131.0,2.0,59.58,0.13,103.6692,5.0,North,Online,...,Clothing,1.7,Returned,Positive,5.15,FREESHIP,3.8,no_data,no_data,NaN
32,2023-02-02,1973.0,108.0,8.0,71.16,0.27,415.5744,8.0,South,Credit Card,...,Clothing,2.7,Not Returned,Negative,14.51,nan,3.9,Frequent buyer,no_data,NaN
34,2023-02-04,1987.0,167.0,7.0,84.65,0.07,551.0715,3.0,East,Online,...,Books,3.3,Returned,Negative,6.59,nan,1.8,First-time customer,no_data,NaN

<div class="alert alert-warning">

**11. Total Number of Missing Values in DataFrame**

**Write a Pandas program to calculate the total number of missing values in a DataFrame.**

</div>

In [26]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_11311/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1563.0,181.0,3.0,97.39,0.07,271.7181,5.0,West,Credit Card,...,Food,2.6,Not Returned,Negative,14.53,nan,1.1,unknown,no_data,NaN
1,2023-01-02,1544.0,171.0,6.0,12.01,0.14,61.9716,9.0,West,Cash,...,Food,4.6,Not Returned,Negative,12.30,nan,NaN,no_data,no_data,NaN
2,2023-01-03,1301.0,165.0,3.0,37.82,0.06,106.6524,6.0,North,Online,...,Books,4.3,Not Returned,Neutral,NaN,WELCOME5,4.4,Used loyalty points,value_3,NaN
3,2023-01-04,1019.0,171.0,1.0,83.75,0.30,58.6250,9.0,East,Cash,...,Books,3.4,Returned,Negative,19.93,nan,4.6,unknown,value_5,NaN
4,2023-01-05,1772.0,115.0,4.0,99.17,0.04,380.8128,5.0,North,Credit Card,...,Food,2.4,Not Returned,Neutral,NaN,nan,3.5,Requested gift wrap,value_4,NaN
5,2023-01-06,1773.0,104.0,1.0,69.42,0.03,67.3374,2.0,North,Cash,...,Electronics,3.5,Returned,Negative,NaN,WELCOME5,2.9,Preferred morning delivery,value_3,NaN
6,2023-01-07,1253.0,142.0,3.0,48.78,0.15,124.3890,1.0,West,Online,...,Food,3.3,Returned,Positive,17.50,nan,4.7,Preferred morning delivery,value_3,NaN
7,2023-01-08,1835.0,172.0,2.0,14.06,0.23,21.6524,6.0,West,Cash,...,Electronics,4.8,Returned,Neutral,13.96,nan,2.5,Frequent buyer,unknown,NaN
8,2023-01-09,1626.0,161.0,4.0,31.65,0.29,89.8860,3.0,South,Online,...,Clothing,2.9,Not Returned,Positive,12.74,nan,NaN,unknown,unknown,NaN
9,2023-01-10,1778.0,148.0,4.0,93.94,0.04,360.7296,7.0,West,Credit Card,...,Books,3.3,Returned,Neutral,NaN,nan,4.5,unknown,value_1,NaN
10,2023-01-11,1651.0,109.0,7.0,63.53,0.28,320.1912,4.0,South,Cash,...,Books,4.9,Returned,Negative,6.25,FREESHIP,NaN,Used loyalty points,unknown,NaN
11,2023-01-12,1210.0,181.0,8.0,50.35,0.19,326.2680,9.0,North,Cash,...,Electronics,4.5,Returned,Positive,13.53,FREESHIP,3.3,no_data,unknown,NaN
12,2023-01-13,1811.0,110.0,7.0,70.01,0.11,436.1623,3.0,South,Online,...,Books,1.3,Returned,Positive,NaN,SAVE10,2.7,no_data,value_5,NaN
13,2023-01-14,1702.0,153.0,2.0,50.19,0.28,72.2736,3.0,South,Credit Card,...,Electronics,2.1,Returned,Positive,NaN,nan,NaN,unknown,unknown,NaN
14,2023-01-15,1385.0,105.0,3.0,55.25,0.05,157.4625,9.0,West,Cash,...,Books,4.6,Not Returned,Positive,19.05,FREESHIP,NaN,Used loyalty points,value_4,NaN
15,2023-01-16,1499.0,152.0,3.0,86.63,0.09,236.4999,3.0,East,Cash,...,Electronics,4.1,Not Returned,Positive,15.47,WELCOME5,1.6,Requested gift wrap,value_2,NaN
16,2023-01-17,1925.0,166.0,4.0,71.20,0.16,239.2320,2.0,South,Online,...,Electronics,1.8,Not Returned,Positive,NaN,WELCOME5,NaN,no_data,unknown,NaN
17,2023-01-18,1149.0,141.0,9.0,82.68,0.10,669.7080,7.0,North,Cash,...,Electronics,2.3,Not Returned,Positive,NaN,FREESHIP,4.0,no_data,value_3,NaN
18,2023-01-19,1814.0,167.0,9.0,90.01,0.01,801.9891,9.0,East,Cash,...,Food,4.8,Not Returned,Positive,NaN,SAVE10,NaN,unknown,value_2,NaN
19,2023-01-20,1529.0,178.0,7.0,13.65,0.10,85.9950,8.0,South,Online,...,Electronics,1.8,Not Returned,Neutral,5.69,SAVE10,4.2,Frequent buyer,value_2,NaN
20,2023-01-21,1013.0,116.0,4.0,31.71,0.01,125.5716,4.0,West,Online,...,Food,3.7,Returned,Positive,19.29,FREESHIP,2.8,First-time customer,value_4,NaN
21,2023-01-22,1462.0,137.0,3.0,22.50,0.03,65.4750,2.0,West,Online,...,Books,1.2,Returned,Neutral,7.19,nan,1.1,Used loyalty points,value_4,NaN
22,2023-01-23,1793.0,162.0,1.0,75.68,0.15,64.3280,6.0,South,Online,...,Clothing,4.3,Returned,Neutral,10.20,WELCOME5,3.5,Preferred morning delivery,no_data,NaN
23,2023-01-24,1014.0,130.0,3.0,95.12,0.08,262.5312,4.0,North,Online,...,Clothing,3.7,Not Returned,Positive,17.01,FREESHIP,4.3,unknown,unknown,NaN
24,2023-01-25,1520.0,180.0,7.0,21.79,0.17,126.5999,5.0,West,Cash,...,Books,3.1,Returned,Negative,10.02,SAVE10,1.7,no_data,value_2,NaN
25,2023-01-26,1696.0,135.0,7.0,13.10,0.06,86.1980,8.0,West,Cash,...,Clothing,3.5,Not Returned,Negative,10.92,FREESHIP,4.8,no_data,unknown,NaN
26,2023-01-27,1565.0,140.0,1.0,19.64,0.07,18.2652,2.0,South,Online,...,Electronics,3.9,Returned,Positive,9.27,WELCOME5,NaN,First-time customer,value_5,NaN
27,2023-01-28,1045.0,175.0,8.0,45.44,0.20,290.8160,4.0,East,Credit Card,...,Clothing,3.6,Returned,Negative,NaN,WELCOME5,1.4,no_data,value_3,NaN
28,2023-01-29,1153.0,194.0,3.0,59.66,0.16,150.3432,8.0,South,Cash,...,Clothing,4.0,Returned,Positive,9.18,WELCOME5,NaN,Used loyalty points,value_3,NaN
29,2023-01-30,1430.0,147.0,6.0,94.70,0.04,545.4720,2.0,West,Credit Card,...,Electronics,2.2,Returned,Neutral,6.19,WELCOME5,4.9,Used loyalty points,value_5,NaN
30,2023-01-31,1484.0,123.0,3.0,20.19,0.17,50.2731,8.0,North,Online,...,Electronics,2.7,Not Returned,Negative,9.26,FREESHIP,3.7,unknown,no_data,NaN
31,2023-02-01,1451.0,147.0,2.0,60.01,0.20,96.0160,4.0,East,Credit Card,...,Clothing,2.6,Not Returned,Neutral,8.45,WELCOME5,NaN,unknown,value_2,NaN
32,2023-02-02,1533.0,125.0,8.0,48.57,0.15,330.2760,1.0,North,Credit Card,...,Clothing,4.6,Not Returned,Neutral,18.18,nan,4.8,Used loyalty points,no_data,NaN
33,2023-02-03,1213.0,160.0,8.0,80.78,0.28,465.2928,1.0,East,Credit Card,...,Electronics,3.2,Returned,Negative,15.18,FREESHIP,NaN,no_data,no_data,NaN
34,2023-02-04,1907.0,118.0,6.0,97.12,0.28,419.5584,9.0,West,Credit Card,...,Clothing,2.6,Returned,Positive,NaN,nan,3.3,unknown,no_data,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 11:**
</div>

In [27]:
print(df.isna().sum().sum())

81

<div class="alert alert-warning">

**12. Replace NaNs with a Constant in Specified Columns**

**Write a Pandas program to replace NaNs with a single constant value in specified columns in a DataFrame.**

</div>

In [28]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_11311/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1986.0,108.0,6.0,10.90,0.17,54.2820,3.0,East,Cash,...,Books,3.4,Returned,Negative,10.63,nan,1.6,Requested gift wrap,value_4,NaN
1,2023-01-02,1078.0,102.0,2.0,37.85,0.16,63.5880,6.0,West,Credit Card,...,Food,2.4,Returned,Positive,11.72,nan,1.2,no_data,value_3,NaN
2,2023-01-03,1840.0,118.0,1.0,48.80,0.26,36.1120,3.0,East,Online,...,Books,3.2,Returned,Negative,NaN,nan,3.8,unknown,no_data,NaN
3,2023-01-04,1021.0,122.0,1.0,19.43,0.13,16.9041,1.0,South,Online,...,Books,3.6,Not Returned,Neutral,6.68,SAVE10,4.4,First-time customer,value_3,NaN
4,2023-01-05,1980.0,125.0,8.0,81.23,0.20,519.8720,1.0,North,Cash,...,Clothing,1.1,Returned,Negative,NaN,SAVE10,3.0,Used loyalty points,value_5,NaN
5,2023-01-06,1441.0,197.0,2.0,15.72,0.14,27.0384,1.0,East,Cash,...,Food,4.1,Returned,Negative,NaN,nan,3.8,Used loyalty points,unknown,NaN
6,2023-01-07,1731.0,144.0,6.0,72.90,0.27,319.3020,3.0,North,Credit Card,...,Clothing,1.7,Not Returned,Negative,NaN,FREESHIP,2.7,First-time customer,unknown,NaN
7,2023-01-08,1358.0,162.0,7.0,17.85,0.14,107.4570,3.0,West,Cash,...,Food,2.4,Not Returned,Positive,13.62,FREESHIP,2.9,Used loyalty points,unknown,NaN
8,2023-01-09,1739.0,141.0,9.0,42.00,0.28,272.1600,3.0,West,Cash,...,Books,2.8,Not Returned,Neutral,17.76,nan,3.2,Requested gift wrap,value_4,NaN
9,2023-01-10,1278.0,161.0,6.0,48.50,0.26,215.3400,2.0,East,Credit Card,...,Clothing,4.0,Not Returned,Positive,5.82,nan,3.7,unknown,value_4,NaN
10,2023-01-11,1230.0,116.0,9.0,87.53,0.19,638.0937,1.0,North,Online,...,Books,4.3,Not Returned,Negative,7.90,WELCOME5,3.9,First-time customer,unknown,NaN
11,2023-01-12,1309.0,137.0,8.0,69.50,0.21,439.2400,1.0,West,Credit Card,...,Clothing,4.0,Not Returned,Neutral,10.14,SAVE10,NaN,Frequent buyer,no_data,NaN
12,2023-01-13,1883.0,186.0,1.0,92.46,0.07,85.9878,2.0,North,Cash,...,Clothing,3.4,Not Returned,Positive,10.34,nan,2.6,unknown,value_2,NaN
13,2023-01-14,1522.0,129.0,9.0,83.83,0.09,686.5677,2.0,East,Cash,...,Electronics,4.5,Returned,Neutral,NaN,nan,NaN,Preferred morning delivery,no_data,NaN
14,2023-01-15,1502.0,117.0,1.0,92.44,0.21,73.0276,5.0,South,Cash,...,Books,1.9,Returned,Neutral,10.56,FREESHIP,4.1,Frequent buyer,value_3,NaN
15,2023-01-16,1292.0,159.0,8.0,31.64,0.07,235.4016,3.0,North,Online,...,Clothing,2.6,Not Returned,Neutral,NaN,nan,3.8,Preferred morning delivery,value_3,NaN
16,2023-01-17,1832.0,162.0,9.0,75.49,0.09,618.2631,2.0,North,Credit Card,...,Electronics,4.0,Not Returned,Positive,17.41,FREESHIP,4.8,Preferred morning delivery,no_data,NaN
17,2023-01-18,1079.0,187.0,4.0,63.54,0.25,190.6200,7.0,South,Credit Card,...,Food,1.4,Not Returned,Positive,6.14,nan,3.0,unknown,value_2,NaN
18,2023-01-19,1659.0,172.0,7.0,98.92,0.11,616.2716,7.0,South,Online,...,Food,2.8,Returned,Positive,13.20,nan,NaN,no_data,value_3,NaN
19,2023-01-20,1021.0,126.0,3.0,27.61,0.23,63.7791,9.0,South,Cash,...,Clothing,2.9,Not Returned,Neutral,11.01,FREESHIP,NaN,no_data,no_data,NaN
20,2023-01-21,1164.0,176.0,3.0,67.07,0.20,160.9680,2.0,South,Credit Card,...,Books,3.5,Not Returned,Positive,NaN,WELCOME5,3.4,unknown,no_data,NaN
21,2023-01-22,1508.0,168.0,7.0,71.74,0.07,467.0274,3.0,West,Cash,...,Clothing,1.1,Not Returned,Negative,14.02,WELCOME5,2.3,First-time customer,unknown,NaN
22,2023-01-23,1132.0,158.0,6.0,97.82,0.25,440.1900,6.0,East,Online,...,Electronics,4.1,Returned,Negative,17.35,SAVE10,NaN,unknown,value_3,NaN
23,2023-01-24,1721.0,171.0,6.0,17.22,0.21,81.6228,6.0,South,Cash,...,Books,4.9,Returned,Negative,7.54,WELCOME5,3.8,unknown,unknown,NaN
24,2023-01-25,1306.0,122.0,2.0,48.46,0.04,93.0432,7.0,West,Credit Card,...,Food,2.6,Returned,Positive,18.62,WELCOME5,4.3,unknown,no_data,NaN
25,2023-01-26,1210.0,177.0,1.0,44.00,0.19,35.6400,9.0,East,Online,...,Food,1.4,Returned,Neutral,NaN,SAVE10,1.8,Requested gift wrap,value_2,NaN
26,2023-01-27,1083.0,108.0,8.0,63.07,0.07,469.2408,6.0,North,Credit Card,...,Clothing,2.1,Returned,Neutral,NaN,FREESHIP,NaN,Requested gift wrap,unknown,NaN
27,2023-01-28,1343.0,188.0,4.0,23.52,0.14,80.9088,7.0,East,Cash,...,Electronics,2.5,Returned,Neutral,NaN,SAVE10,NaN,no_data,no_data,NaN
28,2023-01-29,1926.0,177.0,1.0,38.76,0.19,31.3956,7.0,West,Online,...,Books,2.8,Not Returned,Neutral,11.72,SAVE10,4.8,Used loyalty points,value_3,NaN
29,2023-01-30,1410.0,185.0,3.0,45.84,0.09,125.1432,4.0,East,Cash,...,Clothing,4.8,Not Returned,Positive,9.77,WELCOME5,4.6,no_data,no_data,NaN
30,2023-01-31,1309.0,160.0,7.0,35.78,0.29,177.8266,2.0,East,Cash,...,Electronics,4.6,Not Returned,Neutral,13.75,nan,2.6,no_data,no_data,NaN
31,2023-02-01,1583.0,172.0,9.0,51.44,0.07,430.5528,3.0,East,Credit Card,...,Books,4.7,Not Returned,Neutral,NaN,nan,3.7,Requested gift wrap,value_1,NaN
32,2023-02-02,1429.0,106.0,4.0,45.18,0.23,139.1544,9.0,East,Credit Card,...,Books,4.2,Not Returned,Neutral,NaN,nan,1.1,unknown,value_2,NaN
33,2023-02-03,1895.0,189.0,5.0,60.77,0.20,243.0800,2.0,West,Cash,...,Clothing,2.1,Returned,Neutral,NaN,FREESHIP,NaN,Preferred morning delivery,value_3,NaN
34,2023-02-04,1754.0,146.0,3.0,32.93,0.10,88.9110,4.0,East,Online,...,Books,4.2,Returned,Negative,15.09,WELCOME5,4.4,Preferred morning delivery,unknown,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 12:**
</div>

In [29]:
# Write a Pandas program to fill the missing values in specific columns of a given DataFrame
df_filled = df.fillna({'shipping_cost': 0, 'coupon_code': 'NO_COUPON', 'delivery_rating': 0})
df_filled

# or we can use the `fillna` method directly on the DataFrame
df['shipping_cost'].fillna(0, inplace=True)

# or we can use the `fillna` method directly on the DataFrame with multiple columns
df.fillna(
    {
        'shipping_cost': 0
        , 'coupon_code': 'NO_COUPON'
        , 'delivery_rating': 0
    }
    , inplace=True
)

df

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_11311/3401518830.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['shipping_cost'].fillna(0, inplace=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1986.0,108.0,6.0,10.90,0.17,54.2820,3.0,East,Cash,...,Books,3.4,Returned,Negative,10.63,nan,1.6,Requested gift wrap,value_4,NaN
1,2023-01-02,1078.0,102.0,2.0,37.85,0.16,63.5880,6.0,West,Credit Card,...,Food,2.4,Returned,Positive,11.72,nan,1.2,no_data,value_3,NaN
2,2023-01-03,1840.0,118.0,1.0,48.80,0.26,36.1120,3.0,East,Online,...,Books,3.2,Returned,Negative,0.00,nan,3.8,unknown,no_data,NaN
3,2023-01-04,1021.0,122.0,1.0,19.43,0.13,16.9041,1.0,South,Online,...,Books,3.6,Not Returned,Neutral,6.68,SAVE10,4.4,First-time customer,value_3,NaN
4,2023-01-05,1980.0,125.0,8.0,81.23,0.20,519.8720,1.0,North,Cash,...,Clothing,1.1,Returned,Negative,0.00,SAVE10,3.0,Used loyalty points,value_5,NaN
5,2023-01-06,1441.0,197.0,2.0,15.72,0.14,27.0384,1.0,East,Cash,...,Food,4.1,Returned,Negative,0.00,nan,3.8,Used loyalty points,unknown,NaN
6,2023-01-07,1731.0,144.0,6.0,72.90,0.27,319.3020,3.0,North,Credit Card,...,Clothing,1.7,Not Returned,Negative,0.00,FREESHIP,2.7,First-time customer,unknown,NaN
7,2023-01-08,1358.0,162.0,7.0,17.85,0.14,107.4570,3.0,West,Cash,...,Food,2.4,Not Returned,Positive,13.62,FREESHIP,2.9,Used loyalty points,unknown,NaN
8,2023-01-09,1739.0,141.0,9.0,42.00,0.28,272.1600,3.0,West,Cash,...,Books,2.8,Not Returned,Neutral,17.76,nan,3.2,Requested gift wrap,value_4,NaN
9,2023-01-10,1278.0,161.0,6.0,48.50,0.26,215.3400,2.0,East,Credit Card,...,Clothing,4.0,Not Returned,Positive,5.82,nan,3.7,unknown,value_4,NaN
10,2023-01-11,1230.0,116.0,9.0,87.53,0.19,638.0937,1.0,North,Online,...,Books,4.3,Not Returned,Negative,7.90,WELCOME5,3.9,First-time customer,unknown,NaN
11,2023-01-12,1309.0,137.0,8.0,69.50,0.21,439.2400,1.0,West,Credit Card,...,Clothing,4.0,Not Returned,Neutral,10.14,SAVE10,0.0,Frequent buyer,no_data,NaN
12,2023-01-13,1883.0,186.0,1.0,92.46,0.07,85.9878,2.0,North,Cash,...,Clothing,3.4,Not Returned,Positive,10.34,nan,2.6,unknown,value_2,NaN
13,2023-01-14,1522.0,129.0,9.0,83.83,0.09,686.5677,2.0,East,Cash,...,Electronics,4.5,Returned,Neutral,0.00,nan,0.0,Preferred morning delivery,no_data,NaN
14,2023-01-15,1502.0,117.0,1.0,92.44,0.21,73.0276,5.0,South,Cash,...,Books,1.9,Returned,Neutral,10.56,FREESHIP,4.1,Frequent buyer,value_3,NaN
15,2023-01-16,1292.0,159.0,8.0,31.64,0.07,235.4016,3.0,North,Online,...,Clothing,2.6,Not Returned,Neutral,0.00,nan,3.8,Preferred morning delivery,value_3,NaN
16,2023-01-17,1832.0,162.0,9.0,75.49,0.09,618.2631,2.0,North,Credit Card,...,Electronics,4.0,Not Returned,Positive,17.41,FREESHIP,4.8,Preferred morning delivery,no_data,NaN
17,2023-01-18,1079.0,187.0,4.0,63.54,0.25,190.6200,7.0,South,Credit Card,...,Food,1.4,Not Returned,Positive,6.14,nan,3.0,unknown,value_2,NaN
18,2023-01-19,1659.0,172.0,7.0,98.92,0.11,616.2716,7.0,South,Online,...,Food,2.8,Returned,Positive,13.20,nan,0.0,no_data,value_3,NaN
19,2023-01-20,1021.0,126.0,3.0,27.61,0.23,63.7791,9.0,South,Cash,...,Clothing,2.9,Not Returned,Neutral,11.01,FREESHIP,0.0,no_data,no_data,NaN
20,2023-01-21,1164.0,176.0,3.0,67.07,0.20,160.9680,2.0,South,Credit Card,...,Books,3.5,Not Returned,Positive,0.00,WELCOME5,3.4,unknown,no_data,NaN
21,2023-01-22,1508.0,168.0,7.0,71.74,0.07,467.0274,3.0,West,Cash,...,Clothing,1.1,Not Returned,Negative,14.02,WELCOME5,2.3,First-time customer,unknown,NaN
22,2023-01-23,1132.0,158.0,6.0,97.82,0.25,440.1900,6.0,East,Online,...,Electronics,4.1,Returned,Negative,17.35,SAVE10,0.0,unknown,value_3,NaN
23,2023-01-24,1721.0,171.0,6.0,17.22,0.21,81.6228,6.0,South,Cash,...,Books,4.9,Returned,Negative,7.54,WELCOME5,3.8,unknown,unknown,NaN
24,2023-01-25,1306.0,122.0,2.0,48.46,0.04,93.0432,7.0,West,Credit Card,...,Food,2.6,Returned,Positive,18.62,WELCOME5,4.3,unknown,no_data,NaN
25,2023-01-26,1210.0,177.0,1.0,44.00,0.19,35.6400,9.0,East,Online,...,Food,1.4,Returned,Neutral,0.00,SAVE10,1.8,Requested gift wrap,value_2,NaN
26,2023-01-27,1083.0,108.0,8.0,63.07,0.07,469.2408,6.0,North,Credit Card,...,Clothing,2.1,Returned,Neutral,0.00,FREESHIP,0.0,Requested gift wrap,unknown,NaN
27,2023-01-28,1343.0,188.0,4.0,23.52,0.14,80.9088,7.0,East,Cash,...,Electronics,2.5,Returned,Neutral,0.00,SAVE10,0.0,no_data,no_data,NaN
28,2023-01-29,1926.0,177.0,1.0,38.76,0.19,31.3956,7.0,West,Online,...,Books,2.8,Not Returned,Neutral,11.72,SAVE10,4.8,Used loyalty points,value_3,NaN
29,2023-01-30,1410.0,185.0,3.0,45.84,0.09,125.1432,4.0,East,Cash,...,Clothing,4.8,Not Returned,Positive,9.77,WELCOME5,4.6,no_data,no_data,NaN
30,2023-01-31,1309.0,160.0,7.0,35.78,0.29,177.8266,2.0,East,Cash,...,Electronics,4.6,Not Returned,Neutral,13.75,nan,2.6,no_data,no_data,NaN
31,2023-02-01,1583.0,172.0,9.0,51.44,0.07,430.5528,3.0,East,Credit Card,...,Books,4.7,Not Returned,Neutral,0.00,nan,3.7,Requested gift wrap,value_1,NaN
32,2023-02-02,1429.0,106.0,4.0,45.18,0.23,139.1544,9.0,East,Credit Card,...,Books,4.2,Not Returned,Neutral,0.00,nan,1.1,unknown,value_2,NaN
33,2023-02-03,1895.0,189.0,5.0,60.77,0.20,243.0800,2.0,West,Cash,...,Clothing,2.1,Returned,Neutral,0.00,FREESHIP,0.0,Preferred morning delivery,value_3,NaN
34,2023-02-04,1754.0,146.0,3.0,32.93,0.10,88.9110,4.0,East,Online,...,Books,4.2,Returned,Negative,15.09,WELCOME5,4.4,Preferred morning delivery,unknown,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.00,NO_COUPON,0.0,NaN,NaN,NaN

<div class="alert alert-warning">

**13. Replace NaNs Using Forward or Backward Fill**

**Write a Pandas program to replace NaNs with the value from the previous row or the next row in a given DataFrame.**

</div>

In [30]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_11311/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1331.0,160.0,9.0,13.14,0.27,86.3298,8.0,South,Cash,...,Clothing,3.0,Not Returned,Positive,6.00,SAVE10,NaN,Used loyalty points,value_2,NaN
1,2023-01-02,1576.0,160.0,5.0,47.73,0.08,219.5580,6.0,North,Cash,...,Clothing,1.7,Returned,Neutral,17.81,WELCOME5,5.0,Requested gift wrap,value_5,NaN
2,2023-01-03,1401.0,109.0,3.0,61.52,0.14,158.7216,4.0,East,Cash,...,Books,2.4,Returned,Neutral,9.39,WELCOME5,3.0,no_data,unknown,NaN
3,2023-01-04,1477.0,140.0,3.0,16.98,0.08,46.8648,5.0,North,Credit Card,...,Books,3.9,Not Returned,Negative,18.36,FREESHIP,1.4,Frequent buyer,value_5,NaN
4,2023-01-05,1646.0,137.0,8.0,91.20,0.15,620.1600,3.0,North,Cash,...,Books,1.2,Returned,Positive,NaN,nan,1.8,Requested gift wrap,value_3,NaN
5,2023-01-06,1995.0,152.0,6.0,60.51,0.24,275.9256,6.0,West,Cash,...,Books,2.8,Returned,Negative,11.75,WELCOME5,4.4,Requested gift wrap,value_3,NaN
6,2023-01-07,1860.0,173.0,1.0,46.84,0.28,33.7248,6.0,North,Online,...,Books,1.4,Returned,Positive,12.56,nan,NaN,unknown,value_4,NaN
7,2023-01-08,1124.0,179.0,9.0,12.34,0.28,79.9632,1.0,North,Credit Card,...,Books,1.1,Not Returned,Positive,18.88,WELCOME5,3.9,no_data,value_2,NaN
8,2023-01-09,1313.0,157.0,1.0,88.63,0.15,75.3355,1.0,South,Cash,...,Electronics,3.0,Returned,Neutral,6.11,WELCOME5,NaN,Requested gift wrap,value_5,NaN
9,2023-01-10,1599.0,157.0,3.0,20.11,0.16,50.6772,9.0,South,Cash,...,Food,1.1,Not Returned,Negative,NaN,SAVE10,3.5,Used loyalty points,unknown,NaN
10,2023-01-11,1785.0,157.0,2.0,21.31,0.19,34.5222,2.0,East,Credit Card,...,Food,3.9,Not Returned,Negative,NaN,SAVE10,3.3,Requested gift wrap,value_3,NaN
11,2023-01-12,1218.0,173.0,4.0,91.08,0.08,335.1744,6.0,North,Cash,...,Clothing,3.9,Not Returned,Positive,14.49,WELCOME5,1.3,unknown,no_data,NaN
12,2023-01-13,1326.0,119.0,1.0,91.98,0.06,86.4612,9.0,East,Online,...,Clothing,4.6,Not Returned,Neutral,NaN,FREESHIP,2.7,no_data,value_3,NaN
13,2023-01-14,1360.0,137.0,7.0,81.11,0.08,522.3484,2.0,South,Online,...,Books,1.4,Not Returned,Positive,6.90,FREESHIP,3.3,no_data,no_data,NaN
14,2023-01-15,1938.0,138.0,3.0,31.51,0.09,86.0223,9.0,East,Online,...,Books,4.0,Not Returned,Negative,5.94,SAVE10,3.9,Frequent buyer,no_data,NaN
15,2023-01-16,1050.0,185.0,4.0,90.82,0.10,326.9520,4.0,South,Online,...,Clothing,4.8,Not Returned,Positive,NaN,FREESHIP,NaN,no_data,unknown,NaN
16,2023-01-17,1261.0,194.0,2.0,83.25,0.11,148.1850,2.0,North,Online,...,Books,3.4,Returned,Negative,11.01,FREESHIP,NaN,Used loyalty points,no_data,NaN
17,2023-01-18,1794.0,156.0,7.0,67.77,0.06,445.9266,2.0,North,Credit Card,...,Books,1.7,Not Returned,Positive,19.72,SAVE10,4.5,First-time customer,unknown,NaN
18,2023-01-19,1802.0,168.0,3.0,48.80,0.25,109.8000,5.0,South,Credit Card,...,Electronics,2.4,Not Returned,Negative,6.52,FREESHIP,5.0,unknown,no_data,NaN
19,2023-01-20,1194.0,161.0,4.0,89.39,0.12,314.6528,4.0,North,Cash,...,Electronics,4.1,Returned,Negative,17.66,WELCOME5,NaN,Used loyalty points,value_1,NaN
20,2023-01-21,1055.0,112.0,5.0,49.43,0.02,242.2070,7.0,North,Online,...,Books,2.5,Returned,Positive,12.55,nan,1.7,Used loyalty points,no_data,NaN
21,2023-01-22,1924.0,126.0,7.0,23.50,0.17,136.5350,5.0,East,Online,...,Books,1.5,Not Returned,Positive,NaN,SAVE10,NaN,Preferred morning delivery,no_data,NaN
22,2023-01-23,1663.0,175.0,8.0,18.52,0.21,117.0464,6.0,South,Online,...,Clothing,2.1,Returned,Neutral,12.28,FREESHIP,4.3,Frequent buyer,value_1,NaN
23,2023-01-24,1197.0,119.0,7.0,82.77,0.06,544.6266,7.0,South,Online,...,Food,4.7,Returned,Neutral,6.66,SAVE10,1.3,no_data,value_3,NaN
24,2023-01-25,1788.0,131.0,6.0,92.50,0.12,488.4000,3.0,East,Online,...,Clothing,1.7,Returned,Negative,19.35,SAVE10,3.1,First-time customer,value_5,NaN
25,2023-01-26,1234.0,110.0,3.0,79.11,0.02,232.5834,2.0,West,Credit Card,...,Books,1.8,Not Returned,Negative,15.31,SAVE10,2.1,Preferred morning delivery,unknown,NaN
26,2023-01-27,1543.0,163.0,4.0,68.31,0.30,191.2680,6.0,North,Online,...,Books,4.9,Not Returned,Positive,7.05,WELCOME5,4.3,unknown,value_2,NaN
27,2023-01-28,1761.0,173.0,2.0,30.06,0.07,55.9116,9.0,West,Credit Card,...,Clothing,3.4,Returned,Negative,18.31,nan,4.7,Used loyalty points,no_data,NaN
28,2023-01-29,1241.0,133.0,3.0,16.51,0.24,37.6428,1.0,South,Online,...,Books,1.3,Returned,Positive,7.81,SAVE10,NaN,First-time customer,value_1,NaN
29,2023-01-30,1790.0,181.0,9.0,44.27,0.03,386.4771,3.0,South,Online,...,Books,2.7,Returned,Neutral,19.60,FREESHIP,1.2,no_data,value_2,NaN
30,2023-01-31,1486.0,187.0,4.0,88.11,0.22,274.9032,4.0,South,Credit Card,...,Food,4.9,Returned,Neutral,6.10,WELCOME5,1.5,Requested gift wrap,value_5,NaN
31,2023-02-01,1121.0,184.0,3.0,28.39,0.05,80.9115,1.0,North,Cash,...,Clothing,4.9,Not Returned,Positive,15.62,SAVE10,4.0,Used loyalty points,no_data,NaN
32,2023-02-02,1023.0,131.0,6.0,18.54,0.25,83.4300,2.0,East,Online,...,Electronics,3.4,Returned,Positive,15.86,nan,NaN,Used loyalty points,value_1,NaN
33,2023-02-03,1246.0,194.0,8.0,23.22,0.19,150.4656,2.0,North,Cash,...,Food,1.9,Returned,Negative,10.35,FREESHIP,NaN,unknown,value_4,NaN
34,2023-02-04,1174.0,157.0,7.0,47.81,0.00,334.6700,2.0,North,Online,...,Food,1.7,Not Returned,Positive,18.49,WELCOME5,NaN,unknown,no_data,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 13:**
</div>

In [31]:
# Write a Pandas program to replace NaNs with the value from the previous row or the next row in a given DataFrame.
pd.set_option('future.no_silent_downcasting', True)
df_bfill = df.bfill().infer_objects(copy=False)  # Backward fill
df_ffill = df.ffill().infer_objects(copy=False)  # Forward fill

display(df_bfill)
display(df_ffill)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1331.0,160.0,9.0,13.14,0.27,86.3298,8.0,South,Cash,...,Clothing,3.0,Not Returned,Positive,6.00,SAVE10,5.0,Used loyalty points,value_2,NaN
1,2023-01-02,1576.0,160.0,5.0,47.73,0.08,219.5580,6.0,North,Cash,...,Clothing,1.7,Returned,Neutral,17.81,WELCOME5,5.0,Requested gift wrap,value_5,NaN
2,2023-01-03,1401.0,109.0,3.0,61.52,0.14,158.7216,4.0,East,Cash,...,Books,2.4,Returned,Neutral,9.39,WELCOME5,3.0,no_data,unknown,NaN
3,2023-01-04,1477.0,140.0,3.0,16.98,0.08,46.8648,5.0,North,Credit Card,...,Books,3.9,Not Returned,Negative,18.36,FREESHIP,1.4,Frequent buyer,value_5,NaN
4,2023-01-05,1646.0,137.0,8.0,91.20,0.15,620.1600,3.0,North,Cash,...,Books,1.2,Returned,Positive,11.75,nan,1.8,Requested gift wrap,value_3,NaN
5,2023-01-06,1995.0,152.0,6.0,60.51,0.24,275.9256,6.0,West,Cash,...,Books,2.8,Returned,Negative,11.75,WELCOME5,4.4,Requested gift wrap,value_3,NaN
6,2023-01-07,1860.0,173.0,1.0,46.84,0.28,33.7248,6.0,North,Online,...,Books,1.4,Returned,Positive,12.56,nan,3.9,unknown,value_4,NaN
7,2023-01-08,1124.0,179.0,9.0,12.34,0.28,79.9632,1.0,North,Credit Card,...,Books,1.1,Not Returned,Positive,18.88,WELCOME5,3.9,no_data,value_2,NaN
8,2023-01-09,1313.0,157.0,1.0,88.63,0.15,75.3355,1.0,South,Cash,...,Electronics,3.0,Returned,Neutral,6.11,WELCOME5,3.5,Requested gift wrap,value_5,NaN
9,2023-01-10,1599.0,157.0,3.0,20.11,0.16,50.6772,9.0,South,Cash,...,Food,1.1,Not Returned,Negative,14.49,SAVE10,3.5,Used loyalty points,unknown,NaN
10,2023-01-11,1785.0,157.0,2.0,21.31,0.19,34.5222,2.0,East,Credit Card,...,Food,3.9,Not Returned,Negative,14.49,SAVE10,3.3,Requested gift wrap,value_3,NaN
11,2023-01-12,1218.0,173.0,4.0,91.08,0.08,335.1744,6.0,North,Cash,...,Clothing,3.9,Not Returned,Positive,14.49,WELCOME5,1.3,unknown,no_data,NaN
12,2023-01-13,1326.0,119.0,1.0,91.98,0.06,86.4612,9.0,East,Online,...,Clothing,4.6,Not Returned,Neutral,6.90,FREESHIP,2.7,no_data,value_3,NaN
13,2023-01-14,1360.0,137.0,7.0,81.11,0.08,522.3484,2.0,South,Online,...,Books,1.4,Not Returned,Positive,6.90,FREESHIP,3.3,no_data,no_data,NaN
14,2023-01-15,1938.0,138.0,3.0,31.51,0.09,86.0223,9.0,East,Online,...,Books,4.0,Not Returned,Negative,5.94,SAVE10,3.9,Frequent buyer,no_data,NaN
15,2023-01-16,1050.0,185.0,4.0,90.82,0.10,326.9520,4.0,South,Online,...,Clothing,4.8,Not Returned,Positive,11.01,FREESHIP,4.5,no_data,unknown,NaN
16,2023-01-17,1261.0,194.0,2.0,83.25,0.11,148.1850,2.0,North,Online,...,Books,3.4,Returned,Negative,11.01,FREESHIP,4.5,Used loyalty points,no_data,NaN
17,2023-01-18,1794.0,156.0,7.0,67.77,0.06,445.9266,2.0,North,Credit Card,...,Books,1.7,Not Returned,Positive,19.72,SAVE10,4.5,First-time customer,unknown,NaN
18,2023-01-19,1802.0,168.0,3.0,48.80,0.25,109.8000,5.0,South,Credit Card,...,Electronics,2.4,Not Returned,Negative,6.52,FREESHIP,5.0,unknown,no_data,NaN
19,2023-01-20,1194.0,161.0,4.0,89.39,0.12,314.6528,4.0,North,Cash,...,Electronics,4.1,Returned,Negative,17.66,WELCOME5,1.7,Used loyalty points,value_1,NaN
20,2023-01-21,1055.0,112.0,5.0,49.43,0.02,242.2070,7.0,North,Online,...,Books,2.5,Returned,Positive,12.55,nan,1.7,Used loyalty points,no_data,NaN
21,2023-01-22,1924.0,126.0,7.0,23.50,0.17,136.5350,5.0,East,Online,...,Books,1.5,Not Returned,Positive,12.28,SAVE10,4.3,Preferred morning delivery,no_data,NaN
22,2023-01-23,1663.0,175.0,8.0,18.52,0.21,117.0464,6.0,South,Online,...,Clothing,2.1,Returned,Neutral,12.28,FREESHIP,4.3,Frequent buyer,value_1,NaN
23,2023-01-24,1197.0,119.0,7.0,82.77,0.06,544.6266,7.0,South,Online,...,Food,4.7,Returned,Neutral,6.66,SAVE10,1.3,no_data,value_3,NaN
24,2023-01-25,1788.0,131.0,6.0,92.50,0.12,488.4000,3.0,East,Online,...,Clothing,1.7,Returned,Negative,19.35,SAVE10,3.1,First-time customer,value_5,NaN
25,2023-01-26,1234.0,110.0,3.0,79.11,0.02,232.5834,2.0,West,Credit Card,...,Books,1.8,Not Returned,Negative,15.31,SAVE10,2.1,Preferred morning delivery,unknown,NaN
26,2023-01-27,1543.0,163.0,4.0,68.31,0.30,191.2680,6.0,North,Online,...,Books,4.9,Not Returned,Positive,7.05,WELCOME5,4.3,unknown,value_2,NaN
27,2023-01-28,1761.0,173.0,2.0,30.06,0.07,55.9116,9.0,West,Credit Card,...,Clothing,3.4,Returned,Negative,18.31,nan,4.7,Used loyalty points,no_data,NaN
28,2023-01-29,1241.0,133.0,3.0,16.51,0.24,37.6428,1.0,South,Online,...,Books,1.3,Returned,Positive,7.81,SAVE10,1.2,First-time customer,value_1,NaN
29,2023-01-30,1790.0,181.0,9.0,44.27,0.03,386.4771,3.0,South,Online,...,Books,2.7,Returned,Neutral,19.60,FREESHIP,1.2,no_data,value_2,NaN
30,2023-01-31,1486.0,187.0,4.0,88.11,0.22,274.9032,4.0,South,Credit Card,...,Food,4.9,Returned,Neutral,6.10,WELCOME5,1.5,Requested gift wrap,value_5,NaN
31,2023-02-01,1121.0,184.0,3.0,28.39,0.05,80.9115,1.0,North,Cash,...,Clothing,4.9,Not Returned,Positive,15.62,SAVE10,4.0,Used loyalty points,no_data,NaN
32,2023-02-02,1023.0,131.0,6.0,18.54,0.25,83.4300,2.0,East,Online,...,Electronics,3.4,Returned,Positive,15.86,nan,NaN,Used loyalty points,value_1,NaN
33,2023-02-03,1246.0,194.0,8.0,23.22,0.19,150.4656,2.0,North,Cash,...,Food,1.9,Returned,Negative,10.35,FREESHIP,NaN,unknown,value_4,NaN
34,2023-02-04,1174.0,157.0,7.0,47.81,0.00,334.6700,2.0,North,Online,...,Food,1.7,Not Returned,Positive,18.49,WELCOME5,NaN,unknown,no_data,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1331.0,160.0,9.0,13.14,0.27,86.3298,8.0,South,Cash,...,Clothing,3.0,Not Returned,Positive,6.00,SAVE10,NaN,Used loyalty points,value_2,NaN
1,2023-01-02,1576.0,160.0,5.0,47.73,0.08,219.5580,6.0,North,Cash,...,Clothing,1.7,Returned,Neutral,17.81,WELCOME5,5.0,Requested gift wrap,value_5,NaN
2,2023-01-03,1401.0,109.0,3.0,61.52,0.14,158.7216,4.0,East,Cash,...,Books,2.4,Returned,Neutral,9.39,WELCOME5,3.0,no_data,unknown,NaN
3,2023-01-04,1477.0,140.0,3.0,16.98,0.08,46.8648,5.0,North,Credit Card,...,Books,3.9,Not Returned,Negative,18.36,FREESHIP,1.4,Frequent buyer,value_5,NaN
4,2023-01-05,1646.0,137.0,8.0,91.20,0.15,620.1600,3.0,North,Cash,...,Books,1.2,Returned,Positive,18.36,nan,1.8,Requested gift wrap,value_3,NaN
5,2023-01-06,1995.0,152.0,6.0,60.51,0.24,275.9256,6.0,West,Cash,...,Books,2.8,Returned,Negative,11.75,WELCOME5,4.4,Requested gift wrap,value_3,NaN
6,2023-01-07,1860.0,173.0,1.0,46.84,0.28,33.7248,6.0,North,Online,...,Books,1.4,Returned,Positive,12.56,nan,4.4,unknown,value_4,NaN
7,2023-01-08,1124.0,179.0,9.0,12.34,0.28,79.9632,1.0,North,Credit Card,...,Books,1.1,Not Returned,Positive,18.88,WELCOME5,3.9,no_data,value_2,NaN
8,2023-01-09,1313.0,157.0,1.0,88.63,0.15,75.3355,1.0,South,Cash,...,Electronics,3.0,Returned,Neutral,6.11,WELCOME5,3.9,Requested gift wrap,value_5,NaN
9,2023-01-10,1599.0,157.0,3.0,20.11,0.16,50.6772,9.0,South,Cash,...,Food,1.1,Not Returned,Negative,6.11,SAVE10,3.5,Used loyalty points,unknown,NaN
10,2023-01-11,1785.0,157.0,2.0,21.31,0.19,34.5222,2.0,East,Credit Card,...,Food,3.9,Not Returned,Negative,6.11,SAVE10,3.3,Requested gift wrap,value_3,NaN
11,2023-01-12,1218.0,173.0,4.0,91.08,0.08,335.1744,6.0,North,Cash,...,Clothing,3.9,Not Returned,Positive,14.49,WELCOME5,1.3,unknown,no_data,NaN
12,2023-01-13,1326.0,119.0,1.0,91.98,0.06,86.4612,9.0,East,Online,...,Clothing,4.6,Not Returned,Neutral,14.49,FREESHIP,2.7,no_data,value_3,NaN
13,2023-01-14,1360.0,137.0,7.0,81.11,0.08,522.3484,2.0,South,Online,...,Books,1.4,Not Returned,Positive,6.90,FREESHIP,3.3,no_data,no_data,NaN
14,2023-01-15,1938.0,138.0,3.0,31.51,0.09,86.0223,9.0,East,Online,...,Books,4.0,Not Returned,Negative,5.94,SAVE10,3.9,Frequent buyer,no_data,NaN
15,2023-01-16,1050.0,185.0,4.0,90.82,0.10,326.9520,4.0,South,Online,...,Clothing,4.8,Not Returned,Positive,5.94,FREESHIP,3.9,no_data,unknown,NaN
16,2023-01-17,1261.0,194.0,2.0,83.25,0.11,148.1850,2.0,North,Online,...,Books,3.4,Returned,Negative,11.01,FREESHIP,3.9,Used loyalty points,no_data,NaN
17,2023-01-18,1794.0,156.0,7.0,67.77,0.06,445.9266,2.0,North,Credit Card,...,Books,1.7,Not Returned,Positive,19.72,SAVE10,4.5,First-time customer,unknown,NaN
18,2023-01-19,1802.0,168.0,3.0,48.80,0.25,109.8000,5.0,South,Credit Card,...,Electronics,2.4,Not Returned,Negative,6.52,FREESHIP,5.0,unknown,no_data,NaN
19,2023-01-20,1194.0,161.0,4.0,89.39,0.12,314.6528,4.0,North,Cash,...,Electronics,4.1,Returned,Negative,17.66,WELCOME5,5.0,Used loyalty points,value_1,NaN
20,2023-01-21,1055.0,112.0,5.0,49.43,0.02,242.2070,7.0,North,Online,...,Books,2.5,Returned,Positive,12.55,nan,1.7,Used loyalty points,no_data,NaN
21,2023-01-22,1924.0,126.0,7.0,23.50,0.17,136.5350,5.0,East,Online,...,Books,1.5,Not Returned,Positive,12.55,SAVE10,1.7,Preferred morning delivery,no_data,NaN
22,2023-01-23,1663.0,175.0,8.0,18.52,0.21,117.0464,6.0,South,Online,...,Clothing,2.1,Returned,Neutral,12.28,FREESHIP,4.3,Frequent buyer,value_1,NaN
23,2023-01-24,1197.0,119.0,7.0,82.77,0.06,544.6266,7.0,South,Online,...,Food,4.7,Returned,Neutral,6.66,SAVE10,1.3,no_data,value_3,NaN
24,2023-01-25,1788.0,131.0,6.0,92.50,0.12,488.4000,3.0,East,Online,...,Clothing,1.7,Returned,Negative,19.35,SAVE10,3.1,First-time customer,value_5,NaN
25,2023-01-26,1234.0,110.0,3.0,79.11,0.02,232.5834,2.0,West,Credit Card,...,Books,1.8,Not Returned,Negative,15.31,SAVE10,2.1,Preferred morning delivery,unknown,NaN
26,2023-01-27,1543.0,163.0,4.0,68.31,0.30,191.2680,6.0,North,Online,...,Books,4.9,Not Returned,Positive,7.05,WELCOME5,4.3,unknown,value_2,NaN
27,2023-01-28,1761.0,173.0,2.0,30.06,0.07,55.9116,9.0,West,Credit Card,...,Clothing,3.4,Returned,Negative,18.31,nan,4.7,Used loyalty points,no_data,NaN
28,2023-01-29,1241.0,133.0,3.0,16.51,0.24,37.6428,1.0,South,Online,...,Books,1.3,Returned,Positive,7.81,SAVE10,4.7,First-time customer,value_1,NaN
29,2023-01-30,1790.0,181.0,9.0,44.27,0.03,386.4771,3.0,South,Online,...,Books,2.7,Returned,Neutral,19.60,FREESHIP,1.2,no_data,value_2,NaN
30,2023-01-31,1486.0,187.0,4.0,88.11,0.22,274.9032,4.0,South,Credit Card,...,Food,4.9,Returned,Neutral,6.10,WELCOME5,1.5,Requested gift wrap,value_5,NaN
31,2023-02-01,1121.0,184.0,3.0,28.39,0.05,80.9115,1.0,North,Cash,...,Clothing,4.9,Not Returned,Positive,15.62,SAVE10,4.0,Used loyalty points,no_data,NaN
32,2023-02-02,1023.0,131.0,6.0,18.54,0.25,83.4300,2.0,East,Online,...,Electronics,3.4,Returned,Positive,15.86,nan,4.0,Used loyalty points,value_1,NaN
33,2023-02-03,1246.0,194.0,8.0,23.22,0.19,150.4656,2.0,North,Cash,...,Food,1.9,Returned,Negative,10.35,FREESHIP,4.0,unknown,value_4,NaN
34,2023-02-04,1174.0,157.0,7.0,47.81,0.00,334.6700,2.0,North,Online,...,Food,1.7,Not Returned,Positive,18.49,WELCOME5,4.0,unknown,no_data,NaN
35,2023-02-04,1174.0,157.0,7.0,47.81,0.00,334.6700,2.0,North,Online,...,Food,1.7,Not Returned,Positive,18.49,WELCOME5,4.0,unknown,no_data,NaN

<div class="alert alert-warning">

**14. Replace NaNs with Median or Mean**

**Write a Pandas program to replace NaNs with median or mean of the specified columns in a given DataFrame.**

</div>

In [32]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_11311/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1475.0,178.0,2.0,42.42,0.19,68.7204,6.0,North,Credit Card,...,Electronics,4.0,Not Returned,Neutral,15.20,SAVE10,NaN,unknown,no_data,NaN
1,2023-01-02,1777.0,138.0,3.0,50.45,0.07,140.7555,3.0,East,Cash,...,Clothing,3.1,Returned,Negative,19.34,FREESHIP,2.1,no_data,value_2,NaN
2,2023-01-03,1847.0,131.0,6.0,49.29,0.10,266.1660,2.0,North,Online,...,Electronics,2.4,Returned,Positive,13.22,FREESHIP,2.7,no_data,value_2,NaN
3,2023-01-04,1008.0,170.0,2.0,67.06,0.19,108.6372,4.0,North,Credit Card,...,Clothing,1.4,Not Returned,Neutral,12.27,nan,NaN,First-time customer,value_5,NaN
4,2023-01-05,1610.0,198.0,3.0,65.46,0.26,145.3212,2.0,East,Credit Card,...,Books,3.5,Not Returned,Negative,15.28,nan,4.9,unknown,no_data,NaN
5,2023-01-06,1190.0,148.0,3.0,58.53,0.07,163.2987,7.0,North,Credit Card,...,Clothing,3.1,Not Returned,Neutral,11.63,SAVE10,1.6,no_data,unknown,NaN
6,2023-01-07,1323.0,108.0,9.0,87.51,0.02,771.8382,7.0,South,Cash,...,Clothing,2.4,Returned,Positive,11.02,nan,2.2,no_data,unknown,NaN
7,2023-01-08,1254.0,125.0,7.0,99.26,0.02,680.9236,2.0,West,Online,...,Clothing,4.5,Returned,Negative,16.68,nan,4.4,Used loyalty points,unknown,NaN
8,2023-01-09,1385.0,147.0,3.0,85.16,0.15,217.1580,8.0,East,Cash,...,Food,2.2,Not Returned,Neutral,15.22,FREESHIP,3.2,Preferred morning delivery,value_4,NaN
9,2023-01-10,1241.0,156.0,4.0,59.81,0.08,220.1008,9.0,East,Online,...,Electronics,4.0,Not Returned,Negative,14.04,nan,NaN,no_data,value_5,NaN
10,2023-01-11,1336.0,128.0,5.0,59.03,0.17,244.9745,5.0,North,Cash,...,Electronics,1.8,Returned,Neutral,5.23,nan,4.6,Used loyalty points,value_5,NaN
11,2023-01-12,1096.0,137.0,7.0,27.17,0.20,152.1520,1.0,West,Cash,...,Electronics,3.8,Not Returned,Negative,18.45,FREESHIP,1.6,Frequent buyer,value_3,NaN
12,2023-01-13,1079.0,125.0,8.0,45.61,0.25,273.6600,3.0,North,Credit Card,...,Clothing,4.0,Returned,Neutral,NaN,nan,4.1,no_data,no_data,NaN
13,2023-01-14,1852.0,111.0,5.0,82.25,0.03,398.9125,2.0,South,Credit Card,...,Food,4.1,Returned,Neutral,8.53,WELCOME5,NaN,unknown,value_4,NaN
14,2023-01-15,1243.0,133.0,6.0,22.96,0.19,111.5856,9.0,North,Cash,...,Clothing,3.0,Returned,Positive,8.54,WELCOME5,NaN,Used loyalty points,no_data,NaN
15,2023-01-16,1045.0,122.0,4.0,83.02,0.07,308.8344,8.0,North,Online,...,Food,1.0,Returned,Positive,9.72,nan,2.9,unknown,value_3,NaN
16,2023-01-17,1115.0,197.0,9.0,69.21,0.08,573.0588,1.0,North,Credit Card,...,Clothing,4.7,Not Returned,Positive,16.96,SAVE10,4.5,unknown,value_1,NaN
17,2023-01-18,1045.0,101.0,1.0,98.19,0.25,73.6425,6.0,West,Cash,...,Food,1.6,Returned,Positive,13.85,FREESHIP,3.5,unknown,value_2,NaN
18,2023-01-19,1755.0,180.0,6.0,37.40,0.12,197.4720,3.0,North,Online,...,Electronics,1.1,Returned,Neutral,19.47,nan,3.4,Requested gift wrap,no_data,NaN
19,2023-01-20,1208.0,128.0,5.0,89.85,0.28,323.4600,3.0,West,Online,...,Books,3.3,Returned,Positive,NaN,WELCOME5,3.7,Preferred morning delivery,value_2,NaN
20,2023-01-21,1915.0,184.0,6.0,92.63,0.12,489.0864,2.0,South,Credit Card,...,Electronics,2.9,Returned,Neutral,16.07,nan,4.5,First-time customer,no_data,NaN
21,2023-01-22,1952.0,164.0,1.0,55.22,0.20,44.1760,7.0,East,Online,...,Books,1.5,Not Returned,Positive,13.44,WELCOME5,NaN,unknown,value_1,NaN
22,2023-01-23,1390.0,176.0,2.0,75.89,0.25,113.8350,4.0,East,Credit Card,...,Food,1.1,Not Returned,Negative,NaN,FREESHIP,NaN,unknown,value_2,NaN
23,2023-01-24,1326.0,186.0,4.0,72.12,0.19,233.6688,3.0,South,Online,...,Clothing,3.2,Returned,Neutral,NaN,nan,1.5,Used loyalty points,value_1,NaN
24,2023-01-25,1527.0,128.0,5.0,97.29,0.02,476.7210,5.0,East,Cash,...,Books,4.3,Returned,Negative,5.03,nan,1.2,Frequent buyer,unknown,NaN
25,2023-01-26,1466.0,191.0,7.0,97.72,0.19,554.0724,6.0,North,Online,...,Food,4.5,Not Returned,Neutral,9.30,nan,2.6,unknown,value_5,NaN
26,2023-01-27,1352.0,142.0,8.0,66.67,0.20,426.6880,8.0,South,Credit Card,...,Books,1.1,Not Returned,Positive,14.02,SAVE10,4.9,Frequent buyer,value_4,NaN
27,2023-01-28,1141.0,109.0,9.0,59.40,0.19,433.0260,4.0,East,Credit Card,...,Food,3.3,Returned,Negative,NaN,nan,NaN,no_data,unknown,NaN
28,2023-01-29,1738.0,195.0,5.0,20.83,0.21,82.2785,1.0,East,Online,...,Food,4.9,Returned,Neutral,18.94,FREESHIP,2.2,Preferred morning delivery,unknown,NaN
29,2023-01-30,1032.0,143.0,1.0,70.00,0.26,51.8000,7.0,South,Cash,...,Electronics,2.8,Returned,Neutral,15.98,nan,4.4,unknown,value_2,NaN
30,2023-01-31,1823.0,156.0,2.0,88.62,0.23,136.4748,3.0,East,Online,...,Electronics,1.9,Not Returned,Positive,NaN,nan,4.3,no_data,no_data,NaN
31,2023-02-01,1248.0,163.0,7.0,41.76,0.24,222.1632,7.0,North,Online,...,Books,1.8,Not Returned,Neutral,NaN,WELCOME5,4.1,no_data,value_2,NaN
32,2023-02-02,1383.0,174.0,9.0,65.21,0.26,434.2986,2.0,East,Cash,...,Books,2.1,Not Returned,Positive,11.82,FREESHIP,NaN,no_data,no_data,NaN
33,2023-02-03,1461.0,168.0,1.0,19.15,0.12,16.8520,8.0,East,Online,...,Clothing,3.7,Not Returned,Positive,NaN,SAVE10,2.5,no_data,no_data,NaN
34,2023-02-04,1573.0,175.0,1.0,23.60,0.04,22.6560,6.0,South,Cash,...,Food,2.6,Not Returned,Positive,NaN,SAVE10,NaN,unknown,value_4,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 14:**
</div>

In [33]:
df.fillna({
    'delivery_rating': df['delivery_rating'].median(),
    'shipping_cost': df['shipping_cost'].mean()
}, inplace=True)

df

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1475.0,178.0,2.0,42.42,0.19,68.7204,6.0,North,Credit Card,...,Electronics,4.0,Not Returned,Neutral,15.200000,SAVE10,3.4,unknown,no_data,NaN
1,2023-01-02,1777.0,138.0,3.0,50.45,0.07,140.7555,3.0,East,Cash,...,Clothing,3.1,Returned,Negative,19.340000,FREESHIP,2.1,no_data,value_2,NaN
2,2023-01-03,1847.0,131.0,6.0,49.29,0.10,266.1660,2.0,North,Online,...,Electronics,2.4,Returned,Positive,13.220000,FREESHIP,2.7,no_data,value_2,NaN
3,2023-01-04,1008.0,170.0,2.0,67.06,0.19,108.6372,4.0,North,Credit Card,...,Clothing,1.4,Not Returned,Neutral,12.270000,nan,3.4,First-time customer,value_5,NaN
4,2023-01-05,1610.0,198.0,3.0,65.46,0.26,145.3212,2.0,East,Credit Card,...,Books,3.5,Not Returned,Negative,15.280000,nan,4.9,unknown,no_data,NaN
5,2023-01-06,1190.0,148.0,3.0,58.53,0.07,163.2987,7.0,North,Credit Card,...,Clothing,3.1,Not Returned,Neutral,11.630000,SAVE10,1.6,no_data,unknown,NaN
6,2023-01-07,1323.0,108.0,9.0,87.51,0.02,771.8382,7.0,South,Cash,...,Clothing,2.4,Returned,Positive,11.020000,nan,2.2,no_data,unknown,NaN
7,2023-01-08,1254.0,125.0,7.0,99.26,0.02,680.9236,2.0,West,Online,...,Clothing,4.5,Returned,Negative,16.680000,nan,4.4,Used loyalty points,unknown,NaN
8,2023-01-09,1385.0,147.0,3.0,85.16,0.15,217.1580,8.0,East,Cash,...,Food,2.2,Not Returned,Neutral,15.220000,FREESHIP,3.2,Preferred morning delivery,value_4,NaN
9,2023-01-10,1241.0,156.0,4.0,59.81,0.08,220.1008,9.0,East,Online,...,Electronics,4.0,Not Returned,Negative,14.040000,nan,3.4,no_data,value_5,NaN
10,2023-01-11,1336.0,128.0,5.0,59.03,0.17,244.9745,5.0,North,Cash,...,Electronics,1.8,Returned,Neutral,5.230000,nan,4.6,Used loyalty points,value_5,NaN
11,2023-01-12,1096.0,137.0,7.0,27.17,0.20,152.1520,1.0,West,Cash,...,Electronics,3.8,Not Returned,Negative,18.450000,FREESHIP,1.6,Frequent buyer,value_3,NaN
12,2023-01-13,1079.0,125.0,8.0,45.61,0.25,273.6600,3.0,North,Credit Card,...,Clothing,4.0,Returned,Neutral,13.432692,nan,4.1,no_data,no_data,NaN
13,2023-01-14,1852.0,111.0,5.0,82.25,0.03,398.9125,2.0,South,Credit Card,...,Food,4.1,Returned,Neutral,8.530000,WELCOME5,3.4,unknown,value_4,NaN
14,2023-01-15,1243.0,133.0,6.0,22.96,0.19,111.5856,9.0,North,Cash,...,Clothing,3.0,Returned,Positive,8.540000,WELCOME5,3.4,Used loyalty points,no_data,NaN
15,2023-01-16,1045.0,122.0,4.0,83.02,0.07,308.8344,8.0,North,Online,...,Food,1.0,Returned,Positive,9.720000,nan,2.9,unknown,value_3,NaN
16,2023-01-17,1115.0,197.0,9.0,69.21,0.08,573.0588,1.0,North,Credit Card,...,Clothing,4.7,Not Returned,Positive,16.960000,SAVE10,4.5,unknown,value_1,NaN
17,2023-01-18,1045.0,101.0,1.0,98.19,0.25,73.6425,6.0,West,Cash,...,Food,1.6,Returned,Positive,13.850000,FREESHIP,3.5,unknown,value_2,NaN
18,2023-01-19,1755.0,180.0,6.0,37.40,0.12,197.4720,3.0,North,Online,...,Electronics,1.1,Returned,Neutral,19.470000,nan,3.4,Requested gift wrap,no_data,NaN
19,2023-01-20,1208.0,128.0,5.0,89.85,0.28,323.4600,3.0,West,Online,...,Books,3.3,Returned,Positive,13.432692,WELCOME5,3.7,Preferred morning delivery,value_2,NaN
20,2023-01-21,1915.0,184.0,6.0,92.63,0.12,489.0864,2.0,South,Credit Card,...,Electronics,2.9,Returned,Neutral,16.070000,nan,4.5,First-time customer,no_data,NaN
21,2023-01-22,1952.0,164.0,1.0,55.22,0.20,44.1760,7.0,East,Online,...,Books,1.5,Not Returned,Positive,13.440000,WELCOME5,3.4,unknown,value_1,NaN
22,2023-01-23,1390.0,176.0,2.0,75.89,0.25,113.8350,4.0,East,Credit Card,...,Food,1.1,Not Returned,Negative,13.432692,FREESHIP,3.4,unknown,value_2,NaN
23,2023-01-24,1326.0,186.0,4.0,72.12,0.19,233.6688,3.0,South,Online,...,Clothing,3.2,Returned,Neutral,13.432692,nan,1.5,Used loyalty points,value_1,NaN
24,2023-01-25,1527.0,128.0,5.0,97.29,0.02,476.7210,5.0,East,Cash,...,Books,4.3,Returned,Negative,5.030000,nan,1.2,Frequent buyer,unknown,NaN
25,2023-01-26,1466.0,191.0,7.0,97.72,0.19,554.0724,6.0,North,Online,...,Food,4.5,Not Returned,Neutral,9.300000,nan,2.6,unknown,value_5,NaN
26,2023-01-27,1352.0,142.0,8.0,66.67,0.20,426.6880,8.0,South,Credit Card,...,Books,1.1,Not Returned,Positive,14.020000,SAVE10,4.9,Frequent buyer,value_4,NaN
27,2023-01-28,1141.0,109.0,9.0,59.40,0.19,433.0260,4.0,East,Credit Card,...,Food,3.3,Returned,Negative,13.432692,nan,3.4,no_data,unknown,NaN
28,2023-01-29,1738.0,195.0,5.0,20.83,0.21,82.2785,1.0,East,Online,...,Food,4.9,Returned,Neutral,18.940000,FREESHIP,2.2,Preferred morning delivery,unknown,NaN
29,2023-01-30,1032.0,143.0,1.0,70.00,0.26,51.8000,7.0,South,Cash,...,Electronics,2.8,Returned,Neutral,15.980000,nan,4.4,unknown,value_2,NaN
30,2023-01-31,1823.0,156.0,2.0,88.62,0.23,136.4748,3.0,East,Online,...,Electronics,1.9,Not Returned,Positive,13.432692,nan,4.3,no_data,no_data,NaN
31,2023-02-01,1248.0,163.0,7.0,41.76,0.24,222.1632,7.0,North,Online,...,Books,1.8,Not Returned,Neutral,13.432692,WELCOME5,4.1,no_data,value_2,NaN
32,2023-02-02,1383.0,174.0,9.0,65.21,0.26,434.2986,2.0,East,Cash,...,Books,2.1,Not Returned,Positive,11.820000,FREESHIP,3.4,no_data,no_data,NaN
33,2023-02-03,1461.0,168.0,1.0,19.15,0.12,16.8520,8.0,East,Online,...,Clothing,3.7,Not Returned,Positive,13.432692,SAVE10,2.5,no_data,no_data,NaN
34,2023-02-04,1573.0,175.0,1.0,23.60,0.04,22.6560,6.0,South,Cash,...,Food,2.6,Not Returned,Positive,13.432692,SAVE10,3.4,unknown,value_4,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,13.432692,NaN,3.4,NaN,NaN,NaN

<div class="alert alert-warning">

**15. Interpolate Missing Values Using Linear Method**

**Write a Pandas program to interpolate the missing values using the Linear Interpolation method in a given DataFrame.**

</div>

In [34]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_11311/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1911.0,108.0,2.0,29.29,0.19,47.4498,5.0,South,Online,...,Electronics,3.8,Not Returned,Negative,12.07,FREESHIP,3.5,Used loyalty points,unknown,NaN
1,2023-01-02,1454.0,125.0,8.0,97.32,0.12,685.1328,2.0,East,Credit Card,...,Electronics,4.7,Returned,Positive,NaN,nan,2.7,no_data,no_data,NaN
2,2023-01-03,1499.0,160.0,7.0,58.20,0.20,325.9200,5.0,North,Cash,...,Electronics,4.7,Not Returned,Negative,NaN,WELCOME5,3.8,Used loyalty points,value_4,NaN
3,2023-01-04,1735.0,142.0,9.0,54.46,0.17,406.8162,9.0,North,Cash,...,Books,2.8,Returned,Negative,NaN,WELCOME5,3.7,Requested gift wrap,value_1,NaN
4,2023-01-05,1250.0,147.0,2.0,38.38,0.17,63.7108,2.0,East,Cash,...,Food,4.8,Returned,Neutral,13.65,nan,4.0,Used loyalty points,value_3,NaN
5,2023-01-06,1657.0,167.0,5.0,23.30,0.24,88.5400,8.0,West,Credit Card,...,Electronics,4.0,Not Returned,Neutral,13.16,nan,4.0,Used loyalty points,value_4,NaN
6,2023-01-07,1762.0,158.0,9.0,80.53,0.12,637.7976,4.0,North,Online,...,Clothing,2.9,Returned,Negative,NaN,SAVE10,2.6,unknown,value_2,NaN
7,2023-01-08,1597.0,114.0,3.0,60.99,0.11,162.8433,5.0,East,Online,...,Clothing,4.6,Not Returned,Negative,NaN,nan,2.3,unknown,value_5,NaN
8,2023-01-09,1836.0,136.0,2.0,51.61,0.10,92.8980,4.0,North,Cash,...,Electronics,4.3,Returned,Negative,16.31,FREESHIP,2.8,unknown,value_3,NaN
9,2023-01-10,1477.0,143.0,5.0,44.82,0.10,201.6900,6.0,East,Online,...,Food,2.6,Returned,Negative,10.02,SAVE10,1.4,unknown,no_data,NaN
10,2023-01-11,1780.0,121.0,4.0,83.16,0.26,246.1536,8.0,East,Cash,...,Books,4.0,Returned,Neutral,13.45,nan,4.6,Used loyalty points,unknown,NaN
11,2023-01-12,1265.0,194.0,8.0,79.41,0.06,597.1632,9.0,West,Credit Card,...,Electronics,2.2,Returned,Neutral,7.76,nan,NaN,Preferred morning delivery,value_4,NaN
12,2023-01-13,1824.0,136.0,9.0,64.25,0.02,566.6850,8.0,North,Online,...,Clothing,3.1,Not Returned,Positive,15.74,WELCOME5,1.7,Preferred morning delivery,value_1,NaN
13,2023-01-14,1793.0,124.0,3.0,35.82,0.25,80.5950,1.0,West,Cash,...,Books,2.5,Returned,Neutral,6.29,FREESHIP,NaN,no_data,unknown,NaN
14,2023-01-15,1669.0,124.0,6.0,32.49,0.08,179.3448,1.0,South,Cash,...,Clothing,1.8,Returned,Neutral,NaN,nan,4.1,Frequent buyer,no_data,NaN
15,2023-01-16,1123.0,103.0,6.0,65.07,0.20,312.3360,4.0,South,Cash,...,Electronics,2.2,Returned,Positive,19.76,WELCOME5,3.3,unknown,no_data,NaN
16,2023-01-17,1212.0,195.0,7.0,33.82,0.19,191.7594,7.0,South,Cash,...,Books,3.0,Not Returned,Neutral,NaN,SAVE10,1.2,First-time customer,no_data,NaN
17,2023-01-18,1029.0,171.0,6.0,85.95,0.20,412.5600,3.0,West,Credit Card,...,Clothing,3.4,Returned,Negative,5.53,SAVE10,1.5,unknown,value_2,NaN
18,2023-01-19,1405.0,140.0,7.0,97.33,0.24,517.7956,5.0,North,Online,...,Electronics,2.9,Not Returned,Negative,6.37,nan,1.6,Preferred morning delivery,value_1,NaN
19,2023-01-20,1545.0,189.0,4.0,46.10,0.17,153.0520,3.0,West,Online,...,Clothing,3.3,Returned,Positive,NaN,nan,NaN,Preferred morning delivery,no_data,NaN
20,2023-01-21,1886.0,138.0,6.0,74.80,0.06,421.8720,5.0,West,Cash,...,Electronics,2.2,Not Returned,Positive,11.28,SAVE10,1.9,Requested gift wrap,value_1,NaN
21,2023-01-22,1919.0,128.0,6.0,46.77,0.18,230.1084,7.0,South,Credit Card,...,Food,3.4,Returned,Positive,9.58,nan,1.7,unknown,no_data,NaN
22,2023-01-23,1380.0,150.0,6.0,74.59,0.13,389.3598,8.0,East,Online,...,Food,1.1,Returned,Negative,14.69,nan,3.5,Frequent buyer,no_data,NaN
23,2023-01-24,1007.0,185.0,9.0,58.60,0.22,411.3720,6.0,North,Credit Card,...,Electronics,2.4,Not Returned,Neutral,9.62,nan,2.7,Frequent buyer,unknown,NaN
24,2023-01-25,1209.0,168.0,3.0,46.82,0.22,109.5588,5.0,South,Online,...,Electronics,3.7,Not Returned,Neutral,19.71,FREESHIP,3.8,Preferred morning delivery,value_3,NaN
25,2023-01-26,1724.0,192.0,3.0,28.66,0.05,81.6810,4.0,East,Cash,...,Books,4.2,Returned,Positive,NaN,nan,3.9,Used loyalty points,unknown,NaN
26,2023-01-27,1276.0,159.0,9.0,69.08,0.05,590.6340,3.0,East,Online,...,Books,3.8,Not Returned,Neutral,16.82,nan,NaN,no_data,unknown,NaN
27,2023-01-28,1472.0,170.0,6.0,37.53,0.25,168.8850,4.0,South,Cash,...,Electronics,4.8,Not Returned,Neutral,19.95,WELCOME5,2.9,no_data,value_1,NaN
28,2023-01-29,1247.0,127.0,9.0,99.44,0.17,742.8168,3.0,North,Credit Card,...,Books,4.4,Returned,Negative,11.94,nan,NaN,Requested gift wrap,value_4,NaN
29,2023-01-30,1980.0,185.0,7.0,31.60,0.20,176.9600,2.0,West,Online,...,Electronics,1.4,Returned,Neutral,13.13,nan,NaN,Used loyalty points,unknown,NaN
30,2023-01-31,1400.0,142.0,1.0,23.77,0.17,19.7291,4.0,South,Online,...,Electronics,4.8,Not Returned,Negative,NaN,nan,NaN,no_data,value_4,NaN
31,2023-02-01,1221.0,135.0,1.0,42.99,0.15,36.5415,5.0,South,Online,...,Books,3.7,Not Returned,Positive,15.51,SAVE10,NaN,Preferred morning delivery,unknown,NaN
32,2023-02-02,1856.0,184.0,5.0,90.05,0.06,423.2350,7.0,South,Cash,...,Clothing,3.9,Returned,Neutral,NaN,nan,3.1,unknown,unknown,NaN
33,2023-02-03,1526.0,157.0,6.0,84.58,0.28,365.3856,6.0,West,Online,...,Electronics,1.8,Not Returned,Negative,15.52,WELCOME5,4.4,unknown,no_data,NaN
34,2023-02-04,1263.0,192.0,8.0,16.93,0.21,106.9976,5.0,South,Cash,...,Clothing,3.1,Not Returned,Positive,NaN,nan,NaN,no_data,unknown,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 15:**
</div>

In [35]:
df['shipping_cost_interpolated'] = df['shipping_cost'].interpolate(method='linear', direction='forward')
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column,shipping_cost_interpolated
0,2023-01-01,1911.0,108.0,2.0,29.29,0.19,47.4498,5.0,South,Online,...,3.8,Not Returned,Negative,12.07,FREESHIP,3.5,Used loyalty points,unknown,NaN,12.070
1,2023-01-02,1454.0,125.0,8.0,97.32,0.12,685.1328,2.0,East,Credit Card,...,4.7,Returned,Positive,NaN,nan,2.7,no_data,no_data,NaN,12.465
2,2023-01-03,1499.0,160.0,7.0,58.20,0.20,325.9200,5.0,North,Cash,...,4.7,Not Returned,Negative,NaN,WELCOME5,3.8,Used loyalty points,value_4,NaN,12.860
3,2023-01-04,1735.0,142.0,9.0,54.46,0.17,406.8162,9.0,North,Cash,...,2.8,Returned,Negative,NaN,WELCOME5,3.7,Requested gift wrap,value_1,NaN,13.255
4,2023-01-05,1250.0,147.0,2.0,38.38,0.17,63.7108,2.0,East,Cash,...,4.8,Returned,Neutral,13.65,nan,4.0,Used loyalty points,value_3,NaN,13.650
5,2023-01-06,1657.0,167.0,5.0,23.30,0.24,88.5400,8.0,West,Credit Card,...,4.0,Not Returned,Neutral,13.16,nan,4.0,Used loyalty points,value_4,NaN,13.160
6,2023-01-07,1762.0,158.0,9.0,80.53,0.12,637.7976,4.0,North,Online,...,2.9,Returned,Negative,NaN,SAVE10,2.6,unknown,value_2,NaN,14.210
7,2023-01-08,1597.0,114.0,3.0,60.99,0.11,162.8433,5.0,East,Online,...,4.6,Not Returned,Negative,NaN,nan,2.3,unknown,value_5,NaN,15.260
8,2023-01-09,1836.0,136.0,2.0,51.61,0.10,92.8980,4.0,North,Cash,...,4.3,Returned,Negative,16.31,FREESHIP,2.8,unknown,value_3,NaN,16.310
9,2023-01-10,1477.0,143.0,5.0,44.82,0.10,201.6900,6.0,East,Online,...,2.6,Returned,Negative,10.02,SAVE10,1.4,unknown,no_data,NaN,10.020
10,2023-01-11,1780.0,121.0,4.0,83.16,0.26,246.1536,8.0,East,Cash,...,4.0,Returned,Neutral,13.45,nan,4.6,Used loyalty points,unknown,NaN,13.450
11,2023-01-12,1265.0,194.0,8.0,79.41,0.06,597.1632,9.0,West,Credit Card,...,2.2,Returned,Neutral,7.76,nan,NaN,Preferred morning delivery,value_4,NaN,7.760
12,2023-01-13,1824.0,136.0,9.0,64.25,0.02,566.6850,8.0,North,Online,...,3.1,Not Returned,Positive,15.74,WELCOME5,1.7,Preferred morning delivery,value_1,NaN,15.740
13,2023-01-14,1793.0,124.0,3.0,35.82,0.25,80.5950,1.0,West,Cash,...,2.5,Returned,Neutral,6.29,FREESHIP,NaN,no_data,unknown,NaN,6.290
14,2023-01-15,1669.0,124.0,6.0,32.49,0.08,179.3448,1.0,South,Cash,...,1.8,Returned,Neutral,NaN,nan,4.1,Frequent buyer,no_data,NaN,13.025
15,2023-01-16,1123.0,103.0,6.0,65.07,0.20,312.3360,4.0,South,Cash,...,2.2,Returned,Positive,19.76,WELCOME5,3.3,unknown,no_data,NaN,19.760
16,2023-01-17,1212.0,195.0,7.0,33.82,0.19,191.7594,7.0,South,Cash,...,3.0,Not Returned,Neutral,NaN,SAVE10,1.2,First-time customer,no_data,NaN,12.645
17,2023-01-18,1029.0,171.0,6.0,85.95,0.20,412.5600,3.0,West,Credit Card,...,3.4,Returned,Negative,5.53,SAVE10,1.5,unknown,value_2,NaN,5.530
18,2023-01-19,1405.0,140.0,7.0,97.33,0.24,517.7956,5.0,North,Online,...,2.9,Not Returned,Negative,6.37,nan,1.6,Preferred morning delivery,value_1,NaN,6.370
19,2023-01-20,1545.0,189.0,4.0,46.10,0.17,153.0520,3.0,West,Online,...,3.3,Returned,Positive,NaN,nan,NaN,Preferred morning delivery,no_data,NaN,8.825
20,2023-01-21,1886.0,138.0,6.0,74.80,0.06,421.8720,5.0,West,Cash,...,2.2,Not Returned,Positive,11.28,SAVE10,1.9,Requested gift wrap,value_1,NaN,11.280
21,2023-01-22,1919.0,128.0,6.0,46.77,0.18,230.1084,7.0,South,Credit Card,...,3.4,Returned,Positive,9.58,nan,1.7,unknown,no_data,NaN,9.580
22,2023-01-23,1380.0,150.0,6.0,74.59,0.13,389.3598,8.0,East,Online,...,1.1,Returned,Negative,14.69,nan,3.5,Frequent buyer,no_data,NaN,14.690
23,2023-01-24,1007.0,185.0,9.0,58.60,0.22,411.3720,6.0,North,Credit Card,...,2.4,Not Returned,Neutral,9.62,nan,2.7,Frequent buyer,unknown,NaN,9.620
24,2023-01-25,1209.0,168.0,3.0,46.82,0.22,109.5588,5.0,South,Online,...,3.7,Not Returned,Neutral,19.71,FREESHIP,3.8,Preferred morning delivery,value_3,NaN,19.710
25,2023-01-26,1724.0,192.0,3.0,28.66,0.05,81.6810,4.0,East,Cash,...,4.2,Returned,Positive,NaN,nan,3.9,Used loyalty points,unknown,NaN,18.265
26,2023-01-27,1276.0,159.0,9.0,69.08,0.05,590.6340,3.0,East,Online,...,3.8,Not Returned,Neutral,16.82,nan,NaN,no_data,unknown,NaN,16.820
27,2023-01-28,1472.0,170.0,6.0,37.53,0.25,168.8850,4.0,South,Cash,...,4.8,Not Returned,Neutral,19.95,WELCOME5,2.9,no_data,value_1,NaN,19.950
28,2023-01-29,1247.0,127.0,9.0,99.44,0.17,742.8168,3.0,North,Credit Card,...,4.4,Returned,Negative,11.94,nan,NaN,Requested gift wrap,value_4,NaN,11.940
29,2023-01-30,1980.0,185.0,7.0,31.60,0.20,176.9600,2.0,West,Online,...,1.4,Returned,Neutral,13.13,nan,NaN,Used loyalty points,unknown,NaN,13.130
30,2023-01-31,1400.0,142.0,1.0,23.77,0.17,19.7291,4.0,South,Online,...,4.8,Not Returned,Negative,NaN,nan,NaN,no_data,value_4,NaN,14.320
31,2023-02-01,1221.0,135.0,1.0,42.99,0.15,36.5415,5.0,South,Online,...,3.7,Not Returned,Positive,15.51,SAVE10,NaN,Preferred morning delivery,unknown,NaN,15.510
32,2023-02-02,1856.0,184.0,5.0,90.05,0.06,423.2350,7.0,South,Cash,...,3.9,Returned,Neutral,NaN,nan,3.1,unknown,unknown,NaN,15.515
33,2023-02-03,1526.0,157.0,6.0,84.58,0.28,365.3856,6.0,West,Online,...,1.8,Not Returned,Negative,15.52,WELCOME5,4.4,unknown,no_data,NaN,15.520
34,2023-02-04,1263.0,192.0,8.0,16.93,0.21,106.9976,5.0,South,Cash,...,3.1,Not Returned,Positive,NaN,nan,NaN,no_data,unknown,NaN,15.520
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.520

<div class="alert alert-warning">

**16. Count Missing Values in a Specified Column**

**Write a Pandas program to count the number of missing values of a specified column in a given DataFrame.**

</div>

In [36]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_11311/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1088.0,102.0,8.0,47.87,0.08,352.3232,1.0,South,Cash,...,Electronics,2.0,Returned,Negative,7.31,nan,4.8,First-time customer,no_data,NaN
1,2023-01-02,1487.0,130.0,6.0,35.79,0.19,173.9394,4.0,North,Credit Card,...,Electronics,2.0,Not Returned,Neutral,NaN,nan,2.8,Requested gift wrap,value_4,NaN
2,2023-01-03,1107.0,160.0,6.0,21.76,0.24,99.2256,9.0,West,Online,...,Books,1.6,Not Returned,Negative,14.53,FREESHIP,1.1,Frequent buyer,no_data,NaN
3,2023-01-04,1340.0,120.0,2.0,81.73,0.13,142.2102,5.0,North,Online,...,Clothing,2.2,Not Returned,Neutral,9.73,nan,1.4,Preferred morning delivery,unknown,NaN
4,2023-01-05,1214.0,183.0,4.0,65.72,0.23,202.4176,1.0,East,Online,...,Clothing,3.7,Not Returned,Neutral,8.06,nan,1.4,unknown,value_5,NaN
5,2023-01-06,1883.0,127.0,6.0,37.80,0.06,213.1920,2.0,North,Online,...,Electronics,2.5,Not Returned,Positive,10.65,nan,3.4,Requested gift wrap,value_4,NaN
6,2023-01-07,1298.0,164.0,2.0,97.19,0.20,155.5040,1.0,North,Online,...,Electronics,1.3,Not Returned,Neutral,19.14,nan,3.7,Requested gift wrap,unknown,NaN
7,2023-01-08,1912.0,123.0,6.0,74.05,0.21,350.9970,7.0,North,Credit Card,...,Books,3.3,Not Returned,Neutral,NaN,WELCOME5,3.7,Used loyalty points,value_1,NaN
8,2023-01-09,1006.0,118.0,5.0,67.13,0.06,315.5110,7.0,South,Cash,...,Electronics,3.3,Not Returned,Negative,17.41,nan,2.0,unknown,value_3,NaN
9,2023-01-10,1429.0,156.0,9.0,19.00,0.01,169.2900,3.0,West,Credit Card,...,Books,2.2,Returned,Neutral,10.60,SAVE10,2.3,unknown,value_5,NaN
10,2023-01-11,1899.0,105.0,4.0,21.44,0.30,60.0320,8.0,South,Credit Card,...,Books,1.7,Not Returned,Neutral,15.10,nan,NaN,unknown,unknown,NaN
11,2023-01-12,1335.0,188.0,9.0,88.46,0.22,620.9892,3.0,North,Credit Card,...,Food,3.1,Returned,Neutral,12.42,WELCOME5,2.3,unknown,unknown,NaN
12,2023-01-13,1999.0,116.0,2.0,56.00,0.29,79.5200,2.0,South,Online,...,Books,4.7,Returned,Negative,NaN,nan,3.0,Preferred morning delivery,value_4,NaN
13,2023-01-14,1751.0,179.0,9.0,63.61,0.11,509.5161,5.0,North,Cash,...,Clothing,4.1,Returned,Negative,12.24,nan,3.0,Frequent buyer,value_2,NaN
14,2023-01-15,1336.0,102.0,3.0,15.75,0.18,38.7450,2.0,South,Online,...,Electronics,3.9,Not Returned,Negative,NaN,nan,2.2,no_data,no_data,NaN
15,2023-01-16,1095.0,131.0,4.0,40.07,0.24,121.8128,2.0,South,Cash,...,Electronics,1.7,Returned,Positive,NaN,nan,1.8,unknown,no_data,NaN
16,2023-01-17,1844.0,154.0,1.0,69.79,0.10,62.8110,4.0,West,Online,...,Electronics,4.3,Returned,Negative,14.96,WELCOME5,3.0,unknown,value_5,NaN
17,2023-01-18,1578.0,173.0,3.0,88.75,0.21,210.3375,9.0,North,Online,...,Food,1.2,Returned,Positive,15.47,SAVE10,NaN,Used loyalty points,value_4,NaN
18,2023-01-19,1343.0,190.0,7.0,76.90,0.05,511.3850,7.0,South,Cash,...,Books,3.3,Not Returned,Neutral,NaN,FREESHIP,2.0,Preferred morning delivery,unknown,NaN
19,2023-01-20,1213.0,138.0,3.0,99.70,0.08,275.1720,7.0,South,Credit Card,...,Books,1.2,Not Returned,Neutral,14.10,nan,4.2,First-time customer,value_1,NaN
20,2023-01-21,1768.0,147.0,2.0,67.85,0.22,105.8460,8.0,West,Cash,...,Electronics,2.9,Not Returned,Neutral,NaN,SAVE10,2.5,Preferred morning delivery,value_4,NaN
21,2023-01-22,1283.0,120.0,3.0,70.21,0.07,195.8859,8.0,East,Online,...,Food,3.7,Returned,Neutral,6.24,nan,4.7,Preferred morning delivery,unknown,NaN
22,2023-01-23,1113.0,153.0,6.0,47.34,0.15,241.4340,3.0,South,Credit Card,...,Electronics,4.1,Returned,Negative,19.86,SAVE10,1.3,Used loyalty points,value_1,NaN
23,2023-01-24,1801.0,177.0,1.0,56.10,0.15,47.6850,7.0,West,Cash,...,Books,4.1,Returned,Neutral,6.73,SAVE10,NaN,Preferred morning delivery,unknown,NaN
24,2023-01-25,1771.0,193.0,5.0,98.77,0.12,434.5880,4.0,South,Online,...,Food,4.3,Returned,Neutral,NaN,WELCOME5,1.8,First-time customer,value_3,NaN
25,2023-01-26,1428.0,149.0,1.0,81.05,0.18,66.4610,5.0,North,Credit Card,...,Clothing,4.6,Not Returned,Neutral,NaN,nan,NaN,no_data,value_2,NaN
26,2023-01-27,1879.0,151.0,4.0,38.24,0.20,122.3680,4.0,South,Online,...,Electronics,3.8,Returned,Positive,16.01,FREESHIP,NaN,no_data,value_5,NaN
27,2023-01-28,1026.0,103.0,6.0,26.59,0.29,113.2734,3.0,North,Online,...,Books,1.4,Not Returned,Positive,5.26,WELCOME5,NaN,Used loyalty points,no_data,NaN
28,2023-01-29,1565.0,152.0,7.0,61.18,0.28,308.3472,9.0,West,Credit Card,...,Books,1.7,Not Returned,Positive,14.32,nan,NaN,Requested gift wrap,value_3,NaN
29,2023-01-30,1048.0,155.0,2.0,99.42,0.20,159.0720,6.0,South,Credit Card,...,Electronics,1.4,Returned,Neutral,10.74,nan,3.0,Frequent buyer,value_3,NaN
30,2023-01-31,1407.0,142.0,7.0,73.68,0.22,402.2928,4.0,South,Online,...,Electronics,4.6,Not Returned,Positive,15.72,nan,4.7,Frequent buyer,value_4,NaN
31,2023-02-01,1140.0,107.0,9.0,41.98,0.08,347.5944,7.0,West,Cash,...,Electronics,1.0,Returned,Neutral,6.34,SAVE10,2.9,unknown,unknown,NaN
32,2023-02-02,1132.0,150.0,7.0,36.39,0.30,178.3110,2.0,West,Credit Card,...,Food,2.5,Not Returned,Negative,NaN,WELCOME5,1.2,unknown,value_2,NaN
33,2023-02-03,1044.0,134.0,4.0,78.91,0.09,287.2324,1.0,East,Cash,...,Books,4.5,Returned,Positive,NaN,nan,3.8,Used loyalty points,unknown,NaN
34,2023-02-04,1703.0,140.0,4.0,23.14,0.05,87.9320,4.0,North,Online,...,Books,1.8,Returned,Positive,NaN,nan,3.8,Preferred morning delivery,no_data,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 16:**
</div>

In [37]:
# ordered by number of missing values list of columns with missing values
import pandas as pd
import numpy as np
missing_columns = df.columns[df.isnull().any()].tolist()
missing_columns.sort(key=lambda col: df[col].isnull().sum(), reverse=True)

for col in missing_columns:
    print(f"Column {col:<20} has {df[col].isnull().sum()} missing values.")

Column all_nan_column       has 36 missing values.
Column shipping_cost        has 13 missing values.
Column delivery_rating      has 8 missing values.
Column date                 has 1 missing values.
Column customer_id          has 1 missing values.
Column product_id           has 1 missing values.
Column quantity             has 1 missing values.
Column price                has 1 missing values.
Column discount             has 1 missing values.
Column revenue              has 1 missing values.
Column store_id             has 1 missing values.
Column region               has 1 missing values.
Column payment_method       has 1 missing values.
Column is_member            has 1 missing values.
Column delivery_days        has 1 missing values.
Column customer_age         has 1 missing values.
Column gender               has 1 missing values.
Column product_category     has 1 missing values.
Column rating               has 1 missing values.
Column return_status        has 1 missing values.
Column feedback             has 1 missing values.
Column coupon_code          has 1 missing values.
Column customer_note        has 1 missing values.
Column customer_values      has 1 missing values.

<div class="alert alert-warning">

**17. Count Missing Values in the Entire DataFrame**

**Write a Pandas program to count the missing values in a given DataFrame.**

</div>

In [38]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_11311/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1600.0,110.0,8.0,77.57,0.01,614.3544,3.0,South,Cash,...,Books,2.1,Not Returned,Neutral,13.38,WELCOME5,1.3,First-time customer,no_data,NaN
1,2023-01-02,1810.0,179.0,2.0,32.35,0.06,60.8180,8.0,West,Cash,...,Clothing,1.2,Returned,Negative,12.31,WELCOME5,1.5,no_data,value_3,NaN
2,2023-01-03,1546.0,108.0,7.0,57.97,0.23,312.4583,7.0,South,Credit Card,...,Electronics,2.7,Returned,Negative,13.32,nan,4.1,Preferred morning delivery,value_4,NaN
3,2023-01-04,1864.0,169.0,6.0,16.01,0.26,71.0844,4.0,East,Credit Card,...,Clothing,1.4,Not Returned,Positive,NaN,FREESHIP,NaN,unknown,value_2,NaN
4,2023-01-05,1509.0,119.0,7.0,90.60,0.01,627.8580,1.0,South,Online,...,Clothing,2.7,Returned,Negative,16.29,WELCOME5,NaN,First-time customer,value_4,NaN
5,2023-01-06,1784.0,139.0,9.0,24.30,0.20,174.9600,6.0,East,Credit Card,...,Clothing,3.3,Not Returned,Neutral,17.36,nan,3.9,unknown,unknown,NaN
6,2023-01-07,1310.0,126.0,5.0,70.36,0.14,302.5480,6.0,North,Credit Card,...,Books,4.1,Not Returned,Positive,18.52,WELCOME5,2.7,Used loyalty points,value_5,NaN
7,2023-01-08,1530.0,197.0,8.0,36.63,0.29,208.0584,8.0,South,Cash,...,Food,1.7,Not Returned,Positive,17.78,nan,1.8,Preferred morning delivery,value_5,NaN
8,2023-01-09,1886.0,165.0,9.0,74.33,0.20,535.1760,4.0,East,Credit Card,...,Clothing,1.8,Not Returned,Negative,9.75,WELCOME5,NaN,unknown,value_2,NaN
9,2023-01-10,1207.0,109.0,9.0,79.87,0.11,639.7587,3.0,West,Online,...,Books,2.2,Not Returned,Neutral,NaN,FREESHIP,NaN,Preferred morning delivery,value_3,NaN
10,2023-01-11,1535.0,118.0,1.0,42.93,0.21,33.9147,6.0,East,Credit Card,...,Books,3.2,Not Returned,Negative,15.10,nan,1.9,Preferred morning delivery,value_5,NaN
11,2023-01-12,1229.0,180.0,6.0,62.00,0.06,349.6800,1.0,East,Credit Card,...,Electronics,2.8,Not Returned,Negative,10.03,FREESHIP,NaN,First-time customer,no_data,NaN
12,2023-01-13,1579.0,112.0,3.0,40.52,0.13,105.7572,1.0,North,Credit Card,...,Clothing,4.8,Not Returned,Negative,14.37,FREESHIP,3.1,Used loyalty points,no_data,NaN
13,2023-01-14,1417.0,187.0,4.0,97.39,0.14,335.0216,3.0,South,Online,...,Food,1.8,Not Returned,Positive,10.37,FREESHIP,3.4,Used loyalty points,no_data,NaN
14,2023-01-15,1577.0,174.0,8.0,79.52,0.22,496.2048,2.0,West,Credit Card,...,Books,4.9,Not Returned,Negative,7.50,nan,NaN,Used loyalty points,unknown,NaN
15,2023-01-16,1158.0,191.0,8.0,32.20,0.27,188.0480,6.0,South,Online,...,Clothing,2.6,Not Returned,Negative,NaN,FREESHIP,4.2,Used loyalty points,no_data,NaN
16,2023-01-17,1287.0,148.0,7.0,96.14,0.15,572.0330,3.0,West,Online,...,Food,3.0,Not Returned,Neutral,11.07,nan,NaN,Frequent buyer,value_4,NaN
17,2023-01-18,1472.0,115.0,9.0,34.78,0.15,266.0670,3.0,North,Cash,...,Electronics,1.6,Not Returned,Positive,13.32,nan,4.6,Frequent buyer,no_data,NaN
18,2023-01-19,1084.0,193.0,3.0,86.61,0.21,205.2657,5.0,North,Online,...,Food,2.6,Returned,Neutral,8.29,nan,3.8,Preferred morning delivery,unknown,NaN
19,2023-01-20,1201.0,142.0,9.0,50.54,0.10,409.3740,5.0,North,Cash,...,Books,4.2,Not Returned,Neutral,11.42,FREESHIP,NaN,First-time customer,unknown,NaN
20,2023-01-21,1242.0,197.0,4.0,29.76,0.00,119.0400,7.0,West,Credit Card,...,Clothing,3.4,Not Returned,Negative,NaN,FREESHIP,2.9,unknown,value_1,NaN
21,2023-01-22,1798.0,171.0,2.0,33.19,0.23,51.1126,5.0,North,Online,...,Books,4.9,Returned,Negative,16.40,SAVE10,NaN,Frequent buyer,no_data,NaN
22,2023-01-23,1255.0,129.0,3.0,57.25,0.11,152.8575,8.0,West,Credit Card,...,Books,3.7,Not Returned,Positive,8.02,nan,1.3,unknown,value_2,NaN
23,2023-01-24,1793.0,196.0,2.0,86.63,0.04,166.3296,9.0,South,Credit Card,...,Food,4.6,Returned,Neutral,7.27,nan,NaN,Frequent buyer,value_5,NaN
24,2023-01-25,1433.0,164.0,2.0,12.22,0.26,18.0856,5.0,South,Credit Card,...,Books,4.7,Not Returned,Neutral,14.20,nan,NaN,Requested gift wrap,no_data,NaN
25,2023-01-26,1322.0,166.0,7.0,24.26,0.18,139.2524,8.0,North,Cash,...,Clothing,3.4,Not Returned,Positive,16.87,WELCOME5,4.3,Preferred morning delivery,value_1,NaN
26,2023-01-27,1862.0,143.0,8.0,71.66,0.20,458.6240,9.0,West,Credit Card,...,Food,2.3,Returned,Neutral,15.19,WELCOME5,2.0,unknown,value_3,NaN
27,2023-01-28,1367.0,120.0,9.0,75.39,0.02,664.9398,8.0,West,Cash,...,Food,3.6,Not Returned,Negative,11.24,SAVE10,2.8,Frequent buyer,value_1,NaN
28,2023-01-29,1803.0,184.0,4.0,80.89,0.30,226.4920,4.0,North,Cash,...,Food,2.5,Returned,Negative,14.22,FREESHIP,4.5,Preferred morning delivery,value_3,NaN
29,2023-01-30,1269.0,149.0,3.0,56.28,0.21,133.3836,9.0,West,Online,...,Electronics,1.9,Returned,Neutral,16.20,nan,1.3,Frequent buyer,no_data,NaN
30,2023-01-31,1759.0,110.0,7.0,23.61,0.30,115.6890,2.0,East,Credit Card,...,Food,3.8,Returned,Neutral,8.10,nan,4.5,unknown,value_1,NaN
31,2023-02-01,1179.0,133.0,8.0,29.83,0.18,195.6848,4.0,West,Cash,...,Clothing,3.5,Not Returned,Positive,19.22,WELCOME5,4.6,Used loyalty points,no_data,NaN
32,2023-02-02,1296.0,111.0,5.0,79.33,0.02,388.7170,4.0,North,Credit Card,...,Electronics,3.1,Returned,Positive,NaN,nan,1.6,unknown,unknown,NaN
33,2023-02-03,1508.0,134.0,9.0,38.35,0.22,269.2170,4.0,East,Online,...,Books,2.8,Not Returned,Negative,14.82,nan,4.2,Frequent buyer,value_5,NaN
34,2023-02-04,1570.0,176.0,1.0,22.90,0.09,20.8390,6.0,North,Cash,...,Food,4.0,Returned,Negative,13.03,nan,4.7,no_data,value_1,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 17:**
</div>

In [39]:
print("Total number of missing values in the DataFrame:", df.isna().sum().sum())

Total number of missing values in the DataFrame: 75

<div class="alert alert-warning">

**18. Find Indexes of Missing Values**

**Write a Pandas program to find the Indexes of missing values in a given DataFrame.**

</div>

In [40]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_11311/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1364.0,106.0,5.0,34.01,0.07,158.1465,1.0,South,Cash,...,Books,3.8,Returned,Negative,12.45,nan,4.0,no_data,unknown,NaN
1,2023-01-02,1616.0,172.0,8.0,77.56,0.10,558.4320,1.0,West,Credit Card,...,Food,4.8,Returned,Neutral,16.17,nan,4.5,Used loyalty points,value_2,NaN
2,2023-01-03,1792.0,194.0,3.0,32.28,0.25,72.6300,8.0,North,Online,...,Clothing,4.8,Not Returned,Negative,19.40,nan,NaN,Requested gift wrap,value_5,NaN
3,2023-01-04,1305.0,128.0,2.0,35.67,0.23,54.9318,4.0,East,Online,...,Food,4.0,Not Returned,Negative,NaN,WELCOME5,2.6,unknown,unknown,NaN
4,2023-01-05,1389.0,117.0,7.0,62.41,0.02,428.1326,2.0,South,Credit Card,...,Electronics,1.6,Returned,Positive,NaN,nan,2.7,Preferred morning delivery,value_2,NaN
5,2023-01-06,1998.0,142.0,2.0,22.66,0.11,40.3348,6.0,East,Cash,...,Clothing,2.3,Returned,Neutral,NaN,FREESHIP,2.5,Frequent buyer,value_1,NaN
6,2023-01-07,1652.0,167.0,6.0,87.22,0.21,413.4228,6.0,North,Credit Card,...,Electronics,3.5,Not Returned,Negative,10.39,FREESHIP,NaN,unknown,unknown,NaN
7,2023-01-08,1064.0,104.0,2.0,40.68,0.18,66.7152,5.0,North,Credit Card,...,Books,2.5,Not Returned,Neutral,15.81,SAVE10,2.0,Preferred morning delivery,unknown,NaN
8,2023-01-09,1579.0,144.0,2.0,58.40,0.13,101.6160,4.0,East,Credit Card,...,Books,1.6,Returned,Negative,10.63,WELCOME5,2.3,unknown,no_data,NaN
9,2023-01-10,1891.0,198.0,6.0,73.16,0.02,430.1808,9.0,West,Cash,...,Food,2.0,Not Returned,Positive,15.89,SAVE10,3.3,no_data,unknown,NaN
10,2023-01-11,1592.0,198.0,6.0,70.06,0.15,357.3060,6.0,East,Online,...,Clothing,4.1,Not Returned,Positive,17.74,FREESHIP,3.3,Preferred morning delivery,value_3,NaN
11,2023-01-12,1150.0,165.0,4.0,85.70,0.27,250.2440,4.0,West,Online,...,Clothing,2.9,Returned,Negative,NaN,nan,4.5,Preferred morning delivery,no_data,NaN
12,2023-01-13,1452.0,120.0,5.0,58.88,0.09,267.9040,7.0,East,Credit Card,...,Food,1.4,Returned,Neutral,11.72,nan,1.9,no_data,value_2,NaN
13,2023-01-14,1749.0,153.0,5.0,26.87,0.29,95.3885,8.0,South,Credit Card,...,Food,1.7,Returned,Neutral,12.03,SAVE10,NaN,no_data,no_data,NaN
14,2023-01-15,1972.0,187.0,1.0,70.69,0.29,50.1899,8.0,West,Cash,...,Food,3.0,Returned,Positive,12.92,SAVE10,4.6,First-time customer,unknown,NaN
15,2023-01-16,1962.0,186.0,4.0,66.27,0.28,190.8576,9.0,North,Online,...,Clothing,2.5,Returned,Negative,10.85,nan,NaN,Preferred morning delivery,no_data,NaN
16,2023-01-17,1400.0,132.0,7.0,82.30,0.07,535.7730,7.0,North,Credit Card,...,Clothing,3.8,Returned,Negative,5.16,WELCOME5,NaN,Used loyalty points,no_data,NaN
17,2023-01-18,1011.0,169.0,8.0,26.85,0.08,197.6160,5.0,North,Online,...,Books,3.5,Returned,Negative,14.56,WELCOME5,2.4,Requested gift wrap,unknown,NaN
18,2023-01-19,1856.0,170.0,7.0,87.38,0.09,556.6106,4.0,West,Online,...,Clothing,2.7,Returned,Positive,11.23,nan,NaN,Requested gift wrap,value_2,NaN
19,2023-01-20,1089.0,192.0,4.0,15.69,0.14,53.9736,1.0,South,Online,...,Clothing,3.1,Returned,Negative,11.02,SAVE10,4.9,unknown,value_4,NaN
20,2023-01-21,1352.0,194.0,6.0,20.87,0.03,121.4634,3.0,South,Cash,...,Electronics,1.8,Not Returned,Neutral,6.24,WELCOME5,3.3,Used loyalty points,value_1,NaN
21,2023-01-22,1718.0,171.0,6.0,77.27,0.10,417.2580,1.0,North,Cash,...,Clothing,4.1,Not Returned,Negative,18.21,FREESHIP,NaN,First-time customer,value_5,NaN
22,2023-01-23,1848.0,167.0,3.0,42.05,0.27,92.0895,7.0,East,Cash,...,Food,3.4,Not Returned,Negative,9.47,WELCOME5,4.0,unknown,value_5,NaN
23,2023-01-24,1134.0,168.0,6.0,54.55,0.16,274.9320,7.0,West,Cash,...,Food,5.0,Not Returned,Negative,NaN,nan,2.1,no_data,no_data,NaN
24,2023-01-25,1907.0,195.0,8.0,39.85,0.13,277.3560,1.0,West,Cash,...,Clothing,3.6,Not Returned,Neutral,7.62,WELCOME5,1.6,no_data,value_1,NaN
25,2023-01-26,1940.0,131.0,2.0,16.14,0.18,26.4696,6.0,West,Cash,...,Electronics,2.0,Returned,Positive,15.63,nan,3.3,unknown,unknown,NaN
26,2023-01-27,1901.0,106.0,2.0,90.50,0.29,128.5100,6.0,West,Cash,...,Clothing,4.0,Returned,Neutral,NaN,SAVE10,3.8,no_data,unknown,NaN
27,2023-01-28,1322.0,107.0,7.0,62.71,0.08,403.8524,3.0,North,Cash,...,Books,4.5,Returned,Positive,17.85,nan,NaN,Used loyalty points,value_3,NaN
28,2023-01-29,1106.0,161.0,2.0,70.91,0.21,112.0378,7.0,East,Credit Card,...,Books,2.7,Not Returned,Positive,15.44,SAVE10,3.7,First-time customer,unknown,NaN
29,2023-01-30,1340.0,175.0,2.0,61.85,0.10,111.3300,3.0,West,Cash,...,Books,2.4,Not Returned,Negative,8.00,nan,2.9,Requested gift wrap,value_5,NaN
30,2023-01-31,1673.0,121.0,3.0,12.96,0.21,30.7152,3.0,North,Cash,...,Food,2.5,Returned,Negative,12.67,nan,2.1,Used loyalty points,value_1,NaN
31,2023-02-01,1930.0,183.0,7.0,76.98,0.17,447.2538,2.0,North,Credit Card,...,Clothing,3.0,Returned,Negative,5.30,WELCOME5,4.2,unknown,unknown,NaN
32,2023-02-02,1590.0,146.0,1.0,89.36,0.29,63.4456,8.0,North,Cash,...,Electronics,2.2,Returned,Negative,13.14,WELCOME5,NaN,unknown,unknown,NaN
33,2023-02-03,1554.0,159.0,6.0,25.66,0.09,140.1036,9.0,North,Online,...,Books,4.6,Not Returned,Neutral,15.54,WELCOME5,2.4,unknown,value_4,NaN
34,2023-02-04,1374.0,114.0,1.0,98.12,0.19,79.4772,8.0,North,Cash,...,Food,1.7,Not Returned,Negative,12.20,nan,2.0,no_data,unknown,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 18:**
</div>

In [41]:
# 18. Find Indexes of Missing Values
# Write a Pandas program to find the Indexes of missing values in a given DataFrame.
missing_indexes = df.index[df.isnull().any(axis=1)].tolist()
print("Indexes of rows with missing values:", missing_indexes)

Indexes of rows with missing values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]