[Pandas Data Cleaning and Preprocessing](https://www.w3resource.com/python-exercises/pandas/pandas-data-cleaning-and-preprocessing.php)

In [1]:
import pandas as pd
import numpy as np

<div class="alert alert-warning">

**1. Handling Missing Data in Pandas**

**Write a Pandas program to fill missing values (NaN) in a DataFrame using fillna().**

</div>

In [2]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1243,123,3,43.94,0.05,125.2290,3,North,Online,...,4,62,Male,Books,1.7,Returned,Positive,NaN,SAVE10,1.5
1,2023-01-02,1258,168,6,37.39,0.05,213.1230,1,North,Credit Card,...,4,41,Male,Clothing,4.2,Not Returned,Negative,NaN,nan,NaN
2,2023-01-03,1840,105,4,78.92,0.08,290.4256,4,South,Credit Card,...,6,18,Female,Books,1.6,Not Returned,Positive,17.29,WELCOME5,NaN
3,2023-01-04,1575,167,2,71.43,0.20,114.2880,2,South,Cash,...,2,52,Male,Electronics,4.5,Returned,Positive,15.42,SAVE10,2.6
4,2023-01-05,1790,148,5,78.59,0.02,385.0910,8,East,Online,...,4,57,Female,Clothing,4.8,Returned,Positive,NaN,SAVE10,4.5
5,2023-01-06,1381,116,1,62.33,0.25,46.7475,8,North,Credit Card,...,3,68,Female,Electronics,1.6,Returned,Negative,16.04,SAVE10,3.6
6,2023-01-07,1236,155,5,12.76,0.12,56.1440,2,West,Online,...,1,63,Female,Food,3.0,Not Returned,Negative,NaN,WELCOME5,2.1
7,2023-01-08,1408,150,7,29.87,0.13,181.9083,2,North,Online,...,3,41,Female,Clothing,4.3,Returned,Neutral,17.41,nan,NaN
8,2023-01-09,1336,105,9,93.19,0.17,696.1293,2,West,Cash,...,1,52,Male,Electronics,3.2,Not Returned,Neutral,16.46,nan,NaN
9,2023-01-10,1807,175,2,32.74,0.23,50.4196,1,South,Cash,...,3,45,Female,Clothing,2.2,Not Returned,Neutral,9.45,FREESHIP,NaN
10,2023-01-11,1410,181,7,76.80,0.11,478.4640,1,West,Cash,...,3,54,Female,Electronics,1.9,Not Returned,Neutral,NaN,nan,1.8
11,2023-01-12,1437,123,8,96.74,0.29,549.4832,7,North,Cash,...,6,60,Other,Electronics,2.5,Not Returned,Positive,12.83,nan,4.2
12,2023-01-13,1125,106,4,45.14,0.21,142.6424,9,North,Credit Card,...,6,39,Female,Clothing,2.5,Not Returned,Positive,6.94,nan,1.1
13,2023-01-14,1414,141,6,44.92,0.13,234.4824,5,West,Credit Card,...,1,35,Female,Food,1.0,Returned,Negative,15.42,nan,3.1
14,2023-01-15,1003,113,5,49.01,0.10,220.5450,9,South,Online,...,2,30,Other,Books,4.6,Not Returned,Positive,17.16,SAVE10,3.8
15,2023-01-16,1231,142,7,72.70,0.14,437.6540,5,North,Credit Card,...,6,27,Female,Food,1.5,Not Returned,Negative,19.77,nan,NaN
16,2023-01-17,1015,144,7,32.67,0.04,219.5424,8,South,Credit Card,...,1,27,Male,Clothing,2.5,Not Returned,Positive,12.92,nan,4.8
17,2023-01-18,1123,150,7,12.73,0.11,79.3079,6,West,Online,...,4,19,Male,Clothing,2.4,Returned,Positive,11.78,nan,1.2
18,2023-01-19,1684,152,8,75.47,0.22,470.9328,6,West,Cash,...,5,35,Other,Food,4.2,Not Returned,Positive,5.45,nan,NaN
19,2023-01-20,1708,141,3,67.62,0.00,202.8600,8,East,Cash,...,5,31,Male,Food,3.1,Not Returned,Neutral,19.22,WELCOME5,4.9
20,2023-01-21,1077,195,5,53.44,0.23,205.7440,7,West,Cash,...,3,44,Male,Food,4.3,Not Returned,Negative,NaN,WELCOME5,4.1
21,2023-01-22,1668,142,3,90.24,0.26,200.3328,7,South,Online,...,2,67,Female,Food,4.1,Not Returned,Negative,16.02,SAVE10,NaN
22,2023-01-23,1604,185,3,92.80,0.24,211.5840,2,East,Cash,...,5,39,Female,Books,1.8,Returned,Positive,15.03,nan,1.2
23,2023-01-24,1018,188,1,71.12,0.27,51.9176,3,West,Online,...,1,41,Female,Electronics,1.8,Returned,Positive,8.32,nan,NaN
24,2023-01-25,1839,123,9,79.63,0.28,516.0024,7,North,Cash,...,1,22,Other,Electronics,2.7,Not Returned,Negative,6.84,FREESHIP,4.2
25,2023-01-26,1098,175,7,96.16,0.17,558.6896,2,East,Online,...,6,26,Male,Food,2.0,Returned,Positive,8.69,FREESHIP,4.6
26,2023-01-27,1081,142,9,78.62,0.13,615.5946,4,South,Online,...,1,18,Female,Food,2.4,Not Returned,Positive,17.15,WELCOME5,NaN
27,2023-01-28,1639,104,1,95.30,0.07,88.6290,2,East,Credit Card,...,6,36,Other,Food,4.0,Not Returned,Negative,10.05,nan,2.7
28,2023-01-29,1363,198,1,88.43,0.00,88.4300,5,West,Online,...,5,69,Male,Books,2.2,Returned,Neutral,17.59,SAVE10,NaN
29,2023-01-30,1969,126,7,28.69,0.07,186.7719,9,West,Cash,...,5,22,Male,Clothing,4.3,Returned,Neutral,10.94,nan,1.7
30,2023-01-31,1659,188,1,13.08,0.05,12.4260,9,West,Credit Card,...,6,62,Other,Clothing,2.3,Returned,Negative,7.41,FREESHIP,1.3
31,2023-02-01,1515,177,6,18.70,0.20,89.7600,5,North,Credit Card,...,2,18,Other,Electronics,1.8,Not Returned,Positive,9.73,nan,4.6
32,2023-02-02,1112,115,9,86.32,0.29,551.5848,5,West,Cash,...,4,60,Female,Food,2.8,Not Returned,Negative,7.88,WELCOME5,2.9
33,2023-02-03,1653,133,6,96.28,0.10,519.9120,1,West,Credit Card,...,1,37,Other,Books,4.0,Returned,Positive,13.32,nan,4.2
34,2023-02-04,1539,123,7,19.12,0.13,116.4408,1,South,Online,...,2,36,Other,Food,5.0,Returned,Negative,11.12,WELCOME5,NaN

<div class="alert alert-success">

**Solution 01:**
</div>

In [3]:
# 1. Handling Missing Data in Pandas
# Write a Pandas program to fill missing values (NaN) in a DataFrame using fillna().
result_df = df.fillna({
    'shipping_cost': df['shipping_cost'].mean(),
    'coupon_code': 'No Coupon',
    'delivery_rating': df['delivery_rating'].mean()
})

result_df

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1243,123,3,43.94,0.05,125.2290,3,North,Online,...,4,62,Male,Books,1.7,Returned,Positive,12.884483,SAVE10,1.500000
1,2023-01-02,1258,168,6,37.39,0.05,213.1230,1,North,Credit Card,...,4,41,Male,Clothing,4.2,Not Returned,Negative,12.884483,nan,3.073913
2,2023-01-03,1840,105,4,78.92,0.08,290.4256,4,South,Credit Card,...,6,18,Female,Books,1.6,Not Returned,Positive,17.290000,WELCOME5,3.073913
3,2023-01-04,1575,167,2,71.43,0.20,114.2880,2,South,Cash,...,2,52,Male,Electronics,4.5,Returned,Positive,15.420000,SAVE10,2.600000
4,2023-01-05,1790,148,5,78.59,0.02,385.0910,8,East,Online,...,4,57,Female,Clothing,4.8,Returned,Positive,12.884483,SAVE10,4.500000
5,2023-01-06,1381,116,1,62.33,0.25,46.7475,8,North,Credit Card,...,3,68,Female,Electronics,1.6,Returned,Negative,16.040000,SAVE10,3.600000
6,2023-01-07,1236,155,5,12.76,0.12,56.1440,2,West,Online,...,1,63,Female,Food,3.0,Not Returned,Negative,12.884483,WELCOME5,2.100000
7,2023-01-08,1408,150,7,29.87,0.13,181.9083,2,North,Online,...,3,41,Female,Clothing,4.3,Returned,Neutral,17.410000,nan,3.073913
8,2023-01-09,1336,105,9,93.19,0.17,696.1293,2,West,Cash,...,1,52,Male,Electronics,3.2,Not Returned,Neutral,16.460000,nan,3.073913
9,2023-01-10,1807,175,2,32.74,0.23,50.4196,1,South,Cash,...,3,45,Female,Clothing,2.2,Not Returned,Neutral,9.450000,FREESHIP,3.073913
10,2023-01-11,1410,181,7,76.80,0.11,478.4640,1,West,Cash,...,3,54,Female,Electronics,1.9,Not Returned,Neutral,12.884483,nan,1.800000
11,2023-01-12,1437,123,8,96.74,0.29,549.4832,7,North,Cash,...,6,60,Other,Electronics,2.5,Not Returned,Positive,12.830000,nan,4.200000
12,2023-01-13,1125,106,4,45.14,0.21,142.6424,9,North,Credit Card,...,6,39,Female,Clothing,2.5,Not Returned,Positive,6.940000,nan,1.100000
13,2023-01-14,1414,141,6,44.92,0.13,234.4824,5,West,Credit Card,...,1,35,Female,Food,1.0,Returned,Negative,15.420000,nan,3.100000
14,2023-01-15,1003,113,5,49.01,0.10,220.5450,9,South,Online,...,2,30,Other,Books,4.6,Not Returned,Positive,17.160000,SAVE10,3.800000
15,2023-01-16,1231,142,7,72.70,0.14,437.6540,5,North,Credit Card,...,6,27,Female,Food,1.5,Not Returned,Negative,19.770000,nan,3.073913
16,2023-01-17,1015,144,7,32.67,0.04,219.5424,8,South,Credit Card,...,1,27,Male,Clothing,2.5,Not Returned,Positive,12.920000,nan,4.800000
17,2023-01-18,1123,150,7,12.73,0.11,79.3079,6,West,Online,...,4,19,Male,Clothing,2.4,Returned,Positive,11.780000,nan,1.200000
18,2023-01-19,1684,152,8,75.47,0.22,470.9328,6,West,Cash,...,5,35,Other,Food,4.2,Not Returned,Positive,5.450000,nan,3.073913
19,2023-01-20,1708,141,3,67.62,0.00,202.8600,8,East,Cash,...,5,31,Male,Food,3.1,Not Returned,Neutral,19.220000,WELCOME5,4.900000
20,2023-01-21,1077,195,5,53.44,0.23,205.7440,7,West,Cash,...,3,44,Male,Food,4.3,Not Returned,Negative,12.884483,WELCOME5,4.100000
21,2023-01-22,1668,142,3,90.24,0.26,200.3328,7,South,Online,...,2,67,Female,Food,4.1,Not Returned,Negative,16.020000,SAVE10,3.073913
22,2023-01-23,1604,185,3,92.80,0.24,211.5840,2,East,Cash,...,5,39,Female,Books,1.8,Returned,Positive,15.030000,nan,1.200000
23,2023-01-24,1018,188,1,71.12,0.27,51.9176,3,West,Online,...,1,41,Female,Electronics,1.8,Returned,Positive,8.320000,nan,3.073913
24,2023-01-25,1839,123,9,79.63,0.28,516.0024,7,North,Cash,...,1,22,Other,Electronics,2.7,Not Returned,Negative,6.840000,FREESHIP,4.200000
25,2023-01-26,1098,175,7,96.16,0.17,558.6896,2,East,Online,...,6,26,Male,Food,2.0,Returned,Positive,8.690000,FREESHIP,4.600000
26,2023-01-27,1081,142,9,78.62,0.13,615.5946,4,South,Online,...,1,18,Female,Food,2.4,Not Returned,Positive,17.150000,WELCOME5,3.073913
27,2023-01-28,1639,104,1,95.30,0.07,88.6290,2,East,Credit Card,...,6,36,Other,Food,4.0,Not Returned,Negative,10.050000,nan,2.700000
28,2023-01-29,1363,198,1,88.43,0.00,88.4300,5,West,Online,...,5,69,Male,Books,2.2,Returned,Neutral,17.590000,SAVE10,3.073913
29,2023-01-30,1969,126,7,28.69,0.07,186.7719,9,West,Cash,...,5,22,Male,Clothing,4.3,Returned,Neutral,10.940000,nan,1.700000
30,2023-01-31,1659,188,1,13.08,0.05,12.4260,9,West,Credit Card,...,6,62,Other,Clothing,2.3,Returned,Negative,7.410000,FREESHIP,1.300000
31,2023-02-01,1515,177,6,18.70,0.20,89.7600,5,North,Credit Card,...,2,18,Other,Electronics,1.8,Not Returned,Positive,9.730000,nan,4.600000
32,2023-02-02,1112,115,9,86.32,0.29,551.5848,5,West,Cash,...,4,60,Female,Food,2.8,Not Returned,Negative,7.880000,WELCOME5,2.900000
33,2023-02-03,1653,133,6,96.28,0.10,519.9120,1,West,Credit Card,...,1,37,Other,Books,4.0,Returned,Positive,13.320000,nan,4.200000
34,2023-02-04,1539,123,7,19.12,0.13,116.4408,1,South,Online,...,2,36,Other,Food,5.0,Returned,Negative,11.120000,WELCOME5,3.073913

<div class="alert alert-warning">

**2. Handling Duplicates in Pandas**

**Write a Pandas program to drop rows with missing data.**

</div>

In [4]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1116,124,1,62.16,0.23,47.8632,6,North,Cash,...,4,43,Male,Books,1.1,Not Returned,Positive,7.71,WELCOME5,1.4
1,2023-01-02,1506,141,9,14.64,0.24,100.1376,3,South,Credit Card,...,4,57,Male,Books,4.8,Returned,Negative,NaN,FREESHIP,3.2
2,2023-01-03,1927,151,7,66.26,0.24,352.5032,1,West,Cash,...,5,20,Other,Electronics,4.6,Not Returned,Neutral,8.13,FREESHIP,NaN
3,2023-01-04,1966,127,8,73.18,0.02,573.7312,9,East,Online,...,5,27,Male,Electronics,2.5,Not Returned,Positive,NaN,FREESHIP,2.2
4,2023-01-05,1015,193,1,50.62,0.22,39.4836,6,South,Cash,...,6,42,Other,Electronics,3.4,Not Returned,Positive,17.14,SAVE10,3.9
5,2023-01-06,1305,164,6,69.46,0.12,366.7488,9,West,Credit Card,...,5,50,Other,Books,3.0,Returned,Neutral,11.73,nan,3.2
6,2023-01-07,1321,110,2,56.55,0.04,108.5760,5,West,Credit Card,...,4,28,Male,Clothing,1.3,Returned,Negative,12.18,SAVE10,NaN
7,2023-01-08,1280,193,1,45.20,0.17,37.5160,9,East,Online,...,6,20,Female,Clothing,3.3,Not Returned,Negative,5.76,SAVE10,5.0
8,2023-01-09,1641,163,8,11.66,0.14,80.2208,8,North,Cash,...,1,32,Male,Clothing,3.6,Not Returned,Neutral,5.92,FREESHIP,1.8
9,2023-01-10,1053,185,4,86.63,0.01,343.0548,7,East,Cash,...,6,50,Female,Clothing,3.5,Returned,Negative,8.85,WELCOME5,NaN
10,2023-01-11,1465,173,8,92.78,0.07,690.2832,9,West,Cash,...,5,34,Male,Electronics,2.6,Returned,Positive,15.10,nan,4.5
11,2023-01-12,1441,145,4,83.56,0.18,274.0768,9,East,Credit Card,...,1,47,Female,Food,2.0,Returned,Positive,NaN,WELCOME5,1.8
12,2023-01-13,1456,104,1,25.35,0.14,21.8010,9,West,Cash,...,2,25,Male,Clothing,5.0,Returned,Neutral,18.77,nan,1.6
13,2023-01-14,1563,156,9,92.94,0.02,819.7308,6,South,Credit Card,...,6,60,Male,Books,3.5,Returned,Positive,5.09,WELCOME5,NaN
14,2023-01-15,1043,170,7,98.13,0.19,556.3971,1,South,Credit Card,...,6,44,Female,Food,1.1,Returned,Neutral,NaN,SAVE10,2.7
15,2023-01-16,1169,117,5,48.47,0.16,203.5740,9,East,Credit Card,...,1,66,Male,Food,2.8,Not Returned,Negative,8.27,SAVE10,4.8
16,2023-01-17,1662,109,5,28.82,0.17,119.6030,9,South,Cash,...,3,55,Female,Books,1.6,Not Returned,Positive,18.59,nan,3.0
17,2023-01-18,1292,129,8,58.10,0.27,339.3040,9,West,Credit Card,...,3,43,Female,Electronics,3.3,Returned,Neutral,14.28,SAVE10,4.8
18,2023-01-19,1735,134,7,59.94,0.08,386.0136,4,North,Credit Card,...,5,51,Other,Electronics,1.8,Not Returned,Neutral,11.30,WELCOME5,NaN
19,2023-01-20,1111,185,8,31.49,0.13,219.1704,9,South,Credit Card,...,2,58,Other,Food,4.3,Returned,Neutral,14.66,nan,3.8
20,2023-01-21,1087,198,7,79.50,0.06,523.1100,5,South,Online,...,4,29,Male,Clothing,1.2,Returned,Neutral,13.58,WELCOME5,NaN
21,2023-01-22,1933,102,7,40.62,0.29,201.8814,2,West,Cash,...,5,25,Male,Electronics,4.2,Not Returned,Negative,19.27,WELCOME5,NaN
22,2023-01-23,1292,113,1,69.89,0.15,59.4065,8,East,Cash,...,6,54,Other,Books,4.7,Not Returned,Positive,NaN,WELCOME5,NaN
23,2023-01-24,1090,199,1,74.87,0.01,74.1213,1,South,Online,...,3,24,Male,Clothing,2.5,Returned,Neutral,18.87,SAVE10,1.8
24,2023-01-25,1614,182,5,48.48,0.09,220.5840,9,South,Cash,...,1,69,Female,Clothing,2.0,Returned,Neutral,8.06,WELCOME5,3.5
25,2023-01-26,1264,170,7,90.92,0.19,515.5164,9,East,Credit Card,...,5,18,Male,Electronics,3.0,Not Returned,Neutral,7.30,WELCOME5,2.3
26,2023-01-27,1067,162,7,90.73,0.00,635.1100,4,East,Online,...,1,47,Male,Food,2.0,Returned,Positive,12.22,nan,1.7
27,2023-01-28,1501,180,8,96.39,0.03,747.9864,7,North,Online,...,2,22,Female,Electronics,3.9,Not Returned,Negative,14.67,WELCOME5,4.7
28,2023-01-29,1096,198,5,15.56,0.24,59.1280,8,East,Cash,...,6,48,Female,Clothing,2.4,Not Returned,Negative,15.38,FREESHIP,NaN
29,2023-01-30,1185,189,5,56.16,0.26,207.7920,2,South,Cash,...,1,20,Other,Clothing,3.3,Not Returned,Negative,16.28,SAVE10,1.4
30,2023-01-31,1509,169,7,33.76,0.29,167.7872,1,East,Online,...,6,42,Male,Electronics,1.8,Returned,Positive,19.52,SAVE10,1.9
31,2023-02-01,1673,178,4,79.88,0.02,313.1296,3,East,Credit Card,...,1,65,Female,Books,3.7,Returned,Negative,17.09,nan,1.3
32,2023-02-02,1990,178,2,41.25,0.00,82.5000,3,West,Online,...,6,46,Other,Electronics,3.6,Not Returned,Negative,NaN,SAVE10,1.4
33,2023-02-03,1292,147,7,10.45,0.21,57.7885,5,South,Cash,...,4,42,Male,Clothing,5.0,Not Returned,Negative,16.19,FREESHIP,NaN
34,2023-02-04,1255,152,6,33.20,0.06,187.2480,3,West,Cash,...,5,19,Female,Clothing,1.0,Returned,Neutral,NaN,nan,NaN

<div class="alert alert-success">

**Solution 02:**
</div>

In [5]:
# 2. Handling Duplicates in Pandas
# Write a Pandas program to drop rows with missing data.

result_df = df.dropna()
result_df

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1116,124,1,62.16,0.23,47.8632,6,North,Cash,...,4,43,Male,Books,1.1,Not Returned,Positive,7.71,WELCOME5,1.4
4,2023-01-05,1015,193,1,50.62,0.22,39.4836,6,South,Cash,...,6,42,Other,Electronics,3.4,Not Returned,Positive,17.14,SAVE10,3.9
5,2023-01-06,1305,164,6,69.46,0.12,366.7488,9,West,Credit Card,...,5,50,Other,Books,3.0,Returned,Neutral,11.73,nan,3.2
7,2023-01-08,1280,193,1,45.20,0.17,37.5160,9,East,Online,...,6,20,Female,Clothing,3.3,Not Returned,Negative,5.76,SAVE10,5.0
8,2023-01-09,1641,163,8,11.66,0.14,80.2208,8,North,Cash,...,1,32,Male,Clothing,3.6,Not Returned,Neutral,5.92,FREESHIP,1.8
10,2023-01-11,1465,173,8,92.78,0.07,690.2832,9,West,Cash,...,5,34,Male,Electronics,2.6,Returned,Positive,15.10,nan,4.5
12,2023-01-13,1456,104,1,25.35,0.14,21.8010,9,West,Cash,...,2,25,Male,Clothing,5.0,Returned,Neutral,18.77,nan,1.6
15,2023-01-16,1169,117,5,48.47,0.16,203.5740,9,East,Credit Card,...,1,66,Male,Food,2.8,Not Returned,Negative,8.27,SAVE10,4.8
16,2023-01-17,1662,109,5,28.82,0.17,119.6030,9,South,Cash,...,3,55,Female,Books,1.6,Not Returned,Positive,18.59,nan,3.0
17,2023-01-18,1292,129,8,58.10,0.27,339.3040,9,West,Credit Card,...,3,43,Female,Electronics,3.3,Returned,Neutral,14.28,SAVE10,4.8
19,2023-01-20,1111,185,8,31.49,0.13,219.1704,9,South,Credit Card,...,2,58,Other,Food,4.3,Returned,Neutral,14.66,nan,3.8
23,2023-01-24,1090,199,1,74.87,0.01,74.1213,1,South,Online,...,3,24,Male,Clothing,2.5,Returned,Neutral,18.87,SAVE10,1.8
24,2023-01-25,1614,182,5,48.48,0.09,220.5840,9,South,Cash,...,1,69,Female,Clothing,2.0,Returned,Neutral,8.06,WELCOME5,3.5
25,2023-01-26,1264,170,7,90.92,0.19,515.5164,9,East,Credit Card,...,5,18,Male,Electronics,3.0,Not Returned,Neutral,7.30,WELCOME5,2.3
26,2023-01-27,1067,162,7,90.73,0.00,635.1100,4,East,Online,...,1,47,Male,Food,2.0,Returned,Positive,12.22,nan,1.7
27,2023-01-28,1501,180,8,96.39,0.03,747.9864,7,North,Online,...,2,22,Female,Electronics,3.9,Not Returned,Negative,14.67,WELCOME5,4.7
29,2023-01-30,1185,189,5,56.16,0.26,207.7920,2,South,Cash,...,1,20,Other,Clothing,3.3,Not Returned,Negative,16.28,SAVE10,1.4
30,2023-01-31,1509,169,7,33.76,0.29,167.7872,1,East,Online,...,6,42,Male,Electronics,1.8,Returned,Positive,19.52,SAVE10,1.9
31,2023-02-01,1673,178,4,79.88,0.02,313.1296,3,East,Credit Card,...,1,65,Female,Books,3.7,Returned,Negative,17.09,nan,1.3