[Pandas Missing Values](https://www.w3resource.com/python-exercises/pandas/missing-values/index.php)

In [1]:
import pandas as pd
import numpy as np

<div class="alert alert-warning">

**1. Detect Missing Values**

**Write a Pandas program to detect missing values of a given DataFrame. Display True or False.**

</div>

In [2]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1557,140,8,81.86,0.23,504.2576,1,West,Credit Card,...,6,36,Female,Electronics,2.9,Returned,Neutral,15.27,SAVE10,2.1
1,2023-01-02,1589,197,1,10.90,0.28,7.8480,9,North,Cash,...,5,65,Male,Electronics,2.3,Returned,Neutral,11.63,nan,2.2
2,2023-01-03,1004,151,3,78.12,0.01,232.0164,9,South,Credit Card,...,6,21,Female,Electronics,3.8,Returned,Positive,13.51,FREESHIP,NaN
3,2023-01-04,1487,157,8,76.15,0.11,542.1880,9,West,Cash,...,3,31,Male,Electronics,3.2,Not Returned,Negative,14.55,SAVE10,1.3
4,2023-01-05,1634,127,9,73.89,0.29,472.1571,4,East,Credit Card,...,2,44,Male,Books,2.3,Not Returned,Negative,16.70,FREESHIP,NaN
5,2023-01-06,1289,171,8,53.80,0.28,309.8880,1,West,Credit Card,...,5,20,Female,Books,3.3,Returned,Negative,16.79,nan,NaN
6,2023-01-07,1084,198,6,67.30,0.16,339.1920,7,East,Credit Card,...,6,58,Other,Books,3.4,Returned,Neutral,12.47,nan,1.2
7,2023-01-08,1302,172,3,41.83,0.14,107.9214,1,North,Credit Card,...,4,66,Other,Electronics,4.0,Returned,Neutral,NaN,nan,1.6
8,2023-01-09,1514,113,9,61.52,0.09,503.8488,2,South,Online,...,2,50,Other,Food,2.1,Returned,Positive,18.20,FREESHIP,4.8
9,2023-01-10,1976,147,9,72.08,0.09,590.3352,7,East,Credit Card,...,2,62,Other,Clothing,3.0,Returned,Neutral,17.33,SAVE10,NaN
10,2023-01-11,1747,123,5,49.74,0.06,233.7780,4,South,Credit Card,...,5,19,Male,Books,2.9,Not Returned,Neutral,7.09,nan,NaN
11,2023-01-12,1601,143,5,41.37,0.15,175.8225,2,East,Online,...,2,20,Male,Books,4.3,Not Returned,Negative,17.92,SAVE10,5.0
12,2023-01-13,1089,146,6,17.04,0.11,90.9936,1,West,Credit Card,...,4,61,Male,Books,4.4,Not Returned,Negative,6.99,SAVE10,4.7
13,2023-01-14,1676,106,8,92.73,0.16,623.1456,6,North,Cash,...,1,56,Other,Books,1.2,Returned,Negative,13.55,FREESHIP,2.2
14,2023-01-15,1861,161,4,18.99,0.04,72.9216,9,East,Online,...,5,24,Female,Books,4.5,Not Returned,Positive,7.95,SAVE10,NaN
15,2023-01-16,1530,192,1,56.60,0.12,49.8080,5,South,Cash,...,2,18,Male,Clothing,2.3,Not Returned,Positive,17.95,FREESHIP,NaN
16,2023-01-17,1837,179,1,43.75,0.03,42.4375,2,North,Cash,...,1,66,Female,Clothing,2.8,Returned,Positive,NaN,WELCOME5,2.6
17,2023-01-18,1963,156,3,37.22,0.10,100.4940,6,East,Cash,...,6,28,Female,Clothing,1.0,Not Returned,Positive,5.94,SAVE10,5.0
18,2023-01-19,1000,186,5,53.68,0.02,263.0320,3,South,Online,...,5,67,Male,Electronics,1.4,Returned,Positive,18.25,WELCOME5,NaN
19,2023-01-20,1131,169,9,86.66,0.05,740.9430,4,South,Online,...,3,20,Male,Food,4.8,Returned,Negative,16.54,SAVE10,2.4
20,2023-01-21,1133,196,1,34.70,0.24,26.3720,7,South,Credit Card,...,3,49,Other,Books,1.5,Not Returned,Negative,NaN,FREESHIP,NaN
21,2023-01-22,1186,142,3,38.52,0.14,99.3816,9,South,Online,...,3,56,Male,Clothing,3.6,Not Returned,Neutral,11.12,nan,NaN
22,2023-01-23,1538,174,4,34.43,0.20,110.1760,9,West,Online,...,5,35,Male,Clothing,1.8,Not Returned,Negative,16.29,WELCOME5,3.3
23,2023-01-24,1746,138,9,31.99,0.24,218.8116,7,West,Cash,...,4,20,Male,Clothing,2.7,Not Returned,Negative,12.58,FREESHIP,3.9
24,2023-01-25,1591,198,6,77.96,0.15,397.5960,4,South,Cash,...,4,55,Other,Clothing,3.9,Not Returned,Positive,12.70,SAVE10,1.8
25,2023-01-26,1531,179,7,91.54,0.01,634.3722,6,West,Credit Card,...,3,34,Male,Books,4.9,Not Returned,Neutral,14.19,WELCOME5,2.3
26,2023-01-27,1226,129,8,14.98,0.20,95.8720,3,South,Online,...,6,44,Male,Food,4.1,Not Returned,Negative,19.27,WELCOME5,2.7
27,2023-01-28,1189,173,1,37.36,0.09,33.9976,8,North,Credit Card,...,1,21,Female,Books,4.1,Not Returned,Negative,11.26,SAVE10,3.6
28,2023-01-29,1244,102,2,52.98,0.09,96.4236,5,East,Credit Card,...,4,36,Male,Clothing,1.5,Not Returned,Positive,18.41,FREESHIP,1.4
29,2023-01-30,1041,179,6,52.57,0.03,305.9574,6,East,Credit Card,...,1,30,Other,Clothing,4.8,Not Returned,Positive,6.81,SAVE10,4.2
30,2023-01-31,1394,155,4,12.99,0.19,42.0876,9,West,Online,...,2,40,Other,Books,4.1,Not Returned,Negative,NaN,nan,NaN
31,2023-02-01,1962,183,7,45.23,0.29,224.7931,4,South,Credit Card,...,4,56,Other,Clothing,3.0,Returned,Negative,17.03,nan,2.0
32,2023-02-02,1647,161,6,55.23,0.05,314.8110,4,East,Credit Card,...,3,28,Other,Electronics,4.7,Not Returned,Negative,7.79,nan,3.8
33,2023-02-03,1578,127,4,33.43,0.27,97.6156,9,West,Online,...,1,21,Other,Clothing,1.5,Not Returned,Positive,NaN,nan,4.9
34,2023-02-04,1047,106,4,18.05,0.04,69.3120,3,North,Online,...,4,59,Female,Food,4.2,Not Returned,Positive,9.56,nan,2.1

<div class="alert alert-success">

**Solution 01:**
</div>

In [3]:
print(type(df.isna()))
df.isna()

<class 'pandas.core.frame.DataFrame'>

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
15,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
31,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
34,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [4]:
print(df.isna().any())  
df.isna().sum()

date                False
customer_id         False
product_id          False
quantity            False
price               False
discount            False
revenue             False
store_id            False
region              False
payment_method      False
is_member           False
delivery_days       False
customer_age        False
gender              False
product_category    False
rating              False
return_status       False
feedback            False
shipping_cost        True
coupon_code         False
delivery_rating      True
dtype: bool

date                 0
customer_id          0
product_id           0
quantity             0
price                0
discount             0
revenue              0
store_id             0
region               0
payment_method       0
is_member            0
delivery_days        0
customer_age         0
gender               0
product_category     0
rating               0
return_status        0
feedback             0
shipping_cost        5
coupon_code          0
delivery_rating     11
dtype: int64

<div class="alert alert-warning">

**2. Identify Columns with Missing Values**

**Write a Pandas program to identify the column(s) of a given DataFrame which have at least one missing value.**

</div>

In [5]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1277,125,2,34.92,0.25,52.3800,2,North,Credit Card,...,5,44,Male,Clothing,2.6,Returned,Negative,13.31,SAVE10,1.4
1,2023-01-02,1734,124,5,38.04,0.22,148.3560,6,North,Credit Card,...,1,61,Female,Electronics,4.2,Not Returned,Positive,NaN,WELCOME5,2.1
2,2023-01-03,1678,100,2,29.37,0.04,56.3904,5,North,Online,...,4,62,Other,Clothing,4.9,Not Returned,Positive,7.71,WELCOME5,4.7
3,2023-01-04,1091,155,2,98.77,0.25,148.1550,2,West,Cash,...,2,43,Female,Food,1.6,Returned,Negative,NaN,FREESHIP,5.0
4,2023-01-05,1231,144,6,96.13,0.23,444.1206,2,North,Online,...,6,37,Other,Electronics,4.3,Returned,Neutral,14.05,nan,NaN
5,2023-01-06,1616,104,6,21.91,0.12,115.6848,3,South,Online,...,6,55,Female,Books,2.3,Returned,Positive,14.90,SAVE10,1.7
6,2023-01-07,1595,189,4,82.24,0.27,240.1408,7,East,Cash,...,4,60,Other,Food,3.2,Not Returned,Positive,10.35,WELCOME5,4.7
7,2023-01-08,1895,124,5,14.02,0.27,51.1730,5,West,Online,...,4,27,Other,Books,1.3,Returned,Positive,18.55,nan,4.5
8,2023-01-09,1915,123,1,26.63,0.14,22.9018,7,East,Credit Card,...,2,23,Female,Electronics,1.6,Not Returned,Negative,NaN,FREESHIP,NaN
9,2023-01-10,1668,120,5,16.88,0.13,73.4280,2,North,Credit Card,...,2,32,Male,Books,2.5,Returned,Negative,NaN,nan,NaN
10,2023-01-11,1870,166,8,77.97,0.06,586.3344,5,East,Credit Card,...,3,38,Male,Electronics,2.1,Returned,Positive,5.07,WELCOME5,4.7
11,2023-01-12,1666,130,2,57.02,0.02,111.7592,9,North,Online,...,2,46,Female,Food,2.8,Returned,Neutral,17.22,SAVE10,3.5
12,2023-01-13,1827,153,9,31.55,0.07,264.0735,1,West,Cash,...,5,64,Male,Books,1.9,Returned,Neutral,19.34,WELCOME5,3.9
13,2023-01-14,1588,132,6,10.41,0.11,55.5894,1,North,Credit Card,...,3,21,Male,Electronics,4.3,Returned,Neutral,17.11,SAVE10,3.7
14,2023-01-15,1603,125,4,47.54,0.15,161.6360,6,West,Cash,...,5,61,Female,Food,1.0,Returned,Neutral,NaN,SAVE10,4.9
15,2023-01-16,1896,195,4,56.74,0.09,206.5336,1,North,Online,...,3,26,Male,Books,3.3,Not Returned,Neutral,11.87,FREESHIP,3.9
16,2023-01-17,1715,164,4,21.31,0.17,70.7492,5,South,Credit Card,...,5,43,Female,Books,2.0,Not Returned,Negative,13.27,nan,4.4
17,2023-01-18,1206,159,3,17.98,0.09,49.0854,4,South,Cash,...,3,64,Female,Food,2.6,Not Returned,Positive,14.84,nan,2.8
18,2023-01-19,1109,141,8,66.78,0.00,534.2400,3,East,Cash,...,5,51,Male,Books,3.5,Not Returned,Positive,15.33,nan,NaN
19,2023-01-20,1657,166,1,83.29,0.18,68.2978,6,South,Cash,...,2,40,Other,Books,3.0,Returned,Positive,NaN,SAVE10,NaN
20,2023-01-21,1958,141,8,85.76,0.28,493.9776,9,South,Credit Card,...,5,24,Other,Clothing,1.5,Not Returned,Positive,14.68,nan,3.3
21,2023-01-22,1869,115,2,93.25,0.21,147.3350,5,East,Online,...,4,29,Female,Electronics,3.2,Not Returned,Positive,13.52,nan,2.6
22,2023-01-23,1159,186,2,52.32,0.07,97.3152,6,West,Online,...,5,35,Male,Clothing,4.6,Not Returned,Negative,6.96,nan,NaN
23,2023-01-24,1900,147,4,14.99,0.09,54.5636,3,South,Credit Card,...,5,38,Female,Clothing,1.6,Returned,Positive,19.04,nan,4.7
24,2023-01-25,1561,108,3,86.14,0.22,201.5676,3,North,Credit Card,...,4,19,Male,Books,4.4,Not Returned,Positive,NaN,FREESHIP,4.4
25,2023-01-26,1602,159,6,63.20,0.17,314.7360,5,East,Credit Card,...,4,44,Male,Clothing,2.5,Not Returned,Negative,NaN,SAVE10,3.3
26,2023-01-27,1427,181,8,74.02,0.07,550.7088,4,North,Online,...,4,42,Male,Electronics,4.9,Returned,Neutral,11.28,nan,2.6
27,2023-01-28,1912,124,8,76.93,0.20,492.3520,1,South,Cash,...,2,51,Other,Electronics,2.0,Not Returned,Neutral,14.84,FREESHIP,4.3
28,2023-01-29,1719,184,4,13.45,0.29,38.1980,8,North,Online,...,1,61,Female,Books,1.6,Returned,Negative,7.34,FREESHIP,1.6
29,2023-01-30,1924,197,1,70.59,0.25,52.9425,9,West,Credit Card,...,5,34,Male,Clothing,3.8,Returned,Neutral,5.98,nan,NaN
30,2023-01-31,1428,133,8,54.56,0.09,397.1968,7,South,Online,...,2,34,Female,Electronics,1.2,Not Returned,Positive,NaN,WELCOME5,2.4
31,2023-02-01,1205,126,2,41.62,0.08,76.5808,4,North,Online,...,1,55,Other,Food,1.6,Returned,Neutral,15.32,nan,NaN
32,2023-02-02,1060,100,1,28.06,0.18,23.0092,9,East,Cash,...,1,21,Female,Clothing,1.9,Not Returned,Positive,10.06,WELCOME5,3.3
33,2023-02-03,1330,177,2,23.15,0.19,37.5030,1,South,Cash,...,4,30,Other,Electronics,3.8,Returned,Negative,7.96,SAVE10,4.5
34,2023-02-04,1129,137,8,92.74,0.16,623.2128,3,East,Online,...,1,65,Other,Electronics,4.4,Not Returned,Negative,NaN,WELCOME5,4.9

<div class="alert alert-success">

**Solution 02:**
</div>

In [6]:
df.isna().any()
cols_have_na = df.isna().any()[lambda x: x].index.tolist()

<div class="alert alert-warning">

**3. Count Missing Values in Each Column**

**Write a Pandas program to count the number of missing values in each column of a given DataFrame.**

</div>

In [7]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1338,160,1,60.63,0.25,45.4725,9,North,Cash,...,3,26,Female,Clothing,2.3,Not Returned,Negative,12.58,WELCOME5,NaN
1,2023-01-02,1284,195,4,70.32,0.24,213.7728,8,North,Cash,...,2,18,Male,Electronics,3.3,Returned,Positive,13.84,nan,3.0
2,2023-01-03,1820,145,9,29.21,0.11,233.9721,3,South,Online,...,5,50,Other,Electronics,1.4,Not Returned,Neutral,17.37,FREESHIP,1.8
3,2023-01-04,1889,101,4,50.73,0.05,192.7740,6,East,Online,...,1,68,Other,Books,4.4,Returned,Positive,NaN,nan,NaN
4,2023-01-05,1457,111,8,59.44,0.01,470.7648,9,North,Online,...,3,28,Other,Clothing,1.3,Not Returned,Positive,6.30,nan,3.4
5,2023-01-06,1039,137,8,91.54,0.20,585.8560,3,North,Credit Card,...,6,43,Male,Books,2.0,Returned,Neutral,9.63,nan,4.2
6,2023-01-07,1710,166,9,35.42,0.29,226.3338,1,North,Online,...,4,23,Female,Food,1.5,Returned,Neutral,8.01,nan,1.9
7,2023-01-08,1346,164,7,18.49,0.07,120.3699,1,North,Online,...,6,53,Other,Clothing,3.0,Returned,Negative,NaN,nan,4.6
8,2023-01-09,1115,117,6,78.29,0.23,361.6998,9,West,Cash,...,5,61,Male,Food,2.9,Not Returned,Negative,12.24,nan,3.4
9,2023-01-10,1285,164,2,21.82,0.23,33.6028,3,South,Credit Card,...,1,51,Female,Books,1.1,Returned,Neutral,NaN,nan,NaN
10,2023-01-11,1854,167,1,29.10,0.20,23.2800,1,North,Credit Card,...,5,36,Male,Food,3.0,Not Returned,Neutral,19.73,SAVE10,NaN
11,2023-01-12,1432,139,7,15.95,0.26,82.6210,4,West,Cash,...,6,27,Male,Books,3.7,Not Returned,Neutral,NaN,nan,1.2
12,2023-01-13,1137,195,2,46.43,0.23,71.5022,6,East,Cash,...,1,42,Male,Books,2.2,Returned,Positive,NaN,SAVE10,2.7
13,2023-01-14,1019,116,2,39.89,0.01,78.9822,4,West,Credit Card,...,3,42,Male,Books,3.7,Not Returned,Neutral,NaN,SAVE10,1.1
14,2023-01-15,1704,151,7,71.60,0.27,365.8760,9,East,Cash,...,5,35,Male,Books,3.4,Returned,Neutral,NaN,WELCOME5,3.9
15,2023-01-16,1056,189,4,92.66,0.16,311.3376,6,North,Cash,...,3,28,Female,Clothing,2.4,Returned,Neutral,8.07,FREESHIP,NaN
16,2023-01-17,1690,167,9,46.48,0.11,372.3048,4,South,Credit Card,...,2,46,Female,Clothing,3.6,Returned,Negative,NaN,nan,NaN
17,2023-01-18,1358,165,9,14.71,0.21,104.5881,8,West,Credit Card,...,2,29,Male,Clothing,1.7,Not Returned,Neutral,NaN,nan,4.4
18,2023-01-19,1768,169,1,27.72,0.23,21.3444,6,East,Credit Card,...,5,58,Female,Books,1.5,Returned,Neutral,11.16,nan,4.4
19,2023-01-20,1542,166,2,32.06,0.24,48.7312,5,West,Cash,...,3,43,Female,Books,3.0,Returned,Positive,7.42,nan,NaN
20,2023-01-21,1171,154,5,50.69,0.10,228.1050,5,North,Online,...,2,19,Other,Clothing,4.9,Not Returned,Negative,13.51,nan,NaN
21,2023-01-22,1847,189,2,77.40,0.23,119.1960,9,North,Credit Card,...,2,19,Male,Books,3.0,Returned,Positive,16.78,FREESHIP,1.3
22,2023-01-23,1250,199,6,92.23,0.10,498.0420,7,West,Online,...,4,32,Male,Food,3.8,Returned,Negative,11.49,SAVE10,NaN
23,2023-01-24,1739,170,1,49.40,0.12,43.4720,8,West,Online,...,3,39,Male,Clothing,4.3,Returned,Negative,8.15,FREESHIP,2.4
24,2023-01-25,1923,189,2,47.12,0.13,81.9888,1,West,Credit Card,...,1,26,Other,Electronics,2.5,Returned,Positive,5.56,FREESHIP,3.4
25,2023-01-26,1170,185,9,34.07,0.15,260.6355,5,East,Cash,...,4,26,Male,Food,1.1,Not Returned,Neutral,NaN,nan,3.4
26,2023-01-27,1726,130,9,86.06,0.18,635.1228,8,North,Credit Card,...,5,48,Other,Clothing,1.1,Returned,Neutral,15.12,nan,NaN
27,2023-01-28,1712,161,8,78.13,0.05,593.7880,4,West,Cash,...,6,32,Male,Electronics,2.6,Not Returned,Negative,5.28,SAVE10,1.2
28,2023-01-29,1547,161,2,30.87,0.09,56.1834,3,North,Online,...,6,67,Male,Books,2.1,Returned,Negative,14.76,SAVE10,2.0
29,2023-01-30,1191,189,3,36.26,0.08,100.0776,6,South,Cash,...,1,21,Female,Electronics,3.7,Returned,Neutral,NaN,nan,1.3
30,2023-01-31,1643,126,6,98.87,0.07,551.6946,8,North,Online,...,1,27,Female,Electronics,1.7,Not Returned,Positive,8.83,SAVE10,1.2
31,2023-02-01,1013,186,2,75.53,0.14,129.9116,5,East,Cash,...,6,59,Other,Books,3.8,Not Returned,Neutral,6.76,nan,4.8
32,2023-02-02,1700,126,5,59.99,0.17,248.9585,2,West,Cash,...,3,59,Female,Clothing,5.0,Not Returned,Negative,8.15,FREESHIP,NaN
33,2023-02-03,1006,143,9,77.54,0.07,649.0098,6,West,Credit Card,...,2,32,Other,Books,2.0,Returned,Negative,14.38,nan,4.9
34,2023-02-04,1769,141,1,51.92,0.13,45.1704,5,East,Online,...,6,64,Female,Books,2.0,Not Returned,Positive,7.61,FREESHIP,2.4

<div class="alert alert-success">

**Solution 03:**
</div>

In [8]:
df.isna().sum()

date                 0
customer_id          0
product_id           0
quantity             0
price                0
discount             0
revenue              0
store_id             0
region               0
payment_method       0
is_member            0
delivery_days        0
customer_age         0
gender               0
product_category     0
rating               0
return_status        0
feedback             0
shipping_cost       11
coupon_code          0
delivery_rating     11
dtype: int64

<div class="alert alert-warning">

**4. Replace Non-Valuable Missing Values**

**Write a Pandas program to find and replace the missing values in a given DataFrame which do not have any valuable information.**

</div>

In [9]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values
0,2023-01-01,1346,181,8,89.80,0.09,653.7440,5,South,Credit Card,...,Male,Clothing,1.0,Returned,Negative,NaN,SAVE10,3.5,First-time customer,value_3
1,2023-01-02,1609,151,7,99.56,0.13,606.3204,4,West,Cash,...,Other,Books,4.1,Returned,Positive,15.74,SAVE10,3.1,Requested gift wrap,no_data
2,2023-01-03,1840,148,1,43.11,0.08,39.6612,9,South,Cash,...,Other,Clothing,3.5,Returned,Positive,19.39,nan,NaN,Requested gift wrap,value_5
3,2023-01-04,1053,167,3,30.08,0.13,78.5088,7,West,Cash,...,Male,Food,4.0,Returned,Positive,15.53,WELCOME5,3.0,Preferred morning delivery,unknown
4,2023-01-05,1971,131,7,80.81,0.20,452.5360,9,West,Cash,...,Male,Clothing,4.2,Not Returned,Neutral,12.26,nan,1.6,First-time customer,unknown
5,2023-01-06,1279,117,6,71.80,0.13,374.7960,5,North,Credit Card,...,Female,Food,4.5,Returned,Neutral,17.06,FREESHIP,NaN,Requested gift wrap,unknown
6,2023-01-07,1570,182,2,46.81,0.20,74.8960,7,West,Online,...,Male,Electronics,4.3,Returned,Positive,NaN,WELCOME5,2.8,no_data,value_4
7,2023-01-08,1602,148,6,84.31,0.00,505.8600,1,West,Online,...,Other,Clothing,4.4,Returned,Positive,14.82,nan,NaN,unknown,unknown
8,2023-01-09,1047,181,6,20.76,0.09,113.3496,1,East,Online,...,Other,Food,1.5,Returned,Neutral,NaN,WELCOME5,3.3,Frequent buyer,unknown
9,2023-01-10,1708,150,9,97.86,0.29,625.3254,2,North,Credit Card,...,Male,Books,4.6,Returned,Positive,NaN,WELCOME5,4.2,Requested gift wrap,unknown
10,2023-01-11,1810,194,5,44.82,0.18,183.7620,1,East,Credit Card,...,Other,Electronics,4.6,Returned,Negative,NaN,WELCOME5,2.1,Requested gift wrap,unknown
11,2023-01-12,1071,170,8,59.62,0.01,472.1904,5,South,Credit Card,...,Female,Clothing,2.5,Not Returned,Negative,15.24,FREESHIP,4.4,Used loyalty points,unknown
12,2023-01-13,1316,199,2,52.72,0.19,85.4064,9,West,Credit Card,...,Female,Clothing,4.4,Returned,Negative,11.44,WELCOME5,2.9,unknown,unknown
13,2023-01-14,1362,182,9,80.52,0.11,644.9652,3,North,Credit Card,...,Female,Books,2.6,Returned,Negative,NaN,nan,2.2,no_data,value_5
14,2023-01-15,1224,120,9,61.52,0.25,415.2600,3,North,Online,...,Male,Food,3.8,Not Returned,Neutral,NaN,SAVE10,4.0,no_data,no_data
15,2023-01-16,1985,184,8,47.87,0.17,317.8568,3,North,Online,...,Female,Books,2.3,Not Returned,Neutral,8.34,nan,NaN,Used loyalty points,no_data
16,2023-01-17,1232,180,5,85.77,0.14,368.8110,4,East,Cash,...,Male,Clothing,4.3,Not Returned,Negative,NaN,SAVE10,2.6,First-time customer,no_data
17,2023-01-18,1412,161,4,80.12,0.11,285.2272,3,West,Credit Card,...,Female,Clothing,3.5,Returned,Positive,7.56,nan,4.2,unknown,unknown
18,2023-01-19,1585,102,6,55.11,0.28,238.0752,1,East,Online,...,Female,Books,2.8,Not Returned,Negative,NaN,nan,1.5,Requested gift wrap,value_2
19,2023-01-20,1280,159,8,25.27,0.13,175.8792,2,North,Online,...,Male,Clothing,3.2,Not Returned,Neutral,16.77,nan,2.9,unknown,value_4
20,2023-01-21,1309,197,7,41.05,0.22,224.1330,6,North,Credit Card,...,Male,Books,2.2,Returned,Negative,15.00,SAVE10,2.9,unknown,no_data
21,2023-01-22,1402,168,8,65.12,0.09,474.0736,2,East,Online,...,Male,Electronics,4.0,Not Returned,Negative,11.49,SAVE10,NaN,no_data,no_data
22,2023-01-23,1264,130,1,30.86,0.10,27.7740,5,North,Cash,...,Other,Clothing,2.3,Returned,Negative,19.51,nan,4.8,no_data,value_5
23,2023-01-24,1969,130,6,56.85,0.10,306.9900,7,East,Online,...,Female,Books,3.2,Returned,Neutral,6.58,SAVE10,1.0,no_data,value_1
24,2023-01-25,1435,147,6,63.22,0.11,337.5948,7,North,Online,...,Female,Food,4.0,Not Returned,Positive,NaN,SAVE10,NaN,no_data,no_data
25,2023-01-26,1594,155,5,35.07,0.14,150.8010,9,North,Online,...,Female,Clothing,1.7,Not Returned,Positive,10.86,SAVE10,2.4,First-time customer,no_data
26,2023-01-27,1464,180,3,78.07,0.11,208.4469,9,West,Credit Card,...,Other,Electronics,5.0,Returned,Positive,NaN,SAVE10,NaN,no_data,no_data
27,2023-01-28,1189,174,9,38.37,0.25,258.9975,3,North,Cash,...,Male,Electronics,2.0,Returned,Positive,11.14,SAVE10,1.0,unknown,unknown
28,2023-01-29,1743,177,7,46.83,0.11,291.7509,1,South,Cash,...,Female,Electronics,4.6,Returned,Neutral,18.13,SAVE10,3.8,no_data,value_5
29,2023-01-30,1875,113,3,62.24,0.15,158.7120,1,North,Credit Card,...,Other,Electronics,1.9,Not Returned,Negative,16.75,SAVE10,3.9,unknown,no_data
30,2023-01-31,1114,133,2,59.71,0.09,108.6722,4,North,Online,...,Male,Books,2.4,Returned,Positive,19.61,nan,3.1,First-time customer,value_5
31,2023-02-01,1384,150,3,97.76,0.00,293.2800,6,South,Credit Card,...,Male,Food,1.4,Not Returned,Neutral,14.44,FREESHIP,1.6,unknown,value_4
32,2023-02-02,1511,174,1,83.63,0.21,66.0677,6,East,Cash,...,Female,Food,1.5,Not Returned,Positive,18.31,SAVE10,NaN,unknown,value_1
33,2023-02-03,1922,139,5,80.79,0.09,367.5945,3,North,Credit Card,...,Male,Books,2.4,Not Returned,Positive,5.17,WELCOME5,4.4,Frequent buyer,value_5
34,2023-02-04,1161,131,3,20.36,0.20,48.8640,4,West,Credit Card,...,Male,Electronics,4.5,Not Returned,Positive,NaN,SAVE10,2.6,no_data,value_1

<div class="alert alert-success">

**Solution 04:**
</div>

In [10]:
df.replace({
    'customer_note': {
        'no_data': np.nan,
        'unknown': np.nan
    },
    'customer_values': {
        'no_data': np.nan,
        'unknown': np.nan
    }
}, inplace=True)

display(df.isna().any())
display(df.isna().sum())

date                False
customer_id         False
product_id          False
quantity            False
price               False
discount            False
revenue             False
store_id            False
region              False
payment_method      False
is_member           False
delivery_days       False
customer_age        False
gender              False
product_category    False
rating              False
return_status       False
feedback            False
shipping_cost        True
coupon_code         False
delivery_rating      True
customer_note        True
customer_values      True
dtype: bool

date                 0
customer_id          0
product_id           0
quantity             0
price                0
discount             0
revenue              0
store_id             0
region               0
payment_method       0
is_member            0
delivery_days        0
customer_age         0
gender               0
product_category     0
rating               0
return_status        0
feedback             0
shipping_cost       12
coupon_code          0
delivery_rating      8
customer_note       19
customer_values     21
dtype: int64

<div class="alert alert-warning">

**5. Drop Rows with Any Missing Value**

**Write a Pandas program to drop the rows where at least one element is missing in a given DataFrame.**

</div>

In [11]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values
0,2023-01-01,1402,176,4,22.59,0.28,65.0592,1,South,Online,...,Female,Electronics,3.1,Returned,Positive,10.14,nan,1.5,unknown,no_data
1,2023-01-02,1547,176,1,62.48,0.11,55.6072,1,West,Online,...,Other,Food,2.7,Not Returned,Positive,18.39,nan,NaN,unknown,value_5
2,2023-01-03,1832,162,1,67.49,0.04,64.7904,4,South,Cash,...,Male,Food,1.6,Returned,Negative,16.52,WELCOME5,3.2,First-time customer,value_4
3,2023-01-04,1264,158,7,67.92,0.30,332.8080,6,North,Cash,...,Female,Books,5.0,Not Returned,Positive,10.01,FREESHIP,NaN,Requested gift wrap,value_1
4,2023-01-05,1349,117,8,79.13,0.18,519.0928,2,North,Credit Card,...,Other,Electronics,1.0,Returned,Positive,17.20,FREESHIP,2.8,First-time customer,value_5
5,2023-01-06,1283,113,6,26.56,0.10,143.4240,6,East,Online,...,Male,Electronics,2.0,Returned,Neutral,15.38,WELCOME5,NaN,no_data,value_4
6,2023-01-07,1126,127,5,54.82,0.23,211.0570,9,North,Cash,...,Female,Clothing,4.4,Not Returned,Positive,14.36,FREESHIP,NaN,no_data,value_3
7,2023-01-08,1458,192,7,65.01,0.06,427.7658,1,North,Credit Card,...,Male,Electronics,4.6,Returned,Negative,12.74,FREESHIP,3.7,unknown,no_data
8,2023-01-09,1888,124,4,54.20,0.05,205.9600,5,North,Credit Card,...,Male,Electronics,4.6,Returned,Negative,11.65,nan,3.9,Requested gift wrap,value_3
9,2023-01-10,1623,175,6,32.75,0.22,153.2700,8,West,Credit Card,...,Other,Food,2.4,Returned,Positive,NaN,FREESHIP,4.1,Frequent buyer,value_2
10,2023-01-11,1182,158,4,37.37,0.28,107.6256,2,West,Online,...,Other,Clothing,4.5,Returned,Negative,NaN,SAVE10,3.2,no_data,value_2
11,2023-01-12,1278,132,9,37.76,0.17,282.0672,7,West,Cash,...,Other,Books,1.3,Returned,Neutral,18.41,FREESHIP,4.0,Used loyalty points,value_4
12,2023-01-13,1840,178,1,81.12,0.16,68.1408,5,West,Online,...,Male,Books,4.2,Not Returned,Positive,13.97,FREESHIP,5.0,Frequent buyer,unknown
13,2023-01-14,1364,128,7,36.91,0.18,211.8634,4,North,Cash,...,Male,Food,1.7,Not Returned,Negative,NaN,nan,4.3,Preferred morning delivery,value_1
14,2023-01-15,1539,140,1,11.45,0.10,10.3050,2,West,Credit Card,...,Female,Electronics,1.7,Returned,Negative,17.74,nan,3.7,Preferred morning delivery,no_data
15,2023-01-16,1677,158,8,66.63,0.19,431.7624,9,East,Online,...,Male,Books,2.1,Returned,Negative,15.93,WELCOME5,NaN,no_data,no_data
16,2023-01-17,1504,183,2,52.94,0.28,76.2336,3,South,Online,...,Other,Electronics,4.9,Not Returned,Positive,NaN,WELCOME5,4.8,unknown,no_data
17,2023-01-18,1954,178,6,43.80,0.20,210.2400,4,West,Online,...,Female,Books,3.5,Returned,Positive,12.01,nan,3.8,Preferred morning delivery,no_data
18,2023-01-19,1667,108,6,56.67,0.10,306.0180,7,South,Cash,...,Female,Electronics,1.9,Not Returned,Negative,NaN,WELCOME5,1.8,First-time customer,no_data
19,2023-01-20,1517,180,1,53.19,0.18,43.6158,5,South,Cash,...,Male,Books,4.6,Returned,Neutral,NaN,nan,4.0,no_data,no_data
20,2023-01-21,1497,107,8,76.99,0.15,523.5320,8,East,Online,...,Female,Food,4.6,Not Returned,Positive,10.93,WELCOME5,2.5,no_data,no_data
21,2023-01-22,1105,147,7,82.69,0.07,538.3119,3,West,Online,...,Male,Clothing,3.6,Returned,Negative,9.33,nan,1.6,Used loyalty points,no_data
22,2023-01-23,1782,104,1,61.68,0.02,60.4464,8,North,Online,...,Other,Clothing,3.7,Returned,Negative,13.22,WELCOME5,NaN,no_data,value_5
23,2023-01-24,1201,104,7,89.84,0.17,521.9704,5,North,Online,...,Male,Food,2.4,Returned,Neutral,8.70,nan,2.7,no_data,value_3
24,2023-01-25,1476,190,9,43.09,0.09,352.9071,5,East,Credit Card,...,Other,Electronics,4.8,Not Returned,Negative,7.99,SAVE10,1.0,Preferred morning delivery,unknown
25,2023-01-26,1976,164,7,48.57,0.01,336.5901,1,South,Cash,...,Female,Electronics,1.0,Returned,Neutral,15.08,WELCOME5,NaN,no_data,unknown
26,2023-01-27,1983,197,3,39.75,0.06,112.0950,7,West,Online,...,Other,Electronics,2.0,Returned,Negative,9.62,nan,2.6,no_data,unknown
27,2023-01-28,1993,177,6,46.62,0.15,237.7620,7,East,Credit Card,...,Male,Books,1.2,Not Returned,Positive,11.52,WELCOME5,2.7,no_data,no_data
28,2023-01-29,1468,181,5,52.71,0.13,229.2885,3,North,Cash,...,Male,Clothing,3.0,Not Returned,Positive,19.86,nan,3.2,unknown,value_1
29,2023-01-30,1846,151,9,93.96,0.15,718.7940,7,South,Cash,...,Female,Food,2.2,Returned,Positive,9.59,nan,2.8,unknown,no_data
30,2023-01-31,1584,163,8,78.67,0.09,572.7176,1,South,Online,...,Female,Clothing,4.3,Not Returned,Neutral,5.76,WELCOME5,4.5,Used loyalty points,value_4
31,2023-02-01,1473,107,6,82.93,0.14,427.9188,4,North,Cash,...,Male,Electronics,2.9,Returned,Negative,9.61,WELCOME5,5.0,no_data,no_data
32,2023-02-02,1494,163,7,47.21,0.05,313.9465,5,South,Online,...,Other,Clothing,2.8,Returned,Negative,18.88,WELCOME5,1.6,Preferred morning delivery,no_data
33,2023-02-03,1942,165,9,66.34,0.16,501.5304,8,South,Credit Card,...,Other,Clothing,1.4,Returned,Positive,9.53,nan,1.1,unknown,value_1
34,2023-02-04,1794,125,4,61.74,0.11,219.7944,8,South,Cash,...,Male,Electronics,3.9,Returned,Negative,10.33,nan,1.5,Frequent buyer,no_data

<div class="alert alert-success">

**Solution 05:**
</div>

In [12]:
dropped_df = df.dropna(how='any')
display(dropped_df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values
0,2023-01-01,1402,176,4,22.59,0.28,65.0592,1,South,Online,...,Female,Electronics,3.1,Returned,Positive,10.14,nan,1.5,unknown,no_data
2,2023-01-03,1832,162,1,67.49,0.04,64.7904,4,South,Cash,...,Male,Food,1.6,Returned,Negative,16.52,WELCOME5,3.2,First-time customer,value_4
4,2023-01-05,1349,117,8,79.13,0.18,519.0928,2,North,Credit Card,...,Other,Electronics,1.0,Returned,Positive,17.20,FREESHIP,2.8,First-time customer,value_5
7,2023-01-08,1458,192,7,65.01,0.06,427.7658,1,North,Credit Card,...,Male,Electronics,4.6,Returned,Negative,12.74,FREESHIP,3.7,unknown,no_data
8,2023-01-09,1888,124,4,54.20,0.05,205.9600,5,North,Credit Card,...,Male,Electronics,4.6,Returned,Negative,11.65,nan,3.9,Requested gift wrap,value_3
11,2023-01-12,1278,132,9,37.76,0.17,282.0672,7,West,Cash,...,Other,Books,1.3,Returned,Neutral,18.41,FREESHIP,4.0,Used loyalty points,value_4
12,2023-01-13,1840,178,1,81.12,0.16,68.1408,5,West,Online,...,Male,Books,4.2,Not Returned,Positive,13.97,FREESHIP,5.0,Frequent buyer,unknown
14,2023-01-15,1539,140,1,11.45,0.10,10.3050,2,West,Credit Card,...,Female,Electronics,1.7,Returned,Negative,17.74,nan,3.7,Preferred morning delivery,no_data
17,2023-01-18,1954,178,6,43.80,0.20,210.2400,4,West,Online,...,Female,Books,3.5,Returned,Positive,12.01,nan,3.8,Preferred morning delivery,no_data
20,2023-01-21,1497,107,8,76.99,0.15,523.5320,8,East,Online,...,Female,Food,4.6,Not Returned,Positive,10.93,WELCOME5,2.5,no_data,no_data
21,2023-01-22,1105,147,7,82.69,0.07,538.3119,3,West,Online,...,Male,Clothing,3.6,Returned,Negative,9.33,nan,1.6,Used loyalty points,no_data
23,2023-01-24,1201,104,7,89.84,0.17,521.9704,5,North,Online,...,Male,Food,2.4,Returned,Neutral,8.70,nan,2.7,no_data,value_3
24,2023-01-25,1476,190,9,43.09,0.09,352.9071,5,East,Credit Card,...,Other,Electronics,4.8,Not Returned,Negative,7.99,SAVE10,1.0,Preferred morning delivery,unknown
26,2023-01-27,1983,197,3,39.75,0.06,112.0950,7,West,Online,...,Other,Electronics,2.0,Returned,Negative,9.62,nan,2.6,no_data,unknown
27,2023-01-28,1993,177,6,46.62,0.15,237.7620,7,East,Credit Card,...,Male,Books,1.2,Not Returned,Positive,11.52,WELCOME5,2.7,no_data,no_data
28,2023-01-29,1468,181,5,52.71,0.13,229.2885,3,North,Cash,...,Male,Clothing,3.0,Not Returned,Positive,19.86,nan,3.2,unknown,value_1
29,2023-01-30,1846,151,9,93.96,0.15,718.7940,7,South,Cash,...,Female,Food,2.2,Returned,Positive,9.59,nan,2.8,unknown,no_data
30,2023-01-31,1584,163,8,78.67,0.09,572.7176,1,South,Online,...,Female,Clothing,4.3,Not Returned,Neutral,5.76,WELCOME5,4.5,Used loyalty points,value_4
31,2023-02-01,1473,107,6,82.93,0.14,427.9188,4,North,Cash,...,Male,Electronics,2.9,Returned,Negative,9.61,WELCOME5,5.0,no_data,no_data
32,2023-02-02,1494,163,7,47.21,0.05,313.9465,5,South,Online,...,Other,Clothing,2.8,Returned,Negative,18.88,WELCOME5,1.6,Preferred morning delivery,no_data
33,2023-02-03,1942,165,9,66.34,0.16,501.5304,8,South,Credit Card,...,Other,Clothing,1.4,Returned,Positive,9.53,nan,1.1,unknown,value_1
34,2023-02-04,1794,125,4,61.74,0.11,219.7944,8,South,Cash,...,Male,Electronics,3.9,Returned,Negative,10.33,nan,1.5,Frequent buyer,no_data

<div class="alert alert-warning">

**6. Drop Columns with Any Missing Value**

**Write a Pandas program to drop the columns where at least one element is missing in a given DataFrame.**

</div>

In [13]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values
0,2023-01-01,1281,137,3,89.80,0.27,196.6620,5,North,Online,...,Female,Food,1.1,Not Returned,Neutral,19.27,FREESHIP,1.3,First-time customer,no_data
1,2023-01-02,1475,143,2,84.63,0.16,142.1784,8,West,Cash,...,Male,Food,1.1,Returned,Negative,NaN,nan,2.2,unknown,unknown
2,2023-01-03,1917,188,4,10.01,0.15,34.0340,9,North,Cash,...,Male,Clothing,2.3,Returned,Negative,15.06,WELCOME5,NaN,Preferred morning delivery,unknown
3,2023-01-04,1169,139,6,48.34,0.18,237.8328,6,North,Credit Card,...,Male,Books,2.7,Not Returned,Negative,11.77,nan,3.3,Preferred morning delivery,value_1
4,2023-01-05,1226,140,1,29.77,0.17,24.7091,6,North,Cash,...,Male,Clothing,1.5,Returned,Positive,14.15,nan,2.9,unknown,unknown
5,2023-01-06,1150,139,7,26.62,0.27,136.0282,8,West,Online,...,Other,Books,1.1,Returned,Neutral,NaN,FREESHIP,3.4,no_data,no_data
6,2023-01-07,1177,104,9,71.01,0.12,562.3992,9,East,Cash,...,Male,Electronics,5.0,Returned,Neutral,15.72,WELCOME5,3.8,Frequent buyer,value_5
7,2023-01-08,1342,186,5,97.85,0.12,430.5400,7,West,Cash,...,Female,Books,4.6,Returned,Negative,17.36,nan,NaN,unknown,value_4
8,2023-01-09,1944,191,8,28.54,0.18,187.2224,9,East,Credit Card,...,Female,Food,2.4,Returned,Negative,NaN,SAVE10,4.9,Requested gift wrap,unknown
9,2023-01-10,1056,179,7,61.47,0.17,357.1407,9,West,Online,...,Female,Food,4.3,Not Returned,Positive,NaN,SAVE10,1.7,Frequent buyer,unknown
10,2023-01-11,1699,192,2,26.38,0.21,41.6804,3,North,Cash,...,Other,Clothing,1.5,Not Returned,Positive,17.81,WELCOME5,3.4,no_data,value_2
11,2023-01-12,1366,155,2,18.34,0.28,26.4096,5,North,Cash,...,Male,Electronics,2.9,Not Returned,Negative,10.18,nan,NaN,Preferred morning delivery,unknown
12,2023-01-13,1494,198,5,64.88,0.02,317.9120,9,South,Credit Card,...,Male,Electronics,4.2,Not Returned,Positive,9.67,nan,5.0,Requested gift wrap,no_data
13,2023-01-14,1466,119,9,45.88,0.22,322.0776,4,East,Credit Card,...,Other,Electronics,2.7,Returned,Neutral,15.60,FREESHIP,3.9,Requested gift wrap,unknown
14,2023-01-15,1859,182,1,89.07,0.19,72.1467,4,West,Online,...,Other,Books,1.3,Returned,Negative,NaN,FREESHIP,NaN,First-time customer,no_data
15,2023-01-16,1024,165,6,66.43,0.24,302.9208,6,South,Credit Card,...,Female,Food,2.2,Returned,Neutral,18.84,WELCOME5,NaN,unknown,no_data
16,2023-01-17,1989,160,2,32.28,0.14,55.5216,5,East,Cash,...,Female,Books,4.9,Not Returned,Neutral,10.57,nan,NaN,Frequent buyer,value_1
17,2023-01-18,1576,115,4,42.44,0.16,142.5984,2,West,Online,...,Male,Food,3.6,Returned,Negative,6.61,SAVE10,1.2,unknown,value_4
18,2023-01-19,1538,137,2,30.68,0.08,56.4512,7,South,Online,...,Male,Food,3.2,Returned,Positive,5.12,FREESHIP,1.4,no_data,value_3
19,2023-01-20,1527,108,8,78.87,0.12,555.2448,3,South,Credit Card,...,Other,Clothing,2.8,Not Returned,Positive,12.17,WELCOME5,4.3,no_data,no_data
20,2023-01-21,1824,115,9,54.70,0.28,354.4560,3,West,Credit Card,...,Female,Food,2.8,Returned,Positive,NaN,FREESHIP,1.7,First-time customer,value_1
21,2023-01-22,1166,153,2,16.39,0.19,26.5518,1,West,Cash,...,Other,Clothing,2.6,Not Returned,Neutral,NaN,nan,2.1,no_data,value_2
22,2023-01-23,1975,136,3,53.07,0.29,113.0391,3,South,Cash,...,Male,Books,1.8,Not Returned,Neutral,NaN,nan,1.8,unknown,unknown
23,2023-01-24,1074,101,4,23.75,0.03,92.1500,3,North,Cash,...,Male,Books,3.3,Returned,Positive,NaN,nan,4.8,unknown,value_4
24,2023-01-25,1411,157,4,93.59,0.09,340.6676,1,North,Online,...,Male,Books,1.1,Not Returned,Positive,5.82,nan,NaN,no_data,value_3
25,2023-01-26,1401,108,6,19.23,0.22,89.9964,8,South,Cash,...,Male,Electronics,3.7,Not Returned,Positive,NaN,WELCOME5,1.0,unknown,no_data
26,2023-01-27,1906,162,8,96.39,0.10,694.0080,9,West,Online,...,Female,Books,4.0,Not Returned,Negative,NaN,nan,NaN,Frequent buyer,value_2
27,2023-01-28,1067,199,4,94.91,0.28,273.3408,2,South,Credit Card,...,Other,Books,3.1,Not Returned,Negative,NaN,nan,NaN,unknown,value_1
28,2023-01-29,1446,190,2,73.76,0.02,144.5696,2,North,Online,...,Female,Clothing,1.7,Not Returned,Neutral,9.47,WELCOME5,4.0,First-time customer,unknown
29,2023-01-30,1046,187,3,14.29,0.01,42.4413,4,North,Credit Card,...,Male,Electronics,4.4,Not Returned,Neutral,8.04,WELCOME5,2.3,unknown,value_5
30,2023-01-31,1812,161,4,41.87,0.27,122.2604,1,South,Online,...,Female,Food,1.5,Not Returned,Neutral,NaN,SAVE10,3.3,unknown,value_2
31,2023-02-01,1657,139,2,11.67,0.10,21.0060,9,South,Cash,...,Male,Books,1.0,Not Returned,Positive,16.97,SAVE10,2.1,unknown,unknown
32,2023-02-02,1744,171,2,49.95,0.17,82.9170,5,East,Credit Card,...,Other,Books,1.3,Not Returned,Neutral,13.54,WELCOME5,NaN,Requested gift wrap,value_5
33,2023-02-03,1939,150,1,47.64,0.11,42.3996,2,North,Cash,...,Male,Food,4.5,Not Returned,Positive,8.26,FREESHIP,2.2,unknown,value_4
34,2023-02-04,1394,151,5,52.52,0.04,252.0960,8,South,Online,...,Other,Electronics,3.4,Returned,Neutral,14.41,SAVE10,1.7,Used loyalty points,value_2

<div class="alert alert-success">

**Solution 06:**
</div>

In [14]:
# Drop columns with any missing value
dropped_df = df.dropna(axis=1, how='any')
display(dropped_df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,coupon_code,customer_note,customer_values
0,2023-01-01,1281,137,3,89.80,0.27,196.6620,5,North,Online,...,1,32,Female,Food,1.1,Not Returned,Neutral,FREESHIP,First-time customer,no_data
1,2023-01-02,1475,143,2,84.63,0.16,142.1784,8,West,Cash,...,3,50,Male,Food,1.1,Returned,Negative,nan,unknown,unknown
2,2023-01-03,1917,188,4,10.01,0.15,34.0340,9,North,Cash,...,6,46,Male,Clothing,2.3,Returned,Negative,WELCOME5,Preferred morning delivery,unknown
3,2023-01-04,1169,139,6,48.34,0.18,237.8328,6,North,Credit Card,...,1,43,Male,Books,2.7,Not Returned,Negative,nan,Preferred morning delivery,value_1
4,2023-01-05,1226,140,1,29.77,0.17,24.7091,6,North,Cash,...,4,61,Male,Clothing,1.5,Returned,Positive,nan,unknown,unknown
5,2023-01-06,1150,139,7,26.62,0.27,136.0282,8,West,Online,...,1,56,Other,Books,1.1,Returned,Neutral,FREESHIP,no_data,no_data
6,2023-01-07,1177,104,9,71.01,0.12,562.3992,9,East,Cash,...,6,67,Male,Electronics,5.0,Returned,Neutral,WELCOME5,Frequent buyer,value_5
7,2023-01-08,1342,186,5,97.85,0.12,430.5400,7,West,Cash,...,6,64,Female,Books,4.6,Returned,Negative,nan,unknown,value_4
8,2023-01-09,1944,191,8,28.54,0.18,187.2224,9,East,Credit Card,...,2,38,Female,Food,2.4,Returned,Negative,SAVE10,Requested gift wrap,unknown
9,2023-01-10,1056,179,7,61.47,0.17,357.1407,9,West,Online,...,3,51,Female,Food,4.3,Not Returned,Positive,SAVE10,Frequent buyer,unknown
10,2023-01-11,1699,192,2,26.38,0.21,41.6804,3,North,Cash,...,4,49,Other,Clothing,1.5,Not Returned,Positive,WELCOME5,no_data,value_2
11,2023-01-12,1366,155,2,18.34,0.28,26.4096,5,North,Cash,...,2,25,Male,Electronics,2.9,Not Returned,Negative,nan,Preferred morning delivery,unknown
12,2023-01-13,1494,198,5,64.88,0.02,317.9120,9,South,Credit Card,...,1,38,Male,Electronics,4.2,Not Returned,Positive,nan,Requested gift wrap,no_data
13,2023-01-14,1466,119,9,45.88,0.22,322.0776,4,East,Credit Card,...,4,69,Other,Electronics,2.7,Returned,Neutral,FREESHIP,Requested gift wrap,unknown
14,2023-01-15,1859,182,1,89.07,0.19,72.1467,4,West,Online,...,2,61,Other,Books,1.3,Returned,Negative,FREESHIP,First-time customer,no_data
15,2023-01-16,1024,165,6,66.43,0.24,302.9208,6,South,Credit Card,...,3,29,Female,Food,2.2,Returned,Neutral,WELCOME5,unknown,no_data
16,2023-01-17,1989,160,2,32.28,0.14,55.5216,5,East,Cash,...,4,30,Female,Books,4.9,Not Returned,Neutral,nan,Frequent buyer,value_1
17,2023-01-18,1576,115,4,42.44,0.16,142.5984,2,West,Online,...,2,49,Male,Food,3.6,Returned,Negative,SAVE10,unknown,value_4
18,2023-01-19,1538,137,2,30.68,0.08,56.4512,7,South,Online,...,6,47,Male,Food,3.2,Returned,Positive,FREESHIP,no_data,value_3
19,2023-01-20,1527,108,8,78.87,0.12,555.2448,3,South,Credit Card,...,4,41,Other,Clothing,2.8,Not Returned,Positive,WELCOME5,no_data,no_data
20,2023-01-21,1824,115,9,54.70,0.28,354.4560,3,West,Credit Card,...,1,48,Female,Food,2.8,Returned,Positive,FREESHIP,First-time customer,value_1
21,2023-01-22,1166,153,2,16.39,0.19,26.5518,1,West,Cash,...,3,33,Other,Clothing,2.6,Not Returned,Neutral,nan,no_data,value_2
22,2023-01-23,1975,136,3,53.07,0.29,113.0391,3,South,Cash,...,1,63,Male,Books,1.8,Not Returned,Neutral,nan,unknown,unknown
23,2023-01-24,1074,101,4,23.75,0.03,92.1500,3,North,Cash,...,5,25,Male,Books,3.3,Returned,Positive,nan,unknown,value_4
24,2023-01-25,1411,157,4,93.59,0.09,340.6676,1,North,Online,...,4,33,Male,Books,1.1,Not Returned,Positive,nan,no_data,value_3
25,2023-01-26,1401,108,6,19.23,0.22,89.9964,8,South,Cash,...,2,37,Male,Electronics,3.7,Not Returned,Positive,WELCOME5,unknown,no_data
26,2023-01-27,1906,162,8,96.39,0.10,694.0080,9,West,Online,...,4,61,Female,Books,4.0,Not Returned,Negative,nan,Frequent buyer,value_2
27,2023-01-28,1067,199,4,94.91,0.28,273.3408,2,South,Credit Card,...,3,56,Other,Books,3.1,Not Returned,Negative,nan,unknown,value_1
28,2023-01-29,1446,190,2,73.76,0.02,144.5696,2,North,Online,...,2,37,Female,Clothing,1.7,Not Returned,Neutral,WELCOME5,First-time customer,unknown
29,2023-01-30,1046,187,3,14.29,0.01,42.4413,4,North,Credit Card,...,6,67,Male,Electronics,4.4,Not Returned,Neutral,WELCOME5,unknown,value_5
30,2023-01-31,1812,161,4,41.87,0.27,122.2604,1,South,Online,...,6,65,Female,Food,1.5,Not Returned,Neutral,SAVE10,unknown,value_2
31,2023-02-01,1657,139,2,11.67,0.10,21.0060,9,South,Cash,...,6,45,Male,Books,1.0,Not Returned,Positive,SAVE10,unknown,unknown
32,2023-02-02,1744,171,2,49.95,0.17,82.9170,5,East,Credit Card,...,1,45,Other,Books,1.3,Not Returned,Neutral,WELCOME5,Requested gift wrap,value_5
33,2023-02-03,1939,150,1,47.64,0.11,42.3996,2,North,Cash,...,4,28,Male,Food,4.5,Not Returned,Positive,FREESHIP,unknown,value_4
34,2023-02-04,1394,151,5,52.52,0.04,252.0960,8,South,Online,...,6,60,Other,Electronics,3.4,Returned,Neutral,SAVE10,Used loyalty points,value_2

<div class="alert alert-warning">

**7. Drop Rows with All Missing Values**

**Write a Pandas program to drop the rows where all elements are missing in a given DataFrame.**

</div>

In [15]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_83461/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1381.0,165.0,3.0,30.74,0.06,86.6868,4.0,North,Cash,...,Books,3.7,Returned,Neutral,NaN,FREESHIP,2.4,no_data,no_data,NaN
1,2023-01-02,1250.0,110.0,8.0,80.23,0.24,487.7984,3.0,North,Credit Card,...,Food,2.0,Not Returned,Neutral,8.82,SAVE10,NaN,unknown,value_4,NaN
2,2023-01-03,1500.0,189.0,8.0,73.13,0.12,514.8352,8.0,South,Online,...,Books,5.0,Returned,Neutral,11.50,SAVE10,NaN,Preferred morning delivery,unknown,NaN
3,2023-01-04,1404.0,131.0,5.0,25.69,0.09,116.8895,6.0,West,Credit Card,...,Books,3.6,Returned,Positive,8.88,WELCOME5,1.6,no_data,value_5,NaN
4,2023-01-05,1479.0,197.0,8.0,11.98,0.26,70.9216,9.0,West,Cash,...,Electronics,2.3,Returned,Negative,8.90,WELCOME5,1.5,Used loyalty points,no_data,NaN
5,2023-01-06,1661.0,199.0,7.0,74.95,0.02,514.1570,2.0,West,Cash,...,Electronics,4.4,Not Returned,Negative,19.87,WELCOME5,3.4,unknown,value_2,NaN
6,2023-01-07,1217.0,119.0,8.0,30.56,0.10,220.0320,5.0,East,Cash,...,Food,4.6,Not Returned,Neutral,15.62,WELCOME5,NaN,First-time customer,no_data,NaN
7,2023-01-08,1383.0,112.0,4.0,54.84,0.20,175.4880,5.0,West,Online,...,Clothing,1.4,Returned,Negative,17.77,nan,NaN,Frequent buyer,value_2,NaN
8,2023-01-09,1299.0,101.0,7.0,61.41,0.03,416.9739,6.0,South,Cash,...,Electronics,2.3,Returned,Negative,9.45,nan,2.2,no_data,no_data,NaN
9,2023-01-10,1622.0,112.0,5.0,29.93,0.13,130.1955,9.0,West,Online,...,Food,4.4,Not Returned,Neutral,18.59,nan,NaN,no_data,unknown,NaN
10,2023-01-11,1635.0,114.0,8.0,90.21,0.18,591.7776,1.0,East,Online,...,Books,2.5,Returned,Positive,16.76,nan,1.6,no_data,value_5,NaN
11,2023-01-12,1507.0,146.0,2.0,36.62,0.04,70.3104,6.0,West,Online,...,Electronics,3.3,Not Returned,Positive,13.07,nan,3.0,unknown,value_4,NaN
12,2023-01-13,1197.0,122.0,8.0,18.55,0.11,132.0760,8.0,West,Credit Card,...,Clothing,1.7,Returned,Negative,18.86,nan,3.7,Used loyalty points,unknown,NaN
13,2023-01-14,1827.0,180.0,3.0,44.64,0.07,124.5456,1.0,North,Credit Card,...,Food,2.6,Not Returned,Negative,NaN,FREESHIP,1.2,Preferred morning delivery,unknown,NaN
14,2023-01-15,1788.0,124.0,6.0,52.72,0.13,275.1984,3.0,South,Online,...,Books,4.8,Not Returned,Neutral,13.82,nan,4.0,Frequent buyer,unknown,NaN
15,2023-01-16,1397.0,103.0,8.0,53.56,0.29,304.2208,8.0,East,Cash,...,Electronics,4.6,Returned,Neutral,10.59,SAVE10,3.5,Used loyalty points,unknown,NaN
16,2023-01-17,1008.0,106.0,8.0,28.43,0.13,197.8728,8.0,East,Online,...,Food,1.7,Returned,Neutral,9.59,WELCOME5,1.3,Frequent buyer,no_data,NaN
17,2023-01-18,1474.0,149.0,3.0,95.88,0.24,218.6064,2.0,East,Credit Card,...,Clothing,3.3,Returned,Positive,11.93,WELCOME5,4.7,unknown,unknown,NaN
18,2023-01-19,1093.0,111.0,9.0,31.17,0.11,249.6717,5.0,West,Cash,...,Food,2.4,Returned,Neutral,13.54,WELCOME5,2.3,First-time customer,unknown,NaN
19,2023-01-20,1889.0,184.0,1.0,79.23,0.27,57.8379,9.0,West,Cash,...,Clothing,1.9,Not Returned,Negative,16.55,nan,NaN,unknown,unknown,NaN
20,2023-01-21,1582.0,183.0,3.0,88.38,0.30,185.5980,5.0,East,Cash,...,Food,2.6,Not Returned,Negative,NaN,nan,4.6,no_data,value_4,NaN
21,2023-01-22,1947.0,165.0,4.0,79.50,0.17,263.9400,4.0,East,Online,...,Food,1.1,Returned,Positive,10.50,FREESHIP,NaN,Used loyalty points,value_5,NaN
22,2023-01-23,1014.0,150.0,6.0,86.95,0.12,459.0960,1.0,East,Online,...,Electronics,3.7,Not Returned,Positive,14.72,nan,NaN,no_data,value_1,NaN
23,2023-01-24,1645.0,134.0,9.0,78.48,0.08,649.8144,4.0,North,Online,...,Clothing,4.0,Returned,Positive,15.25,WELCOME5,1.5,unknown,value_2,NaN
24,2023-01-25,1783.0,120.0,3.0,43.84,0.28,94.6944,6.0,North,Credit Card,...,Food,5.0,Not Returned,Positive,12.29,nan,5.0,unknown,value_3,NaN
25,2023-01-26,1473.0,135.0,3.0,83.99,0.17,209.1351,8.0,South,Online,...,Electronics,3.2,Not Returned,Negative,6.71,nan,3.9,Used loyalty points,no_data,NaN
26,2023-01-27,1897.0,132.0,6.0,96.36,0.05,549.2520,6.0,East,Credit Card,...,Electronics,4.2,Returned,Neutral,15.24,FREESHIP,1.2,unknown,value_2,NaN
27,2023-01-28,1625.0,174.0,2.0,54.45,0.10,98.0100,3.0,North,Cash,...,Electronics,2.1,Returned,Neutral,NaN,FREESHIP,NaN,Frequent buyer,value_2,NaN
28,2023-01-29,1736.0,102.0,5.0,41.79,0.26,154.6230,1.0,East,Credit Card,...,Clothing,2.7,Not Returned,Positive,7.48,SAVE10,2.7,unknown,unknown,NaN
29,2023-01-30,1647.0,194.0,5.0,90.69,0.25,340.0875,5.0,West,Cash,...,Clothing,3.8,Returned,Positive,6.11,WELCOME5,4.7,unknown,unknown,NaN
30,2023-01-31,1228.0,122.0,5.0,52.94,0.08,243.5240,2.0,South,Cash,...,Books,3.1,Not Returned,Positive,16.74,FREESHIP,4.8,no_data,no_data,NaN
31,2023-02-01,1314.0,131.0,4.0,40.15,0.16,134.9040,6.0,East,Credit Card,...,Electronics,1.2,Returned,Negative,6.71,nan,2.7,Used loyalty points,no_data,NaN
32,2023-02-02,1533.0,111.0,3.0,29.34,0.15,74.8170,8.0,South,Credit Card,...,Books,4.7,Returned,Negative,7.00,FREESHIP,1.0,Preferred morning delivery,no_data,NaN
33,2023-02-03,1208.0,194.0,5.0,90.81,0.29,322.3755,7.0,South,Credit Card,...,Clothing,2.6,Returned,Positive,NaN,nan,NaN,Frequent buyer,value_3,NaN
34,2023-02-04,1987.0,165.0,6.0,96.83,0.16,488.0232,1.0,South,Online,...,Books,1.1,Returned,Positive,NaN,FREESHIP,1.1,Requested gift wrap,value_5,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 07:**
</div>

In [16]:
# Write a Pandas program to drop the rows where all elements are missing in a given DataFrame
df_dropped = df.dropna(how='all')

# Display the DataFrame after dropping rows
display(df_dropped)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1381.0,165.0,3.0,30.74,0.06,86.6868,4.0,North,Cash,...,Books,3.7,Returned,Neutral,NaN,FREESHIP,2.4,no_data,no_data,NaN
1,2023-01-02,1250.0,110.0,8.0,80.23,0.24,487.7984,3.0,North,Credit Card,...,Food,2.0,Not Returned,Neutral,8.82,SAVE10,NaN,unknown,value_4,NaN
2,2023-01-03,1500.0,189.0,8.0,73.13,0.12,514.8352,8.0,South,Online,...,Books,5.0,Returned,Neutral,11.50,SAVE10,NaN,Preferred morning delivery,unknown,NaN
3,2023-01-04,1404.0,131.0,5.0,25.69,0.09,116.8895,6.0,West,Credit Card,...,Books,3.6,Returned,Positive,8.88,WELCOME5,1.6,no_data,value_5,NaN
4,2023-01-05,1479.0,197.0,8.0,11.98,0.26,70.9216,9.0,West,Cash,...,Electronics,2.3,Returned,Negative,8.90,WELCOME5,1.5,Used loyalty points,no_data,NaN
5,2023-01-06,1661.0,199.0,7.0,74.95,0.02,514.1570,2.0,West,Cash,...,Electronics,4.4,Not Returned,Negative,19.87,WELCOME5,3.4,unknown,value_2,NaN
6,2023-01-07,1217.0,119.0,8.0,30.56,0.10,220.0320,5.0,East,Cash,...,Food,4.6,Not Returned,Neutral,15.62,WELCOME5,NaN,First-time customer,no_data,NaN
7,2023-01-08,1383.0,112.0,4.0,54.84,0.20,175.4880,5.0,West,Online,...,Clothing,1.4,Returned,Negative,17.77,nan,NaN,Frequent buyer,value_2,NaN
8,2023-01-09,1299.0,101.0,7.0,61.41,0.03,416.9739,6.0,South,Cash,...,Electronics,2.3,Returned,Negative,9.45,nan,2.2,no_data,no_data,NaN
9,2023-01-10,1622.0,112.0,5.0,29.93,0.13,130.1955,9.0,West,Online,...,Food,4.4,Not Returned,Neutral,18.59,nan,NaN,no_data,unknown,NaN
10,2023-01-11,1635.0,114.0,8.0,90.21,0.18,591.7776,1.0,East,Online,...,Books,2.5,Returned,Positive,16.76,nan,1.6,no_data,value_5,NaN
11,2023-01-12,1507.0,146.0,2.0,36.62,0.04,70.3104,6.0,West,Online,...,Electronics,3.3,Not Returned,Positive,13.07,nan,3.0,unknown,value_4,NaN
12,2023-01-13,1197.0,122.0,8.0,18.55,0.11,132.0760,8.0,West,Credit Card,...,Clothing,1.7,Returned,Negative,18.86,nan,3.7,Used loyalty points,unknown,NaN
13,2023-01-14,1827.0,180.0,3.0,44.64,0.07,124.5456,1.0,North,Credit Card,...,Food,2.6,Not Returned,Negative,NaN,FREESHIP,1.2,Preferred morning delivery,unknown,NaN
14,2023-01-15,1788.0,124.0,6.0,52.72,0.13,275.1984,3.0,South,Online,...,Books,4.8,Not Returned,Neutral,13.82,nan,4.0,Frequent buyer,unknown,NaN
15,2023-01-16,1397.0,103.0,8.0,53.56,0.29,304.2208,8.0,East,Cash,...,Electronics,4.6,Returned,Neutral,10.59,SAVE10,3.5,Used loyalty points,unknown,NaN
16,2023-01-17,1008.0,106.0,8.0,28.43,0.13,197.8728,8.0,East,Online,...,Food,1.7,Returned,Neutral,9.59,WELCOME5,1.3,Frequent buyer,no_data,NaN
17,2023-01-18,1474.0,149.0,3.0,95.88,0.24,218.6064,2.0,East,Credit Card,...,Clothing,3.3,Returned,Positive,11.93,WELCOME5,4.7,unknown,unknown,NaN
18,2023-01-19,1093.0,111.0,9.0,31.17,0.11,249.6717,5.0,West,Cash,...,Food,2.4,Returned,Neutral,13.54,WELCOME5,2.3,First-time customer,unknown,NaN
19,2023-01-20,1889.0,184.0,1.0,79.23,0.27,57.8379,9.0,West,Cash,...,Clothing,1.9,Not Returned,Negative,16.55,nan,NaN,unknown,unknown,NaN
20,2023-01-21,1582.0,183.0,3.0,88.38,0.30,185.5980,5.0,East,Cash,...,Food,2.6,Not Returned,Negative,NaN,nan,4.6,no_data,value_4,NaN
21,2023-01-22,1947.0,165.0,4.0,79.50,0.17,263.9400,4.0,East,Online,...,Food,1.1,Returned,Positive,10.50,FREESHIP,NaN,Used loyalty points,value_5,NaN
22,2023-01-23,1014.0,150.0,6.0,86.95,0.12,459.0960,1.0,East,Online,...,Electronics,3.7,Not Returned,Positive,14.72,nan,NaN,no_data,value_1,NaN
23,2023-01-24,1645.0,134.0,9.0,78.48,0.08,649.8144,4.0,North,Online,...,Clothing,4.0,Returned,Positive,15.25,WELCOME5,1.5,unknown,value_2,NaN
24,2023-01-25,1783.0,120.0,3.0,43.84,0.28,94.6944,6.0,North,Credit Card,...,Food,5.0,Not Returned,Positive,12.29,nan,5.0,unknown,value_3,NaN
25,2023-01-26,1473.0,135.0,3.0,83.99,0.17,209.1351,8.0,South,Online,...,Electronics,3.2,Not Returned,Negative,6.71,nan,3.9,Used loyalty points,no_data,NaN
26,2023-01-27,1897.0,132.0,6.0,96.36,0.05,549.2520,6.0,East,Credit Card,...,Electronics,4.2,Returned,Neutral,15.24,FREESHIP,1.2,unknown,value_2,NaN
27,2023-01-28,1625.0,174.0,2.0,54.45,0.10,98.0100,3.0,North,Cash,...,Electronics,2.1,Returned,Neutral,NaN,FREESHIP,NaN,Frequent buyer,value_2,NaN
28,2023-01-29,1736.0,102.0,5.0,41.79,0.26,154.6230,1.0,East,Credit Card,...,Clothing,2.7,Not Returned,Positive,7.48,SAVE10,2.7,unknown,unknown,NaN
29,2023-01-30,1647.0,194.0,5.0,90.69,0.25,340.0875,5.0,West,Cash,...,Clothing,3.8,Returned,Positive,6.11,WELCOME5,4.7,unknown,unknown,NaN
30,2023-01-31,1228.0,122.0,5.0,52.94,0.08,243.5240,2.0,South,Cash,...,Books,3.1,Not Returned,Positive,16.74,FREESHIP,4.8,no_data,no_data,NaN
31,2023-02-01,1314.0,131.0,4.0,40.15,0.16,134.9040,6.0,East,Credit Card,...,Electronics,1.2,Returned,Negative,6.71,nan,2.7,Used loyalty points,no_data,NaN
32,2023-02-02,1533.0,111.0,3.0,29.34,0.15,74.8170,8.0,South,Credit Card,...,Books,4.7,Returned,Negative,7.00,FREESHIP,1.0,Preferred morning delivery,no_data,NaN
33,2023-02-03,1208.0,194.0,5.0,90.81,0.29,322.3755,7.0,South,Credit Card,...,Clothing,2.6,Returned,Positive,NaN,nan,NaN,Frequent buyer,value_3,NaN
34,2023-02-04,1987.0,165.0,6.0,96.83,0.16,488.0232,1.0,South,Online,...,Books,1.1,Returned,Positive,NaN,FREESHIP,1.1,Requested gift wrap,value_5,NaN

<div class="alert alert-warning">

**8. Keep Rows with at Least 2 NaN Values**

**Write a Pandas program to keep the rows with at least 2 NaN values in a given DataFrame.**

</div>

In [17]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Define informative and non-informative options
informative_notes = [
    "Requested gift wrap",
    "Preferred morning delivery",
    "Frequent buyer",
    "First-time customer",
    "Used loyalty points"
]

non_informative_notes = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_note():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_notes)
    else:
        return np.random.choice(informative_notes)

# Apply function to create the column
df['customer_note'] = [random_customer_note() for _ in range(len(df))]


# Define informative and non-informative options again for the second column
informative_values = [
    "value_1",
    "value_2",
    "value_3",
    "value_4",
    "value_5"
]

non_informative_values = ["no_data", "unknown"]

# Function to randomly pick one informative or one non-informative note
def random_customer_values():
    if np.random.rand() < 0.5:
        return np.random.choice(non_informative_values)
    else:
        return np.random.choice(informative_values)

df['customer_values'] = [random_customer_values() for _ in range(len(df))]

# Append a row of NaNs
df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

# Add a new all-NaN column
df['all_nan_column'] = np.nan

# Display the updated DataFrame
display(df)

/var/folders/fb/453r9d2j24g8x8tc93n2k6600000gn/T/ipykernel_83461/4116745759.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, pd.DataFrame([[np.nan] * df.shape[1]], columns=df.columns)], ignore_index=True)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-01,1616.0,198.0,6.0,78.48,0.28,339.0336,7.0,North,Cash,...,Electronics,2.9,Returned,Neutral,18.20,nan,2.9,Requested gift wrap,no_data,NaN
1,2023-01-02,1421.0,170.0,7.0,11.85,0.07,77.1435,4.0,West,Cash,...,Books,1.3,Not Returned,Neutral,6.87,FREESHIP,NaN,no_data,unknown,NaN
2,2023-01-03,1475.0,107.0,9.0,99.93,0.22,701.5086,4.0,North,Online,...,Food,4.3,Not Returned,Neutral,13.06,WELCOME5,3.8,Used loyalty points,value_5,NaN
3,2023-01-04,1644.0,128.0,2.0,47.67,0.04,91.5264,6.0,East,Credit Card,...,Electronics,1.2,Returned,Neutral,9.06,nan,2.4,no_data,value_4,NaN
4,2023-01-05,1035.0,122.0,1.0,32.69,0.28,23.5368,8.0,South,Credit Card,...,Electronics,2.8,Not Returned,Neutral,7.24,FREESHIP,NaN,Preferred morning delivery,value_5,NaN
5,2023-01-06,1556.0,154.0,4.0,48.65,0.27,142.0580,2.0,East,Cash,...,Food,1.2,Not Returned,Negative,11.77,FREESHIP,4.7,Requested gift wrap,no_data,NaN
6,2023-01-07,1418.0,126.0,7.0,52.71,0.05,350.5215,7.0,North,Cash,...,Food,4.6,Not Returned,Negative,NaN,SAVE10,NaN,unknown,unknown,NaN
7,2023-01-08,1157.0,155.0,3.0,94.70,0.04,272.7360,4.0,East,Online,...,Food,3.0,Returned,Negative,8.50,FREESHIP,4.6,no_data,no_data,NaN
8,2023-01-09,1832.0,145.0,8.0,99.85,0.01,790.8120,1.0,West,Cash,...,Clothing,2.4,Returned,Negative,5.93,FREESHIP,4.2,unknown,value_4,NaN
9,2023-01-10,1560.0,110.0,7.0,30.49,0.24,162.2068,8.0,West,Online,...,Clothing,4.2,Not Returned,Positive,15.52,SAVE10,NaN,Preferred morning delivery,no_data,NaN
10,2023-01-11,1276.0,177.0,7.0,75.48,0.27,385.7028,2.0,East,Credit Card,...,Electronics,3.4,Returned,Negative,8.83,WELCOME5,NaN,unknown,no_data,NaN
11,2023-01-12,1242.0,177.0,3.0,99.56,0.14,256.8648,5.0,South,Online,...,Clothing,3.9,Returned,Positive,11.23,SAVE10,4.9,Frequent buyer,value_3,NaN
12,2023-01-13,1894.0,157.0,4.0,69.17,0.25,207.5100,9.0,East,Cash,...,Electronics,4.3,Returned,Negative,19.06,nan,NaN,no_data,unknown,NaN
13,2023-01-14,1028.0,100.0,5.0,36.58,0.21,144.4910,9.0,West,Cash,...,Food,4.3,Returned,Negative,5.43,FREESHIP,NaN,Used loyalty points,value_3,NaN
14,2023-01-15,1877.0,109.0,2.0,52.03,0.26,77.0044,9.0,South,Credit Card,...,Books,3.4,Not Returned,Positive,9.59,WELCOME5,3.0,Used loyalty points,value_2,NaN
15,2023-01-16,1190.0,161.0,1.0,40.23,0.05,38.2185,2.0,North,Cash,...,Food,2.1,Returned,Negative,5.41,FREESHIP,2.4,Preferred morning delivery,value_2,NaN
16,2023-01-17,1873.0,196.0,7.0,53.61,0.05,356.5065,3.0,West,Cash,...,Books,3.4,Returned,Positive,NaN,WELCOME5,NaN,unknown,value_5,NaN
17,2023-01-18,1828.0,157.0,8.0,58.79,0.19,380.9592,5.0,South,Credit Card,...,Electronics,1.5,Returned,Neutral,NaN,WELCOME5,4.8,unknown,value_4,NaN
18,2023-01-19,1146.0,183.0,2.0,18.35,0.13,31.9290,1.0,South,Credit Card,...,Electronics,3.5,Returned,Neutral,NaN,FREESHIP,2.3,Used loyalty points,value_3,NaN
19,2023-01-20,1017.0,141.0,7.0,35.73,0.11,222.5979,2.0,North,Credit Card,...,Clothing,4.1,Not Returned,Neutral,5.15,WELCOME5,3.3,First-time customer,no_data,NaN
20,2023-01-21,1449.0,144.0,6.0,14.70,0.04,84.6720,1.0,South,Cash,...,Food,3.4,Not Returned,Negative,16.71,nan,2.5,unknown,value_3,NaN
21,2023-01-22,1275.0,181.0,9.0,92.39,0.03,806.5647,7.0,East,Credit Card,...,Electronics,4.8,Not Returned,Negative,NaN,nan,1.3,Used loyalty points,value_5,NaN
22,2023-01-23,1692.0,161.0,4.0,52.19,0.05,198.3220,5.0,South,Online,...,Electronics,2.1,Not Returned,Neutral,11.76,FREESHIP,NaN,unknown,unknown,NaN
23,2023-01-24,1357.0,125.0,8.0,53.20,0.02,417.0880,6.0,North,Cash,...,Books,2.0,Returned,Positive,11.45,SAVE10,NaN,Frequent buyer,no_data,NaN
24,2023-01-25,1237.0,146.0,6.0,43.28,0.22,202.5504,2.0,North,Online,...,Electronics,3.2,Returned,Neutral,19.15,FREESHIP,4.9,Used loyalty points,value_1,NaN
25,2023-01-26,1865.0,128.0,5.0,76.50,0.07,355.7250,7.0,South,Online,...,Books,3.8,Not Returned,Neutral,18.53,FREESHIP,4.5,unknown,no_data,NaN
26,2023-01-27,1095.0,120.0,1.0,53.49,0.00,53.4900,2.0,West,Online,...,Clothing,1.8,Returned,Negative,NaN,WELCOME5,NaN,First-time customer,value_2,NaN
27,2023-01-28,1930.0,165.0,3.0,78.22,0.06,220.5804,1.0,West,Cash,...,Food,2.5,Returned,Neutral,NaN,FREESHIP,1.7,unknown,value_5,NaN
28,2023-01-29,1830.0,191.0,9.0,11.30,0.13,88.4790,4.0,South,Credit Card,...,Books,3.9,Returned,Neutral,12.65,nan,3.7,First-time customer,unknown,NaN
29,2023-01-30,1972.0,123.0,7.0,85.59,0.26,443.3562,2.0,West,Cash,...,Clothing,1.8,Returned,Positive,5.89,nan,1.4,Frequent buyer,unknown,NaN
30,2023-01-31,1376.0,149.0,6.0,44.48,0.09,242.8608,1.0,North,Online,...,Food,2.5,Returned,Negative,9.23,SAVE10,1.2,no_data,value_1,NaN
31,2023-02-01,1380.0,119.0,8.0,70.07,0.15,476.4760,8.0,East,Cash,...,Food,2.6,Not Returned,Negative,19.21,nan,1.4,Frequent buyer,value_1,NaN
32,2023-02-02,1403.0,169.0,9.0,72.75,0.22,510.7050,1.0,East,Credit Card,...,Books,2.2,Not Returned,Neutral,18.76,nan,1.6,Preferred morning delivery,no_data,NaN
33,2023-02-03,1283.0,169.0,9.0,11.48,0.24,78.5232,1.0,West,Cash,...,Electronics,4.1,Returned,Neutral,14.90,FREESHIP,2.5,no_data,value_5,NaN
34,2023-02-04,1012.0,103.0,4.0,20.60,0.21,65.0960,8.0,West,Online,...,Books,4.2,Not Returned,Positive,18.14,SAVE10,2.4,no_data,value_2,NaN
35,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<div class="alert alert-success">

**Solution 08:**
</div>

In [18]:
pd.DataFrame.sum?

Signature:
pd.DataFrame.sum(
    self,
    axis: 'Axis | None' = 0,
    skipna: 'bool' = True,
    numeric_only: 'bool' = False,
    min_count: 'int' = 0,
    **kwargs,
)
Docstring:
Return the sum of the values over the requested axis.

This is equivalent to the method ``numpy.sum``.

Parameters
----------
axis : {index (0), columns (1)}
    Axis for the function to be applied on.
    For `Series` this parameter is unused and defaults to 0.

    .. warning::

        The behavior of DataFrame.sum with ``axis=None`` is deprecated,
        in a future version this will reduce over both axes and return a scalar
        To retain the old behavior, pass axis=0 (or do not pass axis).

    .. versionadded:: 2.0.0

skipna : bool, default True
    Exclude NA/null values when computing the result.
numeric_only : bool, default False
    Include only float, int, boolean columns. Not implemented for Series.

min_count : int, default 0
    The required number of valid values to perform the operation. If fewer than
    ``min_count`` non-NA values are present the result will be NA.
**kwargs
    Additional keyword arguments to be passed to the function.

Returns
-------
Series or scalar

See Also
--------
Series.sum : Return the sum.
Series.min : Return the minimum.
Series.max : Return the maximum.
Series.idxmin : Return the index of the minimum.
Series.idxmax : Return the index of the maximum.
DataFrame.sum : Return the sum over the requested axis.
DataFrame.min : Return the minimum over the requested axis.
DataFrame.max : Return the maximum over the requested axis.
DataFrame.idxmin : Return the index of the minimum over the requested axis.
DataFrame.idxmax : Return the index of the maximum over the requested axis.

Examples
--------
>>> idx = pd.MultiIndex.from_arrays([
...     ['warm', 'warm', 'cold', 'cold'],
...     ['dog', 'falcon', 'fish', 'spider']],
...     names=['blooded', 'animal'])
>>> s = pd.Series([4, 2, 0, 8], name='legs', index=idx)
>>> s
blooded  animal
warm     dog       4
         falcon    2
cold     fish      0
         spider    8
Name: legs, dtype: int64

>>> s.sum()
14

By default, the sum of an empty or all-NA Series is ``0``.

>>> pd.Series([], dtype="float64").sum()  # min_count=0 is the default
0.0

This can be controlled with the ``min_count`` parameter. For example, if
you'd like the sum of an empty series to be NaN, pass ``min_count=1``.

>>> pd.Series([], dtype="float64").sum(min_count=1)
nan

Thanks to the ``skipna`` parameter, ``min_count`` handles all-NA and
empty series identically.

>>> pd.Series([np.nan]).sum()
0.0

>>> pd.Series([np.nan]).sum(min_count=1)
nan
File:      ~/dev/pandas-exercises/.venv/lib/python3.12/site-packages/pandas/core/frame.py
Type:      function

In [19]:
df.isnull().sum(axis=0)

date                 1
customer_id          1
product_id           1
quantity             1
price                1
discount             1
revenue              1
store_id             1
region               1
payment_method       1
is_member            1
delivery_days        1
customer_age         1
gender               1
product_category     1
rating               1
return_status        1
feedback             1
shipping_cost        8
coupon_code          1
delivery_rating     12
customer_note        1
customer_values      1
all_nan_column      36
dtype: int64

In [20]:
df.isnull().sum(axis=1)

0      1
1      2
2      1
3      1
4      2
5      1
6      3
7      1
8      1
9      2
10     2
11     1
12     2
13     2
14     1
15     1
16     3
17     2
18     2
19     1
20     1
21     2
22     2
23     2
24     1
25     1
26     3
27     2
28     1
29     1
30     1
31     1
32     1
33     1
34     1
35    24
dtype: int64

In [21]:
df_kept = df[df.isnull().sum(axis=1) >= 2]

# Display the DataFrame after keeping rows
display(df_kept.reset_index(drop=True))

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating,customer_note,customer_values,all_nan_column
0,2023-01-02,1421.0,170.0,7.0,11.85,0.07,77.1435,4.0,West,Cash,...,Books,1.3,Not Returned,Neutral,6.87,FREESHIP,NaN,no_data,unknown,NaN
1,2023-01-05,1035.0,122.0,1.0,32.69,0.28,23.5368,8.0,South,Credit Card,...,Electronics,2.8,Not Returned,Neutral,7.24,FREESHIP,NaN,Preferred morning delivery,value_5,NaN
2,2023-01-07,1418.0,126.0,7.0,52.71,0.05,350.5215,7.0,North,Cash,...,Food,4.6,Not Returned,Negative,NaN,SAVE10,NaN,unknown,unknown,NaN
3,2023-01-10,1560.0,110.0,7.0,30.49,0.24,162.2068,8.0,West,Online,...,Clothing,4.2,Not Returned,Positive,15.52,SAVE10,NaN,Preferred morning delivery,no_data,NaN
4,2023-01-11,1276.0,177.0,7.0,75.48,0.27,385.7028,2.0,East,Credit Card,...,Electronics,3.4,Returned,Negative,8.83,WELCOME5,NaN,unknown,no_data,NaN
5,2023-01-13,1894.0,157.0,4.0,69.17,0.25,207.5100,9.0,East,Cash,...,Electronics,4.3,Returned,Negative,19.06,nan,NaN,no_data,unknown,NaN
6,2023-01-14,1028.0,100.0,5.0,36.58,0.21,144.4910,9.0,West,Cash,...,Food,4.3,Returned,Negative,5.43,FREESHIP,NaN,Used loyalty points,value_3,NaN
7,2023-01-17,1873.0,196.0,7.0,53.61,0.05,356.5065,3.0,West,Cash,...,Books,3.4,Returned,Positive,NaN,WELCOME5,NaN,unknown,value_5,NaN
8,2023-01-18,1828.0,157.0,8.0,58.79,0.19,380.9592,5.0,South,Credit Card,...,Electronics,1.5,Returned,Neutral,NaN,WELCOME5,4.8,unknown,value_4,NaN
9,2023-01-19,1146.0,183.0,2.0,18.35,0.13,31.9290,1.0,South,Credit Card,...,Electronics,3.5,Returned,Neutral,NaN,FREESHIP,2.3,Used loyalty points,value_3,NaN
10,2023-01-22,1275.0,181.0,9.0,92.39,0.03,806.5647,7.0,East,Credit Card,...,Electronics,4.8,Not Returned,Negative,NaN,nan,1.3,Used loyalty points,value_5,NaN
11,2023-01-23,1692.0,161.0,4.0,52.19,0.05,198.3220,5.0,South,Online,...,Electronics,2.1,Not Returned,Neutral,11.76,FREESHIP,NaN,unknown,unknown,NaN
12,2023-01-24,1357.0,125.0,8.0,53.20,0.02,417.0880,6.0,North,Cash,...,Books,2.0,Returned,Positive,11.45,SAVE10,NaN,Frequent buyer,no_data,NaN
13,2023-01-27,1095.0,120.0,1.0,53.49,0.00,53.4900,2.0,West,Online,...,Clothing,1.8,Returned,Negative,NaN,WELCOME5,NaN,First-time customer,value_2,NaN
14,2023-01-28,1930.0,165.0,3.0,78.22,0.06,220.5804,1.0,West,Cash,...,Food,2.5,Returned,Neutral,NaN,FREESHIP,1.7,unknown,value_5,NaN
15,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN