[Pandas Missing Values](https://www.w3resource.com/python-exercises/pandas/missing-values/index.php)

In [1]:
import pandas as pd
import numpy as np

<div class="alert alert-warning">

**1. Detect Missing Values**

**Write a Pandas program to detect missing values of a given DataFrame. Display True or False.**

</div>

In [2]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1454,180,2,58.97,0.24,89.6344,6,South,Online,...,4,50,Female,Food,1.0,Returned,Positive,14.54,nan,2.2
1,2023-01-02,1141,183,8,53.45,0.12,376.2880,6,West,Online,...,1,62,Other,Food,2.2,Returned,Neutral,17.21,FREESHIP,4.9
2,2023-01-03,1376,112,2,83.25,0.28,119.8800,6,East,Online,...,6,50,Female,Electronics,2.7,Not Returned,Neutral,17.64,nan,1.5
3,2023-01-04,1546,113,7,75.76,0.27,387.1336,1,South,Online,...,5,68,Female,Food,3.0,Not Returned,Positive,7.24,nan,NaN
4,2023-01-05,1965,150,2,59.57,0.20,95.3120,6,North,Credit Card,...,1,33,Other,Clothing,4.5,Returned,Positive,14.44,nan,4.8
5,2023-01-06,1986,169,3,51.88,0.17,129.1812,1,East,Cash,...,4,69,Other,Books,2.1,Not Returned,Neutral,NaN,nan,1.3
6,2023-01-07,1686,132,5,23.65,0.13,102.8775,4,South,Cash,...,3,54,Male,Books,2.9,Returned,Negative,14.63,FREESHIP,4.6
7,2023-01-08,1228,166,9,91.51,0.17,683.5797,4,North,Cash,...,5,42,Female,Books,2.8,Returned,Positive,14.57,SAVE10,1.9
8,2023-01-09,1929,109,9,35.94,0.17,268.4718,6,East,Online,...,1,60,Female,Electronics,2.0,Returned,Positive,19.77,nan,4.8
9,2023-01-10,1598,109,1,15.31,0.03,14.8507,7,South,Online,...,4,68,Other,Clothing,3.0,Not Returned,Positive,16.54,nan,1.2
10,2023-01-11,1012,140,1,20.75,0.21,16.3925,5,North,Cash,...,5,56,Female,Electronics,1.8,Returned,Neutral,8.44,nan,NaN
11,2023-01-12,1264,156,1,45.47,0.24,34.5572,8,West,Online,...,5,67,Male,Food,4.5,Returned,Neutral,19.42,FREESHIP,3.4
12,2023-01-13,1902,118,9,51.83,0.03,452.4759,4,East,Online,...,5,32,Female,Electronics,2.1,Returned,Negative,17.39,SAVE10,3.3
13,2023-01-14,1246,147,5,46.96,0.08,216.0160,6,East,Cash,...,3,42,Female,Electronics,4.4,Not Returned,Neutral,5.61,nan,4.4
14,2023-01-15,1813,136,1,46.37,0.19,37.5597,6,North,Cash,...,1,49,Female,Clothing,2.8,Returned,Negative,8.48,WELCOME5,NaN
15,2023-01-16,1722,112,1,74.46,0.23,57.3342,3,North,Cash,...,1,28,Male,Clothing,4.8,Returned,Positive,8.96,WELCOME5,NaN
16,2023-01-17,1299,160,6,93.23,0.28,402.7536,8,South,Credit Card,...,6,41,Other,Electronics,2.8,Not Returned,Positive,15.52,FREESHIP,1.2
17,2023-01-18,1841,117,5,86.90,0.03,421.4650,3,South,Online,...,6,48,Female,Food,2.1,Not Returned,Positive,NaN,nan,4.9
18,2023-01-19,1110,115,6,41.93,0.11,223.9062,1,North,Online,...,1,49,Female,Food,4.3,Returned,Positive,11.31,SAVE10,4.8
19,2023-01-20,1750,113,9,18.59,0.06,157.2714,9,North,Cash,...,5,64,Other,Books,3.3,Not Returned,Neutral,NaN,nan,1.9
20,2023-01-21,1931,176,5,66.97,0.23,257.8345,9,West,Cash,...,2,38,Other,Books,2.5,Returned,Neutral,14.60,WELCOME5,3.3
21,2023-01-22,1924,112,9,97.24,0.01,866.4084,1,South,Credit Card,...,2,18,Male,Books,1.8,Returned,Positive,8.17,nan,4.4
22,2023-01-23,1034,108,9,31.41,0.22,220.4982,5,East,Credit Card,...,5,57,Male,Food,4.8,Returned,Positive,13.59,WELCOME5,1.2
23,2023-01-24,1578,191,2,30.91,0.18,50.6924,3,North,Cash,...,5,34,Female,Books,1.4,Returned,Neutral,19.48,nan,3.1
24,2023-01-25,1125,100,4,25.62,0.02,100.4304,1,East,Cash,...,4,47,Other,Food,2.7,Not Returned,Neutral,19.59,FREESHIP,3.6
25,2023-01-26,1826,175,3,53.31,0.23,123.1461,2,South,Credit Card,...,1,65,Male,Food,3.4,Not Returned,Negative,15.08,nan,3.2
26,2023-01-27,1114,165,7,64.86,0.14,390.4572,3,South,Online,...,6,33,Male,Books,4.4,Returned,Neutral,6.40,SAVE10,3.5
27,2023-01-28,1618,191,5,44.70,0.13,194.4450,5,West,Online,...,1,44,Female,Clothing,2.3,Returned,Negative,19.98,SAVE10,NaN
28,2023-01-29,1285,100,3,69.18,0.24,157.7304,2,North,Credit Card,...,6,55,Female,Clothing,4.7,Not Returned,Neutral,13.08,SAVE10,3.4
29,2023-01-30,1832,171,4,52.01,0.11,185.1556,7,West,Cash,...,4,25,Male,Clothing,3.7,Not Returned,Neutral,19.36,nan,NaN
30,2023-01-31,1783,107,8,42.94,0.24,261.0752,2,West,Cash,...,2,25,Male,Food,1.4,Returned,Neutral,5.47,nan,4.5
31,2023-02-01,1769,117,5,88.34,0.25,331.2750,3,West,Credit Card,...,6,66,Other,Electronics,4.8,Not Returned,Neutral,17.65,nan,3.9
32,2023-02-02,1155,154,8,49.34,0.08,363.1424,2,South,Credit Card,...,2,42,Male,Books,4.1,Returned,Negative,5.32,SAVE10,1.2
33,2023-02-03,1583,153,6,58.48,0.20,280.7040,8,West,Cash,...,6,44,Female,Food,1.7,Returned,Positive,NaN,nan,NaN
34,2023-02-04,1911,112,4,39.86,0.26,117.9856,6,South,Online,...,2,25,Female,Books,4.9,Not Returned,Neutral,5.27,SAVE10,1.0

<div class="alert alert-success">

**Solution 01:**
</div>

In [3]:
print(type(df.isna()))
df.isna()

<class 'pandas.core.frame.DataFrame'>

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
15,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
28,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
30,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,True
34,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [4]:
print(df.isna().any())  
df.isna().sum()

date                False
customer_id         False
product_id          False
quantity            False
price               False
discount            False
revenue             False
store_id            False
region              False
payment_method      False
is_member           False
delivery_days       False
customer_age        False
gender              False
product_category    False
rating              False
return_status       False
feedback            False
shipping_cost        True
coupon_code         False
delivery_rating      True
dtype: bool

date                0
customer_id         0
product_id          0
quantity            0
price               0
discount            0
revenue             0
store_id            0
region              0
payment_method      0
is_member           0
delivery_days       0
customer_age        0
gender              0
product_category    0
rating              0
return_status       0
feedback            0
shipping_cost       4
coupon_code         0
delivery_rating     7
dtype: int64

<div class="alert alert-warning">

**2. Identify Columns with Missing Values**

**Write a Pandas program to identify the column(s) of a given DataFrame which have at least one missing value.**

</div>

In [5]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1547,143,4,88.78,0.27,259.2376,4,West,Online,...,3,44,Male,Books,1.8,Returned,Positive,NaN,WELCOME5,2.6
1,2023-01-02,1235,172,8,72.79,0.13,506.6184,7,South,Credit Card,...,6,21,Male,Books,3.3,Not Returned,Neutral,8.41,nan,NaN
2,2023-01-03,1677,151,6,95.78,0.02,563.1864,4,North,Online,...,3,51,Other,Clothing,3.3,Not Returned,Neutral,NaN,FREESHIP,NaN
3,2023-01-04,1897,172,5,27.21,0.11,121.0845,9,West,Cash,...,3,57,Male,Food,1.9,Not Returned,Neutral,14.31,nan,NaN
4,2023-01-05,1718,196,1,85.77,0.23,66.0429,8,West,Cash,...,6,61,Male,Clothing,5.0,Not Returned,Neutral,19.32,SAVE10,2.4
5,2023-01-06,1026,185,1,36.69,0.29,26.0499,8,North,Online,...,3,25,Female,Books,4.6,Not Returned,Neutral,NaN,nan,3.7
6,2023-01-07,1949,145,2,58.16,0.16,97.7088,9,East,Credit Card,...,4,49,Male,Clothing,1.6,Not Returned,Negative,NaN,SAVE10,NaN
7,2023-01-08,1646,155,4,75.51,0.18,247.6728,3,North,Credit Card,...,5,30,Female,Food,4.4,Not Returned,Negative,6.30,FREESHIP,NaN
8,2023-01-09,1547,163,1,58.07,0.01,57.4893,6,East,Cash,...,6,43,Other,Books,2.2,Returned,Negative,6.83,SAVE10,3.3
9,2023-01-10,1863,180,6,40.83,0.03,237.6306,5,East,Credit Card,...,4,26,Female,Clothing,3.2,Returned,Positive,15.04,nan,NaN
10,2023-01-11,1615,157,5,51.28,0.30,179.4800,5,South,Cash,...,6,49,Female,Electronics,3.4,Returned,Neutral,19.26,WELCOME5,NaN
11,2023-01-12,1173,188,5,93.49,0.23,359.9365,8,North,Credit Card,...,6,28,Male,Books,1.5,Not Returned,Neutral,8.66,FREESHIP,3.8
12,2023-01-13,1243,174,2,64.61,0.13,112.4214,8,West,Credit Card,...,3,60,Other,Clothing,1.1,Not Returned,Neutral,7.53,nan,4.0
13,2023-01-14,1240,161,6,56.27,0.28,243.0864,1,North,Credit Card,...,6,54,Other,Food,2.6,Returned,Negative,5.09,FREESHIP,3.4
14,2023-01-15,1238,178,1,86.73,0.29,61.5783,9,West,Cash,...,4,25,Female,Clothing,2.5,Not Returned,Neutral,9.74,nan,3.9
15,2023-01-16,1997,146,3,56.95,0.06,160.5990,4,East,Credit Card,...,1,44,Male,Books,4.1,Returned,Positive,NaN,WELCOME5,4.2
16,2023-01-17,1478,172,1,82.35,0.19,66.7035,2,North,Online,...,6,45,Female,Electronics,1.6,Not Returned,Neutral,NaN,nan,NaN
17,2023-01-18,1007,173,6,28.93,0.13,151.0146,6,North,Credit Card,...,6,33,Female,Clothing,4.0,Returned,Negative,11.81,SAVE10,2.3
18,2023-01-19,1594,135,4,10.07,0.05,38.2660,4,West,Cash,...,6,39,Other,Clothing,3.8,Returned,Negative,9.43,SAVE10,2.1
19,2023-01-20,1821,127,7,55.50,0.20,310.8000,7,North,Cash,...,5,35,Female,Electronics,4.5,Not Returned,Positive,18.92,WELCOME5,NaN
20,2023-01-21,1508,170,2,59.57,0.05,113.1830,4,North,Cash,...,5,19,Female,Food,4.0,Returned,Neutral,7.78,nan,3.5
21,2023-01-22,1117,183,5,16.00,0.24,60.8000,1,East,Credit Card,...,6,58,Female,Books,1.2,Returned,Negative,17.34,WELCOME5,NaN
22,2023-01-23,1404,152,8,83.28,0.09,606.2784,6,North,Credit Card,...,6,61,Male,Clothing,1.2,Not Returned,Negative,NaN,FREESHIP,NaN
23,2023-01-24,1079,109,8,75.86,0.28,436.9536,4,East,Cash,...,3,69,Other,Books,2.9,Not Returned,Negative,7.91,WELCOME5,2.7
24,2023-01-25,1598,112,9,90.89,0.16,687.1284,8,North,Credit Card,...,3,49,Female,Food,3.5,Returned,Negative,7.80,FREESHIP,3.1
25,2023-01-26,1665,118,1,51.57,0.09,46.9287,9,West,Cash,...,1,62,Other,Food,3.9,Not Returned,Positive,NaN,FREESHIP,2.7
26,2023-01-27,1958,191,6,12.21,0.13,63.7362,9,East,Credit Card,...,2,61,Male,Food,2.2,Not Returned,Neutral,NaN,nan,2.7
27,2023-01-28,1903,190,9,61.13,0.15,467.6445,2,North,Online,...,4,48,Male,Clothing,1.9,Not Returned,Positive,19.40,SAVE10,1.4
28,2023-01-29,1153,155,8,89.06,0.15,605.6080,3,East,Online,...,4,56,Other,Clothing,5.0,Not Returned,Neutral,17.49,WELCOME5,NaN
29,2023-01-30,1893,168,4,78.91,0.16,265.1376,9,South,Credit Card,...,5,56,Female,Books,4.6,Not Returned,Positive,13.79,nan,1.2
30,2023-01-31,1269,123,9,69.70,0.18,514.3860,3,South,Credit Card,...,3,30,Male,Food,4.1,Returned,Negative,17.36,FREESHIP,NaN
31,2023-02-01,1404,195,5,46.47,0.23,178.9095,9,South,Credit Card,...,6,21,Female,Clothing,3.2,Returned,Positive,NaN,SAVE10,2.7
32,2023-02-02,1344,109,8,73.42,0.13,511.0032,6,East,Credit Card,...,2,20,Other,Food,1.2,Not Returned,Negative,16.13,WELCOME5,4.3
33,2023-02-03,1557,141,3,35.84,0.17,89.2416,3,North,Cash,...,4,22,Female,Clothing,2.0,Returned,Negative,10.87,FREESHIP,1.4
34,2023-02-04,1916,168,6,86.10,0.15,439.1100,3,North,Credit Card,...,3,57,Female,Books,2.0,Not Returned,Neutral,17.74,WELCOME5,2.6

<div class="alert alert-success">

**Solution 02:**
</div>

In [6]:
df.isna().any()
cols_have_na = df.isna().any()[lambda x: x].index.tolist()