[Pandas Data Cleaning and Preprocessing](https://www.w3resource.com/python-exercises/pandas/pandas-data-cleaning-and-preprocessing.php)

In [1]:
import pandas as pd
import numpy as np

<div class="alert alert-warning">

**1. Handling Missing Data in Pandas**

**Write a Pandas program to fill missing values (NaN) in a DataFrame using fillna().**

</div>

In [2]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1272,163,2,48.16,0.12,84.7616,1,East,Online,...,6,35,Female,Clothing,4.0,Returned,Negative,10.06,FREESHIP,NaN
1,2023-01-02,1901,133,8,19.28,0.06,144.9856,4,North,Cash,...,3,41,Other,Electronics,3.1,Returned,Positive,5.43,nan,4.9
2,2023-01-03,1126,133,9,63.06,0.18,465.3828,1,East,Online,...,4,36,Female,Electronics,2.8,Returned,Negative,NaN,WELCOME5,2.9
3,2023-01-04,1526,151,2,51.02,0.27,74.4892,1,West,Online,...,2,20,Male,Electronics,4.3,Not Returned,Neutral,14.71,nan,NaN
4,2023-01-05,1832,158,6,94.37,0.22,441.6516,8,East,Online,...,5,69,Male,Electronics,4.7,Not Returned,Positive,13.19,SAVE10,1.2
5,2023-01-06,1014,137,4,45.62,0.10,164.2320,5,South,Credit Card,...,2,58,Female,Books,3.7,Not Returned,Negative,12.33,WELCOME5,3.9
6,2023-01-07,1312,120,5,60.60,0.07,281.7900,3,East,Credit Card,...,3,58,Male,Food,3.3,Returned,Positive,NaN,SAVE10,1.5
7,2023-01-08,1896,122,2,79.85,0.02,156.5060,5,North,Online,...,3,45,Male,Electronics,4.1,Not Returned,Positive,NaN,nan,3.5
8,2023-01-09,1904,148,8,57.80,0.24,351.4240,2,West,Cash,...,1,43,Male,Food,4.7,Returned,Neutral,6.90,nan,3.2
9,2023-01-10,1555,170,6,13.34,0.01,79.2396,5,East,Cash,...,1,21,Male,Books,2.5,Not Returned,Positive,15.30,nan,1.4
10,2023-01-11,1138,125,6,46.54,0.16,234.5616,3,West,Credit Card,...,4,23,Other,Food,4.2,Returned,Positive,10.86,WELCOME5,NaN
11,2023-01-12,1039,193,2,45.91,0.11,81.7198,7,West,Credit Card,...,5,24,Other,Food,1.2,Not Returned,Negative,6.30,WELCOME5,3.0
12,2023-01-13,1310,154,6,96.79,0.22,452.9772,5,West,Credit Card,...,3,45,Female,Books,3.6,Returned,Positive,18.82,nan,NaN
13,2023-01-14,1939,109,9,37.03,0.23,256.6179,3,South,Cash,...,5,26,Female,Electronics,1.7,Returned,Neutral,NaN,WELCOME5,4.3
14,2023-01-15,1549,107,5,63.64,0.21,251.3780,7,East,Credit Card,...,6,48,Other,Food,4.5,Not Returned,Positive,12.27,nan,2.4
15,2023-01-16,1434,118,5,33.25,0.10,149.6250,6,North,Cash,...,3,26,Female,Electronics,1.1,Returned,Neutral,NaN,nan,NaN
16,2023-01-17,1105,189,3,92.23,0.09,251.7879,5,South,Online,...,2,68,Other,Food,4.1,Not Returned,Negative,8.16,nan,2.9
17,2023-01-18,1345,136,6,89.29,0.02,525.0252,2,East,Cash,...,1,58,Female,Clothing,1.2,Not Returned,Positive,12.11,SAVE10,1.4
18,2023-01-19,1118,111,3,24.39,0.27,53.4141,2,South,Credit Card,...,4,50,Other,Food,1.2,Not Returned,Negative,NaN,WELCOME5,3.9
19,2023-01-20,1643,105,2,99.50,0.16,167.1600,2,North,Credit Card,...,2,54,Female,Electronics,3.2,Not Returned,Negative,15.83,nan,NaN
20,2023-01-21,1365,161,3,81.95,0.26,181.9290,2,South,Cash,...,4,55,Male,Electronics,2.8,Returned,Neutral,NaN,WELCOME5,1.1
21,2023-01-22,1424,177,2,37.55,0.09,68.3410,9,North,Online,...,2,48,Other,Clothing,1.5,Not Returned,Neutral,5.06,nan,4.9
22,2023-01-23,1039,170,7,91.23,0.28,459.7992,2,West,Credit Card,...,1,63,Male,Electronics,1.6,Returned,Neutral,13.61,nan,1.3
23,2023-01-24,1375,199,4,87.60,0.24,266.3040,3,East,Credit Card,...,1,68,Female,Books,3.9,Returned,Positive,9.19,WELCOME5,3.7
24,2023-01-25,1751,164,2,25.84,0.05,49.0960,5,South,Credit Card,...,2,52,Female,Food,3.7,Not Returned,Positive,18.88,nan,3.3
25,2023-01-26,1887,117,3,55.19,0.23,127.4889,9,West,Cash,...,1,65,Other,Electronics,2.2,Not Returned,Neutral,17.80,nan,1.6
26,2023-01-27,1383,158,2,50.65,0.12,89.1440,1,West,Cash,...,5,34,Male,Clothing,2.9,Returned,Neutral,16.98,SAVE10,3.5
27,2023-01-28,1072,165,8,79.84,0.29,453.4912,6,East,Cash,...,1,55,Male,Books,2.5,Returned,Neutral,14.14,nan,NaN
28,2023-01-29,1712,158,7,81.56,0.10,513.8280,2,East,Online,...,3,38,Male,Food,3.5,Returned,Positive,13.77,nan,NaN
29,2023-01-30,1614,183,7,84.50,0.18,485.0300,4,North,Credit Card,...,2,66,Other,Electronics,1.7,Returned,Positive,16.71,SAVE10,2.7
30,2023-01-31,1600,153,3,44.82,0.14,115.6356,7,North,Cash,...,4,35,Other,Books,1.5,Returned,Negative,NaN,FREESHIP,NaN
31,2023-02-01,1644,198,7,20.35,0.00,142.4500,6,East,Online,...,5,27,Female,Food,1.4,Not Returned,Positive,16.84,SAVE10,4.4
32,2023-02-02,1024,163,6,16.05,0.09,87.6330,5,South,Cash,...,4,55,Female,Clothing,2.7,Returned,Positive,9.50,nan,4.9
33,2023-02-03,1884,158,7,12.44,0.19,70.5348,4,South,Cash,...,2,54,Other,Clothing,4.8,Returned,Neutral,NaN,SAVE10,4.3
34,2023-02-04,1559,175,3,73.40,0.12,193.7760,7,North,Credit Card,...,3,29,Female,Food,3.2,Not Returned,Neutral,NaN,nan,2.5

<div class="alert alert-success">

**Solution 01:**
</div>

In [3]:
# 1. Handling Missing Data in Pandas
# Write a Pandas program to fill missing values (NaN) in a DataFrame using fillna().
result_df = df.fillna({
    'shipping_cost': df['shipping_cost'].mean(),
    'coupon_code': 'No Coupon',
    'delivery_rating': df['delivery_rating'].mean()
})

result_df

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1272,163,2,48.16,0.12,84.7616,1,East,Online,...,6,35,Female,Clothing,4.0,Returned,Negative,10.06,FREESHIP,3.023077
1,2023-01-02,1901,133,8,19.28,0.06,144.9856,4,North,Cash,...,3,41,Other,Electronics,3.1,Returned,Positive,5.43,nan,4.900000
2,2023-01-03,1126,133,9,63.06,0.18,465.3828,1,East,Online,...,4,36,Female,Electronics,2.8,Returned,Negative,12.59,WELCOME5,2.900000
3,2023-01-04,1526,151,2,51.02,0.27,74.4892,1,West,Online,...,2,20,Male,Electronics,4.3,Not Returned,Neutral,14.71,nan,3.023077
4,2023-01-05,1832,158,6,94.37,0.22,441.6516,8,East,Online,...,5,69,Male,Electronics,4.7,Not Returned,Positive,13.19,SAVE10,1.200000
5,2023-01-06,1014,137,4,45.62,0.10,164.2320,5,South,Credit Card,...,2,58,Female,Books,3.7,Not Returned,Negative,12.33,WELCOME5,3.900000
6,2023-01-07,1312,120,5,60.60,0.07,281.7900,3,East,Credit Card,...,3,58,Male,Food,3.3,Returned,Positive,12.59,SAVE10,1.500000
7,2023-01-08,1896,122,2,79.85,0.02,156.5060,5,North,Online,...,3,45,Male,Electronics,4.1,Not Returned,Positive,12.59,nan,3.500000
8,2023-01-09,1904,148,8,57.80,0.24,351.4240,2,West,Cash,...,1,43,Male,Food,4.7,Returned,Neutral,6.90,nan,3.200000
9,2023-01-10,1555,170,6,13.34,0.01,79.2396,5,East,Cash,...,1,21,Male,Books,2.5,Not Returned,Positive,15.30,nan,1.400000
10,2023-01-11,1138,125,6,46.54,0.16,234.5616,3,West,Credit Card,...,4,23,Other,Food,4.2,Returned,Positive,10.86,WELCOME5,3.023077
11,2023-01-12,1039,193,2,45.91,0.11,81.7198,7,West,Credit Card,...,5,24,Other,Food,1.2,Not Returned,Negative,6.30,WELCOME5,3.000000
12,2023-01-13,1310,154,6,96.79,0.22,452.9772,5,West,Credit Card,...,3,45,Female,Books,3.6,Returned,Positive,18.82,nan,3.023077
13,2023-01-14,1939,109,9,37.03,0.23,256.6179,3,South,Cash,...,5,26,Female,Electronics,1.7,Returned,Neutral,12.59,WELCOME5,4.300000
14,2023-01-15,1549,107,5,63.64,0.21,251.3780,7,East,Credit Card,...,6,48,Other,Food,4.5,Not Returned,Positive,12.27,nan,2.400000
15,2023-01-16,1434,118,5,33.25,0.10,149.6250,6,North,Cash,...,3,26,Female,Electronics,1.1,Returned,Neutral,12.59,nan,3.023077
16,2023-01-17,1105,189,3,92.23,0.09,251.7879,5,South,Online,...,2,68,Other,Food,4.1,Not Returned,Negative,8.16,nan,2.900000
17,2023-01-18,1345,136,6,89.29,0.02,525.0252,2,East,Cash,...,1,58,Female,Clothing,1.2,Not Returned,Positive,12.11,SAVE10,1.400000
18,2023-01-19,1118,111,3,24.39,0.27,53.4141,2,South,Credit Card,...,4,50,Other,Food,1.2,Not Returned,Negative,12.59,WELCOME5,3.900000
19,2023-01-20,1643,105,2,99.50,0.16,167.1600,2,North,Credit Card,...,2,54,Female,Electronics,3.2,Not Returned,Negative,15.83,nan,3.023077
20,2023-01-21,1365,161,3,81.95,0.26,181.9290,2,South,Cash,...,4,55,Male,Electronics,2.8,Returned,Neutral,12.59,WELCOME5,1.100000
21,2023-01-22,1424,177,2,37.55,0.09,68.3410,9,North,Online,...,2,48,Other,Clothing,1.5,Not Returned,Neutral,5.06,nan,4.900000
22,2023-01-23,1039,170,7,91.23,0.28,459.7992,2,West,Credit Card,...,1,63,Male,Electronics,1.6,Returned,Neutral,13.61,nan,1.300000
23,2023-01-24,1375,199,4,87.60,0.24,266.3040,3,East,Credit Card,...,1,68,Female,Books,3.9,Returned,Positive,9.19,WELCOME5,3.700000
24,2023-01-25,1751,164,2,25.84,0.05,49.0960,5,South,Credit Card,...,2,52,Female,Food,3.7,Not Returned,Positive,18.88,nan,3.300000
25,2023-01-26,1887,117,3,55.19,0.23,127.4889,9,West,Cash,...,1,65,Other,Electronics,2.2,Not Returned,Neutral,17.80,nan,1.600000
26,2023-01-27,1383,158,2,50.65,0.12,89.1440,1,West,Cash,...,5,34,Male,Clothing,2.9,Returned,Neutral,16.98,SAVE10,3.500000
27,2023-01-28,1072,165,8,79.84,0.29,453.4912,6,East,Cash,...,1,55,Male,Books,2.5,Returned,Neutral,14.14,nan,3.023077
28,2023-01-29,1712,158,7,81.56,0.10,513.8280,2,East,Online,...,3,38,Male,Food,3.5,Returned,Positive,13.77,nan,3.023077
29,2023-01-30,1614,183,7,84.50,0.18,485.0300,4,North,Credit Card,...,2,66,Other,Electronics,1.7,Returned,Positive,16.71,SAVE10,2.700000
30,2023-01-31,1600,153,3,44.82,0.14,115.6356,7,North,Cash,...,4,35,Other,Books,1.5,Returned,Negative,12.59,FREESHIP,3.023077
31,2023-02-01,1644,198,7,20.35,0.00,142.4500,6,East,Online,...,5,27,Female,Food,1.4,Not Returned,Positive,16.84,SAVE10,4.400000
32,2023-02-02,1024,163,6,16.05,0.09,87.6330,5,South,Cash,...,4,55,Female,Clothing,2.7,Returned,Positive,9.50,nan,4.900000
33,2023-02-03,1884,158,7,12.44,0.19,70.5348,4,South,Cash,...,2,54,Other,Clothing,4.8,Returned,Neutral,12.59,SAVE10,4.300000
34,2023-02-04,1559,175,3,73.40,0.12,193.7760,7,North,Credit Card,...,3,29,Female,Food,3.2,Not Returned,Neutral,12.59,nan,2.500000

<div class="alert alert-warning">

**2. Removing Missing Data observations in Pandas**

**Write a Pandas program to drop rows with missing data.**

</div>

In [4]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1598,194,6,60.13,0.16,303.0552,7,East,Online,...,1,35,Other,Electronics,2.0,Not Returned,Neutral,12.95,nan,NaN
1,2023-01-02,1961,190,5,93.46,0.28,336.4560,3,North,Online,...,6,22,Other,Electronics,1.9,Returned,Negative,6.56,nan,3.0
2,2023-01-03,1789,137,3,99.08,0.23,228.8748,4,East,Cash,...,1,35,Other,Food,2.5,Returned,Positive,NaN,nan,2.3
3,2023-01-04,1570,164,1,15.52,0.26,11.4848,3,East,Online,...,5,30,Other,Electronics,4.5,Not Returned,Positive,12.20,nan,NaN
4,2023-01-05,1541,170,2,88.38,0.17,146.7108,8,North,Cash,...,1,26,Other,Electronics,1.5,Returned,Neutral,NaN,nan,4.5
5,2023-01-06,1841,134,3,39.69,0.08,109.5444,1,West,Cash,...,1,49,Female,Food,1.4,Not Returned,Neutral,19.67,nan,3.2
6,2023-01-07,1910,159,7,92.90,0.12,572.2640,1,North,Cash,...,4,21,Other,Electronics,4.9,Returned,Negative,10.67,SAVE10,1.4
7,2023-01-08,1255,140,2,13.21,0.05,25.0990,9,West,Online,...,4,29,Female,Books,3.5,Not Returned,Neutral,NaN,FREESHIP,3.4
8,2023-01-09,1607,188,8,25.52,0.11,181.7024,1,East,Online,...,6,49,Male,Food,4.8,Returned,Neutral,10.08,SAVE10,NaN
9,2023-01-10,1874,193,1,30.05,0.26,22.2370,2,North,Online,...,1,55,Male,Books,1.5,Returned,Negative,NaN,SAVE10,4.7
10,2023-01-11,1424,133,8,57.51,0.28,331.2576,9,South,Cash,...,6,35,Other,Clothing,3.4,Not Returned,Positive,12.11,nan,1.6
11,2023-01-12,1659,103,7,27.63,0.26,143.1234,9,North,Cash,...,2,67,Female,Electronics,3.1,Returned,Positive,13.57,WELCOME5,3.4
12,2023-01-13,1478,156,9,33.63,0.13,263.3229,2,North,Cash,...,5,65,Other,Books,3.4,Not Returned,Negative,NaN,nan,1.9
13,2023-01-14,1277,192,9,30.11,0.10,243.8910,9,East,Online,...,4,46,Female,Food,3.9,Not Returned,Neutral,17.00,FREESHIP,4.1
14,2023-01-15,1645,127,9,16.43,0.28,106.4664,8,West,Online,...,5,38,Female,Food,1.2,Not Returned,Negative,12.41,FREESHIP,NaN
15,2023-01-16,1061,197,2,93.93,0.04,180.3456,2,West,Credit Card,...,6,64,Male,Food,2.4,Not Returned,Positive,9.89,SAVE10,4.4
16,2023-01-17,1610,113,7,31.22,0.00,218.5400,9,North,Online,...,2,53,Female,Books,3.0,Not Returned,Positive,7.03,WELCOME5,1.4
17,2023-01-18,1703,122,6,36.29,0.02,213.3852,9,West,Credit Card,...,5,31,Male,Clothing,3.2,Not Returned,Positive,16.06,nan,3.0
18,2023-01-19,1651,165,1,78.89,0.06,74.1566,3,East,Online,...,3,63,Female,Electronics,4.3,Not Returned,Negative,12.55,WELCOME5,3.0
19,2023-01-20,1101,154,2,26.42,0.07,49.1412,1,East,Cash,...,1,38,Other,Books,2.5,Returned,Neutral,9.72,nan,NaN
20,2023-01-21,1158,176,3,56.45,0.16,142.2540,3,South,Online,...,4,42,Female,Books,2.7,Not Returned,Positive,5.29,WELCOME5,3.6
21,2023-01-22,1605,142,2,43.69,0.25,65.5350,5,South,Credit Card,...,3,54,Other,Clothing,3.8,Returned,Neutral,12.36,FREESHIP,4.6
22,2023-01-23,1349,123,9,85.27,0.16,644.6412,2,West,Credit Card,...,1,24,Other,Clothing,1.4,Returned,Neutral,NaN,FREESHIP,2.7
23,2023-01-24,1457,128,6,36.28,0.26,161.0832,3,North,Credit Card,...,5,36,Male,Food,1.1,Returned,Negative,NaN,FREESHIP,NaN
24,2023-01-25,1928,125,5,32.95,0.15,140.0375,4,North,Credit Card,...,3,42,Female,Food,4.8,Returned,Negative,11.84,nan,4.8
25,2023-01-26,1202,133,3,87.20,0.01,258.9840,2,West,Cash,...,6,62,Other,Food,2.4,Returned,Negative,19.79,FREESHIP,1.9
26,2023-01-27,1620,197,7,71.67,0.19,406.3689,9,West,Online,...,1,23,Male,Books,3.8,Not Returned,Neutral,NaN,WELCOME5,3.4
27,2023-01-28,1304,137,4,50.28,0.15,170.9520,7,South,Cash,...,2,65,Female,Books,1.5,Returned,Neutral,14.63,nan,5.0
28,2023-01-29,1050,138,8,61.78,0.20,395.3920,6,West,Credit Card,...,3,63,Male,Electronics,1.8,Not Returned,Neutral,18.74,SAVE10,NaN
29,2023-01-30,1389,170,4,64.13,0.14,220.6072,7,West,Online,...,3,55,Other,Books,3.5,Returned,Positive,NaN,nan,3.1
30,2023-01-31,1880,188,9,86.94,0.01,774.6354,9,North,Cash,...,1,61,Female,Food,1.2,Not Returned,Neutral,19.65,WELCOME5,4.1
31,2023-02-01,1920,110,5,15.62,0.24,59.3560,7,North,Credit Card,...,4,34,Male,Clothing,4.4,Returned,Negative,NaN,nan,3.9
32,2023-02-02,1680,145,7,22.38,0.16,131.5944,1,East,Credit Card,...,3,54,Other,Books,1.9,Not Returned,Neutral,NaN,WELCOME5,1.4
33,2023-02-03,1728,127,7,28.10,0.29,139.6570,8,East,Cash,...,6,68,Male,Clothing,1.7,Not Returned,Positive,16.44,nan,4.1
34,2023-02-04,1576,193,7,93.58,0.19,530.5986,9,North,Cash,...,6,28,Other,Books,3.2,Returned,Neutral,11.74,nan,NaN

<div class="alert alert-success">

**Solution 02:**
</div>

In [5]:
# 2. Handling Duplicates in Pandas
# Write a Pandas program to drop rows with missing data.

result_df = df.dropna()
result_df

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
1,2023-01-02,1961,190,5,93.46,0.28,336.4560,3,North,Online,...,6,22,Other,Electronics,1.9,Returned,Negative,6.56,nan,3.0
5,2023-01-06,1841,134,3,39.69,0.08,109.5444,1,West,Cash,...,1,49,Female,Food,1.4,Not Returned,Neutral,19.67,nan,3.2
6,2023-01-07,1910,159,7,92.90,0.12,572.2640,1,North,Cash,...,4,21,Other,Electronics,4.9,Returned,Negative,10.67,SAVE10,1.4
10,2023-01-11,1424,133,8,57.51,0.28,331.2576,9,South,Cash,...,6,35,Other,Clothing,3.4,Not Returned,Positive,12.11,nan,1.6
11,2023-01-12,1659,103,7,27.63,0.26,143.1234,9,North,Cash,...,2,67,Female,Electronics,3.1,Returned,Positive,13.57,WELCOME5,3.4
13,2023-01-14,1277,192,9,30.11,0.10,243.8910,9,East,Online,...,4,46,Female,Food,3.9,Not Returned,Neutral,17.00,FREESHIP,4.1
15,2023-01-16,1061,197,2,93.93,0.04,180.3456,2,West,Credit Card,...,6,64,Male,Food,2.4,Not Returned,Positive,9.89,SAVE10,4.4
16,2023-01-17,1610,113,7,31.22,0.00,218.5400,9,North,Online,...,2,53,Female,Books,3.0,Not Returned,Positive,7.03,WELCOME5,1.4
17,2023-01-18,1703,122,6,36.29,0.02,213.3852,9,West,Credit Card,...,5,31,Male,Clothing,3.2,Not Returned,Positive,16.06,nan,3.0
18,2023-01-19,1651,165,1,78.89,0.06,74.1566,3,East,Online,...,3,63,Female,Electronics,4.3,Not Returned,Negative,12.55,WELCOME5,3.0
20,2023-01-21,1158,176,3,56.45,0.16,142.2540,3,South,Online,...,4,42,Female,Books,2.7,Not Returned,Positive,5.29,WELCOME5,3.6
21,2023-01-22,1605,142,2,43.69,0.25,65.5350,5,South,Credit Card,...,3,54,Other,Clothing,3.8,Returned,Neutral,12.36,FREESHIP,4.6
24,2023-01-25,1928,125,5,32.95,0.15,140.0375,4,North,Credit Card,...,3,42,Female,Food,4.8,Returned,Negative,11.84,nan,4.8
25,2023-01-26,1202,133,3,87.20,0.01,258.9840,2,West,Cash,...,6,62,Other,Food,2.4,Returned,Negative,19.79,FREESHIP,1.9
27,2023-01-28,1304,137,4,50.28,0.15,170.9520,7,South,Cash,...,2,65,Female,Books,1.5,Returned,Neutral,14.63,nan,5.0
30,2023-01-31,1880,188,9,86.94,0.01,774.6354,9,North,Cash,...,1,61,Female,Food,1.2,Not Returned,Neutral,19.65,WELCOME5,4.1
33,2023-02-03,1728,127,7,28.10,0.29,139.6570,8,East,Cash,...,6,68,Male,Clothing,1.7,Not Returned,Positive,16.44,nan,4.1

<div class="alert alert-warning">

**3. Detecting Duplicates in Pandas**

**Write a Pandas program to detect duplicates using duplicated() method.**

</div>

In [6]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))


duplicates = df.sample(n=5, replace=False)  # Select 5 random rows without replacement
df = pd.concat([df, duplicates], ignore_index=True)

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1976,120,7,19.65,0.21,108.6645,6,North,Credit Card,...,5,20,Other,Books,4.6,Returned,Neutral,NaN,nan,2.4
1,2023-01-02,1817,107,6,20.30,0.10,109.6200,5,East,Cash,...,1,46,Male,Books,1.3,Returned,Negative,15.11,FREESHIP,1.2
2,2023-01-03,1058,173,8,66.19,0.13,460.6824,1,East,Credit Card,...,4,31,Male,Books,4.3,Not Returned,Positive,7.73,WELCOME5,3.5
3,2023-01-04,1673,161,4,38.28,0.00,153.1200,5,South,Credit Card,...,1,56,Female,Food,2.8,Not Returned,Negative,12.29,nan,2.7
4,2023-01-05,1254,126,1,85.57,0.25,64.1775,3,East,Online,...,2,27,Other,Electronics,4.5,Not Returned,Negative,7.68,nan,NaN
5,2023-01-06,1782,178,6,88.22,0.20,423.4560,9,South,Credit Card,...,4,41,Other,Clothing,4.5,Returned,Negative,5.26,WELCOME5,1.6
6,2023-01-07,1673,193,1,60.03,0.03,58.2291,2,West,Credit Card,...,1,52,Other,Electronics,1.7,Returned,Negative,10.34,SAVE10,NaN
7,2023-01-08,1769,112,9,69.08,0.07,578.1996,4,North,Credit Card,...,1,24,Other,Books,1.4,Not Returned,Positive,17.03,nan,1.8
8,2023-01-09,1552,124,4,81.95,0.03,317.9660,3,South,Online,...,6,57,Female,Books,4.7,Not Returned,Neutral,11.83,nan,4.6
9,2023-01-10,1731,111,8,13.62,0.12,95.8848,5,East,Cash,...,5,54,Female,Clothing,1.2,Not Returned,Positive,10.58,nan,4.6
10,2023-01-11,1750,148,8,41.17,0.24,250.3136,1,East,Online,...,2,42,Other,Electronics,4.9,Returned,Neutral,15.06,nan,3.1
11,2023-01-12,1231,114,5,16.46,0.14,70.7780,5,East,Online,...,4,55,Other,Books,1.7,Returned,Negative,NaN,SAVE10,NaN
12,2023-01-13,1055,198,6,35.73,0.16,180.0792,5,West,Online,...,2,19,Male,Food,4.3,Returned,Neutral,15.37,WELCOME5,4.5
13,2023-01-14,1137,104,3,45.03,0.04,129.6864,9,North,Credit Card,...,6,68,Other,Clothing,4.0,Returned,Negative,12.36,SAVE10,4.3
14,2023-01-15,1619,125,2,43.05,0.23,66.2970,1,South,Online,...,5,46,Other,Food,1.3,Returned,Negative,5.18,FREESHIP,4.9
15,2023-01-16,1546,141,9,56.52,0.13,442.5516,2,South,Online,...,6,58,Female,Food,3.9,Not Returned,Positive,5.50,WELCOME5,1.0
16,2023-01-17,1981,145,5,19.63,0.19,79.5015,6,West,Online,...,2,22,Female,Books,3.4,Returned,Neutral,12.53,nan,NaN
17,2023-01-18,1377,106,1,80.21,0.24,60.9596,6,East,Credit Card,...,6,50,Male,Food,2.6,Not Returned,Neutral,NaN,SAVE10,3.9
18,2023-01-19,1211,135,4,56.37,0.01,223.2252,7,East,Cash,...,4,56,Female,Electronics,1.8,Returned,Positive,NaN,nan,3.8
19,2023-01-20,1289,177,7,38.93,0.30,190.7570,5,North,Credit Card,...,4,48,Male,Clothing,2.6,Returned,Positive,9.04,SAVE10,2.5
20,2023-01-21,1914,163,3,83.61,0.10,225.7470,6,East,Credit Card,...,4,20,Male,Food,3.3,Returned,Negative,8.19,nan,4.2
21,2023-01-22,1620,184,2,64.30,0.10,115.7400,5,North,Online,...,1,31,Other,Books,2.4,Returned,Neutral,NaN,nan,2.5
22,2023-01-23,1208,163,3,38.99,0.03,113.4609,3,North,Online,...,2,57,Male,Food,2.5,Not Returned,Positive,9.39,FREESHIP,NaN
23,2023-01-24,1904,147,3,63.85,0.25,143.6625,1,North,Cash,...,2,59,Other,Clothing,3.3,Returned,Neutral,7.38,WELCOME5,2.4
24,2023-01-25,1279,109,6,49.69,0.17,247.4562,5,East,Cash,...,6,36,Male,Books,3.9,Returned,Negative,NaN,FREESHIP,4.9
25,2023-01-26,1595,108,9,93.36,0.07,781.4232,4,North,Online,...,6,20,Male,Electronics,3.0,Returned,Neutral,15.94,nan,NaN
26,2023-01-27,1872,163,4,95.61,0.24,290.6544,7,South,Cash,...,6,60,Female,Clothing,2.9,Returned,Negative,13.11,nan,NaN
27,2023-01-28,1978,119,9,91.34,0.23,632.9862,6,West,Credit Card,...,5,48,Female,Food,3.5,Returned,Negative,NaN,nan,NaN
28,2023-01-29,1548,143,4,49.94,0.15,169.7960,1,East,Credit Card,...,5,59,Male,Books,3.8,Not Returned,Negative,10.40,SAVE10,3.4
29,2023-01-30,1069,112,9,76.74,0.02,676.8468,4,North,Credit Card,...,1,68,Female,Food,4.3,Not Returned,Positive,6.20,nan,2.8
30,2023-01-31,1466,184,9,68.15,0.23,472.2795,4,South,Cash,...,2,66,Female,Books,3.8,Returned,Neutral,6.81,nan,NaN
31,2023-02-01,1420,146,3,15.96,0.26,35.4312,5,North,Online,...,3,20,Male,Books,1.1,Not Returned,Negative,14.15,FREESHIP,NaN
32,2023-02-02,1442,189,7,34.76,0.23,187.3564,4,West,Cash,...,6,46,Other,Clothing,2.4,Not Returned,Positive,17.22,SAVE10,1.1
33,2023-02-03,1661,162,4,37.21,0.24,113.1184,3,East,Credit Card,...,4,51,Male,Electronics,4.2,Returned,Neutral,NaN,SAVE10,3.6
34,2023-02-04,1681,180,2,97.95,0.28,141.0480,4,East,Cash,...,6,43,Other,Books,3.9,Returned,Neutral,9.15,SAVE10,4.3
35,2023-01-18,1377,106,1,80.21,0.24,60.9596,6,East,Credit Card,...,6,50,Male,Food,2.6,Not Returned,Neutral,NaN,SAVE10,3.9
36,2023-01-28,1978,119,9,91.34,0.23,632.9862,6,West,Credit Card,...,5,48,Female,Food,3.5,Returned,Negative,NaN,nan,NaN
37,2023-01-01,1976,120,7,19.65,0.21,108.6645,6,North,Credit Card,...,5,20,Other,Books,4.6,Returned,Neutral,NaN,nan,2.4
38,2023-01-14,1137,104,3,45.03,0.04,129.6864,9,North,Credit Card,...,6,68,Other,Clothing,4.0,Returned,Negative,12.36,SAVE10,4.3
39,2023-01-12,1231,114,5,16.46,0.14,70.7780,5,East,Online,...,4,55,Other,Books,1.7,Returned,Negative,NaN,SAVE10,NaN

<div class="alert alert-success">

**Solution 03:**
</div>

In [7]:
# 3. Data Cleaning Techniques
# Write a Pandas program to detect duplicates using duplicated() method.
duplicates = df.duplicated()
duplicates_df = df[duplicates]
duplicates_df

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
35,2023-01-18,1377,106,1,80.21,0.24,60.9596,6,East,Credit Card,...,6,50,Male,Food,2.6,Not Returned,Neutral,NaN,SAVE10,3.9
36,2023-01-28,1978,119,9,91.34,0.23,632.9862,6,West,Credit Card,...,5,48,Female,Food,3.5,Returned,Negative,NaN,nan,NaN
37,2023-01-01,1976,120,7,19.65,0.21,108.6645,6,North,Credit Card,...,5,20,Other,Books,4.6,Returned,Neutral,NaN,nan,2.4
38,2023-01-14,1137,104,3,45.03,0.04,129.6864,9,North,Credit Card,...,6,68,Other,Clothing,4.0,Returned,Negative,12.36,SAVE10,4.3
39,2023-01-12,1231,114,5,16.46,0.14,70.7780,5,East,Online,...,4,55,Other,Books,1.7,Returned,Negative,NaN,SAVE10,NaN

<div class="alert alert-warning">

**4. Handling Duplicates in Pandas**

**Write a Pandas program to remove duplicates rows from a DataFrame.**

</div>

In [8]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 100.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))


duplicates = df.sample(n=5, replace=False)  # Select 5 random rows without replacement
df = pd.concat([df, duplicates], ignore_index=True)

# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1890,168,9,39.70,0.17,296.5590,4,East,Online,...,5,53,Female,Books,4.9,Not Returned,Negative,5.37,nan,NaN
1,2023-01-02,1113,149,9,60.20,0.20,433.4400,9,East,Cash,...,2,37,Male,Books,3.8,Returned,Neutral,NaN,SAVE10,2.6
2,2023-01-03,1821,187,7,24.36,0.28,122.7744,1,North,Online,...,5,19,Male,Books,2.4,Not Returned,Neutral,9.58,FREESHIP,1.6
3,2023-01-04,1356,165,4,19.95,0.07,74.2140,6,East,Online,...,4,67,Other,Electronics,1.7,Not Returned,Neutral,11.20,nan,3.3
4,2023-01-05,1397,177,9,29.23,0.18,215.7174,9,North,Credit Card,...,4,34,Other,Books,1.9,Not Returned,Negative,6.06,nan,NaN
5,2023-01-06,1487,165,2,19.51,0.06,36.6788,4,East,Cash,...,6,46,Other,Books,1.4,Not Returned,Negative,NaN,nan,NaN
6,2023-01-07,1989,187,1,75.36,0.11,67.0704,1,South,Cash,...,3,58,Female,Clothing,1.1,Not Returned,Neutral,13.25,nan,1.3
7,2023-01-08,1561,188,5,37.38,0.28,134.5680,9,North,Credit Card,...,1,28,Female,Electronics,2.8,Returned,Negative,NaN,nan,NaN
8,2023-01-09,1061,117,7,79.99,0.22,436.7454,6,East,Cash,...,6,46,Female,Clothing,1.2,Not Returned,Positive,9.70,nan,1.8
9,2023-01-10,1813,191,2,12.95,0.11,23.0510,7,North,Credit Card,...,5,22,Female,Books,3.1,Not Returned,Neutral,NaN,nan,NaN
10,2023-01-11,1969,183,9,61.47,0.07,514.5039,5,East,Cash,...,2,34,Male,Electronics,1.2,Not Returned,Positive,6.55,nan,NaN
11,2023-01-12,1868,134,6,43.01,0.14,221.9316,7,North,Credit Card,...,3,59,Female,Clothing,4.1,Not Returned,Negative,11.33,FREESHIP,NaN
12,2023-01-13,1148,141,4,70.50,0.17,234.0600,2,North,Online,...,6,66,Other,Books,2.8,Returned,Neutral,15.75,FREESHIP,NaN
13,2023-01-14,1848,105,1,64.06,0.16,53.8104,6,South,Online,...,4,35,Male,Clothing,4.7,Returned,Negative,8.65,SAVE10,1.8
14,2023-01-15,1747,172,4,94.14,0.15,320.0760,1,North,Cash,...,3,64,Other,Books,1.3,Returned,Neutral,19.84,FREESHIP,2.8
15,2023-01-16,1057,116,1,22.96,0.08,21.1232,2,West,Cash,...,4,47,Female,Clothing,3.8,Not Returned,Neutral,16.52,FREESHIP,4.5
16,2023-01-17,1102,187,8,19.58,0.27,114.3472,3,South,Credit Card,...,1,50,Female,Food,2.1,Not Returned,Positive,11.63,SAVE10,NaN
17,2023-01-18,1839,122,2,84.84,0.02,166.2864,4,South,Cash,...,6,24,Other,Electronics,3.6,Not Returned,Negative,8.10,SAVE10,3.6
18,2023-01-19,1103,124,8,80.62,0.12,567.5648,1,South,Cash,...,4,27,Female,Clothing,4.9,Returned,Positive,17.57,nan,1.0
19,2023-01-20,1503,111,2,72.68,0.20,116.2880,2,South,Online,...,1,33,Other,Clothing,4.7,Returned,Positive,NaN,SAVE10,4.8
20,2023-01-21,1796,109,5,16.99,0.08,78.1540,2,East,Cash,...,5,46,Female,Food,2.0,Returned,Neutral,17.23,nan,1.0
21,2023-01-22,1393,184,2,42.12,0.11,74.9736,9,South,Credit Card,...,2,53,Other,Food,3.9,Not Returned,Positive,7.42,nan,2.3
22,2023-01-23,1726,186,2,91.36,0.01,180.8928,8,West,Credit Card,...,5,25,Other,Food,2.9,Returned,Neutral,10.79,FREESHIP,4.3
23,2023-01-24,1335,177,6,57.93,0.05,330.2010,9,North,Online,...,2,23,Female,Food,3.4,Not Returned,Neutral,NaN,nan,4.1
24,2023-01-25,1824,132,5,98.54,0.18,404.0140,8,West,Online,...,3,22,Other,Books,1.1,Returned,Neutral,14.92,SAVE10,2.8
25,2023-01-26,1659,125,4,78.37,0.21,247.6492,2,West,Credit Card,...,1,23,Male,Food,4.9,Returned,Neutral,NaN,nan,NaN
26,2023-01-27,1789,130,3,39.29,0.02,115.5126,2,North,Credit Card,...,3,65,Female,Electronics,4.7,Not Returned,Neutral,12.76,nan,1.3
27,2023-01-28,1779,154,9,25.15,0.22,176.5530,8,South,Credit Card,...,6,56,Female,Food,2.6,Returned,Neutral,12.01,nan,3.5
28,2023-01-29,1970,181,7,21.71,0.02,148.9306,6,East,Online,...,3,24,Female,Electronics,4.9,Not Returned,Positive,14.88,FREESHIP,NaN
29,2023-01-30,1336,141,4,33.82,0.17,112.2824,2,South,Online,...,6,40,Female,Clothing,2.4,Returned,Neutral,NaN,FREESHIP,4.2
30,2023-01-31,1611,110,9,99.00,0.04,855.3600,7,South,Cash,...,5,31,Female,Books,3.8,Returned,Neutral,6.92,nan,1.6
31,2023-02-01,1085,198,5,69.48,0.29,246.6540,7,East,Online,...,2,28,Other,Food,5.0,Returned,Positive,16.06,nan,NaN
32,2023-02-02,1651,169,9,35.02,0.12,277.3584,8,West,Cash,...,4,65,Other,Clothing,3.3,Returned,Neutral,18.73,WELCOME5,1.2
33,2023-02-03,1515,198,1,59.88,0.07,55.6884,9,West,Online,...,5,51,Other,Food,2.1,Returned,Positive,7.18,SAVE10,4.8
34,2023-02-04,1652,154,1,47.85,0.12,42.1080,3,East,Credit Card,...,6,33,Male,Electronics,2.2,Returned,Negative,NaN,FREESHIP,3.9
35,2023-01-05,1397,177,9,29.23,0.18,215.7174,9,North,Credit Card,...,4,34,Other,Books,1.9,Not Returned,Negative,6.06,nan,NaN
36,2023-01-25,1824,132,5,98.54,0.18,404.0140,8,West,Online,...,3,22,Other,Books,1.1,Returned,Neutral,14.92,SAVE10,2.8
37,2023-02-03,1515,198,1,59.88,0.07,55.6884,9,West,Online,...,5,51,Other,Food,2.1,Returned,Positive,7.18,SAVE10,4.8
38,2023-01-02,1113,149,9,60.20,0.20,433.4400,9,East,Cash,...,2,37,Male,Books,3.8,Returned,Neutral,NaN,SAVE10,2.6
39,2023-01-31,1611,110,9,99.00,0.04,855.3600,7,South,Cash,...,5,31,Female,Books,3.8,Returned,Neutral,6.92,nan,1.6

<div class="alert alert-success">

**Solution 04:**
</div>

In [9]:
df.drop_duplicates()

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1890,168,9,39.70,0.17,296.5590,4,East,Online,...,5,53,Female,Books,4.9,Not Returned,Negative,5.37,nan,NaN
1,2023-01-02,1113,149,9,60.20,0.20,433.4400,9,East,Cash,...,2,37,Male,Books,3.8,Returned,Neutral,NaN,SAVE10,2.6
2,2023-01-03,1821,187,7,24.36,0.28,122.7744,1,North,Online,...,5,19,Male,Books,2.4,Not Returned,Neutral,9.58,FREESHIP,1.6
3,2023-01-04,1356,165,4,19.95,0.07,74.2140,6,East,Online,...,4,67,Other,Electronics,1.7,Not Returned,Neutral,11.20,nan,3.3
4,2023-01-05,1397,177,9,29.23,0.18,215.7174,9,North,Credit Card,...,4,34,Other,Books,1.9,Not Returned,Negative,6.06,nan,NaN
5,2023-01-06,1487,165,2,19.51,0.06,36.6788,4,East,Cash,...,6,46,Other,Books,1.4,Not Returned,Negative,NaN,nan,NaN
6,2023-01-07,1989,187,1,75.36,0.11,67.0704,1,South,Cash,...,3,58,Female,Clothing,1.1,Not Returned,Neutral,13.25,nan,1.3
7,2023-01-08,1561,188,5,37.38,0.28,134.5680,9,North,Credit Card,...,1,28,Female,Electronics,2.8,Returned,Negative,NaN,nan,NaN
8,2023-01-09,1061,117,7,79.99,0.22,436.7454,6,East,Cash,...,6,46,Female,Clothing,1.2,Not Returned,Positive,9.70,nan,1.8
9,2023-01-10,1813,191,2,12.95,0.11,23.0510,7,North,Credit Card,...,5,22,Female,Books,3.1,Not Returned,Neutral,NaN,nan,NaN
10,2023-01-11,1969,183,9,61.47,0.07,514.5039,5,East,Cash,...,2,34,Male,Electronics,1.2,Not Returned,Positive,6.55,nan,NaN
11,2023-01-12,1868,134,6,43.01,0.14,221.9316,7,North,Credit Card,...,3,59,Female,Clothing,4.1,Not Returned,Negative,11.33,FREESHIP,NaN
12,2023-01-13,1148,141,4,70.50,0.17,234.0600,2,North,Online,...,6,66,Other,Books,2.8,Returned,Neutral,15.75,FREESHIP,NaN
13,2023-01-14,1848,105,1,64.06,0.16,53.8104,6,South,Online,...,4,35,Male,Clothing,4.7,Returned,Negative,8.65,SAVE10,1.8
14,2023-01-15,1747,172,4,94.14,0.15,320.0760,1,North,Cash,...,3,64,Other,Books,1.3,Returned,Neutral,19.84,FREESHIP,2.8
15,2023-01-16,1057,116,1,22.96,0.08,21.1232,2,West,Cash,...,4,47,Female,Clothing,3.8,Not Returned,Neutral,16.52,FREESHIP,4.5
16,2023-01-17,1102,187,8,19.58,0.27,114.3472,3,South,Credit Card,...,1,50,Female,Food,2.1,Not Returned,Positive,11.63,SAVE10,NaN
17,2023-01-18,1839,122,2,84.84,0.02,166.2864,4,South,Cash,...,6,24,Other,Electronics,3.6,Not Returned,Negative,8.10,SAVE10,3.6
18,2023-01-19,1103,124,8,80.62,0.12,567.5648,1,South,Cash,...,4,27,Female,Clothing,4.9,Returned,Positive,17.57,nan,1.0
19,2023-01-20,1503,111,2,72.68,0.20,116.2880,2,South,Online,...,1,33,Other,Clothing,4.7,Returned,Positive,NaN,SAVE10,4.8
20,2023-01-21,1796,109,5,16.99,0.08,78.1540,2,East,Cash,...,5,46,Female,Food,2.0,Returned,Neutral,17.23,nan,1.0
21,2023-01-22,1393,184,2,42.12,0.11,74.9736,9,South,Credit Card,...,2,53,Other,Food,3.9,Not Returned,Positive,7.42,nan,2.3
22,2023-01-23,1726,186,2,91.36,0.01,180.8928,8,West,Credit Card,...,5,25,Other,Food,2.9,Returned,Neutral,10.79,FREESHIP,4.3
23,2023-01-24,1335,177,6,57.93,0.05,330.2010,9,North,Online,...,2,23,Female,Food,3.4,Not Returned,Neutral,NaN,nan,4.1
24,2023-01-25,1824,132,5,98.54,0.18,404.0140,8,West,Online,...,3,22,Other,Books,1.1,Returned,Neutral,14.92,SAVE10,2.8
25,2023-01-26,1659,125,4,78.37,0.21,247.6492,2,West,Credit Card,...,1,23,Male,Food,4.9,Returned,Neutral,NaN,nan,NaN
26,2023-01-27,1789,130,3,39.29,0.02,115.5126,2,North,Credit Card,...,3,65,Female,Electronics,4.7,Not Returned,Neutral,12.76,nan,1.3
27,2023-01-28,1779,154,9,25.15,0.22,176.5530,8,South,Credit Card,...,6,56,Female,Food,2.6,Returned,Neutral,12.01,nan,3.5
28,2023-01-29,1970,181,7,21.71,0.02,148.9306,6,East,Online,...,3,24,Female,Electronics,4.9,Not Returned,Positive,14.88,FREESHIP,NaN
29,2023-01-30,1336,141,4,33.82,0.17,112.2824,2,South,Online,...,6,40,Female,Clothing,2.4,Returned,Neutral,NaN,FREESHIP,4.2
30,2023-01-31,1611,110,9,99.00,0.04,855.3600,7,South,Cash,...,5,31,Female,Books,3.8,Returned,Neutral,6.92,nan,1.6
31,2023-02-01,1085,198,5,69.48,0.29,246.6540,7,East,Online,...,2,28,Other,Food,5.0,Returned,Positive,16.06,nan,NaN
32,2023-02-02,1651,169,9,35.02,0.12,277.3584,8,West,Cash,...,4,65,Other,Clothing,3.3,Returned,Neutral,18.73,WELCOME5,1.2
33,2023-02-03,1515,198,1,59.88,0.07,55.6884,9,West,Online,...,5,51,Other,Food,2.1,Returned,Positive,7.18,SAVE10,4.8
34,2023-02-04,1652,154,1,47.85,0.12,42.1080,3,East,Credit Card,...,6,33,Male,Electronics,2.2,Returned,Negative,NaN,FREESHIP,3.9

In [10]:
# 4. Handling Duplicates in Pandas
# Write a Pandas program to remove duplicates rows from a DataFrame.

df = df.drop_duplicates()
df.reset_index(drop=True, inplace=True)

<div class="alert alert-warning">

**5. Handling Outliers with Z-Score Method**

**Write a Pandas program to handle outliers in a DataFrame with Z-Score method.**

</div>

In [11]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 10000.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))


duplicates = df.sample(n=5, replace=False)  # Select 5 random rows without replacement
df = pd.concat([df, duplicates], ignore_index=True)


# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1729,149,3,3622.35,0.25,8150.2875,4,South,Credit Card,...,2,67,Other,Books,4.5,Returned,Negative,6.51,FREESHIP,NaN
1,2023-01-02,1653,192,3,4684.60,0.28,10118.7360,7,South,Cash,...,6,51,Other,Clothing,3.8,Not Returned,Negative,8.35,SAVE10,NaN
2,2023-01-03,1176,193,4,6627.12,0.10,23857.6320,3,North,Online,...,6,69,Male,Books,2.7,Not Returned,Positive,8.89,FREESHIP,3.7
3,2023-01-04,1201,153,4,213.67,0.23,658.1036,2,North,Credit Card,...,3,34,Female,Clothing,4.3,Returned,Positive,NaN,SAVE10,3.8
4,2023-01-05,1053,133,6,2033.34,0.01,12078.0396,5,West,Cash,...,1,45,Female,Clothing,1.9,Not Returned,Positive,12.02,FREESHIP,2.1
5,2023-01-06,1966,168,4,8109.96,0.21,25627.4736,6,East,Online,...,6,52,Female,Food,2.1,Returned,Positive,NaN,SAVE10,4.6
6,2023-01-07,1242,179,6,4136.89,0.29,17623.1514,9,North,Cash,...,3,55,Other,Electronics,4.9,Not Returned,Positive,8.91,SAVE10,NaN
7,2023-01-08,1633,171,7,5432.41,0.28,27379.3464,9,North,Online,...,6,35,Other,Books,4.2,Not Returned,Neutral,18.39,SAVE10,NaN
8,2023-01-09,1598,128,4,1652.57,0.10,5949.2520,6,North,Cash,...,1,57,Female,Clothing,3.7,Not Returned,Negative,9.32,FREESHIP,3.0
9,2023-01-10,1554,175,3,721.19,0.20,1730.8560,3,South,Online,...,4,59,Female,Clothing,1.9,Returned,Neutral,9.66,nan,NaN
10,2023-01-11,1669,110,6,1879.09,0.12,9921.5952,7,North,Credit Card,...,4,23,Female,Clothing,2.3,Not Returned,Negative,19.77,FREESHIP,4.6
11,2023-01-12,1926,191,5,3379.54,0.04,16221.7920,3,East,Cash,...,2,69,Other,Books,2.2,Not Returned,Negative,15.66,nan,1.8
12,2023-01-13,1787,122,1,5737.47,0.01,5680.0953,8,North,Online,...,6,52,Other,Books,3.1,Not Returned,Negative,NaN,nan,1.6
13,2023-01-14,1729,150,4,7977.70,0.04,30634.3680,7,East,Credit Card,...,1,69,Other,Electronics,4.6,Returned,Neutral,7.58,SAVE10,4.8
14,2023-01-15,1571,191,5,1806.52,0.03,8761.6220,2,North,Cash,...,5,41,Male,Clothing,4.5,Not Returned,Positive,17.38,nan,3.9
15,2023-01-16,1772,134,7,2571.29,0.25,13499.2725,3,West,Online,...,5,30,Female,Clothing,2.1,Returned,Negative,18.18,SAVE10,NaN
16,2023-01-17,1633,140,2,5809.95,0.10,10457.9100,6,South,Online,...,5,45,Male,Food,3.4,Not Returned,Positive,6.58,FREESHIP,3.3
17,2023-01-18,1697,181,2,8673.06,0.05,16478.8140,4,South,Online,...,6,67,Male,Books,4.4,Returned,Neutral,10.46,nan,3.8
18,2023-01-19,1751,108,4,7611.28,0.20,24356.0960,9,West,Cash,...,6,44,Female,Food,2.2,Not Returned,Neutral,NaN,FREESHIP,NaN
19,2023-01-20,1018,136,7,3667.85,0.28,18485.9640,2,North,Credit Card,...,2,65,Other,Food,4.1,Not Returned,Neutral,10.51,nan,3.6
20,2023-01-21,1034,153,6,4057.00,0.03,23611.7400,2,East,Cash,...,1,56,Male,Books,4.3,Returned,Negative,12.27,SAVE10,1.5
21,2023-01-22,1503,151,3,9211.17,0.07,25699.1643,8,North,Online,...,2,65,Male,Books,1.8,Not Returned,Negative,14.00,WELCOME5,4.1
22,2023-01-23,1485,195,8,5929.66,0.06,44591.0432,2,North,Cash,...,5,62,Male,Clothing,4.8,Returned,Negative,11.68,nan,NaN
23,2023-01-24,1956,183,2,583.51,0.23,898.6054,7,East,Online,...,6,46,Other,Books,2.6,Returned,Neutral,18.88,FREESHIP,1.8
24,2023-01-25,1641,170,3,1094.49,0.13,2856.6189,5,North,Credit Card,...,3,44,Female,Clothing,1.6,Not Returned,Neutral,6.39,FREESHIP,1.7
25,2023-01-26,1242,109,9,1692.48,0.16,12795.1488,6,West,Cash,...,4,67,Other,Food,2.3,Returned,Positive,8.12,nan,3.2
26,2023-01-27,1550,147,6,2972.63,0.08,16408.9176,3,South,Online,...,2,59,Other,Books,4.9,Returned,Positive,7.98,nan,2.7
27,2023-01-28,1254,138,5,922.97,0.30,3230.3950,7,West,Cash,...,4,22,Female,Electronics,2.1,Not Returned,Positive,12.21,WELCOME5,2.8
28,2023-01-29,1959,190,7,1239.28,0.28,6245.9712,1,North,Credit Card,...,2,26,Male,Electronics,3.8,Returned,Neutral,14.42,nan,1.3
29,2023-01-30,1498,193,9,2884.33,0.15,22065.1245,4,South,Online,...,1,37,Male,Clothing,2.2,Returned,Negative,17.90,nan,NaN
30,2023-01-31,1907,146,2,7761.57,0.01,15367.9086,8,East,Cash,...,5,54,Female,Books,1.3,Not Returned,Positive,10.16,nan,3.1
31,2023-02-01,1712,169,9,3558.56,0.13,27863.5248,5,North,Cash,...,2,69,Female,Electronics,4.0,Returned,Neutral,17.05,nan,4.1
32,2023-02-02,1652,136,5,423.92,0.19,1716.8760,8,North,Cash,...,2,60,Other,Clothing,4.1,Returned,Positive,NaN,SAVE10,2.8
33,2023-02-03,1755,165,2,8245.87,0.07,15337.3182,7,North,Online,...,2,45,Other,Food,2.0,Not Returned,Negative,NaN,nan,NaN
34,2023-02-04,1935,114,8,9374.03,0.19,60743.7144,6,North,Online,...,6,68,Female,Electronics,2.5,Not Returned,Neutral,13.96,nan,1.1
35,2023-01-13,1787,122,1,5737.47,0.01,5680.0953,8,North,Online,...,6,52,Other,Books,3.1,Not Returned,Negative,NaN,nan,1.6
36,2023-01-22,1503,151,3,9211.17,0.07,25699.1643,8,North,Online,...,2,65,Male,Books,1.8,Not Returned,Negative,14.00,WELCOME5,4.1
37,2023-01-08,1633,171,7,5432.41,0.28,27379.3464,9,North,Online,...,6,35,Other,Books,4.2,Not Returned,Neutral,18.39,SAVE10,NaN
38,2023-01-02,1653,192,3,4684.60,0.28,10118.7360,7,South,Cash,...,6,51,Other,Clothing,3.8,Not Returned,Negative,8.35,SAVE10,NaN
39,2023-01-30,1498,193,9,2884.33,0.15,22065.1245,4,South,Online,...,1,37,Male,Clothing,2.2,Returned,Negative,17.90,nan,NaN

<div class="alert alert-success">

**Solution 05:**
</div>

In [12]:
# 5. Handling Outliers with Z-Score Method
# Write a Pandas program to handle outliers in a DataFrame with Z-Score method.

def handle_outliers_z_score(df, column):
    from scipy import stats
    z_scores = np.abs(stats.zscore(df[column]))
    threshold = 1.5
    return df[(z_scores < threshold)]

result_df = handle_outliers_z_score(df, 'price')

In [13]:
result_df

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1729,149,3,3622.35,0.25,8150.2875,4,South,Credit Card,...,2,67,Other,Books,4.5,Returned,Negative,6.51,FREESHIP,NaN
1,2023-01-02,1653,192,3,4684.60,0.28,10118.7360,7,South,Cash,...,6,51,Other,Clothing,3.8,Not Returned,Negative,8.35,SAVE10,NaN
2,2023-01-03,1176,193,4,6627.12,0.10,23857.6320,3,North,Online,...,6,69,Male,Books,2.7,Not Returned,Positive,8.89,FREESHIP,3.7
3,2023-01-04,1201,153,4,213.67,0.23,658.1036,2,North,Credit Card,...,3,34,Female,Clothing,4.3,Returned,Positive,NaN,SAVE10,3.8
4,2023-01-05,1053,133,6,2033.34,0.01,12078.0396,5,West,Cash,...,1,45,Female,Clothing,1.9,Not Returned,Positive,12.02,FREESHIP,2.1
5,2023-01-06,1966,168,4,8109.96,0.21,25627.4736,6,East,Online,...,6,52,Female,Food,2.1,Returned,Positive,NaN,SAVE10,4.6
6,2023-01-07,1242,179,6,4136.89,0.29,17623.1514,9,North,Cash,...,3,55,Other,Electronics,4.9,Not Returned,Positive,8.91,SAVE10,NaN
7,2023-01-08,1633,171,7,5432.41,0.28,27379.3464,9,North,Online,...,6,35,Other,Books,4.2,Not Returned,Neutral,18.39,SAVE10,NaN
8,2023-01-09,1598,128,4,1652.57,0.10,5949.2520,6,North,Cash,...,1,57,Female,Clothing,3.7,Not Returned,Negative,9.32,FREESHIP,3.0
9,2023-01-10,1554,175,3,721.19,0.20,1730.8560,3,South,Online,...,4,59,Female,Clothing,1.9,Returned,Neutral,9.66,nan,NaN
10,2023-01-11,1669,110,6,1879.09,0.12,9921.5952,7,North,Credit Card,...,4,23,Female,Clothing,2.3,Not Returned,Negative,19.77,FREESHIP,4.6
11,2023-01-12,1926,191,5,3379.54,0.04,16221.7920,3,East,Cash,...,2,69,Other,Books,2.2,Not Returned,Negative,15.66,nan,1.8
12,2023-01-13,1787,122,1,5737.47,0.01,5680.0953,8,North,Online,...,6,52,Other,Books,3.1,Not Returned,Negative,NaN,nan,1.6
13,2023-01-14,1729,150,4,7977.70,0.04,30634.3680,7,East,Credit Card,...,1,69,Other,Electronics,4.6,Returned,Neutral,7.58,SAVE10,4.8
14,2023-01-15,1571,191,5,1806.52,0.03,8761.6220,2,North,Cash,...,5,41,Male,Clothing,4.5,Not Returned,Positive,17.38,nan,3.9
15,2023-01-16,1772,134,7,2571.29,0.25,13499.2725,3,West,Online,...,5,30,Female,Clothing,2.1,Returned,Negative,18.18,SAVE10,NaN
16,2023-01-17,1633,140,2,5809.95,0.10,10457.9100,6,South,Online,...,5,45,Male,Food,3.4,Not Returned,Positive,6.58,FREESHIP,3.3
18,2023-01-19,1751,108,4,7611.28,0.20,24356.0960,9,West,Cash,...,6,44,Female,Food,2.2,Not Returned,Neutral,NaN,FREESHIP,NaN
19,2023-01-20,1018,136,7,3667.85,0.28,18485.9640,2,North,Credit Card,...,2,65,Other,Food,4.1,Not Returned,Neutral,10.51,nan,3.6
20,2023-01-21,1034,153,6,4057.00,0.03,23611.7400,2,East,Cash,...,1,56,Male,Books,4.3,Returned,Negative,12.27,SAVE10,1.5
22,2023-01-23,1485,195,8,5929.66,0.06,44591.0432,2,North,Cash,...,5,62,Male,Clothing,4.8,Returned,Negative,11.68,nan,NaN
23,2023-01-24,1956,183,2,583.51,0.23,898.6054,7,East,Online,...,6,46,Other,Books,2.6,Returned,Neutral,18.88,FREESHIP,1.8
24,2023-01-25,1641,170,3,1094.49,0.13,2856.6189,5,North,Credit Card,...,3,44,Female,Clothing,1.6,Not Returned,Neutral,6.39,FREESHIP,1.7
25,2023-01-26,1242,109,9,1692.48,0.16,12795.1488,6,West,Cash,...,4,67,Other,Food,2.3,Returned,Positive,8.12,nan,3.2
26,2023-01-27,1550,147,6,2972.63,0.08,16408.9176,3,South,Online,...,2,59,Other,Books,4.9,Returned,Positive,7.98,nan,2.7
27,2023-01-28,1254,138,5,922.97,0.30,3230.3950,7,West,Cash,...,4,22,Female,Electronics,2.1,Not Returned,Positive,12.21,WELCOME5,2.8
28,2023-01-29,1959,190,7,1239.28,0.28,6245.9712,1,North,Credit Card,...,2,26,Male,Electronics,3.8,Returned,Neutral,14.42,nan,1.3
29,2023-01-30,1498,193,9,2884.33,0.15,22065.1245,4,South,Online,...,1,37,Male,Clothing,2.2,Returned,Negative,17.90,nan,NaN
30,2023-01-31,1907,146,2,7761.57,0.01,15367.9086,8,East,Cash,...,5,54,Female,Books,1.3,Not Returned,Positive,10.16,nan,3.1
31,2023-02-01,1712,169,9,3558.56,0.13,27863.5248,5,North,Cash,...,2,69,Female,Electronics,4.0,Returned,Neutral,17.05,nan,4.1
32,2023-02-02,1652,136,5,423.92,0.19,1716.8760,8,North,Cash,...,2,60,Other,Clothing,4.1,Returned,Positive,NaN,SAVE10,2.8
33,2023-02-03,1755,165,2,8245.87,0.07,15337.3182,7,North,Online,...,2,45,Other,Food,2.0,Not Returned,Negative,NaN,nan,NaN
35,2023-01-13,1787,122,1,5737.47,0.01,5680.0953,8,North,Online,...,6,52,Other,Books,3.1,Not Returned,Negative,NaN,nan,1.6
37,2023-01-08,1633,171,7,5432.41,0.28,27379.3464,9,North,Online,...,6,35,Other,Books,4.2,Not Returned,Neutral,18.39,SAVE10,NaN
38,2023-01-02,1653,192,3,4684.60,0.28,10118.7360,7,South,Cash,...,6,51,Other,Clothing,3.8,Not Returned,Negative,8.35,SAVE10,NaN
39,2023-01-30,1498,193,9,2884.33,0.15,22065.1245,4,South,Online,...,1,37,Male,Clothing,2.2,Returned,Negative,17.90,nan,NaN

<div class="alert alert-warning">

**6. Normalizing Data with Min-Max Scaling**

**Write a Pandas program that normalizes data with Min-Max scaling.**

</div>

In [14]:
# Create date range
date_range = pd.date_range(start='2023-01-01', periods=35, freq='D')

# Create a dictionary of data
data = {
    'date': date_range,
    'customer_id': np.random.randint(1000, 2000, size=35),
    'product_id': np.random.randint(100, 200, size=35),
    'quantity': np.random.randint(1, 10, size=35),
    'price': np.round(np.random.uniform(10.0, 10000.0, size=35), 2),
    'discount': np.round(np.random.uniform(0, 0.3, size=35), 2),
    'revenue': lambda df: df['quantity'] * df['price'] * (1 - df['discount']),
    'store_id': np.random.randint(1, 10, size=35),
    'region': np.random.choice(['North', 'South', 'East', 'West'], size=35),
    'payment_method': np.random.choice(['Credit Card', 'Cash', 'Online'], size=35),
    'is_member': np.random.choice([True, False], size=35),
    'delivery_days': np.random.randint(1, 7, size=35),
    'customer_age': np.random.randint(18, 70, size=35),
    'gender': np.random.choice(['Male', 'Female', 'Other'], size=35),
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Food'], size=35),
    'rating': np.round(np.random.uniform(1.0, 5.0, size=35), 1),
    'return_status': np.random.choice(['Returned', 'Not Returned'], size=35),
    'feedback': np.random.choice(['Positive', 'Neutral', 'Negative'], size=35),
}

# Create DataFrame
df = pd.DataFrame(data)

# Compute revenue using the lambda function above
df['revenue'] = df['quantity'] * df['price'] * (1 - df['discount'])

# Add 'shipping_cost' with some missing values
df['shipping_cost'] = np.where(np.random.rand(len(df)) < 0.2, np.nan, np.round(np.random.uniform(5.0, 20.0, size=len(df)), 2))

# Add 'coupon_code' with some missing values
coupon_options = ['SAVE10', 'WELCOME5', 'FREESHIP', np.nan]
df['coupon_code'] = np.random.choice(coupon_options, size=len(df), p=[0.2, 0.2, 0.2, 0.4])

# Add 'delivery_rating' with some missing values
df['delivery_rating'] = np.where(np.random.rand(len(df)) < 0.3, np.nan, np.round(np.random.uniform(1.0, 5.0, size=len(df)), 1))


duplicates = df.sample(n=5, replace=False)  # Select 5 random rows without replacement
df = pd.concat([df, duplicates], ignore_index=True)


# Display the updated DataFrame
display(df)

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1738,165,5,2575.21,0.23,9914.5585,2,West,Cash,...,2,31,Other,Books,3.3,Returned,Negative,5.24,FREESHIP,4.9
1,2023-01-02,1629,168,7,9530.91,0.08,61379.0604,7,South,Credit Card,...,2,48,Male,Electronics,2.5,Returned,Positive,19.58,SAVE10,3.5
2,2023-01-03,1322,184,1,8626.80,0.25,6470.1000,9,North,Cash,...,5,64,Male,Electronics,1.9,Returned,Negative,15.84,FREESHIP,NaN
3,2023-01-04,1498,179,8,8114.23,0.22,50632.7952,9,East,Online,...,5,24,Male,Food,1.9,Returned,Neutral,15.59,WELCOME5,1.5
4,2023-01-05,1517,168,1,1013.42,0.10,912.0780,1,North,Online,...,1,57,Female,Electronics,1.0,Returned,Negative,8.32,WELCOME5,3.7
5,2023-01-06,1017,119,6,2895.39,0.23,13376.7018,2,South,Online,...,4,48,Female,Clothing,1.8,Not Returned,Positive,8.34,nan,1.2
6,2023-01-07,1848,122,2,3019.76,0.19,4892.0112,6,West,Credit Card,...,4,47,Female,Books,5.0,Not Returned,Neutral,6.18,FREESHIP,4.6
7,2023-01-08,1092,198,3,3991.89,0.18,9820.0494,5,East,Credit Card,...,3,50,Other,Books,1.7,Returned,Positive,NaN,nan,2.3
8,2023-01-09,1149,181,1,548.10,0.13,476.8470,1,South,Online,...,2,53,Female,Electronics,4.2,Returned,Neutral,14.07,SAVE10,3.0
9,2023-01-10,1244,144,8,3367.05,0.21,21279.7560,9,South,Credit Card,...,3,65,Male,Books,1.3,Not Returned,Neutral,11.35,nan,2.1
10,2023-01-11,1805,155,3,3148.48,0.23,7272.9888,9,West,Credit Card,...,1,55,Female,Books,2.0,Returned,Positive,16.28,nan,1.9
11,2023-01-12,1804,121,1,5795.70,0.11,5158.1730,5,South,Cash,...,2,52,Male,Books,4.0,Returned,Positive,NaN,SAVE10,1.8
12,2023-01-13,1630,158,9,3130.80,0.18,23105.3040,6,East,Credit Card,...,4,36,Male,Electronics,3.8,Returned,Positive,18.69,WELCOME5,2.6
13,2023-01-14,1183,116,7,1935.28,0.25,10160.2200,9,East,Credit Card,...,6,62,Male,Food,2.1,Returned,Neutral,10.74,FREESHIP,1.4
14,2023-01-15,1768,197,8,8395.96,0.21,53062.4672,9,East,Cash,...,2,51,Female,Electronics,2.7,Returned,Positive,18.75,FREESHIP,1.4
15,2023-01-16,1182,128,8,7691.63,0.14,52918.4144,1,South,Cash,...,5,29,Female,Electronics,2.7,Returned,Negative,NaN,FREESHIP,2.6
16,2023-01-17,1688,171,3,598.45,0.08,1651.7220,9,West,Credit Card,...,3,19,Female,Books,1.5,Returned,Neutral,10.96,nan,NaN
17,2023-01-18,1256,162,7,2109.45,0.10,13289.5350,7,South,Online,...,3,60,Female,Books,3.8,Returned,Neutral,NaN,FREESHIP,2.2
18,2023-01-19,1939,137,9,8219.84,0.04,71019.4176,2,West,Credit Card,...,6,60,Male,Clothing,4.7,Not Returned,Negative,17.54,WELCOME5,1.1
19,2023-01-20,1178,110,7,545.59,0.05,3628.1735,7,West,Online,...,1,56,Female,Electronics,4.6,Not Returned,Negative,NaN,nan,NaN
20,2023-01-21,1407,109,7,5019.25,0.05,33378.0125,4,North,Online,...,2,49,Female,Clothing,3.5,Not Returned,Neutral,13.01,SAVE10,NaN
21,2023-01-22,1995,133,6,2427.60,0.23,11215.5120,2,West,Credit Card,...,2,39,Other,Food,2.5,Returned,Negative,16.94,nan,NaN
22,2023-01-23,1480,156,4,223.34,0.21,705.7544,5,West,Online,...,6,19,Female,Books,3.7,Not Returned,Positive,NaN,WELCOME5,1.3
23,2023-01-24,1961,160,9,9376.12,0.07,78478.1244,3,South,Cash,...,3,31,Male,Food,1.7,Not Returned,Negative,NaN,FREESHIP,3.8
24,2023-01-25,1418,121,9,5448.91,0.04,47078.5824,1,East,Cash,...,6,47,Female,Books,5.0,Not Returned,Negative,NaN,nan,NaN
25,2023-01-26,1321,154,6,2733.83,0.07,15254.7714,3,East,Cash,...,5,33,Other,Books,4.2,Not Returned,Neutral,NaN,nan,2.6
26,2023-01-27,1277,158,1,2005.06,0.22,1563.9468,8,East,Online,...,6,30,Female,Clothing,3.5,Not Returned,Positive,14.63,FREESHIP,3.3
27,2023-01-28,1798,162,9,119.58,0.12,947.0736,1,West,Cash,...,3,63,Other,Books,1.5,Not Returned,Positive,8.00,WELCOME5,NaN
28,2023-01-29,1023,143,8,123.24,0.02,966.2016,8,North,Credit Card,...,1,33,Other,Food,4.2,Not Returned,Neutral,9.18,SAVE10,4.0
29,2023-01-30,1826,189,2,8247.29,0.01,16329.6342,7,North,Online,...,6,52,Female,Books,2.2,Not Returned,Neutral,NaN,WELCOME5,3.5
30,2023-01-31,1858,127,7,5197.82,0.05,34565.5030,8,West,Online,...,2,58,Male,Electronics,3.6,Returned,Neutral,7.43,nan,NaN
31,2023-02-01,1388,167,7,529.36,0.24,2816.1952,1,West,Credit Card,...,2,33,Other,Electronics,4.7,Not Returned,Negative,7.37,FREESHIP,NaN
32,2023-02-02,1200,185,8,9890.85,0.06,74379.1920,6,West,Online,...,6,40,Other,Books,2.6,Returned,Neutral,17.40,WELCOME5,4.6
33,2023-02-03,1744,197,1,1084.73,0.21,856.9367,1,West,Cash,...,4,18,Female,Books,2.6,Not Returned,Neutral,NaN,WELCOME5,NaN
34,2023-02-04,1190,198,3,2206.45,0.22,5163.0930,6,North,Online,...,4,66,Female,Electronics,2.5,Returned,Neutral,14.03,nan,1.6
35,2023-01-21,1407,109,7,5019.25,0.05,33378.0125,4,North,Online,...,2,49,Female,Clothing,3.5,Not Returned,Neutral,13.01,SAVE10,NaN
36,2023-01-15,1768,197,8,8395.96,0.21,53062.4672,9,East,Cash,...,2,51,Female,Electronics,2.7,Returned,Positive,18.75,FREESHIP,1.4
37,2023-01-23,1480,156,4,223.34,0.21,705.7544,5,West,Online,...,6,19,Female,Books,3.7,Not Returned,Positive,NaN,WELCOME5,1.3
38,2023-01-31,1858,127,7,5197.82,0.05,34565.5030,8,West,Online,...,2,58,Male,Electronics,3.6,Returned,Neutral,7.43,nan,NaN
39,2023-01-13,1630,158,9,3130.80,0.18,23105.3040,6,East,Credit Card,...,4,36,Male,Electronics,3.8,Returned,Positive,18.69,WELCOME5,2.6

<div class="alert alert-success">

**Solution 06:**
</div>

In [15]:
# 6. Normalizing Data with Min-Max Scaling
# Write a Pandas program that normalizes data with Min-Max scaling.

def normalize_min_max(df, column):
    min_val = df[column].min()
    max_val = df[column].max()
    df[column] = (df[column] - min_val) / (max_val - min_val)
    return df

result_df = normalize_min_max(df.copy(), 'price')

result_df

,date,customer_id,product_id,quantity,price,discount,revenue,store_id,region,payment_method,...,delivery_days,customer_age,gender,product_category,rating,return_status,feedback,shipping_cost,coupon_code,delivery_rating
0,2023-01-01,1738,165,5,0.251311,0.23,9914.5585,2,West,Cash,...,2,31,Other,Books,3.3,Returned,Negative,5.24,FREESHIP,4.9
1,2023-01-02,1629,168,7,0.963163,0.08,61379.0604,7,South,Credit Card,...,2,48,Male,Electronics,2.5,Returned,Positive,19.58,SAVE10,3.5
2,2023-01-03,1322,184,1,0.870636,0.25,6470.1000,9,North,Cash,...,5,64,Male,Electronics,1.9,Returned,Negative,15.84,FREESHIP,NaN
3,2023-01-04,1498,179,8,0.818179,0.22,50632.7952,9,East,Online,...,5,24,Male,Food,1.9,Returned,Neutral,15.59,WELCOME5,1.5
4,2023-01-05,1517,168,1,0.091476,0.10,912.0780,1,North,Online,...,1,57,Female,Electronics,1.0,Returned,Negative,8.32,WELCOME5,3.7
5,2023-01-06,1017,119,6,0.284079,0.23,13376.7018,2,South,Online,...,4,48,Female,Clothing,1.8,Not Returned,Positive,8.34,nan,1.2
6,2023-01-07,1848,122,2,0.296807,0.19,4892.0112,6,West,Credit Card,...,4,47,Female,Books,5.0,Not Returned,Neutral,6.18,FREESHIP,4.6
7,2023-01-08,1092,198,3,0.396295,0.18,9820.0494,5,East,Credit Card,...,3,50,Other,Books,1.7,Returned,Positive,NaN,nan,2.3
8,2023-01-09,1149,181,1,0.043855,0.13,476.8470,1,South,Online,...,2,53,Female,Electronics,4.2,Returned,Neutral,14.07,SAVE10,3.0
9,2023-01-10,1244,144,8,0.332349,0.21,21279.7560,9,South,Credit Card,...,3,65,Male,Books,1.3,Not Returned,Neutral,11.35,nan,2.1
10,2023-01-11,1805,155,3,0.309980,0.23,7272.9888,9,West,Credit Card,...,1,55,Female,Books,2.0,Returned,Positive,16.28,nan,1.9
11,2023-01-12,1804,121,1,0.580899,0.11,5158.1730,5,South,Cash,...,2,52,Male,Books,4.0,Returned,Positive,NaN,SAVE10,1.8
12,2023-01-13,1630,158,9,0.308171,0.18,23105.3040,6,East,Credit Card,...,4,36,Male,Electronics,3.8,Returned,Positive,18.69,WELCOME5,2.6
13,2023-01-14,1183,116,7,0.185820,0.25,10160.2200,9,East,Credit Card,...,6,62,Male,Food,2.1,Returned,Neutral,10.74,FREESHIP,1.4
14,2023-01-15,1768,197,8,0.847012,0.21,53062.4672,9,East,Cash,...,2,51,Female,Electronics,2.7,Returned,Positive,18.75,FREESHIP,1.4
15,2023-01-16,1182,128,8,0.774930,0.14,52918.4144,1,South,Cash,...,5,29,Female,Electronics,2.7,Returned,Negative,NaN,FREESHIP,2.6
16,2023-01-17,1688,171,3,0.049008,0.08,1651.7220,9,West,Credit Card,...,3,19,Female,Books,1.5,Returned,Neutral,10.96,nan,NaN
17,2023-01-18,1256,162,7,0.203645,0.10,13289.5350,7,South,Online,...,3,60,Female,Books,3.8,Returned,Neutral,NaN,FREESHIP,2.2
18,2023-01-19,1939,137,9,0.828987,0.04,71019.4176,2,West,Credit Card,...,6,60,Male,Clothing,4.7,Not Returned,Negative,17.54,WELCOME5,1.1
19,2023-01-20,1178,110,7,0.043598,0.05,3628.1735,7,West,Online,...,1,56,Female,Electronics,4.6,Not Returned,Negative,NaN,nan,NaN
20,2023-01-21,1407,109,7,0.501436,0.05,33378.0125,4,North,Online,...,2,49,Female,Clothing,3.5,Not Returned,Neutral,13.01,SAVE10,NaN
21,2023-01-22,1995,133,6,0.236205,0.23,11215.5120,2,West,Credit Card,...,2,39,Other,Food,2.5,Returned,Negative,16.94,nan,NaN
22,2023-01-23,1480,156,4,0.010619,0.21,705.7544,5,West,Online,...,6,19,Female,Books,3.7,Not Returned,Positive,NaN,WELCOME5,1.3
23,2023-01-24,1961,160,9,0.947322,0.07,78478.1244,3,South,Cash,...,3,31,Male,Food,1.7,Not Returned,Negative,NaN,FREESHIP,3.8
24,2023-01-25,1418,121,9,0.545408,0.04,47078.5824,1,East,Cash,...,6,47,Female,Books,5.0,Not Returned,Negative,NaN,nan,NaN
25,2023-01-26,1321,154,6,0.267545,0.07,15254.7714,3,East,Cash,...,5,33,Other,Books,4.2,Not Returned,Neutral,NaN,nan,2.6
26,2023-01-27,1277,158,1,0.192962,0.22,1563.9468,8,East,Online,...,6,30,Female,Clothing,3.5,Not Returned,Positive,14.63,FREESHIP,3.3
27,2023-01-28,1798,162,9,0.000000,0.12,947.0736,1,West,Cash,...,3,63,Other,Books,1.5,Not Returned,Positive,8.00,WELCOME5,NaN
28,2023-01-29,1023,143,8,0.000375,0.02,966.2016,8,North,Credit Card,...,1,33,Other,Food,4.2,Not Returned,Neutral,9.18,SAVE10,4.0
29,2023-01-30,1826,189,2,0.831797,0.01,16329.6342,7,North,Online,...,6,52,Female,Books,2.2,Not Returned,Neutral,NaN,WELCOME5,3.5
30,2023-01-31,1858,127,7,0.519711,0.05,34565.5030,8,West,Online,...,2,58,Male,Electronics,3.6,Returned,Neutral,7.43,nan,NaN
31,2023-02-01,1388,167,7,0.041937,0.24,2816.1952,1,West,Credit Card,...,2,33,Other,Electronics,4.7,Not Returned,Negative,7.37,FREESHIP,NaN
32,2023-02-02,1200,185,8,1.000000,0.06,74379.1920,6,West,Online,...,6,40,Other,Books,2.6,Returned,Neutral,17.40,WELCOME5,4.6
33,2023-02-03,1744,197,1,0.098774,0.21,856.9367,1,West,Cash,...,4,18,Female,Books,2.6,Not Returned,Neutral,NaN,WELCOME5,NaN
34,2023-02-04,1190,198,3,0.213572,0.22,5163.0930,6,North,Online,...,4,66,Female,Electronics,2.5,Returned,Neutral,14.03,nan,1.6
35,2023-01-21,1407,109,7,0.501436,0.05,33378.0125,4,North,Online,...,2,49,Female,Clothing,3.5,Not Returned,Neutral,13.01,SAVE10,NaN
36,2023-01-15,1768,197,8,0.847012,0.21,53062.4672,9,East,Cash,...,2,51,Female,Electronics,2.7,Returned,Positive,18.75,FREESHIP,1.4
37,2023-01-23,1480,156,4,0.010619,0.21,705.7544,5,West,Online,...,6,19,Female,Books,3.7,Not Returned,Positive,NaN,WELCOME5,1.3
38,2023-01-31,1858,127,7,0.519711,0.05,34565.5030,8,West,Online,...,2,58,Male,Electronics,3.6,Returned,Neutral,7.43,nan,NaN
39,2023-01-13,1630,158,9,0.308171,0.18,23105.3040,6,East,Credit Card,...,4,36,Male,Electronics,3.8,Returned,Positive,18.69,WELCOME5,2.6